### ISSUE TITLE
Tween - Odd behavior with Tween Set end values

### ISSUE THREAD

**Issue by broknecho** [Scirra/Construct-bugs#3683]
## Problem description

The use of Tween Set End Values is not clear and possible has odd behavior.  Using the Tween Set End Values while a position tween is running seems like the right use of this action but it changes the current position oddly in this example.

## Attach a .c3p

[Tween example error.zip](https://github.com/Scirra/Construct-3-bugs/files/4272503/Tween.example.error.zip)

## Steps to reproduce

1. Open attached project and run it
2. Touch the layout to start the tween
3. While tween is running, click again to set the new END values of the position tween

## Observed result

When you click to reset the end values, the position of the Sprite jumps slightly in either X or Y depending on where you click.

## Expected result

New END values set and have the tween smoothly adjust to those new values based on it's current progress/remaining time.

## More details
I could be using this behavior wrong but the manual doesn't specify a good use case for this action.  If it's by design, maybe having a use of it in the `Tween example` project or manual would help.

**Affected browsers/platforms:** Tested in Chrome

**First affected release:** 182.4 Stable

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 80.0.3987.122
Browser engine: Chromium
Browser architecture: 64-bit
Context: browser
Operating system: Windows
Operating system version: 10
Operating system architecture: 64-bit
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
C3 release: r182.4 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 182 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc.
Renderer: ANGLE (NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_filter_anisotropic
KHR_parallel_shader_compile
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is a difficult issue to fully fix.

The basic use case of a tween using a linear ease is easy enough.

The problems arise when a different easing function is used.  Changing the ending value of a playing tween means that a new easing function needs to be generated on the spot for a seamless transition to the new end point.

If a new easing function is not generated, what will happen is that it will look like the tween is re-starting from it's new starting position to the new ending position. The most obvious case would be using a **In Back** easing function. Each time a new ending position is set, the tween would do the little back motion from it's current position to the new ending one.

In the mean time I will do the quick fix.

**Comment by broknecho** [comment]
@DiegoScirra yeah totally agree and I can't really find a use case for that action.

Do you know what it is even used for?  From my understanding, in order to set the `"initial"` end values of a tween, you have to use the `Tween (1 or 2 properties)` action.  This would then `Start` the tween.  And if you can't change the end values while a tween is playing, what is the purpose of that `Set end values` action?

I'm almost thinking that action should just be removed?  Maybe I'm missing something though about how to start a tween using that `Set end values` action?

**Comment by DiegoScirra** [comment]
To to be honest, when I implemented this, I thought people might want to change the end value of a tween as it was playing, for what reason, I do not know. It seems I underestimated the complexity of the action thought.

This is the kind of feature that makes me want to remove them completely, but now it is not possible, as someone out there, might be using it for something.

I will keep the issue open until I get around to fixing it, I have an idea of how to do it, it is not simple  thought.

**Comment by broknecho** [comment]
Totally know what you mean.  I appreciate the insight and I'm not using this action anyways so no blockers here.  Scirra has an unbelievable record for backwards compatibility so I can see why it's left in there.

Thanks a lot for taking a look and just figured I'd report it as it was a little weird from my understanding.

**Comment by JGustavoChico** [comment]
This thread was really useful! 
Having this exact issue, I'm always fighting with the Tween behavior for stuff like spawning an object, setting it's size and making it go back to it's original values with clean code. Tried to give this action an use by setting the tween values before changing it's size and then starting the tween, but it's no use. Pretty frustrating! But I think this behavior is getting close to being amazing! 
Thanks a lot for your work.

**Comment by AshleyScirra** [comment]
Reviewing some older issues and this one looks like it's working better in r354, so closing.
