### ISSUE TITLE
Error with Game Center object

### ISSUE THREAD

**Issue by Bootfit** [Scirra/Construct-bugs#3913]
## Problem description

The Game Center object is installed.

1. If the user is logged in to the game center and tries to submit a score it submits fine and then shows the leaderboard.
2. If the user is not logged in, authorisation fails and a popup message appears telling them to login. The user closes the popup by pressing a close button.
3. Both these actions work fine once.
4. If the user then presses the Leaderboard button again, nothing happens.
5. If the user then returns to the phone home screen (not closing/ending the app) then returns to the app the leaderboard popup then appears.

## Attach a .c3p

[leaderboard popup error.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/4724276/leaderboard.popup.error.c3p.zip)

## Steps to reproduce

1. Go to event sheet and enter an ID for a test leaderboard.
2. Build the app in Xcode and deploy to iOS device.
3. Launch app and press the Boards button.
4. Depending on your Game Center configuration (either your logged in or not) you'll either post to and then display the leaderboard, or you'll get a popup message telling you how to log in to Game Center.
5. Either close the leaderboard or the popup message.
6. Press the Boards button again and nothin happens.
7. Leave the app (but do not close it) and go to the phone home screen.
8. Return to the app and the leaderboard or popup will now appear.
 
## Observed result

Nothing happens when you press the Board button a second time. Only when you leave the app and then return does the appropriate action run.

## Expected result

Each time the Board button is pressed it should carry out the appropriate action immediately.

## More details

**Affected browsers/platforms:** iOS

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Browser: Chrome
Browser version: 83.0.4103.61
Browser engine: Chromium
Browser architecture: (unknown)
Context: browser
Operating system: Mac OS X
Operating system version: 10.15_5
Operating system architecture: (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
C3 release: r197.2 (stable)
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 857 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Intel Inc.
Renderer: Intel HD Graphics 4000 OpenGL Engine
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

Ogg Opus (audio/ogg; codecs=opus)
WebM Opus (audio/webm; codecs=opus)
Ogg Vorbis (audio/ogg; codecs=vorbis)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by karimlahbach** [comment]
Hi Ashley i want to add the game center to my game but it seem like is not open after closing it
is there is any solution for this ?
