### ISSUE TITLE
r276 cascade sublayers button missing in dark theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#5303]
The button that cascades/shows child layers in the LAYERS panel is missing in the default dark theme. 
It does show up in the default light theme.

**Comment by AshleyScirra** [comment]
This confused me at first, so to be clear, this refers to the expand/collapse arrows beside layers that have sub-layers. Here's how they appear in the default theme:
![sub-layers-expand](https://user-images.githubusercontent.com/768723/147947897-20264e36-07e8-47bc-97fc-bee2b87283d7.png)
The design of the dark/light themes however intentionally adjusts the appearance of the layers bar and hides these buttons, as the theme design pre-dates sub-layers. Simply showing the buttons again looks odd, so the design will probably have to be revised to suit them. I think the dark/light themes should be reverted to the standard arrangement of the Layers Bar.

**Comment by F3der1co** [comment]
yea, this is what I am refering to, my wording is indeed a bit unclear, sry.
Mhm I see, personally I would prefer the default light and dark themes to just be palette swapped version of the non themed version to avoid stuff like this from happening in the future.

**Comment by F3der1co** [comment]
I now tested the no themed version of c3 for a bit and I don't like it. Maybe it's just because I have become so used to the dark theme, but the dark theme it is so much cleaner and has better ux imo. 
So I don't want that to become a palette swapped version of the no themed version.
It's weird that in all promo the dark theme is shown, but that's not the real default ui/ux + not the one that gets updated with each patch? I always though it was the one to use.

**Comment by F3der1co** [comment]
I want to do a follow up on this as this is something that is quite important imo, for the following reason:
Without the cascade arrow it is impossible to tell that a collapsed layer has any sub-layers.
So this could potentially make it almost impossible to find stuff because the user might not even know that there is a sub-layer somewhere. If the person realizes they would have to double click every layer to see if there are sub-layers.

**Comment by NickR-Git** [comment]
Any updates on adding this to the dark UI?

**Comment by AshleyScirra** [comment]
I've just reverted the Layers Bar to the same layout as the default theme in both the dark and light themes for the next release cycle (the change will be in the first beta release after the next stable release).
