### ISSUE TITLE
iOS GameCenter action Request Achievement doesn't seem to trigger

### ISSUE THREAD

**Issue by lukasinspace** [Scirra/Construct-bugs#5624]
## Problem description

When GameCenter action > Request Achievement is fired, nothing happens. 

## Steps to reproduce

Testing this bug requires at least one achievement to be set up in App Store Connect.
In C3
1. On start of app > Game Center > authenticate user.
2. Attach action to a button for example to trigger action on touched > Request Achievements.

Interface showing Game Center achievements, both locked and unlocked should appear.

## Observed result

Nothing happens, regardless of whether any achievements have been unlocked or not, GameCenter interface to display achievements does not display. 

## Expected result
What should happen is an interface should display to show the user the list of Achievements both locked and unlocked. 

Note that this works with Leaderboards. The equivalent action to show leaderboards does work. The GameCenter interface opens and leaderboards are displayed. The same needs to work for Achievements. 

## More details

Note that there are some discrepencies with the documentation for this.
In the C3 documentation for GameCenter plugin. The description for 'Request Achievements' action says:
"_Request a list of **available** and **completed** achievements._ " (This is the preferred result. The action should trigger to show all  locked and unlocked Achievements.)

Contradicting this, the description in the C3 interface, when adding the Request Achievements action says: 
"_Request a list of achievements the user has **completed**._" This seems to imply that perhaps this action will only trigger if the user has completed at least 1 achievement? And may not trigger if no achievements are completed?

Note that, achievement submission does seem to work. When I call action 'Report Achievement' the recehievement does get submitted and recorded correctly. However there is no associated acknowledgement of this in the app. No pop-up is displayed by GameCenter plugin to say 'achievement unlocked' or something, like happens with GooglePlay plugin... Not sure if this is a related bug?
But I know achievements do get reported correctly, because when I trigge raction 'Show Leaderboard', a GameCenter interface displays and I can navigate from leaderboards to view achievements and it shows the unlocked achievement. 

So the main problem here is that Request Achievmenets action does not open a GameCenter user interface to display the list of locked and unlocked achievements. 
I think I need this to work because it's something that will get picked up in App Store review process... 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - please take a look - just a heads up some of the libraries we use may be a bit out of date now so could probably do with updating dependencies.

**Comment by DiegoScirra** [comment]
@lukasinspace  Are the corresponding triggers executed after the action? I mean **on achievement list received** or on **achievement list error**.

**Comment by lukasinspace** [comment]
Ok thanks Diego. I was assuming it would work the same way as Google Play, and just show a UI listing achievements, locked and unlocked. 

The Achievement UI is accessible. The action 'Show Leaderboard' takes the player to a GameCenter UI that shows a specific leaderboard. And from there the player can navigate the Game Center UI back to see a list of achievements that can be unlocked.

 I was hoping there was an option so the player can open the same UI but directly open achievements.. or maybe open the top level of the player's Game Center account, something like that.

**Comment by lukasinspace** [comment]
Sorry to answer your question. I'm not sure if those triggers fire: 'on achievement list received'. I'll check tmoro. 1am here.

**Comment by DiegoScirra** [comment]
Ok, no problem.

The reality is that the Cordova plugin C3 is using states that it supports iOS versions 7 and 8.... current version 15. What you expect the plugin to do is sensible, but will need further development rather than a quick fix.

**Comment by lukasinspace** [comment]
Ok well, is this something you guys feel is worth updating? Or will you leave the plugin as-is? 

Worst case if the plugin doesn't get an update, I can alter my game's UI so that the button to open achievements opens GameCenter leaderboards, since that works, and rely on player navigating to their achievements themselves.  I just have to hope it can pass review..

**Comment by lukasinspace** [comment]
@DiegoScirra Yes the triggers do fire as expected. **On achievement list received** is triggered immediately after action **Request achievement list**.

**Comment by lukasinspace** [comment]
@DiegoScirra what your thoughts are about this in terms of timeframe?
If you guys were going update / enhance the GameCenter plugin when would that be done do you think?
Asking because I'm deciding if I should wait for the plugin to be updated, or make some changes in my game and go ahead and submit for review now. Im at the point where I was about to submit the game for review on iTunes, but I can hold off.

**Comment by DiegoScirra** [comment]
@lukasinspace I wouldn't wait.

I don't know how long it will take to add this feature, we will do something about it eventually but it doesn't have a high priority. It's probably better for you to do with what is available rather than wait for us.

**Comment by AshleyScirra** [comment]
@DiegoScirra - I've also assigned issue #3913 to you for review when you get round to this.

**Comment by AshleyScirra** [comment]
As of r413 the Game Center plugin is deprecated, so closing this issue.
