### ISSUE TITLE
Timeline Pingpong 

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-bugs#6006]
## Problem description
if I activate the pingpong option for timelines, the preview on the Timline works great, but in the preview of the project I somehow couldnt make it work. 

## Attach a .c3p
[Timeline_Pingpong.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9382568/Timeline_Pingpong.c3p.zip)

## Steps to reproduce

1.the project has two timelines with pingpong activated, take a look at them, play them in the Timelinebar
2.now preview the project and see the final result
3.activate Loop in Timeline B, preview

## Observed result
the pingpong doesn't work, not in step 2 nor in step 3

## Expected result

pingpong working
## More details

**Affected browsers/platforms:** 
working on mac in chrome, r306

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r306 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 241 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
All the actions are in a block without a condition, so I think they are being executed continually. If you put them inside a **on start of layout** trigger so they only happens once, everything works as expected.

Will look into it further, even though it's a strange use case, it should work.

**Comment by bubbblebub** [comment]
Ouch yes I see, I stumbled on this as I am trying to make another Bugreport, I wasn't looking carefully. Sorry to bother you with something that doesn't make sense, feel free to just close this Bug.

**Comment by DiegoScirra** [comment]
It is possible to fix this, but it's tricky and since it's a rather unusual use case, I'll leave it for sometime later in the future.

**Comment by DiegoScirra** [comment]
I finally got some time to look at old issue and after looking at this more carefully I don't think it's worth fixing it and I am not even sure what the correct behaviour should be.

The timeline scheduling system works properly, even if you spam it with playback requests.

In this particular example the timelines are using the ping pong setting too. Under the hood ping pong timelines modify the playback rate to go back and forth by changing the sign, negative playback rates already make a timeline go backwards, so the ping pong setting uses that behaviour. The problem in here is the playback rate is forced to a positive number every tick, and that messes up the ping pong state.

It's not really possible to decide what the correct thing to do at all times, so I rather just leave this as is and recommend not to do what the example does, and make changes only when needed rather than continuously.
