### ISSUE TITLE
Timeline Dublicate

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-bugs#6009]
## Problem description

I found out that a timeline that I dublicated just for safety reasons, then didnt use (play), still had an influence on my animation. Making this Bugreport showed me a weird influence of "Timeline- Set Time to" action on the whole animation.

## Attach a .c3p
[Timeline_Dublicate_v2.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/9383127/Timeline_Dublicate_v2.c3p.zip)

## Steps to reproduce

1.Preview the project, take a look at the length of the blue sprite
2.now deactivate "set Time "" to 0"
3.repeat step 1
4.dublicate Timeline A
5.repeat step 1
6.activate  "set Time "" to 0"
7.repeat step 1

## Observed result
Step1: Blue sprite has size of the Layout view, looks as intended
Step2/3: Blue sprite is shorter
Step4/5: Blue sprite has same lenght as in step 2/3
Step6/7: Blue sprite is longer than in step 1. the first key of the dublicated timeline influences the size of the sprite

## Expected result

no changes in size when "set Time to 0" is deactivated/activated. No change in size when Timeline is dublicated and not playing (happens only if "set Time "" to 0" is activated)
## More details

**Affected browsers/platforms:** 
tested in chrome on mac, r306

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r306 (beta)
Browser: Chrome 104.0.5112.101
Browser engine: Chromium
Context: browser
Operating system: macOS 11.6.8
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 243 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon Pro 560 OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
There are a few things going on.

1) When you duplicate the timeline, now you have two timelines that can potentially affect the same instance. Using **Set Time 0** with no tags is affecting all timelines in the project. So you have two timelines that are making changes to the same instance.

2) In this particular case, I can see the first keyframe of the **Width** property has a value of 130. Since timelines by default apply changes relative to the starting value of the instance/s they affect, when you use **Set Time 0**, 130 is immediately added to the size of the instance, because that is what should happen when the timeline is at time 0.

3) Because the project has two timelines, what I just described happens twice, because unless you provide a tag to **Set Time**, the change is applied to all timelines.

**Comment by DiegoScirra** [comment]
I did find that setting the Result Mode to absolute is not producing the results I was expecting, so I will investigate this further.

**Comment by bubbblebub** [comment]
thanks for the explanation!
