### ISSUE TITLE
Follow Up: Mobile IAP triggers success and failure at the same time in iOS.  

### ISSUE THREAD

**Issue by vundurty** [Scirra/Construct-bugs#6421]
This is a continuation to previously filed [bug](https://github.com/Scirra/Construct-3-bugs/issues/6390). This time we have removed all third party plugins and we still get the same issue.

1. I'm using Mobile IAP for iOS Consumables
2. After the purchase, I'm receiving purchase success and purchase failure
3. This has never happened before. I'm not sure what could be the reason for this issue.

Requesting you to check if this is the plugin issue.

I've attached the c3p file and Xcode logs
[IAP Check.zip](https://github.com/Scirra/Construct-3-bugs/files/10486729/IAP.Check.zip)

## Steps to reproduce

1. Export to iOS
2. Deploy to testflight
3. Open the app in testflight
4. You will see "Store Registration Success" message on the screen
5. Click 'Buy' to purchase the product
6. After a moment, you will get purchase success trigger and after clicking 'Ok', you will get the purchase failed trigger

## Observed result

After the purchase, I'm receiving both purchase success and purchase failure triggers

https://user-images.githubusercontent.com/22640025/214222392-accb118e-c5ca-4619-ae1a-634656a83d66.mp4

## Expected result

After the purchase, I should receive only purchase success

## More details

iOS app

**Affected browsers/platforms:** 
None

I'm not sure since which version

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r317.2 (stable)
Browser: Chrome 109.0.5414.74
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 240 gb
Storage usage (approx): 75 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
As per my other comment, the "purchase failed" trigger actually fires when there is any IAP related error, which suggests a problem with your IAP configuration. It's difficult for us to test this as it is your own configuration on your own account. It also happens a lot (e.g. a configuration issue with ads was filed as a bug in #6407). Can you also once again obtain the console log messages when the error happens as well?

**Comment by vundurty** [comment]
I've tried to obtain the console logs again but I see the same logs. It says error but it doesn't mention what error.
[PurchaseFailedErrorLog_2.zip](https://github.com/Scirra/Construct-3-bugs/files/10500383/PurchaseFailedErrorLog_2.zip)

Also, regarding the IAP configuration problem. I've tried purchasing with Chadori's Moblie IAP plugin, it is working fine. The purchase failure doesn't trigger (I'm not sure if I can mention the third-party plugin). The purchase failure is happening only in Scirra's Mobile IAP plugin.

I'm not a highly technical person, so I'm unable to understand the issue. If you still think this is a configuration issue at my end, no worries please close this issue.

**Comment by AshleyScirra** [comment]
I'm not sure there's much we can do about this. Unfortunately I can't see any useful error information in the log. As far as I'm aware it's working for everyone else. My best guess is the IAP is configured incorrectly somehow, and Chadori's Mobile IAP plugin isn't checking for the error.

**Comment by UpToSix** [comment]
Hello Sir, 
Please note that the use case is using MobileIAP from standard construct 3 plugin. No Chadori used. The code is just few lines. For iOS it is throwing a purchase failure after purchase is successful. On the other hand, for Android, MobileIAP.Transaction on 'onPurchase Success" returns "null".

May you kindly one please test with your test set up? We are really dependednt on construct 3 standard plugin and not able to proceed further.
Thansk a lot in advance!

**Comment by AshleyScirra** [comment]
Reviewing some older issues, and in this case Mobile IAP was updated to a largely rewritten version as of r347, and so I suspect this issue is no longer applicable so closing. If you still have trouble with the latest release please file a new issue.

**Comment by UpToSix** [comment]
Dear Sir,

Thanks a lot.
But I see that there is a change in the behaviour of restore-purchase.
Can you confirm the earlier behaviour described below is same also now?

The earlier behaviour was:

On Restore Purchases

When a user does not own the IAP in question

- "+ MobileIAP: On any purchase success" = TRUE (weird)

- "+ MobileIAP: On product <productID> purchase success" = FALSE

- "+ MobileIAP: On any purchase failed" = FALSE

- "+ MobileIAP: Has product <productID>" = FALSE

When a user does own the IAP in question

- "+ MobileIAP: On any purchase success" = TRUE

- "+ MobileIAP: On product <productID> purchase success" = TRUE

- "+ MobileIAP: On any purchase failed" = FALSE

- "+ MobileIAP: Has product <productID>" = TRUE




Thanks and Best regards,
***@***.***

**Comment by AshleyScirra** [comment]
@UpToSix - the 'Restore purchases' action changed due to a change in the underlying `cordova-plugin-purchase` plugin. The change is mentioned in the [migration guide](https://github.com/j3k0/cordova-plugin-purchase/wiki/HOWTO:-Migrate-to-v13), but in short, it used to do three tasks (initialize, refresh products, restore purchases), and now it only does one (restore purchases, matching the intended purpose of the action).

**Comment by UpToSix** [comment]
Thanks a lot!

Thanks and Best regards,
***@***.***

**Comment by UpToSix** [comment]
Hello Sir,

I've one Q on "When owned". Cordova docu says it is removed.
But Latest C3 still has it .
Any comments?
[image: image.png]
Thanks and Best regards,
***@***.***
