### ISSUE TITLE
Unable to change AdMob banner size

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#6446]
## Problem description
I'm not sure if it is a bug but playing with the MobileAdvert plugin I have seen that once you create a banner advert with a specific size (for example standard) and you then create a new banner with a different size (for example large)the first banner size is maintained. It seems that the first selected size is maintained through the next banner creations.

## Attach a .c3p
[admob banner bug.android.debug.apk.zip](https://github.com/Scirra/Construct-3-bugs/files/10550566/admob.banner.bug.android.debug.apk.zip)
[admob banner bug.c3p.zip](https://github.com/Scirra/Construct-3-bugs/files/10550569/admob.banner.bug.c3p.zip)
remove the ".zip" extension.

## Steps to reproduce

1. run the apk into an android device (or build a debug apk with the provided c3p file)
2. click the "STANDARD" button and wait for the standard banner creation.
3. click the "HIDDEN" button to hide the banner.
4. click the "LARGE" button to create a new large banner.

## Observed result
A standard banner is shown instead of the large one.
You can follow the above procedure using the large button first and the standard button later but you always get the banner with the size as been chosen first.

## Expected result
Size should change at any banner creation when changed by the user.

## More details

tested on Samsung S6 SM-G920F device only, Android 7.0

**Affected browsers/platforms:** 

APK built with C3 R328. the previous release is also affected by the problem.
**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
What you describe is the intended behaviour and has been for a long time.

The assumption is that any given application will only ever need a banner of one size, so once it is created it is cached to avoid requesting a new ad each time, which can take some time.

The main workflow is to create the banner at a time in which is not immediately needed, so it can have time to make the request for the ad and hopefully be ready to be shown instantly when needed.

**Comment by rraffo** [comment]
Ok understood.
What if in the same app I have different layouts and I need to place a different banner with a different size? How can I reset the first request and generate a new one without closing the app?

**Comment by DiegoScirra** [comment]
Right now there is no way of doing that. It should be easy to add an action to discard the current banner.

**Comment by DiegoScirra** [comment]
Starting with the next beta, the **"Create banner"** action will have a new **"reload"** parameter that will allow to recreate a banner after the initial call.
