### ISSUE TITLE
Error on export to iOS with share plugin in the project.

### ISSUE THREAD

**Issue by squalinho** [Scirra/Construct-bugs#6511]
## Problem description

Error on export to iOS with share plugin in the project and a project name with accented characters (exemple : é ou è)  (widely used in French)

## Attach a .c3p

[test.zip](https://github.com/Scirra/Construct-3-bugs/files/10722469/test.zip)

## Steps to reproduce

1. Create new project, fill all about celles and use accented characters in Name Project.
2. Add share plugin.
3. Export to iOS (i used xcode project ) 

## Observed result

Error

## More details
Error: Platform 'ios' found in config.xml... Migrating it to package.json
Discovered platform "ios". Adding it to the project
Using cordova-fetch for cordova-ios@6.2.0
Adding ios project...
Creating Cordova project for the iOS platform:
Path: ~~/ios
Package: com.acceseditions.ajmd
Name: Modèles de dessins

iOS project created with cordova-ios@6.2.0
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-purchase' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-rate' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Discovered plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for ios
Discovered plugin "cordova-plugin-purchase". Adding it to the project
Installing "cordova-plugin-purchase" for ios
Discovered plugin "construct-mobile-rate". Adding it to the project
Installing "construct-mobile-rate" for ios
Installing "cordova-plugin-add-swift-support" for ios
Discovered plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for ios
 
Error: ENOENT: no such file or directory, open '~~/Modèles de ~~/project.pbxproj'
at Object.openSync (node:fs:600:3)
at Object.readFileSync (node:fs:468:35)
at pbxProject.parseSync (~~/pbxProject.js:61:28)
at ~~/add-swift-support.js:68:20
at process.processTicksAndRejections (node:~~/task_queues:95:5)

**Comment by AshleyScirra** [comment]
Please provide a sample project as per the bug report guidelines.

**Comment by squalinho** [comment]
I just added it, sorry as it was enough to add the share plugin and not put any event to cause the problem I did not think it would be necessary. (sorry bad english, I'm french.)

**Comment by AshleyScirra** [comment]
Thanks. As noted in the bug report guidelines we always require this as it is very common that people accidentally omit details.

I can reproduce, but it's not clear why it's happening. If it's an issue with Cordova itself there may not be an easy fix. In the mean time you can probably easily work around it by avoiding accents in the project name, and renaming it in Xcode.

**Comment by squalinho** [comment]
Yes no problem I understand. 
I will try to rename in xcode. Thank you for everything !

**Comment by AshleyScirra** [comment]
I think I should have a fix for this in the next release cycle (first beta after the next stable release). It looked like an old and redundant part of the Share plugin was causing the problem, but that part isn't needed any more, and so simply removing it allows the build to succeed even when there are accented characters in the project name.
