### ISSUE TITLE
Issues with very rapid use of undo/redo

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-bugs#6531]
A number of issues have been filed involving rapid use of undo/redo, such as performing an action and undoing it as soon as possible, or repeatedly undoing and redoing a lot of actions. These generally appear to involve cases where an action is unexpectedly performed while asynchronous code is running. I also suspect these issues mainly affect slower systems, as the asynchronous code will take longer to run, providing a longer time window for the action to be performed unexpectedly.

Given the similarity of many of these issues and the fact they may possibly need an overall upgrade to the undo system to fundamentally resolve, and to better organise the issues list, I'm merging all such reports in to a single issue here along with the developer assigned to each.

## Issue list

- [x] @AshleyScirra #6494
- [x] @AshleyScirra #6496
    - Appears to be another variant: #6547
- [x] @AshleyScirra #6517
- [x] @AshleyScirra #6518
- [x] @AshleyScirra #6524
- [x] @DiegoScirra #6525
- [x] @DiegoScirra #6529
- [x] @AshleyScirra #6532
- [x] @DiegoScirra #6562
- [x] @DiegoScirra #6567
- [ ] @AshleyScirra #6576
- [x] @AshleyScirra #6597
- [x] @DiegoScirra #6603
- [x] @DiegoScirra #6614
- [x] @DiegoScirra #6615
- [x] @DiegoScirra #6656
- [x] @AshleyScirra #6657
- [x] @AshleyScirra #6658
- [x] @DiegoScirra #6674
- [x] @DiegoScirra #6675
- [x] @DiegoScirra #6676
- [x] @DiegoScirra #6677
- [x] @DiegoScirra #6684
- [ ] @AshleyScirra #6708
- [x] @AshleyScirra #6696
- [x] @AshleyScirra #6695
- [x] @AshleyScirra #6726
- [x] @DiegoScirra #6740
- [ ] @DiegoScirra #6806
- [ ] @DiegoScirra #6911
- [ ] @DiegoScirra #6917

**Comment by AshleyScirra** [comment]
I've made some general improvements for editor robustness around these cases for the next beta. Let's see how much that helps when it's out.

**Comment by AshleyScirra** [comment]
These issues are difficult for us to reproduce, but a range of editor-wide improvements have been made in r331 to improve robustness when commands are run in quick succession. @WilsonPercival - can you check these again in r331 and see if any are fixed?

**Comment by WilsonPercival** [comment]
> These issues are difficult for us to reproduce, but a range of editor-wide improvements have been made in r331 to improve robustness when commands are run in quick succession. @WilsonPercival - can you check these again in r331 and see if any are fixed?

@AshleyScirra No problem. I'll take care of this right now. I will report the results in the same report that I created.

**Comment by DiegoScirra** [comment]
A fixed for #6529 and similar issues will be available when the next release cycle starts

**Comment by DiegoScirra** [comment]
A fix for #6529 and similar issues will be available when the next release cycle starts

**Comment by DiegoScirra** [comment]
A fix for #6674 will be available when the next beta cycle starts

**Comment by DiegoScirra** [comment]
Fixes for #6529 #6614 #6615 #6567 and #6674 will be available when the next release cycle starts

**Comment by AshleyScirra** [comment]
Think we've done enough on this so closing.
