### ISSUE TITLE
Importing and Replacing frames into an Animation

### ISSUE THREAD

**Issue by elmanuelv** [Scirra/Construct-bugs#6590]
Hi!

I have an issue that has been a little bothering to me ever since I switched from C2 to C3

When you imported frames into an animation in Construct 2 and replaced all frames, each frame would keep the points and collision box from the previous ones. However in Construct 3, you have to place each point and set the collision all over again as they are all reset after importing.

This has given me a lot of work every time the artists make changes in sprites that have several image points.

Is it possible to have this like it was on C2?

Thanks!

**Comment by WilsonPercival** [comment]
You can export the animation keeping the collision mask points in a separate file. Read more about it in the official documentation:

https://www.construct.net/en/make-games/manuals/construct-3/interface/animations-editor

**Comment by elmanuelv** [comment]
I don't want to export the animation though :( I want to reimport the frames

**Comment by WilsonPercival** [comment]
> I don't want to export the animation though :( I want to reimport the frames

You can import, adjust the collision mask, then export with the collision mask saved to a separate file. Then you can import it as much as you like, keeping the collision mask.

**Comment by elmanuelv** [comment]
Ooh cool I understand, I didn't know about that. But still feels like too much unnecessary steps comparted to how it was like in Construct 2

**Comment by AshleyScirra** [comment]
@DiegoScirra - sounds like something that was unintentionally different from C2. Perhaps there should be an option for this though? I suspect sometimes the imported animation will be completely different and so clearing all polys/image points makes sense, but other times the imported animation is an update of the existing animation so the existing polys/image points should be preserved.

**Comment by DiegoScirra** [comment]
An additional check box will be added starting with the next release cycle to keep all the animation frame data when using the **"Replace entire animation"** option of the **"Import Strip"** dialog
