### ISSUE TITLE
Issues with interrupting drag-and-drop

### ISSUE THREAD

**Issue by AshleyScirra** [Scirra/Construct-bugs#6664]
A number of issues have been filed relating to interrupting drag-and-drop. For example while still holding the mouse button down to drag an item, the user can press a keyboard shortcut like Ctrl+Z (undoing the creation of the dragged item) or Escape (cancelling the dialog the drag is taking place in) which can result in a crash due to the unexpected state. These should be relatively straightforward to fix - cancelling the drag when any of these events happens should be sufficient.

## Issue list
- [x] @AshleyScirra #6596
- [x] @AshleyScirra #6622
- [x] @DiegoScirra #6623
- [x] @DiegoScirra #6624
- [x] @DiegoScirra #6640
- [x] @DiegoScirra #6653
- [x] @DiegoScirra #6654
- [x] @DiegoScirra #6655
- [x] @DiegoScirra #6661
- [x] @DiegoScirra #6662
- [x] @AshleyScirra #6715
- [x] @AshleyScirra #6703
- [x] @AshleyScirra #6702
- [x] @DiegoScirra #6716
- [x] @DiegoScirra #6697
- [x] @DiegoScirra #6698

**Comment by DiegoScirra** [comment]
Fixed for starting on the next release cycle: #6623
