### ISSUE TITLE
advanced random scripting interface missing

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6672]
## Problem description

I am trying to rewrite some heavy loops in js to improve performance and I was using advanced random, but I cannot seem to find a scripting interface for it. I have to admit that I am very very inexperienced in js, so chances are high that I am just missing how to properly access it.

Advanced random is super useful for stuff like proc-gen etc. which usually requires large nested loops. As nested loops in events tend to be slower, this seems like a good candidate to mix in js. The noise from advanced random would be very useful (I assume it's also faster than creating your own noise in js, because advanced random is using WASM).

As most other plugins have a scripting interface and documentation I felt like this is not nescesarily a suggestion but more so an oversight, but I get that you might see it otherwise. I hope advanced random is not abandonned since NEPEO left.

**Comment by AshleyScirra** [comment]
I think I had kind of assumed the stuff Advanced Random does is easy enough to do in JS anyway - for example permutation tables are more or less just a shuffled array, which is probably just a few lines of JS code, but can be a bit awkward in events so it's handy to have a plugin for it. Still I guess things like the noise functions are worth making accessible as they're already there and it saves bringing in another JS lib to do it. I'll take a look at what features it makes sense to expose to JS.

**Comment by F3der1co** [comment]
Cool, yea noise seems to be the most useful part of it for scripting, but:
I would argue that for people like me coming from events, having functionality that I'm used to like the advanced random permutation and probability table is also valuable to make the transition that much easier, even if a more experienced js developer would not use it. Additionaly when mixing js and events, which currently is my wokflow: find the stuff that is particularily heavy and try to rewrite it in js if possible. 
For example: assuming I am using a probability table in my events, now I have a heavy loop that generates something in the world based on it. In development I realize that I want to rewrite that part in js to improve performance. Now all the other events are already using the advanced random table. So in situations like this I would also love to access the table via scripting.
