### ISSUE TITLE
disabled script not greyed out, incosistency

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6692]
## Problem description

A disabled script in the event-sheet is only crossed but not greyed out unlike other elements in the sheet when disabled.

## Attach a .c3p
[scriptBugsGrey.zip](https://github.com/Scirra/Construct-3-bugs/files/10886669/scriptBugsGrey.zip)

## Steps to reproduce

1.look at the event sheet

## Observed result

disabled script is crossed out but still has color highlighted text. 

## Expected result

the text of a disabled script is greyed out 

## More details

Greying the text out would stay consisten with events, condition and actions. Additionally it would look way less messy visually, as the strikethrough+colors looks very noisy.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I guess you're using the dark theme? Because the default theme does not change the text color of normal event blocks when disabled.

**Comment by F3der1co** [comment]
Oh yea, I guess then this is only inconsistent in the dark and light theme.

**Comment by AshleyScirra** [comment]
This seems tricky to change, as the CodeMirror code editor's styles are overriding the theme styles. Meanwhile it seems mostly an aesthetic change, the disabled state is clearly communicated by the strikethrough style, the default theme works similarly, preserving syntax highlighting may in fact be desirable in some cases, and given the volume of issue reports lately I don't think we have the resources to dig in to potentially subjective issues like this, so closing as won't fix. If you feel strongly about this you can post a suggestion.
