### ISSUE TITLE
dark theme, array change width/height dialog not styled properly

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6712]
## Attach a .c3p
[darkThemeStyle.zip](https://github.com/Scirra/Construct-3-bugs/files/10892185/darkThemeStyle.zip)

## Steps to reproduce

1. right-click cell
2. select change colum width

## Observed result
![coll](https://user-images.githubusercontent.com/89512047/222970660-e71ac239-7ee5-457f-bb76-1b96f0b97ecc.png)
 the text "new size" has the wrong color. (black is used while afaik there is no pure black in the color palette)

## Expected result
correct grey tone is used

## More details
the text is also black in the light theme, while normally a dark-ish grey is used.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
