### ISSUE TITLE
Unhandled exception when dragging variable

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#6721]
## Problem description
When changing variable order, an unhandeled exception happens.

## Steps to reproduce

1.
2.
3.

## Observed result

Error report information
Type: unhandled exception
File: https://editor.construct.net/r333/main.js, line 1826, col 529
Message: Uncaught TypeError: Cannot read properties of null (reading 'ownerDocument')
Stack: TypeError: Cannot read properties of null (reading 'ownerDocument') at CCG.vi.g.K.Table.gK.va (https://editor.construct.net/r333/main.js:1826:529) at CCG.vi.g.K.Table.gK.Kl (https://editor.construct.net/r333/main.js:1828:515) at CCG.vi.g.K.Table.gK.Cd (https://editor.construct.net/r333/main.js:1831:18) at FAa.Ca.j7a.je (https://editor.construct.net/r333/main.js:1825:84)
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Tue Mar 07 2023 21:16:13 GMT+0100 (Central European Standard Time)
Uptime: 55.2 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Edge 110.0.1587.63
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

## More details

**Affected browsers/platforms:** 

Edge, chrome

**First affected release:** 

Beta 333

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.1265
Experience	Windows Feature Experience Pack 1000.22638.1000.0

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was a regression introduced in r333

**Comment by DinoSystem** [comment]
> Will be fixed in the next beta. Was a regression introduced in r333

It also happens when dragging behaviours.

**Comment by F3der1co** [comment]
also crashes with effects, I hope this fixes all cases.
