### ISSUE TITLE
Unhandled exception on any Audio settings change

### ISSUE THREAD

**Issue by constuser** [Scirra/Construct-bugs#6743]
## Problem description

With any change of any Audio parameter, we get an Unhandled exception.

## Attach a .c3p

[AudioBug.zip](https://github.com/Scirra/Construct-bugs/files/10944550/AudioBug.zip)

## Steps to reproduce

1. Create empty project.
2. Add Object type "Audio".
3. In Audio Properties tab change any parameter. For example, change Timescale audio parameter to "On (sounds only)".

## Observed result

Unhandled exception.

## Expected result

The Audio parameters changes without errors.

## More details

**Affected browsers/platforms:** 
Tested only in Chrome on Windows 10.

**First affected release:** 
Worked (no exceptions) on 1/26/2023 (I don't know what the version was at the time).
But exception in r327.3 (stable).

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r327-3/main.js, line 1033, col 141
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at O.i (https://editor.construct.net/r327-3/main.js:1033:147) at O.Wf (https://editor.construct.net/r327-3/main.js:1034:192) at q1 (https://editor.construct.net/r327-3/components/bars/timelineBar/timelineBar.js:31:218) at w5.LWb (https://editor.construct.net/r327-3/components/bars/timelineBar/timelineBar.js:511:296) at w5.rAc (https://editor.construct.net/r327-3/components/bars/timelineBar/timelineBar.js:511:200) at Array. (https://editor.construct.net/r327-3/components/bars/timelineBar/timelineBar.js:507:288) at window.ldb.dispatchEvent (https://editor.construct.net/r327-3/main.js:1232:42) at peb (https://editor.construct.net/r327-3/components/bars/propertiesBar/propertiesBar.js:2:310) at d.nca (https://editor.construct.net/r327-3/components/bars/propertiesBar/propertiesBar.js:112:154) at Array. (https://editor.construct.net/r327-3/components/bars/propertiesBar/propertiesBar.js:99:118)
Construct version: r327.3
URL: https://editor.construct.net/
Date: Fri Mar 10 2023 20:39:43 GMT+0300 (Moscow Standard Time)
Uptime: 508.9 s

Platform information
Product: Construct 3 r327.3 (stable)
Browser: Chrome 111.0.5563.64
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by constuser** [comment]
> Does this happen in the latest beta?

Let me check...

**Comment by constuser** [comment]
> Does this happen in the latest beta?

YES!
Same Unhandled Exception in r333 beta:
---
Error report information
Type: unhandled exception
File: https://editor.construct.net/r333/main.js, line 1034, col 141
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at O.i (https://editor.construct.net/r333/main.js:1034:147) at O.dg (https://editor.construct.net/r333/main.js:1035:192) at r1 (https://editor.construct.net/r333/components/bars/timelineBar/timelineBar.js:31:218) at x5.RYb (https://editor.construct.net/r333/components/bars/timelineBar/timelineBar.js:511:296) at x5.RCc (https://editor.construct.net/r333/components/bars/timelineBar/timelineBar.js:511:200) at Array. (https://editor.construct.net/r333/components/bars/timelineBar/timelineBar.js:507:288) at window.Xeb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at Mfb (https://editor.construct.net/r333/components/bars/propertiesBar/propertiesBar.js:2:358) at d.oda (https://editor.construct.net/r333/components/bars/propertiesBar/propertiesBar.js:115:256) at Array. (https://editor.construct.net/r333/components/bars/propertiesBar/propertiesBar.js:102:122)
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Fri Mar 10 2023 20:55:53 GMT+0300 (Moscow Standard Time)
Uptime: 50.2 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Chrome 111.0.5563.64
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
---

**Comment by DiegoScirra** [comment]
This doesn't happen from an empty project though. I am trying just that and seeing nothing wrong.

From the error you posted it seems there is something going on with timelines, do you have any timelines in your project?

**Comment by constuser** [comment]
No, Timelines are not used, but I have one Timeline tab parked:
![AudioTestScreenshot](https://user-images.githubusercontent.com/127539603/224393031-860f5eaf-526a-4675-bee1-ef134a602920.jpg)

And, when I closed this Timeline tab, the problem with changing the Audio settings disappeared! Hurray!
Now there are no errors when changing any Audio settings!
Thanks so much for finding the cause of this problem!

**Comment by DiegoScirra** [comment]
It looks like the problem happens because the **"Auto Keyframes"** options is toggled in the timeline bar. Must have something to do with global objects like the Audio plugin. While this is fixed, if you turn the option off in the Timeline bar, the error doesn't happen.

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
