### ISSUE TITLE
Unhandled rejection when spamming cut/paste video and audio subfolders

### ISSUE THREAD

**Issue by williamcdubois** [Scirra/Construct-bugs#6745]
## Problem description

Construct 3 crashing after spamming ctrl + x and ctrl + v. This issue is similar to this one: https://github.com/Scirra/Construct-bugs/issues/6533

However, the difference here is instead I am spamming it quickly. After a few seconds, the crash shows up. Happens also with the video subfolders.

## Attach a .c3p

[Project sample](https://drive.google.com/file/d/1hnhQleEB3fTNQcagwE8BUxdBiyeLN4Tk/view?usp=share_link)

## Steps to reproduce

1. Drag the child file in the subfolder above (video with the new folder of video, audio with the new folder of audio).
2. Ctrl + X on a New folder (for example, the new folder inside Videos).
3. Ctrl + V on the parent folder where the cut was made (with the same example, in Videos).
4. If you do it slowly, it will do nothing. However, try to spam it like Formula 1 for 3 seconds.
5. Enjoy the crash!

## Observed result

Construct begins to lag a little until instantly crashes.

## Expected result

Construct 3 doesn't crash.

## More details
This issue occurs, in my case, in both Chrome and Firefox.

Using r327.3 stable.

Core i7-3770 3.4GHz
Nvidia GeForce GTX 1050 Ti
32GB of RAM
Windows 10 64-Bit

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: file name 'inconvenience2.mp4' already used @ Error: file name 'inconvenience2.mp4' already used at d.Xa (https://editor.construct.net/r327-3/projectResources.js:933:186) at v (https://editor.construct.net/r327-3/components/bars/projectBar/projectBar.js:67:375) at async Promise.all (index 0) at async y (https://editor.construct.net/r327-3/components/bars/projectBar/projectBar.js:67:472)
Stack: Error: file name 'inconvenience2.mp4' already used at d.Xa (https://editor.construct.net/r327-3/projectResources.js:933:186) at v (https://editor.construct.net/r327-3/components/bars/projectBar/projectBar.js:67:375) at async Promise.all (index 0) at async y (https://editor.construct.net/r327-3/components/bars/projectBar/projectBar.js:67:472)
Construct version: r327.3
URL: https://editor.construct.net/
Date: Fri Mar 10 2023 17:54:26 GMT-0500 (heure normale de l’Est nord-américain)
Uptime: 950.4 s

Platform information
Product: Construct 3 r327.3 (stable)
Browser: Chrome 110.0.5481.180
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by WilsonPercival** [comment]
I think your problem is more like this: https://github.com/Scirra/Construct-bugs/issues/6494

It has been fixed in the latest beta. Please make sure you test this in the latest beta version.

**Comment by williamcdubois** [comment]
Hi Wilson. I tried without pity to reproduce my issue in the beta version R333, and somehow the problem is fixed there :O

Thanks for the reply!

**Comment by williamcdubois** [comment]
(P.S. The issue was also happens with Videos and not just Sounds)

**Comment by DiegoScirra** [comment]
Closing as it seems this was already fixed.
