### ISSUE TITLE
Editor crash when undoing changes in the Animation editor for TiledBackground object

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#6748]
## Problem description

Editor crashes when I'm trying to undo changes in TiledBackground.

## Attach a .c3p

N/A

## Steps to reproduce

1. In a blank project add a TiledBackground object.
2. Draw something in it with a pencil tool
3. Press Ctrl-Z

## Observed result

![GIF 11-03-2023 12-17-41](https://user-images.githubusercontent.com/36763350/224456992-219d6f95-4122-4b08-adf3-1bdbf1c5831a.gif)

## More info

This happens in Chrome and Firefox.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'kk') @ TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Stack: TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Sat Mar 11 2023 12:17:36 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 50.6 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Chrome 110.0.5481.180
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/6742

**Comment by dop2000** [comment]
Apparently it's a duplicate
