### ISSUE TITLE
Reordering instance variables causes crash

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#6750]
## Problem description

Crash when reordering instance variables

## Attach a .c3p

Any empty project with a sprite and 2 instance variables will do.

https://user-images.githubusercontent.com/31101309/224496347-f216c4ad-0daa-4669-a1cb-1930b9f1e23a.mp4

## Steps to reproduce

1. drag a bottom variable to the top

## Observed result

crash

## Expected result

!crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r333/main.js, line 1826, col 529
Message: Uncaught TypeError: Cannot read properties of null (reading 'ownerDocument')
Stack: TypeError: Cannot read properties of null (reading 'ownerDocument') at CCG.vi.g.K.Table.gK.va (https://editor.construct.net/r333/main.js:1826:529) at CCG.vi.g.K.Table.gK.Kl (https://editor.construct.net/r333/main.js:1828:515) at CCG.vi.g.K.Table.gK.Cd (https://editor.construct.net/r333/main.js:1831:18) at FAa.Ca.j7a.je (https://editor.construct.net/r333/main.js:1825:84)
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Sat Mar 11 2023 17:33:36 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 30.1 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Chrome 111.0.5563.64
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/6721

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
