### ISSUE TITLE
Crash in "Tiled Background Editor" when useing "CTRL-Z" to undo

### ISSUE THREAD

**Issue by ColorfishGames** [Scirra/Construct-bugs#6753]
## Problem description
Crash in "Tiled Background Editor" when useing "CTRL-Z" to undo

## Steps to reproduce

1. Open the "Tile background editor.
2. Edit sprite
3. use CTRL-Z - and it crashes every time

## More details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'kk') @ TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Stack: TypeError: Cannot read properties of null (reading 'kk') at Zx.g.K.MSc.Jg (https://editor.construct.net/r333/projectResources.js:2514:418) at Array.XY (https://editor.construct.net/r333/projectResources.js:2511:116) at Dx.g.K.Qb.dispatchEvent (https://editor.construct.net/r333/main.js:1234:42) at https://editor.construct.net/r333/projectResources.js:2552:416
Construct version: r333
URL: https://editor.construct.net/r333/
Date: Sun Mar 12 2023 09:54:44 GMT+0100 (Centraleuropæisk normaltid)
Uptime: 29.8 s

Platform information
Product: Construct 3 r333 (beta)
Browser: Chrome 111.0.5563.64
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

**Affected browsers/platforms:** 

The crash is in Chrome and the PC app

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/6748

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was a regression introduced in r333.
