### ISSUE TITLE
Crash setting Physics Object scale to Infinity

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#6755]
## Problem description

Crash setting the scale of an object (with a Physics behavior) to Infinity.

## Attach a .c3p
[physics.zip](https://github.com/Scirra/Construct-bugs/files/10951744/physics.zip)

## Steps to reproduce

1. Run Layout1
2. Open the browser console

## Observed result
Game stops and many exceptions in the console.

## Expected result
Game should work, and the Set Scale action should ignore the Infinity value.

**Comment by AshleyScirra** [comment]
This appears to be very complicated to fix and doesn't appear to correlate to a likely problem that games face (why make an infinite sized object?) so I think the best thing to do in this case is take no action.

It is difficult to ignore an infinite size, as we still need to create a physics body as the behavior is enabled. We could just use a small size like 10x10 instead, but then it will act weirdly, with an infinite sized object simulating as if it was 10x109. We could treat this as another way to disable the behavior, but this introduces a lot of complexity to an already difficult codebase, just in case someone tries to create an infinite sized object. Meanwhile presumably it's easy to just not create infinite size objects - I don't see how that has any real utility.
