### ISSUE TITLE
HTML Element - CSS height: 'auto' overriding by original height (when object is moved)

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-bugs#6756]
## Problem description

When I set the Height of a HTML Element via CSS to auto, once the div is moved the size reverts back to the original object height.

It would also be nice if the bounding box of the object will also update when setting size via CSS.

## Attach a .c3p

[htmlElem_CssHeight.zip](https://github.com/Scirra/Construct-bugs/files/10952084/htmlElem_CssHeight.zip)

## Steps to reproduce

1. Run layout.
2. Drag object.

## Observed result

Div height is being reverted to the original object height.

## Expected result

Keep the current height.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
[The documentation for HTML element](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/html-element) notes that Construct controls the `height` CSS property of the main HTML element, and that overriding them can cause the element to work incorrectly. The manual also provides a workaround: use another element inside the HTML element.
