### ISSUE TITLE
Dark theme: The color of the prompt message is not conducive to reading

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#6757]
## Problem description

In the Dark theme, the expression prompt uses gray text, which is not easy to read.

## Observed result

![Snipaste_2023-03-13_18-39-32](https://user-images.githubusercontent.com/45864744/224678357-790dd582-3372-4cb3-9d10-c6e10e7f7c72.png)

## Expected result

Adjust font color, increase contrast

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
https://construct23.ideas.aha.io/ideas/C23-I-201
There's also this suggestion about the wider issues of the bright highlight colour in the dark theme

**Comment by AshleyScirra** [comment]
Fixed for next beta
