### ISSUE TITLE
Dark theme: The rounded corners of the drop-down components are inconsistent

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#6758]
## Problem description

The drop-down component of the dark theme uses inconsistent rounded corner ratios, which is not beautiful.

## Observed result

![Snipaste_2023-03-13_18-42-43](https://user-images.githubusercontent.com/45864744/224679270-c15e5594-8b01-40a0-9094-c7fd8d084fb6.png)

## Expected result

Use the same rounded corner properties.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
For me it looks like this.

![lol](https://user-images.githubusercontent.com/91274932/224683869-acc94974-d5e9-4973-bc8a-1b89fcd8ff92.png)

**Comment by AshleyScirra** [comment]
It doesn't look like that for me either (I see the same thing as @WilsonPercival). Besides, I don't think browsers provide a way to style the dropdown of a `<select>` element with CSS, so I don't think we can alter it.

**Comment by XHXIAIEIN** [comment]
Oh, I've noticed that this is the default style for Chrome and Edge browsers, with rounded corners like this everywhere on `<select>`. And even changing CSS styles doesn't seem to affect him. But if I use Firefox, what I see is normal.

**Comment by XHXIAIEIN** [comment]
I noticed that some parts of the current editor use a custom dropdown component, which works well. 

For example

The `class='menuButton'` for Start page 'OPEN' Button

![46a7713743e1032859eb943e1062c5f](https://user-images.githubusercontent.com/45864744/225078240-029decdf-34c1-4339-ae0e-6bc11ed67242.jpg)

The `<ui-menu>` component of preview options

![Snipaste_2023-03-15_00-40-27](https://user-images.githubusercontent.com/45864744/225078302-99f4e380-3b76-4c98-b486-d42116e90f2b.png)

So, I suggest, replace them with <select> in all that need a dropdown to work.
https://construct23.ideas.aha.io/ideas/C23-I-208
