### ISSUE TITLE
dark theme: script border weird colors

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6761]
## Problem description
In the dark theme, scripts in event-sheets get a border, showing the selection state (not selected, selected and editing).
The colors used are a weird choice as they don't match the typical selection colors and additionally the non selected color is very contrast heavy in the dark theme.

## Attach a .c3p

[scriptWeirdHighlighting.zip](https://github.com/Scirra/Construct-bugs/files/10956649/scriptWeirdHighlighting.zip)

## Steps to reproduce

1.make sure to use the dark-theme
2. observe the border of the scripts
3. select a script and observe the border
4. double-click a script and observe the border

## Observed result
not selected: very bright lilac
selected: yellow
editing: white

https://user-images.githubusercontent.com/89512047/224687199-b25e4a90-fad2-4626-ad1d-f8b7f449cf9d.mp4

## Expected result
Colors that match the typical selection colors of the dark theme (usually bright grey but that is controversial, see  [suggestion](https://construct23.ideas.aha.io/ideas/C23-I-201). Otherwise a blue or more rarely a green/teal is used)
Non-selected color should be least contrasty, maybe no border at all.

## More details
In case you are wondering why there are so many dark theme reports: there was a little discussion about why people dislike the dark theme on discord.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
