### ISSUE TITLE
"Edit object types in family" popup search field only search in the left column (Object types in project), but not in the right column (Object types in Family)

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#6764]
## Problem description

Edit object types in family" popup search field only search in the left column (Object types in project), but not in the right column (Object types in Family). **So removing an object member from a Family is really tedious as i need to scroll the right column until I find it.**

## Attach a .c3p

[FamilyEditMembers_ShouldSearchInBothColumns.zip](https://github.com/Scirra/Construct-bugs/files/10957234/FamilyEditMembers_ShouldSearchInBothColumns.zip)

## Steps to reproduce, OBSERVED VS EXPECTED

1. Right click the MyFamily in Project View > Edit Family
2. Type "toRemove" to find the "Sprite_toRemove" ObjectType you want to remove from the Family Members.

❌Observed : The search field only search for the Object in the left column (all Object Types that are not member of the Family yet), but the right column with all current Family Members isn't filtered. **So removing an object member from a Family is really tedious as i need to scroll the right column until I find it.**

✅ Expected : **The search field works for both the left and the right column : which means it is equally simple to find an Object I want to add and to find an Object I want to remove**

![Bug_SearchObjectTypesInFamily](https://user-images.githubusercontent.com/99751718/224700590-92c90ba2-2130-4225-a869-ee744560e7bb.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like a feature request, so please post it as a suggestion.

**Comment by OverboyDev** [comment]
The feature is called "Edit Family" not "add Family member".
It is equally important to add and to remove ObjectTypes from a family.
It doesn't makes sense that the search feature only works for adding objects.
Even for adding objects, it's better to filter the Objects already included in the Family so we immediatly intuitivly understand if an object we wanted to add was in fact already part of the family.

**Comment by OverboyDev** [comment]
I submitted a suggestion for this useability issue : https://construct23.ideas.aha.io/ideas/C23-I-226
