### ISSUE TITLE
The way actions related to Custom Actions are displayed are inconsistent with the other features of the engine. 

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#6771]
## Problem description

**The way actions related to Custom Actions are displayed is inconsistent with everything else in the engine.** 
For example if i have a "call Function" action, or a "set MyVariable to 1" action, "Function" and "MyVariable" are displayed in bold. However "MyCustomAction" is not displayed in bold if I call its related action.

## Attach a .c3p

[Bug_CustomAction_NotInBold.zip](https://github.com/Scirra/Construct-bugs/files/10970645/Bug_CustomAction_NotInBold.zip)

## Observed result

![image](https://user-images.githubusercontent.com/99751718/225056959-3195591d-1132-4c5a-9214-94d55649b0b3.png)

## Expected result

The "Action1" in the first Action of the screenshot should be displayed in **Bold**

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design.

**Comment by OverboyDev** [comment]
It makes sense for regular actions to not be bold, because they're sentences and the parameters can be anywhere among the string.

However Custom Actions are displayed exactly like Functions. 
So it should behave like Functions.

Moreover parameters of Custom Actions aren't bolded so it's inconsistent with both Functions and Regular functions at the same time.

But as I said, Custom Actions are like Functions so the Action name should be bold as opposed to Regular Actions.

**Comment by mitsuhashish** [comment]
I agree, consistency should be taken into account during the design process.

**Comment by OverboyDev** [comment]
I created a suggestion to fix this annoying display issue with Custom Actions, vote here if you agree : https://construct23.ideas.aha.io/ideas/C23-I-270
