### ISSUE TITLE
Add a use case for script

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#6772]
## Problem description

I think there should be reference a using example code in the documentation, rather than pointing to a more obscure documentation. This makes it easy for novices to learn. Please add this example code after this description

[When using scripts in Construct, use runtime.callFunction() to call an event function from script.](https://www.construct.net/en/make-games/manuals/construct-3/project-primitives/events/functions#:~:text=When%20using%20scripts%20in%20Construct%2C%20use%20runtime.callFunction()%20to%20call%20an%20event%20function%20from%20script.)

```javascript
runtime.callFunction("FunctionName", param1, param2); 
```

At the same time, if you want to dynamically reference functions and pass in any number of parameters, you can use this method. This way, only one string(`"FunctionName, param1, param2"`) needs to be used.

```javascript
runtime.callFunction(..."FunctionName, param1, param2".split(",").filter(e => e.trim()))
```

**Comment by AshleyScirra** [comment]
I don't really want to add examples to the documentation merely to indicate what the correct way to call a JavaScript function is. There is the 13-part [Learn JavaScript in Construct](https://www.construct.net/en/courses/learn-javascript-construct-79) tutorial series which covers the basics of things like that.

I would not regard the second code snippet as good practice - code should be written as code, not strings.
