### ISSUE TITLE
positional sound volume inverted

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#6789]
## Problem description

Sound volume decrease when the emitter gets closer to the listener.

## Attach
[positionalsound.zip](https://github.com/Scirra/Construct-bugs/files/10988884/positionalsound.zip)

## Steps to reproduce

1. drag the emitter closer to the listener.
2.
3.

## Observed result

Volume decrease.

## Expected result

Volume should increase

## More details

**Affected browsers/platforms:** 
Both Chrome and firefox

**First affected release:** 
tested on R334
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
so the inner and outer angle is actually a 3d cone? Never realized that.
