### ISSUE TITLE
Me siguen cobrando cuando ya cancele la suscripción

### ISSUE THREAD

**Issue by ZhionGames** [Scirra/Construct-bugs#6792]
## Problem description

Hace 2 días cancele la suscripción del plan personal porque no tenia como pagarlo, pero tiempo después me compre otro plan personal, después de eso me empezaron a llegar notificaciones de compras rechazadas desde mi tarjeta, y es por construct, parece que el plan que cancele anteriormente aun se sigue cobrando 

## Attach a .c3p

Este error no es de un proyecto 

## Steps to reproduce

 Cancele el plan personal que tenia y me compre otro

1.
2.
3.

## Observed result

Me siguen cobrando el plan anterior aun cuando lo e cancelado 

## Expected result

Que no me sigan cobrando

## More details
Como a las 3 horas de haber cancelado el plan personal ( el cual tengo el problema) me compre otro 

 Chrome  

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
For this kind of problems email support@construct.net
