### ISSUE TITLE
Left to right positioned audio is not smooth

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#6798]
## Problem description

Using positioned audio when you move the audio source from left to right, the audio is not faded smoothly.
Furthermore, even when the audio source is moved over a certain Y axis sound changes unexpectedly. (see the second part of the video)

https://user-images.githubusercontent.com/58107632/225868560-f18b8c9b-5ede-4f0e-9c18-2fb58e803347.mp4

Please activate the audio (I do recommend using headphones for better perception)

## Attach a .c3p

[audio pan.c3p.zip](https://github.com/Scirra/Construct-bugs/files/10999932/audio.pan.c3p.zip)

## Steps to reproduce

1. move the audio source (the green ball) around the listener (the purple square)
2.
3.

## Observed result

The sound is not smoothly adapted from left to right and vice versa.
## More details

**Affected browsers/platforms:** 
C3 R334

**First affected release:** 
Chrome and Firefox are both affected. Firefox seems not affected by the second part of the problem.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I believe this comes down to [this Chrome issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1242647) so Google need to fix that. In general the audio playback is handled by the browser, not Construct, so audio playback issues are usually beyond our control.

**Comment by rraffo** [comment]
I know the Chrome issue you have mentioned but the problem I raised up appears in Firefox as well. Can you please double-check?

**Comment by AshleyScirra** [comment]
As I mentioned these issues tend to be with the browser, not Construct. Due to an extraordinary number of issues filed lately I'm afraid we do not have the time at the moment to further investigate such issues.

**Comment by rraffo** [comment]
I can imagine the workload you are forced to process. I can wait patiently if when you have some time you can take a look at it. I appreciate it.
