### ISSUE TITLE
Unable to manage new timeline

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#6799]
## Problem description

If I start an empty project I'm not able to add instances in the timeline. The timeline bar is disabled.

## Attach a .c3p

Start an empty project
## Steps to reproduce

1. Open the timeline and try to click the + button
2.
3.

## Observed result

The timeline action bar is disabled
## More details

**Affected browsers/platforms:** 

Chrome and firefox
**First affected release:** 
it looks that the problem appear from the R330 version
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. It was a regression introduced in r330. In the mean time, you can still add instances to a timeline by dragging and dropping from the layout view into the timeline bar. After there is at least one instance the toolbar works as expected.
