### ISSUE TITLE
Variables of the same name can be regressed by pasting

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#6805]
## Problem description

In a function, creating a local variable with the same name as a parameter, deleting the parameter, rename local variable, and pasting the parameter it again will still keep the same name.

![Snipaste_2023-03-19_02-24-51](https://user-images.githubusercontent.com/45864744/226127138-4be394f2-e7b6-4024-9c78-e37e2ef4d2e1.png)

In fact, it only reproduces when pasted into a Function parameter.If you paste this clipboard directly, it will be fixed automatically
```json
{"is-c3-clipboard-data":true,"type":"events","items":[{"functionName":"Function1","functionCopyPicked":false,"functionDescription":"","functionCategory":"","functionReturnType":"none","functionIsAsync":false,"functionParameters":[{"name":"abc","type":"string","initialValue":"","comment":""}],"eventType":"function-block","conditions":[],"actions":[],"children":[{"eventType":"variable","name":"abc","type":"string","initialValue":"","comment":"","isStatic":false,"isConstant":false},{"eventType":"block","conditions":[],"actions":[{"id":"set-eventvar-value","objectClass":"System","parameters":{"variable":"abc","value":"\"\""}}]}]}]}
```

![Snipaste_2023-03-19_02-35-18](https://user-images.githubusercontent.com/45864744/226129324-9c369094-c14c-469c-8d9f-e45f0ade4e62.png)

## Attach a .c3p
[issue-same-variable.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11009274/issue-same-variable.c3p.zip)

## Steps to reproduce
1. copy function parameter
2. rename local variable
3. paste function parameter back

[video.webm](https://user-images.githubusercontent.com/45864744/226126672-4eecb587-1031-4276-b2da-ea915fdbb179.webm)

## Observed result

auto rename to abc1 when pasting

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r334 (beta)
Browser: Chrome 111.0.5563.65
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 120 gb
Storage usage (approx): 100 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by XHXIAIEIN** [comment]
By the way, I also have a idea to keep this feature. Group a list of variables:
https://construct23.ideas.aha.io/ideas/C23-I-21

**Comment by AshleyScirra** [comment]
This is indeed a bug as it causes a name collision, which should not be allowed. It should be fixed in the next beta, thanks for the report.
