### ISSUE TITLE
Crash when previewing a sprite animation.

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#6818]
## Problem description

Crash when previewing a sprite animation. (Not sure if wilson already found that one)

## Attach a .c3p

[animprevcrash.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11038219/animprevcrash.c3p.zip)

## Steps to reproduce

1. Switch the "initial animation" to animation 2
2. Preview

## Observed result

Construct crashes once the animation is done playing

## Expected result

No crash

## More details
A looping animation will keep looping fine, but still crashes once the preview is switched off.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r335/plugins/allEditorPlugins.js, line 220, col 257
Message: Uncaught TypeError: Cannot read properties of null (reading 'Aw')
Stack: TypeError: Cannot read properties of null (reading 'Aw') at window.Knb.wv [as zx] (https://editor.construct.net/r335/plugins/allEditorPlugins.js:220:257) at d.Dib (https://editor.construct.net/r335/projectResources.js:813:100) at d.Dpb (https://editor.construct.net/r335/projectResources.js:838:228) at d.jja (https://editor.construct.net/r335/projectResources.js:838:197) at d.mG (https://editor.construct.net/r335/projectResources.js:837:131) at d.w6 (https://editor.construct.net/r335/projectResources.js:808:190) at d.w6 (https://editor.construct.net/r335/projectResources.js:807:431) at dLb.Instance.ZF (https://editor.construct.net/r335/main.js:2050:456) at dLb.Instance.dg (https://editor.construct.net/r335/plugins/allEditorPlugins.js:231:156) at d.hc (https://editor.construct.net/r335/projectResources.js:792:340)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Wed Mar 22 2023 10:06:07 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 44.5 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.66
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/6784
