### ISSUE TITLE
Most unacceptable bug in gameplay history

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-bugs#6826]
Alshley please fix this bug, hard to accept games as serious when player can go thru the corner walls.

i use yours 3d example to show this: 

https://youtu.be/GtO9CQfBQ-0

**Comment by XHXIAIEIN** [comment]
This is not a BUG, it is because the walls in the example are too thin, and if the player moves faster than this range, the wall will appear to penetrate.

You can improve this by **increasing the width** of the walls, and lowering the Custom behavior **Pixel per step** property on the Player object.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.

**Comment by JonaszO** [comment]
> This is not a BUG, Since the walls of this example are relatively thin, if you increase the width of the walls appropriately, it can be solved.
> 
> Or you can improve this by decrease the Custom behavior **Pixel per step** property on the Player object. if the player moves a large distance in pixels per step and can go directly behind a wall on the next step. then this happens. For its principle, you can refer to this example https://editor.construct.net/#open=bullet-stepping

not always in game i can add thic wall, sometimes should be building wall like in this example.
@AshleyScirra what is there to describe, the error concerns going through the wall in the place shown in the video. You run to the corner and press left and right while holding down the forward arrow to make him run into the wall.
