### ISSUE TITLE
Pressing arrow key in the event editor sometimes scrolls to the top of the sheet

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#6828]
## Problem description

When nothing is selected in the event sheet and you accidentally press any of the arrow key (Left, Right, Up or Down), the event sheet is scrolled to the very top and the topmost event is selected.

## Attach a .c3p

Any project with a large event sheet, for example Kiwi Story template:
https://editor.construct.net/#open=kiwi-story

## Steps to reproduce

1. Open ePlayer sheet, scroll to the middle of the sheet
2. Make sure no event is selected
3. Press any arrow key

## Observed result

The event sheet is scrolled to the very top:

![GIF 25-03-2023 21-10-50](https://user-images.githubusercontent.com/36763350/227711309-c35615b3-72bd-4940-8f5a-b8e0ed1f07c8.gif)

## Expected result

Either nearest to the mouse cursor event should be selected, or nothing at all.

When you are working in a sheet with 500+ events and suddenly it scrolls to the very top, it's very anoying. It may take a long time to return back to the event you were editing.

Besides, there are Home/End keys to immediately move to the top/bottom of the event sheet. So this behavior for arrow keys is definitely not necessary.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.111
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 665 mb (0.9%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I believe this is by design and for accessibility. If you want to navigate an event sheet using the keyboard only, then the arrow keys are the main way to navigate events. If the arrow keys do nothing even if nothing is selected, then it's impossible to navigate event sheets by keyboard only without first using the mouse (an accessibility problem for people who have difficulty using pointing devices). Therefore if nothing is selected then the arrow keys will select an event and scroll accordingly. IIRC this was done based on another user's request.

**Comment by dop2000** [comment]
@AshleyScirra Again, this is BAD design! Try editing an event sheet with 1000 events, which scrolls to the very top every now and then - this is the opposite of accessibility!

There are special keys - Home and End which are used to scroll to the first and last event on the sheet. There is absolutely no reason for arrow keys to have this behavior.

**Comment by AshleyScirra** [comment]
I can't remember exactly, but I think the situation was something like someone saying it caused them physical pain to reach for their pointing device, in which case I think the correct decision is to prioritise avoiding causing someone pain. If you think the existing design should be changed please file a suggestion instead.

**Comment by dop2000** [comment]
Accessibility options are usually available in program settings to opt-in. If it's set by default without any way to turn it off, this inconveniences the other 99% of users.
