### ISSUE TITLE
Uncaught (in promise) Error: already loaded texture

### ISSUE THREAD

**Issue by KekGames** [Scirra/Construct-bugs#6830]
## Problem description

Using "Load image from URL" may lead to the game crash in browser. It freezes the game in Edge and Chrome (though in Chrome it's a bit inconsistent) with "Error: already loaded texture". There's Sprite object on Layout 1; the Layout 2 is blank. It happens when you switch from Layout 1 to Layout 2 before the image is loaded, then go back to Layout1. Also worth noting, that if you create the object on Layout 2 before switching back to Layout 1 - the issue doesn't appear.

## Attach a .c3p

https://drive.google.com/file/d/13K4AfC3jMHXp10vRbTYiuxv4ySOiU6vz/view?usp=sharing

## Steps to reproduce

1. Start the project from Layout 1, click on the screen to go to Layout 2
2. Click the screen to switch back to Layout 1
3. Try enabling some events in Event sheets and run the test again

## Observed result

The game freezes when you try to go back to Layout 1

## Expected result

No freeze

## More details

**Affected browsers/platforms:** Edge, Chrome, maybe others

**First affected release:** r317 as well as latest stable, didn't test earlier

## System details

<details><summary>View details</summary>

Uncaught (in promise) Error: already loaded texture
    at ImageInfo.LoadStaticTexture (imageInfo.js:6:290)
    at animationInfo.js:3:18
    at Array.map (<anonymous>)
    at AnimationInfo.LoadAllTextures (animationInfo.js:2:631)
    at runtime.js:2:445
    at Array.map (<anonymous>)
    at SpriteType.LoadTextures (runtime.js:2:436)
    at ObjectClass.LoadTextures (objectClass.js:14:462)
    at Layout._Load (layout.js:22:322)
    at C3Runtime._DoChangeLayout (runtime.js:89:62)

</details>

**Comment by WilsonPercival** [comment]
This seems to have been fixed in `r328b`.

https://github.com/Scirra/Construct-bugs/issues/6393

Always check in the latest beta.

**Comment by KekGames** [comment]
> This seems to have been fixed in `r328b`.
> 
> #6393
> 
> Always check in the latest beta.

Cool, thanks :)
