### ISSUE TITLE
Particle Set X to Touch.X not working in 'Is in touch' event

### ISSUE THREAD

**Issue by WimDeBacker** [Scirra/Construct-bugs#6844]
## Problem description

The spawn-coordinates of particles are not updated in the 'is in touch' event on iOS and Android (in Remote preview). 
+ Touch: Is in touch
-> Particles: Set X to Touch.X
-> Particles: Set Y to Touch.Y
-> Text: Append floor(Particles.X) & ", " & floor(Particles.Y) & ", "

The particles keep spawning on the coordinates from before the touch. 
The Particles.X & Particles.Y values are updated correctly (see text output in example), but not used as coordinates to spawn.

## Attach a .c3p
[TouchParticleXBug.zip](https://github.com/Scirra/Construct-bugs/files/11093746/TouchParticleXBug.zip)

## Steps to reproduce

1. Run the project on a laptop and see how the Sprite and Particles behave on mouse movement, this is the wanted behavior. 
2. Then run (I used Remote preview) the project on a touchscreen device (ios or android have the same problem) the particles should behave the same when using touch.

## Observed result

New particles not spawn on the new touch location. 

## Expected result

The particles should 'follow' the touch movement. 

## More details
- With Mouse: On movement, there are no problems, this works as expected (see example). 
- A sprite does follow the touch as expected (see example). 
- with 'use mouse input' option of the Touch object, in Chrome browser (witch disabled 'On mouse movement events'. ) it works as expected

Tested with remote preview on:
- iPad -> not following touch
- Android phone  -> not following touch

Thanks!
Wim De Backer

**Comment by AshleyScirra** [comment]
This is a mistake in your events. The mouse 'On movement' event also triggers with touch input, but instead of reading the movement value, you read the mouse position, which is always zero on mobile. It works correctly if you only use touch input in a reduced sample like this: [issue6844.zip](https://github.com/Scirra/Construct-bugs/files/11138058/issue6844.zip)

**Comment by WimDeBacker** [comment]
Ok, I see, excuses me.
So I have to put an extra condition 'not in touch' to the Mouse: On Movement event, when I want to use both?
+ Mouse: On movement
+ Touch: [X] Is in touch
