### ISSUE TITLE
Crash on pressing CTRL+R

### ISSUE THREAD

**Issue by Rhindon** [Scirra/Construct-bugs#6845]
## Problem description
With an open project, pressing CTRL+R causes a crash of the editor.

## Attach a .c3p

[The Ring v 3-1 ctrl-r bug report.zip](https://github.com/Scirra/Construct-bugs/files/11096192/The.Ring.v.3-1.ctrl-r.bug.report.zip)

## Steps to reproduce

1. Open C3.
2. Press CTRL+R before opening a project. Confirm that the editor merely reloads/restarts.
3. Open a project and press CTRL+R again. The crash should occur.

EDIT: Additional info that may or may not prove useful:
I tried this process again...once with any objects (at least one...which also happens to be part of a container, if that even matters) selected/highlighted. And then once again by clicking in a blank space in the layout so no objects are selected/highlighted. At first, it seemed that the crash occurred while an object was selected. But then I tried again with no objects selected and one time the crash did not occur and then yet another test (no object selected) and the crash _did_ occur.
I do not know if this will help or hinder finding the solution but I felt it relevant to share.

## Observed result

The editor crashed upon hitting CTRL+R.

## Expected result

Honestly, this was an accidental discovery. I was working in the editor and, since it is browser-based, I wanted to open a new tab in Chrome and I know that CTRL+T will do that even with C3 as the active window. I hit CTRL+R by mistake. So, what I had expected to happen was not something I could account for because I was previously unaware that CTRL+R even did anything. But, upon testing CTRL+R without opening a project first, I surmised that it merely reloads the editor. After opening a project, I would have expected the same thing - the editor reloaded but with no open projects.

## More details

**Affected browsers/platforms:** 
Chrome - Version 111.0.5563.111 (Official Build) (64-bit)
(I copied this line of info literally as the browser was downloading new updates.)

**First affected release:** 
C3 - r355 beta

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: created 30 render targets - seems a lot, is this right?
Stack: Error at qa.bXa (https://editor.construct.net/r335/main.js:1104:289) at window.assert (https://editor.construct.net/r335/main.js:1019:353) at window.GQb.lgb (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:139:486) at d.Wf (https://editor.construct.net/r335/projectResources.js:1328:174) at f6b (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:89:317)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Tue Mar 28 2023 22:13:30 GMT-0500 (Central Daylight Time)
Uptime: 13.6 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.111
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_provoking_vertex, WEBGL_video_texture, WEBGL_webcodecs_video_frame

</details>

**Comment by Rhindon** [comment]
FYI: I did a search for crashes involving CTRL+R...I did not find any so I'm assuming this is not a repeat post of a known issue.

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/6784

`Ctrl + R` starts animation preview.
