### ISSUE TITLE
Crash family cut and paste :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6846]
## Problem description

Construct crashes.

## Attach a .c3p

[crash_family_cut_and_paste_r335b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11104955/crash_family_cut_and_paste_r335b.zip)

## Steps to reproduce

1. Open a project.
2. Remove the last instance from the layout.
3. Cut out the family.
4. Insert a family.
5. Drag `Crash` to the layout.

## Observed result

https://user-images.githubusercontent.com/91274932/228650793-19467c8e-d3ba-4c60-a0f3-059cc378a8ea.mp4

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r335b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r335/projectResources.js, line 614, col 466
Message: Uncaught Error: missing instance variable value
Stack: Error: missing instance variable value at d.iP (https://editor.construct.net/r335/projectResources.js:614:472) at d.JVb (https://editor.construct.net/r335/projectResources.js:682:147) at d.Haa (https://editor.construct.net/r335/projectResources.js:685:60) at d.vg (https://editor.construct.net/r335/projectResources.js:805:389) at window.Pl.yRb (https://editor.construct.net/r335/components/editors/layoutView/layoutView.js:124:410) at CCG.aa.vla (https://editor.construct.net/r335/components/bars/projectBar/projectBar.js:117:253) at Array. (https://editor.construct.net/r335/components/bars/projectBar/projectBar.js:92:501) at CCG.oh.g.K.aKa.dispatchEvent (https://editor.construct.net/r335/main.js:1233:399) at rh (https://editor.construct.net/r335/main.js:377:372) at d.Cd (https://editor.construct.net/r335/main.js:1617:1)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Wed Mar 29 2023 22:36:37 GMT+0300 (Восточная Европа, летнее время)
Uptime: 450.8 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
