### ISSUE TITLE
Crashing construct 3 issue when closing the sprite Image Editor

### ISSUE THREAD

**Issue by euromikesurf** [Scirra/Construct-bugs#6847]
When setting image for the sprite when exiting the image editor now every time construct is crashing with a following error.

No matter what sprite i edit and what image i set, it sets it and saves ok but then crashes.

What does it mean?

What is causing it? The game works fine else

Error report information

Type: unhandled exception
File: https://editor.construct.net/?startTour, line 0, col 0
Message: ResizeObserver loop limit exceeded
Stack: null
Construct version: r327.3
URL: https://editor.construct.net/?startTour
Date: Wed Mar 29 2023 23:41:26 GMT+0100 (Western European Summer Time)
Uptime: 1844.4 s
Platform information

Product: Construct 3 r327.3 (stable)
Browser: Chrome 111.0.5563.146
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[111.0.0.0](http://111.0.0.0/) Safari/537.36
Language setting: en-US
WebGL information

Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by DiegoScirra** [comment]
This is a problem with a browser extension. We have received reports from the Last Pass extension causing this crash, but it could be another one. Try disabling your extensions one by one until you find which one is it. You can also just disable them all when using C3.

We don't fix issues caused by extensions because they are out of our control.
