### ISSUE TITLE
Animation Editor "guessing polygon shape" by default

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#6848]
## Problem description

This isn't exactly a bug but it also is kinda buggy at times I guess. Because this is really really not helpful when importing animations and it looks like this.

![neither](https://user-images.githubusercontent.com/31101309/228875484-4adcb6e2-954f-4033-906e-45b617de2741.PNG)
![neither3](https://user-images.githubusercontent.com/31101309/228875494-d3a25f97-eb1f-4881-a7ee-dcf99f3a596c.PNG)
![nothelping](https://user-images.githubusercontent.com/31101309/228875499-a94207b7-826e-49ae-8a6d-9c0e92b8c026.PNG)

At least one seems to have guessed the bounding box, but even then it added 4 extra points that do nothing but add complexity where it isn't needed.

## Steps to reproduce

1. Import graphics (especially if they're complex)

## Observed result
The resulting polygon shape gets automatically guessed on import, and at times is completely unuseable anyway.

## Expected result

Just default to the bounding box? Or add another default option like for animation speed.
![image](https://user-images.githubusercontent.com/31101309/228876460-df80e117-d02f-4afc-b633-72299bc6adca.png)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.147
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.3 gb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by XHXIAIEIN** [comment]
+1  https://github.com/Scirra/Construct-bugs/issues/4980
If not willing to spend time optimizing the quality of this guess, then please set the default to bounding box, at least it will not make mistakes.

**Comment by Tarek200** [comment]
Hoh I just not long ago requested the same thing on the forum:

**Comment by Wackytoaster** [comment]
I could have sworn I did make a suggestion already but now I can't find it? :V Duh... but yeah, feel free to make it! :D

**Comment by Tarek200** [comment]
> I could have sworn I did make a suggestion already but now I can't find it? :V Duh... but yeah, feel free to make it! :D

Hoh, I just opened recently a feature request for another thing and hit submit, all went well without any errors but after I couldn't find it so definitely there is something wrong with that platform as I had to redo everything again.

If you open it again make sure you post the link on the Forum thread above so I can vote for it and maybe more users if they see it.
