### ISSUE TITLE
New effect compositor renders a black square in the editor but not at runtime

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#6849]
## Problem description

It is the first time I've seen this happen since the release of the effect compositor on r270, but I've got an effect that renders a black square in the layout view instead of the shader result.

The shader shows no errors in the console and works just fine at runtime.

## Attach a .c3p

[old tv filter bug repro.zip](https://github.com/Scirra/Construct-bugs/files/11113551/old.tv.filter.bug.repro.zip)

## Steps to reproduce

1. Open the layout

## Observed result

![image](https://user-images.githubusercontent.com/11213825/228896365-66a65aba-9eb1-4665-bb9a-fcd879738b77.png)

## Expected result

![image](https://user-images.githubusercontent.com/11213825/228896440-46fcfb07-dcb3-4eab-a663-a503cb7b1dfe.png)

## More details

The file I've sent you was initially a C2 project, and the effect was initially a C2 effect that I ported to C3 about 4 years ago and it's worked just fine until r270

**Affected browsers/platforms:** tested only on Chrome 

**First affected release:** r270 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.3 (stable)
Browser: Chrome 111.0.5563.111
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 540 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by skymen** [comment]
I genuinely have NO clue what could be causing this either.
It's the first time I've ever seen this.

My thought process was that this could be due to rendering context differences between the editor and the runtime, and that one of thems causes the rendering to silently fail, or to fail to pass some data properly.

As such, could be a good idea to change the shader code and remove parts of it until the issue disappears. I can try to do that and see if I can pinpoint which part of the shader is causing the issue.

I understand if you close this as there is no reason to think this happens with any other shader besides this one specifically.

**Comment by AshleyScirra** [comment]
Cleaning up some old issues, and I don't think this is realistically going to get fixed, so closing as wontfix. If anyone really wants it to be fixed, a minimal shader would be slightly easier to work with, but the effect compositor is still extremely difficult to debug - all issues like this end up being really difficult to figure out. (FWIW filing issues closer to the time the change is made makes it much more likely it can be fixed, as the longer the time passes, the harder it is to re-figure out how all the internals of the code are working relative to the older codebase.)
