### ISSUE TITLE
Frequent Mobile Ad cancellation

### ISSUE THREAD

**Issue by bitropAlex** [Scirra/Construct-bugs#6850]
## Problem description

It often happens that instead of showing ads, a cancellation occurs, as if the user had closed the ad. 
"On Rewarded Cancelled" event triggered and it can be from 5 to 10 times in a row.
Test mode is enabled

## Attach a .c3p
[AdTest.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11114061/AdTest.c3p.zip)

## Steps to reproduce

1. Export for IOS
2. Install on phone
3. Run app
4. Click Show Ad button a few time
5. if it doesn't reproduce, restart the application or try later (the bug is not permanent)

## Observed result

"On Rewarded Cancelled" Event triggered  from 5 to 10 times in a row.

## Expected result

Ads are shown

## More details

https://user-images.githubusercontent.com/129107647/228913149-38179103-c9a7-4a54-9789-1dc360b1f20c.mp4

**Affected browsers/platforms:** IOS

**First affected release:** r327.3 (stable)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r327.3 (stable)
Browser: Chrome 111.0.5563.110
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.2
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Not sure about it, but this might just be the expected behaviour from Google's SDK.

From looking at the video, you are showing an advert successfully and then proceed to spam with more requests, neither Google nor Apple like it when application developers do that. It's a sure fire way to get your application rejected from either Google's Play Store or Apple's App Store.

It's entirely possible the SDK is just pre-emptively rejecting requests if they are done very quickly after showing an ad and C3 is just dealing with those rejects the best it can.

**Comment by bitropAlex** [comment]
Well, it turns out this is not your bug
Thanks

**Comment by bitropAlex** [comment]
hmm i checked also different cases and it reproduces even with intervals of minutes or hours or even days

**Comment by DiegoScirra** [comment]
I haven't been able to reproduce this. If you wait a reasonable amount of time between ad requests it works, that is the intended use case, you are supposed to show ads sparingly anyway and if there is a failure loading an ad, the application should just transparently ignore the failure.

If you try to request an ad immediately after a failure, like the example does, it might work sometimes, but most likely the SDK will pre-emptively reject that kind of spam.

**Comment by DiegoScirra** [comment]
Testing this is very difficult but I think that the fix for #6966 fixes the issue with the **"Reward Cancelled"** events being fired, still as I said in the comment before, spamming the creation of ads will most likely result in **"Failed to load"** events being fired.
