### ISSUE TITLE
Cut/paste of layout can allow duplicate instance variable names

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6851]
## Problem description

Construct crashes.

## Attach a .c3p

[crash_instance_variable_family_mycologist_r335b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11121675/crash_instance_variable_family_mycologist_r335b.zip)

## Steps to reproduce

1. Open a project.
2. Cut out `Layout 2`.
3. Remove `Cockroach` from the project.
4. Add a variable to the family.
5. Insert layout.
6. Make a clone of `Cockroach`.

## Observed result

https://user-images.githubusercontent.com/91274932/229117583-2e422c30-c0ed-4de9-9209-28808111d540.mp4

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r335b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: name already in object class namespace @ Error: name already in object class namespace at new d (https://editor.construct.net/r335/projectResources.js:609:241) at qa.j (https://editor.construct.net/r335/main.js:1111:44) at d.vC (https://editor.construct.net/r335/projectResources.js:617:388) at d.vT (https://editor.construct.net/r335/projectResources.js:675:523) at d.vT (https://editor.construct.net/r335/projectResources.js:704:223) at Dfb.Xeb (https://editor.construct.net/r335/components/bars/projectBar/projectBar.js:123:305)
Stack: Error: name already in object class namespace at new d (https://editor.construct.net/r335/projectResources.js:609:241) at qa.j (https://editor.construct.net/r335/main.js:1111:44) at d.vC (https://editor.construct.net/r335/projectResources.js:617:388) at d.vT (https://editor.construct.net/r335/projectResources.js:675:523) at d.vT (https://editor.construct.net/r335/projectResources.js:704:223) at Dfb.Xeb (https://editor.construct.net/r335/components/bars/projectBar/projectBar.js:123:305)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Fri Mar 31 2023 15:10:44 GMT+0300 (Восточная Европа, летнее время)
Uptime: 50.6 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Another variant to check: #6853

**Comment by AshleyScirra** [comment]
Fixed for next beta, but #6853 looks like a more complicated case, so closing this issue and reopening that one.
