### ISSUE TITLE
Platform behavior doesn't land properly on moving solids

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#6852]
## Problem description

😢 

https://user-images.githubusercontent.com/31101309/228973815-98f37e86-b562-44cd-b2b4-f8383c370ee1.mp4

## Attach a .c3p
(see reply)

## Steps to reproduce

1. Preview

## Observed result

The square does get pushed up by the moving solid, but doesn't land on it as expected.

## Expected result

Square should land on moving solid.

## More details
Probably related https://github.com/Scirra/Construct-bugs/issues/4239
Maybe related https://github.com/Scirra/Construct-bugs/issues/4406 https://github.com/Scirra/Construct-bugs/issues/4564

Since I'm already here and currently dealing with collision detection myself (I just wrote a continuous collision detection thingy today for my game) shouldn't there be a better way to handle all these edgecases? Or collisions in general? Especially when things start moving it seems like everything goes bonkers, and you've implemented a bunch of threshholds that when too high cause issue X and when too low cause issue Y.

From my perspective at minimum what would be needed is to
- know the position & velocity of both objects to check collision against
- a collision algorithm that takes both object velocities into consideration, ideally framerate independent
- (not taking into account, resizing & non-linear movements)

Constructs behaviors have a variety of velocities that can "overlap", and some behaviors do not even report a velocity at all (sine, tween) though the "true" velocity can be calculated by comparing current position to previous position. (Not sure how expensive that would be but it seems ok)

And the current discrete collision detection is as such framerate dependent. This is usually ok when games run at predictable framerates, but nowadays that is not always the case, especially on PC. While higher framerates usually are good since they increase precision, an unexpected lower framerate will cause those exact issues (phasing through jumpthrough platforms etc.)
From my research I found options. Surely there has to be a better way to handle all this stuff?

- using a fixed timestep and working within those boundaries (not an option with Construct because of the browser limitation?)
- swept collisions/sweptAABB (though I could not find a workable javascript implementation). Obvious downside is it's requirement of non-rotated bounding boxes.
- Continous collision detection (what I ended up writing for myself. Works pretty well, but obviously expensive)

Doesn't the bullet behavior use something like that for it's stepping mode?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 111.0.5563.147
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 133 gb
Storage usage (approx): 4.3 gb (3.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I think the particular quirk in this case is that the moving platform moves upwards faster than the jump speed of the platform behavior. Therefore when the player jumps and thinks it's in the air, the solid platform beneath it immediately pushes upwards in to the player faster than they are already moving. The platform behavior did not properly handle this specific case, but I think I have a fix for it in the next beta.
