### ISSUE TITLE
JSON:  parse a empty string data, warn in the console

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#6856]
## Problem description

I wanted to initialize a JSON object, so I parsed an empty string and it worked.

![Snipaste_2023-04-02_03-18-58](https://user-images.githubusercontent.com/45864744/229310121-f5339dfb-98f1-4c25-bcb6-16eca61f1a51.png)

However, I see an warn in the console.
![Snipaste_2023-04-02_03-17-50](https://user-images.githubusercontent.com/45864744/229310086-f9b088bd-f366-4021-bdc7-30323989e499.png)

But this doesn't happen if I follow the spec to complete the curly braces
![Snipaste_2023-04-02_03-16-47](https://user-images.githubusercontent.com/45864744/229310074-8fd7d9f9-00a9-4438-b340-ee43c782f1d8.png)

## Attach a .c3p

[json-parse-empty-string.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11130394/json-parse-empty-string.c3p.zip)

## Expected result

C3 should be able to automatically handle this situation, let it autocomplete.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
I don't think there is a mistake here. Why are you doing initialize? You will get the same error if you write any invalid data like `"a"`.

**Comment by AshleyScirra** [comment]
This is not a bug. An empty string is not valid JSON.
