### ISSUE TITLE
Crash impudent substitution instance var type close project :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6857]
## Problem description

Construct crashes.

## Attach a .c3p

[crash_impudent_substitution_instance_var_type_close_project_r335b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11130702/crash_impudent_substitution_instance_var_type_close_project_r335b.zip)

## Steps to reproduce

1. Open a project.
2. Cut out the instance.
3. Change the sprite's private variable type to `String`.
4. Paste the instance on the layout.
5. Close the project.

## Observed result

https://user-images.githubusercontent.com/91274932/229316197-1f0e1c74-0618-4759-89f0-c5b5c6dedc32.mp4

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r335b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: released sprite instance was never initialized @ Error: released sprite instance was never initialized at dLb.Instance.B (https://editor.construct.net/r335/plugins/allEditorPlugins.js:226:448) at d.B (https://editor.construct.net/r335/projectResources.js:786:243) at d.B (https://editor.construct.net/r335/projectResources.js:805:140) at d.B (https://editor.construct.net/r335/projectResources.js:679:29) at d.B (https://editor.construct.net/r335/projectResources.js:1723:239) at CCG.Jn (https://editor.construct.net/r335/main.js:892:26)
Stack: Error: released sprite instance was never initialized at dLb.Instance.B (https://editor.construct.net/r335/plugins/allEditorPlugins.js:226:448) at d.B (https://editor.construct.net/r335/projectResources.js:786:243) at d.B (https://editor.construct.net/r335/projectResources.js:805:140) at d.B (https://editor.construct.net/r335/projectResources.js:679:29) at d.B (https://editor.construct.net/r335/projectResources.js:1723:239) at CCG.Jn (https://editor.construct.net/r335/main.js:892:26)
Construct version: r335
URL: https://editor.construct.net/r335/
Date: Sun Apr 02 2023 00:58:00 GMT+0300 (Восточная Европа, летнее время)
Uptime: 54 s

Platform information
Product: Construct 3 r335 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
