### ISSUE TITLE
waterBackground Incorrect distortion at edges

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6864]
## Attach a .c3p

[waterBUG.zip](https://github.com/Scirra/Construct-bugs/files/11140060/waterBUG.zip)

## Steps to reproduce

1. preview the project
2. move mouse to the viewport edges

## Observed result
sprite is incorrectly distorted, texture is stretched to the edge.

https://user-images.githubusercontent.com/89512047/229560640-378bd0ae-1086-4a5b-98fb-b31328ebffe1.mp4

## Expected result
Sprite is correctly cut off at the edges.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid I don't think this is feasible to fix. The problem with warping effects near the edge of the screen is it can end up trying to sample pixels outside the window. Nothing is rendered there so all it can do is repeat the last row of pixels.
