### ISSUE TITLE
Multiplayer Object: Player often didn't leave the room using "Leave room" action and getting kicked by host didn't completely kicks the player out but still said in a room / in a same room.

### ISSUE THREAD

**Issue by OliverL65** [Scirra/Construct-bugs#6872]
## Problem description

I tried to make a function when the player presses the leave button, it will leave. But the bug won't let me make the player completely leave.

And then, I tried to use another method: Requesting the host to kick the player out. It also didn't completely leave the room, but the player will not be able to join a new room.

I looked at the debugging console (or something like that) and it said the player still in the same room and didn't completely leave too. Please fix it as fast as possible, I really need that to fix my game lobby bug. Thank you.

## Attach a .c3p
[game.zip](https://github.com/Scirra/Construct-bugs/files/11147334/game.zip)

(I changed the .c3p extension to .zip because it won't let me upload the file: it didn't support the extension, as I have seen in documentation, it said .c3p file is basically a renamed .zip extension, so that's the reason I changed it.)

## Steps to reproduce

1. Player presses the 'leave server' button while in a room.
2. It will trigger the function like "On touched object/something like that".
3. The code will make the player leave the room by action 'Leave room'.

Another way to make the player leave :
1. Player presses the 'leave server' button while in a room.
2. It will do the same as number 2 before.
3. The code will request host to kick the player instead by: Send message to host with a tag similar to 'kick' with player username message.
4. And then, host will use action 'Kick player' with the player from last message received, that is the player username or something like that.

## Observed result

It didn't leave the room completely.

By the second way, it also didn't completely kick the player out of the room.

## Expected result

I want to make the player 'completely' leaves the room.

## More details

The game project is made in Google Chrome browser (chromium) with the latest update (probably).

Issue occurred in website (html), and etc.

**Affected browsers/platforms:** 
Google Chrome (chromium)
Microsoft Edge (chromium)
Mozilla Firefox

**First affected release:** 
Probably tested as broken in r320(s).

## System details

<details><summary>View details</summary>

PASTE HERE
Platform information
Product: Construct 3 r327.3 (stable)
Browser: Edge 111.0.1661.62
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
Language setting: en-US

Local storage
Storage quota (approx): 113 gb
Storage usage (approx): 100 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks like the same mistake in your project as #4944. Event 47 in 'Home' leaves the room, which is asynchronous and takes some time to complete, but disconnects from the signalling server immediately before it completes. So you are likely left in an inconsistent state where the player is still in the room on the signalling server. Make sure you use 'Wait for previous actions to complete' so async actions finish before proceeding to the next action. Also please note to further investigate we'd need a minimal project as per the bug report guidelines - the provided project has over 100 events, which is usually infeasible to investigate.
