### ISSUE TITLE
Copying Condition can then be pasted in Comment 😊

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#6878]
If you click paste while creating a comment, it will paste data from the condition. 

I think it's suppose to just not paste this, and stay blank, since it's not appropriate context.

e.g.

`{"is-c3-clipboard-data":true,"type":"conditions","items":[{"id":"key-is-down","objectClass":"Keyboard","parameters":{"key":37}}]}`

## Steps to reproduce

1. Try on any project.
2. Press Copy, while a condition is selected
3. Press Q (to make a new comment)
4. Press Paste

## Visual before and after

![image](https://user-images.githubusercontent.com/5744908/230301750-f2cf09f3-565a-4b6f-987d-087daa166808.png)

![image](https://user-images.githubusercontent.com/5744908/230302175-84775326-aca6-422b-be05-d7ea10d5cffd.png)

Tested in Chrome & Brave

**Comment by dop2000** [comment]
This is definitely not a bug.. When you copy events in C3 to clipboard, they are converted to plain-text JSON (which is a great thing for many reasons). 
And you can paste any text into comments, even those JSON strings.
