### ISSUE TITLE
console full of errors

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6879]
## Problem description

there are a lot of errors in the console of the editor.

## Attach a .c3p

no project required

## Steps to reproduce

1. open c3
2. press f12

## Observed result
![errorsInCOnsole](https://user-images.githubusercontent.com/89512047/230439267-9505d65a-e150-4a5c-85a0-947be980ace6.png)

console is full of errors

## Expected result
no errors in console

## More details
while c3 remains functioning without problems, these errors can be scary, look unprofessional and can make it harder to see relevant errors. 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Those errors are false positives. I don't know why they happen, but they don't affect the normal working of Construct, and given most people don't need to look at the console for Construct, I don't think it warrants spending our limited time and resources to investigate.

**Comment by fredriksthlm** [comment]
If Google are sending you errors from their login api, and tells you that your editor tries to load data from some un-allowed origin I really think you should look into it. This just recently started to happen.

Every time something happens in the editor, the users are told to look into the console, then they see all of this, it just doesn't look good.
