### ISSUE TITLE
Browser runs out of Memory when Cropping a Large Number of Animations

### ISSUE THREAD

**Issue by Laserwolve** [Scirra/Construct-bugs#6883]
## Problem description

Construct 3 runs out of memory if you try to crop too many animations to their transparent edges.

## Attach a .c3p

Hosted on Google Drive because it's 103 MBs. : https://drive.google.com/file/d/1b4NHw205t9pQdGeVsqZIKwlC16CuI4te/view?usp=share_link

## Steps to reproduce

1. Open project
2. Open sprite
3. Click "Apply to all animations" under the "Crop transparent edges" dropdown

## Observed result

![image](https://user-images.githubusercontent.com/87336074/230648246-a0e5af3a-957f-45a9-9cc8-36ec4f9539d9.png)

## Expected result

All animations to be cropped to their visible pixels

## More details
Obviously highly dependent on RAM availability. I'm able to consistently reproduce with 32 GB RAM on Windows 11 with nothing else open.

This same crash used to happen when dragging and dropping in a large amount of animations as well. It seems like Construct now "loops through" the animations to be added, instead of all at once, to prevent the crash. Maybe the same logic could be applied here; looping through and cropping instead of cropping everything simultaneously?

**Affected browsers/platforms:** All Chromium browsers, Windows 11

**First affected release:** Unknown

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Edge 111.0.1661.62
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36 Edg/111.0.1661.62
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 3.5 gb (1.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

Keep in mind that while Construct won't crash anymore, cropping that amount of animation frames at the same time can take a while. Using the test project as an example, cropping all the animations in one go took about 2 minutes in my computer. That was about 6700 animation frames in total.

**Comment by Laserwolve** [comment]
Thanks @DiegoScirra! You rock!
