### ISSUE TITLE
r336 Export NWJS BUG video

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-bugs#6884]
https://youtu.be/uEauJnzKL2k

**Comment by GeekManOfficial** [comment]
man, read report guidelines pls. Stop gringe

**Comment by JonaszO** [comment]
> man, read report guidelines pls. Stop gringe

 guildness for you
  I see Crash when i try export game using
  i expect to receive compiled nwjs archive without 10 crash a day

man, if you are not from the team, do not write your posts especially if you have no influence on the operation of C3, unless you are looking for attention  so you already have mine

**Comment by WilsonPercival** [comment]
@JonaszO Can you message me on discord? My nickname is Wilson(Игорь)#7140. I have time and could help you find and report any bugs you have. Your post will be closed without review because you didn't provide a project file.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
