### ISSUE TITLE
Paint Menu Crash

### ISSUE THREAD

**Issue by hex-waffle** [Scirra/Construct-bugs#6885]
In the paint menu for objects if you go from line tool to paint bucket construct 3 will crash.

**Comment by hex-waffle** [comment]
Update: the line tool crashes construct 3 v336

**Comment by WilsonPercival** [comment]
> In the paint menu for objects if you go from line tool to paint bucket construct 3 will crash.

@hex-waffle Could you write the steps to play or record a video? I don't have a crash.
