### ISSUE TITLE
Can't Pick Parent of a Hierarchy Child on the frame the Parent is created thanks to a "Create with hierarchy" action

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#6886]
## Problem description

I have a Hierarchy with a Parent and a Child
If I use the action "Create Object Parent, create hierarchy : True"
I can't pick the parent of the instanciated Child during the first frame.

## Attach a .c3p

[Bug_Report_CantPickParentOnHierarchyChildCreated.zip](https://github.com/Scirra/Construct-bugs/files/11182690/Bug_Report_CantPickParentOnHierarchyChildCreated.zip)

## Steps to reproduce

1. Launch the preview, the Hierarchy already there manage to pick the Parent of the Child
2. Left Click to spawn a new Parent with its hierarchy Child
3. The newly created Child can't pick its parent during the frame corresponding to the creation of the Hierarchy.

## Observed result

"❌ Can't Pick Child's own Parent when Child is created"

## Expected result

"✅ Can Pick Child's own Parent when Child is created"

## More details

It's probably a race condition issue. The "Child : On Created" event is called before the Child is actually added as a Hierarchy Child of Parent.
Maybe the Children are even created before the Parent ? so this is why we can pick the children of a Parent on the first frame but not the opposite ?
However it is very important to not break the fact we can pick the Children of a Parent on the first frame the parent is created with Hierarchy, as it works right now. (because this is 10x more important)
In fact nothing should be changed regarding the behavior of the first frame of a Hierarchy Instanciation exept maybe finding a trick so we can immediatly pick the parent of the newly created child as well.
**If it's impossible to be done without breaking something else or without badly impacting performance, 
then it should probably NOT be fixed even if it's a pain to deal with TBH.** 
But i suppose under the hood C3 can handle that kind of annoying race conditions ?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Workaround: 
[CantPickParentOnHierarchyChildCreated_js_solution.zip](https://github.com/Scirra/Construct-bugs/files/11183059/CantPickParentOnHierarchyChildCreated_js_solution.zip)

**Comment by AshleyScirra** [comment]
This turns out to just be the 'Pick parent' version of a similar issue with 'Pick children' filed in #4997. Fixed for next beta.
