### ISSUE TITLE
Picking Nth, Hierarchy Instances not working if greater than 0 when setup with editor

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-bugs#6892]
Construct 3 - Release 336 stable
Chrome  111.0.5563.147
Windows 11

I believe the parenting hierarchy editor setup doesn't work with the "Pick Nth Child Instance " with a instance value of > 0.

I've created a sprite (pink box), and 2 copies of another sprite (purple box) .  I then connected the furthest one away to the middle purple box via the "add selection to this link" right click menu.  Then I connected the middle one to the first (pink box).  Similar to how a Shoulder -> elbow -> wrist might be connected.

When attempting to use the "Pick Child Instance 1" option it does not allow me to do actions on the furthest away child.  However if I choose Child instance 0 it works.  

In the "Skeleton Example" I've tried changing line 4 to a different instance number other then 0 and it appears to work there.  I suspect the difference is that in this example all of the pieces are connected on "Start of layout" instead of ahead of time using the editor "Attach hierarchy" menu.

Thank you for your time.

[c3-hierarchybug.zip](https://github.com/Scirra/Construct-bugs/files/11187856/c3-hierarchybug.zip)

**Comment by justifun** [comment]
I think my way of thinking appears to be different.  It seems that if you have a child of a child that won't work, but if you add both children to the same parent then you can select instance 1,2,3 etc.  
So what's the correct way to targeting a child of a child?

**Comment by WilsonPercival** [comment]
> I think my way of thinking appears to be different. It seems that if you have a child of a child that won't work, but if you add both children to the same parent then you can select instance 1,2,3 etc. So what's the correct way to targeting a child of a child?

@justifun I may be wrong, but it always seemed to me that hierarchies have only one level of inheritance: `Parent -> Child`.
