### ISSUE TITLE
Custom action for an Object picks all instances in its Family

### ISSUE THREAD

**Issue by davidmarchand** [Scirra/Construct-bugs#6895]
## Problem description

All objects in a **Family** execute a **Family custom action** at the same time, even if the event only calls for a single member of the Family to do so.

## Attach a .c3p

[CustomActionFamilyPicking.zip](https://github.com/Scirra/Construct-bugs/files/11193757/CustomActionFamilyPicking.zip)

The entire event sheet is just 2 events:

![image](https://user-images.githubusercontent.com/17801587/230992618-19d0ded5-702d-4eae-934e-ee4d1dbb6568.png)

## Steps to reproduce

1. Run the game
2. Click anywhere on the screen

## Observed result

Both **Text objects** rotate at the same time, then they rotate again after half a second.

## Expected result

The **Red** text object should rotate first, then **Blue** should rotate after half a second.

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
