### ISSUE TITLE
Bug DragDraw

### ISSUE THREAD

**Issue by M4riot** [Scirra/Construct-bugs#6898]
## Problem description-> 
When starting the Layout the drag functionalities are not working, but if you start the layout that has direct drag and drop it works

## Steps to reproduce

1.Launch the project from the Start page and click the Start button
2.Try dragging the words in sprites down the next page
3.Open the direct layout that has drag and drop and try to drag

## Observed result
Sprites are not dragged

anything

## Expected result
After changing the layout, it was expected that the objects would be dragged

## More details - 
That the objects are dragged and when positioned and released on the right place they go up 1 point and delete that dragged object and the other object appears

**Affected browsers/platforms:** 
All

now

**First affected release:** 
now

## System details - When starting the main layout numbers between 1 and 2 are randomized and saved in a global variable, to start a phase page it compares the variable number when clicking on the start button, inside the phase there are options to drag and drop in the right places and increase the number of points, when you finish all of them you should send them to the next phase

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please see the bug report guidelines. We need a minimal project with the fewest events and objects in order to investigate reported issues. Otherwise it's likely it's just a mistake in your project, which is common.
