### ISSUE TITLE
tadaaaam another update another bugs and crashes

### ISSUE THREAD

**Issue by scribe80** [Scirra/Construct-bugs#6902]
problem with copy events only in relase 337
everything are shown in gif, spend minute to watch this without closing issue as 'completed'

https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExYTRiY2RmMWVjMGY3N2I1ODcyOWJjMWZiNzZlNDhjMjlmNmVlYmZiZSZjdD1n/ZjOg3r7NK7HXt2p3K0/giphy.gif

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
