### ISSUE TITLE
gpuutilisation or debugger gpu profiler not working with webGPU

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6904]
## Problem description
gpuutilisation or debugger gpu profiler not working with webGPU

## Attach a .c3p
no project required

## Steps to reproduce

1. make sure webGPU renderer is enabled
2. start preview with debugger

## Observed result
gpuutilisation returns NaN and GPU profiler states: GPU profiler is not supported...

## Expected result
we can see the gpuutil

## More details
tested on chrome canary 114.0.5709.0
Or maybe you have turned it of on purpose so we inquisitive users can't get some early performance tests done? ;D
If that is the case I would say performance testing is relevant for porting shaders to make sure there is no performance regression

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Performance timing isn't supported by WebGPU yet, but it will be added in due course when it's supported by browsers. This is a known missing (optional) feature so closing this issue.
