### ISSUE TITLE
webGPU text rendering draw calls significally higher

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6905]
## Problem description
webGPU text rendering draw calls significantly higher

## Attach a .c3p
[webGPUtext.zip](https://github.com/Scirra/Construct-bugs/files/11204588/webGPUtext.zip)

## Steps to reproduce

1. preview project with webGL and see draw calls
2. preview project with webGPU and see draw calls
## Observed result
webGL has lower draw calls

## Expected result
both have around the same draw calls

## More details
since text rendering draw calls are always a bit of a pain point in c3 a peformance regression here can be really detrimental.
Maybe it's all still work in progress so test like these are worthless for now?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I looked in to the performance of text rendering in the WebGPU renderer and I think it comes down to a performance bug in Chrome. I [filed a Chrome issue here](https://bugs.chromium.org/p/chromium/issues/detail?id=1456394) and will follow-up there.
