### ISSUE TITLE
Ghost Racer Templace webGPU error

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#6906]
Ghost Racer Templace webGPU error
## Attach a .c3p
Ghost Racer Template
https://editor.construct.net/#open=ghost-racer

## Steps to reproduce

1. start preview with webGPU enabled
2. press f12

## Observed result
canvasManager.js:11 Error creating WebGPU renderer:  GPUPipelineError: Depth stencil state is not present when fragment stage ([ShaderModule], entryPoint: main) is writing to frag_depth.

## Expected result
no error

## More details
happens with a few other, but not all, 3d example projects as well.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by MikalDev** [comment]
Similar issue: running 2D Example project, webgpu works. Add 3DShape to the same project and the above issue appears. Perhaps related to the default frag shader for writing depth depending on transparency?
