### ISSUE TITLE
Android Touch (Touch.Speed & Touch.Angle) Gives Incorrect Values

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-bugs#6919]
So the issue is that on Android a simple touch without moving the finger makes the values of the "Touch.Speed" give incorrect values, sometimes registering speeds of (150 to 500) when they should be cero because was no swipe or finger movement.

Also, the same happens with "TouchAngle" Instead of showing angle zero because there is no touch movement it gives you instead incorrect angles.

**This is causing me many issues like:**
**1**-My slider on touching it, I set the Slider Speed to the "Touch.Speed" so because it never registers the (Touch.speed =0) when you do a touch and you dont move the finger, basically no swipe, so this causes the slider to be constantly in motion and the speed is never zero.

**2**-The second issue is, I have the Level icons pinned to the slider that you need to touch to go to the Levels but because I have a condition that checks "Slider.Speed = 0" then when you touch any icon never triggers to go to the levels because the slider is always speed greater 0.

**Note:**

On iPhones & PC: 
Works correctly, if you touch and dont move the finger it will give you:
Touch.Speed = 0
Touch.Angle = 0

[1-Android_TouchBug.zip](https://github.com/Scirra/Construct-bugs/files/11228430/1-Android_TouchBug.zip)

## Steps to reproduce

1. Open the project and export it as "Web HTML5"
2. Upload it to your Website
3. Visit your website using an Android phone
4. Touch the Screen without moving the finger or swipe
5. Look at the (Touch.Speed & Touch.Angle) Values

## Observed result

Touch.Speed  is not  = 0
Touch.Angle is not  = 0

## Expected result

Touch.Speed  is = 0
Touch.Angle is = 0

## More details

Chorme

-Can remember the first version that I used with this issue because the issue exist since  2+ years ago and I never debug it properly as I thought was something with my code and I put it in one side until now.

-R337-2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r337.2 (beta)
Browser: Chrome 111.0.5563.149
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 360 mb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can't reproduce this on Android with Remote Preview. If I touch the screen but hold steady it does report a touch speed of 0. Am I missing something?

**Comment by WilsonPercival** [comment]
I can't reproduce either. I tried `Remote Preview` and `Export`. Everything seems to be working well.

**Comment by Tarek200** [comment]
> I can't reproduce this on Android with Remote Preview. If I touch the screen but hold steady it does report a touch speed of 0. Am I missing something? Does this reproduce for you with Remote Preview?

That's very strange as I can replicate it constantly in my:

 -Galaxy S8 -------- Using Android version 9
 
-Tablet Galaxy Tab A (2016)  -------- Using Android version 8.1.0 


For me, this issue is not random as its permanent, it happens all the time:
Here is a Video showing the issue on the Galaxy S8 while using C3 "Remote previewing" 

[Videos Compreesed.zip](https://github.com/Scirra/Construct-bugs/files/11234683/Videos.Compreesed.zip)

**Comment by therealPaulPlay** [comment]
I have a Galaxy S8 and it works for me (in an export).

**Comment by Tarek200** [comment]
> 

Thanks for testing Guys!

I dont know what to think now if the problem was only occurring in one of my devices then because you guys can't reproduce, I will say is my device's fault, but since it happens in both devices not sure what to think. Also, we have the same device S8 so this is very weird.


**I just found another device to test:** 
Lenovo Tab M10 FHD plus
Android 10
And it doesn't happen here it works perfectly

**Comment by therealPaulPlay** [comment]
My S8 is running on android 12 though (custom rom), so maybe it is specific to one ui, or more likely, older android versions?

**Comment by Tarek200** [comment]
> My S8 is running on android 12 though (custom rom), so maybe it is specific to one ui, or more likely, older android versions?

I see, that makes sense as mine are both Bellow Android 10 and they dont show any available updates.
Thanks for the info I think that is very important as at the moment it looks like is most likely depending on the Android version.
I'm trying to see if I can recreate the swipe by using normal events so I dont have to rely on (Touch.Speed & Touch.Angle) but looks quite challenging though, lets's see.
