### ISSUE TITLE
Please whitelist "cordova-plugin-color-picker" (build service)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#6921]
This addon is used to display the native color picker dialogue on ios and android. 

github: https://github.com/avargaskun/cordova-plugin-color-picker
npm: https://www.npmjs.com/package/cordova-plugin-color-picker?activeTab=dependencies

**Comment by AshleyScirra** [comment]
Can you explain why you need this instead of `<input type="color">`? That's HTML's existing way of showing a standardised color picker and works across all platforms including iOS and Android.

**Comment by therealPaulPlay** [comment]
Didn't know about this. But can you also customize it like you can with the plugin? Also, this solution doesn't require an html element inside of construct and you can trigger it whenever you want. Additionally, if -webkit-user-select: none is set, it doesn't work, so you can't really make an invisible button because it will be highlighted.

**Comment by AshleyScirra** [comment]
Construct itself uses `<input type="color">`, and when necessary, it uses an invisible one to trigger the color picker when it wants. Are you sure you can't just do that as well? It seems like a complicated way to reinvent an existing HTML feature that doesn't port from mobile to desktop.

**Comment by therealPaulPlay** [comment]
Yeah, you could just create a new html button the size of a screen etc. but the issue is that you can‘t time it that way, so it works for most instances, but not for all and on mobile platforms it looks nice when you can play the button click animation till the end and then trigger the picker (because it is full screen) but ig that is a minor thing

**Comment by AshleyScirra** [comment]
Added `cordova-plugin-color-picker@1.0.0` to allowlist.
