### ISSUE TITLE
Crash event sheet replace undo :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6925]
## Problem description

Construct crashes.

## Steps to reproduce

1. Create a new project.
2. Go to the event editor.
3. Create an event with a `While` condition.
4. Copy the event and paste 5 times.
5. Copy all events and paste 3 times.
6. Copy all events.

The next steps must be done at a pace.

7. Press `Ctrl + Z` until you see an empty event sheet. You have to press, not hold.

The next steps need to be done quickly.

8. Paste the copied events.
9. Press `Ctrl + Z`.
10. In the first event, replace the `While` condition with `On canvas snapshot`.
11. Click `Undo`.

## Observed result

https://user-images.githubusercontent.com/91274932/232226854-c8303359-ed1b-4c47-9894-78fe65093586.mp4

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r337-2b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'innerWidth') @ TypeError: Cannot read properties of null (reading 'innerWidth') at dja (https://editor.construct.net/r337-2/main.js:428:235) at eja (https://editor.construct.net/r337-2/main.js:426:325) at new aj.g.Notification (https://editor.construct.net/r337-2/main.js:1911:104) at qa.j (https://editor.construct.net/r337-2/main.js:1113:44) at aj.g.Notification.Pa (https://editor.construct.net/r337-2/main.js:1913:420) at window.qfb.Ah (https://editor.construct.net/r337-2/main.js:2517:452)
Stack: TypeError: Cannot read properties of null (reading 'innerWidth') at dja (https://editor.construct.net/r337-2/main.js:428:235) at eja (https://editor.construct.net/r337-2/main.js:426:325) at new aj.g.Notification (https://editor.construct.net/r337-2/main.js:1911:104) at qa.j (https://editor.construct.net/r337-2/main.js:1113:44) at aj.g.Notification.Pa (https://editor.construct.net/r337-2/main.js:1913:420) at window.qfb.Ah (https://editor.construct.net/r337-2/main.js:2517:452)
Construct version: r337.2
URL: https://editor.construct.net/r337-2/
Date: Sat Apr 15 2023 01:54:15 GMT+0300 (Восточная Европа, летнее время)
Uptime: 57 s

Platform information
Product: Construct 3 r337.2 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Given that we are getting such a high volume of reports that it's difficult for us to keep up, and this is taking time away from other improvements to Construct like new feature development, and the steps to this look obscure enough that it seems unlikely anyone will run in to it, closing.
