### ISSUE TITLE
In the sprite editor crash

### ISSUE THREAD

**Issue by BigBadOOF** [Scirra/Construct-bugs#6931]
## Problem description

 My problem isn't really due to the project since I have had it before on other projects but if I press Escape in the sprite editor then the entire page freezes and it gets a little annoying when I haven't saved in a while, although if I press the X in the top right of the sprite editor it is just fine (Not all of the time ) 

## Steps to reproduce

1.Add a spritesheet
2.Press the Escape key
3.The Crash Appears

## Observed result

 I think when I add a spritesheet then press Escape to try and close the sprite editor it bugs out

## Expected result

 I would expect the sprite editor to just close like it does when I don't edit a sprite

## More details

 I have had this bug with Opera, Chrome and Edge On Windows 10

**Affected browsers/platforms:**  Chrome, Edge, Opera on Windows 10

**First affected release:**  I'm not sure but it's pretty recent

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@BigBadOOF Please provide an error message.

**Comment by BigBadOOF** [comment]
No Error Message The Engine Just Crashes

**Comment by WilsonPercival** [comment]
> 1.Add a spritesheet
> 2.Press the Escape key
> 3.The Crash Appears

@BigBadOOF I cannot reproduce this. Can you tell me the version in which the hang occurs? And could you record a video?

**Comment by BigBadOOF** [comment]
The Version Is The Latest Version And I'll See If I Can Make A Video

**Comment by BigBadOOF** [comment]
Although The Problem Only Happens On Occasion But Does Get Really Annoying When I Haven't Saved In A While
