### ISSUE TITLE
Saving snapshot with drawing canvas and webgpu enabled causes errors.

### ISSUE THREAD

**Issue by huehauhea** [Scirra/Construct-bugs#6940]
## Problem description

Using drawing canvas with webgpu on, saving snapshot causes error.

## Attach a .c3p

[drawcanvaswebgpubug.zip](https://github.com/Scirra/Construct-bugs/files/11265205/drawcanvaswebgpubug.zip)

## Steps to reproduce

1.Preview
2.Check console

## Observed result

![Untitled](https://user-images.githubusercontent.com/131197974/232872778-98616b2f-4030-41e5-8789-20b45276d0c9.png)

## Expected result

No errors.

## More details

**Affected browsers/platforms:** 
Chrome 113 Beta

**First affected release:** 
 r338
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta
