### ISSUE TITLE
The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.

### ISSUE THREAD

**Issue by Vikingjonsson** [Scirra/Construct-bugs#6944]
## Problem description
When exporting to Xcode project, the Xcode build fails with the error:
`The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Similar to this issue: https://github.com/Scirra/Construct-bugs/issues/6934

## Attach a .c3p
[test.ios.project.zip](https://github.com/Scirra/Construct-bugs/files/11269601/test.ios.project.zip)

## Steps to reproduce
1. Create a new C3 project
2. Add a sprite
3. Export as Xcode project
4. Set export options to:
- Deduplicate images: true
- Loasless format: PNG
- Lossy format: JPG
- Recompress images: true
- Minify mode: Simple
5. Open xcworkspace in Xcode
6. Sign project
7. Build

## Observed result
Build stops with the error: `The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.`

Running pod install in the exported project folder will not help.

## Expected result
Xcode start simulator and starting the application.

## More details
Tested with multiple projects that has worked previously, also tested with newly created projects.

**Affected browsers/platforms:** 
Mac, probably related to the update on the build servers.

**First affected release:** 
Release r336 stable

## System details
<details><summary>Platform information</summary>
Product: Construct 3 r336 (stable)
Browser: Chrome 112.0.5615.49
Browser engine: Chromium
Context: browser
Operating system: macOS 13.3.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 208 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by EMI-INDO** [comment]
**Just like my problem, I solved it.**

Run `cordova platform remove ios` then `cordova platform add ios `

`cd platforms/ios && pod install --repo-update`

then `pod repo update`

I made this video

https://www.youtube.com/watch?v=vfKGsWZdhSE

**Comment by Vikingjonsson** [comment]
@AshleyScirra, a few of them but unfortunately didn't get it to work.

**Comment by AshleyScirra** [comment]
What version of cocoapods are you running? The build service is running 1.12.0, and your local copy probably needs to be at least that version (especially as the error message includes "update your CocoaPods installation"). You can run `pod --version` to check.

**Comment by Vikingjonsson** [comment]
I've tried with versions 1.12.0 and 1.12.1

**Comment by TecenGOD** [comment]
I can confirm that I ran into the same problem today. If I build a Cordova project on my Mac, then it works without problems, but if I choose "export to Xcode" in Construct 3, then I get the same error that the author describes in this thread.

**Comment by AshleyScirra** [comment]
Another alternative is: export a Cordova project, run `cordova prepare` on the Cordova project, and then run `pod install`. That is pretty much the entirety of what the build service does for you when you export an Xcode project.

**Comment by fredriksthlm** [comment]
To run `pod install` is relevant only if the project uses pods. As far as I know @Vikingjonsson don't even use any pods. (he wrote a comment on the former bug report)
So maybe this issue actually started recently if the scirra server now always run pod commands even on projects that don't use pods.
(I don't use the build service though, so I have no idea what is really going on.)

**Comment by xsx** [comment]
Can confirm it started happening recently (last 2 days). Previous projects that exported fine to xcode now give this error.

**Comment by Chadori** [comment]
Try launching the **Terminal** then write `cd` with the directory of the workspace, and finally `pod install`. You will at least know why the installation had failed.

**Comment by Vikingjonsson** [comment]
For me it works for all things except xcode build from Construct 3.
If I get a cordova export from Construct 3 and open it in Xcode the build runs fine as well.
I don't think its a problem with a local config, but can't say for sure.

**Comment by Chadori** [comment]
I, myself, cannot reproduce the issue, even after following the steps. Perhaps this is isolated to an Xcode configuration, installation or version?

**Comment by ArtemLanin** [comment]
> Construct 3 Xcode builds fail, other projects works fine and don't have this issue. Cordova export from Construct 3 works fine when built with Xcode. Don't think its a problem with a local config, but can't say for sure.

Have you find any solution?

**Comment by squalinho** [comment]
Same problem here, but I may have found something, it seems to me related to the browser and the "cordova-plugin-inappbrowser", removing it no more bugs. I hope it can help

**Comment by AshleyScirra** [comment]
In the end I think I figured out the missing piece of the puzzle: it seems the problem only happens if the project includes the Browser plugin. That includes `cordova-plugin-inappbrowser`, which it seems ends up generating an empty Podfile, which it seems cocoapods has a problem with. I don't really understand what's going on and couldn't figure out a workaround even after reproducing it. My best guess is it's some kind of cocoapods bug.

It appears to be a regression caused by #6934 - we changed the build server to run `pod install` automatically if it detects the project using cocoapods. However when `cordova-plugin-inappbrowser` is used, it mysteriously produces an empty Podfile, which caused the build server to run `pod install`, and then you get in to this weird state with a broken Xcode project. So I think in the end the build server cannot run `pod install` automatically, so we've reverted that change. That should mean the previously broken Xcode projects work again if you export them again now (the change has already been made to the build server).

Sorry for the inconvenience - configuring this stuff is hard!

**Comment by ArtemLanin** [comment]
I saw that solution as well, but my project doesn't contain the Browser
plugin and cordova-plugin-inappbrowser but I still got this error.

**Comment by Grizzley1996** [comment]
Watching this mistake and discussion since the beginning.
I had the same issue, yesterday i was fixed. I exported project to Xcode successfully. 

But today i tried to export the same project without changing anything and it outcomes an error in Construct 3 (added screenshot below). 

![photo_2023-05-03 17 27 32](https://user-images.githubusercontent.com/131172679/235965414-858d2042-b289-4426-9008-04c7cc7b3fba.jpeg)

I have done all steps needed steps, also in “About project”.

Think, new issue is linked with this one.

**Comment by AshleyScirra** [comment]
I just did an Xcode export and it worked fine for me. If you have any further issues please file a new issue following all the guidelines, as it looks like a different issue and it's impossible to help without full details.

**Comment by therealPaulPlay** [comment]
It‘s really weird, I never had this issue with the browser plugin and am not able to reproduce it. Are you guys certain that it is related to the browser plugin / the pod install?

**Comment by therealPaulPlay** [comment]
And I have actually heard of this issue  before the change to the build service was made, however, there could be multiple causes
