### ISSUE TITLE
allow the editor to open the.gradle file

### ISSUE THREAD

**Issue by EMI-INDO** [Scirra/Construct-bugs#6945]
<img width="1167" alt="applivion" src="https://user-images.githubusercontent.com/78555833/233061532-902926b8-089d-4921-bed8-f8b895e44c50.png">

- Reasons to speed up file editing

-  # Destination addonSdk AddCordovaResourceFile

-  # example file.gradle

```
// Repos
repositories {
    google()
    mavenCentral()
    maven { url "https://android-sdk.is.com" }
}

dependencies {
    implementation 'adapter: xxx'
    implementation 'adapter: xxx'
    implementation 'adapter: xxx'
}
```

**Thank you sir**

**Comment by WilsonPercival** [comment]
@EMI-INDO It's more like a proposal. You can issue it on the offer platform. https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-suggestions-161682

**Comment by AshleyScirra** [comment]
Please post as a feature suggestion.
