### ISSUE TITLE
Add cordova plugin to build server (cordova.plugin.yabbiads)

### ISSUE THREAD

**Issue by yabbi-sdk-developer** [Scirra/Construct-bugs#6946]
## Problem description

Hello, we are the developers of the add-on for monetization in mobile applications on Construct 3.

Our addon requires a plugin dependency on Cordova to work.

We encountered a problem that when exporting the application, the Cordova dependency is not included in the assembly, and the application is not built correctly (the plugin does not work).

## Attach a .c3p
You can see how the plugin works in the test application:
[YabbiAds-Demo.zip](https://github.com/Scirra/Construct-bugs/files/11273131/YabbiAds-Demo.zip)

And you can find C3 Plugin by [link](https://www.construct.net/en/make-games/addons/942/yabbiads)

## Steps to reproduce

Build application with C3 build server. 

## Observed result

If during export the user selects "Cordova project", and builds it on his computer, everything will work (the plugin will work).
![2023-04-19 15 36 51](https://user-images.githubusercontent.com/102967494/233079479-46751736-c0f6-436b-a64b-d10c21d34e06.jpg)

If you select any other option ("Android Studio Project", "Debug APK", etc.), the Cordova dependency will not be included in the build (the plugin will not work).

## Expected result
We found that the problem is that cordova plugins are added to the build server only after review.
Please add our cordova plugin to your build server.
npm ID - `cordova.plugin.yabbiads`

**Comment by AshleyScirra** [comment]
Added `cordova.plugin.yabbiads@1.0.6` to the build server allowlist.
