### ISSUE TITLE
Template name missing the 3 dots to expand the input box

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#6956]
## Problem description

The field "Template name" in the object properties panel is missing the 3 dots which appear everywhere else there are strings.

![image](https://user-images.githubusercontent.com/7268697/233633634-98ea083b-de49-404e-bc5e-ed691f8a504e.png)

This bug makes it very complicated to read the whole template name string.
Unlike in other string based input text boxes where the 3 dots are present:

![image](https://user-images.githubusercontent.com/7268697/233633755-4864204d-9c2d-4262-aeab-8fe83835eb01.png)

![image](https://user-images.githubusercontent.com/7268697/233633819-5e793361-804a-414e-91bc-a79df9f9cb6d.png)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** since templates were released Live

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 112.0.5615.137
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 824 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not a bug. Some text fields which may contain very long strings (i.e. a paragraph) have a button to edit a longer string in a dialog. Text fields which are not expected to contain a paragraph or more of information, such as the object name and in this case the template name, do not have that.

**Comment by JeFawk** [comment]
> It's not a bug. Some text fields which may contain very long strings (i.e. a paragraph) have a button to edit a longer string in a dialog. Text fields which are not expected to contain a paragraph or more of information, such as the object name and in this case the template name, do not have that.

Ohh?? Rather surprised about this. I opened up a suggestion to add this feature: https://construct23.ideas.aha.io/ideas/C23-I-267
