### ISSUE TITLE
Whitelist request

### ISSUE THREAD

**Issue by VinoosIr** [Scirra/Construct-bugs#6962]
hi. please whitelist these plugin:

**Update:**
`vinoos-cordova-iap@1.1.4`

**New:**
`cordova-plugin-enable-multidex`

**Comment by VinoosIr** [comment]
any news on when they will be added/updated?

**Comment by AshleyScirra** [comment]
As per the [build server plugin review process](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266), please allow 6-8 weeks for routine updates.

**Comment by VinoosIr** [comment]
> As per the [build server plugin review process](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266), please allow 6-8 weeks for routine updates.

But its Urgent. current version not working on android 12+
