### ISSUE TITLE
Included Addons don't update when "Bundle Addons" is enabled (Bug or intended?)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#6967]
## Problem description

When you use bundled addons and update them, they won't be updated in the project files. I am not sure whether this is intended or an issue but it is annoying to work with. 

## Steps to reproduce

1. Install Addons
2. Enable a project that uses bundled addons
3. Update the Addons
4. The bundled addons have not been updated

## Observed result

The bundled addons do not update. 

## Expected result
There should at least be the option to update them, as you otherwise have to disable bundle addons -> save -> update addons -> enable bundle addons again. Also, I don't really see the reason why you would not want to update them in a certain project, it doesn't make much sense as in other projects the newer versions will be used. 

## More details
All platforms are affected.

**Comment by fredriksthlm** [comment]
The option to update already exist. You can just right click on a plugin and choose 'update', if you have a newer installed.

**Comment by therealPaulPlay** [comment]
Where, in the addon manager?

**Comment by fredriksthlm** [comment]
> Where, in the addon manager?

No, the Addon manager is the addons installed in the _editor_, these addons are not related to your _project_.

The addons used in the project is located in  Tools -> View used addons
Here you can see the version used in the project, and also update if the editor has a newer one installed.

**Comment by therealPaulPlay** [comment]
Oh I didn‘t know that! You can click on the project in the folder structure -> tools -> view used addons, that‘s great. Thank you for your help :)
