### ISSUE TITLE
Crash files supreme after fixed :space_invader:

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#6971]
## Problem description

Construct crashes. I have already reported this: https://github.com/Scirra/Construct-bugs/issues/6843

## Attach a .c3p

save open project: [save_open_project.zip](https://github.com/WilsonPercival/WilsonPercival/files/11301929/save_open_project.zip)

## Steps to reproduce

1. Create a new project.
2. Create a new `Dictionary` file.
3. Set the size to `2`.
4. Close the `Dictionary` file.
5. Click `Undo`.
6. Open the `Dictionary` file.
7. Click `Redo`. A window will appear, click `OK`.
8. Create a new script in the `Scipts` folder.
9. Press `Undo` two times. A window will appear, click `OK`.
10. Click `Undo`.

## Observed result

https://user-images.githubusercontent.com/91274932/233798161-6ce63bc3-0882-41aa-b61b-9491303fa362.mp4

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r338b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'innerWidth') @ TypeError: Cannot read properties of null (reading 'innerWidth') at dja (https://editor.construct.net/r338/main.js:428:235) at eja (https://editor.construct.net/r338/main.js:426:325) at new aj.g.Notification (https://editor.construct.net/r338/main.js:1910:104) at qa.j (https://editor.construct.net/r338/main.js:1112:44) at aj.g.Notification.Pa (https://editor.construct.net/r338/main.js:1912:420) at window.ufb.Ah (https://editor.construct.net/r338/main.js:2516:452)
Stack: TypeError: Cannot read properties of null (reading 'innerWidth') at dja (https://editor.construct.net/r338/main.js:428:235) at eja (https://editor.construct.net/r338/main.js:426:325) at new aj.g.Notification (https://editor.construct.net/r338/main.js:1910:104) at qa.j (https://editor.construct.net/r338/main.js:1112:44) at aj.g.Notification.Pa (https://editor.construct.net/r338/main.js:1912:420) at window.ufb.Ah (https://editor.construct.net/r338/main.js:2516:452)
Construct version: r338
URL: https://editor.construct.net/r338/
Date: Sat Apr 22 2023 19:59:59 GMT+0300 (Восточная Европа, летнее время)
Uptime: 167.8 s

Platform information
Product: Construct 3 r338 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
Can't reproduce this one, and the steps seem relatively obscure anyway so seems unlikely to be a significant issue.
