### ISSUE TITLE
Update cordova.plugin.yabbiads in build server

### ISSUE THREAD

**Issue by yabbi-sdk-developer** [Scirra/Construct-bugs#6976]
## Observed result
Hello, please update version of our plugin in build server

Plugin name - `cordova.plugin.yabbiads` 
Old version -  `1.0.6`
New version - `1.1.0`

**Comment by yabbi-sdk-developer** [comment]
@AshleyScirra hello, any news?

**Comment by AshleyScirra** [comment]
As per the [build server plugin review process](https://www.construct.net/en/forum/construct-3/plugin-sdk-10/build-server-cordova-plugin-149266), please allow 6-8 weeks for routine updates.

**Comment by yabbi-sdk-developer** [comment]
@AshleyScirra Should I open issue every time, when I need to update my plugin?

**Comment by AshleyScirra** [comment]
If you want to change which plugin version is going to be approved when this is reviewed, just edit the the original post. If you want to make a whole new request for a different plugin, please file a new issue.
