### ISSUE TITLE
Align center does not work correctly when the zoom is more than 100%

### ISSUE THREAD

**Issue by TecenGOD** [Scirra/Construct-bugs#6980]
## Problem description

If the zoom on the layout in the editor is more than 100%, then when the sprite moves, the coordinates have a number after the decimal point. It also breaks the setting of the object "Align viewport center"

![gif_1](https://user-images.githubusercontent.com/7480088/234375831-d56c9bad-007e-43b8-8e16-06a8a42a9175.gif)

## Attach a .c3p
[editorBug.zip](https://github.com/Scirra/Construct-bugs/files/11325880/editorBug.zip)

## Steps to reproduce

1. Try to put the sprite in the center of the viewport when the zoom of the editor has 100%
2. You get an integer of the viewport center
3. Try to repeat point number 1, but make the zoom more than 100%
4. You get a viewport center with a float number

## Observed result

You get a viewport center with a float number

## Expected result

You get an integer of the viewport center

## System details

Product: Construct 3 r336 (stable)
Browser: Edge 112.0.1722.58
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.58
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
Floating point precision issues strike again. Added some rounding so it should produce clean numbers for the next beta.
