### ISSUE TITLE
Longer saving time when any preview is playing in the layout editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#6982]
## Problem description

I noticed that when I preview particles or a behavior like Sine in the layout editor and save the project, it takes considerably longer to save.

## Attach a .c3p

[LargeProj2.zip](https://github.com/Scirra/Construct-bugs/files/11329529/LargeProj2.zip)

## Steps to reproduce

1. Open the project as a single file C3P
2. Check "Preview" checkbox for the red sprite or particles in the layout editor.
3. Click Save icon.

## Observed result

Normally this project takes 8 seconds to save on my machine.
With preview playing - 13-14 seconds.

But this gets exponentially worse with larger projects!
The game I'm currently working on normally takes about 35 seconds to save.
With preview playing - **2:30 minutes**!

## Expected result

Same saving time, or maybe the previews should be stopped before saving.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r339 (beta)
Browser: Chrome 112.0.5615.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 272 gb
Storage usage (approx): 1.4 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
It takes about 7 seconds to save either way with my system, so I can't reproduce a difference.

If something else on the system is consuming all the available CPU, then naturally that will slow down other activities like saving. So if Live Preview is for some reason slow and taking up all your CPU, then it's expected that it will slow down saving.

I'd advise to save a folder project for a project this large anyway (it has over 3000 files). On my system it's 7 seconds to save a single-file C3P, but after first saving as a folder project, subsequent saves are too fast to time with a stopwatch (a fraction of a second). So if you want fast saves, you should be using a folder project anyway.

**Comment by dop2000** [comment]
The difference between 30 seconds and 2 minutes 30 seconds is pretty significant!
A small preview of particles running in background doesn't explain 500% increase in saving time.
I have a powerful laptop with 24GB RAM.

I know that saving to a folder is much faster, but it doesn't work in our workflow.
