### ISSUE TITLE
Signals "ignore" keyboard conditions

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#6984]
## Problem description

If parent conditions are key pressed, Signal don't carry out the intended event, but the last in the runtime regardless of the conditions.

## Attach a .c3p

[SIGNAL BUG.zip](https://github.com/Scirra/Construct-bugs/files/11332710/SIGNAL.BUG.zip)

## Steps to reproduce

1. Press Shift to show "Paper"
2. Press W to show "Rock"
3. Do nothing to show "Scissors"

## Observed result

The text ALWAYS shows Scissors, regardless of key conditions.

## Expected result

The Text should show "Paper" when pressing Shift and "Rock" when pressing W.

## More details
It seems to happen only with key conditions, I tested with global variables as conditions and works normally, not sure if other conditions could affect it though.

 

**Affected browsers/platforms:** Chrome

**First affected release:** r339, didn't test others

## System details

<details><summary>View details</summary>

Device name	LAPTOP-DAOHK829
Processor	Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.83 GB usable)
Device ID	3FC91B51-E8DD-4CFB-B006-E1141BF1C7B0
Product ID	00325-82098-04728-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 11 Home
Version	22H2
Installed on	‎20/‎11/‎2022
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

</details>

**Comment by AshleyScirra** [comment]
This isn't a bug - the events just don't make sense.

If you have a trigger under a sub-event, when the trigger fires it first runs all the parent events to set up picked instances and verify the trigger should run. It's sort of as if the parent events are actually sub-events of the trigger. However in this case you have "Else" in the parent event. When the trigger fires it then has to check if "Else" is true, but it's only running as a one-off for a trigger, so it doesn't make sense to ask that. "Else" means "did the previous event not run", and in this case Construct (IMO reasonably) interprets that as "no, the previous event didn't run", because it's a one-off trigger so the previous event has not been checked at all. So event 7 always runs.

**Comment by DinoSystem** [comment]
> This isn't a bug - the events just don't make sense.
> 
> If you have a trigger under a sub-event, when the trigger fires it first runs all the parent events to set up picked instances and verify the trigger should run. It's sort of as if the parent events are actually sub-events of the trigger. However in this case you have "Else" in the parent event. When the trigger fires it then has to check if "Else" is true, but it's only running as a one-off for a trigger, so it doesn't make sense to ask that. "Else" means "did the previous event not run", and in this case Construct (IMO reasonably) interprets that as "no, the previous event didn't run", because it's a one-off trigger so the previous event has not been checked at all. So event 7 always runs.

I understand, in that case, should it also work the same way with other triggers? (timer x), or, should it work the same with other parent conditions different from on key pressed? Which isn't the case.

**Comment by AshleyScirra** [comment]
This issue isn't anything specific to signals. The problem is using triggers in sub-events which reference "Else". Those events don't really make sense and the engine doesn't support it.

**Comment by DinoSystem** [comment]
> This issue isn't anything specific to signals. The problem is using triggers in sub-events which reference "Else". Those events don't really make sense and the engine doesn't support it.

Sorry if i seem to insist, i know you're busy with many other issues and implementation, i'm probably making confusion, but if i replace the signal with a different trigger (like a on timer x, or a timer behaviur) the problem doesnt occur even with the Else in the parent events. Also, keeping the Signal, the problem doesn't occur if i use a parent event different from "key is down". Even if this eents structure is not intended to be used, it seems there's something happening with the combination "key is down" and Signal.
