### ISSUE TITLE
Missing script interface for Custom Actions

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#6987]
## Problem description

We can't call a Custom Action via JS scripting.

## More details

It would be cool if we could do it per instance in scripting
**instance.callAction("MyAction", parameter0)**

I know this is not how it works in Event sheet (as it pass the SOL of the related ObjectType) but it would be by far the best way to handle it in JS as there is no SOL here.
**This is why it should be accessible from the IInstance script interface.**

I posted in Github Issues as this is how Scripting Interfaces are added most of the time, but created a suggestion as well if you prefer.

https://construct23.ideas.aha.io/ideas/C23-I-272

**Comment by AshleyScirra** [comment]
This was filed as a suggestion so closing.
