### ISSUE TITLE
Editor notifies about a new beta version even though notifications are enabled for stable releases only

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#6992]
## Problem description

We are using r337.2 in our project and it's possible that we will stay on this version forever, because the porting complany requires us to lock-in the current version.

Even though I selected "Notify me about updates for: Stable releases" in settings, still every time I load Construct it shows me this notification:

![image](https://user-images.githubusercontent.com/36763350/235285656-6819554e-28b0-4cc4-94c8-83eabe880403.png)

## Steps to reproduce

1. Launch r337.2

## Observed result

A notification about the new beta release available.

## Expected result

The editor should not notify me about beta releases if I set "Stable releases" in settings.

It would be great if you could add "No notification" option to that setting.
Or add an option "Don't remind me again about this version" to the notification dialogue.

I'm really not looking forward to getting this message many times a day for the next several years... 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r337.2 (beta)
Browser: Chrome 112.0.5615.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 265 gb
Storage usage (approx): 83 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by vascco47** [comment]
Hi colleagues, that notification does not appear for me, on the C3 desktop app downloaded by Chrome. Maybe try deleting cookies or reinstalling the browser, maybe it will solve the situation?

**Comment by avishaymizrav** [comment]
https://github.com/Scirra/Construct-bugs/issues/4290

**Comment by dop2000** [comment]
Of course this is by design..
I can understand the argument about people submitting reports for bugs which may already be fixed. But developers may choose to stay on a certain release version for various reasons. (I explained mine in this report) 
And I'm pretty sick of seeing this dialogue sometimes a dozen times a day. 
In this case there should definitely be an option "Don't notify me again about this version".

**Comment by vascco47** [comment]
> Of course this is by design.. I can understand the argument about people submitting reports for bugs which may already be fixed. But developers may choose to stay on a certain release version for various reasons. (I explained mine in this report) And I'm pretty sick of seeing this dialogue sometimes a dozen times a day. In this case there should definitely be an option "Don't notify me again about this version". This way I will still receive a notification when a new version is released.

I agree, there is always room for improvement, according to the list of priorities. On the other hand, I take my hat off to them for managing to fix so many bugs in such a short amount of time, to keep this great software running smoothly, in parallel with new features. It's certainly not easy.

**Comment by TecenGOD** [comment]
The version system on Construct 3 is terrible. I am using a Chrome app and want to use a certain version of the stable version of Construct 3, but it automatically updates me to the latest version. This is infuriating, since I have to open a browser page to enter the right URL for the version I need. Why can't it be implemented more correctly? Why can't I opt out of auto-updating Construct???

**Comment by Whited43** [comment]
I join the problem. I would like to manage versions somehow, without autoloading or with notification.

**Comment by vascco47** [comment]
In my opinion, it's best to use the latest stable versions, so that you don't have any inconvenience with the beta versions. I've been using only stable versions for years and I'm very satisfied.

**Comment by TecenGOD** [comment]
> In my opinion, it's best to use the latest stable versions, so that you don't have any inconvenience with the beta versions. I've been using only stable versions for years and I'm very satisfied.

Stable versions unfortunately are not so stable anymore. Critical bugs often appear that can break projects. Therefore, it's not very cool when you open a project and didn't notice that Construct 3 was updated automatically and you saved the project in a new version...

**Comment by avishaymizrav** [comment]
> Of course this is by design.. I can understand the argument about people submitting reports for bugs which may already be fixed. But developers may choose to stay on a certain release version for various reasons. (I explained mine in this report) And I'm pretty sick of seeing this dialogue sometimes a dozen times a day. In this case there should definitely be an option "Don't notify me again about this version". This way I will still receive a notification when a new version is released.

You're preaching to the choir. It annoyed me too, but I believe they will consider this as a suggestion rather than a bug.

**Comment by AshleyScirra** [comment]
As per #4290 this is currently by design: if you use a beta release it will always notify you about a newer beta release. Non-bug change requests should be submitted as suggestions instead.

Note that staying on old releases is something we definitely do not recommend. It basically means you will no longer be able to receive support from us. If you run in to any issues or problems the first thing we will suggest is to update to the latest version, and if you don't do that, we cannot help you any further. At a minimum I would also strongly recommend sticking to a stable release if you have to stay on some release, not a beta release, as beta releases fairly commonly introduce regressions and have known issues that get sorted out in later beta releases. So you could end up stuck with some fairly serious issues long-term if you choose to stay on a beta release.

**Comment by dop2000** [comment]
@AshleyScirra  We are all grown ups and understand the risks of using an outdated version of Construct. You shouldn't inconvenience us for not updating to the latest version.

**Comment by TecenGOD** [comment]
@AshleyScirra You recently wrote a blog about Apple breaking Construct 3. But unfortunately, due to automatic updates, you also break projects on Construct 3. It's not very cool. I want to be able to use a specific version of Construct 3 in the Chrome App.
