### ISSUE TITLE
Construct Anime Video Export

### ISSUE THREAD

**Issue by bitropAlex** [Scirra/Construct-bugs#6994]
## Problem description
Hi trying to use Construct Anime
When i export video (180 sec) with standard options video  quality is terrible 
When i export with video bitrate more then default it doesn't export  

I tried to export many times with different bitrate 3000 4000 5000 6000 ..... 10000

only once it turned out 6000 but after that it didn’t work anymore even with 6000

How i can work with it ?

## Steps to reproduce

1.
2.
3.

## Observed result

<img width="515" alt="Screenshot 2023-04-30 at 13 21 27" src="https://user-images.githubusercontent.com/129107647/235348577-1ed8b24f-9a52-4a28-bd1b-41c9240d604e.png">

<img width="515" alt="Screenshot 2023-04-30 at 13 21 35" src="https://user-images.githubusercontent.com/129107647/235348681-56527c62-ed32-402c-b068-20dd1c478312.png">

## Expected result

I can download video

## More details

**Affected browsers/platforms:** Chrome/Mac

**First affected release:** R336 stable

## System details

<details><summary>View details</summary>

Platform information
Product: Construct Animate r336 (stable)
Browser: Chrome 112.0.5615.137
Browser engine: Chromium
Context: browser
Operating system: macOS 13.3.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 50 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible to help. No project was provided so I tried the 'Animated splash' built-in example; I can change the bitrate to 5000 (twice the default) and export a 180 second animation and it seems to work OK.

**Comment by AshleyScirra** [comment]
I tried again adjusting the export settings and I think I managed to reproduce this. It should be fixed in the next beta.

Please note we often can't fix issues from screenshots alone. This is why we have the bug report guidelines - they are there to make sure we can actually help you. Please try to always follow them if you file any more issues in future to make sure we can resolve the problem you are reporting.

**Comment by bitropAlex** [comment]
I fully understand what you are talking about and if you look at my other tickets there is an attached project file everywhere.
But in this case, I can't attach the whole project. I do not have a right. And what to do in this case?

You should have options for dealing with such cases.
As a programmer in any company, I observe huge variants of debugging logs and so on. Who did what and did it successfully or not.

It's not for me to teach you, but you definitely can't say "No body, no business"

In any case, it's great that you reproduced. But can I know exactly when the next release is? After all, all this time I just can’t do anything and export

Thanks
