### ISSUE TITLE
Cannot iterate children on constructor

### ISSUE THREAD

**Issue by raassh-23** [Scirra/Construct-bugs#6997]
## Problem description

When subclassing instance, `getChildCount()` on the constructor will return 0 if the object is already on the layout from the start. We can't also iterate the children using either `*children()` and `*allChildren()`. But it works perfectly if we create the object with event.

## Attach a .c3p

[children-bug.c3p](https://drive.google.com/file/d/1cnpClS4AT1nWrPqspg-y8e3GeRoTH0B4/view?usp=sharing)

## Steps to reproduce

1. Preview the project and open developer tools
2. Press space

## Observed result

Console output shows the children count for the first constructor call is 0 and doesn't log the children while the second constructor call correctly shows the children count and log all the children
![image](https://user-images.githubusercontent.com/29938033/235490155-c2c2b857-f83d-4839-8eb6-0bea5bdb6b3a.png)

## Expected result

Both constructor call should show the same output

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** R336

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r339 (beta)
Browser: Chrome 112.0.5615.139
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 305 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The sequencing of creating instances in a hierarchy is tricky, but I think we had already solved this for triggering 'On create', and aligning the creation of the subclass to the same time as 'On create' looks like it solves this. So it should be fixed in the next beta.
