### ISSUE TITLE
Confusing condition

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7000]
## Problem description

This isn't exactly a bug, but a confusing design.
These two conditions look identical, yet one of them is False and another is True.

![image](https://user-images.githubusercontent.com/36763350/236110765-f20be0c0-3a56-4b86-97ee-015642d2369c.png)

## Attach a .c3p

[condition.zip](https://github.com/Scirra/Construct-bugs/files/11392823/condition.zip)

## Expected result

There should be a visual difference between "Compare two values" and "Evaluate expression" conditions.
Perhaps this highlighted part should be in a different font (bold and/or italic)

![image](https://user-images.githubusercontent.com/36763350/236111132-136c1051-7c68-428a-892c-4e8aecc9fb15.png)

This actually happened to me a couple of days ago, I spent a lot of time trying to figure out why my code doesn't work.

## System details

<details><summary>View details</summary>
PASTE HERE

Platform information

Product: Construct 3 r340 (beta)
Browser: Firefox 112.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 29 mb (0.3%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon HD 3200 Graphics Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It may be confusing but it's not a bug. Please file a suggestion.

**Comment by dop2000** [comment]
This is not a suggestion, this is an obvious flaw in UI design.
Why do I even bother..

**Comment by WilsonPercival** [comment]
> This is not a suggestion, this is an obvious flaw in UI design. Why do I even bother..

@dop2000 In Construct Classic this looks good:

![classic](https://user-images.githubusercontent.com/91274932/236186496-cc2f6e56-74b7-4c83-ad9e-a7a560637dc9.png)

**Comment by dop2000** [comment]
Yep, that's what I'm talking about. A simple solution.
