### ISSUE TITLE
webGPU running the project with unlimited frames is janky

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7002]
## Problem description
when I test the project with unlimited frames with webGL it works fine and is smooth, but when I switch to webGPU the preview only seems to update at random 1 second intervals, while the debugger FPS value still display a high framerate.

## Attach a .c3p
[webGPUunlimitedJank.zip](https://github.com/Scirra/Construct-bugs/files/11399898/webGPUunlimitedJank.zip)

## Steps to reproduce

1. run the project with webGPU and unlimited frames
2. observe the rotation of the cube

## Observed result
heavy stuttering

## Expected result
smooth rotation

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details
this issue makes performance testing with unlimited frames and webGPU impossible

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Looks like another issue with how Chrome handles this, so [filed an issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1456400) with Google and will follow up there.
