### ISSUE TITLE
Cannot connect to build server

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#7004]
## Problem description

export to Android generates the following error:
![nRC22o4Bdk](https://user-images.githubusercontent.com/58107632/236409453-42aaf06e-0368-4126-a2c8-85b3a58e1c3f.png)

![IgwraQhh7a](https://user-images.githubusercontent.com/58107632/236409468-54579d3d-23b0-4a4f-8f7c-5041fd31c08b.png)

## Attach a .c3p

use any valid c3p file

## Steps to reproduce

1. export to android
2.  deduplicate images, use WebP, recompress images, NO minify
3. Cordova option default (Debug APK)

## Observed result

the errors showed above

## Expected result

normal build

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
R340
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorry, it mysteriously failed a few hours ago for some reason. I've rebooted it and it's running again now.

**Comment by rraffo** [comment]
I'm sorry @AshleyScirra but it looks like there are still some issues.
Now the build doesn't generate an error but the following message stays in the low left corner forever:
![FikFyIlgd3](https://user-images.githubusercontent.com/58107632/236450278-c89a019c-eb99-4220-bd55-7f26715dc6a2.png)
![EUAfZg6ZAj](https://user-images.githubusercontent.com/58107632/236450316-a83b81e3-211c-40e6-b958-9e180df33f86.png)

**Comment by rraffo** [comment]
Now I get this message when I try to generate a debug apk:
![NITss7GOkL](https://user-images.githubusercontent.com/58107632/236463428-94637e5d-e081-407b-8029-c83d5a33eb36.png)

**Comment by rraffo** [comment]
@AshleyScirra  this is what I get from Firefox instead:
![HSMPzYCBDu](https://user-images.githubusercontent.com/58107632/236507298-0392d03f-65b4-4aa3-9f91-f476d0d1b0e3.png)
![waTAw8TQ8W](https://user-images.githubusercontent.com/58107632/236507314-53c2a2b4-0872-49a7-af61-356f9b543dac.png)
