### ISSUE TITLE
Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

### ISSUE THREAD

**Issue by Urggan** [Scirra/Construct-bugs#7005]
## 

## Steps to reproduce

[base-chaperon-reeboot-4.zip](https://github.com/Scirra/Construct-bugs/files/11410056/base-chaperon-reeboot-4.zip)

1. I convert C3P to zip to share may project but my file is C3P
2. Just try to open the project
3. see the message "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."

## Observed result

see the message "Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project."
 

## Expected result

Open the project normaly

## More details
i copied/past some eventsheets from another project : the problem seems to provide from the "GUNgun" event sheet

I work on Macbook pro M1. I use chrome last version

**Affected browsers/platforms:** 

The last version of construct3

**First affected release:** 
Worked this morning on the same version r336 stable

## System details

Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 112.0.5615.137
Browser engine: Chromium
Context: browser
Operating system: macOS 13.2.1
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 436 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Max, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
@Urggan I can't open it because I don't have the required addons. Could you provide them?

![obser](https://user-images.githubusercontent.com/91274932/236578357-a5c48f4e-b1e8-4ffe-8b52-f6a962ac8731.png)

**Comment by Urggan** [comment]
Shure. Here they are. Thank you soooo much to give your time.
[addons.zip](https://github.com/Scirra/Construct-bugs/files/11410508/addons.zip)

**Comment by Urggan** [comment]
Sure! thank you sooo much for your time... Here they are
[addons.zip](https://github.com/Scirra/Construct-bugs/files/11410510/addons.zip)

**Comment by Urggan** [comment]
> @Urggan I can't open it because I don't have the required addons. Could you provide them?
> 
> ![obser](https://user-images.githubusercontent.com/91274932/236578357-a5c48f4e-b1e8-4ffe-8b52-f6a962ac8731.png)
[addons.zip](https://github.com/Scirra/Construct-bugs/files/11410517/addons.zip)

Sure! thank you sooo much for your time... Here they are

**Comment by Urggan** [comment]
> @Urggan I can't open it because I don't have the required addons. Could you provide them?
> 
> ![obser](https://user-images.githubusercontent.com/91274932/236578357-a5c48f4e-b1e8-4ffe-8b52-f6a962ac8731.png)

Problem comes from the "GUNgun" event sheet (between the line 1 and 10). I would remove this event sheet from the project but i can't create a C3P to import in construct 3...

**Comment by WilsonPercival** [comment]
@Urggan Could you message me on discord? My nickname is Wilson(Igor)#7140

Can you provide the project where you copied the events from? I could help find the reason why the project is breaking so that the developers can fix it.

**Comment by Urggan** [comment]
Hi Wilson
Here is the project. It is an example from examples list from construct3...
I can't find you on disord... I created a room here : https://discord.gg/XUsw2Rmw

[Consctruct3-example.zip](https://github.com/Scirra/Construct-bugs/files/11412063/Consctruct3-example.zip)

**Comment by Urggan** [comment]
Many thanks to WilsonPercival... He just saved my project. The problem was from a fonction i copy/past from an another project. He explained the problem here : https://github.com/Scirra/Construct-bugs/issues/6467
