### ISSUE TITLE
Strange pixels in the 9-patch images

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7007]
## Problem description
I am using images from a Unity package. It works seamlessly in Unity, but shows strange pixels in Construct. No matter what margins I use, the pixels remain. In some cases they appear only when the opacity is below 100%.

## Attach a .c3p
[9p.zip](https://github.com/Scirra/Construct-bugs/files/11412440/9p.zip)

## Steps to reproduce

1. Open the file.
2. Change the opacity of the object on the left to 100% to hide the pixels (the strange squares in the corners).
3. Changing the margins will shift the pixels but will not hide them.

## Observed result
The left object has strange corners (that disappear if the opacity is 100%), and the right object has strange pixels as well near the corners (at the margins of the 9-patch).
None of these artifacts appear in Unity.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/9-patch

![doca](https://user-images.githubusercontent.com/91274932/236628697-c472fe3a-dd1e-4485-b98f-6cda70d8e98f.png)

**Comment by Alaadel** [comment]
Thank you.

Would've been nice if C3 could show a warning, e.g. "C3 detected opacity is used with Overlap, this might cause Seams. Consider switching to Exact. For more information [link to docs]".

**Comment by F3der1co** [comment]
to me it makes more sense to default to exact and people can change to overlap if they have the opposite issue, as I didn't have that issue ever so far.
