### ISSUE TITLE
Unable to export to Android

### ISSUE THREAD

**Issue by rraffo** [Scirra/Construct-bugs#7008]
## Problem description

I'm unable to export to Android when using a specific internet provider. Switching to another mobile provider works normally.
 but I'm unable to determine what is the cause without the necessary network information.

## Attach a .c3p
Not necessary.

## Steps to reproduce

1. export to Android generating a debug apk
2. different errors may occur (Build failed error or a "bild service" message lock the process.
3.

## Observed result

The following errors or message appears or hang the process.
![QZTHIj1eVy](https://user-images.githubusercontent.com/58107632/236671671-3b758e53-a027-4aa8-bf6d-bc3dc978e41d.png)
![FikFyIlgd3](https://user-images.githubusercontent.com/58107632/236671675-03208348-7704-45b9-a492-ac2b89ff5ee0.png)
![EUAfZg6ZAj](https://user-images.githubusercontent.com/58107632/236671680-3e6ca0e3-8ead-4e2e-98b4-43b3bab32318.png)

## More details

I need a list of host IPs to track the network's hops and check what node is causing the problem.
Otherwise please check if the problem is caused somehow on your side.
I'm not 100% sure but if I remember correctly a similar problem already happened some time ago.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by rraffo** [comment]
I suspect that the problem is related to the WebSocket communication but I don't have any idea how to test it.
Just to be sure I have restarted any network component on my side and tried other PC and browsers but the only way to workaround is to change the provider that I can only use for test purposes.
I see you are using CloudFlare for the service. Might the WebSocket hanged due to Cloudflare? Maybe the WebSocket proxy?

**Comment by AshleyScirra** [comment]
It works fine for me, and as far as I'm aware everyone else, so this seems to be a problem with a specific Internet connection. I'm afraid it's infeasible for us to help with that, especially as fixing the problematic network configuration is likely out of our control (we don't control the network between you and the build service, just the build service). I would suggest contacting your ISP on the problematic connection for further support.

**Comment by rraffo** [comment]
@AshleyScirra of course you can't help with this problem but since it is a network problem I need the hosts name and IPs involved in the connection to be more specific with my provider or they will bounce me if I tell them I cannot build my APK. They are network engineers, not app developers.
Thanks for understanding me.

**Comment by AshleyScirra** [comment]
The build server runs on `build.construct.net`. CloudFlare publish their IPs here: https://www.cloudflare.com/en-gb/ips/
