### ISSUE TITLE
Animation folder is not automatically expanded when opening animation editor

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7021]
## Problem description

When double-clicking a sprite, the animation should be automatically highlighted on the right bar in the animation editor. And if the animation is inside any folders, these folders should be auto-expanded.
We have sprites with hundreds of animations and complex folder structure. It's sometimes very difficult to find the folder where the animation is located. 

Please don't tell me to post a suggestion, this is a very obvious design problem.

## Attach a .c3p

[AnimationFolders.zip](https://github.com/Scirra/Construct-bugs/files/11438073/AnimationFolders.zip)

## Steps to reproduce

1. Double-click any sprite in the editor.

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/6c1a839b-f041-40e7-9559-646e338d3a64)

Not possible to see in which folder the animation is located.

## Expected result

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/9a5999cc-d954-45e5-af33-8a8ae22ef1a6)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be added in the next beta.
