### ISSUE TITLE
CSS files in subfolders are not linked properly when exported

### ISSUE THREAD

**Issue by raassh-23** [Scirra/Construct-bugs#7022]
## Problem description

CSS files that are placed in subfolders are linked as if they're placed in root, which means the browser can't find the right CSS files. This only happens on exported game and works perfectly fine when being previewed inside of Construct.

## Attach a .c3p
[css-bug.c3p](https://drive.google.com/file/d/1ILDDeS5o2szXWK1jUSmwRz_Mw0kp-D8q/view?usp=sharing)

## Steps to reproduce

1. Open the project and preview it, notice that both text has the correct color
2. Export it to Web (HTML 5)
3. Host it to a server (or use live server on VS Code) and open it

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/29938033/6a721fc6-1872-41be-9f5c-c7fd2351dd1f)

if you open the `index.html`, you can see that `blue.css` is not linked properly
![image](https://github.com/Scirra/Construct-bugs/assets/29938033/13860e7d-d49b-473e-bff1-6c99433d617d)

## Expected result

![image](https://github.com/Scirra/Construct-bugs/assets/29938033/1127ebd2-c924-4860-b381-acb0a197fee5)

the `index.html` should look like this
![image](https://github.com/Scirra/Construct-bugs/assets/29938033/85a67a5e-e0e0-4bf4-8ac6-5af06071904d)

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** R336

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 112.0.5615.140
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 214 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, should be fixed in the next beta.
