### ISSUE TITLE
Editor mobile UI - wrong checkbox size

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-bugs#7025]
## Problem description

In mobile UI the settings checkboxes have different sizes.

## Attach a .c3p

In editor

## Steps to reproduce

1. Open the editor in mobile
2. Navigate to settings (Menu > Settings)
3. Checkboxes have different sizes

## Observed result

Different checkbox sizes

## Expected result

Every checkboxes are same sizes

## More details

![Képkivágás](https://github.com/Scirra/Construct-bugs/assets/47735877/00517148-a27d-4a75-aea3-826cb894d988)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r341 (beta)
Browser: Safari 13.0.3
Browser engine: WebKit
Context: browser
Operating system: iOS 13.2.3
Device type: mobile
Device pixel ratio: 3.0000001192092896
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 4.1 gb (1.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to [bug 177132](https://bugs.webkit.org/show_bug.cgi?id=177132)
Web Animations are not supported. Animations are disabled.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
