### ISSUE TITLE
Plugin Camera seems to don't work on android

### ISSUE THREAD

**Issue by ToleomStudio** [Scirra/Construct-bugs#7029]
## Problem description
After exporting an app which use the camera plugin to google play, the camera does not load, the image never shows, the permission is always denied

## Attach a .c3p
https://editor.construct.net/#open=camera-input

## Steps to reproduce

1. Open the c3p file
2. Fill in the necessary information for android export
3. Click on Project > Export > Android
4. Minification mode > Advanced
5. Choose signed android app bundle
6. Check the box requires camera permission
7. Export game to android after adding keystore

## Observed result
The camera does ot load and the texte "Declined !" is displayed, which means camera permission is denied.

## Expected result
The camera load and the text "approved!" is displayed, which means that camera permission is approved.

## More details
I am currently developing a game with Construct 3 which uses the camera function. I exported the project in test version on Google Play, being careful to check the box "requires camera permission". But when I test the app on my phone, the camera image never shows up. So I used the sample camera available on the construct 3 editor (https://editor.construct.net/#open=camera-input) and exported it as a test version, checking the " requires camera permission", to see if the problem with the camera was in my code. I tested it and the application told me "declined!". This is very strange because it was working when I was previewing the game dirrectly from Construct 3 (in Chrome).

This doesn't happen on Chrome

**Affected browsers/platforms:** 
Android

**First affected release:** 
I use the r336 version
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 113.0.5672.93
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 597 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
The provided "Camera input" sample actually also requests microphone input, so that if you take a recording it includes sound. Therefore if you export with only camera permission enabled, it fails to get the microphone permission. If you export with both camera and microphone permission enabled, it works correctly for me.

**Comment by ToleomStudio** [comment]
Thanks, that worked !
