### ISSUE TITLE
Steam overlay is cut from bottom

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-bugs#7031]
## Problem description

Steam overlay displays from the top screen edge to the bottom edge of layout, not bottom screen edge. It's cut.

## Attach a .c3p

Any exported nw.js for Steam

## Steps to reproduce

1. Run nw.js project exported for Steam.
2. Open Steam overlay
3. Take a screenshot, or get achievement to display overlay popup

## Observed result

Everything will be cut, including main overlay layout. If the game would have more wide proportions, player will never see popups because the black bars will be bigger. Steam overlay will be displayed fully when game proportions are the same as monitor's screen

![image](https://github.com/Scirra/Construct-bugs/assets/46167226/d63a7db1-6a65-4416-84c6-40aeb51dcc6c)

Bottom part is cut, isn't displayed out of the game from the bottom.

![image](https://github.com/Scirra/Construct-bugs/assets/46167226/634de157-b5b8-455e-af66-1f0dff7a12e9)

## Expected result

Steam overlay should be displayed on the whole screen

## More details

Project is exported with checked "Export for Steam"

**Affected browsers/platforms:** Chrome/Windows

**First affected release:** r336 (stable)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 113.0.5672.92
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 105 gb
Storage usage (approx): 2.6 gb (2.5%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please report any issues with the Steam Overlay to Valve - it's made by them and changing it is beyond our control.
