### ISSUE TITLE
«Export for Steam» bit slows the exported project

### ISSUE THREAD

**Issue by ArtRow** [Scirra/Construct-bugs#7033]
## Problem description

I exported my project to nw.js with option «Export for Steam» and without it.  Cursor in this project is made by hiding the default one and using «every tick» action (cursor sprite set position to mouse's). 
When the project runs with option **"c3-steam-mode": false** everything is fine and cursor behavior as well as default. All movements are accurate and precise. But when I run it with option **"c3-steam-mode": true** cursor behavior is different. Cursor is smoothly floating to the mouse position and it takes a time to reach it. Cursor can't reach the mouse position as expected. Players complain about mouse behavior. But without «Export for Steam» option ("c3-steam-mode": false) everything is fine. "chromium-args" also doesn't affect to the issue, just that "c3-steam-mode" affects.

## Steps to reproduce

This issue is light noticeable in an empty project, but more noticeable in a complete project. Also sometimes it has a cumulative behavior and alt-tab looks like resets cumulative slowing. So I didn't provide example file as it doesn't cannot fully reflect the problem. This issue is created to make an attention to difference between steam and non-steam exports.
All my test have shown that all calculations are making in time, but something slows down the rendering of "every tick" actions because of what cursor sprites can't move accurate and precise. 

## Observed result

«Export for Steam» option slows «every tick» rendering (?)

## Expected result

The same or very close game experience with and without «Export for Steam» option.

## More details
Tested on windows 10 and 11, on different computers. Exported project run from Steam and explorer. Best experience was with "c3-steam-mode": false, regardless of chromium-args, but Steam overlay become not useable. 

**Affected browsers/platforms:** Chrome/Windows

**First affected release:** r336 (stable)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 113.0.5672.92
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 105 gb
Storage usage (approx): 5.9 gb (5.7%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
No project is provided so closing as per our usual bug report guidelines. I'd also point out that one of the things 'Export for Steam' mode does is force the project to redraw every frame where it doesn't have to with a normal export, so it may only be that causing the difference. Most of the other changes 'Export for Steam' mode makes are to work around bugs in the Steam Overlay, which is Valve's software; unfortunately if those settings cause other side-effects, we cannot remove them without running in to bugs with the Steam Overlay. I was very reluctant to implement the 'Export for Steam' mode because as ever the best way to solve problems is to get the underlying bugs fixed rather than work around them. So if you want to make sure things work without 'Export for Steam' mode, you can try exporting with it off, but you'll see bugs in the Steam Overlay; you'll need to then report those to Valve and get them to fix those issues as they are beyond our control.
