### ISSUE TITLE
Game won't launch on Steam Deck

### ISSUE THREAD

**Issue by Interinactive** [Scirra/Construct-bugs#7034]
## Problem description

I can't get my C3 project to run on Steam Deck. It worked previously (October), but fails to launch since.

## Attach a .c3p

https://www.dropbox.com/s/s8ikvwhx5iidpjn/BlankTest.c3p

## Steps to reproduce

1. Export game via NW.js
2. Either upload to Steam or add to Steam as a non-Steam game
3. Launch game via Steam deck or Manjaro KDE

## Observed result

The game either opens and closed immediately or it hangs infinitely (I left it overnight once, it never launched)

## Expected result

I expected the game to launch

## More details

If you do not have a Steam Deck, you can use Manjaro KDE as recommended by Valve:

https://partner.steamgames.com/doc/steamdeck/testing

The issue I have on my physical Deck is exactly the same as on the Manjaro VM I also have set up. Be sure that these options are enabled so that Windows games can be played via Proton: https://i.imgur.com/DI7n5cG.png

There are various logs created by Steam that reference things such as: 
Failed to find active context. will fall back to (SteamLibraryWindow)

I have tried various versions of Proton (experimental, v8, v7, v6 etc) but none of them make a difference.

Another user seems to have the same issue: https://www.construct.net/en/forum/construct-3/how-do-i-8/run-game-steam-deck-crashes-176777

**Affected browsers/platforms:** 

Steam Deck

## System details

It worked back in October when I was publicly demonstrating my game, people were playing it on the Deck for hours. At some point between October ~ January, it stopped working. The 'blanktest' file above is a severely stripped down version of the game, but it still doesn't launch.

**Comment by AshleyScirra** [comment]
I think this is related to #6747: the current latest versions of NW.js basically aren't working on Linux. I reported the issue to the NW.js developers here but so far it has not been fixed: https://github.com/nwjs/nw.js/issues/8043

For now I believe the workaround is to stick to using NW.js 0.71.

**Comment by Interinactive** [comment]
I've bookmarked that nw.js ticket to see how it progresses, but for what it's worth, nw.js 0.71 doesn't work for me either. I've been using that version for the greenworks plugin.

**Comment by AshleyScirra** [comment]
Oh, are you using a Windows export and using Steam's Windows compatibility layer to run it on a Linux-based Steam Deck? I would advise to use a Linux export instead. If Steam's Windows compatibility layer doesn't work with a Windows-based app that works fine on Windows, I would say that indicates a problem with Steam's Windows compatibility layer, and so should be reported to Valve instead.

**Comment by Interinactive** [comment]
I have tried a linux export of that test file I attached and I get the same issue on both the Deck and VM

I logged a ticket with Valve through Steamworks, they replied a few times, but the last reply was 4 months ago (the ticket is still open)
