### ISSUE TITLE
Mobile UI disappearing icons 

### ISSUE THREAD

**Issue by KENYONBcom** [Scirra/Construct-bugs#7036]
## Problem description

Icons at the top disappear - save, undo, redo, profile avatar

## Attach a .c3p

Any c3p file. Create a new project to test.

## Steps to reproduce

1.create a new project 
2.watch the icons up top disappear 

## Observed result

Icons disappear 

## Expected result

Icons should be visible 

## More details

**Affected browsers/platforms:** 
Chrome on Android

**First affected release:**
it's been broken for at least the last two betas releases 

## Screenshots before and after

![Screenshot_20230511-100209](https://github.com/Scirra/Construct-bugs/assets/21185437/70d28f0b-23ea-428e-9009-9a9429f10c41)

![Screenshot_20230511-100244](https://github.com/Scirra/Construct-bugs/assets/21185437/b0107881-12a9-4d6a-afb3-d7ff814443ad)

**Comment by WilsonPercival** [comment]
Everything works.

**Comment by AshleyScirra** [comment]
It works fine for me on my Android device.

Graphical glitches like this are often device-specific graphics driver bugs that are beyond our control. You could try reporting it to Google as it may be possible for Chrome to work around it, but I doubt there is anything we can do about it.
