### ISSUE TITLE
Issues trying to export to IOS 16 - Xcode

### ISSUE THREAD

**Issue by portugalcsm** [Scirra/Construct-bugs#7040]
Using latest stable version from Construct on Mac. I am having this issue since last Thursday 11-05-2023. When i try to export a game to IOS (firmware 16 - Xcode) and I receive this message from the server: Time Out.  What should I do to workaround this issue? Link is here to the screenshot.
[https://drive.google.com/file/d/1EHLzO34ifaAy6Z257ITA8ZQEtLruVpWe/view?usp=share_link](url)

<img width="1168" alt="Screenshot 2023-05-13 at 01 15 46" src="https://github.com/Scirra/Construct-bugs/assets/42272385/71e59333-4f02-479b-a658-2a847f1f33f1">

**Comment by portugalcsm** [comment]
I just recorded a video about this issue. I tried other IOS games deployed on Appstore...i am trying to release a new build but the issue persists: 
https://www.youtube.com/watch?v=5qMooTqlskM

Anyone else with this issue?

**Comment by AshleyScirra** [comment]
Duplicate #7045

**Comment by portugalcsm** [comment]
Hi Ashley,

Where is the page i can post the bug? You just closed my post…
The video with the issue description is here: https://www.youtube.com/watch?v=MeHfMSzCGro
Please let me know,

Claudio
