### ISSUE TITLE
Steam achievements over Construct 3 video causes visual bug

### ISSUE THREAD

**Issue by Interinactive** [Scirra/Construct-bugs#7041]
## Problem description

When achievement unlocks over the top of a video that is playing, it looks like the attached image.

![image1](https://github.com/Scirra/Construct-bugs/assets/27459638/cf530f7c-74d9-4cd1-aab2-fdc87d2c1480)

## Attach a .c3p

It might be better if I give you a Steam key to the game so you can test it on Steam and see the achievement activate over a video. Please let me know where to send it.

## Steps to reproduce

1. Reach a point in the game to see an achievement pop up over a video that is playing

## Observed result

A glitchy looking achievement notification

## Expected result

An achievement that unlocks without the glitchiness

**Comment by AshleyScirra** [comment]
All I can recommend is to make sure you are using the 'Export for Steam' option on export, assuming you're using NW.js (the report does not specify exactly what you're doing). If that doesn't work then I'm afraid any issues involving Steam's display will need to be reported to Valve instead.
