### ISSUE TITLE
or unexpected behavior with system pick by comparison

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7051]
## Problem description
system pick by comparison behaves unexpected in or block

## Attach a .c3p
[orUnexpected.zip](https://github.com/Scirra/Construct-bugs/files/11500126/orUnexpected.zip)

## Steps to reproduce

1. preview and see only one circle getting destroyed
2. disable the group "systemPick.." and enable group "or"
3. preview again and see all circles get destroyed eventually

## Observed result
the groups behave differently

## Expected result
they behave the same

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This deals with a very complicated aspect of the event engine, but I think I figured it out and should have a fix in the next beta.
