### ISSUE TITLE
Timeline issue - Timeline does not stop when it is paused

### ISSUE THREAD

**Issue by smGamify** [Scirra/Construct-bugs#7052]
Hello,

There is issue with the timeline controller.

When the timeline is in pause state, the stop all command does not work.
Version r336 stable

Steps:
1. Play timeline
2. Pause timeline
3. StopAll or Stop command

The timeline will start playing.

C3P file link:
https://drive.google.com/file/d/1HKFdSJFiG71zoOIjz1Do7JwK0_Celuaa/view?usp=share_link

Thanks,

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
