### ISSUE TITLE
Проблема с list 

### ISSUE THREAD

**Issue by MishanyaRus125** [Scirra/Construct-bugs#7053]
Доброго времени суток, меня интересует плагин list  и проблема связаная с ним, тоесть когда ставить тип list на телефоне он всеровно ставит тип выбор, я где то читал что вы щас не контраоируете вид HTML,  вы вид думаете как это исправить? Это де ошибка, для многих нужно что лист list работал исправно, спасибо за внимание

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7044
