### ISSUE TITLE
Array Editor: Rename Column Cannot delete the name

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7055]
## Problem description

It is really a great design that Array Editor can rename the Column / Row title, it is very convenient. But in secondary editing, it can only be overwritten with a new name, and cannot be "edited or deleted", which is somewhat inconvenient.

![Snipaste_2023-05-22_12-57-29](https://github.com/Scirra/Construct-bugs/assets/45864744/1475973a-e669-4981-9b01-457673d31cac)

I think, The previous name was a `Value` property instead of `placeholder`, allowing for editing instead of retyping, and when clearing the name, it can be reverted to the Column number.

![Snipaste_2023-05-22_13-05-43](https://github.com/Scirra/Construct-bugs/assets/45864744/ce84c6e1-845f-43e4-a41c-42f23daa5818)

## Attach a .c3p

[arrayEditorRenameColumn.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11527195/arrayEditorRenameColumn.c3p.zip)

## Steps to reproduce

Rename The 'Two' column 

![Snipaste_2023-05-22_13-03-33](https://github.com/Scirra/Construct-bugs/assets/45864744/7d236a01-e4ed-49d1-84f1-aac74a4da084)

## Observed result

The previous name was a 'placeholder' property and could not be edited based on it.

## Expected result

The previous name was a 'value' property, and when clearing the name, revert to the original number. 

Currently, it cannot fill in blank values, i.e., it cannot restore the original number

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be added in the next beta.
