### ISSUE TITLE
Mirroring an object causes incorrect mirroring of its children

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7056]
## Problem description
In Construct, mirroring an object is done by using a negative scale value. This is basically a "hack", but it works.
The problem is that it doesn't work for children of an object, as they need a different method to be mirrored correctly:
1. Define the axis to mirror the object around, in this case it is a vertical line passing through the object's origin.
2. Find the horizontal distance (D) from the parent origin to the child origin.
3. Find the angle (A) of the child.
4. (In Construct, we have to mirror the child here; in order for step 6 to work).
5. Move the child by -2*D.
6. Set the child angle to -1*A.

This mirror's the object's sprite, position, angle.

The issue is that we need to remove the object from the parent for this to work. And of course re-attach it after mirroring.
In an object with many parts, some of them cannot be made into one family, it is unnecessary difficult to save the parent data, detach from it, then read the parent data, figure out which object we need to attach to (because we can't use one family for all objects).

I believe one of the goals of hierarchies is to make composite characters. And characters need to move around and look at the player (i.e. flip and mirror). And the current hierarchy options (afaik) do not allow this in an easy way.
I could do the above solution manually if at least we had a Detach_From_Current_Parent and Reattach_To_Last_Parent actions, where C3 saves the parent data internally and handles the operation. This will even allow more tools to work with hierarchies in such tricky situations.

## Attach a .c3p
[mirror.zip](https://github.com/Scirra/Construct-bugs/files/11530291/mirror.zip)

## Steps to reproduce

1. Click the Mirror button

## Observed result
The limbs are messed up.

## Expected result
The children should be mirrored correctly around the axis of the object.

**Comment by WilsonPercival** [comment]
In `Construct Classic` this works well.

Uploading classic.mp4…

**Comment by WilsonPercival** [comment]
In `Construct Classic` this works well.

https://github.com/Scirra/Construct-bugs/assets/91274932/584ef521-eb32-4c57-87f5-d8168d5f79c6

**Comment by AshleyScirra** [comment]
@WilsonPercival - please do not test Construct Classic, it's not useful - it was retired 10 years ago and uses a completely different codebase.

**Comment by AshleyScirra** [comment]
@DiegoScirra - it looks like mirroring a hierarchy does try to modify the angle of children, but it looks like it just reverses the angle (i.e. adding 180 degrees) rather than mirroring. The same likely applies for vertical flipping.

**Comment by AshleyScirra** [comment]
Minimal repro: [issue7056.zip](https://github.com/Scirra/Construct-bugs/files/11625997/issue7056.zip)

**Comment by AshleyScirra** [comment]
The geometric maths behind this is pretty complicated, but I think I have it working for the next release.
