### ISSUE TITLE
The "Shake" action in the scrollTo behavior does not work after scrolling the layer

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-bugs#7057]
If you add the "scrollTo" behavior to the sprite and use it to shake the camera, then the layer that was moved through the ScrollLayer action stops responding to shaking

[layerscroll_shake_bug_r342.zip](https://github.com/Scirra/Construct-bugs/files/11535737/layerscroll_shake_bug_r342.zip)

## Steps to reproduce

1. Press the D button on the keyboard to shake
2. Press the A button on the keyboard to move the layer
3. Press the D button again

## Observed result

The layer that was moved no longer reacts

## Expected result

The layer that has been moved should shake as before

Wouldn't want like to move a large number of sprites, instead of one layer. To be able to use camera shake

**
chrome, web, android

**Comment by AshleyScirra** [comment]
It's actually working correctly: the 'shake' action adjusts the layout scrolling, but when you set an individual layer's scroll position that overrides the layout scroll position, so the shake will not apply to it.

**Comment by q3olegka** [comment]
I assumed this answer. But it's not too obvious. It's strange that scrolling the layer just breaks the behavior. Shouldn't "scrollto" work based on the current parameters of the layer and already move it? Ok. Let it be a technical point that I don't understand. 

But I setting the layer through scrolling to its initial position, where it was from the start of the layout, it's strange that it doesn't work even from its initial position. Maybe there is an opportunity to update the initial state, as for the behavior of sine?

**Comment by AshleyScirra** [comment]
The whole point of the independent layer scrolling feature is to allow layers to scroll differently to the rest of the view (i.e. the layout scroll position). The 'Scroll To' behavior only affects the layout scroll position. So if you independently scroll a layer, you are overriding that scroll position.
