### ISSUE TITLE
Issue with Parallax Layer Collisions

### ISSUE THREAD

**Issue by JustinShoe78** [Scirra/Construct-bugs#7061]
Problem description:

I came across an issue with collision polygons in a platform style game. In my game, the global variable ‘Position’ toggles the solid behavior of the front tilemap and front sprites, and the back tilemap and back sprites: one is solid/enabled & the other is solid/disabled. My character can jump between platforms located on different layers. The layer in the ‘back’ has an 80% parallax to appear as if the objects are farther away. I am using sprites with identical behaviors for my character, but the sprite/character that has an adjusted collision polygon does not interact with tilemaps the same way the non-adjusted sprite/character interacts with the tilemap. This collision issue is not evident when the character collides with platforms that are sprites, only those that were created with tilemaps.

Steps to reproduce:

The down arrow toggles the ‘front’ and ‘back’ global variable. This toggles the solid behavior enabled or disabled for the front & back platforms; they are opposite.
When walking on the platforms created with sprites the characters interact with the platforms as expected. These platforms have the word ‘front’ and ‘back’ on them.
When walking on the platforms created with tilemaps the sprite with the adjusted collision polygon does not interact with the platforms as expected. These platforms have the letters ’F’ and ‘B’ on them.
The ‘ScrollTo’ and ‘Platform.Default controls’ behavior may be toggled to test each character separately.

Observed result:

The character reaches a point where the screen begins to scroll due to ‘scroll to’ behavior. The character with an adjusted collision polygon does not interact as expected with the platforms that were created with a tilemap but the same character does interact with the platforms that are sprites. The character with no adjustment to the collision polygon interacts as expected with all platforms.

Expected result:

The two characters would interact identically with the solid platforms whether they were created with tilemaps or sprites.

More details:

This occurs for me while using Google Chrome as well as MS Edge. I am using r336
[ParallaxTest.zip](https://github.com/Scirra/Construct-bugs/files/11554492/ParallaxTest.zip)

**Comment by JustinShoe78** [comment]
what additional information do you need? If there is anything else I can provide, I will. thanks!

**Comment by JustinShoe78** [comment]
there are two identically created characters with only one difference: one has an adjusted collision polygon. The character with the adjusted collision polygon behaves very differently when interacting with the platforms created with tilemaps that are on the parallax layer. The non-adjusted player interacts as expected, but the one with an adjusted polygon has a significantly different interaction.

**Comment by JustinShoe78** [comment]
1. in the Project Bar, select the character named 'TestNOTAdjusted.' then in the properties bar, enable "ScrollTo" and enable "Platform.Default Controls"
2. in the Project Bar, select the character named 'TestAdjusted.' then in the properties bar, disable "ScrollTo" and disable "Platform.Default Controls"
3. Run the game
4. Jump around and interact with the platforms labeled 'front' and 'F'
5. While jumping, press the down arrow and interact with the platforms labeled 'BACK' and 'B'
6. The NOTADJUSTED character interacts as expected with all platforms at all positions.
7. STOP the game and disable controls for NOTADJUSTED character
8. Activate 'Platform.DefaultControl' and 'ScrollTo' for the ADJUSTED character
9. Attempt to interact with the platforms in the front and back

**Comment by WilsonPercival** [comment]
@AshleyScirra I made it clearer.

[issue7061.zip](https://github.com/Scirra/Construct-bugs/files/11558845/issue7061.zip)

Steps to reproduce:
1. Open and run the project.
2. Hold the right arrow to make the characters move to the right.

Observable Result: The white character fell.
Expected result: green and white characters rest against the right wall.

The difference between the characters is that they have different collision masks.

**Comment by AshleyScirra** [comment]
Minimal repro not requiring interactivity: [issue7061.zip](https://github.com/Scirra/Construct-bugs/files/11624957/issue7061.zip)

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
