### ISSUE TITLE
Crash closing the project containing a timeline (Error: already released)

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7062]
## Problem description
Construct crashes when I try to close a project with hierarchy and timeline. It shows "Error: already released".

## Attach a .c3p
[backup bug.zip](https://github.com/Scirra/Construct-bugs/files/11554528/backup.bug.zip)

## Steps to reproduce

1. Open the project
2. Close the project

## Observed result
Crash

## Expected result
Graceful close

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: already released @ Error: already released at d.B (https://editor.construct.net/r336/main.js:1232:114) at d.B (https://editor.construct.net/r336/projectResources.js:571:144) at d.B (https://editor.construct.net/r336/projectResources.js:976:317) at d.B (https://editor.construct.net/r336/projectResources.js:987:324) at d.B (https://editor.construct.net/r336/projectResources.js:1723:111) at CCG.Jn (https://editor.construct.net/r336/main.js:892:26) at https://editor.construct.net/r336/components/misc/mainMenu/mainMenu.js:7:450 at https://editor.construct.net/r336/main.js:1880:100
Stack: Error: already released at d.B (https://editor.construct.net/r336/main.js:1232:114) at d.B (https://editor.construct.net/r336/projectResources.js:571:144) at d.B (https://editor.construct.net/r336/projectResources.js:976:317) at d.B (https://editor.construct.net/r336/projectResources.js:987:324) at d.B (https://editor.construct.net/r336/projectResources.js:1723:111) at CCG.Jn (https://editor.construct.net/r336/main.js:892:26) at https://editor.construct.net/r336/components/misc/mainMenu/mainMenu.js:7:450 at https://editor.construct.net/r336/main.js:1880:100
Construct version: r336
URL: https://editor.construct.net/
Date: Wed May 24 2023 15:17:06 GMT+0300 (Eastern European Summer Time)
Uptime: 10.7 s

Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 113.0.5672.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: yes
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
The problem doesn't replicate in the latest beta. I can't remember exactly when this issue was fixed, but I do remember working on something similar fairly recently, so most likely this has been already sorted.

Can you try it out in the latest beta? Opening the project in the beta and closing it, just to verify if that works properly or not.

**Comment by AshleyScirra** [comment]
Assuming this was already fixed so closing.
