### ISSUE TITLE
editor allowing objects with custom actions to be replaced with other object without having custom actions

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-bugs#7066]
I have object with custom actions when I try to replace that object but it showing me other objects to replace which don't have any custom action and that action is also working.
## Attach a .c3p
[custom action bug.zip](https://github.com/Scirra/Construct-bugs/files/11573474/custom.action.bug.zip)

## Steps to reproduce

1. open attached file
2. check event sheet.

## Observed result

object is being replaced and working with non custom action holder object

## Expected result
should not replaced by other objects which don't have that action

## More details

**Affected browsers/platforms:** 
chrome 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Minimal repro: [issue7066.zip](https://github.com/Scirra/Construct-bugs/files/11574580/issue7066.zip)

Steps to reproduce:

1. Open project
2. Select first action in event sheet ("Sprite: CustomAction")
3. Press 'R' to replace object

Observed result:
It offers to replace Sprite with Sprite2, which is invalid as Sprite2 doesn't have a custom action with the same name. Sprite2 can be chosen which results in invalid events (calling a custom action which does not exist).

Expected result:
No Sprite2 to be shown when replacing object as it does not have a matching custom action

**Comment by AshleyScirra** [comment]
Added checks for compatible custom actions when using 'Replace object' for the next beta.
