### ISSUE TITLE
TypeError: expected file

### ISSUE THREAD

**Issue by bundleman** [Scirra/Construct-bugs#7073]
Not oppened poject - `TypeError: expected file` in console. 
Prev version was 327.3 current for try to open is 336. 
UserAgent - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`
OS - `Mac OS Ventura 13.3.1 (a)`.

**Comment by WilsonPercival** [comment]
@bundleman  Can you provide reproduce steps and project file?

**Comment by bundleman** [comment]
@WilsonPercival I just try to open my exist project from local folder.

**Comment by WilsonPercival** [comment]
> @WilsonPercival I just try to open my exist project from local folder.

@bundleman Without your project file, I won't be able to repeat the same mistake you made. My projects open fine. If it cannot be reproduced, then it will not be fixed.

**Comment by bundleman** [comment]
@WilsonPercival 
[bg2.zip](https://github.com/Scirra/Construct-bugs/files/11593795/bg2.zip)

**Comment by bundleman** [comment]
@WilsonPercival My console output 
<img width="1186" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/11851931/8b29c70a-cb2a-4a48-ac8b-d267b865be76">

**Comment by WilsonPercival** [comment]
@bundleman The project was saved in r327-3s and opens perfectly in it. But in r336s he doesn't want to open.

I also noticed that inside the archive there is such a structure:

![observed](https://github.com/Scirra/Construct-bugs/assets/91274932/7f34a7c5-0692-45a6-87de-347d032b49d9)

If you create a new archive with the contents of the `bg2` folder, then everything will open fine:

![observed2](https://github.com/Scirra/Construct-bugs/assets/91274932/59cc9bfb-ce06-498b-ba0c-39f99eafee8e)

I've attached a new project archive just in case.

[bg2_restored.zip](https://github.com/Scirra/Construct-bugs/files/11593840/bg2_restored.zip)

@AshleyScirra Will you fix it?

**Comment by bundleman** [comment]
@WilsonPercival Thanks for trying but it still doesn't work for me ((

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible, or so confusing as to be infeasible, to help.
