### ISSUE TITLE
Tweens of child objects don't work properly if parent objects are being scaled

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7079]
## Problem description

Tweens don't work properly if an object is being scaled by a parent object (for example, tweening the width to 0 does not work)

## Attach a .c3p
[ConstructBugExample.zip](https://github.com/Scirra/Construct-bugs/files/11600693/ConstructBugExample.zip)
Please refer to the object on the right side. 

## Steps to reproduce

Create a new object, set it as a child of an existing object which is being scaled (to the screen size, for example) and then tween the width of the child object to 0 and you will see that it is indeed not zero. This also affects tweening the height of an object. 

## Observed result

The new width of the child object has the wrong value. 

## Expected result

The width should indeed be zero and scale nicely with the scaling of the parent object. 

## System details

PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
I don’t think those bugs are related, my issue is that child objects of scaled parent objects are not tweening to the correct, scaled, values. Rather, the tween uses the values that the child object would have if it wasn‘t being scaled by the parent object.

**Comment by AshleyScirra** [comment]
Please provide a minimal project as per the bug report guidelines, otherwise it's difficult to tell what exactly you are referring to.

**Comment by therealPaulPlay** [comment]
It says in this post and inside the project that the 3rd issue is referring to the object on the right, which is the only object that has the tween behavior. When you click it (it says „click me“ in the project there) you will see that it does not tween to a width of 0.

**Comment by AshleyScirra** [comment]
Please provide a minimal project demonstrating just that alone as per the bug report guidelines.

**Comment by therealPaulPlay** [comment]
[constructTweenIssue.zip](https://github.com/Scirra/Construct-bugs/files/11645468/constructTweenIssue.zip)
Alright, here you go. Sorry, I was busy the last few days so I couldn't make one right away. Hopefully his can be fixed.

**Comment by therealPaulPlay** [comment]
https://github.com/Scirra/Construct-bugs/assets/80539587/77dd8c10-a6ed-4292-806c-3165e289d8af

Here is a video showcasing the issue

**Comment by AshleyScirra** [comment]
@DiegoScirra - not sure what's happening here, looks like the tween ends on a negative value after the parent was resized by the 'Set size' action. Perhaps it's adding/subtracting the width when it should be scaling it? Or treating 0 as a relative end value when it should be absolute?

**Comment by DiegoScirra** [comment]
A fix for this will be available in the next beta release.

**Comment by sotano42** [comment]
This bug is still happening in the latest stable build r368.2. Any update when is it going to be fixed? @DiegoScirra the issue was not happening on r358 release.

**Comment by AshleyScirra** [comment]
This issue has been closed due to previously being fixed. If you are still having trouble please file a new issue.

**Comment by therealPaulPlay** [comment]
Have opened a new issue, as it‘s not happening in the original project anymore but under different circumstances (when you have multiple child objects etc.) 

https://github.com/Scirra/Construct-bugs/issues/7599
