### ISSUE TITLE
Phyics objects with limited revolute joints do not always stay inside the defined boundaries

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7080]
## Problem description

Physics objects with limited revolute joints do not work properly as the object's angle is not staying inside the boundaries but rather snaps back into place

## Attach a .c3p

[ConstructBugExample.zip](https://github.com/Scirra/Construct-bugs/files/11600736/ConstructBugExample.zip)
Please refer to the object on the left side.

## Steps to reproduce

Create 2 new objects, add the physics behavior to both of them, ideally disable collisions on the object that the other one is being hinged to and then do the latter with a revolute joint. If you then try to "spin" the lever in this case with another physics object you will see that it does not stay inside its boundaries. 

## Observed result

It moves down and then snaps back. 

## Expected result

It should always stay inside of the defined angles. 

## More details
Newest stable release

## System details

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's a confusing project file as it appears to still refer to three separate issues, which makes it harder to tell what you mean. Please see the bug report guidelines which advise to provide a minimal project with the fewest events and objects possible.

I think you mean the left-most part of the project, but I can't see anything wrong. It seems to be working normally and works within a limited angle range.

**Comment by therealPaulPlay** [comment]
Yes, it says in this report that I refer to the object on the left. When you pull the lever, is it not staying inside the boundaries and rather snaps back to the initial angle when you stop interacting with it. I‘m no expert but to me it would make a lot more sense if the lever would always stay in the defined range

**Comment by therealPaulPlay** [comment]
https://github.com/Scirra/Construct-bugs/assets/80539587/ac983d93-a98d-4f27-a623-f5789861932a

Here is a video showcasing the bug. Also, what happens regularly, is that the pyhsics behavior just glitches out and no collisions are being registered anymore.

**Comment by AshleyScirra** [comment]
By positioning the round sprite at the mouse you are essentially constantly teleporting a physics object to new positions, which essentially creates an impossible situation for the physics engine (either go past the angle limit, or pass through another object). Neither outcome is realistic. This is why the physics basics tutorial advises against doing that.

**Comment by AshleyScirra** [comment]
Again, the platform behavior and physics behavior won't combine well. Keep everything as physics only.

**Comment by therealPaulPlay** [comment]
Yeah… I get that. It would be quite useful if it did work though. For this case I had to make my own system with gravity, pushback on collision depending on the speed and vector etc. so I‘m just suggesting this as a possible improvement
