### ISSUE TITLE
UID Shuffle Scene graph Git bug with repro

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7082]
## Problem description

Re-submitting this bug with repro: https://github.com/Scirra/Construct-bugs/issues/6865
I added repro after the issue was closed and it seems to have been burried because there was no response after it.

## Attach a .c3p

[Scene graph UID shuffle repro.zip](https://github.com/Scirra/Construct-bugs/files/11151663/Scene.graph.UID.shuffle.repro.zip)

## Steps to reproduce

1. Opening the project shows an error

## Observed result

<details><summary>here is the error:</summary>

Error report information Type: assertion failure Message: child does not have the correct parent Stack: Error at qa.bXa (https://editor.construct.net/r336/main.js:1104:289) at window.assert (https://editor.construct.net/r336/main.js:1019:353) at RBa (https://editor.construct.net/r336/projectResources.js:73:222) at lv.qlb.yg (https://editor.construct.net/r336/projectResources.js:881:459) at d.yg (https://editor.construct.net/r336/projectResources.js:805:177) at d.yg (https://editor.construct.net/r336/projectResources.js:681:489) at d.Ufb (https://editor.construct.net/r336/projectResources.js:1726:356) at d.BYb (https://editor.construct.net/r336/projectResources.js:1804:395) at async d.Zfc (https://editor.construct.net/r336/projectResources.js:1803:439) at async Noa (https://editor.construct.net/r336/main.js:880:412) Construct version: r336 URL: https://editor.construct.net/ Date: Tue Apr 04 2023 20:10:56 GMT+0200 (heure d’été d’Europe centrale) Uptime: 5 s
Platform information
Product: Construct 3 r336 (stable)
Browser: Chrome 111.0.5563.147
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw

</details>

## Expected result

No crash

## More details
The project includes the local git repo so you can checkout commits.
Refer to the original post for more details as I'd rather not copy paste everything for fear of adding unnecessary noise.
The summary is that sometimes git merges can cause a UID overlap and trigger the UID shuffle which doesn't make sure shuffles to mess with the scene graph, and opening the project with an object attached to an instance on another layout corrupts the project.

**Affected browsers/platforms:** All

**First affected release:** Since Scene graph was first introduced

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Can you actually write a series of steps to follow? We need that with every report, every time, regardless of the type of issue. Following a commit history isn't easy as we'd have to reverse-engineer the actual steps to follow from that. Please also make sure all the necessary information is in the same report, as it actually makes it much more complicated to deal with it if we have to cross-reference other issues with information in different places.

**Comment by skymen** [comment]
Ah sorry I thought the step by step repro was for reproducing the crash from the given c3p, not from a blank project.

Here is a video showing the full process step by step:
https://youtu.be/9SJ8OWsuWIE

And here is a step by step breakdown for the entire thing:

1- Create new project
2- Create a sprite and place it on the layout
3- Duplicate that layout (this acts as 2 levels from a game so 2 people can work on their own individual layout)
4- Save as a project folder
5- git init in the folder
6- git commit the changes
7- git checkout a new branch (Now you are acting as Person 2 receiving the files and working on their own branch and their own layout)
8- Make changes to one of the layouts (in my video, Layout 2) and add scene graph data (in my case, by copying the object around and creating a hierarchy)
9- Save and git commit your changes to the new branch
10- git checkout master (Now you are acting as Person 1 working on the project on their side)
11- Close and reopen the project in C3
12- Make changes to the OTHER layout (in my video, Layout 1) and add scene graph data in the same way
13- Save and git commit your changes to master
14- git pull the changes from the new branch into master
15- At this point the merge should be successful since Person 1 ad Person 2 worked on 2 separate layouts
16- Close and reopen the project

**Comment by AshleyScirra** [comment]
r348 has a new random UID numbering mode which you can set in Project Properties. Incremental UIDs are indeed prone to colliding with source control as two contributors can easily create new objects which get assigned the same UID; however with random UIDs the chance of this should be negligible.

In the case of this specific issue I think the problem comes from Construct internally storing UIDs as references to other instances, which doesn't work great with incrementing UIDs as they aren't actually stable identifiers when you involve source control merging. However with random UIDs it should mean collisions essentially never happen, and so UIDs remain stable, and then this issue should not happen in the first place. Therefore perhaps with the new project property for random UIDs, this issue is solved. Would you agree?

**Comment by skymen** [comment]
Yes!

This is a very neat solution.

From my testing, it seems like it's generating a 6 digit random number, wouldn't it be easier if it just generated a random number from 0 up to max_int?

Still, using this collision calculator: https://zelark.github.io/nano-id-cc/
6 digits is still MUCH MUCH MUCH safer than the old incremental version, so thank you very much.

I suppose this new random UID will be enabled by default in the next stable?

**Comment by AshleyScirra** [comment]
OK, closing this issue as I think the new UID numbering setting helps prevent this.

In JavaScript the maximum safe integer is 9007199254740991. Given that sometimes people need to type in UIDs in events and such, using such large numbers would probably be inconvenient. For similar reasons the [default will likely stay the same](https://www.construct.net/en/comments/62122).

Random UIDs also use *at least* 6 digits - to avoid the (probably inevitable) problem that someone adds 1 million objects to a project and runs out of UIDs, it scales the number of digits to the size of the project. Once you cross 100k objects it will increase to 7 digits, once you cross 1 million it will increase to 8 digits, etc. This guarantees that there is always at least 90% of the available UID space free to help avoid any collisions.

**Comment by skymen** [comment]
Alright, that's a fair solution.

Thanks again for the work on this
