### ISSUE TITLE
Layout editor becomes unusable (white) sometimes, after previewing

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7097]
In the past month (maybe 3-4 weeks), the layout editor basically stops working sometimes after previewing. (I use barebones Chrome installed app with no extensions.)

I'm not sure exactly why it happens.

If you want to use the layout editor again, you have to close all of Chrome and then re-open your project again if it happens. (XHXIAIEIN has to restart computer)

_____________________

Me:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/26c1f1a7-3413-4bfa-a2bf-06641b844ad1)

It happens to LukeW too:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/d890a8cc-1376-4852-8398-f815e749af22)

and XHXIAIEIN:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/e3b965eb-a55d-4494-9694-c7e6567c0597)

___________

With my project project, it only happens after I've previewed my game, and  while I play it in fullscreen. So I just test in windowed.

But I can't replicate the preview + fullscreen thing for other projects, and it isn't what it causes it for LukeW.
______________

From XHXIAIEIN: 

> only restart the computer to recover. I'm not sure when it happens, but it does do so after closing the preview. It doesn't happen all the time, but it has happened several times.
>
>Closing the preview - modifying the event sheet - Switch to Layout tabs -  and clicking on the preview does this.  Then this happens.

_______________

It will sometimes show this message sometimes too:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/03605921-f806-42df-9ca7-8e62bce254d4)

It happens before and after updating my NVIDIA (2060) drivers.

I checked Chrome flags to see if webgl was disabled for some reason:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/1a904727-1902-4342-ba0a-b480234e8007)

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/63060bfd-5591-4b8d-a59d-4935cc28adf4)

I pressed F12 and it shows this, I don't know what it all means or if this is normal or not:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/37116a3c-79db-487f-9b2a-85c5d2c52140)

**Comment by AshleyScirra** [comment]
That's the "sad tab" icon that indicates a crash in WebGL, which is usually something caused by a broken graphics driver, or possibly an issue with the browser itself. The later message about WebGL being unavailable seems to back that up. Either way this is not something directly related to Construct so it's out of our control.

I'd note your screenshot appears to enable some experimental WebGL features in the browser flags. If you do that and it causes bugs or crashes, that is entirely your responsibility. We can only support cases where you are using the default flags.

**Comment by alastajj** [comment]
(In regards to the flags, this bug wether webgl flags are enabled or not.)

**Comment by alastajj** [comment]
(The bug occurred before toggling those WebGL flags)
