### ISSUE TITLE
"MobileAdvert" plugin does not work for xCOde and hence for  iOS

### ISSUE THREAD

**Issue by UpToSix** [Scirra/Construct-bugs#7098]
## 

"MobileAdvert" plugin does not work for xCOde and hence for  iOS. Hence we are not able to publish our app in ioS with advertisements. The attached is a super simple code with 1 liner. I'd kindly request to check it once.
This stops our little company from publishing with iOS and admob.
Thai code even when pushed to my iPad it does not load.
It is showing many version errors and generating many threads and CPU consumption.
The same project works on Android without issues.

Appreciate if this is taken with priority please.

## LInk to .c3p file : https://drive.google.com/drive/folders/1jMMQQPK6HO69r-8_WS2FB4JTEs4A2KP9?usp=sharing

The file is saved in the GDrive with open access.

## Steps to reproduce

1.  Download the .c3p file  
2. Open it in Construct3
3. Compile it for xCode
4. Open the workspace file in xCOde
5. Build it in xCode >> Observe the unusual warnings with versioning issues displyed
6. Try to run it on a connected device >> The C3 project will not run and move from the first splash scree

## Observed result

Already given above.

## Expected result

Expected result is:
1. Remove the "Mobile advert" plugin from the .c3p file and follow the same steps above
2. the xCode compiles the code without issues
3. the app loads on a attached iOS device from xCode build

## More details
The "Mobile Advert" actually not working on iOS and stooping us publishing it on iOS. We need a clear direction and solution.

**Affected browsers/platforms:** : NA

**First affected release:** : NA

## System details

iOS and xCode

<details><summary>View details</summary>

Please resolve the issue or provide alternative options. Thanks a lot in advance!

</details>

**Comment by AshleyScirra** [comment]
Are you sure you've correctly configured everything? There are known issues where if the ads are misconfigured, Google's ad SDK can crash which can cause problems. However since that happens in Google's ad SDK it's beyond our control, you just have to make sure it's properly configured.

**Comment by UpToSix** [comment]
Hi Sir,

1. This is working for android
2. Please check the c3P file. It just has the plugin "Mobile Advert" but
not used to launch any adv  - even then giving problem
3. In my real code it is much bigger, hence gave you just a sample code
without any complexity

I'd recommend you please kindly check your test case for "Mobile Advert"
for iOS usage. We are depending on your standard plugins to avoid further
complexity.

Best regards,
Sumanta

Thanks and Best regards,
***@***.***

**Comment by fredriksthlm** [comment]
Just a comment, Ratson was absent for several months, almost a year. So the Admob plugin was not really updated at all.
Now he has re-wrote most of it from scratch and updated everything to the very latest libraries. You can check his website Diego.

**Comment by DiegoScirra** [comment]
The project is misconfigured for iOS exports. The value in the **iOS Application ID** property of the **Mobile Adverts plugin** is not a valid application id.

If you look at it, it has a **"/"** in it. Application ids never have slashes. To get the correct value go into your Admob account, choose your iOS application from the **Apps** menu in the left side, choose **App Settings** and copy and paste the **App ID** value.

**Comment by DiegoScirra** [comment]
@fredriksthlm Thanks for the heads up, will have to check that out.

Will close this issue now.
