### ISSUE TITLE
Video object doesn't play on iOS 16.5

### ISSUE THREAD

**Issue by janfredslund** [Scirra/Construct-bugs#7100]
Playing a video with the Video object is no longer possible on iOS Chrome or Safari. Neither in remote preview nor when exported via Xcode. This is tested on iPhone 13 iOS version 16.5 and it has worked before so I suspect this exact iOS version.

[videotest2.zip](https://github.com/Scirra/Construct-bugs/files/11668398/videotest2.zip)

Run the project in remote preview and open it on iOS device. The video is set to autoplay but you can also push the play button and observe nothing plays. I have provided .mp4 as well as .webm and .ogv files to rule out the file type.

Video doesn't play and the object is not even visible.

**Affected browsers/platforms:** 
Chrome and Safari on iOS. And also when exported via Xcode.
Tested on iPhone 13 iOS version 16.5.

**First affected release:** 
I think it has both worked and not worked in r343, that is why I suspect the updated iOS. Also tested not to work in r344 and r344.2.

<details><summary>View details</summary>

Platform information
Product: Construct 3 r344.2 (stable)
Browser: Chrome 114.0.5735.90
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 159 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I can reproduce, but it looks like a bug in Safari itself: it reports that it can play WebM video files, but when actually attempting playback of a WebM video it fails. We have already filed a couple of issues with Apple about broken WebM support, but so far nothing has happened. We have [great difficulty supporting Safari due to negligent behavior by Apple](https://www.construct.net/en/blogs/ashleys-blog-2/safari-releases-development-1616) in cases like this, so I'm afraid there's not much more we can do.

However as the problem is with WebM specifically, there's an easy workaround: remove all the videos except the MP4 one, and it works, as Safari can successfully play MP4 videos.

**Comment by janfredslund** [comment]
👍
