### ISSUE TITLE
TypeError: expected file (duplicate issue #7073)

### ISSUE THREAD

**Issue by bundleman** [Scirra/Construct-bugs#7103]
## Problem description

Not opened project from local project folder

## Attach a .c3p

[123.zip](https://github.com/Scirra/Construct-bugs/files/11669545/123.zip)

## Steps to reproduce

1. Click to recent project folder

## Observed result

Message screen with test `Failed to open project. Check it is a valid Construct 3 folder project`

https://github.com/Scirra/Construct-bugs/assets/11851931/446c7d61-3d68-48aa-9602-9b01dd077a7e

Messages from console:
`projectResources.js:577 Failed to read file 'layouts\Layout 1.json':  TypeError: expected file
    at Q.Pz (main.js:1057:324)
    at C.f6 (main.js:1106:104)
    at kv.zCc.Psb (projectResources.js:577:68)
    at async Rc.SE.Qza (main.js:1277:286)
Psb @ projectResources.js:577
projectResources.js:576 Failed to read file 'layouts\Layout 1.json':  TypeError: expected file
    at Q.Pz (main.js:1057:324)
    at C.f6 (main.js:1106:104)
    at kv.zCc.Psb (projectResources.js:577:68)
    at async Rc.SE.Qza (main.js:1277:286)
Nz @ projectResources.js:576
main.js:905 [Project] Exception opening:  TypeError: expected file
    at Q.Pz (main.js:1057:324)
    at C.f6 (main.js:1106:104)
    at kv.zCc.Psb (projectResources.js:577:68)
    at async Rc.SE.Qza (main.js:1277:286)`

## Expected result

Project open.

## More details
OS - `Mac OS Ventura 13.3.1 (a)`
UserAgent - `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36`

## System details

<details><summary>View details</summary>

`Platform information
Product: Construct 3 r344.2 (stable)
Browser: Chrome 113.0.5672.126
Browser engine: Chromium
Context: webapp
Operating system: macOS 13.3.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 54 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 655, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)`

</details>

**Comment by WilsonPercival** [comment]
@bundleman Could you show how exactly you open the file you attached?

If I unzip it, then I can safely open it.

https://github.com/Scirra/Construct-bugs/assets/91274932/156c71a7-eb2f-4cc1-9ce6-4db165270dbd

**Comment by bundleman** [comment]
@WilsonPercival Like you but my os Mac OS. That zip archive is only for this issue I try to open it from local folder

https://github.com/Scirra/Construct-bugs/assets/11851931/b1c333e6-73c4-4ade-9198-ee954ed4cc78

**Comment by bundleman** [comment]
@WilsonPercival  What do you think ?

**Comment by WilsonPercival** [comment]
> @WilsonPercival What do you think ?

@bundleman I don't know.

**Comment by JeFawk** [comment]
@bundleman I managed to open it using Chrome on macOS Monterey when opening it as a PROJECT FOLDER.

If I change the extension from .zip to .c3p, it throws the same error you posted.

**Comment by bundleman** [comment]
@JeFawk I'm not trying to open as an archive, but I open it as a project folder

**Comment by JeFawk** [comment]
> @JeFawk I'm not trying to open as an archive, but I open it as a project folder. See my last video

I am fully aware what you are trying to do. I reported my findings and found a solution for you to open your project and keep working on whatever it is you're working on. Seems I completely wasted my time.

**Comment by bundleman** [comment]
@JeFawk Thanks for trying!

**Comment by AshleyScirra** [comment]
It looks like the provided project file is an incorrectly manually zipped project folder. It has the entire project under a subfolder named 123 in the zip, whereas for it to open as a single-file project the files should all be in the root of the zip and not in any subfolder.

Extracting the subfolder to a new folder and then opening it as a project folder works fine, and then if that is compressed to a zip again with the contents in the root and not a subfolder, then that opens fine as a single-file project too.
