### ISSUE TITLE
Replace Object doesn't work on custom actions

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7108]
## Problem description

My project has 2 objects, each has a custom action with the same name. Replacing an object in an event doesn't properly replace its custom action.

## Attach a .c3p
[bug replace action.zip](https://github.com/Scirra/Construct-bugs/files/11716494/bug.replace.action.zip)

## Steps to reproduce

1. right click the OnStartOfLayout block
2. click Replace Object
3. select Sprit2
4. run
5. (result: browser alert "1", which is the action of Sprite. wrong behavior)
6. double click the OnStartOfLayout action
7. double click Action
8. run
9. (result: browser alert "2", which is action of Sprite1. correct behavior)

## Observed result
replacing an object in the block still uses the old action (you can also notice the icon doesn't have the small black custom action symbol).
you have to re-select the action manually in order for C3 to recognize the actual action (and to show the correct icon)

## Expected result

Replace Object selects the proper custom action of the new object.

**Comment by WilsonPercival** [comment]
@Alaadel Everything seems to work well in `r345b`. Are you sure the problem is in the latest beta?

**Comment by Alaadel** [comment]
> @Alaadel Everything seems to work well in `r345b`. Are you sure the problem is in the latest beta?

I am testing the stable release.

**Comment by WilsonPercival** [comment]
> > @Alaadel Everything seems to work well in `r345b`. Are you sure the problem is in the latest beta?
> 
> I am testing the stable release.

@Alaadel The bug reporting guidelines recommend checking for the latest beta releases to avoid re-opening already closed issues: https://github.com/Scirra/Construct-bugs
