### ISSUE TITLE
Replace Object behaves Weirdly with Custom Actions when used with families

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7111]
## Problem description

This is a very weird bug I found that isn't very important because it doesn't break anything but it's weird nonetheless.
Create a custom action block, and then call that custom action in another event.
Now, add the object type to a family, and do a replace Object type on that other event and replace the Object type with the family type

The event now calls a family custom action that doesn't exist, and if I rename the custom action block, it renames that action as well.

If I then duplicate the object type and create a custom action with the same name for that other object type, the family action call works properly (in that it calls both actions).

Even if I go as far as add the custom action to the family, it still works just fine.

The only weird thing happening is that if I rename the first custom action block I made, it will rename the action, but not if I rename the other 2 blocks, including the family custom action.

Here is a video of me reproducing the bug:
https://www.youtube.com/watch?v=QOUiYMZYTNU

## Attach a .c3p
[custom actions bug.zip](https://github.com/Scirra/Construct-bugs/files/11728256/custom.actions.bug.zip)

## Steps to reproduce

1. Rename the Custom Action

## Observed result
The family action gets renamed

## Expected result

The family action doesn't get renamed

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@skymen I can't replicate this in `r345b`. Make sure you test this in the latest beta.

**Comment by skymen** [comment]
You're right, this doesn't happen in last beta. My bad
