### ISSUE TITLE
Crash on mac when using Option + letters in function desc, then using Option + letters in comment above it

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7115]
## Problem description

I started checking for some symbol on my mac using the Option key and doing the piano from the qwert... until bnm,./ keys.
I did so in a function's description. Then I went and did the same in a comment, and C3 crashed:

https://github.com/Scirra/Construct-bugs/assets/7268697/fb7db583-dd9f-4009-9f3e-70a75d31a4a2

## Attach a .c3p

A completely empty project can reproduce this following the steps in the video.

## Steps to reproduce

1. create an empty project
2. make a function
3. go to the function's desc and while holding Option key, press all the keys on the keyboard starting from qwerty...
4. notice the ∑ (option + W) doesn't appear as it's the shortcut to close the event sheet
5. save the function, then do the same in a comment above it

## Observed result

Notice C3 crashes

## Expected result

Expected to not crash and to see ∑ though that's a bit of a stretch considering the current shortcut key.

## More details

**Affected browsers/platforms:** latest Chrome Version 114.0.5735.133 (Official Build) (arm64)

**First affected release:** no idea, just discovered it

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'I') @ TypeError: Cannot read properties of null (reading 'I') at d.I (https://editor.construct.net/r344-2/components/editors/eventSheetView/eventSheetView.js:161:360) at d.ia (https://editor.construct.net/r344-2/components/editors/eventSheetView/eventSheetView.js:161:432) at https://editor.construct.net/r344-2/components/editors/eventSheetView/eventSheetView.js:220:126
Stack: TypeError: Cannot read properties of null (reading 'I') at d.I (https://editor.construct.net/r344-2/components/editors/eventSheetView/eventSheetView.js:161:360) at d.ia (https://editor.construct.net/r344-2/components/editors/eventSheetView/eventSheetView.js:161:432) at https://editor.construct.net/r344-2/components/editors/eventSheetView/eventSheetView.js:220:126
Construct version: r344.2
URL: https://editor.construct.net/
Date: Wed Jun 14 2023 15:56:40 GMT+0200 (Central European Summer Time)
Uptime: 31.9 s

Platform information
Product: Construct 3 r344.2 (stable)
Browser: Chrome 114.0.5735.133
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by AshleyScirra** [comment]
Huh, that's an odd one. It turns out Option+W is the shortcut for closing the current tab, which was conflicting with trying to type in to a comment. It should be fixed for the next beta.
