### ISSUE TITLE
copy paste from one project to another project not working

### ISSUE THREAD

**Issue by luckyrawatlucky** [Scirra/Construct-bugs#7119]
## Problem description
I tried to copy paste animation from animation editor, frames, layout, other objects from project bar > object types even copying instance from layout to another project's layout not working.

## Attach a .c3p
you can use any construct 3 example projects

## Steps to reproduce

1. open construct 3 on 2 different browser's tabs.
2. open any project in 1 tab and/or blank project on another tab
3. try copy pasting anything from entire project to blank project /or any project

## Observed result
copy paste not working.

## Expected result
it should copy and paste content from one project to another.

## More details

stable version is also affected. once fixed please release another stable release for this.
 

**Affected browsers/platforms:** 
Windows / Chrome

**First affected release:** 
Latest stable / r345
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@luckyrawatlucky Turn off.

![aaa](https://github.com/Scirra/Construct-bugs/assets/91274932/abeb0085-d2a0-40fc-afbb-6eb4b7c37fb2)

**Comment by luckyrawatlucky** [comment]
I did tried this, other things working but animations are still not copying.

**Comment by WilsonPercival** [comment]
> I did tried this, other things working but animations are still not copying.

@luckyrawatlucky Are you sure you granted permission to copy?

![aaa](https://github.com/Scirra/Construct-bugs/assets/91274932/2e08d692-4022-4ca1-95d4-37a0debea2cb)

**Comment by AshleyScirra** [comment]
No project was provided so I opened Ghost Shooter, copied the player, and pasted it in to a new empty project in a separate tab. It worked fine for me.

**Comment by luckyrawatlucky** [comment]
I also tried for Ghost Shooter, copy paste objects are working but copy paste animations is not working. 
![image](https://github.com/Scirra/Construct-bugs/assets/17684135/d8550479-f3cd-4c83-b148-0a35e386dc44)
