### ISSUE TITLE
general construct 3 startup problems

### ISSUE THREAD

**Issue by bubbblebub** [Scirra/Construct-bugs#7120]
## Problem description
lately I often had the problem that the newest stable release is not shown in the construct website, I tested in Chrome and Firefox on Mac:
<img width="1627" alt="Bildschirmfoto 2023-06-17 um 09 34 38" src="https://github.com/Scirra/Construct-bugs/assets/35291800/17e582c1-a53a-45bd-8f10-73f6c0c32c92">
as you see only the Beta is visible.
But usually I could work when entering the path manually.

Now after deleting my browser data I have more problems, I cant open my project anymore.
I can log in, but there is still written Free edition. Also after restart of the Browser. in Chrome and Firefox:
<img width="226" alt="Bildschirmfoto 2023-06-17 um 09 36 21" src="https://github.com/Scirra/Construct-bugs/assets/35291800/3b3b5081-99d2-470a-b6aa-9ee8c920e550">

When I try to open the project, it doesnt work, this message appears:
<img width="535" alt="Bildschirmfoto 2023-06-17 um 09 34 05" src="https://github.com/Scirra/Construct-bugs/assets/35291800/7d514fe3-4489-4b54-88a4-8ba47a83b3a8">

So I cant work with construct 3 at the moment. I deleted the Browser Data again but it didnt help.

## Steps to reproduce

1.please see description
2.
3.

## Observed result

construct 3 doesnt work, cant open project, seems to be logged in but not in the same time
## Expected result

I can work with construct 3
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct Animate r344.2 (stable)
Browser: Chrome 114.0.5735.133
Browser engine: Chromium
Context: browser
Operating system: macOS 13.4.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 24 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) HD Graphics 630, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by bubbblebub** [comment]
Meanwhile the problem solved itself somehow. But as it is not the first time I encountered this issue I leave it open. Maybe it is related to bad internet connection?

**Comment by GameSoul7Eugene** [comment]
@bubbblebub, I think you were trying to open a Construct 3 game project that uses _**Custom Movement**_ behavior (which Construct Animate doesn't support). Make sure you are using C3 to open your project instead: [editor.construct.net](https://editor.construct.net/).

**Comment by bubbblebub** [comment]
Indeed I see, thanks for the hint!

**Comment by AshleyScirra** [comment]
It looks like you launched Construct Animate instead of Construct 3. Construct Animate has separate subscriptions and does not include the Custom Movement behavior.
