### ISSUE TITLE
Scaling/tweening is wrong when creating timeline animation

### ISSUE THREAD

**Issue by Ninjadoodle** [Scirra/Construct-bugs#7122]
When playing back my timeline animation inside Construct 3, everything looks correct. When I try to press preview, the scaling/tweening on some parts of the animation is all out of whack.

R 345 Beta
Browser Chrome Version 113.0.5672.126 (Official Build) (x86_64)
Mac OS Ventura Version 13.3.1 (a) (22E772610a)

[Splash.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11783596/Splash.c3p.zip)

**Comment by AshleyScirra** [comment]
I can't see anything wrong between the editor preview and runtime preview in r345. Please always follow the full bug report guidelines every time. We really do need all that information to be able to help you.
