### ISSUE TITLE
Export to Mac Arm using NWJS is reporting that the .app file is damaged. r346

### ISSUE THREAD

**Issue by samuelbromley** [Scirra/Construct-bugs#7125]
## Problem description

when exporting to NWJS, when opening the .app file, it is reported that the file is damaged. 
Exact message is:
“xxx.app” is damaged and can’t be opened. You should move it to the Bin.

## Attach a .c3p

[vs.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11800993/vs.c3p.zip)

## Steps to reproduce

1. export project using NWJS (using Mac Arm option)
2. Open file
3. see error modal

## Observed result

Error Message says:
“xxx.app” is damaged and can’t be opened. You should move it to the Bin.

## Expected result

Game should open

## More details
I have tried it with 3 different projects, and the same result occurs.

I am using this on the latest version of Chrome on a Mac Mini M2 version with 24gb of RAM.

**Affected browsers/platforms:** Chrome

C3 Beta v.364

## System details
Mac Mini M2 2023 model 24gb RAM.

**Comment by JeFawk** [comment]
Did you sign it?
https://www.construct.net/en/tutorials/exporting-desktop-apps-with-nw-js-15

**Comment by samuelbromley** [comment]
yes, i signed it. i have done this many times for exports for M1 etc (using rosetta before).
