### ISSUE TITLE
Checkboxes for layers are still non-color themed for r346

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7126]
## Problem description

<img width="422" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/7746dff6-c360-4b19-8764-2550e41bfea6">

The layers look like so (un-themed):
<img width="303" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/9556cc56-1096-4791-a23a-9a56eacbcfd5">

The themed checkboxes look great!
<img width="260" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/9ca134fc-da79-40a6-b267-5b669614a346">

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** r346

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
