### ISSUE TITLE
Setting a layer's scale can change another layer's scroll position if unbounded scrolling is off

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7146]
## Problem description

I was experimenting with layer scrolls and scales when I found a weird behavior. If I set a layer's scroll and scale, it can affect the scrolling of other layers despite them supposedly not being linked

## Attach a .c3p

[layer scale and scroll bug.zip](https://github.com/Scirra/Construct-bugs/files/11857074/layer.scale.and.scroll.bug.zip)

## Steps to reproduce

1. Change the slider bar

## Observed result

Layer 1 scales correctly, but Layer 0's scroll moves even though it has a "scroll to" object on it that should scroll it back to the center.

This also happens when the scroll to sprite isn't there by the way.

## Expected result

Layer 0 should be unaffected

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** No idea

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It does look confusing but I think it's working as designed. The bounded scrolling mode applies a minimum and maximum scroll position based on the minimum layer scale. The minimum scale looks at all layers, regardless of whether they are independently scrolled, and the scroll boundaries are also applied to all layers regardless of their own independent scrolling. Therefore reducing the scale of Layer 1 will affect the allowed scroll boundaries of Layer 0.

I think wherever the scroll bounds cause unwanted results, the best thing to do is just turn on unbounded scrolling and if necessary impose any scroll boundaries in events.
