### ISSUE TITLE
Crash child is not in parent's list

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7147]
## Problem description

Construct crashes.

## Attach a .c3p

[crash_child_is_not_in_parent's_list_r346b.zip](https://github.com/WilsonPercival/WilsonPercival/files/11858355/crash_child_is_not_in_parent.s_list_r346b.zip)

## Steps to reproduce

1. Open a project.
2. Remove `Layer 1`.
3. Remove the `fun` object from the project.
4. Click `Undo`.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/4d0d46d4-de93-41a8-b0dd-ccb84471c3c9

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r346b

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: child is not in parent's list
Stack: Error at pa.x_a (https://editor.construct.net/r346/main.js:1129:314) at window.assert (https://editor.construct.net/r346/main.js:1044:353) at YCa (https://editor.construct.net/r346/projectResources.js:73:278) at yv.zpb.hU (https://editor.construct.net/r346/projectResources.js:892:320) at yv.zpb.Og (https://editor.construct.net/r346/projectResources.js:893:72) at WCa.d.ZB.d.n_ (https://editor.construct.net/r346/projectResources.js:70:410) at wca (https://editor.construct.net/r346/main.js:212:254) at CCG.xca (https://editor.construct.net/r346/main.js:210:282) at Ipa (https://editor.construct.net/r346/main.js:933:178) at https://editor.construct.net/r346/main.js:2931:382
Construct version: r346
URL: https://editor.construct.net/r346/
Date: Sun Jun 25 2023 01:18:54 GMT+0300 (Восточная Европа, летнее время)
Uptime: 36.5 s

Platform information
Product: Construct 3 r346 (beta)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_lose_context, WEBGL_multi_draw, OVR_multiview2

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - looks like editor scene graph connections are still tried to be restored for a deleted layer.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta

**Comment by WilsonPercival** [comment]
@DiegoScirra I think you are wrong. This should show `Next beta` instead of `r348`. Because `r348b` still hasn't fixed it.

![obser](https://github.com/Scirra/Construct-bugs/assets/91274932/a62b227e-fe92-425c-a279-abab79781703)
