### ISSUE TITLE
Simulate Jump works only once while holding the touch

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7148]
## Problem description
My project allows the player to hold the jump button. I expected doing so will make the player keep jumping as soon as it hits the ground. But Simulate Jump fires only once, and I have to release the touch to make it jump again.

## Attach a .c3p
[sim jump.zip](https://github.com/Scirra/Construct-bugs/files/11859686/sim.jump.zip)

## Steps to reproduce

1. Hold the touch on the blue sprite

## Observed result

red sprite jumps once

## Expected result

red sprite keeps jumping (as soon as it hits the floor, i.e. jump is possible). if double jump is enabled, the sprite should keep jumping as much as possible.

**First affected release:** Stable

**Comment by AshleyScirra** [comment]
This is not to do with 'simulate control' - the default controls work the same: allowing holding the button to keep jumping is called "bunnyhopping", and usually it's an unwanted feature, so the platform behavior logic prevents it.

It's easy to work around in this case: just add an 'Is on floor' condition.

**Comment by Alaadel** [comment]
> This is not to do with 'simulate control' - the default controls work the same: allowing holding the button to keep jumping is called "bunnyhopping", and usually it's an unwanted feature, so the platform behavior logic prevents it.
> 
> It's easy to work around in this case: just add an 'Is on floor' condition.

Thank you.

If I call Simulate Control Left repeatedly, the object keeps moving left.
If I call Simulate Control Right repeatedly, the object keeps moving right.
If I call Simulate Control Jump repeatedly, the object jumps only once? This is not aligned with the left and right behavior, and not an intuitive expectation for the user.

Simulate Control imo should do as its name says. When a programmer calls a function, it should do as it says, instead of adding its own hidden logic and overriding the developer's expectations. And if it does a different thing than what it says, the name and editor description should clearly indicate that.

First, Simulate Control should just simulate the control, as long as it is called.
Second, preventing bunnyhopping should be the responsibility of the developer; i.e. by calling simulate control once (while on floor). In other words, Simulate Control should be continuous (as the name and left/right behavior suggest) by default, and the user can prevent this if he wanted by **adding** conditions.

At the very least, it should have 2 options: Jump Once (no bunnyhopping), and Jump (expected jumping "bunnyhopping").
Having to use an unintuitive workaround (e.g. adding a condition to override hidden logic) for a simple behavior like this doesn't really make sense for me.

Thank you.

**Comment by WilsonPercival** [comment]
> When a programmer calls a function, it should do as it says, instead of adding its own hidden logic and overriding the developer's expectations.

@Alaadel Totally agree with you.

**Comment by AshleyScirra** [comment]
'Simulate control' does exactly the same thing as pressing the key with default controls, so it does work consistently. If you want something different to what normally happens when you press controls, then you need to add extra logic for that.

**Comment by Alaadel** [comment]
> 'Simulate control' does exactly the same thing as pressing the key with default controls, so it does work consistently. It would in fact be surprising and inconsistent if it worked differently (and probably result in complaints and bug reports about the inconsistency). If you want something different to what normally happens when you press controls, then you need to add extra logic for that.

Thank you, I did not realize the Platformer behavior actually works that way.
But that shifts the issue from the SimulateController to the Platformer behavior.
If moving left and right works by pressing or holding, then why does pressing up works only by pressing (holding has no effect) ?

It seems this is the source of the inconsistency problem for me.
Honestly, I think all controls should work in the same way (i.e. by pressing or holding), and the Platformer behavior can have a bool option to disable this for jumping. [I have added this suggestion here](https://construct23.ideas.aha.io/ideas/C23-I-347).

**Comment by WilsonPercival** [comment]
> > 'Simulate control' does exactly the same thing as pressing the key with default controls, so it does work consistently. It would in fact be surprising and inconsistent if it worked differently (and probably result in complaints and bug reports about the inconsistency). If you want something different to what normally happens when you press controls, then you need to add extra logic for that.
> 
> Thank you, I did not realize the Platformer behavior actually worked that way. But that shifts the issue from the SimulateController to the Platformer behavior. If moving left and right works by pressing or holding, then why does pressing up works only by pressing (holding has no effect) ?
> 
> It seems this is the source of the inconsistency problem for me. Honestly, I think all controls should work in the same way (i.e. by pressing or holding), and the Platformer behavior can have a bool option to disable this for jumping, or at least an option to enable "bunnyhopping". [I have added this suggestion here](https://construct23.ideas.aha.io/ideas/C23-I-347).

@Alaadel This has already been implemented in Construct Classic:

![obser](https://github.com/Scirra/Construct-bugs/assets/91274932/582d060b-a0be-4b4e-b8a3-527160dafcab)

**Comment by AshleyScirra** [comment]
> If moving left and right works by pressing or holding, then why does pressing up works only by pressing (holding has no effect) ?

Because that's how almost everyone wants it to work.
