### ISSUE TITLE
Missing transformOpacity and transformVisibility in documentation

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7149]
## Problem description

The script documentation is missing `transformOpacity` and `transformVisibility`.

https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/object-interfaces/iworldinstance

## Attach a .c3p

No.

## Steps to reproduce

1. Follow the link.

## Observed result

![observed](https://github.com/WilsonPercival/WilsonPercival/assets/91274932/2b5c6c26-3ebd-409c-8149-3e0a395f6e5e)

## Expected result

The script documentation has `transformOpacity` and `transformVisibility`.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in 2023

## System details

<details><summary>View details</summary>

![175827374-34cc405b-90fe-4e6e-90e0-482114318fea](https://github.com/WilsonPercival/WilsonPercival/assets/91274932/7b39af09-535f-4b41-b775-70ea971d4c0f)

</details>

**Comment by AshleyScirra** [comment]
Updated documentation to include those properties.
