### ISSUE TITLE
Effect SDK Example: Incorrect color preview in editor

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7150]
## Problem description

I downloaded the Effect SDK files (c3-effect-sdk-v1-3.zip) from the manual.   
And changed the parameters inside from `vec4(1.0, 0.0, 0.0, 1.0)` to `vec4(1.0, 1.0, 1.0, 1.0)`. 
  
Restart and back to C3, This is a **white** Sprite, after the effect is added, it will be displayed in blue in the editor. but in the preview will be displayed in **green**.  

![Snipaste_2023-06-26_14-26-34](https://github.com/Scirra/Construct-bugs/assets/45864744/08357d11-5188-4425-873e-3c42932ddeb4)

## Attach a .c3p

Effect Addon file:
[edit-sample-webgl2.zip](https://github.com/Scirra/Construct-bugs/files/11865155/edit-sample-webgl2.zip)

C3 Project file:
[issue-webgl2-effect.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11865120/issue-webgl2-effect.c3p.zip)

## Observed result

Even if I restarted C3 Editor, Restarted the local server, uninstalled and reinstalled the plugin, the result was the same.

my local server started with this python code.
<details><summary>Python SimpleHTTPRequestHandler</summary>

```python
from http.server import HTTPServer, SimpleHTTPRequestHandler, test
import sys

class CORSRequestHandler (SimpleHTTPRequestHandler):
    def end_headers (self):
        self.send_header('Access-Control-Allow-Origin', '*')
        SimpleHTTPRequestHandler.end_headers(self)

    def send_my_headers(self):
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        self.send_header("Pragma", "no-cache")
        self.send_header("Expires", "0")

if __name__ == '__main__':
    test(CORSRequestHandler, HTTPServer, port=60000)
```

URL
```
http://localhost:60000/sample-webgl2/addon.json
```

</details>

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r346 (beta)
Browser: Chrome 114.0.5735.134
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 140 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: nvidia
Adapter architecture: pascal
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features:

bgra8unorm-storage
depth-clip-control
depth32float-stencil8
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It works for me - the effect outputs only a white color.

The unmodified effect SDK files show blue for the WebGPU shader (which your system details indicate is enabled in the editor), and green for WebGL 2 (which is the default at runtime). So it looks like your screenshot is using the unmodified effect SDK files rather than your edits. I suspect this is either a local caching problem or you just got confused with which files are in use, which is easy to do (I often make that kind of mistake!)

**Comment by XHXIAIEIN** [comment]
I noticed it was a problem with the local server, because I was running this python program in VSCode, and it pointed to a different local path than the addon.json.(This is my first time to at making a plugin)

Can I continue to ask a question?

If I change something in effect.fx, like adjust a parameter, do I need to restart C3 to continue previewing it? Does the editor have any Automatic sync update feature?

---

Suggestion that the Add dev addon dialog of the Addon manager will also support the file system api
