### ISSUE TITLE
Cloning/copying sprite results in unusable copy with "(no instances)"

### ISSUE THREAD

**Issue by cypressi** [Scirra/Construct-bugs#7154]
## Problem description

Attempting to clone or copy/paste a certain sprite (see "cabinet" object the project) results in an unusable copy, with all behavior values showing "(no instances)".

## Attach a .c3p

[clone_cabinet.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11889779/clone_cabinet.c3p.zip)

## Steps to reproduce

1. Right click "cabinet" object.
2. Click clone. Alternatively click copy/paste.
3. Click new "cabinet2".

## Observed result

 Notice behavior values are "(no instances)", making the object unusable.
<img width="295" alt="no_instances" src="https://github.com/Scirra/Construct-bugs/assets/137843760/d95769a2-1bdf-4b06-92f9-a6c7824b1b2e">

## Expected result

A usable copy/clone, with valid behavior properties.

## More details

Happens with r344.2 and r347 beta.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r347 (beta)
Browser: Chrome 114.0.5735.133
Browser engine: Chromium
Context: browser
Operating system: macOS 13.2.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 56 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
@cypressi Just instantiate the `cabinet2` object.

**Comment by AshleyScirra** [comment]
This is by design. There are no instances of the object type in the project, and so nothing can be shown for property values. Add an instance to the project and its properties will be filled out.
