### ISSUE TITLE
Z order bar sometimes doesn't show all layers

### ISSUE THREAD

**Issue by cypressi** [Scirra/Construct-bugs#7155]
## Problem description

The z order bar in inconsistent, in the layers it shows. Opening and closing the z order bar sometimes forces it to show all layers.

## Attach a .c3p

[clone_cabinet.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11889801/clone_cabinet.c3p.zip)

## Steps to reproduce

1. Make the z order bar visible. All layers should show properly in the list. If not, try clicking a layer in the layer bar to "fix" it temporarily.
2. Click away from cabinet object. Click cabinet object (1 in image below).
3. The z order bar now omits most layers.
4. Close the z order bar. Repeat.

## Observed result

<img width="303" alt="layer_order_oddness" src="https://github.com/Scirra/Construct-bugs/assets/137843760/4731bf31-8ee2-4b70-b94c-0f7d1d5beba9">

1. Cabinet object to click (see issue #7154)
2. All layers available.
3. Z order menu. Notice how most layers aren't available. If I close and open the z order bar, they sometimes are. Notice "cabinet 8" rather than "cabinet".

## Expected result

All layers should be available to place the object into:
<img width="305" alt="good_zorder" src="https://github.com/Scirra/Construct-bugs/assets/137843760/b77719f3-4642-46d1-b805-3b91dd8a39be">

## More details

Possibly related to issue #7154.

Happens with r344.2 and r347 beta.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r347 (beta)
Browser: Chrome 114.0.5735.133
Browser engine: Chromium
Context: browser
Operating system: macOS 13.2.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 56 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is by design and [is documented in the manual](https://www.construct.net/en/make-games/manuals/construct-3/interface/bars/z-order-bar).
