### ISSUE TITLE
drag and drop behavior, instance moved while is dragging is false

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7158]
## Problem description
when dragging and object with the drag and drop behavior, the instance is moved while is dragging is false

## Attach a .c3p
[isDraggingIssue.zip](https://github.com/Scirra/Construct-bugs/files/11895868/isDraggingIssue.zip)

## Steps to reproduce

1.drag the red sprite and move the mouse past the bound
2. release the mouse (it is important that you release the mouse quickly during the drag)

https://github.com/Scirra/Construct-bugs/assets/89512047/41a73d8e-6866-43fa-8c95-8be1397c5f8e

## Observed result
red sprite is placed outside the clamped area

## Expected result
red sprite stays inside the clamped area

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@F3der1co There it is necessary not quickly, but it is necessary that the mouse continues to move at the moment of release. Then I can permanently move the sprite outside of the outline.

https://github.com/Scirra/Construct-bugs/assets/91274932/8cc8f447-7da2-4554-8c64-690a622a22f2
