### ISSUE TITLE
White screen bug when running webgpu on 16GB PC

### ISSUE THREAD

**Issue by euromikesurf** [Scirra/Construct-bugs#7166]
After your new Construct Beta, I switched renderer to the new webgpu version and I see HUGE MASSIVE improvement in performance of my RTS game. The maps load now in less than 3 seconds (previously it took 15 secs to load) and FPS is averaging 200-300 vs previously 60-90.

However on PCs with less memory (16GB) I am experiencing a bad white screen issue with this new webgpu renderer. The game runs but all I can see is mouse and white screen! I can still hear the music in background and i can even click on buttons but I don't see anything, so it's not a full crash but fail of renderer.

This is very strange because the game uses just 4gb of memory so 16GB should be more than enough to run it but I can't understand how to get rid of white screen issue with webgpu ? It runs okay on 16GB with old school WebGL.

The white screen comes even in Main menu where there is just few sprites and it's definitely not overloaded by action so it's not an issue of having too many things to render.

It runs perfectly fine on 32gb PC. Any advice what is causing the white screen issues?

**Comment by euromikesurf** [comment]
Below is debug info from the PC that has white screen on Webgpu

chrome://gpu/

DAWN Info


    <Integrated GPU> D3D12 backend - Intel(R) HD Graphics 4600
    [WebGPU Status]
    Available
    [Default Toggle Names]
    lazy_clear_resource_on_first_use: https://crbug.com/dawn/145: Clears resource to zero on first usage. This initializes the resource so that no dirty bits from recycled memory is present in the new resource.
    use_d3d12_resource_heap_tier2: https://crbug.com/dawn/27: Enable support for resource heap tier 2. Resource heap tier 2 allows mixing of texture and buffers in the same heap. This allows better heap re-use and reduces fragmentation.
    use_d3d12_render_pass: https://crbug.com/dawn/36: Use the D3D12 render pass API introduced in Windows build 1809 by default. On versions of Windows prior to build 1809, or when this toggle is turned off, Dawn will emulate a render pass.
    use_d3d12_residency_management: https://crbug.com/dawn/193: Enable residency management. This allows page-in and page-out of resource heaps in GPU memory. This component improves overcommitted performance by keeping the most recently used resources local to the GPU. Turning this component off can cause allocation failures when application memory exceeds physical device memory.
    disallow_unsafe_apis: http://crbug.com/1138528: Produces validation errors on API entry points or parameter combinations that aren't considered secure yet.
    d3d12_split_buffer_texture_copy_for_rows_per_image_paddings: https://crbug.com/dawn/1289: D3D12 requires more buffer storage than it should when rowsPerImage is greater than copyHeight, which means there are pure padding row(s) on each image. In this situation, the buffer used for B2T/T2B copy might be big enough according to WebGPU's spec but it doesn't meet D3D12's requirement, then we need to workaround it via split the copy operation into two copies, in order to make B2T/T2B copy being done correctly on D3D12.
    d3d12_always_use_typeless_formats_for_castable_texture: https://crbug.com/dawn/1276: Always use the typeless DXGI format when we create a texture with valid viewFormat. This Toggle is enabled by default on the D3D12 platforms where CastingFullyTypedFormatSupported is false.
    d3d12_use_temp_buffer_in_depth_stencil_texture_and_buffer_copy_with_non_zero_buffer_offset: https://crbug.com/dawn/727: Split buffer-texture copy into two copies: do first copy with a temporary buffer at offset 0, then copy from the temporary buffer to the destination. Now this toggle must be enabled on the D3D12 platforms where programmable MSAA is not supported.
    d3d12_use_temp_buffer_in_texture_to_texture_copy_between_different_dimensions: https://crbug.com/dawn/1216: Use an intermediate temporary buffer when copying between textures of different dimensions. Force-enabled on D3D12 when the driver does not have the TextureCopyBetweenDimensionsSupported feature.
    apply_clear_big_integer_color_value_with_draw: https://crbug.com/dawn/537: Apply the clear value of the color attachment with a draw call when load op is 'clear'. This toggle is enabled by default on D3D12 backends when we set large integer values (> 2^24 or < -2^24 for signed integer formats) as the clear value of a color attachment with 32-bit integer or unsigned integer formats because D3D12 APIs only support using float numbers as clear values, while a float number cannot always precisely represent an integer that is greater than 2^24 or smaller than -2^24). This toggle is also enabled on Intel GPUs on Metal backend due to a driver issue on Intel Metal driver.
    d3d12_polyfill_reflect_vec2_f32: https://crbug.com/tint/1798: Polyfill the reflect builtin for vec2<f32> for D3D12. This toggle is enabled by default on D3D12 backends using FXC on Intel GPUs due to a driver issue on Intel D3D12 driver.
    [WebGPU Forced Toggles - enabled]
    disallow_spirv: https://crbug.com/1214923: Disallow usage of SPIR-V completely so that only WGSL is used for shader modules. This is useful to prevent a Chromium renderer process from successfully sending SPIR-V code to be compiled in the GPU process.
    [Supported Features]
    texture-compression-bc
    pipeline-statistics-query
    timestamp-query
    timestamp-query-inside-passes
    depth-clip-control
    depth32float-stencil8
    indirect-first-instance
    rg11b10ufloat-renderable
    dawn-internal-usages
    multiplanar-formats
    dawn-native
    implicit-device-sync
    surface-capabilities

**Comment by AshleyScirra** [comment]
I'm afraid it's impossible to help unless you follow the bug report guidelines.
