### ISSUE TITLE
Adding instance variable to timeline result crash

### ISSUE THREAD

**Issue by Finalizator** [Scirra/Construct-bugs#7167]
## Problem description

When I open BossWalkIn timeline and rightclick on RoboBoss item to add properties and choose instance variable "Animation", Construct crashes

## Attach a .c3p
[Bugreport1.zip](https://github.com/Scirra/Construct-bugs/files/11929486/Bugreport1.zip)

## Steps to reproduce

1. Open project.
2. Go to BossWalkIn timeline
3. RightClick on RoboBoss
4. Click on Add properties
5. Select instance variable "Animation"
6. Confirm selection

## Observed result

Construct crashed with a report

## Expected result

Animation variable added to timeline

## More details

**Affected browsers/platforms:** 

Can not specify, but problem is not new. Happened before r347

## System details

<details><summary>Details</summary>
<p>

Error report information

Type: unhandled rejection
Reason: Error: expected function @ Q.Nb@https://editor.construct.net/r347/main.js:1058:38 pa.j@https://editor.construct.net/r347/main.js:1136:26 Qsb@https://editor.construct.net/r347/projectResources.js:1180:190 d@https://editor.construct.net/r347/projectResources.js:1175:262 pa.j@https://editor.construct.net/r347/main.js:1136:44 fI@https://editor.construct.net/r347/projectResources.js:1104:92 IOb@https://editor.construct.net/r347/projectResources.js:1105:40 pjc@https://editor.construct.net/r347/projectResources.js:1105:161 P2.fI/<@https://editor.construct.net/r347/components/bars/timelineBar/timelineBar.js:258:393
Stack: Q.Nb@https://editor.construct.net/r347/main.js:1058:38 pa.j@https://editor.construct.net/r347/main.js:1136:26 Qsb@https://editor.construct.net/r347/projectResources.js:1180:190 d@https://editor.construct.net/r347/projectResources.js:1175:262 pa.j@https://editor.construct.net/r347/main.js:1136:44 fI@https://editor.construct.net/r347/projectResources.js:1104:92 IOb@https://editor.construct.net/r347/projectResources.js:1105:40 pjc@https://editor.construct.net/r347/projectResources.js:1105:161 P2.fI/<@https://editor.construct.net/r347/components/bars/timelineBar/timelineBar.js:258:393
Construct version: r347
URL: https://editor.construct.net/r347/
Date: Sun Jul 02 2023 15:28:22 GMT+0300 (Восточная Европа, летнее время)
Uptime: 390.9 s
Platform information

Product: Construct 3 r347 (beta)
Browser: Firefox 114.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_provoking_vertex

</p>
</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7157

**Comment by DiegoScirra** [comment]
This was introduced in the latest beta from attempting to fix #7134. Both issues will be resolved in the next beta.
