### ISSUE TITLE
Custom Movement behavior's initial angle of motion set incorrectly if speed is 0

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-bugs#7169]
## Problem description

Setting a custom movement behavior's angle of motion before setting its speed to something other than 0 results in the angle being wrong. It's either being set as 0 or 180/-180 depending on the angle passed into the _Set angle of motion_ action.

## Attach a .c3p
[CustomMovementBug.zip](https://github.com/Scirra/Construct-bugs/files/11944751/CustomMovementBug.zip)

## Steps to reproduce

1. Create a sprite and add the Custom movement behavior to it.
2. On the sprite's _On created_ event, use the _Set angle of motion action_ to set the Custom movement behavior angle of motion to something greater than zero but less than 180, or less than zero but greater than -180.
3. Set the Custom movement behavior's overall speed to something non-zero (to demonstrate the bug)
4. Launch the project and observe the sprite's angle of motion

## Observed result

Depending on the angle passed in, the sprite's angle of motion will always be zero, 180, or -180 rather than the value set in the On created event.

Note: setting the speed to something other than zero before setting the angle of motion results in the angle of motion being set correctly.

## Expected result

The angle of motion should be what it was set to using the _Set angle of motion_ action.

## More details

**Affected browsers/platforms:** 
Microsoft store version + Chrome

Noticed in r347

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r347 (beta)
Browser: Edge 114.0.1823.67
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 118 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: nvidia
Adapter architecture: ampere
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features:

bgra8unorm-storage
depth-clip-control
depth32float-stencil8
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This is the same issue as #6105: a zero vector has no angle, and the result is just how the maths works out. Set the speed first and it works.

**Comment by Scoremonger** [comment]
I see, but what we're describing is confusing behavior that's impossible to debug at such a low level for end users like us. It's another of these "not a bug if you understand the underlying implementation details" issues. Those of us that encounter this waste our time figuring out what's going on (sort of) and even writing up apparently useless bug reports about it.

It seems reasonable for us to have assumed that you're storing the angle of motion in the behavior, regardless of speed, then applying it when appropriate. The _Set angle of motion_ action arguably makes this promise, since it has no disclaimer that it will only do its job when the object is moving. If you don't want to change the implementation, please at least consider adding this warning somewhere in the relevant Bullet and Custom movement actions so more people, including you, don't lose their valuable time to this.

**Comment by WilsonPercival** [comment]
> I see, but what we're describing is confusing behavior that's impossible to debug at such a low level for end users like us. It's another of these "not a bug if you understand the underlying implementation details" issues. Those of us that encounter this waste our time figuring out what's going on (sort of) and even writing up apparently useless bug reports about it.
> 
> It seems reasonable for us to have assumed that you're storing the angle of motion in the behavior, regardless of speed, then applying it when appropriate. The _Set angle of motion_ action arguably makes this promise, since it has no disclaimer that it will only do its job when the object is moving. If you don't want to change the implementation, please at least consider adding this warning somewhere in the relevant Bullet and Custom movement actions so more people, including you, don't lose their valuable time to this.

@Scoremonger This is what was stated in the documentation, which you did not read.

https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/bullet

![obser](https://github.com/Scirra/Construct-bugs/assets/91274932/728d44be-e35a-4ba2-b02f-0645b7ecca57)

**Comment by Scoremonger** [comment]
@WilsonPercival Yes, but this is not obvious from within the editor, nor is it intuitive.
