### ISSUE TITLE
On End Animation finished can not trigger.

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-bugs#7173]
## Problem description
On End Animation finished can not trigger.

## Attach a .c3p
[OnEndAnimation_Bug.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11951520/OnEndAnimation_Bug.c3p.zip)
## Steps to reproduce
1. Create Sprite with animation loop
2. Add event command "On Animation 1 finished" then log on the console.

## Observed result
 Nothing show on the log of console.

## Expected result

Console should log when animation finished each animation loop.

## More details
 - Chrome.
 - Construct 3 r 344.2

**Comment by AshleyScirra** [comment]
This is by design. "On animation finished" only triggers when all repeats have finished, and so if it loops forever, it will never finish.
