### ISSUE TITLE
Timeline 'Initial frame' capped by first animation

### ISSUE THREAD

**Issue by Animmaniac** [Scirra/Construct-bugs#7177]
## Problem description

When keyframing the 'Initial frame' of a Sprite animation on the timeline, it's not possible to set the value bigger than the frame count of the first animation of the object.

For instance, if 'Animation1' have 1 frame, and 'Animation2' have 3 frames, you can't keyframe the 'Initial frame' to the value of 1 or 2, even if you keyframed 'Initial animation' to 'Animation2'. It will get capped at 0, because 'Animation1' have only 1 frame.

Though it's possible to add an 'Initial frame' keyframe, select the keyframe on the timeline, and edit the keyframe value on the Properties Bar with a greater value. Then if you select the Sprite object or the 'Initial frame' keyframe, they will have different values, but it won't playback regardless.

## Attach a .c3p

[timeline-frame-limit-bug-A02.zip](https://github.com/Scirra/Construct-bugs/files/11974006/timeline-frame-limit-bug-A02.zip)

## Steps to reproduce

1. Enter editing mode for 'Timeline 1'.
2. Select the Sprite and try to keyframe its 'Initial frame' to any value bigger than 0.
3. Observe the keyframe value and the Sprite frame on the layout.
4. Select the 'Initial frame' keyframe, set its value to 3 on the Properties Bar.
5. Scrub the timeline and observe the keyframe value and the Sprite frame on the layout.
6. Select the Sprite on the layout and observe it's 'Initial frame' value.

## Observed result

On step 3, the 'Initial frame' value is always reset to 0, and the Sprite frame never changes in the layout.

On step 5 and 6, the 'Initial frame' value of the keyframe (on the Properties Bar) is different from the Sprite 'Initial frame' (on the Properties Bar), and the Sprite frame on the layout never changes.

## Expected result

On step 3, the 'Initial frame' value should be set to any value the user sets, and the Sprite frame on the layout should reflect the changes.

On step 5 and 6, the 'Initial frame' value of the keyframe should be equal to the Sprite 'Initial frame' value, and the Sprite frame on the layout should reflect the changes.

## More details

**Affected browsers/platforms:**  Tested only on Chrome 114.0.5735.199

**First affected release:**  Tested on Construct Animate r348 (beta) and recent previous versions.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct Animate r348 (beta)
Browser: Chrome 114.0.5735.199
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 224 gb
Storage usage (approx): 159 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
