### ISSUE TITLE
Mouse right double-click not working.

### ISSUE THREAD

**Issue by KhaledFelfal** [Scirra/Construct-bugs#7180]
## Problem description

The mouse right button double click event doesn't trigger at all. Left right click does trigger though.

## Attach a .c3p

https://drive.google.com/file/d/1Nrwp70pFfIIzbXNqTXKctMmIQ1puGK3e/view?usp=sharing

## Steps to reproduce

Already attached a .c3p file 

## Observed result

Nothing, it doesn't trigger at all.

## Expected result

The right moue button double click triggers

## More details

**Affected browsers/platforms:** 

All browsers.

**First affected release:** never worked on any version of construct up to latest beta release 7 July 2023. 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r344.2 (stable)
Browser: Edge 114.0.1823.67
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 261 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The browser `dblclick` event only fires for the primary (left) button, so it's the browser that only fires double click events for left buttons, rather than being anything to do with Construct. I think this used to work, but I guess it changed in browsers at some point in the past 10+ years since Construct 2 first introduced this condition.

In theory we should probably have two triggers for this - one for left/middle/right click, and a separate one for double-click with no mouse button choice, corresponding to the way the `dblclick` event works. However I think this is so rarely used that the disruption caused by changing a core long-standing feature outweighs the benefit, so I think it's better that we don't take any action.
