### ISSUE TITLE
Unchecking timeline 'Loop' breaks hierarchy on playback (Animate)

### ISSUE THREAD

**Issue by Animmaniac** [Scirra/Construct-bugs#7181]
## Problem description

For some reason, unchecking 'Loop' in the timeline appears to break an object hierarchy for this project while in timeline editing mode. Deleting the second frame from a Sprite animation that is part of the hierarchy, weirdly seems to completely break it (even thought the frame is not used) while in timeline editing mode.

## Attach a .c3p

[timeline-loop-hierarchy-bug-B15.zip](https://github.com/Scirra/Construct-bugs/files/11988795/timeline-loop-hierarchy-bug-B15.zip)

*This is a stripped down version from a more complex project of some character animations (Piggy animations). I was not able to reproduce from scratch.

## Steps to reproduce

1. Enter editing mode for 'Timeline 1'.
2. Play 'Timeline 1'. Observe the Sprites in the layout. Then stop playback.
3. Uncheck 'Loop' from 'Timeline 1' in the Properties Bar.
4. Play 'Timeline 1' two or more times. Observe the Sprites in the layout.
5. Check 'Loop' from 'Timeline 1' in the Properties Bar.
6. Play 'Timeline 1'. Observe the Sprites in the layout. Then stop playback.
7. Open Sprite's Animation Editor, delete the second frame from the animation named 'Top', then close the editor. Observe the Sprites in the layout.
8. Play 'Timeline 1' again. Observe the Sprites in the layout. Then stop playback.
9. Exit editing mode for 'Timeline 1'. Observe the Sprites in the layout.
10. Enter editing mode for 'Timeline 1' again. 
11. Play 'Timeline 1'. Observe the Sprites in the layout.

## Observed result

In steps 2, 6, 9 and 11, the Sprite hierarchy and animation appear as expected.
![timeline-loop-hierarchy-bug-B01](https://github.com/Scirra/Construct-bugs/assets/29487913/a33dd72c-64d1-4986-b33a-9909bb759d9b)

In steps 4 and 7, the Sprite hierarchy appears broken, with children out of place while 'Timeline 1' is stopped.
![timeline-loop-hierarchy-bug-C01](https://github.com/Scirra/Construct-bugs/assets/29487913/3f0c4eac-aa5e-47b7-a371-66d2d681606a)

In Step 8, the Sprite hierarchy appears broken, with children not even animating or following the parent movement while on playback.
![timeline-loop-hierarchy-bug-D01](https://github.com/Scirra/Construct-bugs/assets/29487913/f75e9131-bc27-426e-ad0d-c56d5ff92d0f)

## Expected result

In steps 4, 7 and 8, the Sprite hierarchy should not appear broken, and children should animate properly following their parent transformation.
![timeline-loop-hierarchy-bug-B01](https://github.com/Scirra/Construct-bugs/assets/29487913/a33dd72c-64d1-4986-b33a-9909bb759d9b)

## More details

**Affected browsers/platforms:**  Chrome 114.0.5735.199

**First affected release:**  Tested on Construct Animate r348 (beta) and a few previous releases

## System details

<details><summary>View details</summary>

Platform information
Product: Construct Animate r348 (beta)
Browser: Chrome 114.0.5735.199
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 224 gb
Storage usage (approx): 157 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4600 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
