### ISSUE TITLE
Unable to detect if URL audio is playing

### ISSUE THREAD

**Issue by qimuyicai** [Scirra/Construct-bugs#7183]
## Problem description

The URL audio plays successfully and the Debug layout shows that the URL audio is playing, but the Action triggered by "is tag playing" does not take effect.

## Attach a .c3p

[Unable to detect sound.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11994074/Unable.to.detect.sound.c3p.zip)

## Steps to reproduce

1.Open project
2.Run project by debug layout
3.Click filechooser
4.Choose music in the ZIP or choose your favorite music
5. Music is playing and debug layout also shows that music is playing
6. Text has not changed

## Observed result

Music is playing, but the action triggered by "is tag playing" does not take effect.

## Expected result

Music is playing, the action triggered by "is tag playing" take effect.

## More details

**Affected browsers/platforms:** 

 Chrome, Safari

**First affected release:** 
Just used URL audio today
Before that I only used Video to play audio without any problems.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@qimuyicai This is a bug in your events. When you created the `Play` action, you didn't specify a tag. Instead, you mistakenly refer to the audio file name in the sixth condition. Here is an example of correct operation.

[New project.zip](https://github.com/Scirra/Construct-bugs/files/11994691/New.project.zip)

**Comment by qimuyicai** [comment]
@WilsonPercival Thank you so much. I can't believe I didn't realize that. Hahaha. Feel like I'm a dumbass.
