### ISSUE TITLE
Pick by UID works with newly instance with child, pick all doesn't

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7184]
## Problem description

My problem is probably something of a very old bug in Construct. I would really like to know and to understand why it happens like this, since I run into a lot of these issues.

This is the code (I attached a c3p too) and it works:

<img width="997" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/aefceabf-212f-478a-8cd2-2759a7fc8018">

But the moment I comment the pick by UID and leave it as is, or replace it with Pick all, it stops working:

<img width="1029" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/9f52a975-98d4-44e3-a6e9-37a3730657d1">

https://github.com/Scirra/Construct-bugs/assets/7268697/c82a9aaf-1c86-4c92-9974-9fd75f4991c9

## Attach a .c3p

[Pick by UID works, without it doesnt.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11995147/Pick.by.UID.works.without.it.doesnt.c3p.zip)

## Steps to reproduce

1. Run the project
2. Toggle the line Pick instance by UID disabled and enabled as shown above

Other people tried it and had the same results.

## Observed result

Notice when the pick instance by disabled, even though the child gets created, it cannot be picked.

## Expected result

I'd expect to be able to pick the child without trying to pick it by UID.

## More details

**Affected browsers/platforms:** Chrome on mac

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by JeFawk** [comment]
This is inconsistent, as children are automatically picked after a hierarchy creation.

This works:
<img width="1042" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/c6d0d9de-c488-4d16-be95-5afa81249d5b">

But this does not:
<img width="1035" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/8b8a8dd6-21a8-4fef-9e78-10e5976a5fd1">

Thank you @FedericoCalchera for pointing this out

**Comment by WilsonPercival** [comment]
@JeFawk Basically it's the same as here: https://github.com/Scirra/Construct-bugs/issues/5434

To get around this, you can check the `Copy picked` checkbox.

**Comment by JeFawk** [comment]
> @JeFawk Basically it's the same as here: #5434
> 
> To get around this, you can check the `Copy picked` checkbox.

Might be related but I don't think it's the same, as in my example it's related to how the function works (or doesn't)

**Comment by WilsonPercival** [comment]
@JeFawk When you call the function here, it starts with a new instance list (SOL).

![aa](https://github.com/Scirra/Construct-bugs/assets/91274932/9b89f975-c9df-4160-a519-b06f00e6f641)

**Comment by JeFawk** [comment]
> @JeFawk When you call the function here, it starts with a new instance list (SOL).
> 
> ![aa](https://user-images.githubusercontent.com/91274932/252147453-9b89f975-c9df-4160-a519-b06f00e6f641.png)

Yes but what about the initial issue, not my comments afterwards:

https://github.com/Scirra/Construct-bugs/issues/7184#issuecomment-1627713000

?

Pick by UID works, pick all does not. Why is the child fully created when used Pick by UID and not fully created when used Pick all?

**Comment by WilsonPercival** [comment]
> > @JeFawk When you call the function here, it starts with a new instance list (SOL).
> > ![aa](https://user-images.githubusercontent.com/91274932/252147453-9b89f975-c9df-4160-a519-b06f00e6f641.png)
> 
> Yes but what about the initial issue, not my comments afterwards:
> 
> [#7184 (comment)](https://github.com/Scirra/Construct-bugs/issues/7184#issuecomment-1627713000)
> 
> ?
> 
> Pick by UID works, pick all does not. Why is the child fully created when used Pick by UID and not fully created when used Pick all?

@JeFawk Because in the case where you pass `UID` directly, you are referring directly to the instance, ignoring SOL.

**Comment by JeFawk** [comment]
> > > @JeFawk When you call the function here, it starts with a new instance list (SOL).
> > > ![aa](https://user-images.githubusercontent.com/91274932/252147453-9b89f975-c9df-4160-a519-b06f00e6f641.png)
> > 
> > 
> > Yes but what about the initial issue, not my comments afterwards:
> > [#7184 (comment)](https://github.com/Scirra/Construct-bugs/issues/7184#issuecomment-1627713000)
> > ?
> > Pick by UID works, pick all does not. Why is the child fully created when used Pick by UID and not fully created when used Pick all?
> 
> @JeFawk Because in the case where you pass `UID` directly, you are referring directly to the instance, ignoring SOL.

So if I understand correctly, the SOL is created later (at the end of the event sheet for example), while the object is created on the spot, and that is why the Pick by UID works, and the Pick from SOL does not?

**Comment by WilsonPercival** [comment]
> > > > @JeFawk When you call the function here, it starts with a new instance list (SOL).
> > > > ![aa](https://user-images.githubusercontent.com/91274932/252147453-9b89f975-c9df-4160-a519-b06f00e6f641.png)
> > > 
> > > 
> > > Yes but what about the initial issue, not my comments afterwards:
> > > [#7184 (comment)](https://github.com/Scirra/Construct-bugs/issues/7184#issuecomment-1627713000)
> > > ?
> > > Pick by UID works, pick all does not. Why is the child fully created when used Pick by UID and not fully created when used Pick all?
> > 
> > 
> > @JeFawk Because in the case where you pass `UID` directly, you are referring directly to the instance, ignoring SOL.
> 
> So if I understand correctly, the SOL is created later (at the end of the event sheet for example), while the object is created on the spot, and that is why the Pick by UID works, and the Pick from SOL does not?

@JeFawk Not really. The object is created normally. The only problem is that SOL will not have a newly created instance.

**Comment by JeFawk** [comment]
> 

Aha, so the SOL will _sometimes_ add the object at the end of the event sheet (or after wait 0, which waits until the end)
Meanwhile the object is created right then and can be used with Pick by UID, but nothing else?

Sorry if I'm not understanding fully yet.

**Comment by JeFawk** [comment]
> > > > > @JeFawk When you call the function here, it starts with a new instance list (SOL).
> > > > > ![aa](https://user-images.githubusercontent.com/91274932/252147453-9b89f975-c9df-4160-a519-b06f00e6f641.png)
> > > > 
> > > > 
> > > > Yes but what about the initial issue, not my comments afterwards:
> > > > [#7184 (comment)](https://github.com/Scirra/Construct-bugs/issues/7184#issuecomment-1627713000)
> > > > ?
> > > > Pick by UID works, pick all does not. Why is the child fully created when used Pick by UID and not fully created when used Pick all?
> > > 
> > > 
> > > @JeFawk Because in the case where you pass `UID` directly, you are referring directly to the instance, ignoring SOL.
> > 
> > 
> > So if I understand correctly, the SOL is created later (at the end of the event sheet for example), while the object is created on the spot, and that is why the Pick by UID works, and the Pick from SOL does not?
> 
> @JeFawk Not really. The object is created normally. The only problem is that SOL will not have a newly created instance.

Aha, so the SOL will sometimes add the object at the end of the event sheet (or after wait 0, which waits until the end)
Meanwhile the object is created right then and can be used with Pick by UID, but nothing else?

Sorry if I'm not understanding fully yet.

**Comment by WilsonPercival** [comment]
> > > > > > @JeFawk When you call the function here, it starts with a new instance list (SOL).
> > > > > > ![aa](https://user-images.githubusercontent.com/91274932/252147453-9b89f975-c9df-4160-a519-b06f00e6f641.png)
> > > > > 
> > > > > 
> > > > > Yes but what about the initial issue, not my comments afterwards:
> > > > > [#7184 (comment)](https://github.com/Scirra/Construct-bugs/issues/7184#issuecomment-1627713000)
> > > > > ?
> > > > > Pick by UID works, pick all does not. Why is the child fully created when used Pick by UID and not fully created when used Pick all?
> > > > 
> > > > 
> > > > @JeFawk Because in the case where you pass `UID` directly, you are referring directly to the instance, ignoring SOL.
> > > 
> > > 
> > > So if I understand correctly, the SOL is created later (at the end of the event sheet for example), while the object is created on the spot, and that is why the Pick by UID works, and the Pick from SOL does not?
> > 
> > 
> > @JeFawk Not really. The object is created normally. The only problem is that SOL will not have a newly created instance.
> 
> Aha, so the SOL will sometimes add the object at the end of the event sheet (or after wait 0, which waits until the end) Meanwhile the object is created right then and can be used with Pick by UID, but nothing else?
> 
> Sorry if I'm not understanding fully yet.

@JeFawk Not at the end of the event list. Here is another working example:

![bb](https://github.com/Scirra/Construct-bugs/assets/91274932/9c9cde00-f631-48e8-90c0-7667c9c7c95f)

**Comment by AshleyScirra** [comment]
This is just another variant of the long-standing issue that newly created instances aren't fully created until the end of the next top-level event. The event that created the instance has it picked for itself and all its sub-events, but other events can't pick it until the next top-level event, which includes functions.

The event engine implements some special exceptions for this, one of which is the 'Pick by UID' condition. So that lets you work around it. But in other circumstances it won't work.

I think it should be easy to work around though - if you are creating and initialising some instances, do it all in the same event, or do it in 'On created' triggers.

**Comment by JeFawk** [comment]
> 

Thank you for the explanation.
