### ISSUE TITLE
Tween behavior enabled and not doing anything uses a lot of CPU

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7185]
## Problem description

The Tween behaviour is using a lot of CPU while not doing anything. In my test, using 3500 objects, just having the behaviour enabled it was using 10% cpu, while disabled, 2%, on my MacBook Air M1, which is pretty powerful compared to the majority of laptops used to run web games, which are Chromebooks.

As @F3der1co (FedericoCalchera) pointed out, with the timer behaviour there is no noticeable CPU usage when idle.

This is a big issue (for me at least) since Tween is so versatile, it manages to replace a lot of behaviours while being very clean to use. Micromanaging to enable and disable it for objects that on that moment don't need it is something that would be a huge drawback.

This is with Tween disabled:
<img width="1571" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/0ce31cd6-10e6-4484-ba8b-8361140ef117">
This is Tween enabled and no tween coded:
<img width="1570" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/d51b4dd8-f035-46ea-9568-f423c40c96b9">

## Attach a .c3p

[SineVsTween.c3p.zip](https://github.com/Scirra/Construct-bugs/files/11995332/SineVsTween.c3p.zip)

## Steps to reproduce

1. open the project
2. toggle the Tween enabled property of the Sprite
3. run it
<img width="305" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/a83289eb-6424-4100-a737-de2d3e3185df">

## Observed result

Notice the huge CPU difference even though no Tween is coded.

## Expected result

Expected way less CPU usage for nothing basically happening than C3 doing some checks I assume.

## More details

**Affected browsers/platforms:** Chrome on mac

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r344.2 (stable)
Browser: Chrome 114.0.5735.198
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 210 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment]
This is a great find! 
tween is a behavior that I add to basically any object that is not static in my games, so in my projects it is realistic to have hundreds and even thousands of objects with the tween behavior. 
Another behavior I add to almost all objects is the timer behavior, but this one doesn't seem to have a idle cost. And from my naive understanding they should be working similarly (running timers with tags, just with the tween having some additional complexity how it interprets the timer into the tween progress including eases) This is probably an oversimplification and there might be a reason to have a higher idle cost.
Because I use the tween behavior so much, idle performance improvements would be a benefit for almost all my projects, so I hope this can be improved.

**Comment by AshleyScirra** [comment]
@DiegoScirra - it looks like this is because an enabled Tween behavior is still ticking. It should stop ticking if it is not running any tween.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
