### ISSUE TITLE
Editor resetting width of condition and action blocks

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7187]
## Problem description

Tested with r344.2 and r348 and it's still happening.

## Attach a .c3p

Almost blank project
[New project (1).c3p.zip](https://github.com/Scirra/Construct-bugs/files/12003547/New.project.1.c3p.zip)

## Steps to reproduce

https://github.com/Scirra/Construct-bugs/assets/7268697/ce392168-98bf-4554-ac52-806ccc5e879e

1. open new project, write a random condition
2. edit the width as shown in the video
3. close the event sheet
4. open the event sheet again

## Observed result

The width gets reset to min

## More details

**Affected browsers/platforms:** Chrome on mac Version 114.0.5735.198 (Official Build) (arm64)

**First affected release:** since r 344.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r348 (beta)
Browser: Chrome 114.0.5735.198
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 214 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
Yes, it works well for me too.

**Comment by JeFawk** [comment]
Removed everything from Dev Tools -> Application while on editor.construct, restarted the tab, and it's working properly now.

**Comment by JeFawk** [comment]
I have started encountering the problem again and with sheer dumb luck I managed to figure out it was the panel docked on the bottom as this video shows:
https://github.com/Scirra/Construct-bugs/assets/7268697/bd933a14-a950-46e0-b154-049cba4eada8

The console has some errors, are any relevant maybe?
![image](https://github.com/Scirra/Construct-bugs/assets/7268697/a365860f-9b2f-489a-a93d-4147ecbfd539)

**Comment by JeFawk** [comment]
https://github.com/Scirra/Construct-bugs/assets/7268697/09cd4615-5a36-40a2-8900-7b3737a6ac2d

**Comment by WilsonPercival** [comment]
@JeFawk Yes, I can repeat too if I pin the search bar to the bottom.

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
