### ISSUE TITLE
Tag text bug?

### ISSUE THREAD

**Issue by JonaszO** [Scirra/Construct-bugs#7190]
reproduced steps here
https://youtu.be/gU5PxuZpAtM

also i try
When cursor is over this text object
and when Left click on text object

nothing work for me, should work as i recoirded

**Comment by WilsonPercival** [comment]
@JonaszO Attach the project file and write the steps to reproduce the problem otherwise your report will be closed because you are ignoring the recommendations for reporting.

**Comment by JonaszO** [comment]
> @JonaszO Attach the project file and write the steps to reproduce the problem otherwise your report will be closed because you are ignoring the recommendations for reporting.

sorry for ignoring recomendations, i dont have time for uploading big files and for describing step by step, i do what can do to report something weird and recording screen is for me best way.

**Comment by WilsonPercival** [comment]
> > @JonaszO Attach the project file and write the steps to reproduce the problem otherwise your report will be closed because you are ignoring the recommendations for reporting.
> 
> sorry for ignoring recomendations, i dont have time for uploading big files and for describing step by step, i do what can do to report something weird and recording screen is for me best way.

@JonaszO You don't need to upload a big project, because a minimal project with a problem is needed. You say that you do not have time to publish a normal report, but in fact you are just wasting your time, because. the error will not be corrected. The video is not sufficient to verify that there is a problem.

**Comment by F3der1co** [comment]
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/902d8035-a7ab-4951-93b4-c5fcb68968fc)
there is a reason more information is needed...

**Comment by F3der1co** [comment]
you could use has tag "tag" at mouse.x(text.layerNumber) mouse.y(text.layerNumber)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise your report will not be investigated. For general questions about using Construct please post to the forum instead.
