### ISSUE TITLE
Docking / Closing panels resets the scrolling in the event sheet

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7191]
## Problem description

The problem is that on laptop screens (using 13" screen) every pixel counts. As so, I try to dock the Find all references panel, and to close it when i'm done.
Docking it and closing it resets the event sheet scroll all the way to the top, and this makes it pretty annoying on big event sheets since now I need to also keep in mind the event number I'm at before docking/closing the panel.

I noticed the same happens to the Properties bar panel if docked on the bottom and closed. It probably happens with more panels.

## Attach a .c3p

https://github.com/Scirra/Construct-bugs/assets/7268697/f380fd46-9e1b-45c0-a567-53660d0221f3

The project from the video
[New project.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12014441/New.project.c3p.zip)

## Steps to reproduce

1. Scroll down to the middle of the event sheet
2. Open find all references as shown in the video on the Sprite
3. Dock the panel
4. notice it reset the scroll
5. scroll down again
6. close the panel
7. notice it reset the scroll

## Expected result

I expect the scroll to not be reset, and to have somewhat the center of what I'm looking at with panel docked, still rather in the center after panel is closed. Same with docking it, to have the center of what I'm looking at still be in the center.

## More details

**Affected browsers/platforms:** Chrome mac

**First affected release:** bugged like this for as long as I can remember

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r349 (beta)
Browser: Chrome 114.0.5735.198
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 47 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
