### ISSUE TITLE
8 direction, framerate dependent deceleration

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7194]
## Problem description
the 8 direction behavior seems to have some inconsistencies with regards to how it calculates deceleration. Simulating an input behaves differently from setting a vector (acceleration is not the reason).
This inconsistency goes away (gets smaller) in unlimited framerate mode, hence I assume this is a framerate dependency issue

## Attach a .c3p
[8dirDecel.zip](https://github.com/Scirra/Construct-bugs/files/12021684/8dirDecel.zip)

## Steps to reproduce

1. preview the project
2. black sprite is faster

optional:
3. set to unlimited framerate mode
4. preview
5. they have about the same speed
## Observed result
they have inconsistent speed 

## Expected result
both sprites have the same speed, regardless of framerate (speed in regards to how fast they move across the screen, not the value)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
I did the same test with the platform behavior, there this issue doesn't exist.

**Comment by F3der1co** [comment]
https://github.com/Scirra/Construct-bugs/issues/2754
I just found this report, but I would argue that this is still an issue. Because this means that setting vectors can lead to framerate dependent inconsistencies.

**Comment by F3der1co** [comment]
I filed this bug report because I was helping another c3 user on discord that was struggling with this. They were able to fix the issue by setting deceleration to 0. So I guess at least for them it's not that important.

Personally I am still pro changes like these as they lead to more robustness in the long run even if the change can be a bit painful.

But for me personally I have no need for this in my current project as I am using the platform behavior (I appreciate the changes to that even tho it also broke some minor stuff for me, but was easy enough to work around)

**Comment by AshleyScirra** [comment]
I think given that I'll close this as wontfix. However if it comes up again separately we may take another look.
