### ISSUE TITLE
Greenworks Achievements broken

### ISSUE THREAD

**Issue by TmesisStudio** [Scirra/Construct-bugs#7195]
Hello there!

I actually have a problem regarding Greenworks Achievements. They simply aren't recognized by Steam so it doesn't unlock them in Steam account.
In the past (for another game) I actually manage to unlock achievements, I know how to set up all the stuff. I followed the entirety of the guides available on the WorldWideWeb, but this time it doesn't work.

I exported a NW.js build for Win64 using the latest r350 version of C3, 0.71 version of Greenworks plugin (the latest stable) and 0.1.5.0 of Steam Sdk files as suggested from the Plugin page. "Export for Steam" checked. 
[Here](https://i.ibb.co/dD47bbb/Screenshot-2023-07-13-at-20-39-13.png) you can find an image of the problem that console log point out.

[Here](https://we.tl/t-pTVPBMEvrl) you can find a minimal project for testing the bug.

## Steps to reproduce:

There are two possibilities:

**Comment by AshleyScirra** [comment]
Please only use the latest supported version of Construct (we won't support issues that occur in r327.3 as it is an old release now), and provide a minimal project demonstrating the issue, as per the bug report guidelines.

**Comment by JeFawk** [comment]
> Hello there!
> 
> I actually have a problem regarding Greenworks Achievements. They simply aren't recognized by Steam so it doesn't unlock them in Steam account.
> 
> In the past (for another game) I actually manage to unlock achievements, I know how to set up all the stuff. I followed the entirety of the guides available on the WorldWideWeb, but this time it doesn't work.
> 
> I exported a NW.js build for Win64 using the r327.3 version of C3 (but tried the latest r344.2 build too), 0.71 version of Greenworks plugin (the latest stable) and 0.1.5.0 of Steam Sdk files as suggested from the Plugin page. "Export for Steam" checked. The Steam overlay doesn't give me any problem, so it's just about the achievements that are not working.
> 
> I could privately give a key to someone to test it but maybe Scirra Devs have a project to test if achievement are working or not. Just to understand if it's a problem of mine or a Construct bug.
> 
> If there's any kind of workaround, please tell me.
> 
> [Here's the link ](https://we.tl/t-JIKGEUcoey) to a .c3p project but I don't think it could be useful since you can verify it just by be logged on Steam.
> 
> ## Observed result: Achievements are not unlocking.
> ## Expected result: Achievements must unlock.
> View details

Are you aware you posted your whole project publicly?

**Comment by TmesisStudio** [comment]
> Please only use the latest supported version of Construct (we won't support issues that occur in r327.3 as it is an old release now), and provide a minimal project demonstrating the issue, as per the bug report guidelines.

I edited the original post with what you're requested!

**Comment by AshleyScirra** [comment]
Using Google Translate, the logged error appears to be "The specified procedure could not be found."

I think this is usually caused by a misconfiguration of your export. Are you sure you exported matching all the versions as noted in the [Greenworks documentation](https://www.construct.net/en/make-games/addons/84/greenworks/versions)? i.e. Greenworks 0.71 must be used only with NW.js 0.71, and cannot be used with any other version.

**Comment by TmesisStudio** [comment]
> Using Google Translate, the logged error appears to be "The specified procedure could not be found."
> 
> I think this is usually caused by a misconfiguration of your export. Are you sure you exported matching all the versions as noted in the [Greenworks documentation](https://www.construct.net/en/make-games/addons/84/greenworks/versions)? i.e. Greenworks 0.71 must be used only with NW.js 0.71, and cannot be used with any other version. For example if you exported with the latest NW.js version (0.77.0), it won't work.

Hi! I confirm I'm following the right procedure. In fact, if I create a brand new project it works perfectly fine.
But the file project I send you is the one that was not working, just cleaned from the useless rules and stuff. So it look like it's broken in a way which is outside my control. 
The problem is that this project is my entire year of work and I can't re-do all the stuff from 0. 
Launch date of the game is not that far.
So I have to understand why That project is broken from the inside. Is there a way to check the Js scripts behind the block interface?

**Comment by TmesisStudio** [comment]
Hello!

You can set the bug to close as I solved the issue by simply destroy from the project (and the editor too) the Greenworks plugin, re-download it from the store and then re-import inside the project.
Now everything works fine. 

Thank you for your effort and have a nice day Ash!
