### ISSUE TITLE
HTML Element position bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7200]
## Problem description

The content of the `HTML Element` does not want to go beyond the gray area.

## Attach a .c3p

[html_element_position_bug_r350s.zip](https://github.com/WilsonPercival/WilsonPercival/files/12049775/html_element_position_bug_r350s.zip)

## Steps to reproduce

1. Open and run the project.
2. Move the cursor to the left side of the screen so that it is on the black bar.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/56ea0e28-c37e-4974-b505-89c3a4a75c59

## Expected result

It works well when I move it to the right.

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/6f57a86e-0631-4024-bc35-764ed1af35f9

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r350s

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 109.0.5414.120
Browser engine: Chromium
Context: browser
Operating system: Windows NT 0.1.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 59 gb
Storage usage (approx): 369 mb (0.6%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL indicates a major performance caveat. It is probably using software rendering.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
OVR_multiview2
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Gryphonn** [comment]
@AshleyScirra @DiegoScirra,
in regard to this and one of the previous bugs ([HTMLElement set position bug #5836](https://github.com/Scirra/Construct-bugs/issues/5836)) 

You stated:
_This is a long standing issue affecting any HTML elements moving relative to the canvas. The browser draws them at different times, so they do not always move together at exactly the same time. Unfortunately **I don't think it's possible** to do anything about it._

But I seemed to solve both of these problems (shrinking and delay) by the means of C3. So at least it's not impossible.
Please take a look at the video demonstration and the attached project.

Is it possible to make this behaviour by default? So they move together simultaneously? 
If not is there any obstacle to implement this mechanism internally?


https://github.com/Scirra/Construct-bugs/assets/21972383/cac7adbf-b628-4283-8187-b45c26f6d025
[htmlHierarchy2.zip](https://github.com/Scirra/Construct-bugs/files/12063795/htmlHierarchy2.zip)

**Comment by Gryphonn** [comment]
https://github.com/Scirra/Construct-bugs/assets/21972383/6999f929-0ebc-4503-9d53-11ae1dcaa312

**Comment by AshleyScirra** [comment]
It's currently by design that HTML elements are clipped to the canvas area, to match how other objects render.

@Gryphonn - I don't believe your comment is applicable to this issue.

**Comment by Gryphonn** [comment]
@AshleyScirra 
`to match how other objects render.`

The thing is they do NOT match other objects. What other objects change the width and the height when crossing the edge??

I'd suggest having an option how an HTML element should behave when moved out of the canvas.
1. Shrinking (now by default)
2. Moving freely out of the canvas (no shrinking)
3. Moving out of the canvas then disappearing after passing the edge.
4. Disappearing when touching the edge.

Option 1 looks really bad. I don't see how it can be used in a more or less serious game/app. Options 2-4 are significantly more appealing.

**Comment by Gryphonn** [comment]
@AshleyScirra 
Option 5. Html elements actually match other objects.
Accomplished by 4 html elements outside the canvas.

https://github.com/Scirra/Construct-bugs/assets/21972383/ba29ba62-2d92-4542-9033-5505f5becf58

**Comment by Dime11** [comment]
This have been a problem for me for a while, and this really solves it. But how do I use this on multiple instances of the same object? If I copy the html object, it only affects one.

**Comment by Gryphonn** [comment]
> This have been a problem for me for a while, and this really solves it. But how do I use this on multiple instances of the same object? If I copy the html object, it only affects one.

You need to do several things.
1. Add iHtml as a child to a sprite. (destroyWithParent only)
2. Set .transformX or .transformY to true.
3. Set .transformDx or .transformDy
4. Set .htmlD to the ID of the html element.

Enjoy. Here's a demo.

[htmlHierarchyPro.zip](https://github.com/Scirra/Construct-bugs/files/12825272/htmlHierarchyPro.zip)
