### ISSUE TITLE
Reordering bool parameters in a function or action corrupts folder-based projects

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-bugs#7205]
## Problem description

If you reorder a bool parameter and other types of parameters (i.e., a bool param plus a string or number param) of a custom action or function, and that function is called from a different event sheet, and the project is saved as a folder-based project, the project becomes corrupted and can't be opened again.

Unzip the attached project into a folder, open it in C3, reorder the parameters in either the custom action or the function in event sheet 1, save, close the project and attempt to reopen it - the project will fail to open. Doesn't seem to be an issue when the project is saved as a .c3p.

## Attach a .c3p
[DoomedProject.zip](https://github.com/Scirra/Construct-bugs/files/12060788/DoomedProject.zip)

## Steps to reproduce

1. Create a new project, and add a function to it.
2. Add a bool parameter to the function.
3. Add either a string or number parameter to the function.
4. Add a second event sheet to the project.
5. Add an event on the second event sheet that calls the function.
6. Save the project as a folder-based project. At this point you can close and reopen the project successfully.
7. Reorder the two parameters in the function and save the project.
8. Close the project, and attempt to reopen it.

## Observed result

The project fails to open.

## Expected result

The project should open.

## More details

**Affected browsers/platforms:** 

Only tested on release r350 stable, Microsoft Store version.

**First affected release:** 

Only tested on release r350 stable, Microsoft Store version.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Edge 114.0.1823.82
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 119 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: nvidia
Adapter architecture: ampere
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features:

bgra8unorm-storage
depth-clip-control
depth32float-stencil8
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Should be fixed in the next beta.
