### ISSUE TITLE
iOS mobile export

### ISSUE THREAD

**Issue by listpull** [Scirra/Construct-bugs#7210]
## Problem description
iOS exports with google services will not export

## Steps to reproduce

1. Export iOS game with Google Ads
2.
3.

## Expected result
Error: Platform 'ios' found in config.xml... Migrating it to package.json
Discovered platform "ios". Adding it to the project
Using cordova-fetch for cordova-ios@6.3.0
Adding ios project...
Creating Cordova project for the iOS platform:
Path: ~~/ios
Package: com.listpull.numbermerge
Name: ListPull
iOS project created with cordova-ios@6.3.0
Plugin 'admob-plus-cordova' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-consent' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-device' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-idfa' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-nativestorage' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-export2' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-purchase' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-inappbrowser' found in config.xml... Migrating it to package.json
Plugin 'cordova-launch-review' found in config.xml... Migrating it to package.json
Plugin 'construct-mobile-rate2' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-firebase-analytics' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-vibration' found in config.xml... Migrating it to package.json
Plugin 'cordova-plugin-statusbar' found in config.xml... Migrating it to package.json
Discovered plugin "admob-plus-cordova". Adding it to the project
Installing "admob-plus-cordova" for ios
Discovered plugin "cordova-plugin-consent". Adding it to the project
Installing "cordova-plugin-consent" for ios
Discovered plugin "cordova-plugin-device". Adding it to the project
Installing "cordova-plugin-device" for ios
Discovered plugin "cordova-plugin-idfa". Adding it to the project
Installing "cordova-plugin-idfa" for ios
Discovered plugin "cordova-plugin-nativestorage". Adding it to the project
Installing "cordova-plugin-nativestorage" for ios
Discovered plugin "construct-mobile-export2". Adding it to the project
Installing "construct-mobile-export2" for ios
Discovered plugin "cordova-plugin-purchase". Adding it to the project
Installing "cordova-plugin-purchase" for ios
Discovered plugin "cordova-plugin-inappbrowser". Adding it to the project
Installing "cordova-plugin-inappbrowser" for ios
Discovered plugin "cordova-launch-review". Adding it to the project
Installing "cordova-launch-review" for ios
Plugin dependency "cordova-plugin-device@2.0.3" already fetched, using that version.
Dependent plugin "cordova-plugin-device" already installed on ios.
Discovered plugin "construct-mobile-rate2". Adding it to the project
Installing "construct-mobile-rate2" for ios
Discovered plugin "cordova-plugin-firebase-analytics". Adding it to the project
Installing "cordova-plugin-firebase-analytics" for ios
Discovered plugin "cordova-plugin-vibration". Adding it to the project
Installing "cordova-plugin-vibration" for ios
Discovered plugin "cordova-plugin-statusbar". Adding it to the project
Installing "cordova-plugin-statusbar" for ios
Running in: linux
Setting swift version
Running manual pod update
Pod update failed
Update all pods
Updating local specs repositories

CocoaPods 1.12.1 is available.
To update use: `sudo gem install cocoapods`

For more information, see https:/~~/blog.cocoapods.org and the CHANGELOG for this version at https:/~~/1.12.1

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "GoogleAppMeasurement":
In Podfile:
~~/Analytics (= 9.3.0) was resolved to 9.3.0, which depends on
~~/Core (= 9.3.0) was resolved to 9.3.0, which depends on
FirebaseAnalytics (~> 9.3.0) was resolved to 9.3.0, which depends on
~~/AdIdSupport (= 9.3.0) was resolved to 9.3.0, which depends on
GoogleAppMeasurement (= 9.3.0)

Google-Mobile-Ads-SDK (~> 8.13.0) was resolved to 8.13.0, which depends on
GoogleAppMeasurement (< 9.0, >= 7.0)

CordovaError: Promise rejected with non-error: undefined
at ~~/cordova:30:15
at process.processTicksAndRejections (node:~~/task_queues:95:5)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
