### ISSUE TITLE
Arabic Text RTL Issue

### ISSUE THREAD

**Issue by KhaledFelfal** [Scirra/Construct-bugs#7213]
## Problem description

Some characters display in the wrong direction when writing in Arabic. This includes but not limited to: Fullstops ( . ) and Examination marks (!)

## Attach a .c3p

https://drive.google.com/file/d/1LB0ADmk4IGGNUz-9GEZgn5L1KYN7XjfH/view?usp=sharing

## Steps to reproduce

1. Add a text object
2. Change Text to anything Arabic with some punctuations. 
3. Example ( انت رائع. )

## Observed result

The punctuation mark appears on the right of the text (before the text) not after it. See: 
![image](https://github.com/Scirra/Construct-bugs/assets/62517244/934bd208-1b99-470b-9af0-b2b9853bc930)

## Expected result

The punctuation mark appears after the text, on the left. Since the language is a RTL.

## More details

The work around is to use a special invisible character to fix this called [RLM - Right-to-Left Mark] with Unicode (U+200F)
Please check: https://dotancohen.com/howto/rtl_right_to_left.html

**Affected browsers/platforms:** 

All.

**First affected release:** 
R350

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Edge 114.0.1823.82
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.82
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 182 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The Text object in the layout appears to draw the text the same way as the dialog when editing the text, which is rendered by the browser. So as far as I can see Construct's Text object matches the browser so it seems to be correct for me. But I have my system set to a left-to-right language mode, so perhaps that's the issue.

Despite that, this is a very complicated technical problem for us: for the Text object we have to write and maintain our own text layout engine, and it is exceptionally complicated even without the ability to change the text direction. There's all sorts of possible cases including RTL text, vertical writing modes, and different runs of different text directions embedded in others. I don't think it's really feasible for us to cover it all with our own text layout engine. If you need more advanced text support, you can either use special unicode characters as you noted, or my advice would be to use the HTML Element object to display text, where you can take full advantage of the comprehensive layout engine the browser provides.
