### ISSUE TITLE
"On Touch" is not registering correctly on mobile devices when under heavy load.

### ISSUE THREAD

**Issue by FhenrisGit** [Scirra/Construct-bugs#7217]
## Problem description

"On Touch" actions may not register correctly or may be skipped when under heavy load and another "Is Touching object" is actively triggered

## Attach a .c3p

[On Touch Register Issue.zip](https://github.com/Scirra/Construct-bugs/files/12062468/On.Touch.Register.Issue.zip)

## Steps to reproduce

1. Preview this project remotely on a mobile phone, wait a few seconds for the pathfinding to put your phone under load (but close the project quickly after your tests to avoid putting too much load on your phone).
2. Test "On Touch" actions by touching the left or right side of the screen; blue and red colors should appear when you touch the screen.
3. Now, keep the left side touched and tap the right side; it should still work.
4. Finally, start making circles with your left finger on the blue/left side. While making uninterrupted circles, try tapping the right/red part of the screen. You should see that it doesn't register "On Touched Object" correctly.
5. You can try disabling the pathfinding part of the code and start again from step 1; everything works somewhat normally.

## Observed result

On mobile, under heavy load, "On Touch" actions are not registered correctly if another "Is Touching" action is activated.

## Expected result

On Touch actions should still register, even if they take a bit of time as FPS goes down

## More details

Don't have much more details, C3D project is self explanatory

## System details

Tested on iPhone 12 and iPad Air 2020

**Comment by FhenrisGit** [comment]
Good to notice that it's not just a "things break when CPU is under heavy load" bug. I stress tested it for exageration and demo purpose. This issue occurres on normal conditions but more rarely. I consider it as severe because it prevents me from managing dual D-Pad on a mobile game I’m working on.
It’s just easier to test and debug when it’s more obvious, that's what the pathfinding spam is for, to put a bit of load and make the bug more obvious on testing.

**Comment by WilsonPercival** [comment]
@FhenrisGit Can't repeat. Each click on the right side of the screen is registered.

I modified your project a little. Instead of displaying blue and red sprites, I created a counter. Every time I clicked on the right side of the screen, I added 1 to the counter. Thus, I saw that each click was registered. I did this because I'm guessing that because of the low FPS, sometimes you can't see the red sprite because it won't have time to render or something.

**Comment by FhenrisGit** [comment]
> @FhenrisGit Can't repeat. Each click on the right side of the screen is registered.
> 
> I modified your project a little. Instead of displaying blue and red sprites, I created a counter. Every time I clicked on the right side of the screen, I added 1 to the counter. Thus, I saw that each click was registered. I did this because I'm guessing that because of the low FPS, sometimes you can't see the red sprite because it won't have time to render or something.

Thanks for your test. This is strange. Are you sure you completed step 4 correctly? The non-stop swipe action is important for the bug to occur. In fact, in my project, it wasn't related to display issues. I created this test project with only blue and red to make it visually clearer. However, in my project, when I correctly follow the 4th step, it sometimes doesn't register a simple "Set GLOBAL number to Touch.TouchID."

**Comment by FhenrisGit** [comment]
https://github.com/Scirra/Construct-bugs/assets/139649040/d97583eb-21e9-444c-a19e-45fc7b781acc

**Comment by WilsonPercival** [comment]
> > @FhenrisGit Can't repeat. Each click on the right side of the screen is registered.
> > I modified your project a little. Instead of displaying blue and red sprites, I created a counter. Every time I clicked on the right side of the screen, I added 1 to the counter. Thus, I saw that each click was registered. I did this because I'm guessing that because of the low FPS, sometimes you can't see the red sprite because it won't have time to render or something.
> 
> Thanks for your test. This is strange. Are you sure you completed step 4 correctly? The non-stop swipe action is important for the bug to occur. In fact, in my project, it wasn't related to display issues. I created this test project with only blue and red to make it visually clearer. However, in my project, when I correctly follow the 4th step, it sometimes doesn't register a simple "Set GLOBAL number to Touch.TouchID."

@FhenrisGit Yes, I followed all the steps.

Try this project. When you click on the right side of the screen, the counter should increase.

[Pathfinding demo.zip](https://github.com/Scirra/Construct-bugs/files/12063913/Pathfinding.demo.zip)

**Comment by FhenrisGit** [comment]
> 

Nope, same bug with your test project. Again, you have to do infinite non-stop circles on the left just like in the video for it to occur.

**Comment by WilsonPercival** [comment]
> Nope, same bug with your test project. Again, you have to do infinite non-stop circles on the left just like in the video for it to occur.

@FhenrisGit Can you make another video of my project?

**Comment by FhenrisGit** [comment]
https://github.com/Scirra/Construct-bugs/assets/139649040/987fa88b-b1b7-44eb-b572-4facc5641ae0

I touched the right part of the screen 28 times, it registered only 11 times.

Again, this bug report might look dumb, and the way to reproduce it too. But it prevents me to manage dual D-Pad correctly. Again, it has nothing to do with multi-touch issues as I'm tracking touch.TouchID correctly with each event to separate actions from each touch. 

https://github.com/Scirra/Construct-bugs/assets/139649040/b33dbb65-9185-428c-ba78-8af9773ee724

**Comment by WilsonPercival** [comment]
> 2023-07-16.13-54-18.26A9c7b92.mp4 
> I touched the right part of the screen 28 times, it registered only 11 times.
> 
> Again, this bug report might look dumb, and the way to reproduce it too. But it prevents me to manage dual D-Pad correctly. Again, it has nothing to do with multi-touch issues as I'm tracking touch.TouchID correctly with each event to separate actions from each touch.
> 
>  2023-07-16.13-59-52.F380cf402.mp4

@FhenrisGit There is nothing more I can do to help.

**Comment by FhenrisGit** [comment]
> > 2023-07-16.13-54-18.26A9c7b92.mp4
> > I touched the right part of the screen 28 times, it registered only 11 times.
> > Again, this bug report might look dumb, and the way to reproduce it too. But it prevents me to manage dual D-Pad correctly. Again, it has nothing to do with multi-touch issues as I'm tracking touch.TouchID correctly with each event to separate actions from each touch.
> > 2023-07-16.13-59-52.F380cf402.mp4
> 
> @FhenrisGit There is nothing more I can do to help.

Thx for your test, have a great day :)
