### ISSUE TITLE
on timer is checked every tick

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7225]
## Problem description
on timer is checked every tick

## Attach a .c3p
[onTimerCheck.zip](https://github.com/Scirra/Construct-bugs/files/12065285/onTimerCheck.zip)

## Steps to reproduce

1. run in debug mode
2. see event group CPU cost

## Observed result
on timer costs performance every tick

## Expected result
no performance cost

## More details
The tween behavior seems to handle it differently and is a "true trigger", hence I put in that group to compare.
Going off of my previous bug report the timer check is already much cheaper than tween, so it's not as big of an issue, but if the tween behavior can do it like this it would be great if on timer would also be a "true trigger" to make that check much cheaper.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by OverboyDev** [comment]
If "On Timer" was a true trigger, wouldn't it also help so we don't need to put For Each to make sure it works for multiple instances finishing their timers on the same tick ?

**Comment by F3der1co** [comment]
1. is a good point, it kinda feels inconsistent with the rest of triggers. I guess this way the triggered event might be cheaper if many instances have a on timer at the same time, but as you often end up needing a for each this is worse again. So to me the current implementation of on timer seems worse all around than the tweens on tween finished. (higher overhead for on timer check, and requiring a for each a lot of times)
But maybe there is something I am missing that makes the current implementation favorable?

**Comment by AshleyScirra** [comment]
This is by design - internally "On timer" conditions are in fact tested every tick. However as per #7224. the performance difference is probably meaningless and issues like this are most likely a waste of time.

**Comment by F3der1co** [comment]
By design doesn't mean it's good, but I guess I will do this as a suggestion then

**Comment by F3der1co** [comment]
I don't want to repeat the same from #7224 

Here is a new example with a heavy load and wording it in a way that shows an example use case:
[onTimerC&C.zip](https://github.com/Scirra/Construct-bugs/files/12072927/onTimerC.C.zip)
