### ISSUE TITLE
Timer Behavior and System Every X seconds run much slower at higher frequencies

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7227]
## Problem description
I made a timer that runs every 0.001sec and noticed it runs much slower than it should be.

## Attach a .c3p
[timer.zip](https://github.com/Scirra/Construct-bugs/files/12069425/timer.zip)

## Steps to reproduce

1. Run

## Observed result

The timer that runs every 1/100 is almost half as fast as the 1 and 1/10 timers. The 1/1000 timer counts 1 every 16 seconds instead of 1.

## Expected result
Timers run at the exact time they are set for.

**Comment by WilsonPercival** [comment]
@Alaadel Is it just me or is there a bug in your project? You created two identical events 10 and 11. Is that how it should be?

<img width="540" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/04da618f-9676-4803-acf8-cccff49ecb5b">

**Comment by AshleyScirra** [comment]
Timers are only checked once per tick, and so won't run more often than "Every tick", which is most commonly at 60 FPS.

**Comment by Alaadel** [comment]
> Timers are only checked once per tick, and so won't run more often than "Every tick", which is most commonly at 60 FPS.

Then a "Every 0.001 seconds" condition is ambiguous, because it says 0.001 but then runs at a different value.

I thought the timer was a real timer (independent from the game fps), running in the background on its own at real time speed, then the engine reads its value once per frame. But at least every frame we get a value that has moved 0.001 seconds from the previous reading.
