### ISSUE TITLE
Internationalization: Compare to current locale 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7236]
## Problem description

I was confused about the way the order of 'Compare to current locale' condition parameters displayed.It is not designed uniformly with the order of other plugins.

## Attach a .c3p
[internationalization.conditions.compare-current-locale.text.zip](https://github.com/Scirra/Construct-bugs/files/12091658/internationalization.conditions.compare-current-locale.text.zip)

## Observed result

```
{0} {1} to current locale
```

![Snipaste_2023-07-19_14-23-57](https://github.com/Scirra/Construct-bugs/assets/45864744/a050be46-27f5-452a-859e-7f51d9cc7ea4)

## Expected result

```
current locale {0} {1}
```

![Snipaste_2023-07-19_14-21-46](https://github.com/Scirra/Construct-bugs/assets/45864744/2fb6d0eb-cfba-4dd9-9dcf-7f000ee783b8)

## More details

Observed 2:
![01](https://github.com/Scirra/Construct-bugs/assets/45864744/916788ee-0baf-4b81-b9bd-f07bd15ab87b)

Expected 2:
![Snipaste_2023-07-19_14-16-21](https://github.com/Scirra/Construct-bugs/assets/45864744/acc9001c-b016-46cd-ad31-e0d72b34ff7e)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
