### ISSUE TITLE
Construct 3 builds damaged APK (not installed on Android)

### ISSUE THREAD

**Issue by eSSy-90** [Scirra/Construct-bugs#7237]
## Problem description
Hello. I'm creating a signed apk release using Construct 3. But the APK file is broken and not installed. 

## Attach a .c3p
Project file: https://drive.google.com/file/d/1GZErzIHHLZlTWRer1aRORTrLDilhLekG/view?usp=drive_link

## Steps to reproduce

1. Open the project.
2. Export it for Cordova (Deduplicate images, Minify script - simple) for Android 8+ (Signed Release APK, only "Hide status bar" checkbox mark).
3. Try to install the APK file.

## Observed result

When I try to install the APK, the following happens.
BlueStacks says: Install parse failed.  Unexpected Exception.

Google Play Console says:
6:56 13151 13151] Zip: bad offsets (dir 61841673, size 41339, eocd 61817476)
error: failed opening zip: Invalid offset.

The Android device says: "APP not installed".
## Expected result

The compiled APK should install without errors.

## More details
If you delete the object types starting with "A-D", then the compiled APK will install successfully.
If you remove all sounds and music, then the compiled APK will install successfully too.
I purposely made a project without game code to narrow down the range of the bug.

**Affected browsers/platforms:** 
I used different browsers: Mozilla Firefox, Google Chrome. Also on another PC. The problem remains.

**First affected release:** 
This bug never appeared in 2022.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The project file is not public. Please provide a minimal repro project with a public link as per the bug report guidelines.

I'm not aware of any other users reporting problems, so at first glance my assumption would be that this is some kind of configuration problem with the app or the device/emulator in your specific case.

**Comment by eSSy-90** [comment]
> The project file is not public.
Sorry. I have shared the file. The link hasn't changed.

**Comment by eSSy-90** [comment]
Can anyone help me?

**Comment by WilsonPercival** [comment]
> Can anyone help me?

@eSSy-90 Today is a day off.

**Comment by eSSy-90** [comment]
7 days off in a row?

**Comment by WilsonPercival** [comment]
> 7 days off in a row?

@eSSy-90 https://www.construct.net/en/make-games/releases/beta/r351

<img width="565" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/916bc185-5afd-4299-9d0e-9006a6af75e1">

**Comment by eSSy-90** [comment]
> @eSSy-90 https://www.construct.net/en/make-games/releases/beta/r351

I just tried. It did not help. The error remains.

**Comment by WilsonPercival** [comment]
> > @eSSy-90 https://www.construct.net/en/make-games/releases/beta/r351
> 
> I just tried. It did not help. The error remains.

@eSSy-90 I didn't ask you to try. I just pointed out to you that 24-28th July are non-working days.

**Comment by eSSy-90** [comment]
> @eSSy-90 I didn't ask you to try. I just pointed out to you that 24-28th July are non-working days.
Ah. Ok.

**Comment by AshleyScirra** [comment]
The provided project uses a third-party addon "UnityAdsX". Please only submit issues where no third-party addons are used as per the bug report guidelines.

**Comment by eSSy-90** [comment]
> The provided project uses a third-party addon "UnityAdsX". Please only submit issues where no third-party addons are used as per the bug report guidelines.

Removing the UnityAdsX plugin from the project did not help. The error remains. Here is the project without the plugin: https://drive.google.com/file/d/1sfyAoJ9bHo7GUAL5pPSgO4ORluwrLGWB/view?usp=sharing

**Comment by eSSy-90** [comment]
Can anyone help solve this problem?

**Comment by eSSy-90** [comment]
> @eSSy-90 Pay for your subscription?

Ha-ha! 😄 I will have to create another topic because this topic is closed.
