### ISSUE TITLE
Video Plugin Drags Project Performance Down Below 10 FPS (*Only After v285!*)

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-bugs#7238]
## Problem description

Video playback on Firefox extremely reduces project performance (down to single digit frames-per-second), and while this has been reported before as a Firefox issue, it seems that **Firefox runs videos perfectly fine up to Construct 3 v285!** I've gone back and confirmed this by running projects in older versions: in v285 there's no issue, in v286 projects containing videos wouldn't run at all, and then in v287 videos will run but slow down the project performance entirely. This leads me to believe that the issue is caused by some change introduced in v286.

Could you perhaps look into the changes made to Construct's video plugin (which are mentioned in a couple places in the v286 and v287 patch notes, including a regression of some kind https://www.construct.net/en/make-games/releases/beta/r287) at the time and see if anything was done that might explain the video player now dropping project performance like this?

## Attach a .c3p
[Video.zip](https://github.com/Scirra/Construct-bugs/files/12099379/Video.zip)

## Steps to reproduce

1. In **v285 on Firefox**, open the included project or another project with a video added to the layout.
2. Run the project and note that **it runs smoothly** while playing the video.
3. In **v286 and onward on Firefox**, open the included project or another project with a video added to the layout.
4. Run the project and note that **performance drops drastically** (sometimes as low as 2 FPS) with the video struggling to play (and in v286 specifically the project may not finish loading for preview at all).

## Observed result

After v285, videos break performance in Firefox.

## Expected result

Videos would play and not negatively affect performance in future versions, just like in v285.

## More details

Video of sample project running in v285:
https://github.com/Scirra/Construct-bugs/assets/4585257/27f6cbae-2a10-4a3f-9848-6054fd32ad5e

Video of sample project running in v286:
https://github.com/Scirra/Construct-bugs/assets/4585257/7bbdda67-5c59-4553-95f4-3c852b14ff56

Video of sample project running in v287:
https://github.com/Scirra/Construct-bugs/assets/4585257/03d37b9c-eeb8-4a87-9587-c35f4c458ba2

Theoretically, if a project were made simple enough that it doesn't need C3's more modern features but did need video playback, it could be built in v285 but that seems ill-advised and of course lock someone out of a lot of newer desirable features.

**Affected browsers/platforms:** Firefox

**First affected release:** Worked fine in v285, issue appears in v286/287 and onward.

## System details

System details from **v287**:

<details><summary>Platform Information</summary>

Browser: Firefox
Browser version: 115.0
Browser engine: Gecko
Context: browser
Operating system: Windows
Operating system version: 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
C3 release: r287 (beta)
Language setting: en-US
Local storage

Storage quota (approx): 58 gb
Storage usage (approx): 682 mb (1.1%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I suspect the relevant changes were made in response to issue #5524 - itself an effort to improve video performance on Android.

We've been through a few iterations of how to best play videos in a WebGL context now (which is what Construct needs to do - it's not the same as a typical video playback), and it's proven a struggle to get something that performs well on all browsers and platforms. I don't want to change it back, as it will bring back the performance problem in #5524. It seems weird that Firefox is so slow in this case, so instead I've filed a Firefox issue for it here: https://bugzilla.mozilla.org/show_bug.cgi?id=1844548
