### ISSUE TITLE
Render cells crash when destroying a global object

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7239]
## Problem description

Destroying a global object that came from a layer with render cells enabled and went to a new layout where the layer doesn't have render cells enabled crashes the game

## Attach a .c3p

[renderCellBug.zip](https://github.com/Scirra/Construct-bugs/files/12100868/renderCellBug.zip)

## Steps to reproduce

1. Preview Layout 1
2. Press Button to go to Layout 2
3. Press Other Button to destroy Sprite 1

## Observed result

Error
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/d2160ce6-7348-4f0d-8213-e3a742183ed8)

## Expected result

No error

## More details

For some ungodly reason, when debugging this with the Chrome Debugger, wether the sprite is global or not, and wether it comes from a layer with render cell or not, the function still gets called.
What seems to happen here is that `this.GetLayer().GetRenderGrid()` returns null and so calling Update on it rightfully crashes.

HOWEVER, when disabling the render cells, this method still gets called, and for some reason, stepping over that line just teleports the program counter elsewhere and the runtime just goes on its merry way and keeps running as if nothing ever happened.

Now, maybe the runtime is wrapping that call in a try catch but not if render cells are enabled, but I couldn't manage to find said trycatch and I'm just left wondering what the fuck is happening with the debugger.

All I know is that one case works and the other one does not.

**Affected browsers/platforms:** Tested Chrome Only

**First affected release:** AFAIK for at least 2 years (according to the developer of BioGun who reported this issue to me thinking I was a Scirra employee)

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
