### ISSUE TITLE
Duplicating array file and renaming without entering it doesn't save row/column properties (names, sizes)

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7240]
## Problem description

I am running into the problem that I have a template array file (as json, made in C3) which I duplicate to fill up different dialogues. When I duplicate it, if I do not enter the new file, but instead rename it beforehand, the column/row properties do not get saved.

https://github.com/Scirra/Construct-bugs/assets/7268697/fac7bc30-4a43-4c15-9f93-ca346c5cc600

This is the original
<img width="882" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/7268697/5353210e-36e9-468d-9c48-6fa2b0c25b7e">

## Steps to reproduce

1. open project
2. create array (file)
3. rename some rows and columns, resize them
4. close the file
5. duplicate file
6. rename file
7. open the duplicated file

## Observed result

Notice the duplicated file does not have the columns and rows names and sizes saved.

## Expected result

I expect the properties to be saved at all times.

## More details

**Affected browsers/platforms:** Chrome on mac

**First affected release:** r344.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r344.2 (stable)
Browser: Chrome 114.0.5735.198
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 81 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by JeFawk** [comment]
This also happens when you move an array file inside a subfolder

https://github.com/Scirra/Construct-bugs/assets/7268697/771bdea5-6b7d-47d7-b1d5-efb8be42c690

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
