### ISSUE TITLE
Color picker for tabs not appearing at all in Safari

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7243]
## Problem description

The color picker window does not appear:

https://github.com/Scirra/Construct-bugs/assets/7268697/3c373751-3c9e-4819-88ae-a513cae1b644

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** Safari mac

**First affected release:** r350
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Safari 16.0
Browser engine: WebKit
Context: browser
Operating system: macOS 10.15.7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
Language setting: en-US

Local storage
Storage quota (approx): (status unavailable)
Storage usage (approx): (status unavailable)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Safari due to bug 177132
Web Animations are not supported. Animations are disabled.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
Storage quota estimate is unavailable.
WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
Supported encode formats:

MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

H.264 (video/mp4; codecs=avc1.42E01E)

</details>

**Comment by AshleyScirra** [comment]
More Safari weirdness. It looks like a Safari bug but I found a workaround which is probably a quicker solution (especially as I am sick to death of the terrible way Apple deal with Safari issues).
