### ISSUE TITLE
Array file columns and rows can be resized with right click while menu is opened

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7248]
## Problem description

Right clicking on the edge of a row / column opens the menu and gets the row / column stuck into resize move following the cursor.

https://github.com/Scirra/Construct-bugs/assets/7268697/c95f9cd5-a5b4-40d7-a8f7-88dc7f84c348

## Steps to reproduce

1. open an empty project
2. create an array file
3. open the file
4. right click on the edge as if you were to resize a column or a row (if using left click)

## Observed result

Notice the context menu opens, and the column/row is being resized following the mouse cursor as long as the cursor is not overlapping the context menu.

## Expected result

No resize, just context menu should appear. Resizing should be done only with left mouse button.

## More details

**Affected browsers/platforms:** Chrome on Mac

**First affected release:** since I can remember

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 114.0.5735.248
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 105 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
@JeFawk Can not reproduce.

**Comment by JeFawk** [comment]
Okey, thanks. I added more information.

**Comment by JeFawk** [comment]
Maybe dragging with any mouse button is related to having C3 work on mobile?

**Comment by AshleyScirra** [comment]
Weirdly I can't reproduce this on Windows but it does reproduce on macOS, even though both are using Chrome. Probably some inconsistently with pointer events. However on Windows you can resize cells using the middle and right mouse buttons, and usually that is only allowed for the left mouse button, and allowing resizing with the right mouse button is probably why it's interfering with the context menu. So for the next beta I've just made sure cell resizing only works with the left mouse button.
