### ISSUE TITLE
"Your browser is too old" on latest Chrome 115

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7257]
## Problem description
I have been using Construct for months. A few days ago my internet provider had issues and I couldn't launch construct. When the service came back today, C3 has been showing this message:
```
The following features required to run Construct but are not supported by the current browser:

ES2015 support
```
I added the browser console output below.

## More details

**Affected browsers/platforms:** Chrome (Version 115.0.5790.110 (Official Build) (64-bit))

**First affected release:** Stable

## System details

<details><summary>View details</summary>

es2015check.js:1     Failed to load resource: the server responded with a status of 503 ()
editor.construct.net/:1 Refused to execute script from 'https://editor.construct.net/r350/loader/es2015check.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
analytics-init.js:1     Failed to load resource: the server responded with a status of 503 ()
editor.construct.net/:1 Refused to execute script from 'https://editor.construct.net/r350/loader/analytics-init.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
supportCheck.js:4 Uncaught TypeError: window.ClaimAnalyticsSandbox is not a function
    at p (supportCheck.js:4:148)
    at l (supportCheck.js:3:269)
    at h (supportCheck.js:2:318)
    at supportCheck.js:7:141
    at supportCheck.js:7:146
register-root-sw.js:17 Registered root service worker on https://editor.construct.net/
editor.construct.net/:1 Refused to apply style from 'https://editor.construct.net/r350/loader/loadingerror.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
/r350/appmanifest.json:1     Failed to load resource: the server responded with a status of 503 ()
/r350/appmanifest.json:1 Manifest: Line: 1, column: 1, Syntax error.
/r350/media/icon-512.png:1     Failed to load resource: the server responded with a status of 503 ()
editor.construct.net/:1 Refused to apply style from 'https://editor.construct.net/r350/loader/loadingerror.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
appmanifest.json:1     Failed to load resource: the server responded with a status of 503 ()

</details>

**Comment by AshleyScirra** [comment]
It works fine for me right now in Chrome 115. The error logs show a 503 error so I think this is related to a server outage we had recently which was subsequently fixed so this should not be happening any more.
