### ISSUE TITLE
Crash timeline forgotten family

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7259]
## Problem description

Construct crashes.

## Attach a .c3p

[crash_timeline_forgotten_family_r351b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12188526/crash_timeline_forgotten_family_r351b.zip)

## Steps to reproduce

1. Open a project.
2. In the right ear, click on `Sprite` in the family and select `Remove from family`.
3. Duplicate `Timeline 1`.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/ba42984d-8795-4993-a007-957938c1749a

## Expected result

Construct does not crash.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r351b

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: behavior type not found @ Error: behavior type not found at d.nOa (https://editor.construct.net/r351/projectResources.js:1197:112) at d.Ha (https://editor.construct.net/r351/projectResources.js:1194:501) at d.L3b (https://editor.construct.net/r351/projectResources.js:1199:132) at d.kLc (https://editor.construct.net/r351/projectResources.js:1171:62) at d.Ha (https://editor.construct.net/r351/projectResources.js:1169:448) at d.Ha (https://editor.construct.net/r351/projectResources.js:1174:180) at d.kLc (https://editor.construct.net/r351/projectResources.js:1170:501) at d.Ha (https://editor.construct.net/r351/projectResources.js:1169:448) at d.Ha (https://editor.construct.net/r351/projectResources.js:1127:330) at d.M3b (https://editor.construct.net/r351/projectResources.js:1134:9)
Stack: Error: behavior type not found at d.nOa (https://editor.construct.net/r351/projectResources.js:1197:112) at d.Ha (https://editor.construct.net/r351/projectResources.js:1194:501) at d.L3b (https://editor.construct.net/r351/projectResources.js:1199:132) at d.kLc (https://editor.construct.net/r351/projectResources.js:1171:62) at d.Ha (https://editor.construct.net/r351/projectResources.js:1169:448) at d.Ha (https://editor.construct.net/r351/projectResources.js:1174:180) at d.kLc (https://editor.construct.net/r351/projectResources.js:1170:501) at d.Ha (https://editor.construct.net/r351/projectResources.js:1169:448) at d.Ha (https://editor.construct.net/r351/projectResources.js:1127:330) at d.M3b (https://editor.construct.net/r351/projectResources.js:1134:9)
Construct version: r351
URL: https://editor.construct.net/r351/
Date: Fri Jul 28 2023 00:59:05 GMT+0300 (Восточная Европа, летнее время)
Uptime: 52.7 s

Platform information
Product: Construct 3 r351 (beta)
Browser: Chrome 115.0.5790.110
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - removing Sprite from Family1 means it no longer has the family behavior, and so a timeline track referencing the family behavior for Sprite needs to be removed, in much the same way it would be removed if the behavior itself was deleted.

**Comment by DiegoScirra** [comment]
Will be fixed starting with the next release cycle.
