### ISSUE TITLE
On tween finished tag is not working properly for newly created family objects, after the first tween is finished

### ISSUE THREAD

**Issue by vascco47** [Scirra/Construct-bugs#7274]
## Problem description
We have a family that has tween behavior. After creating an object from a family, with the running tween behavior, the "On Tween finished" tag does not work correctly for every next newly created object, with a different tween tag, after the first tween is finished.

## Attach a .c3p
[FamilyTweenOnFinishedBug.zip](https://github.com/Scirra/Construct-bugs/files/12219960/FamilyTweenOnFinishedBug.zip)

## Steps to reproduce

1. Open file and run Layout 1 preview
2. Press space to start objects creation and tween behavior
3.

## Observed result

After creating second object of the family, with a different Tween tag than the "On tween finished" tag, an infinite loop starts.
## Expected result

After completing the Tween behavior for the second object, no new objects should be created.
## More details

**Affected browsers/platforms:** 
Tested in Chrome Version 115.0.5790.110 (Official Build) (64-bit)

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.110
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 52 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment]
I think this is a misunderstanding of the tagging system:
https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/tween
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/18100a6b-d5e8-4ad4-b8bc-452d0a81d3bb)

**Comment by DiegoScirra** [comment]
Yes, this is a misunderstanding of the tag system of the tween behaviour.

When you use the string **"Test tween"**, you are actually giving the tween two tags, **"Test"** and **"tween"**. Spaces are used as delimiters, so you are able to give a tween multiple tags. This means that when you create a new tween with the tag string "Test tween 1", it has three tags "Test", "tween" and "1".

A tween with those tags matches an **"On Finished Condition"** with the tags **"Test"** and **"tween"** so the example will generate an infinite loop.

You can get the example to work as you expect it, if you use the tag "Test_tween" and "Test_tween_1" in the appropriate places.

**Comment by vascco47** [comment]
I didn't think in that direction at all, since I looked at each Tag as a single string. I should have read the Tween manual before writing on this page. This is definitely not a bug.
Thanks for the clarification @F3der1co and @DiegoScirra
