### ISSUE TITLE
Multiplayer Real Time Game Example Broken

### ISSUE THREAD

**Issue by tyler3327** [Scirra/Construct-bugs#7275]
## Problem description

Upon trying to play the multiplayer real-time game example it presents you with a kicked message.

## Attach a .c3p

Just open the example provided by construct 3.

## Steps to reproduce

1.Open real-time multiplayer game example
2.click play button
3.choose any username
4.Choose any user name and click join
5.Your game will attempt to join host then fail and kick you

## Observed result

cannot play I've tested this on desktop windows 11, s23 ultra, and laptop windows 11.

## Expected result

Join as host or join a host but it fails to find a host or set you as a host.

![test](https://github.com/Scirra/Construct-bugs/assets/32486148/e59e1ee0-5e12-4208-813f-dc5d3376a023)

**Comment by AshleyScirra** [comment]
It works fine for me.

Note it uses a hard-coded room name, and so there could have been someone else hosting the example at the time you tried to test it, who could not establish a connection to your device. That would be consistent with what you saw. In that case you should change the room name to make your own independent test.
