### ISSUE TITLE
STATUS_STACK_BUFFER_OVERRUN in Chromium when using Text and TextInput

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7280]
## Problem description
When the project is being run in preview, Chromium has the following error code: STATUS_STACK_BUFFER_OVERRUN

## Attach a .c3p
[PreviewLoadBug.zip](https://github.com/Scirra/Construct-bugs/files/12252181/PreviewLoadBug.zip)

## Steps to reproduce
1. Create a new project
2. Add multiple textinputs and a text field
3. The project does not render anymore

## Observed result
![grafik](https://github.com/Scirra/Construct-bugs/assets/80539587/9698c667-b11b-493c-8cff-6ea24f18c0c6)

The preview does not work. 

## Expected result

The preview should load. 

## More details
Chromium Version 92.0.4515.131

## System details
Windows 11 with AMD graphics drivers and 13th gen intel cpu

<details><summary>View details</summary>

**Comment by AshleyScirra** [comment]
Works fine for me in Chrome 115. You said you're using Chrome 92, which is quite out of date now, so I would guess that's the problem.

**Comment by therealPaulPlay** [comment]
Can confirm it is working in Version 117. Interesting. Thanks for testing anyway!
