### ISSUE TITLE
Family spawn original object - actions applied to the wrong instance

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-bugs#7281]
## Problem description

When I use a family to spawn the original object, any actions preformed on the original object in that event is applied to the family instance instead.

## Attach a .c3p

[family_vs_sprite.zip](https://github.com/Scirra/Construct-bugs/files/12255034/family_vs_sprite.zip)

## Steps to reproduce

1. Preview the project.

## Observed result

Newly created instance remain white and visible while the family instance who created them changes.

## Expected result

Actions after spawning should apply to the new instances only.

## More details

**Affected browsers/platforms:** 

**First affected release:**  r352

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's kind of a confusing project that relies on creating lots of instances on top of each other so it's hard to tell what's happening. If I make a truly minimal reproduction of what you state, it appears to work correctly: 
[issue7281.zip](https://github.com/Scirra/Construct-bugs/files/12259544/issue7281.zip)
So if the problem really is that spawning from a family applies following actions incorrectly, that project seems to show that does in fact work correctly: only the spawned object is rotated.

**Comment by WilsonPercival** [comment]
> It's kind of a confusing project that relies on creating lots of instances on top of each other so it's hard to tell what's happening. If I make a truly minimal reproduction of what you state, it appears to work correctly: [issue7281.zip](https://github.com/Scirra/Construct-bugs/files/12259544/issue7281.zip) So if the problem really is that spawning from a family applies following actions incorrectly, that project seems to show that does in fact work correctly: only the spawned object is rotated.

@AshleyScirra No, you won't see wrong work in your project either. I created a project demonstrating the problem. Notice that the sprite behind it has rotated. And as we know, new sprites are created on top.

[example.zip](https://github.com/Scirra/Construct-bugs/files/12259769/example.zip)

**Comment by avishaymizrav** [comment]
> It's kind of a confusing project that relies on creating lots of instances on top of each other so it's hard to tell what's happening. If I make a truly minimal reproduction of what you state, it appears to work correctly: [issue7281.zip](https://github.com/Scirra/Construct-bugs/files/12259544/issue7281.zip) So if the problem really is that spawning from a family applies following actions incorrectly, that project seems to show that does in fact work correctly: only the spawned object is rotated.

It happens in your file too, try coloring the newly created instance and see that the bottom one is colored and not the top.

**Comment by AshleyScirra** [comment]
OK, here's the minimal repro I needed: [issue7281-take2.zip](https://github.com/Scirra/Construct-bugs/files/12335092/issue7281-take2.zip)

It's currently working the same as if you did "Sprite: spawn Sprite", in which case a long-standing limitation means it does not pick the spawned sprite instance. However it is possible to make an exception for the case where the action is for a family, so it works as expected in this case. This change has been made for the next beta.
