### ISSUE TITLE
QR code not recognized by Android 13 (Samsung Galaxy S22)

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-bugs#7284]
## Problem description
I created several short and long URLs (play store link) with different QR plugin correction level settings and in different sizes but my camera app does not recognize any of them. Do you need a example file?

## Steps to reproduce

1. add QR plugin
2. preview to scan it

## Observed result

nothing happens on Android 13 (Samsung)
## Expected result

QR Code should be recognized and an option to open the link shown.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r350
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.111
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.8000000715255737
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 325 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by WilsonPercival** [comment]
@TheBl4ckSh33p Have you tried this example? Doesn't it work for you?

<img width="313" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/5e2a7dc9-3f16-47b0-8cfa-d39f9549d9a6">

**Comment by TheBl4ckSh33p** [comment]
yes, it worked! It seems it does not like my black/dark background in my app. 
So you always need to have a white background around the code?

**Comment by WilsonPercival** [comment]
> yes, it worked! It seems it does not like my black/dark or red background in my app. So you always need to have a white background around the code?

@TheBl4ckSh33p I cannot answer this question.

**Comment by AshleyScirra** [comment]
It works fine for me.

Whether or not specific QR code readers can read the QR code is not an issue with Construct. It's definitely generating a valid QR code. But you probably need to make sure nothing obscures the QR code, that its colors aren't altered, and that it has a clear border (no other content right up against it) to ensure QR code readers can correctly identify it. Again, none of this is specific to Construct, that's just how QR codes work - they need to be clearly presented to be readable.

**Comment by TheBl4ckSh33p** [comment]
I see, but I used a new layer with a solid background (tiled bg) to have the code without distractions on screen.

But when the background is not white it is not recognized. I tried several colors and only white worked so far. 🤔
