### ISSUE TITLE
Missing manual info for Sprite.AsJson

### ISSUE THREAD

**Issue by TheBl4ckSh33p** [Scirra/Construct-bugs#7286]
## Problem description
The manual does not explain what the AsJson expression does or mention that it even exists.
(its a big list of values and even some text from other text objects, not sure why it is in the sprite.asjson)

## Attach a .c3p
N/A

## Steps to reproduce

1. add sprite
2. broser > download string > Sprite.AsJson as string

## Observed result

N/A
## Expected result
N/A

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Yep, it's already documented in the "Common expressions" section.

**Comment by TheBl4ckSh33p** [comment]
Thanks. Didn't look for common expressions. 🫠

I believe other plugins had the AsJSON expression listed.
