### ISSUE TITLE
When an object reads JSON data, the object's child objects cannot immediately follow its coordinates

### ISSUE THREAD

**Issue by kalefal** [Scirra/Construct-bugs#7294]
When you use JSON to save the state of an object, your children who follow coordinates are still reading the previous coordinates when you read JSON to return to that state.

Maybe it's not a bug, that's how the engine works. But such a situation is indeed more troublesome to deal with.

**Comment by WilsonPercival** [comment]
@kalefal Could you reproduce the problem in the project? It is very difficult to understand what your problem is without having a project file.

**Comment by kalefal** [comment]
> @kalefal Could you reproduce the problem in the project? It is very difficult to understand what your problem is without having a project file.

Ok, I'll create a new project file to reproduce the problem. When you press the Save and Load buttons, the children of the loaded object become disjointed
[Child objects problem when reading JSON.zip](https://github.com/Scirra/Construct-bugs/files/12327562/Child.objects.problem.when.reading.JSON.zip)

**Comment by WilsonPercival** [comment]
> > @kalefal Could you reproduce the problem in the project? It is very difficult to understand what your problem is without having a project file.
> 
> Ok, I'll create a new project file to reproduce the problem. When you press the Save and Load buttons, the children of the loaded object become disjointed [Child objects problem when reading JSON.zip](https://github.com/Scirra/Construct-bugs/files/12327562/Child.objects.problem.when.reading.JSON.zip)

@kalefal I'm not sure if this is a bug. As a workaround, you can try doing the following:

<img width="532" alt="solution" src="https://github.com/Scirra/Construct-bugs/assets/91274932/f9bf2bb4-b115-476a-8a48-cd4d0b7aa60a">

**Comment by kalefal** [comment]
> 



> > > @kalefal Could you reproduce the problem in the project? It is very difficult to understand what your problem is without having a project file.
> > 
> > 
> > Ok, I'll create a new project file to reproduce the problem. When you press the Save and Load buttons, the children of the loaded object become disjointed [Child objects problem when reading JSON.zip](https://github.com/Scirra/Construct-bugs/files/12327562/Child.objects.problem.when.reading.JSON.zip)
> 
> @kalefal I'm not sure if this is a bug. As a workaround, you can try doing the following:
> 
> <img alt="solution" width="532" src="https://user-images.githubusercontent.com/91274932/260240923-f9bf2bb4-b115-476a-8a48-cd4d0b7aa60a.png">

Well, this solution is also possible.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible for us to help.
