### ISSUE TITLE
Importing script for side effects is broken now

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7295]
## Problem description

This line:
`import "./script.js`
now crashes C3's preview

## Attach a .c3p

[import bug.zip](https://github.com/Scirra/Construct-bugs/files/12320606/import.bug.zip)

## Steps to reproduce

1. Preview
2. Replace the import with the comented one
3. Preview again

## Observed result

This line:
`import "./script.js`
crashes C3's preview

This line:
`import * as test from "./script.js"`
does not crash C3's preview

## Expected result

It didn't crash in the past, and I don't see why it would crash now

## More details

**Affected browsers/platforms:** Chrome, haven't tested the other ones

**First affected release:** No clue, all I know is that it happened after 336 because it worked fine then 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@skymen Can not reproduce. Everything works perfectly.

https://github.com/Scirra/Construct-bugs/assets/91274932/939e83de-cc11-433c-a8cc-66346e0fc48b

**Comment by WilsonPercival** [comment]
> It seems the bug happens at random even for me. I have no idea why. At least it's consistently working when using debug, but for some reason on my PC it breaks half the time.
> 
> I asked a few other ppl to test and tested on other machines and it's all working fine. Wondering if it's caused by a new Chrome update, or if I need to blame an extension somehow even tho they haven't changed for the past 6 months

@skymen I also catch bugs sometimes.

There were cases when I ran and got out a window that the scripts were broken. I didn't change anything, just ran it again and it worked.

I also caught errors when I wrote the code, the code was correct, but the syntax check gave an error where there was none. I don't remember the exact sequence that I did to fix it. It seems that I just wrote one character, then erased it and it all worked.

**Comment by AshleyScirra** [comment]
It all seems to be working fine for me.

FWIW script imports have to be served via the Service Worker. If you have any browser extensions which could interfere with that, or you clear/reset browser data periodically, it could cause the Service Worker to be missing or serve incorrectly, which would cause an error trying to load the import. But if the SW is there and working normally it should all work fine, and that's what I see happening.
