### ISSUE TITLE
The clipboard feature isn't working on Android, when going through a Facebook link

### ISSUE THREAD

**Issue by TurkMcGill** [Scirra/Construct-bugs#7296]
## Problem description

I recently released a web-based game: worddad.com. It includes a Share feature where players tap or click on a "Share" button. This copies a text message to the clipboard using the Clipboard object. They can then paste the message into Facebook, e-mail, etc. (I am NOT using the Share object in my game.)

When I officially announced the game I posted about it on Facebook. A few days later players started reporting that the Share feature wasn't working. I tracked the problem down to Android phone users. I created a test project (attached) and had two of my Android players test it. They both reported that the the Clipboard object worked, as intended, ONLY if they typed the address of the game into the browser on their Android phones. If they followed the Facebook link to the game, however, then the Clipboard object did NOT work. (They tapped a button to copy a text message then tapped in a text input box. The clipboard was empty.)

## Attach a .c3p

I zipped up a .c3p file and attached it to this message.

## Steps to reproduce

1. Send yourself a Facebook message with the link: https://www.cuttergames.com/cliptest/
2. Use an Android device and follow the Facebook link
3. Tap on the OK button, then tap in the Input box at the bottom of the screen. Try to paste the message.
4. Try the same thing again, only this time type the URL into a browser. Now the Clipboard object will work.

## Observed result

[cliptest.zip](https://github.com/Scirra/Construct-bugs/files/12323087/cliptest.zip)

When you go through Facebook, the Clipboard feature doesn't work. You tap on the button to copy the text message, but when you try to paste the message the clipboard is empty.

## Expected result

I expected the Clipboard object on Android to work whether it goes through a Facebook link or not. 

## More details

I have only received complaints about the Clipboard feature not working on Android phones.

**Affected browsers/platforms:** 

One of my testers, who is having the problem, reported these system specs:
Samsung A53G, Android 13, Chrome 115.0.5790.166

## System details

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.171
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 546 gb
Storage usage (approx): 30 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

**Comment by AshleyScirra** [comment]
The underlying Clipboard API works in Chrome, but a [known issue](https://bugs.chromium.org/p/chromium/issues/detail?id=1271620) is currently preventing it from working in the Android WebView. I would guess when viewing in the Facebook app it is using the Android WebView instead of the real Chrome browser so is running in to that bug. I'm afraid there's nothing we can do until Google fix the issue.
