### ISSUE TITLE
Form elements squashed at viewport edges

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-bugs#7297]
## Problem description

Form elements such as buttons are resized when up against the edge of the viewport.

## Attach a .c3p
https://www.dropbox.com/scl/fi/evfvzgn6t5s5ab40j9n64/formelementclipping.c3p?rlkey=c0p411c6jodx276gjgopg9mkx&dl=0

## Steps to reproduce

1. Preview project
2. Use sliderbar to scroll up and down

## Observed result
Form elements are resized at edge of viewport.

See difference in rendering behavior between the sprite+text and the form elements at the edge of the viewport.

## Expected result
Button elements are clipped at edge of viewport and preserve their size.

Allow form elements to exist at their full size even when partially or fully outside the viewport.

## More details
This has implications for slider bars being cut short as well, as can be observed in the attached example.
Would setting the css property overflow: clip be possible or reasonable?
https://www.w3schools.com/cssref/pr_pos_overflow.php
I don't seem to be able to apply this property manually, as the runtime seems to explicitly adjust the size of the elements dynamically.

It would be ideal if the rendering and behavior of form elements could be as similar as possible to any other object like a sprite. I know form elements won't work with layers and z levels, but maybe this resizing behavior at the edge of viewport could be improved without being a breaking change?

**Affected browsers/platforms:**  Chrome Windows 10

**First affected release:**  n/a

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.171
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 55 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon RX 570 Series Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7200

**Comment by oosyrag** [comment]
Yes, a duplicate, but I given Ahsley's stated intent of "It's currently by design that HTML elements are clipped to the canvas area, to match how other objects render." in that issue, I think it's worth at least another glance. Hopefully this example project illustrates the problem a little better.

As it is now, HTML element's aren't clipped, they are being resized to fit within the bounds of the canvas/viewport. Maybe it's an issue of definition of clipped, but I imagine clipped as in cut off, not resized, similar to how other objects render. I've added a column of sprites for comparison to the example project to clearly shows the difference in rendering between html form buttons and sprites as it is now.

**Comment by DinoSystem** [comment]
That's why I no longer use HTML elements in my game, got my custom buttons, took a month to make fancy and fuctional ones.

**Comment by oosyrag** [comment]
The application of CSS to form could be a very powerful tool in addressing a weakness of Construct - making quick, easy, and appealing UI elements. Rather than just giving up on a very awesome feature and going with the alternative, I'd rather try to bring attention to and address the issue so that the feature may be improved for future use.

Here is another simple use case, if helpful to show the problem further. https://www.dropbox.com/scl/fi/s6p8wcdxgxx06ta35q8so/cssverticalslider.c3p?rlkey=bjalyf6dz9xerwy187a9l3qdr&dl=0
Two sliders of the same length on the layout editor, rotated 90 degrees. This could be useful as a custom scroll bar. The one on the right is cut short in preview.
