### ISSUE TITLE
Opening NW.js or WKWebview export on macOS fails.

### ISSUE THREAD

**Issue by joelmayer87** [Scirra/Construct-bugs#7306]
When downloading an exported project using either the WKWebview or NW.js option (latest Chromium), macOS gives an error message: "File is damaged and should be moved to the bin". When using your ad-hoc Notarization Terminal Command it works again but it's still unusual that it brings an error message like this. Also i noticed that Construct fails to export NW.js on Macs with anything below the most current Chromium version.

Found same issue here:

https://github.com/Scirra/Construct-bugs/issues/2484

NA

## Steps to reproduce

1. On an Apple Silicon Mac running the specified OS Version Open Example File in Construct
2. Choose Export
3. Choose either NW.js or WKWebview option
4. Export for 64bit ARM
5. Unzip the project 
6. Right Click to open it, which usually forces un-notarized apps to open

## Observed result

Error Message appears.

## Expected result

Usual way macOS does things. You r-click open it twice to override GateKeeper.

Only tested as far back as 350 and the problem persists to the current beta.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Edge 115.0.1901.203
Browser engine: Chromium
Context: webapp
Operating system: macOS 13.4.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 2.8 gb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Pro, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by joelmayer87** [comment]
Updated my system to the latest version (13.5) and got the same result. Just thought i'd add.

**Comment by AshleyScirra** [comment]
> When downloading an exported project using either the WKWebview or NW.js option (latest Chromium), macOS gives an error message: "File is damaged and should be moved to the bin".

The error does not appear when you export or download. I only see this after extracting the resulting zip and attempting to run the unsigned app. This is not supported. The fact macOS shows a weird error message is just macOS being weird and is nothing to do with Construct. The documentation says you must sign it before it will run, and that's the only supported scenario.

> Also i noticed that Construct fails to export NW.js on Macs with anything below the most current Chromium version.

Apple Silicon support for NW.js was only added in v0.77.0 and older versions won't work.

**Comment by AshleyScirra** [comment]
Perhaps they are notarizing the executable themselves. But I'd prefer not to do that, as it seems it associates the tool developer's ID with all content made with it, rather than associating the individual developer's ID with the content they publish themselves. For example on Windows I wouldn't want to digitally sign every executable as distributed by Scirra Ltd, even though digital signatures have benefits, as then everything anyone opens ever made in Construct appears as made by us, which I think is misleading and not what Construct developers want either. So the signing should be done by the publisher, not the tool developer.
