### ISSUE TITLE
Whitelist plugin (new)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-bugs#7308]
Hi,

Would you please whitelist the new plugin below:

```JS
chadori-applovin-max-build@1.0.1
cordova-plugin-health@2.1.0
```
### Reasons
- In the AppLovin MAX documentation, there are additional configurations supposedly added in the config.xml, and in Android Studio and Xcode aside from just installing the official Cordova plugin. This is the plugin to set those configurations, installations, features, etc. so that we do not have to export to Android Studio or Xcode and manually configure. Instead, we can just directly export to `.apk` or `.aab`, and directly run on Xcode without additional configurations.
- This plugin doesn't require maintenance, so hopefully this doesn't need an update for years to come.

I have followed the required guidelines to my knowledge, please let me know if there are issues with my request.
Thank you.

**Comment by AshleyScirra** [comment]
Added `chadori-applovin-max-build@1.0.1` and `cordova-plugin-health@2.1.0` to build service.
