### ISSUE TITLE
Steam Deck built-in controller stops working after connecting external controller

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7310]
## Problem description

After connecting an external controller controller to Steam Deck, the built-in Steam Deck controls stop working.

This is a serious issue - our game has failed Steam Deck certification because of it.
I tested a couple of other Steam games made in Construct 3 and they all have this bug.

## Attach a .c3p

C3P:
https://www.dropbox.com/scl/fi/92uwavxx9z4eznfjokv6s/Deck-gamepad-bug2.c3p?rlkey=cp1uo9yv3fqpcty3i5i2z7w6n&dl=0

Linux64 export, latest NWjs version:
https://www.dropbox.com/scl/fi/gxtc9p8bfthjlb1zjrdbv/GamepadKeyLogger_Linux64.zip?rlkey=u2fh682gdoft67ejrn93ppy16&dl=0

## Steps to reproduce

1. Install the exported game on Steam Deck, add it to Steam. (there are several ways to do this) 
2. Run the game
3. Connect an external controller

## Observed result

The built-in controller is detected as XBox 360 and works normally:
![image](https://github.com/Scirra/Construct-bugs/assets/36763350/7d00efd4-0ee0-4929-9d2f-d2d0006dcb2d)

After you connect another controller (USB or Bluetooth), the built-in one immediately stops responding.
After a few seconds it disappears from the list:
![image](https://github.com/Scirra/Construct-bugs/assets/36763350/8dddcd94-1346-46d5-9ebc-f2d47b0e657b)

Even if you disconnect the external controller, the built-in one won't wort until you restart the app.

## More details

This doesn't happen with games made in other engines like Unity.

**Affected browsers/platforms:** Steam Deck

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.171
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 265 gb
Storage usage (approx): 3 gb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I don't see how this is related to Construct's code - it just talks to the gamepad API provided by the browser and has no influence or logic whatsoever pertaining to managing the detection or hardware connections with gamepads. I think it would be best to contact Valve support about this, unless you can reproduce it with NW.js or Chrome on a Linux system, in which case it might be a NW.js/Chrome issue.
