### ISSUE TITLE
[Multiplayer] Jump issue for peer with local input prediction

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-bugs#7313]
## Problem description

[Multiplayer] Jump issue for peer with local input prediction.

I was observing feasibility of using the Multiplayer plugin again ever since the new updates, it's the closest thing we have to a [smooth sync](https://assetstore.unity.com/packages/tools/network/smooth-sync-96925), until I've came across this bug again. I think this is the last issue we have with the multiplayer plugin, I really hope this finally gets fixed.

If fixing this is not a priority, please at least allow us to disable local input prediction to one axis, in this case the y-axis, since it will at least remedy the issue and make multiplayer platformer somewhat feasible. Thank you.

## Attach a .c3p
[B̶u̶g̶ ̶r̶e̶p̶o̶r̶t̶ ̶-̶ ̶M̶u̶l̶t̶i̶p̶l̶a̶y̶e̶r̶ ̶p̶l̶a̶t̶f̶o̶r̶m̶e̶r̶.̶z̶i̶p̶](https://github.com/Scirra/Construct-bugs/files/12362314/Bug.report.-.Multiplayer.platformer.zip)

[Bug report - Multiplayer platformer.zip)](https://github.com/Scirra/Construct-bugs/files/12363317/Bug.report.-.Multiplayer.platformer.zip) - (Edited) Fixed collision points and origin of player object, just in case it disturbs testers.

## Workaround
For those who need a workaround for this issue, here's a smooth solution:
- [Bug report - Multiplayer platformer - Workaround.zip](https://github.com/Scirra/Construct-bugs/files/12371751/Bug.report.-.Multiplayer.platformer.-.Workaround.zip)

## Steps to reproduce
1. Open two (2) previews, the project will automatically assign the **host** and **peer**.
2. Try jumping from the peer's application.

## Observed result
- The peer fails to jump properly.

## Expected result
- For the client-side prediction to work with jumps.

## Additional resources
- https://www.construct.net/en/forum/construct-2/bugs-21/multiplayer-platformer-jump-113533

**Comment by AshleyScirra** [comment]
Multiplayer bugs generally prove exceptionally difficult to deal with. I'm not sure we'll be able to make progress on this any time soon.

**Comment by Chadori** [comment]
Yeah, it's nearly a decade of a bug report way back from Construct 2, I'm probably expecting too much. Although, I understand, you're a small team afterall. I'll probably just have to use Unity with smooth sync for this, or Godot, since they both have multiplayer support, thanks anyway.

For other's sake though, I'll leave this open.

**Comment by Chadori** [comment]
For those who need a workaround for this issue, here's a smooth solution:
- [Bug report - Multiplayer platformer - Workaround.zip](https://github.com/Scirra/Construct-bugs/files/12371751/Bug.report.-.Multiplayer.platformer.-.Workaround.zip)

The concept is simple; basically, the goal is to avoid the y-axis server reconciliation (position correction) received from the host and only handle client-side prediction for the user-player peer from a peer-client perspective.
However, since the `Sync object` action only has 4 options and none of those allow us to sync only one axis, which I also requested previously, we will have to do this indirectly instead.

![image](https://github.com/Scirra/Construct-bugs/assets/31282960/61936e23-300c-412b-bd33-09138106f3dc)

We will need to avoid syncing our actual player with a placeholder, not to be confused with the **player placeholder** for the platform behavior, but a placeholder for the **multiplayer entity**. This placeholder must also have the same behaviors as your player placeholder, in this case the platform behavior.

![image](https://github.com/Scirra/Construct-bugs/assets/31282960/52a38580-0be0-43ec-b8c9-e63b1e9ad735)

I'll call this multiplayer entity placeholder **"Mask"**, and it will be invisible throughout the game. The behavior and goals of the multiplayer entity placeholder will be the following:
- **Host**
  - Receive input from the peer.
  - Instantly set the x-axis and y-axis of the player placeholder to the multiplayer placeholder since the host state is the authoritative state.
- **Peer**
  - Receive input from the host.
  - Receive server-authoritative game state.
  - **[Important]** For the non-local (non-user) players, instantly set the x-axis and y-axis to their multiplayer placeholders since the game state received from the host will not be conflicted.
  - For the user player (local user), instantly set the x-axis of the player placeholder to the multiplayer placeholder. Although, **DO NOT** set the y-axis of the player placeholder to the multiplayer placeholder, instead allow the client-side prediction (platform behavior of the multiplayer placeholder) to simulate the y-axis movement.

- **Limitations**: Since this is only a workaround, there are limitations.
  - There is a small chance that a jump can get misplaced; you must check the difference between the y-axis of the multiplayer placeholder and the y-axis of the player placeholder to see if it needs teleporting. Since this rarely happens, there's no need to interpolate; rather, just instantly set the position, although that's up to you.
  
  The platform behavior should now sync smoothly with the multiplayer plugin, until the multiplayer plugin is officially fixed.

**Comment by Chadori** [comment]
**[Warning]** The sample projects have simulated latency!

**Comment by F3der1co** [comment]
suggestion:
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/fe015b9f-b42e-4cf6-a8ed-7c85cce86351)
change the dropdown to checkboxes like the add child action:
x,
y,
angle,

**Comment by Chadori** [comment]
Hi @AshleyScirra, maybe we can avoid the **difficult** sync algorithm rewrite, at least for now, if we are allowed to disable the y-axis server reconciliation by adding flexibility in the object sync options? This includes the suggestion above, which resembles the hierarchy options.

It's the most pragmatic approach and the quickest solution. And after having tested the workaround for a while now, the sync does feel smooth, even with simulated latency. The only caveat is the *very rare* chance the y-axis can stray off, but that can still happen even with a decent sync algorithm.

**Comment by Chadori** [comment]
Hi @AshleyScirra, please at least allow us to turn off the y-axis reconciliation with the **Sync object** action. It really messes up the jumps. I've fixed that by making a multiplayer placeholder instance, but it messes up position correction with Sine behaviors or anything actually, by making the platform instance jump erratically.

I don't know why you think this issue is so difficult. The workaround is simply a fix by commenting this out:
![image](https://github.com/Scirra/Construct-bugs/assets/31282960/366a8cc8-3fd3-476c-81f2-d1db15ba4584)

And to fix the plugin, just add options wherein it only each of the following options:
- `ro.AddValue(INTERP_LINEAR, precision, "x");`
- `ro.AddValue(INTERP_LINEAR, precision, "y");`

If you cannot fix stuffs like these for us, please at least allow the community to edit the runtime again. The features in Construct 2 days were more superior than today, because of the community.

**Comment by SPECT0R1A** [comment]
I was wondering if there was any progress made on solving this issue?

**Comment by Chadori** [comment]
> I was wondering if there was any progress made on solving this issue?

I'm afraid no. The Construct Team has more important things to do like breaking plugins, unsupporting features and tormenting plugin developers for no reason.
- https://www.construct.net/en/forum/construct-3/plugin-sdk-10/addon-sdk-v2-182122
- https://www.construct.net/en/comments/67450

**Comment by AshleyScirra** [comment]
In the next release there are two additional options for controlling how input prediction works:

- Avoid solids: this stops input prediction moving the object in to a solid. If it would have moved the object in to a solid, it instead leaves the object in the same position.
- Platform mode: when enabled for an object using the Platform behavior, this stops input prediction on the Y axis while the Platform movement is on the floor. It will resume input prediction on the Y axis whenever the object is in mid-air.

These settings are fairly simple but if both are enabled it seems to do a much better job of input prediction with the Platform behavior.

If it doesn't do enough, I'm afraid as per my previous comment, I don't know what else ought to be done about it. Further improvements would need research to identify a better algorithm for handling this type of movement, and that should be filed as a feature request describing the algorithm to use.
