### ISSUE TITLE
Facebook Instant Games Ads not working

### ISSUE THREAD

**Issue by am-brick** [Scirra/Construct-bugs#7316]
Neither Facebook login works nor does loading/showing Facebook Instant Games ads work.

[MagicDice.Facebook.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12381327/MagicDice.Facebook.c3p.zip)

## Steps to reproduce

1. Export .c3p file using Facebook Instant Games option
2. Upload zip file to Facebook developer page in Web Hosting section
3. Run the game on Facebook website on PC

## Observed result

The facebook login popup never shows and ads don't load.

## Expected result

Facebook login popup should show up and then ads should load.

## More details
In browser console, there are two errors thrown: 

Exception in 'facebook' handler 'login': DOMException: A parameter or an operation is not supported by the underlying object

The second error is:

[Instant Games] Failed to load ad:  Object { code: "ADS_NO_FILL", message: "No fill" } main.js:153:224

Tested in Google Chrome, Mozilla Firefox

All versions, it never worked

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.170
Browser engine: Chromium
Context: browser
Operating system: macOS 13.4.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 137 gb
Storage usage (approx): 223 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
You don't need to use the Facebook object for Instant Games. Just use the Instant Games plugin on its own.

`ADS_NO_FILL` looks like an error provided by the Instant Games platform, indicating there are no ads available. I think you'll have to contact Instant Games support for help with that - there's nothing we can do about it.
