### ISSUE TITLE
Minify server not work

### ISSUE THREAD

**Issue by henrikszucs** [Scirra/Construct-bugs#7317]
## Problem description

Minify service server not work.
I think it will more useful that users can choose between offline and online minification (in dropdown list).
https://construct23.ideas.aha.io/ideas/C23-I-381

## Attach a .c3p

Any project

## Steps to reproduce

1. Open project
2. Export
3. Set minify to advance

## Observed result

Failed to connect

## Expected result

Connenct and export

## More details

![Képkivágás2](https://github.com/Scirra/Construct-bugs/assets/47735877/4c234d6f-4fff-407d-8f57-5d11926e6f62)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r354 (beta)
Browser: Chrome 116.0.5845.97
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 296 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by C3GameDev** [comment]
Hey,
for me the Minify service also doesn't work anymore for over 1 day now.
I'm using the latest stable and the issue can be reproduced with any project (also tried with new empty project) and also it doesn't matter if you use simple or advanced minify, both don't work...

**Comment by henrikszucs** [comment]
@C3GameDev the last stable not contain cloud minify, you need r354 or above version.
Now the server works well but this new feature worried me because users depend from a single server. No backup options or plans that exist in previous versions.

Great example is the android building server. You can build your app in local machine and if servers are broken I can continue my work.

**Comment by C3GameDev** [comment]
@henrikszucs Hey, just to be sure: Minifier just isn't supported anymore in the latest Stable version? Why is there still an option to use the minifier at export?

**Comment by henrikszucs** [comment]
Yes sometimes need clear the cache. Might CheerpJ stucked. It is a framework to run minifer tool that is a Closure Compiler that written in Java (not in JavaScript).

In the latest stable (r350) version minifier work as before. In the latest beta update (r354 - https://www.construct.net/en/make-games/releases/beta/r354) change that minify option will not run in the local computer, instead use https://minify.construct.net/ service and if you cannot access to https://minify.construct.net/ your exportation wont work if enable minify option.

**Comment by WilsonPercival** [comment]
Can not reproduce. In `r354b` advanced minification works well.

**Comment by AshleyScirra** [comment]
The minify server is working fine for me right now.

> Now the server works well but this new feature worried me because users depend from a single server. No backup options or plans that exist in previous versions.

There is an alternative option: export without minification and then minify the resulting JavaScript files with a separate third party tool. In this respect it is actually analogous to the build service - either use the service we provide or do it yourself.
