### ISSUE TITLE
Construct 3 builds damaged APK (not installed on Android)

### ISSUE THREAD

**Issue by eSSy-90** [Scirra/Construct-bugs#7318]
## Problem description
Hello. I'm creating a signed apk release using Construct 3. But the APK file is broken and not installed. 

## Attach a .c3p
Project file without 3-rd party addons: https://drive.google.com/file/d/1sfyAoJ9bHo7GUAL5pPSgO4ORluwrLGWB/view?usp=sharing

## Steps to reproduce

1. Open the project.
2. Export it for Cordova (Deduplicate images, Minify script - simple) for Android 8+ (Signed Release APK, only "Hide status bar" checkbox mark).
3. Try to install the APK file.

## Observed result

When I try to install the APK, the following happens.
BlueStacks says: Install parse failed.  Unexpected Exception.

Google Play Console says:
6:56 13151 13151] Zip: bad offsets (dir 61841673, size 41339, eocd 61817476)
error: failed opening zip: Invalid offset.

The Android device says: "APP not installed".
## Expected result

The compiled APK should install without errors.

## More details
If you delete the object types starting with "A-D", then the compiled APK will install successfully.
If you remove all sounds and music, then the compiled APK will install successfully too.
I purposely made a project without game code to narrow down the range of the bug.

**Affected browsers/platforms:** 
I used different browsers: Mozilla Firefox, Google Chrome. Also on another PC. The problem remains.

**First affected release:** 
This bug never appeared in 2022.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't think Android lets you run a signed APK unless it comes from a known source like the Google Play Store. Have you tried a debug APK?

**Comment by eSSy-90** [comment]
> I don't think Android lets you run a signed APK unless it comes from a known source like the Google Play Store. Have you tried a debug APK?

Android allows you to run a signed APK. And the source doesn't matter. For 3 years I have been releasing updates for my game using the "signed release APK" method.
Please note: the error disappears if you remove half of the objects from the project. And the signed APK release installs on Android without problems. This means that the problem is exactly how Construct 3 compiles the APK. Perhaps the size of the APK matters.
Debug APK does not help.

**Comment by AshleyScirra** [comment]
I tried following the steps to build a signed release APK from the given project with the same settings. It built, installed and ran just fine on an Android device. So it all seems to be working fine for me. My best guess is there is a problem with your Internet connection that is corrupting the data received from the build server, perhaps only when a certain amount of data is transmitted, hence deleting content could work as it brings the transferred data size below the threshold at which corruption happens on your connection. I'm afraid such problems are beyond our control and there is nothing we can do to help with that.

If you cannot find any other solution, then you should be able to build your app locally using the Cordova CLI, as that does not use the build service: https://www.construct.net/en/tutorials/building-mobile-apps-locally-21
All the build service does is run those same steps, so you can do the same thing manually on your local machine.
