### ISSUE TITLE
Open Folder with NWJS on Windows

### ISSUE THREAD

**Issue by squalinho** [Scirra/Construct-bugs#7319]
With our products we provide a resource folder containing pdfs. We need to be able to open the containers folder by clicking on an icon. to do this we use:
NWjs.AppFolder&"..\" & "/doc/"
Until version v0.62.0 it works, but from version 0.63.0 Windows cannot find the folder.

[bug.zip](https://github.com/Scirra/Construct-bugs/files/12408109/bug.zip)

## Steps to reproduce

1. Export project, 
2. create folder doc at the same level as win64
3. lanch and left click mouse

## Observed result

 windows error : windows cannot find ... 

## Expected result

opening the doc folder

## More details

NWJS

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
If you show the expression the project uses in a text object, it looks like this:

`C:\path\to\appfolder\..\/doc/`

...which is an invalid path. So it looks like the problem is with your project.

**Comment by squalinho** [comment]
Oh sorry,  I made a mistake in my tests but the bug is still present by replacing by:
NWjs.AppFolder&"..\doc\" it works with NWJS 0.62 but not with 0.63

 it works with NWJS 0.62 but not with 0.63

**Comment by squalinho** [comment]
> If you show the expression the project uses in a text object, it looks like this:
> 
> `C:\path\to\appfolder\..\/doc/`
> 
> ...which is an invalid path. So it looks like the problem is with your project.

Oh sorry, I made a mistake in my tests but the bug is still present by replacing by:
NWjs.AppFolder&"..\doc"

it works with NWJS 0.62 but not with 0.63

**Comment by squalinho** [comment]
@AshleyScirra Please try to export with the two different versions of NWJS you will see that there is a problem.

**Comment by JustDzhi** [comment]
@squalinho 
![image](https://github.com/Scirra/Construct-bugs/assets/95054989/72ead165-788b-4bf4-a546-6a41e6b3004d)
In my opinion, it works great.

**Comment by squalinho** [comment]
> @squalinho 
> ![image](https://github.com/Scirra/Construct-bugs/assets/95054989/72ead165-788b-4bf4-a546-6a41e6b3004d)
> In my opinion, it works great.

You try export with NWJS 0.62 and 0.63 ? 
Tested on two different computer, same issue, 0.62 works not 0.63 and older for me.

**Comment by JustDzhi** [comment]
@squalinho 

https://github.com/Scirra/Construct-bugs/assets/95054989/3b141127-cd5d-4f47-a7e9-b28dde339973

Checked on version 0.62 and recorded the proofs.

**Comment by squalinho** [comment]
> @squalinho 
> 
> https://github.com/Scirra/Construct-bugs/assets/95054989/3b141127-cd5d-4f47-a7e9-b28dde339973
> 
> Checked on version 0.62 and recorded the proofs.

Thanks to test !
Sorry I don't explain correctly,

"Tested on two different computer, same issue, 0.62 works not 0.63 and older for me"

I forgot comma ->

"Tested on two different computer, same issue, 0.62 works , not 0.63 and older for me"

0.62 work
0.63 and older ->issue to me

**Comment by JustDzhi** [comment]
https://github.com/Scirra/Construct-bugs/assets/95054989/f7125a02-044c-44b3-b859-ff68ec5d6202

https://github.com/Scirra/Construct-bugs/assets/95054989/8418bab6-d10b-4179-8f9c-03c631758251

I tested 0.63 & 0.64 on my computer, and it's working

**Comment by squalinho** [comment]
> 0.63.mp4 
>  0.64.mp4 
> @squalinho I tested 0.63 & 0.64 on my computer, and it's working

A big thank you for the tests but really I don't understand, a friend just tested on Discord just now and he has the same problem as me.
Could there be a connection with language and special characters? However, I don't use any in my event sheet...
Really, I do not understand

**Comment by squalinho** [comment]
@JustDzhi Oh ! I saw a difference in your video, my doc folder is at the same level as the win64 folder, not in it, NWjs.AppFolder&"..\doc"
Can you try with that please?

**Comment by JustDzhi** [comment]
https://github.com/Scir@squalinho a/Construct-bugs/assets/95054989/45aa5531-4a5e-4d7c-8e7f-05f7fb24c51b

@squalinho First, we need to get the path to the folder, and then use the NWJS.ChoosenPath expression to pass this path to the ShellOpen event.

**Comment by JustDzhi** [comment]
@squalinho First, we need to get the path to the folder, and then use the NWJS.ChoosenPath expression to pass this path to the ShellOpen event.

https://github.com/Scirra/Construct-bugs/assets/95054989/5cb5191f-bc2b-4b0d-92af-835e65cb7ec3

**Comment by squalinho** [comment]
No sorry this is not the desired behavior, the doc folder contains pdf documents which must be accessible directly by clicking in 0.62 it works perfectly.

**Comment by JustDzhi** [comment]
https://github.com/Scirra/Construct-bugs/assets/95054989/d3f40a41-3db4-45f9-ac04-84633b03a23f

@squalinho maybe that?

**Comment by squalinho** [comment]
@JustDzhi Yes ! That works ! A big big thank you to you!!
