### ISSUE TITLE
Construct lags or freezes when moving elements using Down arrow

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#7327]
## Problem description

Construct lags and sometimes freezes completely when moving elements using keyboard's Down arrow. The problem is that when it freezes completely, there is no error message shown, so you cannot save your project.

## Attach a .c3p

[Down Arrow Lag.zip](https://github.com/Scirra/Construct-bugs/files/12420191/Down.Arrow.Lag.zip)

## Steps to reproduce

1. Select an element and move it using keyboard's down arrow

## Observed result

Construct lags

## Expected result

Elements to be moved smoothly on any direction using keyboard

## More details

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** 353? 354?

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r355 (beta)
Browser: Chrome 116.0.5845.97
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 354 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I tried holding the down arrow with the object in the Layout View selected, and I held it down for some time, and it seemed to work perfectly fine here. I'm afraid there's nothing we can do if we cannot reproduce the problem.

**Comment by Dramamini** [comment]
I tested it again. It's working on firefox, the problem shows up on Chrome. Anyway, thanks for your time Ashley

**Comment by MaruserPHT** [comment]
Ive got the exact same issue in edge for quite some time, its not about project, its something wrong with the construct itself cause all projects do the same thing and in any other browser no issues at all
