### ISSUE TITLE
Arrays created in r354 load wrong in r355

### ISSUE THREAD

**Issue by CalebBennetts** [Scirra/Construct-bugs#7334]
## Problem description
When I open a project in r355 that was created in an earlier release (at least in r354), any arrays load incorrectly, and interacting with the array causes crashes.

## Attach a .c3p
https://drive.google.com/file/d/1QP1UORLn6OMvLmNZYG2-hJVPpqWPw43M/view?usp=sharing

## Steps to reproduce

1. Create a project in r354.
2. Create an array.
3. Fill in some data.
4. Save and close the project.
5. Open the project in r355.

## Observed result
The array loads in 2 separate places.
1. A tab with the json information represented as code.
2. A dockable window with the size controls for the array, but no data content.
Attempting to use the size controls crashes the editor.

## Expected result
The array would show up as a tab with size controls at the top and a tabular representation of the data below.

## More details

**Affected browsers/platforms:** 
Only tested with Firefox on Windows 7.

**First affected release:** 
Breaks in r355, but only when trying to open a file made in r354 (or possibly any older release).
## System details

<details><summary>View details</summary>

PASTE HERE
Error report information

Type: unhandled exception
File: https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js, line 102, col 269
Message: TypeError: this.columns[e] is undefined
Stack: Dg@https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js:102:269 Yxb@https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js:38:267 eFc/<@https://editor.construct.net/r355/components/editors/dataEditor/dataEditor.js:23:358 dispatchEvent@https://editor.construct.net/r355/main.js:1257:42 this.uGb@https://editor.construct.net/r355/main.js:1743:486
Construct version: r355
URL: https://editor.construct.net/r355/
Date: Wed Aug 23 2023 19:08:35 GMT-0500 (Central Daylight Time)
Uptime: 15.3 s
Platform information

Product: Construct 3 r355 (beta)
Browser: Firefox 115.0
Browser engine: Gecko
Context: browser
Operating system: Windows 7
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_provoking_vertex
</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7328
