### ISSUE TITLE
R355 - Drawing Canvas on a 3D layer causes image to skew at specific angles

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-bugs#7338]
## Problem description

If you have a Drawing Canvas on a 3D layer, and the 3DCamera is positioned and looking in some specific angles, it causes the Drawing Canvas image to stretch vertically, causing a "crop" effect.

I discovered this in my main project as I have many Drawing Canvas objects that are generated on a 2D layer then placed onto a 3D layer, which works fine, but my 3DCamera moves around smoothly and happens to hit the bad angles that cause this visual bug.

Sprite/Text are not affected.

## Attach a .c3p

[Google Drive](https://drive.google.com/file/d/1CziEQ7YvMKI82NUbLR1pH5-tGV0W8_xo/view?usp=sharing)

## Steps to reproduce

1. Preview the C3P file.
2. Observe the C3 Logo which looks correct, it is a drawing canvas with a sprite pasted onto it (sprite is destroyed immediately).
3. Click the button labelled "Go to example position".
4. Observe the visual bug.
5. You can affect the bug by resizing the preview window, or pressing W and S to move the camera forward and backwards and observe the jittery visuals.

## Observed result

Visuals stretched/crop from drawing canvas image.

## Expected result

No visual bug.

## More details
I tested on my main computer and a 2nd laptop, also tested on Chrome & Firefox, the bug happens everywhere.
Also updated my graphic drivers and such but the issue remains.

**Affected browsers/platforms:** Chrome/Firefox Windows

**First affected release:** R355

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r355 (beta)
Browser: Chrome 118.0.5969.0
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 77 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F15) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
The main problem here is the Drawing Canvas is set to 'Automatic' resolution mode, which tries to establish its resolution from its display size in 2D. These calculations don't work well in 3D and ended up causing the jittery rendering. If you instead set it to fixed resolution mode, it works fine in 3D, and that is probably a more appropriate setting anyway as with a 3D view you probably just want to give it a fixed texture size that it's always drawn with rather than trying to vary the resolution depending on where the camera is.

However I was also able to find a way to improve the rendering quality in 3D even when using automatic resolution mode, which is done for the next release cycle; nevertheless I'd still recommend using fixed resolution mode.
