### ISSUE TITLE
Serious performance issues

### ISSUE THREAD

**Issue by XIMIKATIK** [Scirra/Construct-bugs#7340]
I don't understand what the problem is, but since version r351 in my released android game, the performance has sunk a lot, I can't get more than 40 FPS and the CPU load reaches 80%, although it didn't rise above 40-50% from 60FPS before/ I haven't changed anything or added anything to the game, everything looks fine in the preview, but after exporting to android, the game slows down a lot.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
It's impossible to investigate this kind of issue without any additional information.
