### ISSUE TITLE
Whitelist UnityAds3 4.8.1 cordova Plugin (Fix for Android Build failing)

### ISSUE THREAD

**Issue by artemisoftnian** [Scirra/Construct-bugs#7341]
Hi Ashley,

Once more here I'm ready for another update to UnityAds3 plugin up to 4.8.1 : com-artemisoftnian-plugins-unityads3@4.8.1
Please put me in the flow if can be whitelisted.

Thanks in advance as always!
Great day!

**Comment by AshleyScirra** [comment]
Added `com-artemisoftnian-plugins-unityads3@4.8.1` to build service (replacing v4.8.0 as per the versioning rules).
