### ISSUE TITLE
Weird WGSL issues with custom shaders

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7342]
## Problem description

Hi, I found a very weird WGSL bug that results in the screen going black, and I have ZERO clue why it happens and what the error means.

The issue is that the repro uses 3 addons I made, so I understand if you don't feel enclined looking into it as it's very probable the issue comes from me doing something wrong.

## Attach a .c3p
[Cool Button.zip](https://github.com/Scirra/Construct-bugs/files/12457256/Cool.Button.zip)

ADDONS USED (They have been bundled with the project)
- Empty Shell: https://www.construct.net/en/make-games/addons/933/empty-shell
- Better Shine: https://www.construct.net/en/make-games/addons/1085/better-shine
- Rounded Square Mask: https://www.construct.net/en/make-games/addons/1090/rounded-square-mask

## Steps to reproduce

1. Enable WebGPU
2. Preview

## Observed result
Two things happen that are weird:

1- The angle (or Y axis) is reversed
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/2a8d7108-28c4-4ebe-95bc-24944b9898dc)
(2nd rounded square has been disabled because of issue n°2)

2- There is a black screen and a WGSL error when both squares use the same shaders
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/82b19509-12a1-47cd-b298-a7a254ac7233)
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/f4e9db59-342e-4d13-960f-3e363f5b16e9)

[Texture] usage (TextureUsage::(TextureBinding|RenderAttachment)) includes writable usage and another usage in the same synchronization scope.
 - While validating render pass usage.

[Invalid CommandBuffer] is invalid.
 - While calling [Queue].Submit([[Invalid CommandBuffer]])

## Expected result

The result looks fine when WebGPU is disabled
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/76a5becc-2148-4269-a27a-c7eae0632460)

## More details

It's a particularly complicated issue because the WGSL warning just does not happen when I disabled one of the shines on one of the two rounded squares.

The Y axis issue still happens regardless.

This leads me to believe that:
- The Y axis/angle thing is an issue within the empty shell addon draw code because it does not happen when rendering the bettershine shader on a sprite

- The WGSL error comes from an optimisation that renders multiple instances of an object in a single go if they have the same effects but diff params. Because this just doesn't happen if the effect stack is not the same for both instances.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've been looking in to a bunch of WebGPU issues lately, and I can reproduce this, but it's probably impossible to fix in it's current form - it's just too complex a project. As always we need a minimal repro otherwise it's generally infeasible to fix. Can you create a minimal repro for this? If it only happens with a custom effect, then the project should only use the minimum necessary custom effect to reproduce the problem.

To give you an idea what a total nightmare it is to debug a project like this, here's the WebGPU debug render log for a single frame. If there are more than about 10 entries it quickly becomes essentially impossible to tell what's happening in the engine.

![image](https://github.com/Scirra/Construct-bugs/assets/768723/095e7a26-3cc8-4a60-9565-f40495f11652)

**Comment by skymen** [comment]
Ok, finally got time to look into this some more.

I managed to remove most of the stuff. It seems to be a very weird case of renderer state being broken by my empty shell addon. I have no idea why though because all my addon does here is render a colored square 🤔 

I get this warning
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/b3405c93-70e3-49ab-8377-e38a92a6d22c)

Also, the bug ONLY happens when the texture has an effect. It doesn't happen when drawn with no effect. It doesn't need a custom effect either, I reproduced it with a built in one, so I don't think the actual effect's code matters.

Anything rendered before the first empty shell is rendered correctly. If two empty shells render back to back, and there is nothing to render before it, the screen goes black. If there is anything, that is rendered correctly, and everything after just doesn't render.

BUT if the text object is rendered between the two, the renderer works again........

Now, this issue doesn't happen with Sprite, which is weird because as far as I know my empty shell addon doesn't do anything out of the ordinary. When in color fill mode, it renders a colored square, and when it is in texture fill mode, the process is a copy paste of the sprite's draw code (minus the mesh part) and the issue happens with both modes.

Maybe this is caused by the fact that my empty shell addon doesn't have the "has an image" tag 🤔 ...
....
........
YES THATS IT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
REPRO WITH NO 3RD PARTY STUFF:

[wgsl error minimal repro - Copie.zip](https://github.com/Scirra/Construct-bugs/files/13420641/wgsl.error.minimal.repro.-.Copie.zip)

Steps:
Just change the Z order. Put the text in between the two shadow lights and the issue disappears. This ONLY happens when a world object with no texture associated with it renders stuff with an effect on it in WGSL, twice in a row.

**Comment by AshleyScirra** [comment]
I'm trying to wrap up the last remaining WebGPU issues, and I was finally able to figure out the problem with the WebGPU renderer here from the minimal repro. I verified the fix also works with the original project using third-party shaders - that now renders correctly with WebGPU too. The fix will be in the next release cycle (first beta after the next stable).
