### ISSUE TITLE
Crash when add family custom acions

### ISSUE THREAD

**Issue by thanhcuong90** [Scirra/Construct-bugs#7345]
## Problem description
Add >2 custom actions for family Crash construct 3

## Attach a .c3p
[CatCombat.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12472076/CatCombat.c3p.zip)

## Steps to reproduce

1. Add 1 family with 2 objects
2. Create 1 custom actions
3. Create 2 custom actions 
4. Rename custom actions 2
5. Save file.

## Observed result
Crash the web

## Expected result
Don't crash

## More details

**Affected browsers/platforms:** 
MS Edge

**First affected release:** 
beta r356
## System details

<details><summary>View details</summary>

Product: Construct 3 r356 (beta)
Browser: Edge 116.0.1938.62
Browser engine: Chromium
Context: browser
Operating system: macOS 11.7.2
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.62
Language setting: en-US

</details>

**Comment by AshleyScirra** [comment]
The provided project is not a minimal project (please see the bug report guidelines) and the issue sounds similar to #7321, so closing.
