### ISSUE TITLE
Physics - 0 Density has more Mass than 0.1 Density

### ISSUE THREAD

**Issue by 4demon** [Scirra/Construct-bugs#7346]
## Problem description

If give you a physics object a density of 0 it has more mass than an object with low density.

## Attach a .c3p

[https://1drv.ms/u/s!AlZkRk7KfdFFjdp1M7Ur4zP6zrTCWw?e=J2hFay](url)

## Steps to reproduce

1. Move the slider to change the object's density.

## Observed result

Note the object's mass is 50 when the density is 0

## Expected result

I expected the mass to be 0.

**Comment by AshleyScirra** [comment]
The mass is computed by the Box2D physics engine. However a density of 0 is unrealistic: no real-world physical object can have a zero density (it implies a physical object that is a vacuum or something weird like that). I don't think using such unrealistic cases with a realistic physics engine is worth investigating anyway - the point of the physics engine is to act realistically, and there's no way to do that for a zero density object.
