### ISSUE TITLE
Timeline editor preview for 3rd party addon custom properties not supported

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-bugs#7349]
## Problem description

When doing timeline preview, 3rd party addon custom properties are not supported (preview does not change the properties, even though the appropriate timeline integration in editor and runtime instance.js is done)

## Attach a .c3p
[3DObjectTimeline.zip](https://github.com/Scirra/Construct-bugs/files/12477921/3DObjectTimeline.zip)

## Steps to reproduce

1. Load latest 3DObject addon
https://kindeyegames.itch.io/c3-3dobject-alpha/devlog/582211/runtime-timeline-support-for-angle-and-scale-properties
(I already gave a key for this addon to Ashley, if you need a new one, let me know)
2. Load project
3. Preview timeline1
4. Run project

## Observed result

Timeline preview does not show changes for custom properties (*Angle and *Scale).
Runtime does show changes for custom properties

## Expected result

Preview show changes for custom properties, same as runtime.

## More details

Followed integration instructions, adding functions to editor and runtime instance.js

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
@DiegoScirra - any idea if this is a problem with the addon, a simple oversight, or something not supported that would be a lot of work to add?

**Comment by DiegoScirra** [comment]
So I have been looking at this, and got it working in my development build.

As it turns out there were a few small things missing for 3rd party plugins that produce changes in the layout view when being previewed in a timeline.

**Comment by DiegoScirra** [comment]
A fix for this will become available starting with the next release cycle.

Any plugins that need to preview timeline changes in the layout view  will need to implement the **OnTimelinePropertyChanged(id, value, detail)** method which is pretty much the same as **OnPropertyChanged(id, value)**, but it is called when a timeline is producing changes. The switch statement only needs to care about properties which have been marked to be **"interpolatable"** in the plugin definition.

In that function the plugin needs to update the corresponding internal state, namely using the new **GetTimelinePropertyValue(id)** method from **IObjectInstance** which gets the value of a property with any changes a timeline might be applying to it. After the internal state is updated the plugin should refresh the layout view to view the changes.

Lastly, the plugin should implement the new method **OnExitTimelineEditMode** which is called when timeline edit mode is turned off. In this method the plugin's internal state should be updated again so any timeline changes from the preview are reset. Using **GetPropertyValue(id)** to get values without timeline changes for each corresponding property and refreshing the layout view should be enough.

When the release is made I will post this again in the forums, in case there are changes to the API.

**Comment by MikalDev** [comment]
Thanks Diego, looking forward to the update.

**Comment by DiegoScirra** [comment]
@MikalDev Where can I send you a modified version of your plugin? You don't need to make a lot of changes but it will be easier than trying to figure out what you need to do from that description.

**Comment by MikalDev** [comment]
@DiegoScirra - thanks for the offer, I appreciate it! Ashley should have my email address, you can send it through email or put it up on sendgb.com (w/ a download once option) and _email_ me a link. If there is any issue, let me know. Thanks for the help.
