### ISSUE TITLE
Error when open single .c3p file || Error: Failed to fetch @ TypeError: Failed to fetch

### ISSUE THREAD

**Issue by fachrizalafandi** [Scirra/Construct-bugs#7352]
## Problem description

I don't know what's wrong, because yesterday I opened my project file and it was fine. Today I intend to continue my work on the project, but suddenly the project file cannot be opened.

## Attach a .c3p

[mim-ls14.c3p](https://drive.google.com/file/d/1Z_6Qhukc9k3jA2zoiJXCukheEYRCq878/view?usp=sharing)

## Steps to reproduce

1. open editor.construct.net
2. select menu Open -> File
3. Select the mim-ls14.c3p file.
4. Error appears and the project cannot be opened

## Observed result

Error message and project file cannot be opened.
![image](https://github.com/Scirra/Construct-bugs/assets/78633868/59f44622-3496-4b96-8c7e-5699c73d1cca)

## Expected result

project files can be opened

## More details

I use the same version of construct 3 when the project can be opened, and when the project cannot be opened.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct version: r350
URL: https://editor.construct.net/
Date: Thu Aug 31 2023 09:47:42 GMT+0700 (Western Indonesia Time)
Uptime: 32 s

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.112
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment]
Can not reproduce. I have everything open. 
<img width="960" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/f9a262dc-fb6b-44f2-97d6-4b5a54ecd6bf">

**Comment by fachrizalafandi** [comment]
> Can not reproduce. I have everything open. <img alt="obser" width="960" src="https://user-images.githubusercontent.com/91274932/264633502-f9a262dc-fb6b-44f2-97d6-4b5a54ecd6bf.png">

yes yesterday after I tried to restart my laptop, it finally worked. I don't know what the problem is, but I'm grateful that my project can be opened.
