### ISSUE TITLE
Pathfinding movement not working properly on 2nd layout after placing an instance on 1st layout

### ISSUE THREAD

**Issue by ashconstruct** [Scirra/Construct-bugs#7354]
## Problem description
I've 3 objects with pathfinding behaviour in 2nd layout and they are moving from destination A to B and then B to A. Issue is out of the 3 objects only 1 is properly moving other two are keeps freezing for some seconds at some intervals

Issue is happens only when we place any object on the 1st layout which has pathfinding behaviour. If we delete all the objects which has pathfinding behaviour from 1st layout then there is no issue on 2nd layout

Issue can see only if we start it as preview project or preview 1st layout. If we start it from the 2nd layout preview then we cannot see the issue

## Attach a .c3p
https://drive.google.com/file/d/1tBSjR0x2zRk1aVbXlWH-svPq7FabS4LZ/view

## Steps to reproduce

1. Preview as project or layout preview from 1st layout. Only one instance is there. Didn't assign any movement in 1st layout. Then press M on keyboard to go to 2nd layout
2. In 2nd layout. Issue begins here one object is moving properly other two are keeps freezing for some seconds
3. After this delete instance from 1st layout then check on 2nd layout there is no issue

## Observed result

In 2nd layoutonly one object is moving properly with pathfinding behaviour

Please see the below video of my issue,

https://drive.google.com/file/d/1R_bCtVKlSMphMkGMqB1ucQcTkDKdXPr9/view

## Expected result

All objects are supposed to move without any delay or freezing

## More details

**Affected browsers/platforms:** Android, Chrome, Firefox, Windows

**First affected release:** Not sure from which version has this issue, project started with latest stable 350

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.111
Browser engine: Chromium
Context: browser
Operating system: Windows NT 8.0.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 255 gb
Storage usage (approx): 238 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4000 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by avishaymizrav** [comment]
@ashconstruct You're basically keep looking for a path every 0.5 second, which can cause a lot of overhead cpu and no movement if the calculation is not done in time for the second call.

Try adding these two conditions on your path finding events. This should solve your issue.
isNot calculating path
isNot moving along path

**Comment by ashconstruct** [comment]
Did you delete the instance from 1st layout? As I said in the above details if we delete it from the 1st layout then there is no issue in the 2nd layout. I dont think its an overload  because after deleting the instance from 1st layout I tried with morethan 30 instances in the 2nd layout without any issue

**Comment by AshleyScirra** [comment]
Thanks for the report, this is indeed a complicated issue with the way pathfinding jobs are internally scheduled. It should be fixed in the next beta.
