### ISSUE TITLE
hierarchy and tween breaks with save/load

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7356]
## Problem description
hierarchy and tween breaks with save/load

## Attach a .c3p
[saveLoadHierarchyBreaks.zip](https://github.com/Scirra/Construct-bugs/files/12488807/saveLoadHierarchyBreaks.zip)

## Steps to reproduce

1. start preview
2. click save button
3. click load button

## Observed result
hierarchy breaks, bones of the skeleton are disconnected

## Expected result
hierarchy stays intakt

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
