### ISSUE TITLE
Platformer solid slopes + near Jumpthru = very sluggish jittery movement

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7361]
## Problem description

Moving down a slope with platformer behavior, which has jump thru objects near it, causes really intense slow down and jitter with the movement. 

The player sprite shakes violently and struggles to move through it, moving up and down too.

It becomes even more extremely apparent when there are multiple jumpthrus on top of one another.

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/2606ef73-7d8a-4b23-a6e7-3a8f0f9b61d6)

Thank you for fixing this, would really help my 6 year old project feel much better 💖

ps. I have to have the platforms close to the slopes sometimes

## Attach a .c3p

[jumpthru jitter.zip](https://github.com/Scirra/Construct-bugs/files/12503602/jumpthru.jitter.zip)

## Steps to reproduce

1. walk left and right along the slope

## Observed result

sluggish jittery movement moving through a jump thru platform

It gets worse when there's multiple overlapping

## Expected result

should be able to walk smoothly along the slope as if the jumpThrus weren't even there

## More details

**Affected browsers/platforms:** chrome win

**First affected release:** not sure

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r356 (beta)
Browser: Chrome 116.0.5845.141
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 3.7 gb (1.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_draw_instanced_base_vertex_base_instance
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_multi_draw_instanced_base_vertex_base_instance
WEBGL_provoking_vertex
WEBGL_video_texture
WEBGL_webcodecs_video_frame
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Due to the extreme complexity of the behavior logic, the [jump-thru behavior does not support slopes](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/jump-thru):

> Note the Jump-thru behavior **does not support slopes.** Any slopes in your game should use the Solid behavior instead.

I think this can be considered to extend to jump-thrus intersecting a solid slope, since that is probably even more complicated logic. Do you really, really need this? It is exceptionally difficult to make virtually any changes to the Platform behavior without causing a raft of regressions, many of which are worse than the original problem.

**Comment by alastajj** [comment]
@AshleyScirra 

I appreciate you looking into this! 

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/bcd2d9ce-ebc8-4cd3-90ed-20255cb07733)

>I think this can be considered to extend to jump-thrus intersecting a solid slope,

This doesn't appear to matter that it's intersecting a slope. 

It's just that having solid slopes at all near a jump thru seem to cause issues.

______________

Would it be easier to fix now that you've had more years of experience?

It would definitely improve the quality of my game in some areas. 

But I also understand the difficulties and challenges of attempting to fix it.

Thank you for considering this!

**Comment by AshleyScirra** [comment]
I've looked in to this some more and got a fix in for the next beta. However it is an extremely complicated change that was very difficult to figure out, and we will have to see how it goes with regards to regressions. There is most of the beta release cycle for testing though so hopefully we'll be able to establish how reliable the fix is.
