### ISSUE TITLE
Platform vector Y bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7366]
## Problem description

I have a sprite with a `Platform` behavior. I also have a platform with `Sine` behavior that moves vertically. When the platform starts moving up, the `Set vector Y` action does nothing. It looks like the character is just stuck to the platform.

This works fine in `r337b`, but doesn't work in `r357b`.

## Attach a .c3p

[platform_vector_y_bug_r337b_r357b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12524265/platform_vector_y_bug_r337b_r357b.zip)

## Steps to reproduce

1. Open and run the project.
2. Wait for the platform to move up and press `1` to make the character jump.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/c3d49c27-9caf-47fb-9fab-6415142cf78d

## Expected result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/bbf805a7-bff0-4eaf-b7e6-507a1caf1184

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r357b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r357 (beta)
Browser: Chrome 116.0.5845.141
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 573 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by TomoloGames** [comment]
https://github.com/Scirra/Construct-bugs/issues/7086https://github.com/Scirra/Construct-bugs/issues/7086

Did you see this (last comment) and filed a bug report because I wouldn't do it or is this just a strange coincident?

**Comment by WilsonPercival** [comment]
> #7086
> 
> Did you see this (last comment) and filed a bug report because I wouldn't do it or is this just a strange coincident?

@TomoloGames There are no matches. I actually posted a new report on your issue.

**Comment by TomoloGames** [comment]
> > #7086
> > Did you see this (last comment) and filed a bug report because I wouldn't do it or is this just a strange coincident?
> 
> @TomoloGames There are no matches. I actually posted a new report on your issue.

What do you mean "there are no matches"?

**Comment by WilsonPercival** [comment]
> > > #7086
> > > Did you see this (last comment) and filed a bug report because I wouldn't do it or is this just a strange coincident?
> > 
> > 
> > @TomoloGames There are no matches. I actually posted a new report on your issue.
> 
> What do you mean "there are no matches"?

There is nothing random in the world.

**Comment by TomoloGames** [comment]
Dude, why are you being so cryptic? I've been waiting for this issue to be solved for months and  today I told Ashley it still hasn't been solved (even though he said it had been solved) and not long after that you posted this bug report. I just wanted to know if it was a coincident or not.

**Comment by WilsonPercival** [comment]
> Dude, why are you being so cryptic? I've been waiting for this issue to be solved for months and today I told Ashley it still hasn't been solved (even though he said it had been solved) and not long after that you posted this bug report. I just wanted to know if it was a coincident or not.

No. I'm just going through all the reports that people reply to.

**Comment by TomoloGames** [comment]
Okay, cool =)

**Comment by AshleyScirra** [comment]
This project uses 'Set vector Y' instead of jumping, which is usually not a good idea, as jumping has special logic to handle certain cases, and setting the vector Y does not. In this case merely setting the vector Y does not work with the moving platform tracking code: changing the vector Y stops attempting to follow the moving platform since it only tries to do that while the player is stopped; that leaves it intersecting the platform, and it runs in to the fix for bug #6852 which resets the vector Y to 0 to properly handle landing on a moving platform. So it basically handles this as "stop following the moving platform, but then instantly land on it again, which resets vector Y".

I don't think there's a good fix for this, and meanwhile a better approach is to use the actual jump logic which handles this kind of thing properly. So as a workaround, set the jump strength to 1000 and simulate a jump, instead of setting the vector Y to -1000.

**Comment by TomoloGames** [comment]
> This project uses 'Set vector Y' instead of jumping, which is usually not a good idea, as jumping has special logic to handle certain cases, and setting the vector Y does not. In this case merely setting the vector Y does not work with the moving platform tracking code: changing the vector Y stops attempting to follow the moving platform since it only tries to do that while the player is stopped; that leaves it intersecting the platform, and it runs in to the fix for bug #6852 which resets the vector Y to 0 to properly handle landing on a moving platform. So it basically handles this as "stop following the moving platform, but then instantly land on it again, which resets vector Y".
> 
> I don't think there's a good fix for this, and meanwhile a better approach is to use the actual jump logic which handles this kind of thing properly. So as a workaround, set the jump strength to 1000 and simulate a jump, instead of setting the vector Y to -1000.

How come it works in previous versions but not now? How can we use coyote-jumps and triple jumps if we can't use Vector Y?
