### ISSUE TITLE
Crash when closing the Ease editor

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7368]
## Problem description

Crash when closing the Ease editor.

## Attach a .c3p
(New Project)

## Steps to reproduce

1. Add a sprite
2. Add it to timeline
3. Click the track
4. Open ease editor from the property window
5. Confirm the message dialog
6. Close the ease editor

## Observed result

Crash

## Expected result

No crash

## More details

**Affected browsers/platforms:** Chrome (desktop app)

**First affected release:** stable

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Q.i (https://editor.construct.net/r350/main.js:1059:147) at d.qxc (https://editor.construct.net/r350/main.js:1186:255) at d.uAa (https://editor.construct.net/r350/projectResources.js:1316:274) at https://editor.construct.net/r350/components/bars/propertiesBar/propertiesBar.js:65:362
Stack: TypeError: unexpected type at Q.i (https://editor.construct.net/r350/main.js:1059:147) at d.qxc (https://editor.construct.net/r350/main.js:1186:255) at d.uAa (https://editor.construct.net/r350/projectResources.js:1316:274) at https://editor.construct.net/r350/components/bars/propertiesBar/propertiesBar.js:65:362
Construct version: r350
URL: https://editor.construct.net/
Date: Wed Sep 06 2023 06:42:59 GMT+0300 (Eastern European Summer Time)
Uptime: 21.5 s

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.141
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.375
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 6GB Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment]
@Alaadel I think you are referring to this bug: https://github.com/Scirra/Construct-bugs/issues/7129

I can repeat the crash on HP windows 7, but I can't on Asus windows 11.

**Comment by DiegoScirra** [comment]
Still can't reproduce this one.
