### ISSUE TITLE
Project Exported to Windows (WebView2) broken by "Set Text to" with too many characters and Array data.

### ISSUE THREAD

**Issue by SPECT0R1A** [Scirra/Construct-bugs#7369]
## Problem description

When exporting a project to WebView2 (64-bits), if this project has too many characters in a text object linked to an Array -> black screen.

## Attach a .c3p

[BUG_CONSTRUCT_3_06092023.zip](https://github.com/Scirra/Construct-bugs/files/12539905/BUG_CONSTRUCT_3_06092023.zip)

## Steps to reproduce

1. Create a 3D Array. For example size Width: 8, Height: 3, Depth: 7
2. Create a Text Object.
3. Create Event: Every Tick: Set Text to: Array.At(0,0,0)&" | "&Array.At(1,0,0)&" | "&Array.At(2,0,0)&" | "[...]&newline,Array.At(0,1,0),etc...
4. The goal is to display the array lines and be able to view the array in real-time in a text looking like this:

| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 |

The text is supposed to display the first "face"(Depth 1) of this 3D array.

## Observed result

Black screen when starting the project.

## Expected result

Project to launch and display the text. (Works fine when exported to NW.js. I need WebView export because contrary to NW.js I can launch the same .exe multiple times, in order to test multiplayer.)

## More details

At first I thought this would be a limitation of the number of characters at around ~5000ish, so I tested with a +6000 characters text. No issue. The issue seems to be only when retrieving data from an array and the overall text has more than ~5000 characters.
Temporary solution that works is to use "Append text" in a second event, dividing the text in two events.

**Affected browsers/platforms:** 

Tested with r350 Stable and latest Construct Beta r357.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 116.0.5845.142
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.2 gb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by SPECT0R1A** [comment]
Just found how to open multiple preview windows for testing multiplayer... Feeling dumb. I had been exporting all this time.
But issue with getting a black screen still remains. I tested another thing, tried to disable BBC Code in Text object, just to check: no change.

**Comment by AshleyScirra** [comment]
The error in WebView2 is `RangeError: Maximum call stack size exceeded`. So it appears to be such a long expression that it is running in to the limit of how many JavaScript calls are allowed.

I don't see any reason to further investigate or fix this: the expression would far more easily be made with a loop. It would be much more convenient, quicker to set up as you won't have to type out absolutely everything, and not have this problem, so you should just do that.
