### ISSUE TITLE
Animation preview won't close if over marquee selection

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7371]
## Problem description

In the Animations editor, if the animation preview window is over a marquee selection, the preview window doesn't respond to mouse clicks.

I think the mouse is stuck; it's reacting as if it's over a marquee selection, instead of reacting to the preview window buttons (restart, X to close). Thus the window can't be closed with the mouse.

Pressing ESC to close the Preview still works, as does clicking outside the sprite's boundaries to deselect the marquee. I only realized this the second time it happened; initially i had to restart construct and lose my work.

## Attach a .c3p

(make a new project)

## Steps to reproduce

1. Create a sprite object.
2. Open the sprite in the animations editor.
3. Make sure the zoom level is big enough that the animation preview window will be overtop of the image. 
4. Press cmd/ctrl + A to select the whole image.
5. Press the Preview button.

## Observed result

The cursor is stuck in 'move selection' mode. The preview's X and restart buttons can't be clicked.

## Expected result

The preview's X and restart buttons work as they do when no selection is made.

## More details

**Affected browsers/platforms:** Chrome, MacOS, Ventura

**First affected release:** 357.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed when the new release cycle starts.
