### ISSUE TITLE
Holding ESC closes the animation preview and the Animation Editor

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7372]
## Problem description

If you press ESC for too long during an animation preview, the whole Animations Editor will close as well.

## Attach a .c3p

(make a new project)

## Steps to reproduce

1. Create a sprite object.
2. Open the sprite in the Animations Editor.
3. Press the Preview button.
4. Hold ESC.

## Observed result

The Preview window closes (as it should), but then a moment later, the Animations Editor closes too.

## Expected result

The Animations Editor shouldn't close because ESC is held down. A new 'close window' request should require a new pressing of the ESC button.

## More details

**Affected browsers/platforms:** Chrome, MacOS, Ventura

**First affected release:** 357.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed when the next release cycle starts.
