### ISSUE TITLE
timeline initial animation keyframe doesn't play the animation

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7374]
## Problem description
The timeline initial animation keyframe doesn't play the animation if the first animation isn't playing

## Attach a .c3p
[initialAnimationNotPlayingTL.zip](https://github.com/Scirra/Construct-bugs/files/12552151/initialAnimationNotPlayingTL.zip)

## Steps to reproduce

1. watch the preview

## Observed result
sprite animation of the timeline doesn't play

## Expected result
sprite animation of the timeline does play

## More details
**It seems like it only works if the animation that came before played/has multiple frames**.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
