### ISSUE TITLE
inconsistent and confusing property naming

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7375]
## Problem description
Some properties start with "initial", which sounds very confusing if you are animating that property via timelines. For example "initial animation" and "initial frame" sounds incorrect in this context. And these are very heavily used properties to animate if you do a mixture of timeline and frame by frame animation. 
I'd just rename it to "animation", as that works for both the timeline and normal properties. The same for "initial frame" and "initially visible". The "initial" should just be removed from everything, also all the other properties like "size", "position" don't use "initial size" or "initial position" so it would also be more consistent.

## Observed result
properties are named:
- "initially visible"
- "initial animation"
- "initial frame"

## Expected result
- "visible"
- "animation"
- "frame" or "animation frame"

**Comment by AshleyScirra** [comment]
I sort of agree about the general point (although the "initial" naming is correct if you disregard timelines, as it's the value it starts with). However changing such core long-standing terminology is extremely costly in terms of literally years worth of ensuing confusion as reams of documentation, tutorials, lesson plans and so on become out of date and need updating, and in practice they won't be, so it just makes a big mess. I don't think the usability benefit of perhaps slightly better names outweighs the costs of changing the basic terminology of core features, so I don't think we should actually change this.
