### ISSUE TITLE
preview is broken if the timeline is set to start on a layout and the TimelineController has been deleted

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7376]
## Problem description
preview is broken if the timeline is set to start on a layout and TimelineController has been deleted

## Attach a .c3p
[deleteTimelineManagerCrash.zip](https://github.com/Scirra/Construct-bugs/files/12552506/deleteTimelineManagerCrash.zip)

## Steps to reproduce

1. start preview

## Observed result
black screen and error message: caught (in promise) TypeError: Cannot read properties of undefined (reading 'Cnds')

## Expected result
Construct either 
- doesn't allow deleting the timeline controller in that case
- doesn't try to start the timeline/removes that property
- at least gives a better error message i.e. "timelineController is missing"

## More details
side note: if you delete the audio object everything still works just the audio doesn't play. So there that similar case is handled correctly.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
It seems to be similar to this https://github.com/Scirra/Construct-bugs/issues/7373

**Comment by F3der1co** [comment]
oh yea, sounds like the same issue. I'll still keep this one open as I think this one has tracked down the cause.

**Comment by DiegoScirra** [comment]
Will be fixed on the next beta by just preventing the runtime crash. If the plugin is not present it's not really a problem, it's just added to begin with as a small convenience in case you want to set up some events.
