### ISSUE TITLE
Construct crashes when selecting font for text object

### ISSUE THREAD

**Issue by yeoji** [Scirra/Construct-bugs#7378]
## Problem description

When trying to select a font for a text object, Construct crashes almost always with the message `ResizeObserver loop completed with undelivered notifications.`

Crash logs are pasted below.

## Attach a .c3p

[project.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12558017/project.c3p.zip)

## Steps to reproduce

1. Open the project
2. Click on the text object
3. Under properties, select `Font`

![Screenshot 2023-09-08 at 7 45 06 pm](https://github.com/Scirra/Construct-bugs/assets/8002179/d9cc8c4f-0cab-4b92-9439-6638a7a271a2)

## Observed result

Construct crashes

![image](https://github.com/Scirra/Construct-bugs/assets/8002179/b74c1001-d352-4e61-96e5-7ab3c2567bce)

## Expected result

I should be able to select a font and Construct should not crash

## More details

**Affected browsers/platforms:** 
Chrome, macOS

**First affected release:** Not sure, I'm new to Construct

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/, line 0, col 0
Message: ResizeObserver loop completed with undelivered notifications.
Stack: null
Construct version: r350
URL: https://editor.construct.net/
Date: Fri Sep 08 2023 19:26:34 GMT+1000 (Australian Eastern Standard Time)
Uptime: 90.3 s

Platform information
Product: Construct 3 r350 (stable)
Browser: Chrome 115.0.5790.170
Browser engine: Chromium
Context: webapp
Operating system: macOS 13.4.1
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 10
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, Apple M1 Max, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 64
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7241

**Comment by yeoji** [comment]
Thanks @WilsonPercival, I had the Lastpass extension installed. Blocking it on the Construct editor resolved the issue.

**Comment by AshleyScirra** [comment]
@yeoji - please report this issue to the Lastpass extension developers.
