### ISSUE TITLE
Quote array editor bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7383]
## Problem description

When I copied and pasted the cell, the quote disappeared.

## Attach a .c3p

[quote_array_editor_bug_r357_2b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12566399/quote_array_editor_bug_r357_2b.zip)

## Steps to reproduce

1. Open a project.
2. Open `Array editor`.
3. Copy the first cell.
4. Paste into the second cell.

## Observed result

<img width="323" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/7a5f01f0-0809-4578-b5e3-37a0fbb2445c">

## Expected result

<img width="319" alt="expected" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/41aeb4b3-107e-490e-9834-505b9c2ee7c8">

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r357-2b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r357.2 (beta)
Browser: Chrome 116.0.5845.180
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 606 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Seems to work fine for me. Perhaps you have some browser extension that is interfering.

**Comment by WilsonPercival** [comment]
> Seems to work fine for me. Perhaps you have some browser extension that is interfering.

@AshleyScirra The only extension I have is an ad blocker. I demonstrated the bug in the incognito tab. Can you make sure you are not exposing the contents of the cell? Everything works fine if you open the cell. But the quote disappears if you simply copy the cell without opening the contents.

https://github.com/Scirra/Construct-bugs/assets/91274932/cdb780e7-d14d-4909-b5f0-952d7663504d

**Comment by XHXIAIEIN** [comment]
I can reproduce this, let me give a clearer description:

## Problem description
If paste the 'CELL' directly into another cell, the quotation marks may not be escaped correctly.

When select a cell, the JSON data in the array editor is copied.
(Just select the cell. no edit.)

```
"{"a": "",
"b": ""}"
```

And The content of the cell is actually like this.   
(Double-click the cell. enter edit input)
```
{"a": "",
"b": ""}
```

Notice the placement of their quotation marks.

However, pasting cells directly may cause the quotation marks of the data to be escaped incorrectly. It may be a problem with regular expression processing
