### ISSUE TITLE
The Tile Movement Behavior's "simulate control" action won't work at start of layout.

### ISSUE THREAD

**Issue by AndreYin** [Scirra/Construct-bugs#7386]
The Tile Movement Behavior's "simulate control" action won't work at start of layout

https://1drv.ms/u/s!AuQM7MihYyx4s4ozw6wcFHVYQg3pjA?e=MVYd5X

## Steps to reproduce

1. Create a new project
2. Create a sprite and add Tile Movement behavior to it
3. Create a "On Start of Layout" event, with a "Sprite -> Simulate Tile Movement control" to any direction

The sprite doesn't move.

The sprite object should move as soon as the layout starts.

All browsers

I'm not sure how to test for that, but it worked in the first release that had the Tile Movement (r122).

<details><summary>View details</summary>

Platform information
Product: Construct 3 r355 (beta)
Browser: Opera GX 101.0.4843.74
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 OPR/101.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 268 gb
Storage usage (approx): 167 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 96000 Hz
Output channels: 8
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This appears to be a mistake in your events. 'Simulate control' only takes effect for one tick - normally you use it with a condition like "key is down" so it continually applies. Your logic applies the control for a single tick, waits for 1 second, then applies the control for a single tick again. You probably want something more like "Time < 1 second: simulate control".

**Comment by XHXIAIEIN** [comment]
If I add wait 0.01 in front then it works
![Snipaste_2023-09-16_13-22-32](https://github.com/Scirra/Construct-bugs/assets/45864744/d67a24ee-de47-42de-8d12-e0a30a1868a7)
