### ISSUE TITLE
My construct 3 project wont open

### ISSUE THREAD

**Issue by Mewantmods** [Scirra/Construct-bugs#7389]
## Problem description

 My construct 3 project wont open it just says not a construct 3 file when it is a construct 3 file.
## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Try pressing F12 to bring up the developer tools and see what messages are printed to the console.

Does your project still work with the previous stable release?

**Comment by AshleyScirra** [comment]
This issue is not actionable and our policy is to close such issues. Please follow the bug report guidelines and at least share your project file.
