### ISSUE TITLE
Crash: clicking play audio button multiple times 

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7392]
with audio play at position window, I clicked the "play" button multiple times quickly by accident and it crashed the editor

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/36442eae-dfc8-4cbf-9858-b6f4736efc86)

Error report information
Type: unhandled rejection
Reason: Error: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
Construct version: r358
URL: https://editor.construct.net/
Date: Sat Sep 16 2023 18:31:40 GMT+1000 (Australian Eastern Standard Time)
Uptime: 7684.1 s

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 116.0.5845.188
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_provoking_vertex, WEBGL_video_texture, WEBGL_webcodecs_video_frame

**Comment by WilsonPercival** [comment]
It's very difficult to repeat. I get it 3 times out of 10.

https://github.com/Scirra/Construct-bugs/assets/91274932/2f27256a-614b-4a06-8342-ff161bc4daec

**Comment by alastajj** [comment]
thank you for helping to confirm!

**Comment by AshleyScirra** [comment]
No project was provided so I tried Space Blaster. I clicked the play button as fast as I possibly could for some of the 'Play sound' actions and no crash occurred. Can you find a more reliable way to reproduce this? It is difficult to do anything if we cannot reproduce it.
