### ISSUE TITLE
IOS crash when erroneously exceeding VRAM limit by unloading & loading images simultaniously (possible fix / improvements needed)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7394]
On IOS, a Construct 3 application loading/releasing great amounts of VRAM can lead to the webview reloading (appearing as a crash) when switching scenes if the application exceeds the memory limit of IOS during the loading process or if the main thread of the webview maxes out at 100%. This can happen with the use of custom loading actions, however, can also happen with "Go To Layout", but just rarely. 

EDIT: After further analyzing, the webview reloads are directly tied to the performance. It seems that during heavy loading, the CPU maxes out and no new frames are being generated for a short amount of time, which causes the WebView to reload. 

In Construct 3, there currently is no way to reduce the loading speed when using these actions (which ones is explained under the steps to reproduce) or use some kind of lazy loading. Second, Construct 3 should ideally react to the memory warnings and unload unused assets before loading the new ones on a scene switch. Third, there might be the option to use the `WKSuspendInBackground preference for iOS that prevents your web view from reloading when process is at its limit.` according to this [thread](https://github.com/ionic-team/cordova-plugin-ionic-webview/issues/337) on the ionic bug tracker (which uses Cordova as well) to prevent the webview from reloading, though I'm not sure if this is even relevant for Construct, but the error is the same one. 

Here is a video of how that could look like (this is my own project, not the test project): 
https://github.com/Scirra/Construct-bugs/assets/80539587/8a710131-23c4-4854-8b01-bb961e80118f

The issue is not prevalent on Android / chrome webview, even with phones that have under 2GB of ram. 

## Attach a .c3p
Granted, this is quite an extreme example, yet, according to the project statistics, this game "only" takes up a max. of 780mb of vram which should not lead to a crash (and when using this with regular loading, it works most of the time). I cannot upload the c3p directly as it exceeds the 25mb limit of github. I uploaded it as a zip file to dropbox (needs to be renamed to c3p), it is around 75mb big. If it does not load at all on your test device, reduce the number of images. However, the Crash message is the same. 

[Dropbox](https://www.dropbox.com/scl/fi/3mx9ndx8elnf1o0m94dtl/Construct3VramTestLoadingIssue.zip?rlkey=em0255x83s9pdxwu90yw33tao&dl=0)

## Steps to reproduce

1. Create a Construct 3 project with around 600-700mb of images (when in vram, not as compressed files) in Construct 3
2. Create 3 layouts, two with a large amount of images (at least 500mb) and one that will serve as a loader layout for one of them. Note: the crash sometimes happens when simply using "Go to Layout" as well, but is easier to replicate with this setup.
3. Use the actions "unload unused images from memory" as well as "Load layout images into memory" in the event sheet of the loader layout. On Start of the layout -> Load layout images into memory. Now, we do not want to instantly switch once the loading was complete, therefore we set a boolean to true once the loading has finished and if that boolean is true, switch to the layout. I also added some tweens and destroy actions here to stress the CPU more. 
4. Export the Project to Xcode (do not deduplicate images or recompress them) and you might need to install the pods manually (for some reason I always have to, even if I'm not using any addons)
5. When you now switch from the first layout with many images to the loader layout which will then send you to the second layout once everything is loaded, a crash _can_ happen. If you repeat this often, it is very likely to crash sometimes. I also sometimes get a crash when loading the application. 

## Observed result

The vram limit is being exceeded or the main thread of the webview maxes out at 100% and the application crashes. This is because likely around 1 gigabyte of vram is being used, which should not be the case. When regular construct loading is being used, this does only happen sometimes. 

## Expected result

The storage should be allocated smoothly and there should not be a spike in vram usage that leads to a crash. 

## More details
This is how the Xcode crash message looks like:

2023-09-16 19:57:55.404378+0200 Bluelife[3284:194440]
[Process x10d004350 - [PID=3445]
WebProcessProxy: :didClose: (web process 0 crash)
2023-09-16 19:57:55.404500+0200 Bluelife3284:194440]
[Process] 0x10d004350 - [PID=3445
WebProcessProxy::processDidTerminate0rFailedToLaunch:
reason=Crash
2023-09-16 19:57:55.404579+0200 Bluelife[3284:194440]
[ProcessSuspension] 0x10c01dfe - ProcessAssertion:
Failed to acquire RBS Background assertion
'XPCConnectionTerminationWatchdog' for process because
PID 0 is invalid
2023-09-16 19:57:55.410251+0200 Bluelife[3284:194440]
[Process] 0x130856218 - [pageProxyID=14, webPageID=15,
PID=3445] WebPageProxy: :processDidTerminate: (pid
3445), reason=Crash
2023-09-16 19:57:55.411392+0200 Bluelife[3284:211863]
[ProcessSuspension] 0x10c01dfe -
ProcessAssertion::acquireSync Failed to acquire RBS assertion 'XPCConnectionTerminationWatchdog' for process with PID=0, error: (null)
2023-09-16 19:57:55.424321+0200 Bluelife[3284:194440]
[Loading] 0x130856218 - [pageProxID=14, webPageID=15, PID=3445] WebPageProxy::dispatchProcessDidTerminate:
reason=Crash

## System details

IOS 16.6, running on iPhone 11 Pro. 
All Construct releases are affected.

**Comment by AshleyScirra** [comment]
I'm afraid I don't believe there is anything we can do about this on Construct's side. Browsers do not give web pages precise control over memory usage. When it comes to GPU resources we can and do destroy resources instantly as per the load/unload actions. However I think the precise moment memory is released depends on the browser engine and the garbage collector. So I believe Construct is already doing everything it can; if the browser or GC doesn't respond fast enough perhaps it risks an out-of-memory crash, but that is beyond our control and something the browser maker needs to fix.

So I think you will need to report this issue to Apple here: https://bugs.webkit.org/
Alternatively, try to reduce the overall memory usage of your project.

**Comment by therealPaulPlay** [comment]
The issue is also happening with projects that use less memory overall, but less often. I realized that it happens a lot more frequently when the device is getting hot and cpu usage spikes, so I assume it is more likely to be caused by the main thread being at 100% and no new frames being generated for too long. I‘ll report it to Apple, but I think if there was an option in Construct to load images at a slower pace to still allow for rendering ~20fps it would not happen. It only happens when the frames drop to zero during loading for around 0.2-0.3s. This would also be beneficial for animated loading screens so that they don‘t lag.

**Comment by therealPaulPlay** [comment]
I've investigated it further, and the crash actually happens when you just use "unload unused images" as well. So it can't be a vram limit, it must be something else.

**Comment by therealPaulPlay** [comment]
https://bugs.webkit.org/show_bug.cgi?id=261685

**Comment by therealPaulPlay** [comment]
Thank you for providing your expertise to get this issue resolved :) 
I‘ve actually worked on the construct project a bit to get it to crash more often and reduced the number of images so it now uses around 500-600mb as I realized that the crash percentage didn‘t decrease by doing that. I‘ve done things such as put a Wait 0 seconds between the unload unused images and load layout images so that the tween animations and text set actions trigger before the layout has been loaded + a few other changes as well. I‘ve attached the xcode project to the webkit report, but I can update the construct project if necessary.
You are totally right with the point that you made, even if there is a way to get exact performance numbers from ios and reduce loading speed accordingly it would still not solve the actual issue and be a workaround that probably doesn‘t work 100% of the time…

**Comment by hightouch67** [comment]
Seems like this issue is still not solved. Random crashes at loading/unloading resources makes it impossible to use WebKit for iOS.

**Comment by mikecann** [comment]
I totally agree :(

**Comment by AshleyScirra** [comment]
Please continue to contact Apple about this since as best as we can tell only they can fix this issue.

**Comment by hightouch67** [comment]
> Please continue to contact Apple about this since as best as we can tell only they can fix this issue.

I did it myself but it does not look like they want to take action, so what's the point to continue... we now managed it by reducing a lot of assets loading and by decreasing the ram usage, but we shouldn't have to pull out our hairs for something like this and even more when a project is consistent and require lot of assets. And this should be added to the official resources of c3. We lost a lot of time before understanding why we had those random crashes.

**Comment by therealPaulPlay** [comment]
I agree, yes. A feature I've suggested a few times is where you can downsize images on export, that would be awesome (or in the editor, in a simple way).

I've noticed that when the application stays below ~400MB ram usage at all times, it doesn't crash. However, when you make a game for mobile + PC, you don't want low-resolution assets. Moreover, downsizing images is very time consuming because they then change size on the canvas.

**Comment by therealPaulPlay** [comment]
I made a new, more specific feature request. Feel free to give it an upvote if you think this easier way of downsizing images could be beneficial to prevent exceeding the VRAM limit.

>> https://github.com/Scirra/Construct-feature-requests/issues/358
