### ISSUE TITLE
CONSTRUCT 3 EDITOR BROKEN AFTER UPDATE TO 358 STABLE !!!

### ISSUE THREAD

**Issue by devktv** [Scirra/Construct-bugs#7395]
## Problem description

Hello. After update editor not work, if i try do reset layout or choose variable or set text and other manipualtion. All is broken

## Steps to reproduce

1. Just create new project or use any other
2. Try add action - Restart layout, choose variable or set text for text element
3. Run project and you not see any changes, edit not working now

## Observed result

Im not see any changes after changes in project

## Expected result

Now construct 3 is broken - impossible work with C3
There is a feeling that changes are not made to the project and when it starts viewing the changes are not visible

## More details

**Affected browsers/platforms:** 
Windows, Chrome

**First affected release:** 
358 STABLE

## System details
Windows 10 Pro

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@devktv  Can you try on an incognito tab? If the problem is present in incognito, could you record a video demonstrating the problem?

**Comment by AshleyScirra** [comment]
It all seems to be working fine for me, and I haven't seen any similar complaints from other users. It looks like the same thing as was posted to the forum here, where I already replied with some things to try: https://www.construct.net/en/forum/construct-3/general-discussion-7/construct-editor-broken-178704

**Comment by devktv** [comment]
All is work. Problem in cache after update. Sorry for this and thank you for your time.
