### ISSUE TITLE
Particles not rendering correctly in WebGPU

### ISSUE THREAD

**Issue by IdeasPerSecond** [Scirra/Construct-bugs#7396]
## Problem description

When trying to use effects on particle objects, such as Set Color or Glow, with the new WebGPU render, the particles don't render, or render with severe artifacts. I have observed this issue effect other sprites that would normally render just fine.

## Attach a .c3p
[WebGPU Artifacts.zip](https://github.com/Scirra/Construct-bugs/files/12641916/WebGPU.Artifacts.zip)

## Steps to reproduce

1. Enable WebGPU
2. Enable any effect
3. Preview

## Observed result

I would expect the particles to render, but after enabling any effect, they simple do not show up.

## Expected result

Switching off WebGPU results in the particles working as intended, with the effects correctly applied and rendered.

## More details

I have attempted to apply effects to particles in other projects, and they don't render or render in such a way as to effect the rendering of other sprites in the layout.

Curiously, if the latest Construct Editor uses WebGPU by default, the effect correctly renders in the preview of the editor.

**Affected browsers/platforms:** 
Chrome
Desktop Exports

**First affected release:** 

First noticed this issue in r358 stable

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 116.0.5845.188
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 2.6 gb (0.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Everything seems to appear normally for me with WebGPU rendering. The particles appear, and I can't see any obvious difference to rendering with WebGL mode. My best guess is this is a graphics driver problem. Are your drivers up-to-date? Are you using any beta/pre-release drivers or have you altered their configuration at all?

**Comment by WilsonPercival** [comment]
> Everything seems to appear normally for me with WebGPU rendering. The particles appear, and I can't see any obvious difference to rendering with WebGL mode. My best guess is this is a graphics driver problem. Are your drivers up-to-date? Are you using any beta/pre-release drivers or have you altered their configuration at all?

@AshleyScirra Yes, the project in the report works fine for me too.

But I created my own and it doesn't work. Please check it.

[issue7396.zip](https://github.com/Scirra/Construct-bugs/files/12648035/issue7396.zip)

**Comment by AshleyScirra** [comment]
I can reproduce particles not appearing in WebGPU mode with that project.

**Comment by IdeasPerSecond** [comment]
My mistake! I forgot to enable the effects in the example project.

**Comment by WilsonPercival** [comment]
@AshleyScirra Particles will be visible if you place a sprite under them:

[issue7396_background.zip](https://github.com/Scirra/Construct-bugs/files/12837723/issue7396_background.zip)

**Comment by AshleyScirra** [comment]
Other variants to check: #7446, #7447

**Comment by AshleyScirra** [comment]
Fixed for next beta, along with #7447 which was the same underlying issue. Issue #7446 appears to be different though so reopened that one.
