### ISSUE TITLE
Near and Far distance doesn't work with WebGPU on.

### ISSUE THREAD

**Issue by 3hue3** [Scirra/Construct-bugs#7405]
## Problem description

The Near/Far distance from camera does not work with WebGPU enabled.

## Attach a .c3p
[nearfardistancebug.zip](https://github.com/Scirra/Construct-bugs/files/12665721/nearfardistancebug.zip)

## Steps to reproduce

1.Run game and see near/far working.
2.Turn on WebGPU
3.Run game again and see near/far are not working.

## Observed result
Near/Far are being ignored.

## Expected result

For it to work with WebGPU on.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I suspect this is related to #7419, as the way fog effects work also depend on the near/far distance.

**Comment by AshleyScirra** [comment]
Fixed for next beta.
