### ISSUE TITLE
Cannot read properties of null on tileset interaction

### ISSUE THREAD

**Issue by benjaboyy** [Scirra/Construct-bugs#7406]
## Problem description

After i had made a copy of tileset 3, every tileset makes the engine crash if i tried to draw something.
A other backup from before this copy works fine.

## Attach a .c3p

[AirForceInterstellarbackup.zip](https://github.com/Scirra/Construct-bugs/files/12666595/AirForceInterstellarbackup.zip)

## Steps to reproduce

1. Open project
2. Click on Tilemap_level_9 that is in the current view
3. Try to draw, select, fill ect... (all crash)

## Observed result

Crash

## Expected result

Draw, select ect....

## More details

On all my pc's
On all Tilesets

**Affected browsers/platforms:** 

**First affected release:** r358 and r359

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r358/components/bars/tilemapBar/tilemapBar.js, line 117, col 94
Message: Uncaught TypeError: Cannot read properties of null (reading 'addEventListener')
Stack: TypeError: Cannot read properties of null (reading 'addEventListener') at window.el.hxc.v_a (https://editor.construct.net/r358/components/bars/tilemapBar/tilemapBar.js:117:94) at CCG.ba.HXb (https://editor.construct.net/r358/components/bars/tilemapBar/tilemapBar.js:73:320) at CCG.Qh.g.ib.dispatchEvent (https://editor.construct.net/r358/main.js:1258:42) at Xq.g.K.gk.zka.g3 (https://editor.construct.net/r358/main.js:1738:254) at Xq.g.K.gk.zka.Vvb (https://editor.construct.net/r358/main.js:1739:121) at https://editor.construct.net/r358/main.js:402:49
Construct version: r358
URL: https://editor.construct.net/
Date: Tue Sep 19 2023 23:27:55 GMT+0200 (Central European Summer Time)
Uptime: 80.5 s

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 117.0.5938.88
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 750 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex
</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
