### ISSUE TITLE
On r359, Music is broken on all games if exported using Webview2

### ISSUE THREAD

**Issue by 3hue3** [Scirra/Construct-bugs#7407]
## Problem description

Music does not work with webview2 on latest beta

## Steps to reproduce

1.open any example with music
2.export with webview2
3.see that it doesn't work

## Observed result
music broken

## Expected result
music works

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@3hue3 Can not reproduce. Everything works fine for me.

https://github.com/Scirra/Construct-bugs/assets/91274932/0cf10de9-26c7-44ef-b4da-1c4bd0c85246

**Comment by 3hue3** [comment]
@WilsonPercival 

Look at Demonoire, try exporting that game. The music does not play at all on webview2 export. The sound effects work fine.

**Comment by 3hue3** [comment]
Edited to *music and not audio.

**Comment by WilsonPercival** [comment]
@3hue3 Yes, the music is not playing.

<img width="960" alt="observed" src="https://github.com/Scirra/Construct-bugs/assets/91274932/e366bea7-3c9d-4fb9-b524-2abc3655b201">

**Comment by AshleyScirra** [comment]
Minimal project since as the bug report guidelines say we always need one: 
[issue7407.zip](https://github.com/Scirra/Construct-bugs/files/12675304/issue7407.zip)

That does reproduce the issue for me.

**Comment by AshleyScirra** [comment]
Fixed for the next beta. (There was an accidental regression when doing updates to support the new extension system in r359.)
