### ISSUE TITLE
Tag count and position functions don't work on Sprite font

### ISSUE THREAD

**Issue by johnBrink** [Scirra/Construct-bugs#7408]
## Problem description

I am trying to use the TagCount, TagX, TagY, TagWidth, and TagHeight properties of a Sprite font object. However, when I try this, all of these properties/functions return 0 even when I have matching tags.

I was able to reproduce this in the built-in "BBCode Tag Ranges" example.

## Attach a .c3p

[sprite font tag example.zip](https://github.com/Scirra/Construct-bugs/files/12667123/sprite.font.tag.example.zip)

## Steps to reproduce

1. Open the provided project file (which is edited from an official example)
2. Run the project.
3. Open the browser console.

## Observed result

The Text and SpriteFont objects should have a red and blue dot, respectively, at the top-left of their tagged area. The console logs should show the locations of these dots in the console.

## Expected result

The Text object behaves as expected, but on the SpriteFont object, the functions all return 0 and the blue dot appears at the top-left of the screen.

## More details

**Affected browsers/platforms:** Tested on Chrome 116.0.5845.190, Windows 10

**First affected release:** I have only tried this in v358

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 116.0.5845.190
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 280 gb
Storage usage (approx): 3.5 gb (1.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
It seems to be similar to this: https://github.com/Scirra/Construct-bugs/issues/7276

**Comment by johnBrink** [comment]
Ah, I see. Calling the event again some time after the start of the layout does in fact work. It's a tad inconvenient for a workaround, as this means players might see a flash as my styling appears.

Did the fix not get incorporated into the latest stable release or did it not work in all cases?

**Comment by WilsonPercival** [comment]
> Ah, I see. Calling the event again some time after the start of the layout does in fact work. It's a tad inconvenient for a workaround, as this means players might see a flash as my styling appears.
> 
> Did the fix not get incorporated into the latest stable release or did it not work in all cases?

I think it's the latter.

**Comment by AshleyScirra** [comment]
I thought I fixed this at the same time as #7276, but it turns out the SpriteFont case is more complicated. It should be fixed in the next beta.

**Comment by johnBrink** [comment]
Thanks for the quick turnaround! I'll keep an eye out for this in the next release.
