### ISSUE TITLE
Example browser:  copy direct link can contain beta release

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7409]
## Problem description

Currently, the Example browser can copy the link to the example through the context menu.
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/3fabad87-173c-4862-9e99-848fdef0702e)

But if the example is added to the Beta, then this link cannot be opened.
```
https://editor.construct.net/#open=rpg-encounter
```

Only the specified release can be accessed correctly
```
https://editor.construct.net/beta#open=interior-designer
```

## Steps to reproduce

1.
2.
3.

## Observed result

```
https://editor.construct.net/#open=rpg-encounter
```

## Expected result

If copy in beta, include the beta
```
https://editor.construct.net/beta#open=interior-designer
```

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I don't think this is worth fixing - the feature is mainly there for us to provide shortcuts on the website, documentation and such and those only ever refer to the latest stable release. I don't think it's worth having a link to open an example in a beta release, as it will always lead to the latest beta release and never update to open in a stable release, even when the project becomes available in the stable release. So - just wait for the next stable release to link to new examples.
