### ISSUE TITLE
Mesh physics bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7410]
## Problem description

I have two mesh sprites with physicist behavior. The right sprite works well. The left one doesn't work well. Please fix it so that the left one works well too.

## Attach a .c3p

[mesh_physics_bug_r359b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12673011/mesh_physics_bug_r359b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/097c258a-8608-4e9e-9a63-d1ba13a19426

## Expected result

The left one should behave the same way as the right one. Now it looks like its physical grid is rectangular.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r359b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r359 (beta)
Browser: Chrome 117.0.5938.89
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 116 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by Gryphonn** [comment]
You might ask why you'd need such a feature? 
We are working on a game where you can draw a **movable** physical object.
And meshes seem to be the only mechanism to do it in C3. 
But intersecting lines are inconsistent. Sometimes they work, sometimes they don't.
So this is from a real project. Please look into it.

![demoBug](https://github.com/Scirra/Construct-bugs/assets/21972383/58f8dfb0-8eb8-487e-b223-b8797cb93fa0)

**Comment by AshleyScirra** [comment]
In the console you can see it fails trying to separate the shape in to convex polygons, which is required for the physics engine:

> Physics polygon separation resulted in no polys.  Make sure all your collision masks for objects with the Physics behavior are valid and don't have any overlapping lines.

It notes not to use any overlapping lines, which your project does using the mesh feature. I don't think it's feasible to support this nor do I think Box2D fully supports this. I don't know why the one on the right works, I would have assumed this would not work at all, but anyway, I'm afraid I don't think it's possible for us to support this.

**Comment by WilsonPercival** [comment]
> In the console you can see it fails trying to separate the shape in to convex polygons, which is required for the physics engine:
> 
> > Physics polygon separation resulted in no polys.  Make sure all your collision masks for objects with the Physics behavior are valid and don't have any overlapping lines.
> 
> It notes not to use any overlapping lines, which your project does using the mesh feature. I don't think it's feasible to support this nor do I think Box2D fully supports this, as it is a weird thing to do to have a self-intersecting shape - in the real world a solid part of an object cannot pass through another solid part of the object. I don't know why the one on the right works, I would have assumed this would not work at all, but anyway, I'm afraid I don't think it's possible for us to support this. I think it might be possible to work around by composing the shape out of multiple physics objects which do not intersect, if you can find a way to do that (but this geometry stuff can be super hard).

@AshleyScirra There are no messages in my console.

<img width="960" alt="observed" src="https://github.com/Scirra/Construct-bugs/assets/91274932/31891256-4b28-4635-97f9-f500ba95de04">
