### ISSUE TITLE
Finally, I found the root cause of why I sometimes encountered the project corruption issue

### ISSUE THREAD

**Issue by LLCodeWiz** [Scirra/Construct-bugs#7412]
## Problem description
Construct 3 doesn't handle missing/unwanted files within the project folder correctly, causing "corrupt project" errors. Suggested solutions include saving all files or introducing a "Force Save" option.

(The context of the issue is when you save as a Project Folder, not as a C3P)

## Attach a .c3p

This can be only demonstrated.

## Steps to reproduce

Step 0:
You have a Project Folder in your local machine, e.g. at "C:\MyC3Project\src.",  You have created multiple layouts, events, etc.

Step 1:
Make some changes to Layout 1 and hit the save button in Construct 3.

Step 2:
Delete all the contents within the "C:\MyC3Project\src" folder while your project is still running in the browser. (This extreme step is necessary to easily reproduce the issue and the reason for this will become clear later)

Step 3: 
You make a few minor edits to Layout 1 and hit save again. In this situation, Construct 3, ignoring the missing files (deleted in Step 2) only saves the changes in Layout 1.

Step 4: 
Consequently, when you attempt to reopen the project at a later time, you encounter a "corrupt project" warning.

## Observed result

Construct 3 fails to detect the missing files (deleted in Step 2) and only saves the changes made to Layout 1 (Step 3). This incomplete saving process ultimately leads to a "corrupt project" when attempting to reopen the project at a later time.

## Expected result

C3 should detect the missing files (deleted in Step 2) and save the entire project folder, ensuring project integrity.

## More details
At first, I considered submitting this as an idea for a Save All/Force Save button in the editor. However, I later realized that it's crucial and should be categorized as a bug report. This is because people who use **Version Control are highly likely to encounter this issue.** (Using systems like Git can sometimes face problems when syncing changes, and discarding the changes, and When multiple members work on the same project, there's a higher chance user will face this issue)

Resolution Suggestion:

To address this issue, Construct 3 should consider performing the following actions to update the Save button's functionalities:

👉Examine all files present within the project folder.
👉Save all files within the folder, including those that might be missing but are supposed to be there.
👉Replace any files that have been altered with the updated versions.
👉Remove any files that are no longer relevant or within the scope of the project folder.

I also posted this in the community a few days ago, where I explained it in detail. https://www.construct.net/en/forum/construct-3/general-discussion-7/less-known-issue-may-corrupt-178644

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
https://github.com/Scirra/Construct-bugs/issues/6763

**Comment by AshleyScirra** [comment]
This isn't really a bug: at step 2 you delete a bunch of stuff from your project while Construct is still open. So you basically corrupt your own project at that step. I think it is also impossible to implement your suggestion, as in some cases Construct relies on the fact the file is on disk and so doesn't have it in memory, so it cannot write it back to disk from memory. So... don't delete your project while it's open in Construct!

**Comment by LLCodeWiz** [comment]
@AshleyScirra

> "as in some cases Construct relies on the fact the file is on disk and so doesn't have it in memory, so it cannot write it back to disk from memory."

But when we export as a C3P, Construct 3 compiles everything correctly (which means C3 must store everything somewhere in a temp folder). Could a similar feature be introduced for project folders?

So, I request you, please don't discard this request entirely. It could be a valuable addition for users who work with project folders.

Thank you for your attention.

**Comment by AshleyScirra** [comment]
So then if you open a 500 MB project, Construct will have to copy 500 MB of data to a temp folder before you can start using it. That'd probably be really slow and wasteful.

**Comment by LLCodeWiz** [comment]
> That'd probably be really slow and wasteful.
Fair, Perhaps adding an additional Save button, like the 'Save All' or 'Force Save' button, could be a sensible solution.
