### ISSUE TITLE
Hierarchy child mirror angle + persist  bug

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7413]
## Problem description

A mirrored child object with persist behavior that is rotated. Then switch scenes, and when you return to this scene again, the mirror will be reset.

## Attach a .c3p

[persist_hierarchy_child.c3p.zip](https://github.com/Scirra/Construct-bugs/files/12697868/persist_hierarchy_child.c3p.zip)

## Steps to reproduce
1. Just click to preview

## Observed result

After the playback is over, you can continue to click `1` to re-enter the layout. You will observe that the red square on the right will switch between two angle states.

![03](https://github.com/Scirra/Construct-bugs/assets/45864744/d1c15197-7718-4082-ac28-34a024b0052e)

## Expected result

![02](https://github.com/Scirra/Construct-bugs/assets/45864744/31bf7499-2c19-4189-acda-a31c48b69bf4)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
