### ISSUE TITLE
Crash when opening image editor for individual tile in a tilemap

### ISSUE THREAD

**Issue by raassh-23** [Scirra/Construct-bugs#7414]
## Problem description

Construct crashes when opening image editor for individual tile in a tilemap

## Attach a .c3p

[crashTilemap.c3p](https://drive.google.com/file/d/1z7FMiD8DmzhSIWFnhsHhFeVo6gKdUjBj/view?usp=drive_link)

## Steps to reproduce

1. Open tilemap bar
2. Double click on a tile to open image editor

## Observed result

Construct crashed

## Expected result

Construct doesn't crash

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r359 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'cTa') @ TypeError: Cannot read properties of undefined (reading 'cTa') at N2a.Spc.ga (https://editor.construct.net/r359/projectResources.js:2083:274) at AN.Epb.ga (https://editor.construct.net/r359/projectResources.js:2088:13) at https://editor.construct.net/r359/projectResources.js:2035:9 at async window.akb.ad (https://editor.construct.net/r359/main.js:2947:377)
Stack: TypeError: Cannot read properties of undefined (reading 'cTa') at N2a.Spc.ga (https://editor.construct.net/r359/projectResources.js:2083:274) at AN.Epb.ga (https://editor.construct.net/r359/projectResources.js:2088:13) at https://editor.construct.net/r359/projectResources.js:2035:9 at async window.akb.ad (https://editor.construct.net/r359/main.js:2947:377)
Construct version: r359
URL: https://editor.construct.net/r359/
Date: Fri Sep 22 2023 20:59:20 GMT+0700 (Western Indonesia Time)
Uptime: 119.4 s

Platform information
Product: Construct 3 r359 (beta)
Browser: Chrome 117.0.5938.92
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 Ti Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. Was a regression introduced in r359.
