### ISSUE TITLE
Video of bear and seagulls playing in Construct iOS game

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7425]
## Problem description
This is the most absurd bug that I have ever encountered and I don‘t expect anyone to fix it but I want to ask whether you guys have an idea what this could be caused by. 

There is a ~0.2% chance of a video of a bear that I had never seen before and is not part of my project appearing and playing in my game. It appears after switching scenes in Construct & loading rewarded video ads with the advert plugin, until now, always a few seconds after launching a construct game. 

It opens in the iOS video player as a floating video. I have not ever seen this video in my life, but did some research on it. 

The video originates from Windows Vista (a sample video) and is from the Microsoft wildlife series. It was being used as a test video for the .wmv file format. This is the video [source](https://youtu.be/JlgNSaiCPPQ?si=LsjhL28nQJ3xGXZ8). 

Screenshots of this: 
![IMG_6985](https://github.com/Scirra/Construct-bugs/assets/80539587/9d87c1f5-7ebb-44a5-bc6f-1458bf6d8ae6)
![IMG_6984](https://github.com/Scirra/Construct-bugs/assets/80539587/40712c36-5e43-4d5e-b6db-95496db13ee3)

## Attach a .c3p
Appears to be a thing in every construct game exported to ios but can‘t confirm anything as the chance of it appearing is so low. 

## Steps to reproduce
 
1. Create a Construct project and add the advert + browser addons to it. Those are the only ones that could influence this afaik. 
2. Load an ad with the advert plugin
3. Do that often and switch scenes on iOS

## Observed result

A video of a bear and seagulls might appear.

## Expected result

I do not expect a bear. 

## More details

**Affected browsers/platforms:** <!-- 
Safari running ios 17 (ios 16 affected too)

**First affected release:**
r358

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
![IMG_6954](https://github.com/Scirra/Construct-bugs/assets/80539587/43313796-8e31-47f0-83a3-9e4f51d5b376)
This is how the (rotated, for some reason) video player looks like. I‘m just reporting this in hope that someone at Scirra knows what this is, if not, I‘ll try to find anything causing this in the xcode project and will analyze the console log but this video only appears every ~3h when testing so it is reaally hard to catch.

**Comment by therealPaulPlay** [comment]
![IMG_6991](https://github.com/Scirra/Construct-bugs/assets/80539587/78d2dca6-472f-4dbc-89e5-d391d7091c3e)
After further testing, I have realized that when the bear video appears and I fire the show ad trigger, the bear video becomes the ad. This makes me believe that this is related to the ad plugin and I‘ll file a bug report there.

**Comment by AshleyScirra** [comment]
This has to be one of the craziest bug report titles I've ever seen 😅

I can assure you the bear/seagull video doesn't come from Construct - we've never used that video, not even in testing.

Since you are using adverts, which make use of video playback, I would suspect that is indeed the cause of the problem rather than Construct. The appearance of the video in test mode seems to indicate the ad service is using that video as a placeholder when real video ad content is not available. So if anything is going wrong with that, I think you're best off reporting it to the ad network, as it's not something under our control.

**Comment by therealPaulPlay** [comment]
Thanks👍 I‘ll file a bug report for the cordova-admob-plus (or how it‘s called) plugin. Just wanted to know whether you know anything about this.
