### ISSUE TITLE
AdvancedRandom: Empty seed string doesn't produce random results

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7427]
According to the documentation: "An empty string (the default) will use a random seed, ensuring the sequence of numbers is different every time."

However _random(number)_ returns the same result every time.

I know that we can use AdvancedRandom.RandomSeed expression, but this means that the documentation is wrong.

## Attach a .c3p

[EmptySeedBug.zip](https://github.com/Scirra/Construct-bugs/files/12762850/EmptySeedBug.zip)

## Observed result

Same number generated every time.

## Expected result

Random number.

## System details
<details><summary>View details</summary>
Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 117.0.5938.92
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 265 gb
Storage usage (approx): 2.7 gb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
@dop2000 The documentation talked about this field with an empty value.

<img width="214" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/b06b4a76-929b-4f2a-9cf2-83a72095060a">

**Comment by dop2000** [comment]
@WilsonPercival 
It makes sense, but still inconsistent - an empty value in properties generates a random seed, but setting a seed to empty value with an action doesn't.

**Comment by AshleyScirra** [comment]
I don't think this is a bug, it's just a confusion between what the default property means. For the 'Seed' property, the default empty string means to use a random seed and so produce unpredictable numbers. It's used as a shorthand to avoid having a separate checkbox like "use fixed seed". On the other hand the 'Update seed' action always sets the seed you give it, since by using the action your intent is explicitly to use the seed you provide. So it uses whatever you give it, even if it's an empty string, and therefore will always produce the same sequence of numbers. If you want to go back to a random seed, the *RandomSeed* expression is what you should pass instead of an empty string. I can see why this might seem confusing though, so I added a note to the [documentation](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/advanced-random) for the 'Update seed' action:

> Note if you pass an empty string, it still uses the empty string as the seed. If you want to go back to using a random seed, pass the RandomSeed expression as the seed to set.
