### ISSUE TITLE
Attachment state WebGPU bug using effects in 3D

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7429]
## Problem description

When I launch the game I see a black screen and the console is yellow.

## Attach a .c3p

[attachment_state_web_gpu_bug_r360b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12774261/attachment_state_web_gpu_bug_r360b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

<img width="941" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/ea804e4d-b8a7-478e-93d3-bd231edd38d4">

## Expected result

The game starts normally and the console is not yellow.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r360b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r360 (beta)
Browser: Chrome 117.0.5938.89
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 186 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Additional details: the problem appears to be related to the combination of both 3D shape, which has an effect, and the SpriteFont object. If the SpriteFont object is removed it works. If the SpriteFont is Z ordered below the 3D shape, it works. If the 3D shape object does not have an effect, it works. So it seems to be a problem that only occurs with the specific situation of rendering a 3D shape with an effect followed by a SpriteFont, with a 3D camera.

**Comment by AshleyScirra** [comment]
Fixed for next beta.
