### ISSUE TITLE
How the Construct 2 WebGL renderer works

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7433]
## Problem description

The link goes to https://www.construct.net/en, but I wanted to read it.

## Attach a .c3p

https://www.construct.net/en/blogs/ashleys-blog-2/construct-webgl-renderer-works-917

## Steps to reproduce

1. Follow the link.
2. Click on `a brief overview in a reply`.

## Observed result

<img width="646" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/70e153d3-ffb6-4597-98ec-43d862f13ef1">

https://www.construct.net/en

## Expected result

I can read what is in the link.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in 2023

## System details

<details><summary>View details</summary>

![175827374-34cc405b-90fe-4e6e-90e0-482114318fea](https://github.com/WilsonPercival/WilsonPercival/assets/91274932/e1da2a51-f2ad-4e06-81df-33aff2831ede)

</details>

**Comment by AshleyScirra** [comment]
This isn't a Construct bug, just a broken link from a 2014 blog post. I don't think the original forum post could be easily found now, and IIRC, the blog had all the same information and more and was better written, so it doesn't matter anyway. Further, I would advise to be wary of such old posts, as often they end up being considerably out of date - a lot has changed over the past ~10 years.

**Comment by WilsonPercival** [comment]
> This isn't a Construct bug, just a broken link from a 2014 blog post. I don't think the original forum post could be easily found now, and IIRC, the blog had all the same information and more and was better written, so it doesn't matter anyway. Further, I would advise to be wary of such old posts, as often they end up being considerably out of date - a lot has changed over the past ~10 years.

@AshleyScirra I didn't find them on purpose. You've referenced them in your blogs on how WebGL and WebGPU work.
