### ISSUE TITLE
Not possible to set up typescript until you create at least one script

### ISSUE THREAD

**Issue by alvaromartmart** [Scirra/Construct-bugs#7438]
## Problem description

The latest R361 beta introduces Typescript support. However it's not possible to set up typescript until you create unless one script. I suspect it's because it tries to write to a folder that doesn't yet exist, so it throws a permissions error.

## Steps to reproduce

1. Create a new project
2. Save as folder
3. Try to set up typescript
4. It fails
5. Add a script and save the project
6. Typescript setup succeeds

## Observed result

![Screenshot 2023-10-04 at 10 06 55](https://github.com/Scirra/Construct-bugs/assets/18287793/b0ce247c-6a65-4492-873d-a4faaa2df31a)

## Expected result

Should be able to configure Typescript even before creating the first script.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I hadn't thought about this case as if you have no script files then there are no .ts files to create either, so there's nothing much to set up. However I think it makes sense to add the default script files in this case so setting up TypeScript still works, which is done for the next beta.
