### ISSUE TITLE
Construct 3 Editor Font Preview does not use a pangram (s is left out)

### ISSUE THREAD

**Issue by MasonJSwan** [Scirra/Construct-bugs#7444]
## Problem description

Font preview does not use a pangram to display every letter. "S" is missing.

## Attach a .c3p

Not applicable. If you really need one I've attached a blank project with an imported font
[blankproject.zip](https://github.com/Scirra/Construct-bugs/files/12821714/blankproject.zip)

## Steps to reproduce

1. Open/Create any project
2. If no fonts are imported in the project, right click the fonts folder in the Project bar and import any font
3. Double click the font to open the font preview

## Observed result

The Font preview displays the sentence "The quick brown fox jumped over the lazy dog." in the previewed font family at various font sizes.

## Expected result

The Font preview should display "The quick brown fox jump**s** over the lazy dog." or should find some other way to include the "s" letter.

## More details

**Affected browsers/platforms:** Presumably all browsers since it's an issue with the editor, but I've been able to test it in Firefox and Edge.

**First affected release:** Presumably all releases of Construct 3, but I've been able to verify that this issue is present on r71.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Edge 117.0.2045.47
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.47
Language setting: en-US

Local storage
Storage quota (approx): 285 gb
Storage usage (approx): 127 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 96000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by fredriksthlm** [comment]
There is a cool story behind this exact sentence. It was the first sentence that was sent via the Moscow-Washington hotline. And it was in fact  **jumped** and not **jumps**. 

**_THE QUICK BROWN FOX JUMPED OVER THE LAZY DOG'S BACK 1234567890_**, a line that contains all letters of the alphabet. The Soviets replied by sending a poetic description of the setting Moscow sun.

https://www.cryptomuseum.com/crypto/hotline/index.htm

**Comment by AshleyScirra** [comment]
Huh, I assumed it was a pangram, but I guess there was a typo! Well spotted, fixed for the next beta.
