### ISSUE TITLE
C3 Crash Part2

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-bugs#7448]
Randomly crashed while I was trying to edit some comments:

![Image 005](https://github.com/Scirra/Construct-bugs/assets/41597700/77f7091e-e16d-4cbf-967d-a05362405e81)

I recently opened another BUG about another Crushings here:
[https://github.com/Scirra/Construct-bugs/issues/7445](url)

But this crush error gives a different message so I suppose it is a different issue also I used a different C3 project and C3 version than the other BUG report. 

No Capx

## Steps to reproduce

1.I was just trying to update a comment on the editor

## Observed result

C3 Crash

## Expected result

That C3 doesn't crash

## More details

Some of F12 Console Logs:
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' blob: <URL> <URL> 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-4duIxu7gRCkz/ELYlbC1dW0Er+DL3VFLgrdCHAhad8U='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

**Affected browsers/platforms:**  
Chrome

**First affected release:** 
R361

## System details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r361/, line 0, col 0
Message: ResizeObserver loop completed with undelivered notifications.
Stack: null
Construct version: r361
URL: https://editor.construct.net/r361/
Date: Sat Oct 07 2023 18:32:17 GMT+0100 (British Summer Time)
Uptime: 9524.9 s

Platform information
Product: Construct 3 r361 (beta)
Browser: Chrome 117.0.5938.150
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7378

**Comment by Tarek200** [comment]
Thanks @WilsonPercival for pointing that out.

I went through all the duplicate Bugs and looks like most of the users pointing to "LastPass" which I dont have.
I will keep an eye on my third-party plugins on Chrome and see if any of them are causing the issue.

**Comment by nerdError** [comment]
Having a billion browser extensions (any of which can break something) and not providing any files to replicate the bug is the best way to get your issue closed without investigation 😅

**Comment by DiegoScirra** [comment]
That error message definitely points at a problem with an extension.

**ResizeObserver** is an API of modern browser's which C3 doesn't use at all, so if it's causing problems, it's coming from somewhere else.
