### ISSUE TITLE
C3 crashes when creating new KEYSTORE in beta r361

### ISSUE THREAD

**Issue by KabutoJRM** [Scirra/Construct-bugs#7455]
## Steps to reproduce

**Affected browsers/platforms:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r361/main.js, line 1917, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at rr.g.li.aMa (https://editor.construct.net/r361/main.js:1917:242) at aj.g.Cvc.zd (https://editor.construct.net/r361/main.js:1919:416) at https://editor.construct.net/r361/main.js:1919:139
Construct version: r361
URL: https://editor.construct.net/r361/
Date: Mon Oct 09 2023 15:43:04 GMT-0500 (hora estándar de Colombia)
Uptime: 347.7 s

Platform information
Product: Construct 3 r361 (beta)
Browser: Edge 117.0.2045.60
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Edg/117.0.2045.60
Language setting: en-US

WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: nvidia
Adapter architecture: pascal
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features: bgra8unorm-storage, depth-clip-control, depth32float-stencil8, indirect-first-instance, rg11b10ufloat-renderable, texture-compression-bc

</details>

**Comment by DiegoScirra** [comment]
The crash report suggests this has something to do with a keyboard shortcut rather than creating anything, but there is not enough information to investigate it properly. Closing.
