### ISSUE TITLE
Can't export any projects

### ISSUE THREAD

**Issue by SEKTORxx** [Scirra/Construct-bugs#7460]
## Steps to reproduce

1.Start export project
2.Wait
3. looking at the error

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct version: r358
URL: https://editor.construct.net/
Date: Wed Oct 11 2023 20:16:25 GMT+0500 (Узбекистан, стандартное время)
Uptime: 666.3 s

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 117.0.5938.152
Browser engine: Chromium
Context: browser
Operating system: Windows NT 8.0.0
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment]
@SEKTORxx Everything works well for me. Can you check on the incognito tab?

**Comment by SEKTORxx** [comment]
I try

**Comment by gutsalovpavel** [comment]
the same for me. Some projects are working, and some - not, it happens after the last update (362) probably

**Comment by gutsalovpavel** [comment]
nope, issue in the 361 version. In the 360 build, everything is working

**Comment by WilsonPercival** [comment]
> the same for me. Some projects are working, and some - not, it happens after the last update (362) probably

@gutsalovpavel Can you send me the project?

**Comment by gutsalovpavel** [comment]
Nope but I can show you the errors. Last build (362) not loading itself, or loading time after time 
![image](https://github.com/Scirra/Construct-bugs/assets/125470357/39b4f716-d227-49fc-aa74-e458af1c35dd)

**Comment by gutsalovpavel** [comment]
oh stop, the game is loaded. It is something with skirra servers maybe, because when the game wasn't loaded, I saw errors related to the lost connection or something like that, so, sometimes the game can be published sometimes not

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines, otherwise it's impossible for us to help.

It looks like you might be using third-party addons. Those could be the cause of the problem, in which case you'd need to contact the addon developer for support.
