### ISSUE TITLE
Is Sharing Supported is true, but Share does not work on apple devices

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7461]
## Problem description

If the sharing is not supported, the button is invisible. On apple devices, the button shows up, but does nothing when clicked. All works fine on windows 10.

## Attach a .c3p

[test share.zip](https://github.com/Scirra/Construct-bugs/files/12873945/test.share.zip)

## Steps to reproduce

1. Preview
2. Click Share
3. Check the browser console

## Observed result

![Screenshot 2023-10-09 at 6 31 18 PM](https://github.com/Scirra/Construct-bugs/assets/12113416/78f46722-d2fc-4928-ad4b-87ecb127ad8c)
![Screenshot 2023-10-09 at 6 42 19 PM](https://github.com/Scirra/Construct-bugs/assets/12113416/8961a66a-215a-48ba-918f-2ef98744d480)

Screenshots are from Mac, but the same result happens on iPhone and iPad.

## Expected result

1. Is Sharing Supported should be false
2. If Is Sharing Supported is true, then sharing should always work

## More details

**Affected browsers/platforms:** 

**First affected release:** r358 stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
What exactly are you doing when publishing your project?

It looks like you might be using a web export and loading it in an iframe. That would need you to specify that web share is allowed inside the iframe, which appears to be what the error message is referring to. That is not an issue with Construct, it's just the browser permissions set for the iframe.
