### ISSUE TITLE
Changes to Tilemaps Don't Save to Project Folder

### ISSUE THREAD

**Issue by CodyRockwell** [Scirra/Construct-bugs#7462]
## Problem description

Editing the placement of tiles in a layout will not save unless you make some other change to the project before saving (such as moving a sprite in the layout or adding/deleting an event sheet). Editing the event sheet before saving does not affect whether or not the tilemap saves, even though changes to the event sheet do save.

This problem only affects local folder projects, not .c3p files.

## Attach a .c3p

https://www.dropbox.com/scl/fi/g7eu0fpsdaco4z4bomt2l/Tilemap-Bug.zip?rlkey=ezhw1i5ap4a0kmb1hs6kjpz3s&dl=0

## Steps to reproduce

1. Edit the tilemap in Layout 1
2. Save the project and reopen it in a new tab
3. Your changes won't have saved
4. Try editing the tilemap and then moving the sprite in Layout 1 before saving
5. Reopening the project will show that the tilemap saved this time

## Observed result

Whether or not tilemaps in project folders save is dependant on the other actions you perform before saving.

## Expected result

Tilemaps should save everytime.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Outcome is the same on r358 and beta r362

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Chrome 118.0.5993.70
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 56 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002487) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta
