### ISSUE TITLE
Binary Data url bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7467]
## Problem description

When I press the `Play` button I see an error in the console and the sound does not play.

## Attach a .c3p

[binary_data_url_bug_r362b.zip](https://github.com/WilsonPercival/WilsonPercival/files/12920917/binary_data_url_bug_r362b.zip)

[Cannon.webm](https://github.com/Scirra/Construct-bugs/assets/91274932/fc323038-76a9-4480-83ab-5b14d5e64c9e)

## Steps to reproduce

1. Open a project.
2. Launch and open the console.
3. Click the `Load` button and select the `Cannon.webm` file.
4. Click the `Play` button. Please note that there is an error in the console and no sound can be heard.
5. Return to the project. Open the event sheet and turn off the `Browser -> Log` action.
6. Run the project.
7. Click the `Load` button and select the `Cannon.webm` file.
8. Click the `Play` button. Please note that there is no error in the console and audio can be heard.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/3971bf90-3eb6-4934-9d39-7bb9568c583a

## Expected result

When I press the `Play` button, there are no errors in the console and the sound plays.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r362b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r362 (beta)
Browser: Chrome 117.0.5938.150
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 546 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by brushfe** [comment]
<img width="653" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/63005234/a97b0175-0f39-43b6-acf2-14d5bf596e90">

This works if the browser call is made in this trigger instead, but I agree that a failed browser action shouldn't prevent the sound from playing at all.

**Comment by WilsonPercival** [comment]
> <img alt="image" width="653" src="https://user-images.githubusercontent.com/63005234/275643836-a97b0175-0f39-43b6-acf2-14d5bf596e90.png">
> This works if the browser call is made in this trigger instead, but I agree that a failed browser action shouldn't prevent the sound from playing at all.

@brushfe I don't know what you mean because your trigger is never executed in my project file.

**Comment by brushfe** [comment]
@WilsonPercival Strange! Maybe i missed something on my end then. Sorry to mislead us! I hope it gets resolved

**Comment by AshleyScirra** [comment]
Fixed for next beta.
