### ISSUE TITLE
Event search filter does not adjust number in title text

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7468]
When I searched for "name" in my event sheet, it says I have "925 results", but in the filter section where I narrowed it down with "add key", it still says the same amount of results. 

But you can see by the size of the scroll bar, that it's really only a couple dozen results, not 925!

I found this confusing. I almost gave up on the search because it said there was so many results, until I browsed the results and noticed that the text was incorrect.

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/afa8c1d2-8a19-4b42-9b18-34e33f2a20d5)

____________

capx

[filterbug.zip](https://github.com/Scirra/Construct-bugs/files/12924479/filterbug.zip)

________________

1. use search in event sheet
2. type this: 
![image](https://github.com/Scirra/Construct-bugs/assets/5744908/15a5edf0-23ba-46e9-9b5c-fed982fce152)
3. Observe this text not change when you add filter text in the input box: 
![image](https://github.com/Scirra/Construct-bugs/assets/5744908/20457cd6-e0e8-4e9e-89e9-bd0197ccdec3)

**Comment by AshleyScirra** [comment]
Fixed for next beta.
