### ISSUE TITLE
Editor text input fields do not indicate they've been cropped, resulting in inaccurate information

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7469]
Construct editor does not provide any information in any of its input fields that the string has been cropped.

I think it might be standard practice nowadays to indicate that a field has been cropped, look at how Chrome does it:
![image](https://github.com/Scirra/Construct-bugs/assets/5744908/40d69ff9-daf9-4c85-96d6-683ded510ca6)

When the string is too long to be displayed it adds the "..." before the edge of the crop to indicate that there is hidden text.

This expectation has caused me  great confusion when using the Construct editor because it is not using this practice. 

________

###   Example

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/6d36f0e7-d7fa-4561-9339-575e610d010c)

Here I have clicked on a sprite and the editor claims that the variable = "one_two"

This is an error though!

In reality the variable = "one_two_three"

But this can only be known by chance you have this window's width pulled out further:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/98892aa4-4717-449e-bcfa-fd4670e2287f)

___________

### Expectation

This empty space that's covering text should instead be filled with "..."

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/2006c847-74c5-478b-b083-bc3aee0e4c3f)

This will result in greater clarity and help to ensure that accurate information is conveyed.

___________________

This should apply to all fields, here is another example:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/9c0062cc-c4ac-44d1-8e4e-52ed55c61dff)

It appears to say "48" but in reality it's secretly "480" if you widen the window/field.

**Comment by AshleyScirra** [comment]
I think this is reasonably straightforward to do with a change to the CSS, so it's in for the next beta.

**Comment by JeFawk** [comment]
The implementation of this is causing me issues: https://github.com/Scirra/Construct-bugs/issues/7951

Not ok to help some at the expense of others.
