### ISSUE TITLE
Sound doesn't play in Firefox when immediately playing it after fading & stopping it (Example with Typewriter Text) (Chrome works)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7480]
## Problem description

When playing a sound file in Firefox immediately after fading it to negative db levels and stopping it it does not play (at least, that's what I think could be going on here). In Chrome and Safari it is working fine. 

## Attach a .c3p
[TypewriterSound.zip](https://github.com/Scirra/Construct-bugs/files/13061116/TypewriterSound.zip)

## Steps to reproduce
1. Play audio sound
2. Fade it to negative decibel levels and stop it
3. Play it again as soon as it has stopped playing in Firefox

## Observed result

The sound doesn't play. 

## Expected result
Sound should play like it does in Chrome.

## More details
Newest Firefox version is affected.
Using newest Construct 3 stable release.

## System details
PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
Edit: I've noticed that the sound plays the second time when you restart the layout and then try again. Not sure what to make of that

**Comment by WilsonPercival** [comment]
@AshleyScirra @therealPaulPlay Minimum project:

[issue7480.zip](https://github.com/Scirra/Construct-bugs/files/13061248/issue7480.zip)

Steps:

1. Open and run the project.
2. Press `1`.
3. Wait half a second.
4. Press `2`.
5. Wait half a second.
6. Press `1`.

Observed result: no sound plays.

**Comment by AshleyScirra** [comment]
It looks like a Firefox bug. I'll try to figure out a workaround or file an issue directly with Mozilla.

**Comment by AshleyScirra** [comment]
I think I figured out a minimal repro so I filed an issue with Mozilla here: https://bugzilla.mozilla.org/show_bug.cgi?id=1860581

Closing this issue as it will be followed up there.
