### ISSUE TITLE
Bug with chrome 118.0.5993.80

### ISSUE THREAD

**Issue by zizmsall** [Scirra/Construct-bugs#7486]
The game is working then if the screen lost focus, when we go back to the game, the event are not firing (when we click on a button for example).

## Attach a .c3p

Any projet even those in the example page behave same way, you can reproduce using anyone of them.

## Steps to reproduce

1.Launch any app on chrome 118.0.5993.80 (mobile)
2.Let the mobile go to sleep (or change app)
3.Come back to the app

## Observed result

The event are not fired.
(only pure javascript work)

**Comment by AshleyScirra** [comment]
Sounds the same as #7481.
