### ISSUE TITLE
Where is the text WebGPU bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7487]
## Problem description

When I start the game I don't see any text. `WebGL` works well.

## Attach a .c3p

[License Test Example.zip](https://github.com/WilsonPercival/WilsonPercival/files/13118210/License.Test.Example.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

<img width="852" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/879a06d4-f7ba-4911-bd19-061546aae60a">

## Expected result

`WebGL`:

<img width="851" alt="expected" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/752838b6-1c45-4876-be37-da69b3ab0404">

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r364b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r364 (beta)
Browser: Chrome 118.0.5993.89
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 876 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This doesn't reproduce with the built-in example. It seems the provided project has been modified in some way to cause the problem. However it is not a minimal project which makes it extremely difficult to tell what has been changed.

Please provide a minimal project as per the bug report guidelines, as it avoids this problem.

**Comment by WilsonPercival** [comment]
> This doesn't reproduce with the built-in example. It seems the provided project has been modified in some way to cause the problem. However it is not a minimal project which makes it extremely difficult to tell what has been changed.
> 
> Please provide a minimal project as per the bug report guidelines, as it avoids this problem.

@AshleyScirra 
[issue7487.zip](https://github.com/Scirra/Construct-bugs/files/13165745/issue7487.zip)

**Comment by AshleyScirra** [comment]
If I just put a text object in a new project it works with the WebGPU renderer. Presumably the provided project has changed something that causes the problem? I already just wasted hours tracking down a tiny change in a project for issue #7453 and would rather not repeat that, can you identify the change that causes the problem?

**Comment by WilsonPercival** [comment]
> If I just put a text object in a new project it works with the WebGPU renderer. Presumably the provided project has changed something that causes the problem? I already just wasted hours tracking down a tiny change in a project for issue #7453 and would rather not repeat that, can you identify the change that causes the problem?

@AshleyScirra Oh, why ( There was no need to waste time. I just first described the detailed steps on how to create a project, but you said that this was not necessary. All you need is just a project file and steps to reproduce the project. No need to waste time on searches, it's better to just ask)

I simply set the `Near distance` value to `100`.

**Comment by AshleyScirra** [comment]
> I just first described the detailed steps on how to create a project, but you said that this was not necessary.

People sometimes write steps like "1. Create a new project 2. Insert a Sprite object 3. Fill the image with a solid blue color 4. Close the animations editor 5. Switch to the event sheet..." - all that is useless information. That's what you don't need to include. Obviously the thing that actually causes the problem is the most important information and should always be included!

> I simply set the Near distance value to 100.

This is not a bug: the camera Z is at 100 and so the near plane is exactly on the text object, which means it's not guaranteed to render.

**Comment by WilsonPercival** [comment]
@AshleyScirra "This is not a bug: the camera Z is at 100 and so the near plane is exactly on the text object, which means it's not guaranteed to render." - To be honest, I didn't understand what this meant. But just so you know - it works well in r363b.

**Comment by WilsonPercival** [comment]
@AshleyScirra And on the value of the `Near distance` parameter equal to `51` there is no text either.

**Comment by WilsonPercival** [comment]
@AshleyScirra This was fixed in `r365b`. Presumably along with https://github.com/Scirra/Construct-bugs/issues/7490
