### ISSUE TITLE
Construct crashing while panning image in sprite editor.

### ISSUE THREAD

**Issue by ruskul** [Scirra/Construct-bugs#7491]
## Problem description

(copied form forum post.  Ashley couldn't reproduce the bug, but I thought the crash report may help)

Construct crashes in firefox when panning an image in the sprite editor, if you click the middle mouse button and drag to pan, and release the middle mouse button while the cursor is outside the sprite editor window and above the browser menu/url bar.

I can only get this to crash in firefox, chrome works fine.

## Attach a .c3p

Any project works, brand new, or existing one.  You just need one sprite to edit.

Basic project with sprite:

https://drive.google.com/file/d/152bQdZrtNffGtRsmJMFrGCJkiLiPOLov/view?usp=drive_link

## Steps to reproduce

Simply create a new project, create a sprite, and then open the sprite editor.

Put the mouse cursor on the image and Click and hold with the middle mouse button to pan the image. While holding the middle mouse button down to pan, move the cursor to the browser tabs/urls UI at the top of the screen. What happens?

When I am panning around a sprite and overshoot and my cursor ends up in the firefox menu/tab area, Construct crashes.

## Observed result

Construct crashes with error report, pasted below.

## Expected result

No crashing :D

## More details

I am unsure when this bug first started, It obviously is rare to trigger and requires specific user input.

## System details

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r358/main.js, line 1052, col 340
Message: TypeError: expected HTML element
Stack: Q.Ga@https://editor.construct.net/r358/main.js:1052:340 da.Nm@https://editor.construct.net/r358/main.js:1074:84 Nfa@https://editor.construct.net/r358/projectResources.js:2462:231 g4a.yvc Construct version: r358
URL: https://editor.construct.net/
Date: Wed Oct 25 2023 11:31:33 GMT-1000 (Hawaii-Aleutian Standard Time)
Uptime: 82.5 s
Platform information

Product: Construct 3 r358 (stable)
Browser: Firefox 118.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 400 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
