### ISSUE TITLE
Unstable GPU performance in WebGL2

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-bugs#7499]
## Problem description
Encountering performance inconsistencies when extending the runtime window during the execution of GPU-intensive effects in WebGL2.

While some level of fluctuation might be expected, the primary concern is the inconsistent duration of these performance hits before reaching a stable state. **While in some instances, stability is never achieved.**

Frequently toggling to full-screen mode significantly alters the user experience by either:
**a.)** Initial hit in performance, followed by performance stability.
**b.)** Initial hit in performance, followed by a brief period of stability, only to experience sporadic spikes at later intervals.
**c.)** As observed towards the end of the video, the performance degrades significantly and continues to do so indefinitely, until exiting full-screen mode.  (see video further below)

Some performance instability might arise due to the dynamic loop size, so the loop can't be unrolled on compilation. But this is a rather extreme case. (during my tests i observed a difference between 36% (stable) vs 80~99% (unstable) GPU utilization.

## Attach a .c3p
Unfortunately this project has numerous objects which may complicate the debugging process. However that's on purpose to make the performance instability evident.
[NM32_benchmarkReport.zip](https://github.com/Scirra/Construct-bugs/files/13192029/NM32_benchmarkReport.zip)

## Steps to reproduce
Run preview
1. Hit F11 to go into full-screen
2. Observe GPU utilization and FPS
3. Hit F11 to close full-screen
4. Repeat step 1-3, this might take a few tries to get it stuck entirely

## Observed result
https://github.com/Scirra/Construct-bugs/assets/12261601/995e9c64-5373-4329-b85e-bf45312ed820

## Expected result
Consistent test results, and not in some cases running significantly worse forever.
Stable GPU performance, not unpredictable utilization spikes.

## More details
The same behavior can be witnessed by just enlarging the window without triggering a full-screen.
This can be reproduced in preview, with or without debugger.
Can also be reproduced on a webview2 export.
The performance fluctuation was reproduced by multiple users.
**Sidenote:** The WebGPU variant of this effect runs **significantly** worse, however without noticeable fluctuations. (was unable to find the cause, so possibly related to C3 overhead. Just worth mentioning)

Although this project uses a custom effect, it is a very similar use case to the official bump mapping effect and mainly increases the workload a lot by computing many overlapping lights per map. While this benchmark isn't a "realistic" use-case, it showcases the underlying performance issues. I've set up this benchmark after having noticed significant performance issues in my personal project in a realistic use-case.

**Affected browsers/platforms:** 
Chrome 118.0.5993.118

**First affected release:** 
Unknown

## System details
<details><summary>View details</summary>
Platform information
Product: Construct 3 r364 (beta)
Browser: Chrome 118.0.5993.118
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 503 gb
Storage usage (approx): 80 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 (0x00002204) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</details>

**Comment by Everade** [comment]
Using a fixed loop size and breaking the loop with a conditional statement seems to fix the instability issues.
But i'm not sure if that also explains the randomness when going in and out of full-screen.

**About WebGPU:**
The performance difference from WebGL2 to WebGPU is really extreme in this case. And it would be great to know if that's due to the overhead created by %%C3_UTILITY_FUNCTIONS%% ?!

**Comment by AshleyScirra** [comment]
You should be very wary of the [warnings in the manual about the cpuutilisation/gpuutilisation expressions](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-expressions#internalH1Link8) when looking at these measurements - which also applies to the debugger readings, since it just shows the value of those expressions there.

In general these values fluctuate because they are timer-based estimates, and therefore subject to the CPU/GPU power management. For example the GPU may reduce to half power, and then the timer reading will double, even though it is doing exactly the same amount of work. The power management schemes are far more complicated than that though, and also involve the temperature readings on the device, so they can end up fluctuating differently after the device has been under load for some time and so heated up.

So in general we won't investigate bugs that are merely "look at this timer-based reading changing unpredictably", as you're probably just looking at the hardware power management affecting the reading.

**Comment by F3der1co** [comment]
To me the more interesting find is that webGPU performs way worse in this case, and I think this should be investigated where the overhead comes from as to me the shader code looks very similar. 
Has this to do with c3 breaking the batch more than webGL, is this cause by the utility function or struct with many unifroms or the Chromiums webGPU implementation itself etc. ?

**Comment by Everade** [comment]
This isn't about those specific readings, this is about actual performance issues.
I get identical readings on any GPU utilization tool outside the debugger. Such as NVIDIA or HWMonitor or any other GPU performance tool. And i get physical coil whining due to the sudden high loads.

The GPU is throttling when its running smooth... And it boosts up when it's struggling to keep up. Not the other way around, at least not in this case.
My understanding here is that the output suddenly gets much more demanding. This isn't about the GPU heating up either.  Hit full-screen back and forth and you will get different results 50% of the time.

1.st test - enlarging window - **(EXTREME LAG, INDEFINITELY)**
94% Utilization
Drawing 246.11W
Graphics at 1995MHz
50% Frame Buffer
Yes the heat is a little higher here because i was waiting to make sure the lag stays. It ran bad to begin with, but it's definitely not throttling due to heat.
![image](https://github.com/Scirra/Construct-bugs/assets/12261601/d5d13944-7b1c-4e99-aef6-deeddfe7e956)

2nd test - enlarging window - **(SMOOTH & STABLE)**
39% Utilization
Drawing 99.17W
Graphics at 1410MHz
3% Frame Buffer
Lower heat, makes sense considering running throttled/not boosting.
![image](https://github.com/Scirra/Construct-bugs/assets/12261601/9192f251-426a-4628-9857-0ec2e2bc98ee)

3rd test - lag, smooth, lag, smooth, lag
4th test - smooth indefinitely
5th test - lag, smooth
6th test - lag indefinitely
7th test - lag indefinitely
8th test - smooth indefinitely
9th test - smooth indefinitely
10th test - lag, smooth
and so on....

@AshleyScirra 
I hope these readings raise your interest into actually testing this. I know your time is precious, but absolutely nothing about this looks normal to me. Wasting your time is my biggest nightmare, so i would like to avoid that. But i really think i found an actual issue here.

And as F3der1co stated, it would also be great to know what's going on with WebGPU in this case. The performance difference is humongous.

**Comment by AshleyScirra** [comment]
I don't see what we'd do about this anyway. Construct issues the same WebGL commands no matter the window size. There's nothing much for us to change there. Actual hardware utilisation would be something handled at the driver/hardware level, and utilisation readings will probably vary in response to that.

**Comment by Everade** [comment]
@AshleyScirra 
You can verify this with FPS, i showed you utilization to proof that there's an issue. So the issue isn't the utilization, the issue is the actual GPU performance it suddenly demands.
There are 2 very distinct modes you can easily spot with your eyes. **A.)** Lots of FPS **B.)** Very low FPS

There are even cases in which it happens right at the start, with a tiny window size. So it might not even be related to changing the window size, it's just how you can easily reproduce it to see these 2 distinct performance modes.

Change window size by **1 single pixel.** Your GPU is now folding proteins and computing 7 hidden dimensions indefinitely!
1 more pixel, casualy rendering some sprites.

To me it looks like the GPU suddenly has to do much more work than intended. But if there's nothing we can do about it...
If at least WebGPU would have been an option, but that just runs 3 times worse for this shader.


Eitherway thank you for your response, appreciate it.
