### ISSUE TITLE
Баг с аддонами на эффекты r365 (beta)

### ISSUE THREAD

**Issue by mAXONgH** [Scirra/Construct-bugs#7517]
## Problem description

Вылетает по ошибке unhandled rejection

## Attach a .c3p

.c3p нету, так как проблема делает краш construct 3 даже в пустом проекте.

1. Выбираю любой проект
2. Захожу в эффекты (неважно где)
3. Выбираю эффект из аддонов и вылетает ошибка: 

## Expected result

Изменить визуальное представление объекта.

## More details
проверено на Yandex Browser

r360 - r362

Неизвестно

## System details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'k$a') @ TypeError: Cannot read properties of null (reading 'k$a') at d.yIc (https://editor.construct.net/r365/projectResources.js:674:20) at new d (https://editor.construct.net/r365/projectResources.js:673:275) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at new window.nq (https://editor.construct.net/r365/projectResources.js:666:370) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at d.sRb (https://editor.construct.net/r365/main.js:2587:324) at async d.rjb (https://editor.construct.net/r365/projectResources.js:689:424) at async lOa (https://editor.construct.net/r365/projectResources.js:475:152)
Stack: TypeError: Cannot read properties of null (reading 'k$a') at d.yIc (https://editor.construct.net/r365/projectResources.js:674:20) at new d (https://editor.construct.net/r365/projectResources.js:673:275) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at new window.nq (https://editor.construct.net/r365/projectResources.js:666:370) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at d.sRb (https://editor.construct.net/r365/main.js:2587:324) at async d.rjb (https://editor.construct.net/r365/projectResources.js:689:424) at async lOa (https://editor.construct.net/r365/projectResources.js:475:152)
Construct version: r365
URL: https://editor.construct.net/r365/
Date: Tue Oct 31 2023 20:30:08 GMT+0300 (Москва, стандартное время)
Uptime: 9.5 s

Platform information
Product: Construct 3 r365 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.931 YaBrowser/23.9.3.931 Yowser/2.5 Safari/537.36
Language setting: ru-RU

WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: nvidia
Adapter architecture: turing
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features: bgra8unorm-storage, depth-clip-control, depth32float-stencil8, indirect-first-instance, rg11b10ufloat-renderable, texture-compression-bc

<details><summary>View details</summary>

</details>

**Comment by WilsonPercival** [comment]
@mAXONgH This means that the shader does not support `WebGPU`. Turn off `WebGPU` in the editor, then it won't crash.

**Comment by dop2000** [comment]
https://translate.yandex.com/en/?source_lang=ru&target_lang=en

**Comment by mAXONgH** [comment]
> ## Problem description
> Вылетает по ошибке unhandled rejection
> 
> ## Attach a .c3p
> .c3p нету, так как проблема делает краш construct 3 даже в пустом проекте.
> 
> 1. Выбираю любой проект
> 2. Захожу в эффекты (неважно где)
> 3. Выбираю эффект из аддонов и вылетает ошибка:
> 
> ## Expected result
> Изменить визуальное представление объекта.
> 
> ## More details
> проверено на Yandex Browser
> 
> r360 - r362
> 
> Неизвестно
> 
> ## System details
> Error report information Type: unhandled rejection Reason: Error: Cannot read properties of null (reading 'k$a') @ TypeError: Cannot read properties of null (reading 'k$a') at d.yIc (https://editor.construct.net/r365/projectResources.js:674:20) at new d (https://editor.construct.net/r365/projectResources.js:673:275) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at new window.nq (https://editor.construct.net/r365/projectResources.js:666:370) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at d.sRb (https://editor.construct.net/r365/main.js:2587:324) at async d.rjb (https://editor.construct.net/r365/projectResources.js:689:424) at async lOa (https://editor.construct.net/r365/projectResources.js:475:152) Stack: TypeError: Cannot read properties of null (reading 'k$a') at d.yIc (https://editor.construct.net/r365/projectResources.js:674:20) at new d (https://editor.construct.net/r365/projectResources.js:673:275) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at new window.nq (https://editor.construct.net/r365/projectResources.js:666:370) at oa.j (https://editor.construct.net/r365/main.js:1126:44) at d.sRb (https://editor.construct.net/r365/main.js:2587:324) at async d.rjb (https://editor.construct.net/r365/projectResources.js:689:424) at async lOa (https://editor.construct.net/r365/projectResources.js:475:152) Construct version: r365 URL: https://editor.construct.net/r365/ Date: Tue Oct 31 2023 20:30:08 GMT+0300 (Москва, стандартное время) Uptime: 9.5 s
> 
> Platform information Product: Construct 3 r365 (beta) Browser: (unknown) (unknown) Browser engine: Chromium Context: browser Operating system: Windows 11 Device type: desktop Device pixel ratio: 1 Logical CPU cores: 12 Approx. device memory: 8 GB User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.5845.931 YaBrowser/23.9.3.931 Yowser/2.5 Safari/537.36 Language setting: ru-RU
> 
> WebGPU information Renderer: WebGPU Supports GPU profiling: no Major performance caveat: no Maximum texture size: 8192 Adapter vendor: nvidia Adapter architecture: turing Adapter device: (unavailable) Adapter description: (unavailable) Adapter features: bgra8unorm-storage, depth-clip-control, depth32float-stencil8, indirect-first-instance, rg11b10ufloat-renderable, texture-compression-bc
> 
> View details



> Reference in new

**Comment by mAXONgH** [comment]
> @mAXONgH This means that the shader does not support `WebGPU`. Turn off `WebGPU` in the editor, then it won't crash.
Спасибо, просто не очень разбираюсь в WebGPU.
