### ISSUE TITLE
Dynamic layers goToLayout Anchor global layers GetParallaxXOrigin bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7521]
## Problem description

When I move between layouts the game freezes and an error appears in the console.

This is the minimum project I was able to do. Removing anything else no longer causes the bug.

## Attach a .c3p

[dynamic_layers_go_to_layout_anchor_global_layers_get_parallax_x_origin_bug_r365b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13231802/dynamic_layers_go_to_layout_anchor_global_layers_get_parallax_x_origin_bug_r365b.zip)

## Steps to reproduce

1. Open and run the project.
2. Press `1`.
3. Press `2`.
4. Press `3`.
5. Press `4`.
6. Press `5`.

## Observed result

<img width="930" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/49c335eb-7d75-4e93-ac70-05defe59099c">

## Expected result

The game does not freeze and there are no errors in the console.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r365b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r365 (beta)
Browser: Chrome 118.0.5993.118
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 658 mb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: amd
Adapter architecture: gcn-5
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features:

bgra8unorm-storage
depth-clip-control
depth32float-stencil8
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This looks like a complicated and potentially time-consuming issue that isn't affecting real-world projects, so closing.

**Comment by XHXIAIEIN** [comment]
> This looks like a complicated and potentially time-consuming issue that isn't affecting real-world projects, so closing.

This is actually a real problem I encountered in my current project. I asked WilsonPercival for help but had no results, and then entrusted him to help me publish an issue.

You can try to focus on investigating from these aspects:

1. In an eventsheet included in all Layouts, create a dynamic layer in `On start layout` and place it under an existing UI layer as a sublayer.

There is another key message here. Remove all dynamic layers is executed during On Start Layout. This is the direct cause of this error. If you put it on the On end of layout this error will not be triggered.

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/fafc9f32-39fa-4da5-a115-10ac3ba00001)

**Comment by XHXIAIEIN** [comment]
I recreated an example
[issue7521.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13266529/issue7521.c3p.zip)

**Comment by XHXIAIEIN** [comment]
I re-make an example base on original project
[issue7521.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13266839/issue7521.c3p.zip)
