### ISSUE TITLE
Editor Show Hierarchy with global Layer bug

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7522]
## Problem description

In different Layouts, add hierarchy to the global layer will cause the arrows of other layers to also point here.

![01](https://github.com/Scirra/Construct-bugs/assets/45864744/ce3aa211-a561-4597-9b68-bae4f07ef7e8)

![02](https://github.com/Scirra/Construct-bugs/assets/45864744/53d5924c-da7d-4cee-89af-90beecf79f66)

## Attach a .c3p
[issue-globallayer-show-hierarchy-arrow.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13235021/issue-globallayer-show-hierarchy-arrow.c3p.zip)

## Steps to reproduce
1.
2.
3.

## Observed result

See other arrows from other Layouts

## Expected result

Only display the arrow of the current Layout

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
looks similar https://github.com/Scirra/Construct-bugs/issues/7404

**Comment by DiegoScirra** [comment]
Will be fixed when the next release cycle starts.

**Comment by dop2000** [comment]
So it isn't still fixed in r268?

**Comment by WilsonPercival** [comment]
> So this isn't still fixed in r268?

@dop2000 The next release cycle begins with the version that comes after the stable one, that is, with `r369b`.
