### ISSUE TITLE
Animate error with Instagram video upload

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-bugs#7525]
## Problem description
Uploading any video export from Animate to Instagram gives an error.
![Screenshot 2023-11-03 085928](https://github.com/Scirra/Construct-bugs/assets/16654934/e75f1191-008f-41b0-ba7d-ae117464fc68)

## Attach a .c3p
[cosmi.zip](https://github.com/Scirra/Construct-bugs/files/13250504/cosmi.zip)

## Steps to reproduce

1. Load the project
2. Export video (any setting- looks like 3500 kbps is preferred)
3. "Create" new post on Instagram with the export

## Observed result
Video is uploaded, and can even be cropped, but trying to finish the post with "share" returns the error um_request_failure

## Expected result
The video should post as normal

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
As far as I'm aware Construct Animate is generating a valid video file, as it works everywhere else. Presumably this is an issue with Instagram's service so you should contact them for support.
