### ISSUE TITLE
Dark theme object property selection button not styled properly

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7527]
## Problem description
In the dark theme the object property selection button looks incorrectly styled to me

## Attach a .c3p
[objectProperty.zip](https://github.com/Scirra/Construct-bugs/files/13255182/objectProperty.zip)

## Steps to reproduce

1. make sure dark theme is enabled
2. select the 3DShape and look at the Object Face Properties

## Observed result
![ndt](https://github.com/Scirra/Construct-bugs/assets/89512047/4438702f-2d4c-4739-8987-9b45b027c29c)
white button with sharp corners

## Expected result
![dt](https://github.com/Scirra/Construct-bugs/assets/89512047/5c65114d-fed4-437b-8d16-fd0ea1dc9d2c)
typical dark theme button with "..." as text.
The button could also be a bit wider imho, so its easier to select especially for touch.

## More details
This is the case for other object properties as well, i.e. 3rd party plugins, particles etc.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
