### ISSUE TITLE
Construct 3 r365 crashing when exporting to android

### ISSUE THREAD

**Issue by TechBoxNorth** [Scirra/Construct-bugs#7529]
## Problem description

Construct 3 crashes when trying to export to any of the android options.

## Attach a .c3p

[AndroidTest.zip](https://github.com/Scirra/Construct-bugs/files/13263868/AndroidTest.zip)
rename to AndroidTest.c3p

## Steps to reproduce

1. Create a simple game
2. Export to android using any of the options like debug apk, cordova project etc.
3.

## Observed result

Construct 3 crashes but finishes the export if not shut down or restarted

## Expected result

Export to android without crashing.

## More details

**Affected browsers/platforms:** Android

**First affected release:** r365 worked fine in r364

## System details

PASTE HERE

Error report information
Type: unhandled exception
File: https://editor.construct.net/r365/main.js, line 1917, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at rr.g.li.jMa (https://editor.construct.net/r365/main.js:1917:242) at aj.g.cwc.yd (https://editor.construct.net/r365/main.js:1919:416) at https://editor.construct.net/r365/main.js:1919:139
Construct version: r365
URL: https://editor.construct.net/r365/
Date: Mon Nov 06 2023 08:34:11 GMT+0100 (centraleuropeisk normaltid)
Uptime: 1148 s

Platform information
Product: Construct 3 r365 (beta)
Browser: Chrome 118.0.5993.120
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Ti (0x00002489) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7464

Everything works fine for me. Perhaps some extension is interfering. Try to find out which one by turning off each of them one by one.

**Comment by TechBoxNorth** [comment]
The attached project doesn't use any third party extensions! I even tried to remove the touch plugin but that didn't help either!

**Comment by AshleyScirra** [comment]
We've had a bunch of reports of this and we can't figure out why it happens. It doesn't reproduce for us and the error message appears to be nonsense.

Usually such problems are caused by broken browser extensions that are interfering with Construct. Try disabling any browser extensions you have installed. It would be interesting to know which browser extension is causing this, so it can be reported to the extension developer.

**Comment by TechBoxNorth** [comment]
Ok there seems to be some problem with my google chrome installation.
Opening the project in Edge browser and exporting works fine.
Installing as app from Edge browser and again exporting to android works fine.

Sorry for wasting everybodys time :)

**Comment by baezipsa** [comment]
This source hasn't changed in a year.

Both Android and App Store builds have been successful before.
A month ago, both Android and App Store failed.
Today, Android builds. The App Store still doesn't build.

**Comment by WilsonPercival** [comment]
@baezipsa Everything works fine for me. There may be a problem with the browser extension. Try disabling one at a time to find which extension is causing the problem.
