### ISSUE TITLE
r362: Failed to open folder project message

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7534]
## Problem description

r362 included some improvements to folder projects, and now we are getting this error when trying to open a large folder project:

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/882afab4-bf0e-45e2-9ca0-a938eb3d1d00)

After a few seconds the rest of the error message appears in the console:

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/54d69887-1e03-4c60-a4b2-507409a716a6)

Oddly, the editor seems to function normally after closing this error message.

## C3P

Unfortunately, the project is too big to share - 8GB and over 14,000 files.
We will send the download link to support email.

I couldn't reproduce this issue with a smaller project (150 MB).

## More details

The happens with different project versions on different computers.

**First affected release:** no error in r361, error in r362

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r362 (beta)
Browser: Chrome 119.0.6045.106
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 265 gb
Storage usage (approx): 6.1 gb (2.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x0000164C) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
I received your project folder via email and could reproduce it. It looks like Chrome just randomly fails with weird error messages (saying files don't exist, when they do...) if too many file system operations are done in parallel, which is a problem that's come up in other places. A very large project folder doing the new reload-on-open ended up doing too many reloads in parallel which caused randomly failing file operations; adding a throttle seems to fix it, which is the same solution we've used in other cases. This is a regression since the last stable release so we'll have one more beta release before the next stable release.
