### ISSUE TITLE
Line of Sight Behavior is not working with a Tilemap with solid behavior

### ISSUE THREAD

**Issue by Kroyam** [Scirra/Construct-bugs#7536]
## Problem description

When using a TileMap with the solid behavior the Line of Sight behavior is not working as expected.

## Attach a .c3p

[TilemapBUGTest.zip](https://github.com/Scirra/Construct-bugs/files/13299604/TilemapBUGTest.zip)

## Steps to reproduce

1. In GameLayout you can see the expected behavior when the player is in the air the object is highlighted and the line is drawn.
2. In Hooktest you can see that the same object is not detecting the lineofsight event and not being highlighted
3. if you remove the condion of line of sight from the event sheet it is highlighted

## Observed result

On Hooktest the Line of sight event from the nail to the player is not being passed

## Expected result

Since there aren´t any painted tiles in the spaces between the nail and the player the Lineofsight event should pass

## More details

**Affected browsers/platforms:** 

google chrome, opera gx

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
the issue is that the origin of the Wall Nail is inside the tilemaps wall, move it out a bit and it works

**Comment by AshleyScirra** [comment]
Looks like @F3der1co is right - it's a mistake in your project, as you can't have LOS to inside a solid.
