### ISSUE TITLE
Animate HTMLElement does not export to video

### ISSUE THREAD

**Issue by pigmalien** [Scirra/Construct-bugs#7544]
## Problem description
When exporting video in Animate the HTMLElement object will not render.

## Attach a .c3p
[animatehtmlvideo.zip](https://github.com/Scirra/Construct-bugs/files/13335414/animatehtmlvideo.zip)

## Steps to reproduce

1.Open project file 
2.Export to video
3.Check the export

## Observed result
The html is not present

## Expected result
The html should be rendered.

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Beta Animate 366
## System details
Windows 11

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid this is just a limitation of exporting to video. I don't think it's technically feasible to accomplish exporting HTML elements to a video in faster-than-realtime. The current video export system only includes content of the main canvas element, and HTML elements sit on top of that and aren't included as part of the canvas image content. The web platform does not currently provide any feature to draw arbitrary HTML content to a canvas.

Possible workarounds:
- screenshot the HTML content and import as an image in a Sprite
- use the Video Recorder object (or some other screen recording tool) to record a video of the entire window/browser tab in real-time. (This also permits interactivity during the video recording.)

**Comment by pigmalien** [comment]
I was afraid of that. Thanks for looking.
