### ISSUE TITLE
missing layer exists condition

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7545]
## Problem description

After dynamic layers are supported, the condition of whether the Test layer already exists is missing. It was probably forgotten and therefore reported as a bug.

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/254faac9-246c-4596-800a-595be3fd7963)

This will avoid repeated creation of layers causing error messages on the console.
![Snipaste_2023-11-14_04-21-15](https://github.com/Scirra/Construct-bugs/assets/45864744/653811e3-bd63-49de-aa78-bdd5cb1d1802)

Looked like a suggestion, so I submitted one on the suggestion platform as well
https://construct23.ideas.aha.io/ideas/C23-I-482

## Steps to reproduce

1.
2.
3.

## Expected result

Add 'layer is exists' condition

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@XHXIAIEIN This is already implemented, implicitly: you can use the `LayerIndex(layer)` system expression. So `LayerIndex("lol")` will return `-1` to you, indicating that there is no such layer.

**Comment by AshleyScirra** [comment]
This is a suggestion and it was already filed as such so closing the issue report.

Please always make an effort to follow the [suggestion guidelines](https://www.construct.net/en/forum/construct-3/general-discussion-7/announcing-new-construct-161682) - my first question is, why can't you just give every layer a unique name? If there's no good answer to that question then we probably won't do it.

**Comment by XHXIAIEIN** [comment]
This is very useful in many global layer and global eventsheet usage:

Currently, I put all common UI on the global layer to manage, and then add the corresponding layer to the specific Layout. and include a global eventsheet. During initialization, it is very necessary to have a condition to know whether a certain layer exists in the current scene. Currently, it can only be detected using an additional instance variable. Using unique layer names also adds extra strings, which is very tedious and tedious.
