### ISSUE TITLE
SrcOriginStart and SrcOriginEnd values change when rendering a sprite mesh with one point that moves on the Z axis

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7548]
## Problem description

When a sprite mesh is rendered in 3D, the srcOrigin values change and no longer reflect the position of the texture in the spritesheet.

## Attach a .c3p

[srcOriginBug.zip](https://github.com/Scirra/Construct-bugs/files/13364012/srcOriginBug.zip)

## Steps to reproduce

1. preview
2. compare with editor

## Observed result

![chrome_UVN1Fu91kW](https://github.com/Scirra/Construct-bugs/assets/11213825/804f30db-ba17-46e8-90d2-5ca571b6ab9d)

https://github.com/Scirra/Construct-bugs/assets/11213825/71287d9d-9d34-40cd-8d16-eba5f62d9d38

And here is the same bug, but happening on another shader I'm working on

https://github.com/Scirra/Construct-bugs/assets/11213825/14ddf65d-d0d1-41c0-8c98-1457ca7f296e

## Expected result

Runtime should look the same as the editor, because the editor is correct.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is tricky as the effect compositor is designed to run in 2D so doesn't really fully support the use of 3D. However it should at least be consistent, and it should be fixed in the next release cycle (making the runtime work like the editor).

**Comment by F3der1co** [comment]
If this means no more forced predraw in 3d, this means we can do a lot of effects now that weren't possible before! :0

**Comment by AshleyScirra** [comment]
To be clear, this change only affects mesh distortion specifically; 3D objects like 3D shape still always pre-draw (as this issue did not involve them).
