### ISSUE TITLE
Error during project export for Android

### ISSUE THREAD

**Issue by Carmi333** [Scirra/Construct-bugs#7549]
## Problem description

During the export of my project, I got problems. In particular, I tried to export a 'Debug APK' and once installed on my smartphone, the app would not start and would crash.

I then tried to export the project as an 'Signed Android App Bundle' but unfortunately C3 returned an error concerning some parameters that were not configured correctly.

After several attempts, I tried exporting an example of yours provided by C3 and the error was the same. I therefore wondered whether it was an editor-related bug.

## Attach a .c3p

I tried all kinds of projects. Even yours provided as an example.

## Steps to reproduce

Exporting a project for Android. Specifically "Signed Android App Bundle"

## More details

![image](https://github.com/Scirra/Construct-bugs/assets/25287865/e73429ba-5f40-40b5-9af7-381b7a383ae1)

![image](https://github.com/Scirra/Construct-bugs/assets/25287865/28bff679-365b-4dbd-a3cd-dbd43027ce97)

![image](https://github.com/Scirra/Construct-bugs/assets/25287865/995e2463-2959-4848-b62b-a7d86627466d)

**Comment by AshleyScirra** [comment]
I tried exporting Space Blaster as a debug APK, transferred it to an Android device, and it ran fine. The build service is also used hundreds of times a day and we are not currently getting reports from other users. So I suspect it's a problem with your device - make sure you've correctly set up developer mode or it will refuse to run unknown APKs.

**Comment by Carmi333** [comment]
Thank you very much. OK for the APK debug, but about the "App Bundle".

There it just won't let me export and returns ". See screen.

Best regards.



Il giorno gio 16 nov 2023 alle ore 12:52 Ashley (Scirra) <
***@***.***> ha scritto:
