### ISSUE TITLE
Drawing Canvas "save Image" doesnt accurately save the size as requested:

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-bugs#7550]
Drawing Canvas "save Image" doesnt accurately save the size as requested:

I have a PNG size =  (120x123) 
I paste it into the Drawing Canvas and I want to save it at (122x125), basically two pixels extra on each axis. 

For some reason, it doesn't accept this calculation that I save into the Global Variables (W & H)
![2023-11-16 02 11 45](https://github.com/Scirra/Construct-bugs/assets/41597700/0b063241-6e16-487b-8cf4-c7f7527813a5)

Which results in:
W = 122
H = 125
Though it saves the Image at (122x124)

![2023-11-16 02 10 21](https://github.com/Scirra/Construct-bugs/assets/41597700/3c7c21ac-a3b8-4e84-b82d-3e27f418139b)

But weirdly it accepts this one which is the exact same Value:  So here it saves the Image at (122x125) as requested.
![2023-11-16 02 13 49](https://github.com/Scirra/Construct-bugs/assets/41597700/eee45807-bea0-4f98-a295-e4df2ae188d5)

Also, if you put the value directly it works too:
So here it saves the Image at (122x125) as requested.
 
![2023-11-16 02 15 17](https://github.com/Scirra/Construct-bugs/assets/41597700/db8c024a-6ed0-4515-8fe9-9fed40ab27da)

It looks like despite the 3 examples passing the same exact value the only difference is how you got to those values, some are accepted and others are not.

Results:
![ssd](https://github.com/Scirra/Construct-bugs/assets/41597700/a5c924d2-9689-4c27-af4b-941c418c8c31)

## Attach a .c3p

[Canvas BUG2.zip](https://github.com/Scirra/Construct-bugs/files/13371763/Canvas.BUG2.zip)

## Steps to reproduce

1. Run the project
2. Wait until it downloads the 3 PNGs
3. Check the -----> "Not Working.png"   

## Observed result

"Not Working.png" has size 122x124

## Expected result

That the "Not Working.png" saves at the requested size 122x125

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r362
r367

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r367 (beta)
Browser: Chrome 119.0.6045.159
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 85 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 (0x00001BE1) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
@Tarek200 Can not reproduce. Everything works well for me. Saves 122x125, as it should.


https://github.com/Scirra/Construct-bugs/assets/91274932/9e9d8ce1-34b2-4245-b5cc-1fd559018d90

**Comment by Tarek200** [comment]
Thanks @WilsonPercival, that's really weird as I can reproduce it all the time:

https://github.com/Scirra/Construct-bugs/assets/41597700/dc7f16d5-eb9c-4e87-bcb4-3604815f1ed7

It may depend on the device, as the calculation is done by Device PixelRatio but the end result should be (122x125) in any device. 
Im testing on: 
Chrome 
Monitor (1920x1080) 
Not sure if that makes any difference

The question is why the other two don't fail when I pass the same (122x125) value.

Thanks for testing though I appreciated it.

**Comment by WilsonPercival** [comment]
@Tarek200 I have 1920x1200.

**Comment by Tarek200** [comment]
**I forgot to mention that:**

**It works with these Full-Screen Modes:**
-OFF
-Scale Inner 
-LetterBox Integer Scale 


**It doesn't work with these Full-Screen Modes:**
-Scale Outer
-LetterBox Scale


https://github.com/Scirra/Construct-bugs/assets/41597700/a835fc45-382d-4f46-b485-9cbf2189a952

**Comment by WilsonPercival** [comment]
@Tarek200 I was able to repeat the bug myself. If I set `Viewport size` to `720x1081`, then I will download an image of `121x125` size.

**Comment by WilsonPercival** [comment]
@Tarek200 I understood what the problem was. This is a bug in your events. You output the value of the variable `W` to the `TextInput` object and get `122`. Actually this is not true. `TextInput` rounded the value to integers. This is why it is always better to use the console.

<img width="121" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/8d43eb85-f4ec-4f49-ba36-6ae9461e0b1c">

**Comment by AshleyScirra** [comment]
This looks like a mistake in the project, as it calculates fractional values but doesn't make any effort to round them. If you pass fractional values to the Drawing Canvas save image position/size, IIRC it just rounds them down, which might not be what you want (e.g. 121.999999999 will be rounded to 121, not 122). So you probably want to put in some of your own round expressions (or ceil to round up) and make sure it does the rounding that you want. Note as well that the device pixel ratio can be fractional too, depending on the system.

**Comment by Tarek200** [comment]
@WilsonPercival Thanks but I do use the Browser Logs all the time I have been a long time working in Construct, that's the first thing I checked and there are no fractions.
Also, TextImput should never round the numbers I think you have a mistake in your events.

**Comment by Tarek200** [comment]
@AshleyScirra Is not passing Fractional numbers as I explained before the 3 examples are passing the exact:
W = 122
H =125

There are no fractions to round as is already a whole number so I still dont understand why it works with the last two groups but not the first one, there is something weird going on there as it messes up the values.
If the 3 group examples are all passing the exact (122x125) they should all fail or all work as intended dont you think? 
This for me is still a bug, can you check please as I already wasted more than a week with this? 

Here is a video showing the Browser Logs passing the whole numbers:
W =122
H =125
https://github.com/Scirra/Construct-bugs/assets/41597700/5b879eba-e826-40c9-b830-529499a48ae6

**Comment by Tarek200** [comment]
@AshleyScirra 

Just to make it clear, it shouldn't be any fractional numbers, we always have whole numbers because we (Dive and then Multiple) by the same number so it is impossible to get fractional numbers:

**Example**
Original ImageWidth = 120
Original ImageHeight = 123

DevicePixel_W = 0.862037037
DevicePixel_H = 0.862037037


Set DrawingCanvas Width to ----- > (120 / 0.862037037) = 139.205157
Set DrawingCanvas Height to ----- > (123 / 0.862037037) = 142.685286


**DrawingCanvas Save Image:**
Width ----- >  (139.205157 *  0.862037037) = 120 
Height ----- >  (142.685286 *  0.862037037) = 123

It always gives you back the original Number that you divided so is not possible to ever have fractional numbers if the original size starting number is a whole number.

===========================

**So that was the basics:**

Now as I explained if I want to Download the image two pixels bigger. So we do the same thing but add that extra two pixels on each axis.

**Example**
Original ImageWidth = 120
Original ImageHeight = 123

DevicePixel_W = 0.862037037
DevicePixel_H = 0.862037037


Set DrawingCanvas Width to --- > ((120+2)  / 0.862037037) = 141.525243
Set DrawingCanvas Height to --- > ((123 + 2) / 0.862037037) = 145.005372


DrawingCanvas Save Image:
Width ----- >  (141.525243 *  0.862037037) = 122
Height ----- >  (145.005372 *  0.862037037) = 125


So this means the explanation that you gave about the rounding doesn't apply here as we dont have any "Fractional Numbers" we pass only whole numbers to the DrawingCanvas. The issue has to be something else then.

**Comment by Tarek200** [comment]
There is definitely a bug in there as something weird is happening under the hood, it feels like you have some code rounding which affects numbers that dont have fractions therefore it shouldn't be rounded, looks like that is why it's saving these weird wrong sizes.

**Here is a more clear Example:**
 
**1-In the first I set the Variables:**
W = (DrawingCanvas.Width  * DevicePixel_W) ------>Results  in 122
H = (DrawingCanvas.Height *  DevicePixel_H) -----> Results  in 125
But DrawingCanvas saves the Image at 122x124 

**2-In the second test, I set the Variables:**
W = 122
H = 125
Directly without any calculation in between, but DrawingCanvas saves the Image at 122x125 as intended.

I log the variables (W & H) so you can see that both tests have the exact same values but one works and the other one does not.
This is really weird as it doesn't make any sense, what is going on here?
Both tests should save at the exact same values as the variable is set to 
W = 122
H = 125
in both cases

**Here is the project:**
[Canvas BUG5.zip](https://github.com/Scirra/Construct-bugs/files/13385309/Canvas.BUG5.zip)


**Video:**

https://github.com/Scirra/Construct-bugs/assets/41597700/951a9ed5-5ebb-4c43-bcc0-24ae481a067d

**Comment by WilsonPercival** [comment]
@Tarek200 You're making the same mistake again: instead of simply printing the value of the variable, you concatenate it with a string like this: `"W = " & W`. Please look at this report: https://github.com/Scirra/Construct-bugs/issues/5463

I also output the variable values to the console, look:

[Canvas BUG.zip](https://github.com/Scirra/Construct-bugs/files/13386072/Canvas.BUG.zip)

**Comment by Tarek200** [comment]
> @Tarek200 You're making the same mistake again: instead of simply printing the value of the variable, you concatenate it with a string like this: `"W = " & W`. Please look at this report: #5463
> 
> I also output the variable values to the console, look:
> 
> [Canvas BUG.zip](https://github.com/Scirra/Construct-bugs/files/13386072/Canvas.BUG.zip)

Thanks @WilsonPercival 

Hoh I have been using Construct extensively for more than 8 years and I never run into that problem)) what a surprise, it looks like a very special case according to Ashley on that bug.
Thanks for the help mate, that was great, I finally can sleep in peace lol, as it has been hunting me this bug for quite some time.

Now what Ashley said makes sense as DrawingCanvas tries to round the Number Down from (124.99999999999999) to 124
I think to avoid this C3 should apply automatically a round-up to the final value for Variables with "Floating point calculations" such as this Ceil(124.99999999999999)
