### ISSUE TITLE
Window disappears bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7552]
## Problem description

The window disappears.

## Attach a .c3p

<img width="311" alt="attach" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/941ae613-73fc-435c-a590-c2bdf2aed57a">

## Steps to reproduce

1. Make sure you have `Free edition`.
2. Open `Ghost Shooter in code`.
3. Create a new event sheet.
4. Click `Add event`. Since the project uses more than is available in the `Free edition`, you cannot edit it, so the `Free edition limit` window will pop up. Click `Cancel`.
5. Remove all scripts from the project to remove the editing restriction.
6. Click `Add event`. Please note that when the window opens, it will immediately disappear.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/842e22a1-b043-4d77-b412-c49bb6fa2e03

## Expected result

The window should not disappear.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r367b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r367 (beta)
Browser: Chrome 119.0.6045.124
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 1.1 gb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by XHXIAIEIN** [comment]
I've been running into this a lot lately, but I don't know how to reproduce it. It seems that this problem only occurs in the window of the selected object. When pressing Enter, it can enter the System object. At this time, the conditions and actions windows will not disappear again. If I restart the browser it works normally again.

**Comment by OverboyDev** [comment]
I also ran into a similar issue recently.

**Comment by AshleyScirra** [comment]
I've looked in to this and it seems like possibly a browser bug. It only happens with UI animations enabled, so you can turn that off in settings to work around it if it's annoying you. The problem seems to be the first time the dialog is shown and hits the free edition limit it's immediately cancelled, and so there is an extremely brief fade-out animation. However despite that animation ending it seems the browser still leaves an opacity of 0 on the dialog which makes it invisible. As far as I can tell our code is correct and the animation finishes and no longer exists, but it still seems to be having an effect on the dialog opacity.

The dialog system is highly complex and so I'm not sure filing a browser bug would be feasible, and I found what seems like a reliable workaround, so hopefully it's sorted. But workarounds sometimes have side-effects so we will have to see how it goes over the next few beta releases. If anything else comes up we might have to revert the fix and file an issue anyway.
