### ISSUE TITLE
I found a way to make text rendering faster while also properly handling kerning

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7555]
## Problem description

Text rendering at the moment suffers from being pretty slow, and I think I found a way to make it faster.
For context, for a while I've been maintaining an experimental addon that overwrites part of the text renderer to add some changes I feel are necessary. So far this has been fairly simple stuff, namely:

- Adding an Angles tag
- Making the outline from the outline tag render behind the text so it actually functions as an outline
- And most importantly for today's bug report, changes how text is drawn to fix kerning issues where the text would pop into position after the end of a text animation.

https://github.com/Scirra/Construct-bugs/assets/11213825/240b1a6a-dc0c-4a56-bf03-b4b834129299

A few days ago, I got a bug report about my kerning fix not working as intended. While kerning was properly handled on any given line, the "correct" size was not taken into account for word wrapping and there was still some amount of popping

With my old kerning fix

https://github.com/Scirra/Construct-bugs/assets/11213825/f7b81f51-caa4-4c0a-90ed-b1a163c675e9

Without my fix

https://github.com/Scirra/Construct-bugs/assets/11213825/1788e046-3b67-4002-9b03-7dcef5b73d79

This meant I had to add the same kerning measurement code to the MeasureLine function of the WordWrap class, but doing this caused MASSIVE lag. I tried a LOT of things to make it better, and in the end I ended up caching kerning measurements and it made it drastically better (run at 120fps) but CPU Util was still through the roof (80% CPU util while 4 text are being animated, vs 60% without my fix).

Now, 60% is still a massive number and it makes no sense that the text renderer would be this slow, so I dug some more, and it sounds like the culprit lies in the _WrapText function calling MeasureLine every time it adds a word to a line.

In a naïve scenario, this is fine because the line is created word by word and text mostly never changes, but my [Animate Text addon](https://github.com/skymen/animate-text) this creates a worst case scenario where:
1- Graphemes are being regenerated on every frame
2- Lines are being created character by character

So, this made each line call measureText O(n²) times where it should only ever need to call it (O(n) times.
From what I can gather, this was also an issue caused by kerning since measuring word by word did not actually guarantee accurate line measurements since Kerning offsets can come and change values.

However, since I'm already caching kerning values, I can just add them back, and it's all back to being good.

In conclusion, the new method handles kerning properly AND runs faster and I don't think the same solution is possible without properly handling kerning accross fragments.

## Attach a .c3p
This c3p requires both my [Animate Text addon](https://github.com/skymen/animate-text) and my [Experimental Text Fix addon](https://github.com/skymen/experimental-text-fix) (Downloadable from releases)

[kerning measure issue.zip](https://github.com/Scirra/Construct-bugs/files/13400073/kerning.measure.issue.zip)

## Steps to reproduce

1. Preview in debug mode
2. Press any key on the keyboard to start the animation
3. Remove Experimental text fix addon
4. Preview again and compare

## Observed result

Vanilla runs slowly and causes CPU Util to skyrocket and has letters suddenly popping into place at the end

## Expected result

My fix runs a bit better (still not ideal, but easily has 10% CPU Util less) and properly handles Kerning

## More details

Now, let me be clear, this is not me telling you I think my fix should be implemented as is. A lot of my code is of questionable quality because of the hacky nature of this addon. I also rewrote the C3.SplitGrapheme to make it ever so slightly faster because it is being called VERY often and is partially to blame for the performance issues. However, the way I rewrote it might cause issues in some edge cases so that needs to be taken with a grain of salt.

However, I think making the WrapText function faster inherently depends on having the kerning cache because otherwise I can't see any way to properly measure a line without having to measure it again and again.

But there might be a better way to get kerning offset values that don't require measuring text 3 times, since the data should be somewhere in the font file. I mean, the browser is getting it from somewhere, right?

Let me know if you need me to explain in details the thought process behind each function change and I will gladly do so, so if you're interested in reimplementing this properly you can do it with better code quality.

**Affected browsers/platforms:** I only tested Chrome, sorry :(

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
I can confirm the performance improvement on my end:
unlimited full frames: 
- without fix fps drop down to 400
- with fix fps drop down to 600

I really hope these improvements get brought to vanilla (also including the outline and angle fixes)!

**Comment by skymen** [comment]
Tested with a few lines with only dots in unlimited full frames and I get:

- 135 fps with fix
- 80 fps without fix

Both were at 80% CPU Util, but I guess this is not relevant in the case of unlimited full frames

In Unlimited ticks only I get:

- 195 fps with fix
- 80 fps without fix 

Again, both were around 55% CPU Util

**Comment by skymen** [comment]
Update:

Someone reported to me a bug with my approach. I haven't looked at it yet, but I'd rather update this thread in case the fix takes too long.

![image](https://github.com/Scirra/Construct-bugs/assets/11213825/52dcf8db-93bd-4c8a-9534-01bc4f8b125d)

![image](https://github.com/Scirra/Construct-bugs/assets/11213825/47a83516-5e6e-4077-9886-6c095f55ce14)


Repro:

[AnimateText_ParagraphSwitchBackBug_V2 - Copie.zip](https://github.com/Scirra/Construct-bugs/files/13403800/AnimateText_ParagraphSwitchBackBug_V2.-.Copie.zip)

**Comment by skymen** [comment]
Turned out to be a simple fix that just required an edge case check. Doesn't seem to affect performance at all
https://github.com/skymen/experimental-text-fix/releases/tag/skymen_ExperimentalTextFix-2.0.0.4.c3addon

**Comment by AshleyScirra** [comment]
Does your addon hack the internals of the text layout engine? It is very difficult to know what to do about issues involving thousands of lines of third-party code. It is not something we would normally support.

**Comment by skymen** [comment]
Hi, the bug I am reporting is about the Vanilla C3 renderer. My addon does not create the issue, it fixes it, and to do so it does hack the layout engine, yes

**Comment by skymen** [comment]
[wavy text performance issue.zip](https://github.com/Scirra/Construct-bugs/files/13440855/wavy.text.performance.issue.zip)

Here you go

**Comment by AshleyScirra** [comment]
That project runs at 60 FPS for me. So it seems to be performing OK. So what's the problem?

If you hack the engine to do crazy stuff and ends up being slow, I'm afraid that's not something we can support. I have tried to always be clear: I strongly recommend you do not hack the engine, if you do then we will not provide any support, and all your code could permanently break at any time.

**Comment by BluePinStudio** [comment]
The minimal project @skymen uploaded runs at 50-60fps for me while using >50% of my CPU.

**Comment by skymen** [comment]
The project uses 60% of my CPU just to render 4 pieces of text AND kerning is wrong which can create even more visual issues when typing text (as shown in the videos above). It should not be taking 60% of my CPU to render 4 pieces of text.

Again, my hack does not make it slower it makes it faster AND fixes the kerning issue. My hack isn't the issue here. I am asking if the changes I've done can be included in the engine so I don't have to maintain a complex hack to make text rendering a bit better.

**Comment by AshleyScirra** [comment]
Sorry, we can't accept proposed code changes by filing issues. This tracker is meant to be a bug report process, not a code change proposal system. Construct has hundreds of thousands of lines of code, and it's difficult enough for us to change it, let alone outsiders who aren't aware of things like backwards compatibility considerations, workarounds, future plans, and architectural concerns. The blog post I wrote a while back on [the unexpected complications of minor features](https://www.construct.net/en/blogs/ashleys-blog-2/unexpected-complications-1535) essentially argues that in complex software there is no such thing as a small change, and even trivial code changes can have extremely difficult consequences, let alone significant changes or overhauls to existing parts of the codebase, let alone all that done by people who don't already have familiarity with the codebase, how it has evolved over time, and the reasons it is designed the way it is.

This kind of thing is what the suggestions platform is for, so please file such requests there. I'd add it's important to include the use case. For example in this case here, does anyone really need a whole paragraph of wavy text? I'd have thought it would typically be for emphasis of a single word or phrase, or an animated title screen. In that case optimising benchmarks like this will not bring any meaningful improvement to real-world games, which makes it essentially a waste of our limited development time. For this reason we have to focus our limited resources on things with compelling use cases.
