### ISSUE TITLE
Duplicating layout with Global layers make conflicting Global layers

### ISSUE THREAD

**Issue by Fishaphrodite** [Scirra/Construct-bugs#7556]
## Problem description

It is possible in construct 3 r358 stable to have multiple Layers with Global property to "Yes" having the same name, instead of having only one of them being "Yes" and the others being "Overriden" (see the c3p for an exemple, and the steps to reproduce); seems to have changed between release 337 and 338

## Attach a .c3p
[globalLayerIssue.zip](https://github.com/Scirra/Construct-bugs/files/13400367/globalLayerIssue.zip)

Layout 1 and Layout 2 have a global layer called "Layer 1" with the Global parameter set to Yes; they also have a different content; meanwhile Layout 3 also has it, but with its global parameter set to "Overriden"

## Steps to reproduce

From a new empty project :
1. Add a new layer to the default Layout 1, call it Layer 1
2. Set that layer as Global
3. Right click on the Layout 1 and use the "Duplicate" option, Name the new Layout "Layout 2"
4. Layout 1 and Layout 2 both have the "Layer 1" being set to Global : Yes, as a result, modifications to Layout 1's won't be copied into Layout 2, and vice-versa
5. Create a new Layout, call it "Layout 3"
6. Manually create a Layer in Layout 3, and call it Layer 1 (it's property will be set to Overriden, as normally expected)
7. Any changes to Layout 2's Layer 1 will carry on Layout 3's Layer 1 only, any changes to Layout 1's Layer 1 won't affect anything

## Observed result

When a layout is duplicated while being a Global Layer reference, the newly created layout will also have this property, creating a conflict later on, this becomes a problem especially after duplicating one of those multiple times.

## Expected result

The layout resulting of the duplication should have its layer Global status being "Overriden"

## More details

**Affected browsers/platforms:**  Tested on Chrome and Firefox in a linux mint environment, it is an editor bug

**First affected release:** seems to occur starting **release 338**

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r358 (stable)
Browser: Firefox 119.0
Browser engine: Gecko
Context: browser
Operating system: Linux (unknown)
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0
Language setting: en-US
Local storage

Storage quota (approx): 91 gb
Storage usage (approx): 624 mb (0.7%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    UI effects are disabled in settings.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Intel
Renderer: Intel(R) HD Graphics
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 255
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    WEBGL_compressed_texture_astc
    WEBGL_compressed_texture_etc
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context

Audio information

System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)
    WebM Vorbis (audio/webm; codecs=vorbis)
    Ogg Vorbis (audio/ogg; codecs=vorbis)
    MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav; codecs=1)

Supported encode formats:

    WebM Opus (audio/webm; codecs=opus)
    Ogg Opus (audio/ogg; codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm; codecs=av01.0.00M.08)
    MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
    WebM VP9 (video/webm; codecs=vp9)
    WebM VP8 (video/webm; codecs=vp8)
    Ogg Theora (video/ogg; codecs=theora)
    H.264 (video/mp4; codecs=avc1.42E01E)

Supported encode formats:

    WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This works properly in the latest beta and latest stable. It was fixed in r359 during the last beta cycle.
