### ISSUE TITLE
Pathfinding failed to trigger "On arrived" when using debugger "CPU profiler" tab

### ISSUE THREAD

**Issue by Nabu0001** [Scirra/Construct-bugs#7558]
## Problem description
The Pathfinding Behavior failed to trigger the "On arrived" event when using the debugger "CPU Profiler" tab. When using other tabs, it goes back to normal and further pathfinding requests work again. But as soon as the CPU Profiler tab is opened, any object moving along the path will just stop at path end without triggering "On arrived"

## Example .c3p
https://www.dropbox.com/scl/fi/10ce7oardb9p25jh8d0il/Construct3-r358-r367-BUG-Pathfinding-CPU-Profiler.c3p?rlkey=p32r5ikoxh3qqzb2z2u29r5ac&dl=0

## Steps to reproduce
- Open the project with debugger
- Click anywhere to move blue sprites via Pathfinding Behavior
- They should change color from blue to red upon arriving
- Open the CPU Profiler tab while sprites are moving

## Observed result
- Blue sprite are not turning to red upon arriving, because "On arrived" was not triggered

## Expected result
- "On arrived" should trigger correctly to allow debugging

**Affected browsers/platforms:** 
Tested on Brave and Edge

**First affected release:** 
From at least r358 to r367 but experienced with older versions

**Comment by AshleyScirra** [comment]
Fixed for next beta.
