### ISSUE TITLE
Dark Theme Boolean Issue [AGAIN]

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#7560]
## Problem description
Reported here but no answer so I create new issue: https://github.com/Scirra/Construct-bugs/issues/3360#issuecomment-1807860772
Dark theme don't show boolean if they have different values. (One sprite has true one sprite has false instance variable.)

## Attach a .c3p

[Boolean.zip](https://github.com/Scirra/Construct-3-bugs/files/3642466/Boolean.zip)

## Steps to reproduce

1. Use dark theme.
2. Select all sprites.
3. Look test instance variable. It is shows they all false.

## Observed result

![image](https://user-images.githubusercontent.com/54614906/65432080-4424e100-de23-11e9-99ca-61c5e66b3ba6.png)

## Expected result

Should be show similar Default theme.

## More details
I think you can check Light theme too. I didn't check because I don't wanna lost my theme settings.

**Affected browsers/platforms:** Chrome/Firefox/

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
