### ISSUE TITLE
VideoRecorder On Recording Ready trigger not working on iPhone after app is suspended while recording is in progress.

### ISSUE THREAD

**Issue by letnrodrigues** [Scirra/Construct-bugs#7562]
## Problem description

On iPhone, if you minimize your browser while recording your camera with the VideoRecorder plugin, the trigger "On Recording Ready" won't fire after the page is resumed and no errors are shown in console.
We've observed it on Safari/Chrome/Firefox running in both iPhone 7 with iOS 15.7.9 and iPhone 12 with iOS 17.1.1.

## Attach a .c3p

This is reproductible in the Camera Input c3 example. I've attached it here anyway.
[Camera Input Example.zip](https://github.com/Scirra/Construct-bugs/files/13430897/Camera.Input.Example.zip)

## Steps to reproduce

1. Run the Camera Input example project on iPhone (preferably the models we've tested with)
2. Click "Start Recording" button
3. Minimize the browser with the home button while the recording is in progress. You have to minimize the entire app, simply changing tabs inside the browser won't cause problems.
4. Open any other app.
5. Go back to the Camera Input page and click "Stop".
6. Observe that the download button never gets enabled. "On Recording Ready" is never triggered and the trigger "On Recording Error" won't be fired either.

## Observed result

The download button never gets enabled. "On Recording Ready" is never triggered and the trigger "On Recording Error" won't be fired either.

## Expected result

It's expected that either "On Recording Ready" or "On Recording Error" will fire. 

## More details

We've tested it with Safari, Chrome and Firefox on our iPhones and all of them had this issue and there were no errors logged in console. Android phones did not have this problem in any situtation we've tested.

**Affected browsers/platforms:** 
Safari/Chrome/Firefox running on iOS. Not observed in any other platform.

**First affected release:** 
Observed in r358 stable, unsure about previous versions.

**Comment by AshleyScirra** [comment]
If this works on other systems and is only a problem on iOS, then the most likely explanation is a bug in Safari. (Note that since Apple ban other browser engines on iOS, Chrome, Firefox, Edge and any other available browsers are in fact just skins over the Safari browser engine.) In this case the best approach is to report it directly to Apple, so I would ask that in this case you first file the issue with Apple here: https://bugs.webkit.org/
