### ISSUE TITLE
Z-Elevation Missing on some drawing object

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7563]
## Problem description
A property, actions and an expression for z-elevation are missing on some drawing objects. The  z-elevation can be changed via js and it seems to work perfectly. So this seems like an oversight.
The objects are:
- DrawingCanvas
- QRCode
- UserMedia
- Video

Imo, ideally all drawing objects should have z-elevation (side node: maybe it should even move into the Position properties and be renamed to Z, but that's not relevant for this)

## Attach a .c3p
[zElevation.zip](https://github.com/Scirra/Construct-bugs/files/13437885/zElevation.zip)

## Steps to reproduce

1. project just shows they can be moved on the z axis via js

## Observed result
can be done with js but not inside the editor or events.

## Expected result
can also be done in editor and events.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Added Z elevation actions for the next beta.
