### ISSUE TITLE
WebView2 exported game has default controls

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#7565]
1 - Export a game for windows with VW2

2 - Play the game

3 - Press F5 -> game refreshes like a browser page - wat?
This along with an array of default controls for browser.

You can use js code to prevent it:
> document.addEventListener('keydown', function(event) {
	event.preventDefault();
	});

But that also prevents worker mode...

**Comment by WilsonPercival** [comment]
@DinoSystem I found a workaround: if you put the code in `HTMLElement` it will work in worker mode too. But I'm not sure if this is the best approach, maybe someone can suggest a more correct one.

[prevent_default_in_worker_workaround.zip](https://github.com/Scirra/Construct-bugs/files/13440276/prevent_default_in_worker_workaround.zip)

**Comment by AshleyScirra** [comment]
It looks like this affects F3 (find in page), F5 (reload), and F7 (caret browsing). Are there any other default controls you meant? It's useful to be comprehensive otherwise I may well miss something you already knew about.

**Comment by DinoSystem** [comment]
> It looks like this affects F3 (find in page), F5 (reload), and F7 (caret browsing). Are there any other default controls you meant? It's useful to be comprehensive otherwise I may well miss something you already knew about.

There's also Alt+Shift prompting language selection, and context menus right-clicling on form controls (in my game i still use loading bars and textboxes)

And possibly something I missed as well..

**Comment by AshleyScirra** [comment]
I think Alt+Shift is a system shortcut rather than a shortcut in the app, and context menus on form controls is by design.

**Comment by AshleyScirra** [comment]
Blocked the F3, F5 and F7 shortcuts in WebView2 for the next beta.

**Comment by skymen** [comment]
I'll be honest, this is a problem that takes 3 lines of JS to fix, and if you don't wanna use JS, you can have an event sheet with all the annoying keys as "on key triggered" events.

I don't think a predefined list of "annoying keys" that C3 already disables is a good idea. Sometimes you might want these keys to have the default behavior, and sometimes you might need more anyway, so whatever the list it will never be perfect.

If there was a way to let the user define what keys he wants to disable, why not. The only issue atm with events is that you can't disable key combos (like CTRL+F) with events, only JS
