### ISSUE TITLE
Event editor: search results for objects is inconsistent

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7575]
## Problem description

There are many windows in the event editor that allow you to pick an object. 

In their search windows you have a way to search for an object:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/ba8ca864-8a1c-4f46-9fd8-29615530b9ac)

Most windows it will show me the best result, in the same way.

But there are times where the search works differently for some reason, like when picking an object with a "create" action, or "replace object" action:

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/51f32999-7d76-48f6-bd19-8fd42f0db8eb)

## Attach a .c3p

[searchInconsistent.zip](https://github.com/Scirra/Construct-bugs/files/13465835/searchInconsistent.zip)

## Steps to reproduce

1. Add an action, and search "ore"
2. Select an object to create, and search "ore"
3. Replace an object in an event, and search "ore"
4. Add a condition, and search "ore"

## Observed result

Sometimes the sprite "ore" will be first result, other times it's the last result

## Expected result

"Ore" should always be seen as the first result when it is what is searched for.

Having different windows have different methods of searching, despite the window looking very similar, is very confusing and misleading.

Expect them all to use the same search style.

## More details

Chromium, r368, Win 10

**Comment by AshleyScirra** [comment]
Technically there are two different dialogs used for these features, and they do indeed have different sort ordering. Aligning them to use the same result ordering makes sense, and that's done for the next beta.
