### ISSUE TITLE
Cannot Change hierarchy Select Mode After changing to "All"

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-bugs#7579]
## Problem description

When you have 2 object a parent and a child, and you set the Select Mode to "All" on the parent, the select-mode property disappears and there is no easy way to switch the select-mode after that.

Not sure this is a new issue?  have never used select mode before?

## Attach a .c3p

** rename zip file to .c3p
[select-mode-heirarchy.zip](https://github.com/Scirra/Construct-bugs/files/13467881/select-mode-heirarchy.zip)

## Steps to reproduce

1. Create empty project
2. Create 2 sprites objects
3. add one as child of the other
4. set the parents select mode to "all"

## Observed result

At this point the select mode property disappears from the property bar, and there is no easy way to set the select mode, a work around is to open the z-order bar and select the parent object to be able to set select mode back.

## Expected result

After setting select mode, that property should not disappear, you should be able to set select-mode after it has been changed to all

## More details

**Affected browsers/platforms:** 

**First affected release:** 

latest-stable  r368

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368 (stable)
Browser: Edge 119.0.2151.72
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 560 gb
Storage usage (approx): 160 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment]
btw I wrote a suggestion for this many month ago: https://construct23.ideas.aha.io/ideas/C23-I-159
