### ISSUE TITLE
collision not working as expected after collision cell size was changed

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7585]
## Problem description
collision not working as expected after collision cell size was changed

## Attach a .c3p
[collisionCellsBug.zip](https://github.com/Scirra/Construct-bugs/files/13491174/collisionCellsBug.zip)

## Steps to reproduce

1. drag the red sprite over the violet sprite
2. see alerts 
3. move sprite off again
4. click the button
5. drag the red sprite over the violet sprite again
6. observe alerts
## Observed result
in the first overlap alert 1 and 2 runs, in the second overlap, after the collision cell size changed, only alert 2 runs

## Expected result
in both case alert 1 and 2 runs

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
