### ISSUE TITLE
Particles thrombus WebGPU bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7587]
## Problem description

When I start the game I see a white square. `WebGL` works well.

Please note that the `Fullscreen quality` parameter is set to `Low`. The `Bulge` effect also hangs on the layout. There are also two effects `Glow horizontal` and `Glow vertical` hanging on the particles. Also on the particles the value of the `Blend mode` parameter is indicated as `Additive`. Also on particles the value of the `Rate` parameter is indicated at `0`.

## Attach a .c3p

[particles_thrombus_web_gpu_bug_r369b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13497283/particles_thrombus_web_gpu_bug_r369b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

<img width="335" alt="webgpu" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/1e33003f-7ffb-44cf-af7c-cc238e7a81de">

## Expected result

<img width="332" alt="webgl" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/e40711e9-57fe-42f5-9b8e-fe084201d663">

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r369b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r369 (beta)
Browser: Chrome 119.0.6045.160
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 102 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: amd
Adapter architecture: gcn-5
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features:

bgra8unorm-storage
depth-clip-control
depth32float-stencil8
float32-filterable
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
I spent a while debugging this but just can't figure it out. It also seems to require an extremely specific combination of settings and features: removing/changing any of the particle effects, its blend mode, the layout effect, the fullscreen quality, or the particle rate, prevents the issue from happening. Given the difficulty of the bug and the unlikely combination of settings I don't think this is worth the likely large amount of development time it would take to fix. If this ends up occuring in a real-world project we could review again, but it seems unlikely that will be the case.

**Comment by WilsonPercival** [comment]
> I spent a while debugging this but just can't figure it out. It also seems to require an extremely specific combination of settings and features: removing/changing any of the particle effects, its blend mode, the layout effect, the fullscreen quality, or the particle rate, prevents the issue from happening. Given the difficulty of the bug,the unlikely combination of settings, and the ease of a workaround (just make it invisible and the square goes away) I don't think this is worth the likely large amount of development time it would take to fix. If this ends up occuring in a real-world project we could review again, but it seems unlikely that will be the case.

@AshleyScirra 

https://github.com/Scirra/Construct-bugs/assets/91274932/03a9416f-65b5-4c2d-8287-8de1d3fd297a

**Comment by AshleyScirra** [comment]
Oh, right. It's useful to refer to such things in the original report to make it clear it affects a real project.

I still don't understand why it happens, but I added a hack in the engine to work around it. Hopefully this won't come back to haunt us...
