### ISSUE TITLE
Error on startup 

### ISSUE THREAD

**Issue by EdinoroGoK** [Scirra/Construct-bugs#7590]
## Problem description

Error loading  Construct

## Attach a .c3p

Screenshot 

## Steps to reproduce

1. Launching Construct in a browser
2. Launching the PS version Construct 
3.

## Observed result

error

## Expected result

Start  Construct

## More details

I encountered this problem a long time ago, a simple change of browser helped me, now I've encountered it again. Only my "solution" doesn't work anymore, tried all browsers. The funny thing is that it works on my laptop, but not on my computer. The provider is the same. Browser is the same.

**Affected browsers/platforms:** 

r368.2

**First affected release:** 

## System details

<details><summary>View details</summary>

fetching loader/lang/precompiled-it-IT.json(500)
![screen](https://github.com/Scirra/Construct-bugs/assets/70941212/b7e946c9-b9b0-44fc-a41e-ed5d18900bd2)

</details>

**Comment by WilsonPercival** [comment]
@EdinoroGoK Does it work in the incognito tab?

**Comment by EdinoroGoK** [comment]
@WilsonPercival yes

**Comment by WilsonPercival** [comment]
> @WilsonPercival yes

@EdinoroGoK In this case, just clear the cache.

**Comment by AshleyScirra** [comment]
It works for me and unfortunately there is not enough information in the report for us to be able to investigate further.

Things to try:

- Disable any browser extensions, as they can sometimes interfere with Construct and cause problems
- Clear the browser cache and try again
- Use a private browsing window
- Use a different browser

**Comment by EdinoroGoK** [comment]
@AshleyScirra Cache cleaned, I wrote that it happens in any browser
