### ISSUE TITLE
Physics + timescale Bug 

### ISSUE THREAD

**Issue by MrPhap** [Scirra/Construct-bugs#7593]
## Problem description
When I using physic and set timescale for one object to 0, , other object also effected.
## Attach a .c3p
[Bug_physic_timescale.zip](https://github.com/Scirra/Construct-bugs/files/13508396/Bug_physic_timescale.zip)

## Steps to reproduce
1. Create two Sprite (spriteA, SpriteB), and add Physic behavior for each one
2. In code set: Start of layout -> set object SpriteA timescale to 0.
3. Play to preview

## Observed result

Sprite B not fall as normal. 

## Expected result
. Sprite A will stay in it's position. SpriteB will fall down.

## More details

**Affected browsers/platforms:** Chrome
I open it with r368.2

**Comment by WilsonPercival** [comment]
@MrPhap https://github.com/Scirra/Construct-bugs/issues/7583

**Comment by MrPhap** [comment]
> @MrPhap #7583

Thank you so much!
