### ISSUE TITLE
HTML elements layer divide effect bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7594]
## Problem description

When I launch the game in `WebGL` I see a black square. When I run the game in `WebGPU`, there is no square.

Please note that on `Layer 1` there is a checkmark next to the `HTML elements layer` parameter.

## Attach a .c3p

[html_elements_layer_divide_effect_bug_r369b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13510015/html_elements_layer_divide_effect_bug_r369b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

<img width="413" alt="webgl" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/4f5ed15e-488d-4e91-a083-da3f84d35467">

<img width="381" alt="webgpu" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/5446416c-bf17-4409-ae86-68fe21b89540">

## Expected result

Should work the same.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r369b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r369 (beta)
Browser: Chrome 119.0.6045.160
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 102 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGPU information
Renderer: WebGPU
Supports GPU profiling: no
Major performance caveat: no
Maximum texture size: 8192
Adapter vendor: amd
Adapter architecture: gcn-5
Adapter device: (unavailable)
Adapter description: (unavailable)
Adapter features:

bgra8unorm-storage
depth-clip-control
depth32float-stencil8
float32-filterable
indirect-first-instance
rg11b10ufloat-renderable
texture-compression-bc
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
It's not useful to put background blending effects directly above a HTML layer, as they are composited separately and so there is no background to be blended with. Since there is no useful reason to do this, closing.

**Comment by WilsonPercival** [comment]
This was fixed in `r376b`.
