### ISSUE TITLE
Tweens of child objects don't work properly if parent objects of parent objects are being scaled

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7599]
## Problem description

When you create an object that is a child of an object that is a child of an object and all objects are being scaled, the last one fails to tween to a width of 0, the width is rather being miscalculated. This is an update to #7079, now an object that is a child of 1 object scales properly but if we bring a second or more objects into the mix that are also parents and being scaled, it still does not work. 

## Attach a .c3p

[ConstructBugExample.zip](https://github.com/Scirra/Construct-bugs/files/13516356/ConstructBugExample.zip)

## Steps to reproduce

1. Create 3 objects
2. Make the 2nd object the child of the first one and then the third object a child of the second one
3. Scale the two parent objects
4.  Run a tween on the third object with final width = 0

## Observed result

The object will not tween to width 0. 

## Expected result

The object should have a width of 0 in the end. 

## More details
r368.2 stable is affected

## System details

Chromium

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
A lot of things are broken for me too now unfortunately

**Comment by sotano42** [comment]
@AshleyScirra hey ashley, any updates on this? this is really affecting my work and not. Any milestone?

**Comment by AshleyScirra** [comment]
If this is a regression we would make it a higher priority, but currently nobody has said it's a regression so it looks like a regular bug that's always been there and so will be handled normally, in which case please be patient and allow the team time to get round to it.

**Comment by sotano42** [comment]
@AshleyScirra this is for sure a regression bug. r358 worked fine and it suddenly broke in the next version. When I opened some games to be updated the tween started failing. I can workaround in a couple of games using r358, but it's not the case for my larger project.

**Comment by therealPaulPlay** [comment]
It‘s not quite a regression. The bug that made tweens that go to width 0 malfunction was fixed in r358 but only for a single child, but introduced this new issue. If there are children of children now it is completely broken.

**Comment by therealPaulPlay** [comment]
Any updates on this? Unfortunately breaking a lot of my projects (tweens to width=0 are never working for me because all of my UI objects are children of their UI window which is a children of a scaler object)

**Comment by therealPaulPlay** [comment]
Awesome, thanks!

**Comment by therealPaulPlay** [comment]
Just tested this and it is working perfectly in r376, thank you very much!
