### ISSUE TITLE
Large Project Bottlenecks: Clicking Tabs

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-bugs#7613]
## Problem description

Large Project Series: A project with 18k objects (stress test)

The time it takes to open a tab takes a considerable amount of time.

## Attach a .c3p

[Large_Project_Debug_0.zip](https://github.com/Scirra/Construct-bugs/files/13545911/Large_Project_Debug_0.zip)

## Steps to reproduce

1. Click the Layout 1 tab
2. Note the time it takes to open
3. Click the Ev_Empty_0 tab
4. Note the time it takes to open
5. Click the Ev_Empty_1 tab (To control for cases where leaving a layout might be determining time delay, instead empty event sheet to empty event sheet)
6. Note the time it takes to open

Main question: Why does it take so long to open an empty event sheet in large projects?

**Comment by AshleyScirra** [comment]
Merging in to #7611
