### ISSUE TITLE
Large Project Bottlenecks: Cloning Objects

### ISSUE THREAD

**Issue by OneRepCloser** [Scirra/Construct-bugs#7614]
Large Project Series: A project with 18k objects (stress test)

The time it takes to clone objects takes a considerable amount of time.

## Attach a .c3p

[Large_Project_Debug_0.zip](https://github.com/Scirra/Construct-bugs/files/13545911/Large_Project_Debug_0.zip)

## Steps to reproduce

1. Clone an object in Layout 1
2. Note the time it takes to clone the object

**Comment by AshleyScirra** [comment]
This appears to have the same cause as #7615, so worth re-checking at the next release.

**Comment by AshleyScirra** [comment]
Merging in to #7611
