### ISSUE TITLE
Flowchart not styled in dark and light theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7619]
## Problem description
Flowchart not styled in dark theme, I know it's early so I totally understand if you want to wait until it's a bit more finalized ui/ux wise.

## Attach a .c3p
flow chart example project

## Steps to reproduce

1. check the flow chart view

## Observed result
not styled correctly

## Expected result
styled correctly

## More details
I generally want to break a lance for developing Construct 3 with the dark theme as the focus instead of the un-themed c3, I don't know the relative usage numbers but I expect most people (that aren't just opening c3 to try it) are using the dark theme.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
I use dark theme wherever possible. But I don’t care about getting the appearance right. For me, correct performance and stability are much more important.

**Comment by F3der1co** [comment]
it's definitely way less important than performance and stability!
But to me it hurts usability as it makes certain things read as much more important/drawing the eye (i.e. a back and white box in a otherwise low contrast dark grey ui). Secondly it makes the software look less appealing and professional which can impact you subconsciously much more than you might think and first impression of new users are affected by it a ton.

**Comment by DiegoScirra** [comment]
The next beta will have a styling that better fits the dark and light themes.
