### ISSUE TITLE
Find window not styled correctly in dark theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7620]
## Problem description
Find window not styled correctly in dark theme

## Attach a .c3p
empty project

## Steps to reproduce

1. open the find window in the dark theme

## Observed result
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/70a3a50c-cff0-4fce-91c3-08b23c9a28e5)

## Expected result
text inputs and checkbox is styled correctly

## More details
I generally want to break a lance for developing Construct 3 with the dark theme as the focus instead of the un-themed c3, I don't know the relative usage numbers but I expect most people (that aren't just opening c3 to try it) are using the dark theme.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in next beta.
