### ISSUE TITLE
Timeline animations bug again

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7621]
## Problem description

I switch the sprite animation, but it doesn't change.

## Attach a .c3p

[timeline_animations_bug_r337b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13567523/timeline_animations_bug_r337b.zip)

## Steps to reproduce

1. Open a project.
2. Add an instance of the sprite to the timeline.
3. Click `Editing mode`.
4. In the left ear, switch `Initial animation` to `Animation 2`.
5. Duplicate `Timeline 1`.
6. Remove the sprite instance from the timeline.
7. Open `Timeline 1`.
8. Open `Timeline 2`.
9. Close the timeline panel.
10. In the left ear, switch Initial animation to Animation 2.
11. In the left ear, switch Initial animation to Animation 1. Note that the sprite shows Animation 2 all the time.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/10c096b8-0585-45c3-9dca-f6857ed0c6e0

## Expected result

When I switch animations they change.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** broke in r370b

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r370 (beta)
Browser: Chrome 119.0.6045.200
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 182 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This is a completely different issue. It's not happening AGAIN.

**Comment by WilsonPercival** [comment]
> This is a completely different issue. It's not happening AGAIN.

@DiegoScirra If anything, I'm talking about this report: https://github.com/Scirra/Construct-bugs/issues/6899

Same problem, just different steps.

**Comment by brushfe** [comment]
@DiegoScirra Take it or leave it, but I think you could be more understanding in your replies, both here and overall. To an end user, this is the same issue — animations aren't changing — so it seems pretty fair a user would call this the same problem happening twice. On your end it's different, because your code caused the same error in two ways, but that's irrelevant and impossible to see from the user POV. These bugs reports are here to help, and I think you should talk to people reporting them the same way.
