### ISSUE TITLE
Flowchart crash with ctrl+z

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7623]
## Problem description

Can throw an exception when ctrl+z is used while dragging a new connection.

## Attach a .c3p

Flowchart example

## Steps to reproduce

1. Delete a connection
2. Start dragging a new connection to the same "in", don't release mouse button yet
3. Ctrl+Z
4. Try to add the new connection to the now again connected "in"

## Observed result

Crash

## Expected result

No crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r370/main.js, line 220, col 25
Message: Uncaught TypeError: Cannot read properties of null (reading 'Rra')
Stack: TypeError: Cannot read properties of null (reading 'Rra') at CCG.Ic (https://editor.construct.net/r370/main.js:220:25) at window.Auc.Ss (https://editor.construct.net/r370/components/editors/flowchartView/flowchartView.js:63:362) at window.zuc.yd (https://editor.construct.net/r370/components/editors/flowchartView/flowchartView.js:60:19) at HTMLElement. (https://editor.construct.net/r370/components/editors/flowchartView/flowchartView.js:58:471)
Construct version: r370
URL: https://editor.construct.net/r370/
Date: Wed Dec 06 2023 08:35:25 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 29 s

Platform information
Product: Construct 3 r370 (beta)
Browser: Edge 119.0.2151.97
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro K620 (0x000013BB) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
