### ISSUE TITLE
3D Camera Plugin Rotation snapping issue

### ISSUE THREAD

**Issue by Cowboy-Toad-Team** [Scirra/Construct-bugs#7631]
## Problem description

I'm using camera parallel to layout. The 3D camera plugin seems to be storing previous rotation values that do not get reset when you restart the layout. Therefore, when you move the mouse to change the camera rotation, it snaps to the last perspective you were looking at before you restarted/switched layouts.

## Attach a .c3p

[3DCameraBug.zip](https://github.com/Scirra/Construct-bugs/files/13629984/3DCameraBug.zip)

## Steps to reproduce

1. Move the mouse pointer to look around.
2. Press (SPACE) to restart the layout, wait a second and then move the mouse pointer again.

## Observed result

Notice how the camera snaps to the previous 3D camera rotation values as soon as you move your mouse.

## Expected result

The camera shouldn't snap to the previous layouts rotation values from _before_ the restart, it should move from where it is looking before there is any mouse movement, like it does the first time you run the project.

**Affected browsers/platforms:** 

Chrome/OperaGX/Windows

**First affected release:** 

Unknown

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r358 (stable)
Browser: Opera GX 104.0.4944.85
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 6
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 OPR/104.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 123 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 (0x00001B81) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
Ogg Theora (video/ogg; codecs=theora)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
