### ISSUE TITLE
Canvas snapshot of part of screen broken since r369

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7635]
## Problem description
Canvas Snapshot of part of screen doesn't work since r369.

## Attach a .c3p
[CameraSnapshotPartOfFullLayout.zip](https://github.com/Scirra/Construct-bugs/files/13640667/CameraSnapshotPartOfFullLayout.zip)

## Steps to reproduce

1. press take snapshot

## Observed result
image is empty

## Expected result
snapshot corresponds to the green area

## More details
this works correctly in r368.2. The values returned from PlatformInfo and the layer seem correct in both stable and beta.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
