### ISSUE TITLE
HTML element bug with Persist Behavior

### ISSUE THREAD

**Issue by LoneBilly** [Scirra/Construct-bugs#7636]
## Problem description

HTML element 

## Attach a .c3p
[repro_html_persist_bug.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13642459/repro_html_persist_bug.c3p.zip)

## Steps to reproduce

The issue concerns HTML elements with the "persistent" behavior. Here is how I can describe the bug:

I add an element, such as a list, to layout 2 of the application.
I configure this element to have a "persistent" behavior.
Then, I go back to layout 1.
When I return to layout 2, I notice a visual artifact: the element briefly appears at coordinates (0,0) instead of staying in the location where I originally positioned it.
This problem only occurs when the element has been configured with the "persistent" behavior. 
Thank you for your attention to this issue, and please inform me of any solution or updates regarding it.

Sincerely,
LoneBilly

**Affected browsers/platforms:** 

All

**First affected release:** 

I noticed it 3 years ago ^^

**Comment by WilsonPercival** [comment]
It's very similar to this report: https://github.com/Scirra/Construct-bugs/issues/6227

**Comment by LoneBilly** [comment]
> It's very similar to this report: #6227

Not really.
This bug is on all HTML éléments with the persist behavior.

It could be a list, a button, input...

And the coordinate is always 0,0, not out of the layout like #6227 ;)

**Comment by AshleyScirra** [comment]
This is pretty much the same case as #7634. Construct is issuing a sequence of immediate updates, but for some reason the browser decides to paint in between updates. It's difficult to work around in the engine. It also seems like a weird use case - why would you want the persist behavior on HTML elements? It's more designed for game objects like ensuring the things you've picked up from a level don't come back when returning to the level.

As with #7634 the best thing to do is just work around it - if you make the button initially invisible and make it visible on 'Start of layout', it seems to work OK.

**Comment by LoneBilly** [comment]
> C'est à peu près le même cas que #7634 . Construct publie une séquence de mises à jour immédiates, mais pour une raison quelconque, le navigateur décide de peindre entre les mises à jour. Il est difficile de contourner le moteur. Cela semble également être un cas d'utilisation étrange : pourquoi voudriez-vous le comportement persistant sur les éléments HTML ? Il est davantage conçu pour les objets de jeu, comme garantir que les éléments que vous avez récupérés dans un niveau ne reviennent pas lorsque vous revenez au niveau.
> 
> Comme avec [#7634,](https://github.com/Scirra/Construct-bugs/issues/7634) la meilleure chose à faire est simplement de contourner ce problème - si vous rendez le bouton initialement invisible et que vous le rendez visible sur « Début de la mise en page », cela semble fonctionner correctement.

I use Persist Behavior to keep my selection on my list when I change layouts and come back.
This seems easier than creating variables for all elements

**Comment by LoneBilly** [comment]
To work around the problem, we can set the initial condition to "make it initially invisible." However, if we have this solution in the editor, perhaps you could be able to fix the issue and ensure that the persistent element remains invisible until it is in its correct position?

**Comment by LoneBilly** [comment]
@AshleyScirra To work around the problem, we can set the initial condition to "make it initially invisible." However, if we have this solution in the editor, perhaps you could be able to fix the issue and ensure that the persistent element remains invisible until it is in its correct position?

**Comment by LoneBilly** [comment]
[repro_html_persist_bug.c3p 2.zip](https://github.com/Scirra/Construct-bugs/files/13666915/repro_html_persist_bug.c3p.2.zip)
C3P without the bug (when initialy invisible)
