### ISSUE TITLE
Blinking cursor on HTML elements

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#7637]
## Problem description

A blinking text cursor is showing on HTML elements.

## Attach a .c3p

[HtmlCursorBug.zip](https://github.com/Scirra/Construct-bugs/files/13643803/HtmlCursorBug.zip)

## Steps to reproduce

1. Run Project
2. Press Up or Left or Right Button on keyboard

## Observed result

A blinking text cursor appears on the HTML element

## Expected result

No blinking cursor

## More details
![htmlbug1](https://github.com/Scirra/Construct-bugs/assets/53188782/d7728608-2ede-4414-9a26-a99c1bd8f730)
![htmlbug2](https://github.com/Scirra/Construct-bugs/assets/53188782/dad1bc17-4bd3-45b1-898b-57d4795ea3c4)

**Affected browsers/platforms:** Chrome, Windows

**First affected release:** r369

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r370 (beta)
Browser: Chrome 120.0.6099.71
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 414 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M (0x00000A68) Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
Can not reproduce.

**Comment by Dramamini** [comment]
It happens on Chrome. On Firefox is ok

**Comment by WilsonPercival** [comment]
> It happens on Chrome. On Firefox is ok

I tried it in chrome.

**Comment by Dramamini** [comment]
Happens after r369. r368 is ok. Maybe I should have capture it with a video

**Comment by WilsonPercival** [comment]
> Happens after r369. r368 is ok. Maybe I should have capture it with a video

I tried it in `r370b`.

**Comment by Dramamini** [comment]
https://github.com/Scirra/Construct-bugs/assets/53188782/cebf516e-00e1-4999-97fd-7a262f1f8124

**Comment by Dramamini** [comment]
Another observation is that if you disable html element, cursor becomes light gray and if you make html element invisible, cursor blinks on top left viewport corner


https://github.com/Scirra/Construct-bugs/assets/53188782/617415ec-77e3-43cb-b24c-cfd2f5cc7d8b

**Comment by Dramamini** [comment]
Hi @AshleyScirra thanks for your answer!
What is editing mode? No I have no extensions installed.. 
But why this is not happening before r369?

**Comment by Dramamini** [comment]
@AshleyScirra I think something that has changed in r369 preview.css is causing this and maybe it's visible only to me because I have an older system (Windows 10). Anyway.. thanks for your time and congratulations for your amazing work.

**Comment by AshleyScirra** [comment]
If you edit the page HTML with developer tools and add `contenteditable="true"` to the page's `<html>` tag, then the entire document becomes editable, and then I see a blinking cursor the same as your pictures show. However this editing mode is definitely not the default, nor would we have done anything to intentionally enable it, and this issue does not reproduce for me. So I would guess you've somehow changed something about your browser that enables editing mode by default. My best guess would be a browser extension did that, but perhaps something else did. I don't think there's anything else we can do about this, so closing.
