### ISSUE TITLE
"On-Screen" broken since newest update

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7641]
## Problem description

"On-Screen" in combination with "trigger once" used to work like it is being used in the example project but is now broken. 

## Attach a .c3p

[OnScreenBroken.zip](https://github.com/Scirra/Construct-bugs/files/13650541/OnScreenBroken.zip)

## Steps to reproduce

1. create particles
2. create action to make them spray if they are on screen
3. create action to make them stop spraying if they are not on screen

## Observed result

They do not start to spray. 

## Expected result

They should spray like in previous versions. 

## More details
Tested in 368.2 stable (previous major stable release was not affected)

## System details

chromium 

PASTE HERE

</details>

**Comment by therealPaulPlay** [comment]
I‘m only updating to stable releases and wasn‘t testing wirth 358 much but am pretty sure it worked there (because I was implementing features presumably with that version looking at the release dates that used this). Otherwise, in r350 it was working 100%.

**Comment by WilsonPercival** [comment]
> @WilsonPercival I‘m only updating to stable releases and wasn‘t testing with 358 much but am pretty sure it worked there (because I was implementing features presumably with that version, looking at the release dates, that used this). Otherwise, in r350 it was working 100%.

@therealPaulPlay I just tested this in `r329b` and it works the same.

**Comment by therealPaulPlay** [comment]
Thanks. I just tested every stable release of the past 6 months and it's not working the way that my project did, I have no idea why it was working in my project lol. Closing this now and sorry for the inconvenience
