### ISSUE TITLE
Opening flowchart editor causes immediate crash.

### ISSUE THREAD

**Issue by AFHell** [Scirra/Construct-bugs#7642]
Trying to open a flowchart in order to edit it immediately oopses Construct.

## Attach a .c3p

No need for a c3p, crashes also on demo projects.

## Steps to reproduce

1. Start Construct, go to the example projects section and choose one of the flowchart demos, open it.
2. In the project navigation bar, find any flowchart and right click on it, then choose [Edit]

## Observed result

Construct crashes with major exception message.

## Expected result

The flowchart editor opens.

## More details

Happens on 370 and 371, on either Chrome or Edge, it doesn't matter if in Private mode or not.

Here is an info dump from the crash:

Error report information
Type: unhandled exception
File: https://editor.construct.net/r371/main.js, line 1051, col 141
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Q.i (https://editor.construct.net/r371/main.js:1051:147) at Plb (https://editor.construct.net/r371/components/bars/projectBar/projectBar.js:81:478) at Wlb.l.I.bold (https://editor.construct.net/r371/components/bars/projectBar/projectBar.js:86:204) at https://editor.construct.net/r371/main.js:1921:410
Construct version: r371
URL: https://editor.construct.net/r371/
Date: Tue Dec 12 2023 17:50:32 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 279.6 s

Platform information
Product: Construct 3 r371 (beta)
Browser: Edge 119.0.2151.97
Browser engine: Chromium
Context: browser
Operating system: Windows NT 8.0.0
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0
Language setting: de-DE

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 960 (0x00001401) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
