### ISSUE TITLE
Can't add new object if no layout tabs are open

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7643]
## Problem description

If there aren't any layout tabs open, you can't add new objects to the project tree. 

## Attach a .c3p

Any project should do (just close all the layout tabs), but I'll start from scratch in the steps.

## Steps to reproduce

1. Create a new project
2. Close the "Layout 1" tab
3. Right-click on "Object Types" in the project tree

## Observed result

The option "+ Add new object type" is missing

## Expected result

The option "+ Add new object type" is always available.

## More details

If this is intentional, my goal when I found the error was to add a dictionary object (something independent of layouts, like a sprite)

**Affected browsers/platforms:** Chrome 119.0.6045.159

**First affected release:** r369

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design, as the normal flow of adding an object which appears in a layout is to immediately place it after choosing it. If there is no active layout view then this step cannot be done, and so to avoid confusion the "Add new object type" menu option is hidden in that case.

**Comment by brushfe** [comment]
@AshleyScirra Thanks for looking into this. I made a note in the report that I was adding an object that didn't apply to layout (a dictionary). Is the current design that no objects whatsoever can be added without a layout, or just those that go on layouts? It feels like non-layout objects should be allowed at any point.
