### ISSUE TITLE
Flowchart ctrl+z crash

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7644]
## Problem description

Crash

## Attach a .c3p

[crash.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13659224/crash.c3p.zip)

## Steps to reproduce

1. Resize Node
2. Delete Node
3. Ctrl+Z (multiple times)

## Observed result

Crash

## Expected result

No

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'Qja') @ TypeError: Cannot read properties of null (reading 'Qja') at window.d3.ic (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:48:306) at C1a.rl.aTa (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:9:444) at C1a.rl.Pg (https://editor.construct.net/r371/projectResources.js:1983:366) at C1a.rl.qf (https://editor.construct.net/r371/projectResources.js:1999:45) at window.Ec.Xh (https://editor.construct.net/r371/projectResources.js:1988:319) at d.Xh (https://editor.construct.net/r371/projectResources.js:1853:298) at https://editor.construct.net/r371/main.js:2974:95 at window.Onb.Xh (https://editor.construct.net/r371/main.js:2974:146)
Stack: TypeError: Cannot read properties of null (reading 'Qja') at window.d3.ic (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:48:306) at C1a.rl.aTa (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:9:444) at C1a.rl.Pg (https://editor.construct.net/r371/projectResources.js:1983:366) at C1a.rl.qf (https://editor.construct.net/r371/projectResources.js:1999:45) at window.Ec.Xh (https://editor.construct.net/r371/projectResources.js:1988:319) at d.Xh (https://editor.construct.net/r371/projectResources.js:1853:298) at https://editor.construct.net/r371/main.js:2974:95 at window.Onb.Xh (https://editor.construct.net/r371/main.js:2974:146)
Construct version: r371
URL: https://editor.construct.net/r371/
Date: Wed Dec 13 2023 11:01:48 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 10.1 s

Platform information
Product: Construct 3 r371 (beta)
Browser: Edge 120.0.2210.61
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA Quadro K620 (0x000013BB) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
