### ISSUE TITLE
Game crash when removing a layer when there's a sprite with mutiple "button" object parented to it on debug mode 

### ISSUE THREAD

**Issue by Archibaldr** [Scirra/Construct-bugs#7645]
## Problem description

When you create a layer with a sprite on top that has several button objects parented to it, and then delete this layer, ONLY in debug mode, the game crashes.

## Attach a .c3p

https://www.dropbox.com/scl/fi/7iiwavnzt7xgyba57mrvr/Bug.c3p?rlkey=0disnohqtvdy3xo4yzhogtqj7&dl=0

## Steps to reproduce

1. IN DEBUG MODE, Go to layout 1, click on the red rectangle box
2.On the spawned object, click on the red box at his right top corner
3.the game will crash

## Observed result

What do you see happen?

The game crash when in debug mode

What did you expect to happen instead?

The game to not crash when in debug mode

**Affected browsers/platforms:** Tried on Chrome and Brave 

**First affected release:**  R368.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Minimum project: 
[issue7645.zip](https://github.com/Scirra/Construct-bugs/files/13662944/issue7645.zip)

Steps to reproduce:
1. Open a project.
2. Launch and open the console.
3. Press `1`.

Observed result: errors in the console.

**Comment by AshleyScirra** [comment]
Fixed for next beta.
