### ISSUE TITLE
When the remote preview is connecting, if close the dialog,  will not be able to preview again

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7646]
## Problem description

When the remote preview is connecting, if close the dialog,  will not be able to preview again until restart C3.

As additional information for [this issue](https://github.com/Scirra/Construct-bugs/issues/7606)

## Steps to reproduce
1. remote preview
![Screenshot_20231214_011418](https://github.com/Scirra/Construct-bugs/assets/45864744/0f0d146a-651f-4999-b3e2-77b5853ace6c)

2. When connecting, close the dialog
![Screenshot_20231214_012624](https://github.com/Scirra/Construct-bugs/assets/45864744/14431c3c-3cfb-43b3-8ba1-34109f57bb2a)

## Observed result

will not be able to preview again

## Expected result

Can be previewed again

## More details

Because there is a problem with my keyboard (Fn and F1 are reversed) and I don't know how to swap them back. So I can only use the mouse to enter Debug mode. However, I often accidentally click on the remote preview, so I quickly turn it off.

Also because of the VPN, it is always very slow for me to open the remote preview, and it takes several seconds to remain in the connecting state.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
I can reproduce this. If I quickly open and close a remote preview, then after that I will not be able to open it. Moreover, I won't be able to run the normal preview.

https://github.com/Scirra/Construct-bugs/assets/91274932/b6151eb9-37b4-4dd4-96d9-d3703b35123b

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
