### ISSUE TITLE
Mouse skips with 3d camera

### ISSUE THREAD

**Issue by jpound94** [Scirra/Construct-bugs#7648]
## Problem description

When setting up a first person controller using pointer lock and rotating the camera with mouse movement, at random intervals the mouse seems to "skip" and faces the camera in a different direction. Attached a video capturing this below. I thought this was an issue with my mouse until a playtester said it happened a lot.

## Attach a .c3p

Can be observed on the first-person platformer c3p.

## Steps to reproduce

1. Spend enough time playing through and a skip will eventually occur.

## Observed result

Camera faces a different direction.

## More details

https://github.com/Scirra/Construct-bugs/assets/153773366/6c501329-39aa-4ac3-bff8-0c019c9cce17

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 120.0.6099.71
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 462 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 (0x00002216) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
Can not reproduce.

**Comment by AshleyScirra** [comment]
I ran around the entire "First person platformer" example and it never skipped for me.

Are you sure it's not a problem with the mouse? If the mouse has a fault and incorrectly thinks the cursor jumped to the right, that will cause your view to rotate when using mouse look. Testing a couple of other systems should identify whether it's a defective mouse, or printing the `Mouse.MovementX/Y` expressions which control the rotation might identify large jumps coming from the mouse input. It's hard to think of any reason the engine itself would suddenly skip the view, as that only happens via the 'Rotate camera' action.

**Comment by ksushkinSlave** [comment]
I have the same issue!

**Comment by F3der1co** [comment]
I hope this bug can be looked into again as this affects one game that I am planning to release soon.
This suggestions outlines why it happens and a solution `(requestPointLock() with unadjustMovement: true)`: https://github.com/Scirra/Construct-feature-requests/issues/206

I tried implementing this myself in js, but I wasn't able to request pointer lock, it seems like I need access to the main canvas.

**Comment by jpound94** [comment]
I'm glad that others have experienced this happening (and is still happening now), I've been hesistant to make any sort of first person shooter because of this issue and how detrimental it would be to gameplay.

**Comment by F3der1co** [comment]
see a solution here:
https://github.com/Scirra/Construct-bugs/issues/8059

**Comment by Cowboy-Toad-Team** [comment]
Hi, we are still having multiple customers reporting this issue, we are unable to reproduce it ourselves and have no idea what causes it. Could this issue possibly be reopened?

**Comment by moonbitgames** [comment]
> Hi, we are still having multiple customers reporting this issue, we are unable to reproduce it ourselves and have no idea what causes it. Could this issue possibly be reopened?

For me, this has been fixed from r398 onwards by using 'unadjusted movement' in the pointer lock event.

**Comment by Cowboy-Toad-Team** [comment]
> > Hi, we are still having multiple customers reporting this issue, we are unable to reproduce it ourselves and have no idea what causes it. Could this issue possibly be reopened?
> 
> For me, this has been fixed from r398 onwards by using 'unadjusted movement' in the pointer lock event.

Amazing thank you! Just confirmed this
