### ISSUE TITLE
Changing Layout Scale + Canvas Size causes anchored objects to move to wrong positions upon restart

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7652]
## Problem description
When you combine Layout Scale + Canvas size and change both and then restart the layout, anchored objects will shift to incorrect positions. 

## Attach a .c3p
[AnchorLayoutScaleBug.zip](https://github.com/Scirra/Construct-bugs/files/13677217/AnchorLayoutScaleBug.zip)

## Steps to reproduce
1. Create anchored object
2. Add actions "Change Layout Scale" and "Change Canvas resolution" with values that keep the proportions the same
3. Restart the layout

## Observed result

Anchored objects shift. 

## Expected result

They should not shift. 

## More details
Using r368.2

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Workaround: 
[AnchorLayoutScaleBug_workaround.zip](https://github.com/Scirra/Construct-bugs/files/13677517/AnchorLayoutScaleBug_workaround.zip)

**Comment by therealPaulPlay** [comment]
Thanks for your workaroud, but it basically is a direct replacement to the anchor behavior.. I mean yeah, saving the relative x/y distance from the corresponding viewport borders works but I think the anchor behavior is just more convenient and probably more performant (at least in comparison to everyt tick, on resized (browser object) would prob be as performant). Also I'm using it a lot in my project and would be very glad if it would be fixed in the future🙌

**Comment by AshleyScirra** [comment]
The Anchor behavior does not currently support changing the viewport size at runtime. For more advanced cases, just use the system viewport expressions anyway, as they give you full control over positioning.

**Comment by therealPaulPlay** [comment]
Thank you @F3der1co, this makes transitioning to a different solution a lot easier. @AshleyScirra Thank you for the insight. I‘d have just hoped that these engine features are compatible with each other, because I‘m using the anchor behavior extensively in my project (40+ objects) and I believe that it is one of the most essential plugins for handling scaling on mobile devices, which need resolution scaling the most. Further, some Android devices with „game modes“ actually decrease the resolution to increase fps and many power saver modes on android do the same thing. That means, that there are many possible situations in which the anchor behavior breaks, and with that the UI of a game.

My project at this point is really big and I appreciate the engine a lot, but it’s just unfortunate that I have to use custom solutions in the form of code or plugins for so much (movement, vibrations, fullscreen, tweens, physics, game saves, ads, cordova loading screen, project backups, camera/scrollto, buttons, time system to accomodate for traveling between timezones, particles, timescale etc.), even though built-in plugins exist but they are not flexible enough in some areas or have issues. 

Either way, I believe it might be beneficial for many construct users if the anchor behavior  would get fixed  and would improve the stability of many games :)

**Comment by therealPaulPlay** [comment]
> you might want to check out skymens better anchor behavior, that's like the name suggest just a straight up improvement over the build in one in every way: https://www.construct.net/en/make-games/addons/1186/better-anchor
Did some testing with this, it unfortunately suffers from the same issue

**Comment by F3der1co** [comment]
> > you might want to check out skymens better anchor behavior, that's like the name suggest just a straight up improvement over the build in one in every way: https://www.construct.net/en/make-games/addons/1186/better-anchor
> 
> Did some testing with this, it unfortunately suffers from the same issue

really? I specifically tested this project before writing.

**Comment by therealPaulPlay** [comment]
Messaged him :) In the meantime, I've built upon @WilsonPercival 's solution and came up with this (in case anyone in the future finds this bug report). Keep in mind that 3840 and 2160 represent my target viewport resolution and you'll need to use e.g. 1920 and 1080 if that is your viewport resolution (in the editor). 

![image](https://github.com/Scirra/Construct-bugs/assets/80539587/43a1ebc7-7527-4c0b-9c67-1bebf5331f24)
