### ISSUE TITLE
Flowcharts: deleting connected output makes its previous input not connectable

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7653]
## Problem description
deleting connected output makes it's previous input not connectable

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13678226/flowchartBugged.zip)

## Steps to reproduce

1. delete the output named "delete this" (without disconnecting first)
2. try connection "Option 2" of the start node with the other node

## Observed result
can't be connected

## Expected result
can be connected

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
