### ISSUE TITLE
Flowchart: Node output value input box ux

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7654]
## Problem description

https://github.com/Scirra/Construct-bugs/assets/89512047/9967bc23-6ea4-423f-b14e-ecc13cc7a966

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13678349/flowchartBugged.zip) 
(just reusing the file from previous report)

## Steps to reproduce

1. single click the value field on the node

## Observed result
nothing happens

## Expected result
you can edit it without opening the larger text box, just like the value in the node properties bar (video might make it clearer)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Currently there is a similar behaviour when double clicking on the name fields. Double clicking on the value field brings up the edit dialog for the value of an output.

With the next beta, both fields will show the edit text box for quick edits with a single click. This will be consistent with the behaviour of the Properties bar. The dialog box will continue to be available from the button on the value field and from the context menu.
