### ISSUE TITLE
Flowcharts: delete flowchart dialog box string missing

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7657]
## Problem description
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/c617b91c-89de-4a2d-bea9-3417052078dd)
delete flowchart dialog box string missing

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13678658/flowchartBugged.zip)
(same project again, no need to redownload)

## Steps to reproduce

1. delete a flowchart from project

## Observed result
Dialog shows up with missing string

## Expected result
Dialog has some content

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
