### ISSUE TITLE
Changing the "layer scale rate" at any point in time after scaling Canvas + Layer results in the layer to change in scale

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7658]
## Problem description

If you change the canvas size, and the layout scale accordingly, later changing a layer's scale rate will lead to its scale changing. 

## Attach a .c3p
[LayerScaleBug.zip](https://github.com/Scirra/Construct-bugs/files/13679094/LayerScaleBug.zip)

## Steps to reproduce

1. Fullscreen quality: low
2. Change Canvas Size + Layout Scale
3. Change the Layer Scale rate later 

## Observed result
The layer will scale to a different size. 

## Expected result

It should stay the same as the shift is happening after scaling the layout. Second, this is necessary to work around the fact that there is currently no way afaik to _only_ change the layout scale without alterning the layer scales of all layers which is an issue if layers have different scale rates. 

## More details
using r368.2

## System details

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. The layer final scale is calculated as `((layerScale * layoutScale) - 1) * scaleRate + 1`. If you change the scale rate you will suddenly get a new scale calculated.

**Comment by therealPaulPlay** [comment]
Alright, thank you for the explanation. The issue with that is that there is now seemingly way to implement different render resolutions (which is quite important for mobile games, as many phones have high-res displays but lack sufficient gpu power) in conjunction with different layer scale rates? 

That’s quite unfortunate, as layer scale rates are pretty important for the camera controller in my game as I‘m zooming in/out a lot. Only solution that comes up in my mind is to just handle scaling on a layer per layer basis with different scale factors for each.

However, I feel like there should be a proper way to handle resolution scaling that does not interfere with layer scaling, the anchor behavior
and physics. Especially because these are integral parts of the engine and should, in my opinion, be compatible with this feature.

**Comment by therealPaulPlay** [comment]
![image](https://github.com/Scirra/Construct-bugs/assets/80539587/5d72a494-1578-4a81-bed6-05fb2e37336d)
yep that'll do. Thanks for the formula btw
