### ISSUE TITLE
HTML Elements Layers - HTML5 iOS Bug (black screen, no layers above visible)

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-bugs#7659]
## Problem description

When using HTML5 on  iOS (16), and using the new HTML Elements Layer feature, 2 bugs happen.

1. Initially I get a "project background color screen" (default black), I can sometimes go off the tab and back on it and my project will then appear.
2. Any layers above the HTML Elements layer are NOT visible. they simply do now show.

I obviously have the new checkbox checked on the layer in question (with the HTML Element on).

## Attach a .c3p
[html_issue.zip](https://github.com/Scirra/Construct-bugs/files/13684012/html_issue.zip)

## Steps to reproduce

1. Run the attached project on and remote preview it on IOS.
4. You will see black screen. If you disable the HTML Layer (tick box) then it loads OK.
5.If  you managed to load it WITH the HTML Layer enabled, the layer above will NOT be visible.

## Observed result

See above

## Expected result

For the project to load corrently and for the layers above the HTML Layer to be visible.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
