### ISSUE TITLE
Flowchart: connection circles are low resolution

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7661]
## Problem description
The in and out connection circles are low resolution, this is compounded by the fact that we can freely zoom in, but is already noticeable at relatively far zoom levels, a svg circle might be a better fit. (https://fonts.google.com/icons?selected=Material+Symbols+Outlined:circle:FILL@0;wght@400;GRAD@0;opsz@24&icon.query=circle)
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/52a27518-2834-4541-a580-5b0b4e7e231d)

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13684221/flowchartBugged.zip)
(reusing project, no need to redownload)

## Steps to reproduce

1. look at in and out circle/connection point

## Observed result
pixelated low resolution raster graphic

## Expected result
smooth circle

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
The next beta will start using SVG elements to improve resolution at different zoom levels.
