### ISSUE TITLE
NW.js Export Breaking With Physics Behavior in any Sprite

### ISSUE THREAD

**Issue by Tesophus** [Scirra/Construct-bugs#7663]
## Problem description

Any project exported for NW.js that contains a sprite with the Physics Behavior in it is not opening (Don't pass the initializing loading stage).

## Attach a .c3p

[NW_Export_Chromium114_Breaking_With_Physics_Behavior.zip](https://github.com/Scirra/Construct-bugs/files/13685295/NW_Export_Chromium114_Breaking_With_Physics_Behavior.zip)

## Steps to reproduce

1. Make an empty project
2. Add an Sprite Object
3. Add Physics Behavior to the Sprite
4. Export to NW.js with any version above v0.77.0 (Chromium 114)
5. Open Project.exe
6. See it not loading (Just black screen)

If You're using my example project, just take from step 4. Export  to NW.js and open the .exe

## Observed result

![Screenshot_187](https://github.com/Scirra/Construct-bugs/assets/10690795/bb289f14-89da-4a70-ad5e-ee8703f0255e)

## More details

**Affected browsers/platforms:** Exporting to NW.js

**First affected release:** v0.77.0 (Chromium 114)

It's still happening in the latest v0.82.0 (Chromium 119) and it's still happening in the latest beta release of construct r371 beta

I'm using Windows 10 Pro 64x.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 120.0.6099.72
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 2.9 gb (1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 970 (0x000013C2) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
This appears to be a [known bug in NW.js](https://github.com/nwjs/nw.js/issues/8075). The NW.js team need to fix that. In the mean time you can work around this by turning off worker mode (in Project Properties set 'Use worker' to 'No'), or for Windows, use the Windows WebView2 export option which is not affected by the bug.
