### ISSUE TITLE
Flowchart: deleting nodes or outputs only possible through context menu

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7664]
## Problem description
Deleting nodes or outputs on Flowcharts is only possible through context menu and not via the delete key. I post this as a bug as this feature is supported in the rest of the engine, so it really feels like an oversight here (and I never delete anything through the context menu normally).

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13695844/flowchartBugged.zip)
(generic flowchart file again)

## Steps to reproduce

1. click a nodes header and press delete
2. click an output on a node and press delete

## Observed result
nothing happens

## Expected result
Node and Output is deleted.

## More details
there is a case where you currently can select a flowchart and an output at the same time (without shift clicking), it's not obvious why, and it could interfere with this. 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
About the context menu
I suggest following the editor preferences of placing the edit first


Observed result
![Snipaste_2023-12-21_13-01-04](https://github.com/Scirra/Construct-bugs/assets/45864744/b29f656f-58cb-4bfc-830e-847d28a194a7)

Expected result

![Snipaste_2023-12-21_13-03-09](https://github.com/Scirra/Construct-bugs/assets/45864744/2daad9c3-fd9e-4441-af43-6cef24435223)

Edit name -> Rename

![Snipaste_2023-12-21_13-07-37](https://github.com/Scirra/Construct-bugs/assets/45864744/a0ea4a00-8c58-47cc-a559-8b91b5e9deee)

**Comment by DiegoScirra** [comment]
This will be added to the next beta.
