### ISSUE TITLE
Flowcharts: Tag Tooltip incorrect suggestions

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7665]
## Problem description
Tag Tooltip only suggests "bandit-quest-1" from the example project instead of tags used in this project. Not entirely sure if this is a bug specific to me.

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13695875/flowchartBugged.zip)

## Steps to reproduce

1. select the tag

## Observed result
tooltip suggests "bandit-quest-1" as auto fill (might require to have opened the example before).

## Expected result
It does suggest previously used tags from this project, for example "speech".

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
That tooltip is part of the browser's built in behaviour. We can't control what it shows, not even sure what is the logic behind it. I will disable it to avoid confusions.

**Comment by F3der1co** [comment]
> That tooltip is part of the browser's built in behaviour. We can't control what it shows, not even sure what is the logic behind it. I will disable it to avoid confusions.

I thought @AshleyScirra was able to control it to some extend for other features where it does end up showing more useful suggestions. But yea if it doesn't work properly disabling it is probably a good idea.

**Comment by AshleyScirra** [comment]
@DiegoScirra - you could use a `datalist` element and list available tags as option elements within it, providing a tag autocomplete for just known tags.

**Comment by DiegoScirra** [comment]
I will just disable it for now, I never though about it to begin with and already have many questions about it.
