### ISSUE TITLE
Flowchart: opening a closed flowchart view moves the scroll towards the top left

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7667]
## Problem description
opening a closed flowchart view moves the camera towards the top left, this can make orienting really difficult as I often had it open in a space where no nodes are.

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13695905/flowchartBugged.zip)
same project

## Steps to reproduce

1. open flowchart view
2. close flowchart tab
3. repeat

## Observed result
Flowchart scroll keeps getting offset.

## Expected result
Scroll and zoom is correctly restored or it just focuses the start node at 100% zoom if opened.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This will be fixed properly in the next beta. The behaviour is different in the current beta, but still doesn't work quite right.
