### ISSUE TITLE
Flowchart: Start node checkbox undo-point inconsistent

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7668]
## Problem description
Changing the start node checkbox in the node properties and then pressing Undo does not restore correctly. (I was also able to get a crash once, but uncertain if it's really connected as I didn't find a repro)

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13695936/flowchartBugged.zip)
same project

## Steps to reproduce

1. mark a different node as "Start node"
2. Undo

## Observed result
state is not restored (no node is start node now)
I also saw that the ui doesn't update the "- (Start node)" correctly sometimes.

## Expected result
the previous start node is now start node again after the undo

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
