### ISSUE TITLE
Flowchart: pressing undo while moving a node crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7669]
## Problem description
pressing undo while moving a node crash

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13696034/flowchartBugged.zip)
same project

## Steps to reproduce

1. move a node to create and undo-point
2. drag a node (don't release)
3. press ctrl-z

## Observed result
crash

## Expected result
no crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Error report information
Type: unhandled exception
File: https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js, line 12, col 475
Message: Uncaught TypeError: Cannot read properties of null (reading 'Wa')
Stack: TypeError: Cannot read properties of null (reading 'Wa') at sjb (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:12:475) at HTMLDivElement. (https://editor.construct.net/r371/components/editors/flowchartView/flowchartView.js:50:311)
Construct version: r371
URL: https://editor.construct.net/r371/
Date: Sun Dec 17 2023 13:08:26 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 959.7 s

Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 120.0.6099.110
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex
PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
