### ISSUE TITLE
Flowchart: undoing add output can lead to misplaced node

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7670]
## Problem description
undoing add output can lead to misplaced node

## Attach a .c3p

[nodeOver.zip](https://github.com/Scirra/Construct-bugs/files/13696050/nodeOver.zip)
this is a unique project
## Steps to reproduce

https://github.com/Scirra/Construct-bugs/assets/89512047/515d692e-c5d8-4359-977d-39bac576aea1

1. press add on the bottom node
2. undo

## Observed result
Nodes overlap

## Expected result
nodes don't overlap (also undoing the node scaling that sometimes happens by adding an option might be the fix)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This should already be fixed in the latest beta.
