### ISSUE TITLE
Crash when set object to a global layer bur not exist in the current Layout

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7671]
## Problem description

Crash when set object to a global layer but not exist in the current Layout.

![Screenshot_20231218_022625](https://github.com/Scirra/Construct-bugs/assets/45864744/a8a886dc-5ee6-432a-a3bc-c2da463d8832)

## Attach a .c3p

[issue-globallayer.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13697364/issue-globallayer.c3p.zip)

## Steps to reproduce
1.
2.
3.

## Observed result

Additional: if moved to the sub layer C of Layer B, it will not crash

## Expected result

No crash, 
or not show the no-existing global layers in the list

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
