### ISSUE TITLE
Unpredictable Bookmark Bar Crash

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-bugs#7672]
## Problem description

Very randomly, double-clicking on a bookmark will crash Construct 3 with red crash screen and error message.

I cannot reproduce this in a c3p: Once this crash happens, I always use the save option from the crash window, then restart C3, open the same crashed project c3p file, double click the bookmark, and it works correctly.

This isn't a new issue, I have had this happen for YEARS, it's so random and unpredictable, sometimes multiple times a month, sometimes safe for a month.

I have never reported it because I cannot repro it, I thought it was best to "retrace my steps" but it's wayy too unpredictable, unless I recorded myself using C3 endlessly! I tried to repro but have failed, I apologise profusely but thought it was worth posting in case there's a clue.

The reason I chose to post today, is because I noticed the error message says "bookmark does not belong to this event sheet".
However, in the crash screen, I can see in the background beneath the red crash screen that I was on the correct event sheet that the bookmark belongs to.

I never renamed any event sheets, and I never cut/paste/moved the bookmarked event that caused the crash.

Hope these details help, and thank you for your time!

<details><summary>Error Message From C3</summary>
Error report information
Type: assertion failure
Message: bookmark does not belong to this event sheet
Stack: Error at pa.P3a (https://editor.construct.net/r371/main.js:1121:314) at window.assert (https://editor.construct.net/r371/main.js:1036:353) at d.S7a (https://editor.construct.net/r371/components/editors/eventSheetView/eventSheetView.js:177:162) at https://editor.construct.net/r371/components/bars/bookmarksBar/bookmarksBar.js:10:405
Construct version: r371
URL: https://editor.construct.net/r371/
Date: Mon Dec 18 2023 06:01:55 GMT+0000 (Greenwich Mean Time)
Uptime: 6348.6 s

Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 122.0.6182.0
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F15) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex
</details>

## Attach a .c3p

N/A - Doesn't affect a saved c3p.

## Steps to reproduce

Unable to provide these. I really wish I could, but this crash has happened for years and I have tried to repro but cannot figured this out.

## Observed result

Crash when double-clicking bookmark randomly.

## Expected result
No crash

## More details
Has happened for years.
Use Windows 10 with latest Chrome with no extensions.

**First affected release:**
Years ago!
## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r371 (beta)
Browser: Chrome 122.0.6182.0
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 534 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F15) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
I do remember this issue from a while back, I have an idea of why it happens, but with out a way to reproduce it is impossible to verify a possible fix would actually do anything.

**Comment by Jase0000** [comment]
Thank you @DiegoScirra

You won't believe it, I found a way to repro!!
Seems I was wrong that I "didn't move events", as the repro involves moving events, hmm.

[C3P File](https://drive.google.com/file/d/1KkLSKjtgcwSLmHxHjeEE1axfisY_-o7l/view?usp=sharing)

Steps:
1. Open C3P, go to Event Sheet
2. Move bookmarked event to event 1 (so it is no longer a sub-event).
3. Double-click the bookmark in the Bookmark panel   (Important - It won't crash unless you do this)
4. Undo
5. Double-click the bookmark in the Bookmark panel
6. Crash

**Comment by DiegoScirra** [comment]
I see, that makes sense. It should be easy to fix knowing that moving a bookmarked event is the problem.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
