### ISSUE TITLE
MobileAdvert: Ads are displayed only if the user "Consents", If the user does not consent, No Ads are displayed At All.

### ISSUE THREAD

**Issue by sashiklv** [Scirra/Construct-bugs#7673]
## Problem description

Admob and **MobileAdvert** are configured, the android build is made. After the Consent Prompt, if the user picks "Do not consent" or "Confirm choices" (limited), no ads are served at all. If the user selects "Consent" or agrees to all, ads are displayed. This occurs even with the plugins "test mode" on or off. Ads should be displayed but non-personalized. Currently, no ads at all are served. Tested with multiple users.

## Attach a .c3p

_no .c3p were provided at the moment_

## Steps to reproduce

MobileAdvert configured, debug APK built

## Observed result

Ads are displayed only if user "Consent". If not consent, nothing is displayed.

## Expected result

Ads should be displayed even if user do not consent, or make his choises.

## More details
It should always show ads, but get non-personalized ads, but nothing is displayed if user does not "Consent" .
It seems like something is not going through. Something isn't right, it shouldn't be like that.

**Affected browsers/platforms:** Android 11-13

**First affected release:** r362.2 stable

## System details

_no system information were given_

**Comment by fredriksthlm** [comment]
"_Ads should be displayed but non-personalized_ ". This is a misunderstanding. When users do not consent it will just be _Limited ads_, for Admob this means **no ads** will be served at all.

So the plugin works like it is supposed to work.

**Comment by DiegoScirra** [comment]
Even for non personalised ads, there are still requirements than need to be met. If the end user does not give consent for personalised ads, depending on the consent form, there is still a chance that non personalised ads will not be served either.

https://support.google.com/admob/answer/9760862?hl=en&sjid=9989627199052348838-EU

The relevant bit is:

> If the consent requirements for personalized ads are not met, Google will serve non-personalized ads when all of the following criteria are met:
> 
> The end user grants Google consent to:
> Store and/or access information on a device (Purpose 1)
> Legitimate interest (or consent, where a publisher configures their CMP to request it) is established for Google to:
> Select basic ads (Purpose 2)
> Measure ad performance (Purpose 7)
> Apply market research to generate audience insights (Purpose 9)
> Develop and improve products (Purpose 10)

If the user does not give consent to any of those, no ads are served.
