### ISSUE TITLE
Flowchart: node scaling broken if done from far zoom level

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7678]
## Problem description
node scaling broken if done from far zoom level

https://github.com/Scirra/Construct-bugs/assets/89512047/de902c9d-e243-4f23-a302-7a771b268f28

## Attach a .c3p
[flowchartBugged.zip](https://github.com/Scirra/Construct-bugs/files/13706580/flowchartBugged.zip)
same

## Steps to reproduce

1. zoom out to about 40% for example
2. scale node smaller from the right or left

## Observed result
node is scaled smaller than it should

## Expected result
node doesn't allow scaling further

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
the zoom level doesn't matter, it does the opposite if closer than 100% seems like the min width doesn't take the zoom into account and only works correctly at 100% zoom

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
