### ISSUE TITLE
Flowchart: scaling overlap

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7680]
## Problem description
scaling can overlap nodes (maybe duplicate)

https://github.com/Scirra/Construct-bugs/assets/89512047/69d61ea4-cdc0-4424-a1bb-894d3c4ee285

## Attach a .c3p
[overlapNode.zip](https://github.com/Scirra/Construct-bugs/files/13708804/overlapNode.zip)

## Steps to reproduce

1. scale the bottom node from the bottom edge upwards

## Observed result
nodes overlap

## Expected result
nodes don't overlap

## More details
might be a duplicate of https://github.com/Scirra/Construct-bugs/issues/7655, but repro is slightly different so decided to report it too

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This should be fixed in the next beta along with #7655 and other similar issues resizing nodes.
