### ISSUE TITLE
Flowchart: dark theme grid too high contrast

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7682]
## Problem description
The grid of the Flowchart background has really high contrast (light grey and dark grey). Their higher contrast than the nodes themselves, drawing eyes away from to nodes to the background. To me the grid is only there to orient and show scale it should be lower contrast.

## Steps to reproduce

1. look at flow chart in dark theme

## Observed result
High contrast grid lines competing with nodes
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/e41a4305-efb1-4415-a1d7-8c39eae1e339)

## Expected result
Some other grey that has less contrast with the background color.
Example with slightly darker grey but could also be a darker grey than the background, so the contrast is the other way.
![test2](https://github.com/Scirra/Construct-bugs/assets/89512047/063a6759-fc07-4153-903f-3e52c8149aa0)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Changed for the next beta.
