### ISSUE TITLE
bbcode outline lineThickness:  sans-serif font have burrs

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7684]
## Problem description

If lineThickness is greater than 1, some strokes will have glitches.

![Snipaste_2023-12-19_15-49-52](https://github.com/Scirra/Construct-bugs/assets/45864744/a208eedc-6ac8-4d4c-879a-9d06cb4fe85e)

```
[lineThickness=2][outline=#FFFFFF]W[/outline][/lineThickness] [lineThickness=2][outlineback=#FFFFFF]W[/outlineback][/lineThickness]
```

In sans-serif and serif fonts, some characters will also have this deviation.

![Snipaste_2023-12-19_15-55-28](https://github.com/Scirra/Construct-bugs/assets/45864744/419e8d39-dad3-4471-b9a2-31e2aadb45b1)

```
[font=sans-serif][lineThickness=3][outlineback=#FFFFFF]W[/outlineback][/lineThickness][/font]
[size=10]sans-serif[/size]
[font=serif][lineThickness=8][outlineback=#FFFFFF]W[/outlineback][/lineThickness][/font]
[size=10]serif[/size]
```

In the CJK language, this impact is even more obvious.

![Snipaste_2023-12-19_15-56-14](https://github.com/Scirra/Construct-bugs/assets/45864744/302e04f4-987c-49e1-8dc9-7ea7862432f6)

```
[font=sans-serif][lineThickness=3][outlineback=#FFFFFF]购买[/outlineback][/lineThickness][/font]
[size=10]sans-serif[/size]
[font=serif][lineThickness=8][outlineback=#FFFFFF]购买[/outlineback][/lineThickness][/font]
[size=10]serif[/size]
```

## Attach a .c3p

[issue-bbcode-lineThickness.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13712725/issue-bbcode-lineThickness.c3p.zip)

## Steps to reproduce

1.
2.
3.

## Expected result

get a good stroke effect.
https://codepen.io/RilDev/pen/vYeOjgj
https://codepen.io/shermanchens/pen/ZPBwyJ

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The browser draws the outline, not Construct. That's just how the browser draws stroked text with a thick line to a canvas. You could report it to browser makers if you want, but it works the same in Chrome and Firefox, so it may well be by design.

**Comment by XHXIAIEIN** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1513140

**Comment by XHXIAIEIN** [comment]
Feb 20, 2024 11:18PM
Status: Won't Fix (Infeasible)
This related to issues 40789021 and 40789021 - a consequence of trying to extract contours for stroking. There is not spec'ed solution for this and this will go wrong depending on font contours. I suggest to use a different styling or a different font if possible.
As you say, this does not work in other browsers either. `-webkit-text-stroke` is a non-standard property.

**Comment by XHXIAIEIN** [comment]
What if we use SVG text instead of Canvas text? Is this possible? This way we can change the appearance of the text through CSS
