### ISSUE TITLE
Empty podfile generates with every project which results in dependency issues in Xcode

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7686]
## Problem description

Every project includes an empty podfile (as well as pods.json, pods-release.xcconfig and pods-debug.xcconfig) even though it is not required. Because of this, you cannot export in Xcode because of missing dependencies. However, running `pod install` locally in the folder fixes the issue (but actually installs nothing). I've tested this on two machines (my win 11 pc running chromium and my m1 macbook running regular chrome, latest version) and the behavior is exactly the same.
Also, if I actually do have a valid podfile because I am using e.g. mobile advert, the pod folder is not generating either. 
<img width="507" alt="Bildschirmfoto 2023-12-19 um 21 56 02" src="https://github.com/Scirra/Construct-bugs/assets/80539587/973c72f3-fcdf-4663-bf5c-eda7e8e3c48b">
(this is how the pod install log looks like, it generated empty folders except the target support files one which is actually necessary cuz of the dependency)

## Attach a .c3p

[iosExortTest.zip](https://github.com/Scirra/Construct-bugs/files/13720204/iosExortTest.zip)
[iosExortTest.ios.project.zip](https://github.com/Scirra/Construct-bugs/files/13720205/iosExortTest.ios.project.zip)

## Steps to reproduce

1. Create a new project and fill in the details
2. I added one object (a standard text object, but it doesn't matter)
3. Export the project to xcode, in my case, xcode project, webp compression, minify simple, deduplicate images, version 14+

## Observed result

Empty podfile generates but no pod folder. 

## Expected result

No podfile is needed (and it should install pods if it was needed)

## More details
Looking back, my first memo of this being broken is from April 9th 2023. However, I can't say for sure whether that was the case for "emtpy" projects too at that point in time. However, for empty projects, it has been broken for a few months already as well. (noted that at the end of April). I‘ve always been using the latest stable release (at the time, r350),  but maybe this is related to the build service. 

I have a few addons installed (for ads, radial progress, qr code scanner etc.) but as they are not part of the project I don‘t think that can affect it in any way (but you might know better).

## System details

<details><summary>Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 120.0.6099.109
Browser engine: Chromium
Context: webapp
Operating system: macOS 14.0.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 137 gb
Storage usage (approx): 1.1 gb (0.8%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
When I export the provided project to an Xcode project, there is no Podfile in the resulting zip, so that does not reproduce for me.

However this is a known issue with Cordova (not Construct) when using some plugins like the Browser object. It's been reported here: https://github.com/apache/cordova-ios/issues/1365

**Comment by therealPaulPlay** [comment]
> When I export the provided project to an Xcode project, there is no Podfile in the resulting zip, so that does not reproduce for me.
> 
> However this is a known issue with Cordova (not Construct) when using some plugins like the Browser object. It's been reported here: [apache/cordova-ios#1365](https://github.com/apache/cordova-ios/issues/1365)

Yes, interesting that it doesn’t reproduce - I‘ve tried it on my windows pc and macbook. As I specifically mentioned, I‘m not using any plugin. No browser plugin as well. I‘m getting the empty podfile and xxconfig files every time. The issue per se is not new, It has been the case for third party plugins too for a long time but without any plugins is rather new (april) for me. It‘s really weird though that it isn’t the same for you…

**Comment by therealPaulPlay** [comment]
Quick update:
The example project generates an empty pod file for me because I have a a behavior plugin installed, that seemingly causes this. 

However, with Cordova scheme set to legacy, this also happens when I open Construct in a fresh browser without any plugins installed.

**Comment by fredriksthlm** [comment]
When you set _Hide status bar_ then Construct includes the plugin cordova-plugin-statusbar and official Cordova plugins creates a podfile when used. When you use this setting in Construct the app is opened **with** the statusbar present, and via code (via this plugin) the statusbar is hidden after launch programatically.

This is though never a good approach in hiding the statusbar and should not really be used by Construct projects either (the plugin should only be used if you need to trigger the statusbar off/on during runtime). If you do not want the statusbar at all you should state that in the p-list for ios apps and in the theme for Android apps and you should not use this plugin at all.


The below keys removes the statusbar for iOS apps and fixes your issue.

`<key>UIStatusBarHidden</key>
<true/>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>`
