### ISSUE TITLE
Whitelist plugins (urgent)

### ISSUE THREAD

**Issue by sspnet-tech-developer** [Scirra/Construct-bugs#7689]
```
cordova.plugin.yabbi@1.0.6
cordova.plugin.madex@1.0.6
cordova.plugin.yabbi.mediation@1.0.6
cordova.plugin.madex.mediation@1.0.6
```

Reason: Build failure due to conflict with dependency when mixed.

**Comment by AshleyScirra** [comment]
Please make sure you test your dependencies work correctly with local builds before requesting adding to the build service. This process requires us to perform a security review and we do not want to do that work just for testing purposes.

**Comment by sspnet-tech-developer** [comment]
@AshleyScirra We apologize, we check everything we send to your server locally, merry cristmas =)

**Comment by AshleyScirra** [comment]
Added to the build service.
