### ISSUE TITLE
Else color doesn't update when setting block to OR

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7695]
## Problem description

Else color doesn't properly update when setting a block to OR/AND

## Attach a .c3p

N/A

## Steps to reproduce

1. Create a block with a valid Else condition and another condition under it
2. Set block to OR
3. update the event in any way (adding condition, moving a condition, moving the block etc)
2. Set block to AND
3. update the event in any way (adding condition, moving a condition, moving the block etc)

## Observed result

Else color only updates after another action has updated the block

https://github.com/Scirra/Construct-bugs/assets/11213825/8edf231f-250e-4210-96ae-711f9526c16c

## Expected result

Else color should change immediately when setting the block to OR or back to AND

## More details

This is purely visual, doesn't affect anything else from what I've tested

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7003

Note that this also blocks the preview.

**Comment by AshleyScirra** [comment]
Looks like a variant of #7003 so closing as duplicate.
