### ISSUE TITLE
FaceImagePointZ is not taking Z elevation of the 3d shape into account

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7699]
## Problem description
FaceImagePointZ is not taking Z elevation of the 3d shape into account

## Attach a .c3p
[facePointZ.zip](https://github.com/Scirra/Construct-bugs/files/13786079/facePointZ.zip)

## Steps to reproduce

1. start preview

## Observed result
text keeps printing 7.5

## Expected result
text keeps changing as the shapes Z elevation is changing

## More details
keeping z-elevation in object space is a bit confusing as the normal image point expressions are returned in layer space.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
