### ISSUE TITLE
flowcharts - duplication crash

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-bugs#7700]
## Problem description

Duplicating a flowchart from the project panel causes the editor to crash when there is at least one node in the flowchart.

## Attach a .c3p

As this can be reproduced in an empty project in about 3 seconds, I'm not bothering with uploading a c3p. It can also be triggered in the provided flowchart examples.

## Steps to reproduce

1. Create a flow chart in an empty project. .
2. In the flow chart add at least one node
3. In the project panel, right click the flowchart and click 'duplicate'.

## Observed result

The editor crashes

## Expected result

For no crash to occur

## More details

**Affected browsers/platforms:** 

Chrome and Firefox

**First affected release:**

r372.2 beta

## System details

Error report information
Type: unhandled rejection
Reason: Error: output is not in node @ Error: output is not in node at window.EO.ge (https://editor.construct.net/r372-2/projectResources.js:1805:172) at LT (https://editor.construct.net/r372-2/components/editors/flowchartView/flowchartView.js:21:412) at Array. (https://editor.construct.net/r372-2/components/editors/flowchartView/flowchartView.js:94:405) at window.Wnb.dispatchEvent (https://editor.construct.net/r372-2/main.js:1265:42) at Cv (https://editor.construct.net/r372-2/projectResources.js:51:208) at window.EO.gb (https://editor.construct.net/r372-2/projectResources.js:1805:408) at window.EO.Dg (https://editor.construct.net/r372-2/projectResources.js:1807:442) at window.EO.Da (https://editor.construct.net/r372-2/projectResources.js:1808:213) at AGa (https://editor.construct.net/r372-2/projectResources.js:149:112) at window.kl.Da (https://editor.construct.net/r372-2/projectResources.js:1802:78)
Stack: Error: output is not in node at window.EO.ge (https://editor.construct.net/r372-2/projectResources.js:1805:172) at LT (https://editor.construct.net/r372-2/components/editors/flowchartView/flowchartView.js:21:412) at Array. (https://editor.construct.net/r372-2/components/editors/flowchartView/flowchartView.js:94:405) at window.Wnb.dispatchEvent (https://editor.construct.net/r372-2/main.js:1265:42) at Cv (https://editor.construct.net/r372-2/projectResources.js:51:208) at window.EO.gb (https://editor.construct.net/r372-2/projectResources.js:1805:408) at window.EO.Dg (https://editor.construct.net/r372-2/projectResources.js:1807:442) at window.EO.Da (https://editor.construct.net/r372-2/projectResources.js:1808:213) at AGa (https://editor.construct.net/r372-2/projectResources.js:149:112) at window.kl.Da (https://editor.construct.net/r372-2/projectResources.js:1802:78)
Construct version: r372.2
URL: https://editor.construct.net/r372-2/
Date: Sat Dec 30 2023 19:00:05 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 56.3 s

Platform information
Product: Construct 3 r372.2 (beta)
Browser: Chrome 120.0.6099.130
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.6500000953674316
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6700 XT (0x000073DF) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
