### ISSUE TITLE
Flowcharts: Adding a new output to an already connected node results in crash

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7701]
## Problem description

When you create two nodes and then add a new output to the first one, it crashes.

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-bugs/files/13798213/New.project.zip)
![image](https://github.com/Scirra/Construct-bugs/assets/80539587/90c33ee8-35bc-44f9-8fb9-42b1b9f8ef67)

## Observed result

It crashes

## Expected result
It shoud not crash

## System details
r372.2 (crash log below)

<details><summary>View details</summary>

Error report information

Type: unhandled exception
File: https://editor.construct.net/r372-2/components/bars/propertiesBar/propertiesBar.js, line 59, col 255
Message: TypeError: cnb is undefined
Stack: dnb/h<@https://editor.construct.net/r372-2/components/bars/propertiesBar/propertiesBar.js:59:255
Construct version: r372.2
URL: https://editor.construct.net/r372-2/
Date: Sat Dec 30 2023 14:55:32 GMT+0100 (Central European Standard Time)
Uptime: 104.2 s
Platform information

Product: Construct 3 r372.2 (beta)
Browser: Firefox 121.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0
Language setting: en-US
WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Radeon R9 200 Series Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7676
