### ISSUE TITLE
Unlimited FPS (Full frames) enabled: Game gets progressively more laggy on iOS until it suddenly runs smoothly

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7702]
## Problem description

Using "unlimited fps" on iOS behaves weirdly. This option is of course not meant for exports but is handy for on-device performance testing and I'd be glad if this worked well.

## Attach a .c3p
This is just a very minimal platformer game with an fps counter (top right side) for testing.
[DoodleJumpRipoff.zip](https://github.com/Scirra/Construct-bugs/files/13799392/DoodleJumpRipoff.zip)

## Steps to reproduce

1. Create a game
2. Set the framerate mode to unlimited (full frames)
3. Export to iOS and test it

## Observed result
At first, the fps counter reports really high fps values (sometimes 4000+) but the game feels very laggy and gets progressively more laggy until it almost comes to a standstill, after which it feels super smooth. Then however, the fps values are much lower (still high though, around 2000). This is very annoying for testing as the "laggy" phase can sometimes be pretty long (like, a few minutes), other times it is only a few seconds long. 

The example video shows a very short "laggy" phase (but sometimes it takes a lot longer):

https://github.com/Scirra/Construct-bugs/assets/80539587/923b21c0-e9a0-4394-bdd9-1450e6866397

Note that the beginning here doesn't look all that laggy on video but actually feels very laggy on device and it only feels smooth after the big lag spike. The basically identical game in unity does not show this odd behavior with unlimited fps.

## Expected result

It should feel very smooth and report accurate fps values.

## More details
Using r3682. stable

## System details

<details><summary>View details</summary>

Tested on the iPhone 15P running ios 17.2.1.

</details>

**Comment by AshleyScirra** [comment]
If it works on all other platforms but only has a problem on iOS, it sounds a lot like a bug with Safari's frame scheduling. This is beyond our control and not something we can easily influence from Construct's code, so is best reported directly to Apple. So please file an issue with them here: https://bugs.webkit.org/
Post the issue link here and I will follow it to answer any Construct-specific questions.

**Comment by therealPaulPlay** [comment]
Alright, I've filed a bug [here](https://bugs.webkit.org/show_bug.cgi?id=267054). I can say that the option works smoothly on my android phone, however, it leads to a crash on PC (Chrome 117) after around 30-60 seconds so it's not "perfect" either ;) These 30-60 seconds are very smooth though and are enough for testing
