### ISSUE TITLE
3D Camera Forward Vector is not being properly updated by the rotate action 

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7706]
## Problem description

The camera's 3D forward vector is changed by the rotate action, but the new value isn't being reflected back in the camera's data.

## Attach a .c3p
[camera Forward Vector bug.zip](https://github.com/Scirra/Construct-bugs/files/13821309/camera.Forward.Vector.bug.zip)

## Steps to reproduce

1. Preview
2. Press "A" to toggle rotate modes

## Observed result

Forward vector is not being properly updated

## Expected result

Forward vector is being properly updated

## More details

I encountered this issue while implementing my FMOD addon to Construct. FMOD's spatialisation requires the use of the camera's forward vector to position the sounds appropriately. This seems to be the same issue as this bug report:
https://github.com/Scirra/Construct-bugs/issues/6436

May I respectfully ask why that might ever be "by design"?
Looking through the engine's code, the camera rotate action seems to calculate a new unrelated forward vector from the rotated look at, but that just never gets stored in the camera's forward vector, and really I can't seem to understand any reason why the camera's forward vector would ever not point forward.
I'm guessing it's related to Quaternions and the Gimball Lock problem?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
IIRC the forward vector does not change with camera rotation, as it means you can use the forward vector for movement ignoring mouse look, which I think a couple of existing projects do. It's easy to work around: as noted in #6436, just subtract the look position from the camera position, as is recommended in the [Audio manual entry](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/audio):

> When using the Rotate camera action of 3D Camera (e.g. for mouse look), the ForwardX/Y/Z vector of the camera does not change. Instead to get the correct orientation for 3D Audio, use `3DCamera.LookX - 3DCamera.CameraX` for the X component, and repeat similarly for the Y and Z components.

**Comment by skymen** [comment]
Yeah, understood this is by design, and I agree that it is easy to workaround, but it is arguably easier (and less confusing) to just work around the issue you described by just storing an angle value in a separate variable.

Because to me at least, it makes zero sense for the camera's forward to point forward but not the forward of the camera, like another forward that I defined by setting the camera rotation, but not with the rotate camera action, so it defined a forward and now I can rotate the camera while not touching the camera forward so the camera forward keeps pointing forward in an arbitrary other direction that isn't actually forward.

ESPECIALLY when if I want to "Press W to move forward" I would expect the player to move forward based on where the camera is looking at. Like at all times. Otherwise, I would move at a given other arbitrary angle that I can define separate from the camera.
