### ISSUE TITLE
ADD FOLDER "EMPTY" ON OPEN/BROWSER STORAGE ERRORS

### ISSUE THREAD

**Issue by Walerowski** [Scirra/Construct-bugs#7710]
## Problem description

If you click "Add Folder" on the menu "Open/Browser Storage" and you will click the "OK" button and leave the directory name blank an error occurs.

## Steps to reproduce

1.
2.
3.

## Observed result

Error report information
Type: unhandled rejection
Reason: Error: d.trim is not a function @ TypeError: d.trim is not a function at Pl (https://editor.construct.net/r368-2/main.js:708:22) at Hl.g.J.dZc.b7a (https://editor.construct.net/r368-2/main.js:2730:206)
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
