### ISSUE TITLE
Clipboard fails to ask for permission in chrome

### ISSUE THREAD

**Issue by Aldenwar** [Scirra/Construct-bugs#7715]
## Clipboard plugin doesn't allow copying in html 5 export

Trying to copy text with mouse "on object clicked" action fails, when done in a web export, at least on Chrome and Brave browsers. Firefox or playing in the editor on the other hand has no problems, and immediately copies on click. On erroring browsers, prints these errors on brower console:

[Violation] Permissions policy violation: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
main.js:251

Failed to copy to clipboard:  DOMException: The Clipboard API has been blocked because of a permissions policy applied to the current document. See https://goo.gl/EuHzyv for more details.
_OnCopyText @ main.js:251

## 
[ClipboardTest Bug.zip](https://github.com/Scirra/Construct-bugs/files/13846181/ClipboardTest.Bug.zip)

## Steps to reproduce

1. Export the project included to some site like itch.io as html5 
2. Play the exported project
3. Click on the sprite, which should copy some text to clipboard

## Observed result

Notice on Brave/Chrome text was not copied and browser console throws error. On Firefox behavior is  as expected

## Expected result

Works on all browsers.

## More details

**Affected browsers/platforms:** 
Chrome, Brave

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Can not reproduce. I uploaded the exported project to netlify and copying to the clipboard works fine. There are no errors.

**Comment by Aldenwar** [comment]
Hm, okay, thank you for the information. It was very difficult to find anything by googling the issue. 

However, if a site-wide policy is the reason, then why does Firefox still manage to perform the copying without an issue?

**Comment by ErichRonis** [comment]
ErichRonis_PrOgRi-KI
