### ISSUE TITLE
Can't rename behaviors

### ISSUE THREAD

**Issue by Scoremonger** [Scirra/Construct-bugs#7717]
## Problem description

I'm unable to rename family or object behaviors in 373.2 (372.2 was fine.) The cursor appears for a split second, then goes away.

## Attach a .c3p

Any project with a behavior will do.

## Steps to reproduce

1. Open any project containing an object with a behavior, or create a new project with a single object + any behavior.
2. Attempt to rename the behavior by double-clicking, right-clicking and chosing "Rename" from the context menu, or hitting F2 with the behavior selected in the behaviors list.

## Observed result

The cursor will appear on the behavior name for maybe one frame, then disappears. Typing does not change the behavior name.

## More details

**Affected browsers/platforms:** Tested in Chrome + Edge on Windows.

**First affected release:** Worked in 372.2, broken in 373.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r373.2 (beta)
Browser: Edge 120.0.2210.91
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 265 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti (0x00002208) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Works fine for me. Perhaps you have a browser extension installed that is interfering?

**Comment by Scoremonger** [comment]
I don't believe so - I've tried the Microsoft Store version on one computer, and a Google Chrome browser with all extensions disabled on two different computers, and have seen the same problem in all cases. 372.2 in Chrome works fine on both PCs I've tested with, too.

**Comment by WilsonPercival** [comment]
> Works fine for me. Perhaps you have a browser extension installed that is interfering?

@AshleyScirra This works well in the default theme. But it doesn't work well in dark theme. Also note that this worked well in `r372b`.

https://github.com/Scirra/Construct-bugs/assets/91274932/2b060345-a969-4c65-85c3-41d2c708235c

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.

Was a regression introduced with the changes made to the table control needed for Flowcharts.
