### ISSUE TITLE
NW / WV2 exported project doesn not save window size

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#7718]
1) Export a project in NW and VW2
2) Run the game, change window size
3) Close and run again

Expected: window size is remembered.
Result: window size resets.

C3 373.2
Windows 11

**Comment by AshleyScirra** [comment]
Construct does not currently make any attempt to save and restore the window size in desktop exports. You might be able to implement that logic yourself, or file a feature request.
