### ISSUE TITLE
Memory leak create and destroy sprite 166 sec bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7719]
## Problem description

When I create and delete sprites, I noticed that there are sometimes significant spikes in `FPS` (at first I thought it was the `garbage collector` doing its job). But when I waited for about `166 seconds`, I saw that the game started losing `FPS`, after which it froze completely.

## Attach a .c3p

[memory_leak_create_and_destroy_sprite_160_sec_bug_r323b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13852494/memory_leak_create_and_destroy_sprite_160_sec_bug_r323b.zip)

## Steps to reproduce

1. Open and run the project.
2. Wait `166 seconds` or more.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/9fb4fb7b-edf9-499e-9fc1-ec40cf1934b5

## Expected result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/ea8a92e1-3915-42c1-bb2f-2cac659d78d4

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Worked well in `r323b`, broke in `r324b`. Still doesn't work in `r373-2b`.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r373.2 (beta)
Browser: Chrome 120.0.6099.130
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 123 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
There was indeed a small memory leak creating and destroying some kinds of objects which could accumulate over time. This is fixed for the next beta.

FWIW you don't need to wait so long to check for a memory leak - press Shift+Escape in Chrome and you can use its own task manager to check the memory use of individual tabs/windows, and check if the memory usage is increasing abnormally.

**Comment by DinoSystem** [comment]
Wilson strikes again! Good catch!

**Comment by WilsonPercival** [comment]
> There was indeed a small memory leak creating and destroying some kinds of objects which could accumulate over time. This is fixed for the next beta.
> 
> FWIW you don't need to wait so long to check for a memory leak - press Shift+Escape in Chrome and you can use its own task manager to check the memory use of individual tabs/windows, and check if the memory usage is increasing abnormally.

@AshleyScirra Great! Thank you very much, I will use it)
