### ISSUE TITLE
Physics behavior is not applying while Pathfinding is moving.

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7720]
## Problem description

My physics objects need to find a path to the target, but pathfinding controls the movement to an extent where physics is not applied. Objects overlap each other in unrealistic way, then suddenly behave after they arrive. They look like they are fighting each other for space.
I tried making the physics drive the pathfinding instead (by looping over nodes and applying force towards it), but the objects get stuck (object A is in front of B, and B is trying to apply a force pushing A instead of moving around it).

In summary: pathfinding objects have no awareness of themselves. each one is just trying to move on the path regardless of others.

I have tried changing the cell size and border, but it didn't work.
I have tried adding other objects/families as obstacles, but it didn't work.

## Attach a .c3p
[pf and physics.zip](https://github.com/Scirra/Construct-bugs/files/13852603/pf.and.physics.zip)

## Steps to reproduce

1. Run the project

## Observed result

Objects overlap each other while moving, but doesn't overlap after they arrive.

## Expected result

Physics objects shouldn't overlap.

**Comment by AshleyScirra** [comment]
See the tutorial [Physics in Construct: the basics](https://www.construct.net/en/tutorials/physics-construct-basics-6). The Physics behavior does not interact properly with other behaviors as your project tries to do. Other behaviors will basically teleport physics objects to overlap each other, which is not allowed by the physics engine, and so cause strange physics simulation results.
