### ISSUE TITLE
Tilemap brush window crash if the C3 is offline.

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7722]
## Problem description

I rarely use Tilemap brushes, but I needed it once and my internet was down. I tried opening the brushes window, select a brush and edit some tiles, but I it always crashed during the middle of the process. All worked well after the internet returned and C3 was online.

## Attach a .c3p

(Invert Gravity Platformer example)

## Steps to reproduce

1. Open the project
2. Go offline
3. Open tilemap brushes window
4. Select a brush
5. Change some tiles
6. Do any other operation in the window

## Observed result
Crash

## Expected result

No crash

## More details

**Affected browsers/platforms:** Chrome app

**First affected release:** previous stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This might be fixed, along with a whole bunch of similar issues related to offline support. Can't really test it in development so will have to wait to see how everything works in the next beta,

**Comment by AshleyScirra** [comment]
@DiegoScirra - can test now with r374.

**Comment by DiegoScirra** [comment]
Just tried this out and it looks to be working properly now. Will close now.
