### ISSUE TITLE
Particles object save and load bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7724]
## Problem description

When I load the game, the game does not restore correctly. It can be seen that the particle sprites have frozen.

## Attach a .c3p

[particles_object_save_and_load_bug_r122b.zip](https://github.com/WilsonPercival/WilsonPercival/files/13853302/particles_object_save_and_load_bug_r122b.zip)

## Steps to reproduce

1. Open and run the project.
2. Press `1` to create particles.
3. Press `2` to save the game.
4. Reload the page.
5. Press `3` to load the game.

## Observed result

https://github.com/WilsonPercival/WilsonPercival/assets/91274932/d95e2422-3ed1-4e7a-94fb-48c576413e00

## Expected result

There should be no extra sprites after loading.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** `r122b` because this is the first release in which the ability to bind an object to particles became available. It's strange why you didn't write about this in the issue.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r373.2 (beta)
Browser: Chrome 120.0.6099.130
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 123 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by NukeThemAllGame** [comment]
**Update from Mike (Nuke them all game) on the same save game bug issue.** 

The game is not able to save any particle systems. It simply crashes with the bug attached. 
![bugs_](https://github.com/Scirra/Construct-bugs/assets/154996981/3e123e29-7716-4989-8273-f5af9ad43f5b)

However if I stop time (time scale 0) and then force destroy particle system BEFORE saving, the game would not crash.

So i confirm the issue with the particle system save game bug, hopefully you can fix

**Comment by NukeThemAllGame** [comment]
Additionally  If I dont force "stop time" using Set time scale to 0 , the save game would crash 100% even without particles.
I would suggest to hard-code stop time into saving function to avoid this. so construct first stops time, then saves, then resumes time automatically. This way it would not crash for bigger projects like mine because it simply cant save fast enough if i dont stop time manually. Cheers!

![stop_time](https://github.com/Scirra/Construct-bugs/assets/154996981/a8d9bcf7-013c-47ef-b5bf-8f00f21e8d8e)

**Comment by NukeThemAllGame** [comment]
Additionally when using **load** function I always get following **error** and game **freezes**:

![load_bug](https://github.com/Scirra/Construct-bugs/assets/154996981/7b48a760-bb65-4e08-81e8-392988855157)

**Comment by WilsonPercival** [comment]
@NukeThemAllGame Can you message me on discord (wilson_percival)? I need the project file and reproduction steps.

**Comment by NukeThemAllGame** [comment]
> @NukeThemAllGame Can you message me on discord (wilson_percival)? I need the project file and reproduction steps.

I sent you friend request (from papamike) on discord

**Comment by AshleyScirra** [comment]
@NukeThemAllGame - that looks unrelated to this issue, as the project provided in this issue does not log any errors. You will need to file a separate issue for that for it to be fixed, as fixing this issue likely won't affect that one.

**Comment by AshleyScirra** [comment]
Looks like @DiegoScirra last touched this code when fixing #5177 so assigning.

**Comment by DiegoScirra** [comment]
The original issue will be fixed in the next beta, along with another minor issue which was causing restored particles to be drawn with an incorrect opacity for a short time.
