### ISSUE TITLE
Objects with physics behavior not working properly in some situations

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-bugs#7726]
## Problem description

The Ball objects, with the physics behavior on, are not moving in some situations. 

## Attach a .c3p

https://www.dropbox.com/scl/fi/phbca6d9i50w943y50tm7/PhysicsTest.c3p?rlkey=mn27fjdt51v3ogfcf9knlx266&dl=0

## Steps to reproduce

1. Open the example .capx and preview it.
2. Wait 1 second for the ball to stop completely.
3. Press SPACE bar to rotate the arm object (that is using tween behavior).

Check this video out:

https://github.com/Scirra/Construct-bugs/assets/9966693/86204e88-1ed1-42ca-9076-0a5bf5e1c439

## Observed result

The Ball object froze.

## Expected result

The Ball should slide down.

## System details

Platform information
Product: Construct 3 r373.2 (beta)
Browser: Chrome 120.0.6099.199
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
View details</summary>

**Comment by AshleyScirra** [comment]
See the tutorial [Physics in Construct: the basics](https://www.construct.net/en/tutorials/physics-construct-basics-6). The Physics behavior does not interact properly with other behaviors as your project tries to do. Other behaviors will basically teleport physics objects to overlap each other, which is not allowed by the physics engine, and so cause strange physics simulation results. You should try to keep all Physics-related movement in terms of the Physics behavior actions.
