### ISSUE TITLE
Can't change Audio Volume in Xbox

### ISSUE THREAD

**Issue by elmanuelv** [Scirra/Construct-bugs#7727]
Hi! I think there is a bug regarding the audio volume in the Xbox export.

## Problem description
When I try to use the "Set Volume" action, it works perfectly on the preview and PC exports, but when I export to Xbox using the new Xbox UWP option, the music plays at a constant volume and never decreases or increases its volume.

## Attach a .c3p
I created this project that only has the music and instructions on how to increase and decrease volume. As I explained, it works perfectly on PC but not when exporting to Xbox
[XboxAudioTest Project.zip](https://github.com/Scirra/Construct-bugs/files/13876540/XboxAudioTest.Project.zip)

## Steps to reproduce
1. Open the project and export to Xbox UWP
2. Port to Xbox
3. Press the direction buttons to increase/decrease music volume

## Observed result
The music volume stays the same

## Expected result
The music should change its volume

**Affected browsers/platforms:**
Xbox

**First affected release:**
r371

Thanks!

**Comment by elmanuelv** [comment]
Still happening in r375 😅 can you confirm you're getting the same result @AshleyScirra ?

**Comment by elmanuelv** [comment]
Hi Ashley! Thanks for the reply :)

I have already reported the issue to Microsoft
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4330

By the way, have you tried plugging the devkit directly to a screen using an HDMI?

Thanks for the help!

Manu

**Comment by AshleyScirra** [comment]
My headset arrived and I was able to reproduce this - it does look like an Xbox WebView2 bug as it works fine on Windows and exactly the same files don't work on Xbox. I was able to make a minimal repro and attach it to the Microsoft WebView2 issue you filed which hopefully helps them fix it quickly. Closing this issue as it will be followed up there.

**Comment by elmanuelv** [comment]
I don't think they will :/ 

UWP are no longer supported and from this year they're will reject all apps using it

**Comment by AshleyScirra** [comment]
> UWP are no longer supported and from this year they're will reject all apps using it

I've not seen anything saying that. Do you have a reference for that?

**Comment by elmanuelv** [comment]
They recently told me. Just sent you the information to support@construct.net since I'm not sure if I can share it here
