### ISSUE TITLE
Keyboard Mapping Example - Minor Fault

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-bugs#7731]
## Problem description
The "Keyboard Mapping" example has a logical error in which, when escaping an active key mapping action, it will not reset properly as expected.
Instead it remaps always to what's currently saved for the top menu action input.

## Attach a .c3p
https://editor.construct.net/#open=keyboard-mapping

## Steps to reproduce
1. Preview the example project
1. Navigate to the second or third menu entry by pressing arrow down. ( Walk right or Jump)
2. Hit Enter
3. Hit Escape

## Observed result
Input is being reset to value "Walk left" instead of the currently selected option.

## Expected result
Reset to the correct action input.

## More details
The culprit is within the group "Keyboard mapping" at "Escape is down" the function call is being called with the keycode value `KBMappingArr.At(TextInput.menuEntry)` instead of `KBMappingArr.At(currentEntry)`.
![image](https://github.com/Scirra/Construct-bugs/assets/12261601/7a8d0bef-eb88-45af-8f38-86fb54b2807a)

**Affected browsers/platforms:**
Unrelated

**First affected release:**
Since example release

## System details
<details>
Unrelated
</details>

**Comment by fvcalderan** [comment]
Good catch! I'll correct the example for the upcoming beta release. Thanks!

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
