### ISSUE TITLE
[Addon SDK] IWorldInstance : GetRect() / GetBoundingQuad() / GetColor() return Rect/Quad/Color instead of IRect/IQuad/IColor

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#7733]
## Problem description

**EDIT :** I'm not sure if this is by design or not as we can still access the Rect/Quad/Color methods, but leaving it open just in case

**If it's returning the right types, why does it look like the variables are obfuscated ?**

___________________________

IWorldInstance : GetRect() / GetBoundingBox() / GetColor() return Rect/Quad/Color instead of IRect/IQuad/IColor

![image](https://github.com/Scirra/Construct-bugs/assets/99751718/4920ae85-74c7-427c-beeb-9e13562a24ea)

## Attach a .c3p

Not possible

## Steps to reproduce

1. Try to access one of this method from the exposed Editor SDK

## Observed result

Returns obfuscated Secret SDK instances instead of Exposed SDK instances which means those method are useless and unusable despite being some of the very few exposed method of the editor SDK.

## Expected result

Returns Exposed SDK instances

## More details

Please make sure all exposed methods returns public instances in the Editor SDK. There was a similar issue not so long ago with Textures, I suspect there might be other places where it doesn't work as expected (might be worth to check all Get Methods from every interfaces)

![image](https://github.com/Scirra/Construct-bugs/assets/99751718/5ca9e919-7497-4ea6-bc3b-391dcc3f89f8)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It looks like it's working correctly to me. [The documentation](https://www.construct.net/en/make-games/manuals/addon-sdk/reference/object-interfaces/iworldinstance) says it returns SDK.Rect/Quad/Color classes, and the methods do return those types, and those types are themselves documented in the "Geometry interfaces" section.
