### ISSUE TITLE
[Addon SDK - Editor API] Missing obvious methods : IInstanceBase.OnDestroyed() & IInstanceBase.Destroy()

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#7734]
## Problem description

Editor Addon SDK is missing obvious methods : IInstanceBase.OnDestroyed() & IInstanceBase.Destroy()
(no sure if this should be on the IInstanceBase or IInstance)

## Attach a .c3p

Impossible

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a feature request so please file it on the suggestions tracker.
