### ISSUE TITLE
[Addon SDK - Editor API ] Missing obvious Hierarchy Methods

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#7735]
## Problem description

Exposed Editor API missing obvious Hierarchy Methods on the IWorldInstanceBase or IWorldInstance :

obvious :
GetChildren()
GetAllChildren()
GetParent()
AddChild(args)
RemoveFromParent()

less obvious, but still :
OnChildAdded(childIWorldInstance)
OnChildRemoved(childIWorldInstance) : also triggered when Child is Destroyed
SetHierarchyParams(HierarchyParams) : allow to override Hierarchy parameters boolean, useful, for UI

## Attach a .c3p

Impossible

## More details

Those are probably trivial to add and it looks like an oversight but those additions would be game-changers for Editor Addon Making

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a feature request so please file it on the suggestions tracker.

**Comment by OverboyDev** [comment]
I already submitted a feature request for those here (2024) and on the last platform (2023)
https://github.com/Scirra/Construct-feature-requests/issues/15

However the feature request is about all the required methods for the Editor SDK to create cool UI systems which includes several more specific and less obvious method.

**Any chance to have basic OnDestroy()/Destroy() methods and basic Hierarchy methods like GetChildren/GetParent/AddChild/RemoveFromParent in a reasonable timeframe please ?**

Those all feel like oversight and those are probably just a matter of exposing existing stuff to the exposed Editor SDK while it would be a huge game-changer for 3rd party editor dev.
Not only it would help for UI but also to create a bunch of tools allowing to procedurally create and move instances directly from the editor. 
I've been stuck for too long on many things because of the lack of those simple "obvious" methods.

**Comment by AshleyScirra** [comment]
The SDK APIs are actually pretty complicated and the external APIs are particularly time-consuming and tricky to test adequately (sometimes involving building an entire fake plugin just to see if methods work properly). Please file suggestions to the suggestions tracker, as it is inappropriate to file feature requests to the bug tracker, even for things you assume are small or easy, but also please note in the feature request guidelines we ask that you do not claim your suggestions are easy, as [often minor features turn out to be complicated anyway](https://www.construct.net/en/blogs/ashleys-blog-2/unexpected-complications-1535). We also ask that you provide a compelling use case to help us prioritise suggestions, and issues like this one do not state any compelling use case nor review the workarounds, which usually means we would not prioritise it as it does not follow the suggestion guidelines.

**Comment by OverboyDev** [comment]
The usecase and workarounds are explained in the issue though.

I'm having a hard time to understand how I could write a more detailed and exhaustive feature request.

There is no way to create UI system that work at edit-time.

**Comment by OverboyDev** [comment]
Compare that feature request with almost any other feature request ever posted on all suggestions platform and you'll realize it provides way more details about the issue/the workarounds/the implementation than most of them

**Comment by OverboyDev** [comment]
Also I didn't claim it was easy I claimed it was a matter of exposing existing stuff which is true for the methods I categorized as "obvious".

**Comment by AshleyScirra** [comment]
What does "create a UI system" mean though? How does it actually work? What will the user do? What kinds of UI will it cover and what other kinds will it not cover? What is the involvement of hierarchies? What other alternatives have been considered, which could work, and which are insufficient, and why? Which parts of the request are essential and which are optional? This is all stuff we'd like to know, and so the feature request guidelines encourage you to explain all that, but if you look at just the issue filed here in the first post, it completely skips over all that.

We can't consider feature requests that say something like "I'm making an RPG and it's essential I have XYZ". It just leaves so much unsaid that there a high risk we don't cover what you actually want, that it turns out it's 5x as much work as originally stated (follow-up requests are extremely common - "actually I need ABC too, and it's useless without it..."), sometimes it was already possible another way, etc. etc. etc...

**Comment by OverboyDev** [comment]
Ok thanks I understand what you mean. I'll try to explain it better here while still keeping it as concise as i can:

I think the suggestion was more clear on the previous platform as I wrote it after a first proposal for a Scirra-made Hierarchy-based UI system, which didn't involve Behaviors but directly new Hierarchy settings, such as a "UI Hierarchy Mode" changing the other available Hierarchy settings - and that i linked in the new better Addon SDK proposal
Even if this idea is now obsolete thanks to this new proposal to add methods to the Editor API of the Addon SDK, it's worth a read to understand it details what could be made :
(obsolete request) **Hierarchy-based UI Autolayouting** https://construct23.ideas.aha.io/ideas/C23-I-78
Since then i thought it would be way better to just provide us the Editor API so anyone can do it itself making addons.

The main idea with those new Editor API would be that **Behaviors of an instance would be able to access and set the position/angle/scale of their parent and children**.

For example you could have a Vertical Layout or Gird Layout behavior that you put on a parent instances and that automatically layouts all its children based on the behavior parameters. (a few examples : child spacing, max number of columns).
I'm only giving the most basic example here because the true potential of it is immense.

Those Hierarchy-based Behavior-based UI system any addondev could create would have the benefit to perfectly work with everything else in the engine (**any world-object plugins such as 9Patch/TiledBG/Text would be compatible** while it's incredibly hard to do it via events with Families as multi-plugin family support doesn't exist), it would also work directly in editor exactly the same way it works at runtime, and doesn't involve very complex system to implement for Scirra. Just exposing existing stuff for the most part (with the exception of a few very handy methods I explain in details in the suggestion)

Most of the UI system made in Game-engines are hierarchy-based and work that way : parent UI objects have properties that acts on their UI children and everything happens live directly in the editor, this is the industry-standard.
Ressources about AutoLayouting in other Game Engines :
Godot Containers : https://docs.godotengine.org/en/stable/tutorials/ui/gui_containers.html
Unity Autolayouting : https://docs.unity3d.com/Packages/com.unity.ugui@1.0/manual/comp-UIAutoLayout.html
I especially recommend reading the Godot Container documentation as it's considered as the best UI system made in a popular Game engine and the documentation is very clear and concise.
_________________________

The methods i'm asking in the feature request are all important if we want to build such systems.
The least obvious are detailed extensively there (especially the MoveParentInstead(boolean))

For example, we should know the top parent Object changed its angle if we want to make sure to update the position of the full UI Hierarchy. For the same reason, we should be able to Trigger something when a Child is added/removed to an parent object with a "Horizontal Layout" behavior to update the position of all the remaining children.

__________________________

Every single method API suggestion listed in the suggestion would have an even bigger potential that just UI. For example, we could imagine creating a Plugin/Behavior called "DecorationGenerator", that takes an Object, a radius, and an instance count parameters. When pressing a callback link button "Generate", it would automatically generate that number of instances at random position inside the circle around the object defined by the radius. (to procedurally create a forest directly in editor for example). 

If we were able to Destroy instances via Editor API, we could add an other callback link button "Cancel" to destroy all the instances that were just created (or it could just happen automatically when regenerating the forest if the first generation doesn't please us). Right now we only can create instance but can't destroy them.

If Hierarchy API were a thing, all those procedurally generated instance could be automatically added as child of the generator so moving the generator moves the whole generated forest).

That last point is just a "dumb example" to show how exposing Destroy and Hierarchy methods to Editor API opens a lot of potential for Editor Tools in C3. (but again UI is the number 1 reason why the suggestion is that popular)

**Comment by AshleyScirra** [comment]
Just to be clear, this is a closed issue on the bugs tracker - this kind of content ought to be on the feature request tracker instead.

**Comment by OverboyDev** [comment]
I updated the 2024 suggestion to include all additional details, 

You can still access the post above easily from there as there is a link to this issue if you want the additional sentence and examples i wrote here but some of them are redundant with the last edit of the suggestion.

I saw you added a "major project" tag to the suggestion, this is why I ask again if at least some of the obviously missing methods could be pushed in a reasonable timeframe.

Every single listed API would enhance the possibilities.
