### ISSUE TITLE
Animation editor crash

### ISSUE THREAD

**Issue by NukeThemAllGame** [Scirra/Construct-bugs#7736]
I simply clicked on one of the animations and received a crash error (I copy paste it below)

[[## Attach a .c3p](https://discord.com/channels/@me/1194182264926515261/1194548088317165569)](https://drive.google.com/file/d/1JAGuoKs97o6L5TA5KEc18UbqF767WzFX/view?usp=sharing)

## Steps to reproduce

1. Open project
2. Double click on sprite called Flagcapture
3. Click on Default2 animation and construct will crash

## Observed result

 

Full crash

## More details

Edge browser 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r373-2/main.js, line 1054, col 141
Message: Uncaught TypeError: unexpected type
Stack: TypeError: unexpected type at Q.i (https://editor.construct.net/r373-2/main.js:1054:147) at PHa (https://editor.construct.net/r373-2/projectResources.js:189:22) at Array.ric (https://editor.construct.net/r373-2/projectResources.js:2232:145) at sy.g.J.cc.dispatchEvent (https://editor.construct.net/r373-2/main.js:1268:42) at kKa (https://editor.construct.net/r373-2/projectResources.js:280:392) at UB.Qqc.DSa (https://editor.construct.net/r373-2/projectResources.js:2582:23) at Array. (https://editor.construct.net/r373-2/projectResources.js:2578:63) at CCG.uh.g.J.ZQa.dispatchEvent (https://editor.construct.net/r373-2/main.js:1267:399) at CCG.uh.g.J.ZQa.BP (https://editor.construct.net/r373-2/main.js:1635:391) at CCG.uh.g.J.ZQa.lI (https://editor.construct.net/r373-2/main.js:1630:24)
Construct version: r373.2
URL: https://editor.construct.net/r373-2/
Date: Wed Jan 10 2024 19:07:45 GMT+0000 (Western European Standard Time)
Uptime: 110224.2 s

Platform information
Product: Construct 3 r373.2 (beta)
Browser: Edge 120.0.2210.91
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.125
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00009A60) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
Normally it is not possible to have an animation with no frames. The only thing I can think about, is that the project is the result of a previous crash and when clicking "Save" on the crash report dialog, this invalid project was saved.

It's impossible to figure out what happened previously, so unless there are anymore clues, I will have to close.

**Comment by NukeThemAllGame** [comment]
> Normally it is not possible to have an animation with no frames. The only thing I can think about, is that the project is the result of a previous crash and when clicking "Save" on the crash report dialog, this invalid project was saved.
> 
> It's impossible to figure out what happened previously, so unless there are anymore clues, I will have to close.

I dont know why it happened but I've seen this bug before few times, just did not report... I suggest in such cases to delete animation automatically to prevent futher crashes if it has no frames. I cant even delete it, even if I right click on it it just crashes.

Thank you

**Comment by WilsonPercival** [comment]
@DiegoScirra Maybe it's similar to this? https://github.com/Scirra/Construct-bugs/issues/7384

**Comment by NukeThemAllGame** [comment]
> #7384

That bug was discussed in September so I assume it was not fixed, because my report is about current build of construct and it still happens.

I would suggest following - if somehow animation has no frames either automatically delete it or  add single empty frame. Both solutions is better than full construct crash, moreover user himself is unable to delete such buggy animation because we cant even click it, it causes instant crash. Thank you.
