### ISSUE TITLE
Animations Editor: After delete animation frame, does not focus on the next frame

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7737]
## Problem description

Currently, after selecting a frame and delete, the dialog box will lose focus. If want to delete Frame continuously, it will be very inconvenient.

## Attach a .c3p

[issue-delete-frame.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13917006/issue-delete-frame.c3p.zip)

## Steps to reproduce
1. select a frame, and delete
2. Observe that the cursor is not in the Frame 

## Observed result

1. Select a frame
![01](https://github.com/Scirra/Construct-bugs/assets/45864744/b874a94a-a705-47bc-9b09-554cf8ad2a2a)

2. delete
![02](https://github.com/Scirra/Construct-bugs/assets/45864744/be5f906c-34c0-4b33-b3c3-c2920e4bb456)

## Expected result

Plan A:
focus next frame
![03](https://github.com/Scirra/Construct-bugs/assets/45864744/b041f530-6089-41b8-8fb3-287f6a14602b)

Plan B:
In order to take into account the habits of different users, shortcut keys can also be supported for continuous deletion. For example, hold down `Shift + Delete` to delete continuously?

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This works properly in Chrome and Firefox, both in the browser and installed as an app. How are you deleting frames?

**Comment by XHXIAIEIN** [comment]
I just press `Del` key.

<details><summary>View details</summary>

Platform information
Product: Construct 3 r374 (beta)
Browser: Chrome 120.0.6099.217
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 477 gb
Storage usage (approx): 224 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by WilsonPercival** [comment]
@DiegoScirra This only works well the first time you launch the animation editor. Subsequent times it stops working.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
