### ISSUE TITLE
CodeMirror displays font poorly in other languages environments

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7740]
## Problem description

This may be related to the chrome default font. My browser and system display language are Chinese. The default font is other.

![Snipaste_2024-01-13_12-40-43](https://github.com/Scirra/Construct-bugs/assets/45864744/f00df4cc-0650-4038-b9c5-c4240b8c03eb)

## Observed result

javascript

![Snipaste_2024-01-13_13-38-17](https://github.com/Scirra/Construct-bugs/assets/45864744/40874c3f-c148-48ee-b163-572ec1e5a7cf)

![Snipaste_2024-01-13_13-36-56](https://github.com/Scirra/Construct-bugs/assets/45864744/27bc4027-8e7c-473c-b28e-9757f3330c0c)

json
![Snipaste_2024-01-13_13-43-51](https://github.com/Scirra/Construct-bugs/assets/45864744/1d8a599f-371c-4be3-bf05-aea256e2bf3d)

![Snipaste_2024-01-13_13-44-03](https://github.com/Scirra/Construct-bugs/assets/45864744/9bd83568-9d74-49ff-869c-764921368367)

## Expected result

If I set Chrome default language to English, this is normal

![Snipaste_2024-01-13_16-59-59](https://github.com/Scirra/Construct-bugs/assets/45864744/f1e44c6d-b1a9-40dc-a08f-97e2d45816e7)

![Snipaste_2024-01-13_16-53-51](https://github.com/Scirra/Construct-bugs/assets/45864744/78133255-75c2-4c7e-980c-99094465e5d3)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r374 (beta)
Browser: Chrome 120.0.6099.217
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 477 gb
Storage usage (approx): 219 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by fredriksthlm** [comment]
@XHXIAIEIN  CodeMirror uses  _font-family: monospace_ so actually your "chinese" font is a valid one. Even if that one was quite odd.. All code editors use different monospace fonts.
(Your "english" font is def  **not** the expected/normal one, since that is not a monospace font at all)

`.CodeMirror {
    font-family: monospace;
    height: 300px;
    color: #000;
    direction: ltr;
}`

**Comment by AshleyScirra** [comment]
CodeMirror does indeed set `font-family: monospace` and so it uses whatever the browser has set for a monospace font. If you don't like it you can normally change it in browser settings. For example in Chrome I can go to Settings - Appearance - Customize fonts, and changing "Fixed-width font" changes the font used by Construct's code editor.
