### ISSUE TITLE
When I run a project the display is completely garbled

### ISSUE THREAD

**Issue by kgish** [Scirra/Construct-bugs#7742]
## Problem description

When I try and run a new project by selecting preview project, the project starts but the display is messed up, see attached screenshot.

This is the case not only for my own projects, but also occurs for any of the demo projects I attempt to run.

I might also mention that all of the other games that I have installed on the same machine run perfectly without any issues.

Also, the games I create using other game engines, like Defold, or plain-vanilla work fine.

This seems at first glance to be a problem specific to Construct3, but I might be wrong.

## Attach a .c3p

[project.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13931570/project.c3p.zip)

## Steps to reproduce

1. Create a new project
2. Run preview project
3. Observe the display output

## Observed result

The display is corrupted:

![screenshot](https://github.com/Scirra/Construct-bugs/assets/79195/217e152a-a4bd-4035-8079-131ef58a0fc5)

## Expected result

The display should work properly.

## More details

[system-details-report.txt](https://github.com/Scirra/Construct-bugs/files/13931592/system-details-report.txt)

[lshw --c-video.txt](https://github.com/Scirra/Construct-bugs/files/13931596/lshw.--c-video.txt)

![devtools-console](https://github.com/Scirra/Construct-bugs/assets/79195/4f0cf86c-d1f6-4055-9ba6-ec6e56573ca9)

**Affected browsers/platforms:** 

Chrome: Version 120.0.6099.109 (Official Build) (64-bit)

**First affected release:** 
Don't know

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 120.0.6099.109
Browser engine: Chromium
Context: webapp
Operating system: Linux 6.5.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 549 gb
Storage usage (approx): 35 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, Vulkan 1.3.255 (AMD Radeon RX 6700 XT (RADV NAVI22) (0x000073DF)), radv)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by kgish** [comment]
Well, I'm not using nvidia and it's a linux system.What baffles me is that all my other games are working fine with the same graphics driver, so it seems that there is something specific to construct3 in combination with amdgpu which is the cause of the problem.On Jan 15, 2024 17:04, "Ashley (Scirra)" ***@***.***> wrote:
I can't reproduce that with my Windows system with an NVIDIA GeForce GTX 1070. The screenshot you provided looks a lot like corruption caused by a graphics driver bug, especially since the console is logging OpenGL errors, and especially because it looks like you're on a Linux system which are particularly prone to graphics driver bugs.
So I'm afraid it looks like a system driver problem rather than a problem with Construct. You could try reporting it to Google at crbug.com in case they can work around it, or perhaps tweaking settings or updating/changing graphics drivers may help.

**Comment by AshleyScirra** [comment]
This is always difficult, I have to explain this over and over again over the years: no, just because it happens in Construct does not mean it's Construct's fault. Graphics driver bugs can occur randomly, only happen on Thursdays, only happen on a full moon, or only affect one piece of software and not others. I've seen many complicated graphics driver bugs in 15+ years of working in software development. Let me be clearer: this is **categorically a graphics driver bug with your system and not a problem with Construct**. Asking us to fix it will achieve nothing, as it's not our software that's broken. Some people don't understand this and keep insisting we fix it anyway, when it's impossible for us to do so. Please don't be that person.
