### ISSUE TITLE
"Failed to start preview. Try reloading Construct before trying again."

### ISSUE THREAD

**Issue by epic20** [Scirra/Construct-bugs#7744]
## Problem description

I was working on my game perfectly fine but then it says "Failed to start preview. Try reloading Construct before trying again."
I tried reloading or even restart my pc but didn't work, It's fine for other projects but not this. I think it's something about spritesheets I don't know

## Attach a .c3p

[Project.zip](https://github.com/Scirra/Construct-bugs/files/13944224/Project.zip)

**Comment by WilsonPercival** [comment]
I can't open your project. Please remove any third party addons according to reporting guidelines.

<img width="396" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/62ad6273-3c22-4ebf-b763-26f4d29db0a5">

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help you.

**Comment by epic20** [comment]
> Please follow the bug report guidelines otherwise it's impossible for us to help you.
Hi, Sorry about that. I removed any third party addons so here's the updated one:

[Project.zip](https://github.com/Scirra/Construct-bugs/files/13961974/Project.zip)

**Comment by epic20** [comment]
> > > Please follow the bug report guidelines otherwise it's impossible for us to help you.
> > 
> > 
> > Hi, Sorry about that. I removed any third party addons so here's the updated one:
> > [Project.zip](https://github.com/Scirra/Construct-bugs/files/13961974/Project.zip)
> 
> @epic20 I noticed that one of the frames in animations "2" and "6" were corrupted, which was causing the project to start having problems. I removed these animations from the project and now everything works fine.
> 
> Can you tell me how exactly you added this animation to the project? Also, what extension did the image files have?
> 
> [ONAH2.zip](https://github.com/Scirra/Construct-bugs/files/13962254/ONAH2.zip)

I selected each images from the files and drop them in at once for the animations
