### ISSUE TITLE
Player Stuck or Freeze on jump through object randomely

### ISSUE THREAD

**Issue by worldruller** [Scirra/Construct-bugs#7745]
## Steps to reproduce

=>add object
=>add platform behaviour
=>add jump through object
=>add event of if player is on floor then simulate control jump

1.
2.
3.

## Observed result

some time player stuck or freeze on that object

## Expected result

player should be jumped of from the object

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Can you attach a project file that reproduces the problem?

**Comment by worldruller** [comment]
> Can you attach a project file that reproduces the problem?

that's my client project, he doesn't want to share the project on forum. its just simple game of player jump on object and go higher and higher (object is tile and they have move through behaviour).

**Comment by WilsonPercival** [comment]
> > Can you attach a project file that reproduces the problem?
> 
> that's my client project, he doesn't want to share the project on forum. its just simple game of player jump on object and go higher and higher (object is tile and they have move through behaviour).

I don't need your whole project. You can remove everything from it except what is causing the problem. Otherwise it will be impossible to help.

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help you.

**Comment by worldruller** [comment]
[Uploading JumpGitProj.zip…]()
here is the file sorry for late replay, pls help me
