### ISSUE TITLE
Crash when pasting actions that modify constants

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7746]
## Problem description

(This seems like something that should likely be disallowed, versus an outright crash?)

When pasting an action that modifies a constant string variable with the same name, Construct crashes.

## Attach a .c3p

https://drive.google.com/file/d/1S-5q1RGIbgbHSnEwbqws4vXwEoEsAB4n/view?usp=sharing

## Steps to reproduce

1. Copy the action In Group 2's event
2. Paste it onto the event in Group 1

## Observed result

Construct crashes (crash report below)

## Expected result

A warning that the action is invalid/couldn't be pasted

## More details

**Affected browsers/platforms:** Chrome 120.0.6099.216, MacOS Ventura 13.5.2

**First affected release:** r375, but this crash occurs in r269 as well

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: cannot select detached view
Stack: Error at pa.N4a (https://editor.construct.net/r375/main.js:1121:314) at window.assert (https://editor.construct.net/r375/main.js:1036:353) at d.Mp (https://editor.construct.net/r375/components/editors/eventSheetView/eventSheetView.js:178:278) at d.X3b (https://editor.construct.net/r375/components/editors/eventSheetView/eventSheetView.js:177:256) at https://editor.construct.net/r375/components/editors/eventSheetView/eventSheetView.js:236:472 at async window.Qob.ld (https://editor.construct.net/r375/main.js:2984:436)
Construct version: r375
URL: https://editor.construct.net/r375/
Date: Wed Jan 17 2024 08:08:28 GMT-0500 (Eastern Standard Time)
Uptime: 161.4 s

Platform information
Product: Construct 3 r375 (beta)
Browser: Chrome 120.0.6099.216
Browser engine: Chromium
Context: browser
Operating system: macOS 13.5.2
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) Iris(TM) Plus Graphics 655, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_provoking_vertex
</details>

**Comment by AshleyScirra** [comment]
Thanks, good catch. Fixed for the next beta (it will show an error instead of crashing).

**Comment by brushfe** [comment]
Thanks very much!
