### ISSUE TITLE
Duplicating animations

### ISSUE THREAD

**Issue by NukeThemAllGame** [Scirra/Construct-bugs#7747]
In animation editor when duplicating animation, the duplicate is created with a name "Animation 1" instead of "name_of_original_animation_2" like in cloning objects. For consistency - suggestion to use the same ideology when creating clone of animation

Not needed

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines, or if you wish to make a suggestion, file it on the feature requests tracker instead.
