### ISSUE TITLE
Project generates with Empty Podfile and dependency issues when using the export option "Hide Status bar"

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7750]
## Problem description

Pretty much same thing as in #7686 #7400 (partly #6934), but I've now discovered why you guys were unable to replicate this issue while it was happening in every project for me. It's the build option "hide status bar" in the export menu. Checking this will install the cordova plugin statusbar, which causes an empty podfile to generate which leads to dependency issues in xcode. 

I haven't confirmed this yet, but as the vibrate option also adds a cordova plugin (the same way), it is very likely that this causes the same issue as well.

## Attach a .c3p

There is a c3p in #7686, but it works with every project

## Steps to reproduce

1. Create project and fill in the details required to export
2. Check the option "hide status bar"
3. Export

## Observed result
A podfile is being generated and there are dependencies in the pods-release.xccofing and debug file. 

## Expected result

These files should not generate because afaik Cordova-plugin-statusbar does not require the use of pods.

## More details
Using Chromium.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by fredriksthlm** [comment]
When you set _Hide status bar_ then Construct includes the plugin **cordova-plugin-statusbar** and official Cordova plugins creates a podfile when used. When you use this setting in Construct the app is actually still opened with the statusbar present, and via code (via this plugin) the statusbar is hidden _after_ launch programatically.

This is though never a good approach in hiding the statusbar and should not really be used (the plugin should only be used if you need to trigger the statusbar off/on during runtime).
If you do not want the statusbar at all you should state that in the p-list for ios apps and in the theme for Android apps.

The below keys removes the statusbar for iOS apps and fixes your issue.

`<key>UIStatusBarHidden</key>
<true/>
<key>UIViewControllerBasedStatusBarAppearance</key>
<false/>`

**Comment by therealPaulPlay** [comment]
Thank you, that’s a neat solution that I‘ll definitely give a try! 
However, as the official mobile ads plugin (for example) also creates a podfile and actually installs the pods, I think setting this checkbox should lead to the pods getting installed too, otherwise people have to do that manually which can be a hurdle for some as it doesn’t tell you that you need to do that when choosing said option. Maybe it would be more clever to just swap out the plugin for your solution in the build service, if that works.

**Comment by AshleyScirra** [comment]
The problem is this issue in Cordova that causes it to generate an empty podfile: https://github.com/apache/cordova-ios/issues/1365

Cordova need to fix this, I don't think there's any good workaround for Construct. Meanwhile AFAIK if you have an empty podfile, you can ignore it (don't run `pod install`); if it's not empty then `pod install` should work correctly.

**Comment by therealPaulPlay** [comment]
> The problem is this issue in Cordova that causes it to generate an empty podfile: [apache/cordova-ios#1365](https://github.com/apache/cordova-ios/issues/1365)
> 
> Cordova need to fix this, I don't think there's any good workaround for Construct. Meanwhile AFAIK if you have an empty podfile, you can ignore it (don't run `pod install`); if it's not empty then `pod install` should work correctly.

Unfortunately, you can't ignore it as it also generates the dependencies to the support files in the 2 other xccodeconfig files. Therefore, I still need to run pod install to generate these support files, even if the podfile is empty. I hope Cordova will fix this :)
