### ISSUE TITLE
GamepadIndex returns inconsistent results

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7751]
## Problem description

When referencing Gamepad.GamepadIndex, Construct knows the value of it in an event's conditions, but not actions.

## Attach a .c3p

https://drive.google.com/file/d/1gVGNcZ0YyJJ3DbaXXJfJBVSfasmmS59s/view?usp=sharing

## Steps to reproduce

1. Connect a gamepad. 
2. Run the project.
3. Press the A button (X on PS controller).

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/63005234/254aad2f-f9e0-4de7-b714-5a5440e03050)

![image](https://github.com/Scirra/Construct-bugs/assets/63005234/05d30419-0da5-43a5-b7e9-bb8a534c3b7f)

Both conditions trigger when the A button is pressed on Gamepad #0, because the index 0 is recognized by both conditions. 

However, only the second action can recognize the index 0. For some reason, the first returns -1, despite the Gamepad Index of 0 being known and required for this event to run.

## Expected result

Both actions should have GamepadIndex set to 0 (or whatever the correct gamepadIndex is for the gamepad it recognizes).

## More details
As someone pointed out when I asked around the forum, the manual mentions that gamepadIndex is only meant to be used in certain conditions. But this seems like a bug—the index is known in the condition when picking, but lost in the action. I'd imagine losing that index information wouldn't be intentional. If it is, maybe this is a feature request?

**Affected browsers/platforms:** Chrome 120, Mac 13.4

**First affected release:** Broken in r375, and as far back as r350. Interestingly, only the first event fires in 269.

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. As the [manual](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/gamepad) states:

> In an On gamepad connected/disconnected trigger, or when using On any button pressed/released with a gamepad of -1, this expression indicates the index of the corresponding gamepad.

The expression was designed for those specific features only, as those are the only features where it provides any meaningful information, and it is set to -1 the rest of the time.

**Comment by brushfe** [comment]
@AshleyScirra Thanks for the reply! 

I didn't expect it was by design—this is one of the few (only?) times where identifying information is lost between condition and action. The gamepad index is like its UID/IID, which all other objects retain during picking. 

Anyway! It feels like it would count as meaningful information at all times, so i'll take my chances with a feature request.
