### ISSUE TITLE
MoveTo: After Stop on solids, can not move again

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7752]
## Problem description

Confused about the 'Stop on solids' behavior of MoveTo as it completely stops working after the collision. And cannot move again.

In my opinion, it should only trigger once during the move. It will not stop again unless it collides with the entity the next time it moves. Instead of always being disabled (even if they remain in collision on the next click, the engine should handle it automatically to ensure it works).

## Attach a .c3p

[MoveTo-StopOnSolids.c3p.zip](https://github.com/Scirra/Construct-bugs/files/13972638/MoveTo-StopOnSolids.c3p.zip)

## Steps to reproduce
1. Enable 'Stop on solids' 
2. Moves toward to Solid object, Stop after when collision
3. After stopping, click anywhere behind again

## Observed result

![Snipaste_2024-01-18_14-01-46](https://github.com/Scirra/Construct-bugs/assets/45864744/b1063431-c4fc-4be2-a903-b9e9ff8f344c)

## Expected result

Can be moved again

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The problem with this project setup is the 'Move to' behavior will stop, but the next time it is trying to move it will try to carry on at the same angle (i.e. still moving forwards) while rotating towards the new position. Further as 'Set angle' is enabled the rotation of the Sprite may also cause it to collide with the solid immediately again. It can move again if you turn off 'Set angle' and set the rotate speed to 0 for instant turns, as that avoids it still trying to run in to the solid.
