### ISSUE TITLE
Go To Layout event after Collision action

### ISSUE THREAD

**Issue by TomChurchyard** [Scirra/Construct-bugs#7757]
## Problem description

Text cannot be set after in a layout if the event to set that text is a collision between sprites. 

## Attach a .c3p

[ConstructBug.zip](https://github.com/Scirra/Construct-bugs/files/13990545/ConstructBug.zip)

Working solution included below:
[WorkingSolution.zip](https://github.com/Scirra/Construct-bugs/files/13990736/WorkingSolution.zip)
Altering the event to be a system comparison check rather than collision is a workaround for the issue.

## Steps to reproduce

1.  Go to layout based on collision
2. Set text based on same collision
3. Text should update

## Observed result

Text does not update as expected. Retains default value.

## Expected result

Text to update to new value.

## More details

**Affected browsers/platforms:** 
Only tested on Chrome.

**First affected release:** 
Worked in previous releases.
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TomChurchyard** [comment]
Both layouts share an event sheet. This function does work if the layout is changed based on a system variable comparison, just not with sprite collisions.

**Comment by WilsonPercival** [comment]
> Both layouts share an event sheet. This function does work if the layout is changed based on a system variable comparison, just not with sprite collisions.

@TomChurchyard `WorkingSolution.zip` works because after you switched to the second layout the event was executed.

**Comment by TomChurchyard** [comment]
> > Both layouts share an event sheet. This function does work if the layout is changed based on a system variable comparison, just not with sprite collisions.
> 
> @TomChurchyard `WorkingSolution.zip` works because after you switched to the second layout the event was executed.

Switching to the second layout happens within the same event as setting the text with the same order. The event order does not matter in this specific example anyway. The only difference between the two examples is that one of the events is a sprite collision and the other is a system variable comparison.

**Comment by WilsonPercival** [comment]
> > > Both layouts share an event sheet. This function does work if the layout is changed based on a system variable comparison, just not with sprite collisions.
> > 
> > 
> > @TomChurchyard `WorkingSolution.zip` works because after you switched to the second layout the event was executed.
> 
> Switching to the second layout happens within the same event as setting the text with the same order. The event order does not matter in this specific example anyway. The only difference between the two examples is that one of the events is a sprite collision and the other is a system variable comparison.

@TomChurchyard In `ConstructBug.zip` the text setting action happens on the first layout. There is no instance of text on the layout, so this action doesn't work.

In `WorkingSolution.zip` the action of setting the text happens on the second layout. There is an instance of text on the second layout, so the action fires.
