### ISSUE TITLE
iOS: Gamepads are not working (not being recognized)

### ISSUE THREAD

**Issue by therealPaulPlay** [Scirra/Construct-bugs#7765]
## Problem description

Gamepads do not seem to be working in iOS. I've tested it with and without the game controller component in Xcode and it doesn't seem to be working for me. According to apple, this is one of the capabilities that do not require a developer license and I was only able to test it without one - maybe that is the issue (but I don't think so, as afaik the capability is not needed for controller support inside of the webview). 

## Attach a .c3p

[gamepad test.zip](https://github.com/Scirra/Construct-bugs/files/14014747/gamepad.test.zip)

## Steps to reproduce

1. Add the gamepad object to a project
2. Add an action to indicate that it is working
3. Fill in the project details and test it on iOS

## Observed result
The controller does not seem to be recognized. 

## Expected result
The controller should work like it does on PC or android. 

## More details
Only iOS is affected. 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Does this affect Safari with web exports, or iOS app exports, or both?

Usually such issues are out of our control, as Construct just reports the gamepad input provided by the browser. It's up to the browser, system, driver availability, and the specific gamepad tested, which all combine to determine whether a specific gamepad will work.

**Comment by therealPaulPlay** [comment]
Okay, well it affects web exports too. I've also noticed that other browser games and applications can't pick up gamepad inputs in safari on my iPhone too so I'm pretty sure there is no way to work around that unless apple allows it

**Comment by AshleyScirra** [comment]
What gamepad are you testing with exactly, and how are you connecting it (i.e. cable or wireless)?

For example I have an old Xbox One wireless controller (model 1537). However [this Apple guide](https://support.apple.com/en-gb/111101) does not list it as a supported device, so I wouldn't expect it to work. I could order something in to the office to test, but it would be good to know what you're using and whether it's listed as a supported device, and while I can give it a spin and see if it works or not, there may not be anything we can do about it - Construct doesn't decide if gamepads are supported, it just uses the browser's Gamepad API and the browser/OS determines whether the gamepad is supported.

**Comment by therealPaulPlay** [comment]
I‘m using the Xbox Series X/S wireless controller and have tested it prior with the PS4 Controller as well

**Comment by AshleyScirra** [comment]
No, Safari supports the same standard Gamepad API that Chrome does. That documentation link appears to be their own documentation for the standard Gamepad API (although not very useful documentation).

Does the gamepad work if you test it in Safari with a generic tester website like https://hardwaretester.com/gamepad ?

**Comment by therealPaulPlay** [comment]
Oh okay I read somewhere that they are using their own thing but apparently that was incorrect. Yes, this website works (with the controller connected wirelessly).

**Comment by AshleyScirra** [comment]
OK, so just to be clear, that website correctly detects gamepad input but Construct doesn't?

**Comment by AshleyScirra** [comment]
So I managed to get an old PlayStation 4 wireless controller to pair with an iPhone 12 Pro Max. It seems the Gamepad API works fine in the Safari browser, but is broken in WKWebView. So it's a bug in iOS and Apple will need to fix it. I filed it with them here: https://bugs.webkit.org/show_bug.cgi?id=269292

Closing this issue as it will be followed up there.

**Comment by therealPaulPlay** [comment]
Perfect, thank you! Good to hear that it at least _should_ be working and isn’t just unsupported. I hope they‘ll fix it :)

**Comment by AshleyScirra** [comment]
Does anyone know if this ever worked? It might be useful for Apple to know if it worked on a previous version of iOS and stopped working with a more recent release.

**Comment by JohnMcW** [comment]
I briefly tested this a few months ago but can't exactly remember when - maybe November 2023?  But it definitely worked - I was using a Nintendo Switch JoyCon and an iPad - no idea what iOS version was on it.  I generally update promptly though.  I see that iOS 17's release date was 18/9/23.

**Comment by AshleyScirra** [comment]
Just an update on this issue: in the end this turned out to be a bug in WebKit (the Safari browser engine) which now appears to be fixed in iOS 18. So gamepads should be working correctly again in iOS apps on iOS 18+.
