### ISSUE TITLE
Picking sprites using string instance variables is not working for OR blocks

### ISSUE THREAD

**Issue by vascco47** [Scirra/Construct-bugs#7766]
## Problem description

Not sure if this is a bug or by design.
Attached is a file with two cases of picking objects by comparing instance variables within OR blocks.
The code is the same for both cases. In the first case, numeric variables were used and objects are picked there, and in the second case, string variables were used, where picking objects does not work.

## Attach a .c3p

[ORtest.zip](https://github.com/Scirra/Construct-bugs/files/14022502/ORtest.zip)

## Steps to reproduce

1.Open file and run;
2.On the left are objects that are taken via numeric variables (color change every tick), while on the right are objects for which the same action is attempted via string variables.
3.

## Observed result

The objects on the right do not respond.

## Expected result

The objects on the right should change colors like the ones on the left, unless I misunderstood something.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
This is a bug in your project. You wrote a string with double quotes when expected without quotes.

<img width="152" alt="obser" src="https://github.com/Scirra/Construct-bugs/assets/91274932/15c4aa8c-44e9-4ead-bad4-1dc8fca6f023">

**Comment by AshleyScirra** [comment]
This is a mistake in your project. Instance variables in the properties bar do not need quotes around the initial string (they are not expressions). If you add them then the string content is actually `"a"` and not `a`, and the events check if they are `a` as the double quotes are part of including a string literal in an expression.
