### ISSUE TITLE
Tween Behavior scale property doesn't work on Sprite font

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-bugs#7767]
## Steps to reproduce

1. Open the example file.
2. Click the Left Mouse button to modify the scale of the sprite font with tween behavior.
3. Click the Right Mouse button to modify the scale of the sprite font with "set scale"  and "wait" action.

## Observed result

2. Tween behavior doesn't work.
3. Set scale works.

## Expected result

2. Tween behavior should work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is admittedly confusing, but it's not a bug.

For tweens, changing the scale is a shortcut for changing the width and height of the object. In the layout view try resizing the Spritefont object. You can see the text size does not change, only its surrounding box. That is what the tween scale is doing.

For SpriteFont's 'Set scale' action, it is changing the 'Scale' property of the SpriteFont object, which is what size to draw the text at. In the layout view try changing the 'Scale' property of the Spritefont object. You can see that the text size is changing. That is what the 'Set scale' action is doing.

You can tween other properties like Spritefont's drawing scale by using a value tween and using the 'Set scale' action to set the scale to the current value of the tween while it is running.
