### ISSUE TITLE
HTML elements layer effect invisible bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7768]
## Problem description

When I start the game, the sprite is not visible.

## Attach a .c3p

[html_elements_layer_effect_invisible_bug_r376b.zip](https://github.com/WilsonPercival/WilsonPercival/files/14025819/html_elements_layer_effect_invisible_bug_r376b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

<img width="698" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/068b1bcd-7b90-46ec-b4e2-93392d787ef3">

## Expected result

<img width="601" alt="expected" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/52fae84f-aa52-40c5-8c6f-5b1ee48ae5bc">

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** It's hard to say because in previous versions you see a black square instead of a sprite. Still doesn't work in `r376b`.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r376 (beta)
Browser: Chrome 120.0.6099.225
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 727 mb (0.3%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
This is actually the correct rendering result. Due to the way compositing works with HTML layers, all the content above the HTML layer is rendered to a transparent surface, and then the result copied to the display - much like a "force own texture" layer. A background-blending effect rendering to a completely transparent surface will usually not render anything as the output is fully transparent too. You can see the sprite disappear for the same reason if you make its layer 'Force own texture'. The only reason it displays in the editor is that the editor does not implement HTML layers and so previews it as if there are no HTML layers.
