### ISSUE TITLE
3D First Person Template Exports with Transparent Layers, 3D Objects "Break"

### ISSUE THREAD

**Issue by AppDude27** [Scirra/Construct-bugs#7769]
## Problem description

I am using a copy of the first person shooter example browser project. When I launch the project with remote preview, the environment looks fine. But when I export it with any of the Windows export options, the 3D environment becomes messy. The objects are transparent and I can see through them. Any additional 3D layers don't work either. 

Update 1/23/2024 12:09 PM CST
When I right click on my project and I go to Properties -> Compatibility, I've tried running the project with Compatibility settings set to "Windows Vista" and my 3D layouts worked. I then tried the rest of them compatibility options and these are my results:
My operating system: Windows 11 Home
Windows Vista - 3D layouts working
Windows Vista Service Pack 1 - 3D layouts working
Windows Vista Service Pack 2 - 3D layouts working
Windows 7 - Broken
Windows 8 - Broken
I'm glad that this is helping me, but I'm not sure how I can use this information to help me solve the problem without running a compatibility mode.

![image](https://github.com/Scirra/Construct-bugs/assets/9124095/32d9bbf9-da1b-45bd-88d1-c6981c1584e7)

## Attach a .c3p

[New project.zip](https://github.com/Scirra/Construct-bugs/files/14027016/New.project.zip)
[New Project Dev.zip](https://github.com/Scirra/Construct-bugs/files/14027107/New.Project.Dev.zip)

## Steps to reproduce

1. Open the attached project
2. Run the project in the preview to see that it works fine.
3. Export the project using NW.js or Windows Webview2 (both are faulty)
4. Open the exe file for the project
5. Notice the issue.

## Observed result
Layers are transparent, objects are not the same as preview.

## Expected result
The preview and export should be the same.

The layers are all messy, transparent, and the objects are visible even if they are behind 3D walls.

## More details

This problem isn't just happening to the example project, it's also happening to my personal indie game project as well. I figured that I could attach this example and then apply the solution to my personal game.

I tested this in Edge and Chrome. The latest versions. Both have issues. I also tested this on my ROG Ally (Windows 11) and still have issues.

**Affected browsers/platforms:** 

**First affected release:** 
N/A 

## System details

<details><summary>View details</summary>

Windows 11
Processor	11th Gen Intel(R) Core(TM) i7-11700F @ 2.50GHz   2.50 GHz
Installed RAM	16.0 GB (15.9 GB usable)
Product ID	00342-20768-98321-AAOEM
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

</details>

**Comment by AppDude27** [comment]
[New Project Dev.zip](https://github.com/Scirra/Construct-bugs/files/14027100/New.Project.Dev.zip)

I attached the exported project as an example. The attachment here is the actual c3p file. Thanks

**Comment by WilsonPercival** [comment]
Can not reproduce.

**Comment by AppDude27** [comment]
When I right click on my project and I go to Properties -> Compatibility, I've tried running the project with Compatibility settings set to "Windows Vista" and my 3D layouts worked. I then tried the rest of them compatibility options and these are my results:
1. Windows Vista - 3D layouts working
2. Windows Vista Service Pack 1 - 3D layouts working
3. Windows Vista Service Pack 2 - 3D layouts working
4. Windows 7 - Broken
5. Windows 8 - Broken

I'm glad that this is helping me, but I'm not sure how I can use this information to help me solve the problem without running a compatibility mode.

**Comment by fvcalderan** [comment]
I was able to reproduce the bug and can confirm that it works fine under Windows Vista compatibility, but not Windows 7 or 8. I am running Windows 11 23H2 22631.3007.
![image](https://github.com/Scirra/Construct-bugs/assets/24211835/82d20885-3b12-45ce-ae57-00352d000f9d)

**Comment by AshleyScirra** [comment]
It works fine for me - it looks fine after export, including the exported version you provided.

This looks a lot like a graphics driver bug. I'm afraid there is little we can do about that. By default WebView2 and NW.js exports have 'Ignore GPU blacklist' enabled which means it is more prone to graphics driver glitches. You can uncheck that and then drivers with known bugs will revert to software rendering, which should work reliably but is much slower. You could also try updating your drivers or installing any available system software updates.
