### ISSUE TITLE
project freeze at loading on iphone

### ISSUE THREAD

**Issue by FONGKA2** [Scirra/Construct-bugs#7784]
## Problem description
it's just freeze on loading screen before load in the event start of layout, but work fine on desktop, everything work last week

## Attach a .c3p
web export: https://logineus.today/121
c3p: https://logineus.today/121/E-Interface.c3p

## Steps to reproduce
just run on iphone

## Observed result
freeze, when entry eventsheet

## More details

**Affected browsers/platforms:** 
ios

**First affected release:** 
r367
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This project uses both a third-party addon and includes a large amount of its own logic, both of which could be the cause of the problem. Please see the bug report guidelines as it is not possible to investigate such projects.
