### ISSUE TITLE
Sprite animation name contain other languages,  after export can not open game

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7791]
## Problem description

If Sprite animation contains other languages characters, export the game at webview2, after play the loader page, it will enter a black screen.

![Snipaste_2024-01-29_23-42-49](https://github.com/Scirra/Construct-bugs/assets/45864744/e2bdb8dc-cacb-482e-8650-bdcb2763bbc6)

![Snipaste_2024-01-29_23-46-31](https://github.com/Scirra/Construct-bugs/assets/45864744/cf9d43fe-25a2-4eae-a14b-0899956b1f9d)

## Attach a .c3p

[issue-chinese-name.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14086432/issue-chinese-name.c3p.zip)

## More details

**First affected release**: work in Stable but broken on beta

_Originally posted by @XHXIAIEIN in https://github.com/Scirra/Construct-bugs/issues/7787#issuecomment-1914975503_

**Comment by AshleyScirra** [comment]
Thanks, good catch, there was a place in the WebView2 code it wasn't handling unicode properly. Should be fixed in the next beta.
