### ISSUE TITLE
import files dialog no support remove file

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7792]
## Attach a .c3p

import files dialog no support remove file

![Snipaste_2024-01-30_02-51-23](https://github.com/Scirra/Construct-bugs/assets/45864744/6afc8127-f404-420d-9965-3cf506059a3c)

Because I accidentally passed in an index.html. I want to delete it but can't. I have to close the dialog box and then enter it again

| | |
| ---- | ---- | 
| ![Snipaste_2024-01-30_02-48-11](https://github.com/Scirra/Construct-bugs/assets/45864744/7491f820-0931-40b9-85e2-15cd0e306fff) | ![Snipaste_2024-01-30_02-48-23](https://github.com/Scirra/Construct-bugs/assets/45864744/8380fbdc-0b57-4422-b6a7-ea768e4d6ee0) |

## Steps to reproduce
1. Import a file in the import files dialog
2. Select the file in the list, try press the Del key

## Observed result

Unable to remove file from list.

## Expected result

support 'del' key to remove

Note: For the non compliant files will not be added to the list.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a request for an enhancement so please post it to the suggestions tracker instead.
