### ISSUE TITLE
Animation Editor:  Save all animtions Images with data not contain frame tags data

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7793]
## Problem description

This may be an oversight. Because Frames Tag is a relatively new feature. When Save all animtions Images with data, it was not included.

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/efc54ebc-e317-4ae0-8f95-120f87e16bde)

## Attach a .c3p

[image.zip](https://github.com/Scirra/Construct-bugs/files/14088904/image.zip)

save from:
https://editor.construct.net/#open=text-icons-to-html

## Steps to reproduce

Load images zip file 
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/65324fad-6921-49af-a9b0-91821a85aa9c)

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/01ca575a-d72d-4c02-8705-1d4afbd89603)

## Expected result

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/6686e9f1-336d-4b06-a9b2-8817f5b97e31)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
@DiegoScirra This works if you click `Load animations`, but does not work if you click `Load frames` or drag the archive into the animation editor.

**Comment by DiegoScirra** [comment]
In that case it has always worked like this.

The options to specifically  load frames treat the bulk import files a little bit differently. Mainly all the images present in the file are added to the current animation. If there are multiple animations in the bulk file, all the images are added to the current animation as a flat list. All metadata is ignored, that includes collision polygons, frame tags, durations and image points.

I guess this could be implemented, but it's not a priority.

**Comment by XHXIAIEIN** [comment]
I think this should submit a suggestion, so close it
