### ISSUE TITLE
The log10 command does not calculate the logarithm correctly for some values.

### ISSUE THREAD

**Issue by tvister091** [Scirra/Construct-bugs#7794]
## Problem description

The log10 command does not calculate the logarithm correctly for some values. Tested on values of 1,000,000 and 1,000,000,000. In the first case, it gives the answer 5.999999999999999 (should be 6) . In the second case, 8.999999999999998 (should be 9).

## Attach a .c3p

[log10()-test.zip](https://github.com/Scirra/Construct-bugs/files/14098381/log10.-test.zip)

## Steps to reproduce

1. Launch the game in Debugger mode
2. View global values log_1_000_000 and log_1_000_000_000

## Observed result

log10(1000000) = 5.999999999999999
log10(1000000000) = 8.999999999999998

## Expected result

log10(1000000) = 6
log10(1000000000) = 9

## More details

The problem occurs in the Windows and Google Chrome versions.
Affected release: r368.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 121.0.6167.85
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: ru-RU

Local storage
Storage quota (approx): 167 гб
Storage usage (approx): 30 мб (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4000 (0x00000166) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Previously Construct calculated `Math.log(x) / Math.LN10`, but it looks like `Math.log10(x)` has better precision. As we are close to a stable release and minimizing non-critical changes this is done for the next release cycle (it will be in the first beta after the next stable release).
