### ISSUE TITLE
Cannot import tagged FLAC files

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#7797]
## Problem description

If you try to import a tagged FLAC audio file (which contains metadata such as track name, artist name, etc.) into the Import Audio dialog, Construct will fail to encode it. Encoding works fine if the FLAC file has no metadata.

## Steps to reproduce

1. Download [test audio files](https://drive.google.com/drive/folders/17lQ9VpYH1YiVb0JQUvfPLia6Gjo84pjI)
2. Create a new project or open any existing one
3. Right-click either **Sounds/Music** folder and select _Import sounds/music_
4. Try to import the file **"Wizard Dance.flac"**

## Observed result

Audio file encoding failed.

## Expected result

Audio file encoding was successful. The encoded audio file does not have metadata of the original file.

## More details

If you try to import that same FLAC file again (e.g. by closing the Import Audio dialog and reopening it), the encoding will be placed in the **"Queued"** state and will never be completed. You can try importing other versions of the same file (FLAC untagged, MP3 untagged and MP3 tagged) and they will all be encoded successfully.

**Affected releases:** r368.2 (current stable) & r377 (current beta)

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r377 (beta)
Browser: Edge 120.0.2210.133
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 58 gb
Storage usage (approx): 37 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4000 (0x00000166) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
This is weird because we use a WebAssembly build of FFmpeg for audio conversion, and it seems it doesn't understand tagged FLAC files. I guess it's some bug in FFmpeg. However when the browser supports FLAC we can use that to decode the file first which works around the problem. I've done that for the next release cycle (first beta release after the next stable release, as we are close to a stable release and trying to minimise changes).
