### ISSUE TITLE
Editor Fade Behavior Event Sheet Issue

### ISSUE THREAD

**Issue by LupMotion** [Scirra/Construct-bugs#7798]
In the proccess of making an text fade, when trying to enable or disable the behavior "Fade", the game doesn't show any options for that behavior (in the event sheet), only showing when to start, fade-out or fade-in. Thus, concluding it may be an "Bug" or issue, I made this report in belief of getting any info about it.

##attach a .c3p file
No .c3p file can be attached since it's an editor bug

## Steps to reproduce
1. Create an "Text" object 
3. Add an "Fade" behavior 
3. Open event sheet 
4. Add an event for when the layout starts 
5. Add an action for the text

1.
2.
4.

## Observed result
When seeing the Fade's behavior options, there will be only, start, restart, set fade-out time, set fade-in time and set wait time

## Expected result
When seeing the Fade's behavior options, there should be an Enable/Disable Behavior option

## More details
All details known have already been provided

**Affected browsers/platforms:** 
The only browser that has been affected so far is Chrome. More info will be needed from others.

**First affected release:** 
The issue was detected in r377 but there's no knowledge of other releases
## System details
As stated before, it's an editor issue. There isn't any point on pasting system info, but if needed, thus it'll be provided;
--

<details><summary>View details</summary>
PASTE HERE
</details>
--
there is no crash report dialog or file info since it's an editor issue.

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7254

**Comment by LupMotion** [comment]
@WilsonPercival i've readen that report, but I still don't know how to disable.

**Comment by AshleyScirra** [comment]
This sounds more of a feature request than a bug. However as the Fade behavior is a [superseded feature](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/superseded-features) we are unlikely to make any further changes to it. Use Tween instead.
