### ISSUE TITLE
EXTERNAL STORAGE PERMISSION NOT WORK COMPILATION

### ISSUE THREAD

**Issue by BoaIdeiaSistema** [Scirra/Construct-bugs#7799]
The external storage permission, even though checked during compilation, is not being added to the App.

I would like help, perhaps a way to write this permission into the manifest manually, or some update to the Construct 3 system

![image](https://github.com/Scirra/Construct-bugs/assets/157070990/332a1090-34f4-4fd0-8bc8-a703dd817bf0)

**Comment by AshleyScirra** [comment]
Construct does specify to use `WRITE_EXTERNAL_STORAGE` if you check that setting. However [as of Android 11 that setting is ignored](https://developer.android.com/about/versions/11/privacy/storage):

> If your app targets Android 11, both the `WRITE_EXTERNAL_STORAGE` permission and the `WRITE_MEDIA_STORAGE` privileged permission no longer provide any additional access.

So I think we will just remove the setting, as it no longer does anything useful.

**Comment by AshleyScirra** [comment]
Removed the option for the next release cycle.

**Comment by BoaIdeiaSistema** [comment]
What is the possibility of making this functionality work?

I think you will have to add the cordova.plugins.permissions npm dependency

I made the addon to request the permission, but it didn't work because this permission is not declared in the manifest.

Is there any way I can change the manifest in the construct 3 compiler?

**Comment by AshleyScirra** [comment]
As I said, the `WRITE_EXTERNAL_STORAGE` permission is no longer used by Android and so has no effect. I think that guide I linked to covers the alternatives.

**Comment by BoaIdeiaSistema** [comment]
Thank you for your attention !
