### ISSUE TITLE
Arithmetic operations of addition, subtraction, multiplication, and division with floating point numbers give incorrect results.

### ISSUE THREAD

**Issue by tvister091** [Scirra/Construct-bugs#7800]
## Problem description

Arithmetic operations of addition, subtraction, multiplication, and division with some floating point numbers give incorrect results. Seen when working with global and instance variables (Number and Text). In turn, no problems were found when working with the Text object.

This also relates to my previous topic about the log10() (https://github.com/Scirra/Construct-bugs/issues/7794): it calculates incorrectly precisely for global and instance variables.

## Attach a .c3p

An example of a project where the subtraction operation (1.1 - 0.2) is carried out:
[Arithmetic operations.zip](https://github.com/Scirra/Construct-bugs/files/14112736/Arithmetic.operations.zip)

## Steps to reproduce

1. Launch the game in Debugger mode
2. View global variable Global_Variable
3. View instance variable Instance_Variable

## Observed result

1.1 - 0.1 = 1
1.1 - 0.2 = 0.9000000000000001
1.1 - 0.3 = 0.8
1.1 - 0.4 = 0.7000000000000001
1.1 - 0.5 = 0.6000000000000001
1.1 - 0.6 = 0.5000000000000001
1.1 - 0.7 = 0.40000000000000013
1.1 - 0.8 = 0.30000000000000004
1.1 - 0.9 = 0.20000000000000007
1.1 - 1 = 0.10000000000000009

1 - 1.1 = -0.10000000000000009
1 - 0.9 = 0.09999999999999998
1 - 0.8 = 0.19999999999999996
1 - 0.7 = 0.30000000000000004
1 - 0.6 = 0.4
1 - 0.5 = 0.5
1 - 0.4 = 0.6
1 - 0.3 = 0.7
1 - 0.2 = 0.8
1 - 0.1 = 0.9

0.1 + 1.1 = 1.2000000000000002
0.1 + 1 = 1.1

1.1/10 = 0.11000000000000001
0.1/10 = 0.01

0.1 * 0.1 = 0.010000000000000002
0.1 * 0.2 = 0.020000000000000004
0.1 * 0.3 = 0.03

## Expected result

1.1 - 0.1 = 1
1.1 - 0.2 = 0.9
1.1 - 0.3 = 0.8
1.1 - 0.4 = 0.7
1.1 - 0.5 = 0.6
1.1 - 0.6 = 0.5
1.1 - 0.7 = 0.4
1.1 - 0.8 = 0.3
1.1 - 0.9 = 0.2
1.1 - 1 = 0.1

1 - 1.1 = -0.1
1 - 0.9 = 0.1
1 - 0.8 = 0.2
1 - 0.7 = 0.3
1 - 0.6 = 0.4
1 - 0.5 = 0.5
1 - 0.4 = 0.6
1 - 0.3 = 0.7
1 - 0.2 = 0.8
1 - 0.1 = 0.9

0.1 + 1.1 = 1.2
0.1 + 1 = 1.1

1.1/10 = 0.11
0.1/10 = 0.01

0.1 * 0.1 = 0.01
0.1 * 0.2 = 0.02
0.1 * 0.3 = 0.03

## More details

The problem occurs in the Windows and Google Chrome versions.
Affected release: r368.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 121.0.6167.85
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: ru-RU

Local storage
Storage quota (approx): 167 гб
Storage usage (approx): 29 мб (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4000 (0x00000166) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)

</details>

**Comment by F3der1co** [comment]
https://github.com/Scirra/Construct-bugs/issues/5463

**Comment by F3der1co** [comment]
the report says it calculates "correctly" in the text object, and I think this is just due to the automatic rounding discussed  in https://github.com/Scirra/Construct-bugs/issues/5463

**Comment by DiegoScirra** [comment]
The comment by Ashley in #5463 explains this pretty well.

**Comment by AshleyScirra** [comment]
The aptly-named website [0.30000000000000004.com](https://0.30000000000000004.com/) explains this. Computers can't do fractional calculations with perfect precision!

**Comment by tvister091** [comment]
Yes, I understand. However, the Text object calculates everything correctly (just like any calculator on the Internet), but global and instance variables do not. Because of this, it is impossible to work only with variables, since in my calculations numbers are always rounded to a lower value, and, for example, the expression 1 - 0.8 = 0.19999999999999996 will be rounded to 0.1. But I found a solution: you need to perform calculations in the Text object, then convert the string to a number using the float(Text.Text) command and assign this number to a global or instance variable.

**Comment by AshleyScirra** [comment]
As noted in #5463 the Text object applies a small amount of rounding, specifically for cases like this, so it tends to display a short number instead of a long number with a tiny floating point precision error. It is not that it is calculating everything correctly: it is that it calculates the same result, and then slightly rounds the result to a few decimal places.

The `str()` expression bypasses rounding, so if you set the text object's text to `str(1.1-0.2)`, you'll see you get exactly the same result.

**Comment by tvister091** [comment]
This is true. I just researched this issue. Thanks for the additional clarification. So, I will use the roundToDp command. :)
