### ISSUE TITLE
3d camera turns off when looking excatly top-down

### ISSUE THREAD

**Issue by Gryphonn** [Scirra/Construct-bugs#7801]
## Problem description

I'm moving the 3dCamera along the surfase of the imaginary sphere around the small cube.
The camera always looks at the center of the small cube (= center of the sphere).
But when I'm excatly above the center looking down the camera "turns" off. It doesn't see anything (you can judge that by the huge cube around the small one). Only the background of the 3d layer appears.

## Attach a .c3p

[3dcamera_2.zip](https://github.com/Scirra/Construct-bugs/files/14128227/3dcamera_2.zip)

## Steps to reproduce
1. Move the slider farthest to the right (or left)
2. When the angle is 90 (-90) the camera turns off. You only see the grey background.

## Observed result
https://github.com/Scirra/Construct-bugs/assets/21972383/16576cf6-b2f0-4480-ade8-6b2dca3c1667

## Expected result
https://github.com/Scirra/Construct-bugs/assets/21972383/85455e87-9d03-4267-9b3c-166d533b03ab

## More details
When I change a point the camera looks at a little bit off the center (even by 0.0001) everything is fine.
When I add an X or Y component to the UP vector (even by 0.0001) everything is fine.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a mistake in your project. The up vector is hard-coded to (0, 0, 1) regardless of the direction the camera is pointing in. When it points exactly down, it is then pointing in the reverse direction of the up vector, and therefore the up vector is invalid for determining the orientation of the camera, and so nothing can be rendered. You need to make sure you provide a valid up vector for all camera orientations.
