### ISSUE TITLE
Visible Sub-Layers are Considered Invisible Based on Parent Layers

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-bugs#7805]
## Problem description

Somewhat confusingly, the condition "is layer visible" returns _false_ on _visible_ sub-layers within invisible layers. This behavior isn't explicitly mentioned in the manual so it seems to be a potential oversight and not intentional. This issue means that one cannot accurately check if a sub-layer's individual "visible" property at all times independently of the state of its parent layer. This causes certain problems such as an inability to record the initial visibility state of a sub-layer at the start of a game so you can automatically reset it to that initial state when restarting the game (a workaround method for the fact that Restart Layout does not reset layer properties). You would also not be able to correctly determine ahead of time if a sprite on a sub-layer will be visible when its parent layer is toggled, as you can't check the sub-layer's visibility separately from the parent layer's. If one needed to determine the visibility state of the _parent_ layer, they could instead use a condition to check _its_ visibility instead of that of the sub-layer.

## Attach a .c3p

[SublayerVisibility.zip](https://github.com/Scirra/Construct-bugs/files/14144347/SublayerVisibility.zip)

## Steps to reproduce

1. Open the project.
2. Run the project, noting text displays connected to the state of each layer and sub-layer and their visibilities.
3. Note that as indicated, the _visible_ sub-layer within an invisible layer is considered by conditions to be invisible.

## Observed result

A visible sub-layer is still considered invisible in this case.

## Expected result

A sub-layer that is _set to visible_ will be confirmed as such by the condition "is layer visible", regardless of the visibility state of its parent layer.

## More details
If in fact this is the intended behavior, as sub-layers do inherit other things from parent layers, then I would ask for another, different condition or method for determining **the toggled state of a sub-layer's individual visibility separate from its parent** as there currently seems to be no other way to find that and solve some issues that arise from this.

**Affected browsers/platforms:** Firefox, Chrome.

**First affected release:** r377

## System details

Platform information

Product: Construct 3 r377 (beta)
Browser: Firefox 122.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.0) Gecko/20100101 Firefox/122.0
Language setting: en-US
Local storage

Storage quota (approx): 224 gb
Storage usage (approx): 1.1 gb (0.5%)
Persistant storage: Yes
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    The Clipboard API is not supported. Some clipboard features may be unavailable.
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 980 Direct3D11 vs_5_0 ps_5_0)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm;codecs=opus)
    WebM Vorbis (audio/webm;codecs=vorbis)
    MPEG-4 Opus (audio/mp4;codecs=opus)
    MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav;codecs=1)

Supported encode formats:

    WebM Opus (audio/webm;codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm;codecs=av01.0.00M.08)
    WebM VP9 (video/webm;codecs=vp9)
    WebM VP8 (video/webm;codecs=vp8)
    MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
    MPEG-4 VP9 (video/mp4;codecs=vp9)
    MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:

    WebM VP8 (video/webm;codecs=vp8)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
> This behavior isn't explicitly mentioned in the manual

It is mentioned [here](https://www.construct.net/en/make-games/manuals/construct-3/system-reference/system-conditions#internalH1Link3:~:text=This%20check%20includes%20parent%20layers%3A):

> This check includes parent layers: if any parent layer is invisible, then its sub-layers count as invisible too.

Making a parent layer invisible implicitly makes all its sub-layers invisible, so I think it's correct that "Is visible" is false in this case.

Perhaps there could be some other condition e.g. "is self visible" which only checks its own visibility setting and ignores the state of parent layers. However that would be a feature request.

**Comment by WilsonPercival** [comment]
In fact this is already present in JavaScript:

https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/layout-interfaces/ilayout/ilayer

<img width="532" alt="kek" src="https://github.com/Scirra/Construct-bugs/assets/91274932/724a555b-8b37-4236-87ea-493a2e883029">
