### ISSUE TITLE
Crash when Open Shared c3p file on Cloud callback 403 code

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7806]
## Problem description

I found a C3P file in my Google Drive. But display the Size is unkown.

![Snipaste_2024-02-04_00-42-23](https://github.com/Scirra/Construct-bugs/assets/45864744/d87d5b6a-d8d8-4335-b0b1-effb1f35a8bc)

![07](https://github.com/Scirra/Construct-bugs/assets/45864744/2942eb8c-f193-466e-bf3b-c6aff673fc92)

If I open it file, C3 crashes

![Snipaste_2024-02-04_00-38-10](https://github.com/Scirra/Construct-bugs/assets/45864744/11fd0ab9-cfd0-4294-b9ef-4a487bebb0da)

After investigation, it was found that this file was shared by others and saved to the Drive. So he didn't show my information. If I download it locally from Google Drive, it can be opened.

![Snipaste_2024-02-04_00-59-59](https://github.com/Scirra/Construct-bugs/assets/45864744/061cfaf8-c06a-4cad-844d-49ec826112cd)

## Log

```
Error report information
Type: unhandled rejection
Reason: {"response":{},"code":403,"status":""}
Construct version: r368.2
URL: https://editor.construct.net/
Date: Sun Feb 04 2024 00:36:59 GMT+0800 (China Standard Time)
Uptime: 13.8 s

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 121.0.6167.85
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex
```

```
register-root-sw.js:17 Registered root service worker on https://editor.construct.net/
main.js:2934 Stop!
main.js:2935 This is a browser feature intended for developers. If someone told you to copy and paste something here to enable a feature or "hack" something, it is a scam and may allow them to steal your account information or your work.
main.js:2935 Note: this is the developer tools console for the Construct editor. If you're looking for developer tools for preview, be sure to open developer tools for the preview window instead.
root-sw.js:273 [Root-SW-Offline] Up to date
sw.js:273 [SW-Offline] Up to date
main.js:222 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' blob: https://downloads.construct.net https://downloads.scirra.com 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-YEoY5MMKx23nGqjz6TM8tin0KGorJPFml1PGHNqjeIo='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

(anonymous) @ main.js:222
button:1 
        
        
       Failed to load resource: the server responded with a status of 400 ()
m=credential_button_library:49 [GSI_LOGGER]: The given origin is not allowed for the given client ID.
_.B @ m=credential_button_library:49
main.js:880 Registered service worker on https://editor.construct.net/r368-2/
www.googleapis.com/drive/v3/files/1DbSgGJmNVfhXbWJxJRUx5JBZZAkpp5w?alt=media:1 
        
        
       Failed to load resource: the server responded with a status of 403 ()
editor.construct.net/:1 Uncaught (in promise) Object

```

## Steps to reproduce

1. Save files from other users to own Cloud
2.
3.

## Observed result

Crash due to 403 code

## Expected result

no crash, but prompts that it cannot be opened.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Cloud save with Google Drive is only coded to show shared content from shared folders that have "editor" permission granted. As far as I can see that's how it works and I can successfully open a shared project inside a shared folder in this case; if the permissions are different then the shared folder doesn't appear at all.

Perhaps there is some other way to set up sharing, but to be able to investigate we need the full steps to reproduce, including how you set up this sharing situation in the first place.

**Comment by XHXIAIEIN** [comment]
Only can view
![10](https://github.com/Scirra/Construct-bugs/assets/45864744/33a45e6b-e1f7-4d4f-9bd9-03e76d75817c)

**Comment by AshleyScirra** [comment]
OK, so I take it in this case you are using 'Share - Copy Link', sending the link to someone else, then using the 'Add shortcut' option to add a shortcut to the shared file to your own Google Drive. That looks like it does reproduce the issue for me.

**Comment by AshleyScirra** [comment]
It seems the normal Google Drive APIs don't support shortcuts, and read-only files would take extra work to support (otherwise Construct will still try to save over them and fail). I could not reproduce any crash in this situation though - it just says "failed to open file", appearing to correctly report an error message. Still as it seems shortcuts are not supported I've just filtered them from the list for the next beta so they won't appear.
