### ISSUE TITLE
Failed to open project: Flowchart problem

### ISSUE THREAD

**Issue by algiz13** [Scirra/Construct-bugs#7807]
## Problem description

When trying to open a file, it fails with this message: Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.
This appears in the console.
 [Project] Exception opening:  Error: no flowchart element found
    at d.j5a (projectResources.js:1785:61)
    at window.Ch.ff (projectResources.js:1795:9)
    at d.ff (projectResources.js:1784:444)
    at d.Upb (projectResources.js:1830:365)
    at d.w$b (projectResources.js:1914:81)
    at async CCG.Hn (main.js:872:1)
    at async Xpa (main.js:921:307)
    at async Object.PM (main.js:3001:319)

Seems to have been when the startnode of a flowchart was deleted, and no new start node was made.

## Attach a .c3p
https://drive.google.com/file/d/1VLTfyn0casrWnnmabKwvsSqlM4gFf-tx/view?usp=drive_link

## Steps to reproduce

1. Create a project with the flowchart object.
2. Create a flowchart with a few linked nodes.
3. Delete the star node and save.
4. Try to reopen.

## Observed result

Messagebox: Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.

## Expected result

File should open.

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:**
r377 beta

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r377 (beta)
Browser: Chrome 121.0.6167.140
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 138 gb
Storage usage (approx): 437 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 (0x00001B80) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment]
A fix for this will go out in the next beta.
