### ISSUE TITLE
Pasting multiple copied cells from Excel bug

### ISSUE THREAD

**Issue by dop2000** [Scirra/Construct-bugs#7812]
The ability to paste data from Excel/Google Sheets into C3 array is a great feature. Unfortunately, pasting several cells may overwrite a row of values below.

I think this only happens with Excel now, but I remember having the same issue with Google Sheets.

## Attach a .c3p

[sample_.zip](https://github.com/Scirra/Construct-bugs/files/14189285/sample_.zip)

## Steps to reproduce

1. Open the spreadsheet in Excel
2. Copy one line of values
3. Try to paste it into the array into the same line

## Observed result

Values in the row below disappear

![image](https://github.com/Scirra/Construct-bugs/assets/36763350/93a10863-6b53-4626-9d3a-403c327ff838)

## Expected result

Values in other lines should not be affected.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r368.2 (stable)
Browser: Chrome 121.0.6167.140
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.3541666269302368
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 531 gb
Storage usage (approx): 3.5 gb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6800 (0x000073BF) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm; codecs=opus)
Ogg Opus (audio/ogg; codecs=opus)
WebM Vorbis (audio/webm; codecs=vorbis)
Ogg Vorbis (audio/ogg; codecs=vorbis)
MPEG-4 AAC (audio/mp4; codecs=mp4a.40.5)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav; codecs=1)
Supported encode formats:

WebM Opus (audio/webm; codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm; codecs=av01.0.00M.08)
MP4 AV1 (video/mp4; codecs=av01.0.00M.08)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
H.265 (video/mp4; codecs=hev1.1.2.L93.B0)
H.264 (video/mp4; codecs=avc1.42E01E)
Supported encode formats:

WebM AV1 (video/webm; codecs=av1)
WebM VP9 (video/webm; codecs=vp9)
WebM VP8 (video/webm; codecs=vp8)
</details>

**Comment by WilsonPercival** [comment]
https://github.com/Scirra/Construct-bugs/issues/5928

**Comment by dop2000** [comment]
@DiegoScirra I understand from your comment in that old ticket that the problem is with the extra new line at the end of the clipboard data. Can you simply remove it? 
When the clipboard contains nothing but empty cells and newlines - allow pasting it. But if there is some actual data, then trim the newline at the end. I believe this should cover all bases.

**Comment by DiegoScirra** [comment]
@dop2000

I would need to check how the data ExCel copies to the clipboard looks like. If it is possible to distinguish it from other applications then I could modify it safely. The problem is if there is no way to tell that, in that case I wouldn't know if the data is coming from a program which isn't adding any characters you didn't ask for or not.

Google sheets doesn't add any extra line breaks, so if data from Google sheets has an extra line break, I have to assume it's the right thing and just paste that.

**Comment by dop2000** [comment]
But pasting an extra line break is much more destructive than not pasting it.. 
Besides, if you copy a line of cells in Excel and paste it into Google Sheets - this doesn't overwrite the cells below. 
If Google Sheets can detect and ignore the extra line break, I think it's safe to do the same in C3.
