### ISSUE TITLE
Construct 3 Exported Applications Default to Integrated GPU Despite High Performance Setting on Dual-GPU Laptops

### ISSUE THREAD

**Issue by TamaniDamani** [Scirra/Construct-bugs#7813]
## Problem description
When launching games exported with NWJS or WebView2 on laptops equipped with both integrated and dedicated GPUs, the games default to using the integrated graphics processor (iGPU) instead of the dedicated GPU. This results in suboptimal game performance. Manually adjusting settings in the NVIDIA Control Panel to force the use of the dedicated GPU can mitigate this issue, but it's not an ideal solution for end users.

## Attach a .c3p
[Please attach a minimal Construct project (.c3p) file that demonstrates the issue. The file should be as small as possible and only include what is necessary to observe the problem.]

## Steps to reproduce
Export any game project from Construct 3 using NWJS or WebView2.
Run the exported game on a laptop with both integrated and dedicated GPUs.
Observe which GPU is utilized by the game (via Task Manager or GPU activity indicators).
Observed result
The game defaults to running on the integrated GPU, despite the presence of a more powerful dedicated GPU, leading to lower performance.

## Expected result
The game should automatically utilize the dedicated GPU when available, ensuring optimal performance without requiring manual configuration by the user.

## More details
This issue has been observed across multiple devices and seems to be consistent regardless of the specific hardware or drivers used. Manual configuration via the NVIDIA Control Panel to prefer the dedicated GPU can serve as a workaround, but this is not a feasible solution for all users.

## Affected browsers/platforms: NWJS, WebView2 exports (The issue is not browser-specific but rather related to how these platforms interact with GPU selection on Windows.)

First affected release: [Not applicable as this issue pertains to the export process and hardware interaction rather than a specific release of Construct 3.]

**Comment by AshleyScirra** [comment]
It's not Construct doing this - see [this forum post](https://www.construct.net/en/forum/construct-3/how-do-i-8/force-game-built-construct-180823#forumPost1103326).
