### ISSUE TITLE
Trouble Exporting to Xcode Format

### ISSUE THREAD

**Issue by nosebagmedia** [Scirra/Construct-bugs#7815]
I am getting this error message when I try to export to iOS Xcode format, but it works fine when I do Cordova. Anyone know why? Thank you.

Also, I am trying to update my app on the app store, but I am having trouble. The first time I managed to get it on there, it was a very complex workaround, and I am just trying to skip that if possible.

ERROR MESSAGE:

Error: Platform 'ios' found in config.xml... Migrating it to package.json

Discovered platform "ios". Adding it to the project

Using cordova-fetch for cordova-ios@7.0.1

Adding ios project...

Creating Cordova project for the iOS platform:

Path: ~~/ios

Package: com.nosebag.media

Name: Patric's Pursuit

iOS project created with cordova-ios@7.0.1

Plugin 'admob-plus-cordova' found in config.xml... Migrating it to package.json

Plugin 'cordova-plugin-consent' found in config.xml... Migrating it to package.json

Plugin 'cordova-plugin-device' found in config.xml... Migrating it to package.json

Plugin 'cordova-plugin-idfa' found in config.xml... Migrating it to package.json

Plugin 'cordova-plugin-nativestorage' found in config.xml... Migrating it to package.json

Plugin 'construct-mobile-export2' found in config.xml... Migrating it to package.json

Discovered plugin "admob-plus-cordova". Adding it to the project

Installing "admob-plus-cordova" for ios

Discovered plugin "cordova-plugin-consent". Adding it to the project

Installing "cordova-plugin-consent" for ios

Discovered plugin "cordova-plugin-device". Adding it to the project

Installing "cordova-plugin-device" for ios

Discovered plugin "cordova-plugin-idfa". Adding it to the project

Installing "cordova-plugin-idfa" for ios

Discovered plugin "cordova-plugin-nativestorage". Adding it to the project

Installing "cordova-plugin-nativestorage" for ios

Discovered plugin "construct-mobile-export2". Adding it to the project

Installing "construct-mobile-export2" for ios

Running in: linux

Setting swift version

Running manual pod update

Pod update failed

Update all pods

Updating local specs repositories

CocoaPods 1.15.0 is available.

To update use: `sudo gem install cocoapods`

For more information, see https:/~~/blog.cocoapods.org and the CHANGELOG for this version at https:/~~/1.15.0

Analyzing dependencies

[!] The target `Patric's Pursuit` is declared multiple times for the project `Patric's Pursuit.xcodeproj`.

CordovaError: Promise rejected with non-error: undefined

at ~~/cordova:30:15

at process.processTicksAndRejections (node:~~/task_queues:95:5)

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it's impossible for us to help.
