### ISSUE TITLE
Binary data: compression & decompression always fails on iOS web export

### ISSUE THREAD

**Issue by AmogusJS** [Scirra/Construct-bugs#7816]
## Problem description

Binary data compression & decompression actions always fail on iOS web export. This does not appear to be an issue with Safari as other implementations of the deflate compression work fine on the same device (e.g. https://www.zickty.com/texttogzip).

## Attach a .c3p
https://editor.construct.net/#open=compression

## Steps to reproduce

**On Desktop:**
1. Enter any text
2. Press 'Compress'
3. Press 'Decompress'

First, text will be compressed and then decompressed back correctly as expected.

**On iOS:**
1. Enter any text
2. Press either 'Compress' or 'Decompress'

You'll get either 'Compression failed' or 'Decompression failed' message depending on what option you've chosen. Regardless of the text entered, both actions always fail.

## Observed result

Compression and decompressions always fail on iOS.

## Expected result

Text is compressed and decompressed back correctly without any errors.

## More details
**Affected browsers/platforms:**
Safari on iPhone 6s with iOS 15.8 (real device)
Safari on iPhone 14 Pro with iOS 16.2 (through Appetize)

**First affected release:**
First discovered on r368.2

## System details

<details><summary>View details</summary>
'Copy' button does not work. The text in Platform information window is not selectable either.
</details>

**Comment by AshleyScirra** [comment]
Have you tested on iOS 17+? Compression support was only added in Safari 16.4 (so iOS 15.8 won't support it) and IIRC, it was broken until Safari 17 (pretty typical of Apple's negligence with Safari).

**Comment by AshleyScirra** [comment]
I exported the compression example and uploaded it here: https://downloads.scirra.com/labs/bugs/compression/index.html

It works fine for me with Safari on iOS 17.2.1. So I think you are just using out-of-date software that does not support it.
