### ISSUE TITLE
c3runtime.js error

### ISSUE THREAD

**Issue by rmmcassa** [Scirra/Construct-bugs#7819]
## Problem description

Single project with just a sprite, exported to HTML5, sometimes it works sometimes it doesn't. It throws a c3runtime.js error.
It I keep exporting (without touching anything) eventually it will work.

Online example:
https://www.ultimatelang.com/v4b

## Attach a .c3p

[](https://drive.google.com/file/d/1ZYS2HbwXpcgCVvsKu8IjJxhK99eDNL3T/view?usp=sharing)

## Steps to reproduce

1. Just s project with a single sprite
2. Export to HTML5
3.Uoload to a web server. Sometimes work sometimes doesn't

## Observed result

No loading default logo, then black screen

## Expected result

a red sprite on screen

## More details
Tested in the latest stable version and the latest beta version. Same result,

**Affected browsers/platforms:** All

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Can not reproduce. Can you send a screenshot of the error?

**Comment by rmmcassa** [comment]
> Can not reproduce. Can you send a screenshot of the error?

![Screenshot (188)](https://github.com/Scirra/Construct-bugs/assets/159689053/409a598f-e1f3-42cb-8f81-548597b7f135)

**Comment by WilsonPercival** [comment]
> > Can not reproduce. Can you send a screenshot of the error?
> 
> ![Screenshot (188)](https://private-user-images.githubusercontent.com/159689053/303935626-409a598f-e1f3-42cb-8f81-548597b7f135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzI1ODgsIm5iZiI6MTcwNzY3MjI4OCwicGF0aCI6Ii8xNTk2ODkwNTMvMzAzOTM1NjI2LTQwOWE1OThmLWUxZjMtNDJjYi04ZjgxLTU0ODU5N2I3ZjEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxNzI0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWQ0YzAyNTcyNmRmZjQ2NDlkMDVkNWUyODhhZWE5NWIxYWMyY2M4YTUwNjQ0YzZmMjRiMDBiNjViZmFjMzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i1oILxWH1NHUBFS-UfquTnPxWBd7jqh_Cpw9j8yavwI)

Can you show the error by opening the console like this?

![image](https://github.com/Scirra/Construct-bugs/assets/91274932/7d434974-df1d-4d4b-a08e-c0c4cb39c155)

**Comment by rmmcassa** [comment]
> > > Can not reproduce. Can you send a screenshot of the error?
> > 
> > 
> > ![Screenshot (188)](https://private-user-images.githubusercontent.com/159689053/303935626-409a598f-e1f3-42cb-8f81-548597b7f135.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzI1ODgsIm5iZiI6MTcwNzY3MjI4OCwicGF0aCI6Ii8xNTk2ODkwNTMvMzAzOTM1NjI2LTQwOWE1OThmLWUxZjMtNDJjYi04ZjgxLTU0ODU5N2I3ZjEzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQxNzI0NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWQ0YzAyNTcyNmRmZjQ2NDlkMDVkNWUyODhhZWE5NWIxYWMyY2M4YTUwNjQ0YzZmMjRiMDBiNjViZmFjMzNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.i1oILxWH1NHUBFS-UfquTnPxWBd7jqh_Cpw9j8yavwI)
> 
> Can you show the error by opening the console like this?
> 
> ![image](https://private-user-images.githubusercontent.com/91274932/303935865-7d434974-df1d-4d4b-a08e-c0c4cb39c155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NzM2NzgsIm5iZiI6MTcwNzY3MzM3OCwicGF0aCI6Ii85MTI3NDkzMi8zMDM5MzU4NjUtN2Q0MzQ5NzQtZGYxZC00ZDRiLWEwOGUtYzBjNGNiMzljMTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDE3NDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWUzYWUzNGI4ZTJiMDljMGNmMWJiMTEyNzQ5NDk5MzIwM2NmOGI2NTE2ZmZlYTM3MmFmZGUwNjhiMmQ5OGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IL6WdlAzDSv9CgveCD_U7KM8UfwUz4Sk2vRd6xKgI8k)

![Screenshot (189)](https://github.com/Scirra/Construct-bugs/assets/159689053/2af67252-c1a5-4347-bc59-912a128172fc)

**Comment by AshleyScirra** [comment]
It works fine for me and no project has been provided as required by the bug report guidelines so it's impossible to investigate anyway, so closing. Please always follow the bug report guidelines otherwise it's impossible for us to help.
