### ISSUE TITLE
3Dshape scripting interface .shape error

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7820]
## Problem description
Using the shape scripting interface of the 3d object causes an error.
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/9f9c5d24-1952-4e7e-8f2e-7220017e24ea)
I'm fairly certain that it's due to a typo here, it should be ``_GetShape()`` instead, with a capital S.

## Attach a .c3p
[getShape.zip](https://github.com/Scirra/Construct-bugs/files/14232988/getShape.zip)

## Steps to reproduce

1. run preview

## Observed result
error

## Expected result
get the shape string

## More details
We cannot get the shape in events, would be neat to have a shape expression there too.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, it is indeed a typo. As it's a trivial fix I've included the fix for the stable release (currently scheduled for tomorrow).
