### ISSUE TITLE
Error trying to create a Sprite or Tile background

### ISSUE THREAD

**Issue by maxim55hdhh55** [Scirra/Construct-bugs#7824]
вот ета ето после обновления "Error report information
Type: unhandled rejection
Reason: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. @ Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:315) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: Error: Failed to execute 'convertToBlob' on 'HTMLCanvasElement': "Canvas" has no rendering context. at Function.C.IO (https://editor.construct.net/r379/main.js:1099:124) at d.fS (https://editor.construct.net/r379/projectResources.js:811:200) at d.fS (https://editor.construct.net/r379/projectResources.js:725:315) at async https://editor.construct.net/r379/projectResources.js:2944:169 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/
Date: Tue Feb 13 2024 20:27:41 GMT+0200 (Восточная Европа, стандартное время)
Uptime: 496.1 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 100.0.4896.75
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) c3_wladek_hack/1.4.0 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36
Language setting: ru-RU

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Family Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_video_texture, WEBGL_webcodecs_video_frame, OVR_multiview2"

**Comment by WilsonPercival** [comment]
Can not reproduce. Can you repeat the problem in an incognito tab?

**Comment by DiegoScirra** [comment]
I have translated the title of the issue using Google translate. In the future try doing that, it would become very confusing if everyone wrote in their own language.

As for the issue, I can't reproduce it, but I have noticed that you are using an old version of Chrome. Try updating to the latest and see if that helps.

**Comment by AshleyScirra** [comment]
> Product: Construct 3 r379 (stable)
> Browser: Chrome 100.0.4896.75

Both of these are out of date. The latest Construct version is r379 and the latest Chrome version is v121. Please update both as presumably using out-of-date software is the problem, as it doesn't reproduce for me in Chrome v121.

**Comment by AshleyScirra** [comment]
I also note that your user agent string indicates you're using Electron and includes `c3_wladek_hack`. Perhaps you should not come to us with such requests...

**Comment by maxim55hdhh55** [comment]
Оу боже я приям много ошибок зделал пока просил о помощи с етим багом
простите наверно стоит фиксить мне все самому... а хак зделан владиком ну
такая судьба ну и простите што неперевел етот текст времени нету:(

ср, 14 февр. 2024 г., 12:35 Ashley (Scirra) ***@***.***>:

**Comment by sergiopoverony** [comment]
@maxim55hdhh55 сразу фильм вспомнился, про Максимку, который фильмы пиратил. Думай головой что делаешь.

**Comment by rezzonanc** [comment]
хохлы)
