### ISSUE TITLE
Something is wrong with the SpriteFont color

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-bugs#7827]
## Problem description

I looked here recently and the topic of SpriteFont color was already discussed. But maybe I have something different. I only use stable versions in my game and when I upgraded to the latest stable version I saw that there was something wrong with my SF. I use the general color for white SF, but for the icons that are in the SF image I use BBcode and [color=fff]. (I haven't used # before color in bbcode, but it doesn't fix the situation)
The color changes are too confusing and I don’t understand why this is happening

## Attach a .c3p

[SF-bug-.zip](https://github.com/Scirra/Construct-bugs/files/14277146/SF-bug-.zip)

## Steps to reproduce

Watch the video in the archive with the source

## Observed result

I see the wrong color. Sometimes it's right and sometimes it's not

## Expected result

with [color={color}] or [color=#{color}] I should always see the correct color

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is the same cause as #7821. Using just `fff` for a color is not valid CSS color syntax. However using `#fff` is, and that does fix the problem for me.

Technically this is a breaking change as previously SpriteFonts used a custom non-standard JavaScript color parser. Not only was this not consistent with the Text object (e.g. in this case `fff` is not acceptable in BBcode for Text, but was allowed for SpriteFont), it also did not support all the same colors (e.g. as per #7638 the color name `red` was allowed for Text, but not SpriteFont). I think it is worth having a breaking change to align SpriteFont BBcode with Text, so they both support the same colors and work consistently, and the only thing that is broken is non-standard syntax which would not be accepted by browsers in CSS, so arguably it was a bug that such values were ever accepted. So while this might cause some disruption to existing projects I think it's worthwhile to keep things standardised and consistently supported, and hopefully it should be straightforward to update projects - you just need to make sure it specifies a valid CSS color.

**Comment by fredriksthlm** [comment]
To me this is still very weird.
If I change the left instance of the spritefont to #fff , then actually both spritefont instances change to white, even if the other one still has the erroneous fff tag still. If I change only the right one, then only the right one will show white, but not the left one.
Also o, that if they have ever change to white, they will still be white in the editor, even if you change back to an erroneous syntax, while in preview they will not be white!
So for me the editor is not inline with either preview or the actual code then..

**Comment by q3olegka** [comment]
Yes. As we wrote above, everything is exactly like that and it is confusing.  No problem to add # to bbcode, but please see again how it works in the editor

**Comment by AshleyScirra** [comment]
I think it is just using the last valid color when it encounters an invalid color. I guess we could change that to default invalid colors back to white or something, but I don't think it's a serious issue.
