### ISSUE TITLE
Phone editing css crash

### ISSUE THREAD

**Issue by OrcusLabs** [Scirra/Construct-bugs#7830]
## Problem description
Was editing a css on the phone app. Tried typing in a - and it erased the line. Tried pasting font-size into the css, app crash.

Error report information
Type: unhandled exception
File: https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js, line 44, col 330
Message: Uncaught TypeError: Cannot read properties of null (reading 'replaceChild')
Stack: TypeError: Cannot read properties of null (reading 'replaceChild') at cd (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:44:330) at Xg (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:113:224) at Me (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:109:386) at https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:97:445 at Rd (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:43:301) at tc (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:96:168) at https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:104:58 at Oc (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:142:431) at Pc (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:149:87) at Fa.pollContent (https://editor.construct.net/r379/3rdparty/codemirror/codemirror.js:289:409)
Construct version: r379
URL: https://editor.construct.net/
Date: Wed Feb 14 2024 06:13:10 GMT-0800 (Pacific Standard Time)
Uptime: 78.2 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.144
Browser engine: Chromium
Context: webapp
Operating system: Android 14.0.0
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Qualcomm)
Renderer: ANGLE (Qualcomm, Adreno (TM) 730, OpenGL ES 3.2)
Major performance caveat: no
Maximum texture size: 4096
Point size range: 1 to 1023
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_float_blend, EXT_texture_filter_anisotropic, EXT_texture_norm16, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_clip_cull_distance, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw
## Steps to reproduce

1.
2.
3.s

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Can you attach the project file and write the exact steps that reproduce the problem?

**Comment by AshleyScirra** [comment]
Tried editing a CSS file on a similar Android device. Everything seemed to work fine, including typing `-` and pasting `font-size`.

Please always follow the bug report guidelines otherwise it's impossible for us to help.
