### ISSUE TITLE
"Flowcharts Questionnaire" example typo

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#7832]
## Problem description

Just a typo in the text, nothing more.

## Typo

![TypeSript-typo](https://github.com/Scirra/Construct-bugs/assets/59319082/8c3992c8-e511-483f-8d98-ebba81220cef)

**Comment by AshleyScirra** [comment]
Thanks, fixed for the next beta. I don't think it quite merits a changelog entry but it should be corrected in the next release.
