### ISSUE TITLE
Renaming a Custom Action Crashes Browser (not just Construct!)

### ISSUE THREAD

**Issue by WightLightProjects** [Scirra/Construct-bugs#7833]
## Problem description

Renaming a Custom Action Crashes Browser (not just Construct!)

## Attach a .c3p

[RenameActionBug.zip](https://github.com/Scirra/Construct-bugs/files/14290956/RenameActionBug.zip)

## Steps to reproduce

1. Create project.
2. Create object in project.
3. In event sheet, add custom action for object.
4. Attempt to rename custom action.

## Observed result

Browser crashed entirely on attempting custom action rename.

## Expected result

No crash!

## More details

Apparently happens specifically in Chrome and Chromium browsers. Has not affected Firefox.

https://github.com/Scirra/Construct-bugs/assets/155599328/0552afd2-ef4d-43fd-bba5-eb19faf96fea

**Affected browsers/platforms:** Chrome, Arc.

**First affected release:** At latest, r379 stable.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.160
Browser engine: Chromium
Context: browser
Operating system: Linux 6.5.0
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 274 gb
Storage usage (approx): 126 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 480 Graphics (polaris10 LLVM 15.0.7), OpenGL 4.6)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
Looks like the same issue as #7796. Chrome v121 is affected, but it should be fixed in v122+, which is already available as a beta release if you want to work around this.
