### ISSUE TITLE
Folder not display in 'Create object' action dialog

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7835]
## Problem description

The folder structure is not shown in the System action 'Create object' dialog, which can become inconvenient in some large projects with a large number of objects

## Attach a .c3p

https://editor.construct.net/#open=demonoire

## Steps to reproduce
1. Add 'System' action: Create object

## Observed result
![Snipaste_2024-02-16_21-59-19](https://github.com/Scirra/Construct-bugs/assets/45864744/abe3232d-5bb9-47fe-9ef7-c30fd0087f7e)

## Expected result

![Snipaste_2024-02-16_22-15-29](https://github.com/Scirra/Construct-bugs/assets/45864744/93b5c3ea-15a0-476e-9c9e-4730f2dd98db)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is currently by design. However you can file a feature request for this.

**Comment by XHXIAIEIN** [comment]
https://github.com/Scirra/Construct-feature-requests/issues/143
