### ISSUE TITLE
I can't create a new project because of bugs and or isues.

### ISSUE THREAD

**Issue by mrchicken3344** [Scirra/Construct-bugs#7839]
I can't make a new project on construct 3 well. 

So I am on a school chromebook and wanted to make a project. So I opened up a new project and noticed some tool bar stuff has no picture. And when I double clicked to add a new thing. The pictures for the things to add are gone to. Thats odd. And when I tried to add a sprite the tool bar there was gone also. I also got an error message for the 3d shape one to, I dont know how many are not working.

So I also tried to do a guided tour and came into similar isues, exept when it asks you to drag the pig into the spot it gave me this error code.

I hope this makes it to you guys and is not deleated. I know there is no example but I can't give one, sorry.
I hope this gets fixed.

Over all isue.
Some tool bars are gone and I can't seem to make sprites because of that and similiar isues.

Error report information
Type: unhandled rejection
Reason: Error: expected file @ TypeError: expected file at Q.eB (https://editor.construct.net/r379/main.js:1048:324) at xp.kP (https://editor.construct.net/r379/main.js:1193:115) at https://editor.construct.net/r379/projectResources.js:2372:332 at Array.filter () at eN.spa.mSa (https://editor.construct.net/r379/projectResources.js:2372:319) at eN.spa.w8a (https://editor.construct.net/r379/projectResources.js:2374:163) at NM.d2b (https://editor.construct.net/r379/projectResources.js:2296:495) at v7a.vCc.XS (https://editor.construct.net/r379/projectResources.js:2533:130)
Stack: TypeError: expected file at Q.eB (https://editor.construct.net/r379/main.js:1048:324) at xp.kP (https://editor.construct.net/r379/main.js:1193:115) at https://editor.construct.net/r379/projectResources.js:2372:332 at Array.filter () at eN.spa.mSa (https://editor.construct.net/r379/projectResources.js:2372:319) at eN.spa.w8a (https://editor.construct.net/r379/projectResources.js:2374:163) at NM.d2b (https://editor.construct.net/r379/projectResources.js:2296:495) at v7a.vCc.XS (https://editor.construct.net/r379/projectResources.js:2533:130)
Construct version: r379
URL: https://editor.construct.net/?startTour
Date: Fri Feb 16 2024 17:26:31 GMT-0600 (Central Standard Time)
Uptime: 100.7 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.159
Browser engine: Chromium
Context: browser
Operating system: Chrome OS 15699.58.0
Device type: desktop
Device pixel ratio: 0.9004614353179932
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by XHXIAIEIN** [comment]
I think if you can't provide more detailed information then this error won't be handled. Because other people don't know what's going on. 

Have you tried restarting the browser and opening C3 again, will this still happen?

**Comment by mrchicken3344** [comment]
Sorry, I know I did not provide much info. Here is a screen recording. But I dont know if it will work as a link or not.

[Uploading Screen recording 2024-02-17 11.36.38 AM.webm…]()

**Comment by mrchicken3344** [comment]
Thats wierd it did not work?

**Comment by mrchicken3344** [comment]
[Screen recording 2024-02-17 11.36.38 AM.webm](https://github.com/Scirra/Construct-bugs/assets/160289784/5deda93f-81cd-459f-ba1e-d631cf2951ed)

**Comment by mrchicken3344** [comment]
here is part 2 of that when I  restarted it.

[Screen recording 2024-02-17 11.37.34 AM.webm](https://github.com/Scirra/Construct-bugs/assets/160289784/b2d2346f-d197-4a02-ae61-34876e75e623)

**Comment by mrchicken3344** [comment]
And here is when I tried to reset the tool bar.

[Screen recording 2024-02-17 11.56.33 AM.webm](https://github.com/Scirra/Construct-bugs/assets/160289784/f9265025-4218-4379-98ed-91132bf2ef51)

**Comment by mrchicken3344** [comment]
I have restarted the app/computer. And made a new acount which also failed. I have used the app in the past without these isues, and I came back after a while and now this happend?

**Comment by mrchicken3344** [comment]
Hope the videos help.

**Comment by mrchicken3344** [comment]
I still can't add a 3d shape.

**Comment by XHXIAIEIN** [comment]
Maybe you can continue to check or maybe it's a conflict caused by a browser extension? Try disabling all extensions, or try using another browser? Or Upgrading graphics card driver software?

**Comment by mrchicken3344** [comment]
it gives me this error code.

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Q.zn (https://editor.construct.net/r379/main.js:1057:227) at C.KD (https://editor.construct.net/r379/main.js:1096:307) at naa (https://editor.construct.net/r379/main.js:142:58) at oaa (https://editor.construct.net/r379/main.js:142:276) at Object.HD (https://editor.construct.net/r379/main.js:1094:473) at Yc.DC.rEa (https://editor.construct.net/r379/main.js:1282:294) at https://editor.construct.net/r379/main.js:1282:179 at new Promise () at Yc.DC.Ya (https://editor.construct.net/r379/main.js:1282:114) at C.qNa (https://editor.construct.net/r379/main.js:1094:466)
Stack: TypeError: unexpected type at Q.zn (https://editor.construct.net/r379/main.js:1057:227) at C.KD (https://editor.construct.net/r379/main.js:1096:307) at naa (https://editor.construct.net/r379/main.js:142:58) at oaa (https://editor.construct.net/r379/main.js:142:276) at Object.HD (https://editor.construct.net/r379/main.js:1094:473) at Yc.DC.rEa (https://editor.construct.net/r379/main.js:1282:294) at https://editor.construct.net/r379/main.js:1282:179 at new Promise () at Yc.DC.Ya (https://editor.construct.net/r379/main.js:1282:114) at C.qNa (https://editor.construct.net/r379/main.js:1094:466)
Construct version: r379
URL: https://editor.construct.net/?startTour
Date: Sun Feb 18 2024 12:22:20 GMT-0600 (Central Standard Time)
Uptime: 15.9 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.159
Browser engine: Chromium
Context: browser
Operating system: Chrome OS 15699.58.0
Device type: desktop
Device pixel ratio: 0.9004614353179932
Logical CPU cores: 2
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Mesa Intel(R) UHD Graphics 600 (GLK 2), OpenGL ES 3.2)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw

**Comment by AshleyScirra** [comment]
I can't reproduce any problem on Chrome 121 on Windows. I'd guess there is some problem with the Chromebook device rather than Construct, especially because of:

> So I opened up a new project and noticed some tool bar stuff has no picture. 

If other graphics glitches are appearing in the editor, that typically indicates a graphics driver problem, which is the number 1 cause of weird issues that only happen on specific devices. Such issues are with the device's system software and out of our control so you'd have to report them to Google.

Assigning @DiegoScirra in case you can divine anything from these crash reports but I'd guess this is not something we will be able to help with.

**Comment by DiegoScirra** [comment]
From looking at the initial crash report it looks like the test image you load in the guided tour somehow fails to be decoded, which is very strange. By the time that happens I think that a bunch of other things have gone wrong and it's just luck that the application is still running. Icons not loading is not a good sign.

Without a Chrome OS device it's almost impossible to investigate this, and even if we had one this could be due to a spotty internet connection or out of date graphics drivers. If the hardware is old enough it might not even be possible to update the drivers. If we were to get a Chromebook, it would be a new one and chances are high that everything would work properly.
