### ISSUE TITLE
Theme: include event sheet styling issues

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7843]
## Problem description
Styling of the "include event sheet dialog looks broken, I think it's a regression as I remember it working better before, but I didn't want to spend the time checking older versions, so not certain.
Additionally the search bar isn't styled

## Attach a .c3p
independent of project

## Steps to reproduce

1. enable dark theme
2. add an event sheet 
3. right-click event sheet and press "include event sheet"
4. select a sheet to see the selection colors change

## Observed result
Colors of the main selection are looking wrong and get worse if you select something, search bar isn't styled.

https://github.com/Scirra/Construct-bugs/assets/89512047/a7888e95-e0d5-486a-ab17-1ff72c2f6ac8

## Expected result
List has correct colors when selecting etc. Search bar is styled.
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/1dfb089d-12e6-44dc-9c02-7cfe941ccb90)
I.e like other similar dialogues with a dark background of the main area and dark text input.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
