### ISSUE TITLE
Pick nearest bug

### ISSUE THREAD

**Issue by WilsonPercival** [Scirra/Construct-bugs#7846]
## Problem description

The `Pick nearest` condition does not work correctly.

## Attach a .c3p

[pick_nearest_bug_r42b.zip](https://github.com/WilsonPercival/WilsonPercival/files/14338615/pick_nearest_bug_r42b.zip)

## Steps to reproduce

1. Open and run the project.

## Observed result

<img width="202" alt="observed" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/fc4d1a55-f7b3-4ca8-bbf2-e0cb92df5668">

## Expected result

<img width="206" alt="expected" src="https://github.com/WilsonPercival/WilsonPercival/assets/91274932/fbfd9cde-d64e-4329-a7ac-786614858b6b">

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** Broke in `r42b` as it is the oldest version I can test. Still doesn't work in `r379s`.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.161
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 283 gb
Storage usage (approx): 1021 mb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001638) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by WilsonPercival** [comment]
> This project picks the object nearest to (0, Infinity).
> 
> Which object is nearest to a point an infinite distance away? I think mathematically speaking, they are all the same distance away, as the distance is infinite. Infinity is a weird thing. So it's not wrong that it picks the top sprite.
> 
> You probably want to just use a large but finite number instead, like 99999999.

@AshleyScirra I thought that if I chose infinity, it meant that I was choosing the largest number possible.

**Comment by AshleyScirra** [comment]
No, infinity is a strange mathematical concept that does not work like other numbers. I was just reading a bit about this and it depends on the definition of infinity, but in some definitions, Infinity + 1 is the same as Infinity, and so you can't meaningfully say an object Infinity pixels away is nearer than an object Infinity + 200 pixels away.

**Comment by WilsonPercival** [comment]
> No, infinity is a strange mathematical concept that does not work like other numbers. I was just reading a bit about this and it depends on the definition of infinity, but in some definitions, Infinity + 1 is the same as Infinity, and so you can't meaningfully say an object Infinity pixels away is nearer than an object Infinity + 200 pixels away.

@AshleyScirra Yes, of course, I understand that there is no infinity greater or less in mathematics. But I thought that in computers all numbers are finite and infinity in a computer simply represents the largest number the computer can handle.

**Comment by AshleyScirra** [comment]
Floating-point numbers have special bit patterns to denote +Infinity, -Infinity, and NaN (and JavaScript only uses floating-point numbers - it has no integer type in the language). These have special characteristics that work differently to normal numbers. You can try it out with JavaScript code as `Infinity` is a pre-defined global set to a number with the special value Infinity; code like `Infinity - 1` still returns `Infinity`, whereas if it were merely the largest possible number, it would return a lower number. There are other special cases like `1 + NaN` still returns `NaN`.

**Comment by WilsonPercival** [comment]
@AshleyScirra Thanks I'll know!
