### ISSUE TITLE
some flowchart interactions make weird selection

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7847]
## Problem description
Some flowchart interactions make weird selection. I.e. a arbitrary nodes output is selected seemingly randomly.

## Attach a .c3p
[flowchartSelect.zip](https://github.com/Scirra/Construct-bugs/files/14343290/flowchartSelect.zip)

## Steps to reproduce

https://github.com/Scirra/Construct-bugs/assets/89512047/804e5bee-a84d-45c7-be2a-503705e066da

1. link the first node to the second

## Observed result
 output 1 of node 3 gets highlighted

## Expected result
selection doesn't change or maybe the just connected node gets selected

## More details
there are other interactions that cause this, probably not exhaustive: pasting a node, disconnecting a node, deleting a node output

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
