### ISSUE TITLE
Flowcharts: ctrl+c a node option crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7848]
## Attach a .c3p
[flowchartSelect.zip](https://github.com/Scirra/Construct-bugs/files/14343801/flowchartSelect.zip)

## Steps to reproduce

1. select a node option, press ctrl+c

## Observed result
crash

## Expected result
no crash

## More details

It seems like we can copy a node Option, but we cannot paste a node Option, not sure if this is intended or only nodes themselves are intended to be copy pastable?

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js, line 22, col 475
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'bi')
Stack: TypeError: Cannot read properties of undefined (reading 'bi') at pkb (https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js:22:475) at zlb.VW (https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js:120:185) at Dkb (https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js:29:297) at Array. (https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js:113:374) at window.rj.dispatchEvent (https://editor.construct.net/r379/main.js:1264:399) at Skb (https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js:39:6) at Array. (https://editor.construct.net/r379/components/editors/flowchartView/flowchartView.js:142:276) at Sf.g.vb.Yya.dispatchEvent (https://editor.construct.net/r379/main.js:1264:399) at Sf.g.vb.Yya.Dd (https://editor.construct.net/r379/main.js:1367:16) at Csa.Dd (https://editor.construct.net/r379/main.js:1370:292)
Construct version: r379
URL: https://editor.construct.net/
Date: Tue Feb 20 2024 12:46:48 GMT+0100 (Mitteleuropäische Normalzeit)
Uptime: 133.4 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 121.0.6167.185
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex

</details>

**Comment by DiegoScirra** [comment]
The crash will be fixed in the next beta, and the expected behaviour is to only be able to cut, copy and paste nodes.
