### ISSUE TITLE
Flowcharts: deleting a node Option is very inconsistent 

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7849]
## Problem description
Flowcharts: deleting a node Option via context menu or delete key is very inconsistent, I think it has to do with selection issues again

## Attach a .c3p
[flowchartSelect.zip](https://github.com/Scirra/Construct-bugs/files/14343847/flowchartSelect.zip)

## Steps to reproduce

1. try deleting a node output pressing Delete or right-click context menu

## Observed result
Deletes the node itself or sometimes incorrectly forbids deleting the node Option even though there are other Options or sometimes even fails silently

## Expected result
delete the node Option, except if there is only one node option left

## More details
Deleting through the flowchart properties seems to work well.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Is this happening in the **r380** or in **r379**? I think a fix for this went out but was not mentioned in the change log.

**Comment by F3der1co** [comment]
> Is this happening in **r380** or in **r379**? I think a fix for this went out but was not mentioned in the change log.

This was reported for 379, just tested in r380 and it seems to work well now!
