### ISSUE TITLE
Crash when you add a category to functions

### ISSUE THREAD

**Issue by DanishDonut** [Scirra/Construct-bugs#7856]
## Problem description ----- MAKING FUNCTIONS and adding a category will cause the "Aww snap" screen from chrome. 

You can make a function all right. But if you assign a category then the browser disconnects immediately.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Update Chrome to v122+ and it should not happen any more.
