### ISSUE TITLE
r379 Crash When Open Animation editor 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7865]
## Problem description

C3 crashes when I create or edit Tiled Background object.

Update: 
Not just the Tiled Background object, but just enter the animation editor can crash

For example: Double click on any image to edit
https://editor.construct.net/#open=animated-title-screen

## Attach a .c3p

any project
It crash when enter the animation editor

## Steps to reproduce

![Snipaste_2024-02-28_15-16-36](https://github.com/Scirra/Construct-bugs/assets/45864744/9c33f146-63b1-4ea1-aada-e9e076c00c2a)

## Observed result

![Snipaste_2024-02-28_15-14-20](https://github.com/Scirra/Construct-bugs/assets/45864744/654cc4e3-f222-4552-b945-8efff8f008ae)

```
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Da') @ TypeError: Cannot read properties of undefined (reading 'Da') at Tz.b_.Da (https://editor.construct.net/r379/projectResources.js:2258:155) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2123:207) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2128:410) at sy.g.J.fc.UP (https://editor.construct.net/r379/projectResources.js:2118:106) at https://editor.construct.net/r379/projectResources.js:2114:473 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: TypeError: Cannot read properties of undefined (reading 'Da') at Tz.b_.Da (https://editor.construct.net/r379/projectResources.js:2258:155) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2123:207) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2128:410) at sy.g.J.fc.UP (https://editor.construct.net/r379/projectResources.js:2118:106) at https://editor.construct.net/r379/projectResources.js:2114:473 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/
Date: Wed Feb 28 2024 15:13:15 GMT+0800 (中国标准时间)
Uptime: 93.2 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 122.0.6261.70
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex
```

## More details

**Affected browsers/platforms:** 

**First affected release:**  worked in r381 but broke in r379

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 122.0.6261.70
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 477 gb
Storage usage (approx): 75 mb (0%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by WilsonPercival** [comment]
Remove the Construct data and the crash will no longer occur.

I know of a case where when opening a project it infects r379s and then even when creating a new project we will receive this error.

**Comment by XHXIAIEIN** [comment]
update: When I cleared the website cache, the problem no longer occurred and it worked.
![Snipaste_2024-02-28_15-31-29](https://github.com/Scirra/Construct-bugs/assets/45864744/2866b992-9c1e-4a46-9604-baacd5babe34)

**Comment by AshleyScirra** [comment]
The steps as stated do not reproduce any problem for me.

If there is some special project you need to open before the problem reproduces, please provide that too, so there is a full sequence of steps to successfully reproduce the problem.

**Comment by XHXIAIEIN** [comment]
There are no special steps, I just open any of the examples。

**Comment by WilsonPercival** [comment]
@AshleyScirra Sorry to mislead you, this is not actually related to a specific project. Here are the steps:

1. Open `r381b`.
2. Create a sprite.
3. Fill the image with any color.
4. Close the animation editor.
5. Open `r379s`.
6. Create a sprite.
7. When opening the animation editor, a crash will occur.

Please follow all the steps otherwise the crash will not occur.

Also note that subsequently opening `r379s` will fail every time the animation editor is opened. To get around it, you need to remove the Construct data.

**Comment by DiegoScirra** [comment]
This will be fixed on the next beta, but the current stable won't be patched. The great majority of our users don't use beta releases, so most people won't even see this problem.

**Comment by skymen** [comment]
Is there any solution besides clearing the cache? Any specific key I can manually remove rather than wipe the whole thing?

**Comment by DiegoScirra** [comment]
@skymen

Press **F12** to go into dev tools, go to the **Application tab**, on the left hand side, under **Storage**, look for **IndexDB**, in there look for **PresistantMap** and finally click on **keyvaluepairs**.

You should see a table in the right hand side appear which has one entry called **UI_STATE**. Right click on it and delete it. Technically only the Animations Editor UI state data is causing problems, but even though you can look at the individual data stored, you can only delete the whole entry.

**Comment by skymen** [comment]
Thanks 🙏

**Comment by XHXIAIEIN** [comment]
This can work! Thanks!
<img width="940" alt="Snipaste_2024-04-12_13-06-53" src="https://github.com/Scirra/Construct-bugs/assets/45864744/7f0fd544-2258-459c-a835-572866cb03fe">
