### ISSUE TITLE
Audio.Duration not updated if new track plays under same tag

### ISSUE THREAD

**Issue by j0schi** [Scirra/Construct-bugs#7866]
Title says it all. after the track has ended i load a new track from an external URL and play it (not looping) under the same tag as before. The problem is that Audio.Duration("tag") only returns the playbacktime from the first track loaded. The value seems to be... cached? 

Sorry for keeping it so short, i am lacking the time to do a demo file rn, might come back to it later, but at least wanned to let you know in case somebody else runs into it!

Kind regards

Updates: 
Unloading the audio does not help
Stoping the audio manually does not help
Changing the trackname does not help

Not really sure anymore if its a bug or maybe wanted: **`if you add the remote audio under a unique name the audio.duration seem to work correctly`**. I would have expected that this value is updated if the URL changes. On the other hand a caching makes quite some sense here.

**Comment by WilsonPercival** [comment]
I think it's the same as this: https://github.com/Scirra/Construct-bugs/issues/7266

**Comment by WilsonPercival** [comment]
Can not reproduce. I made a minimal project demonstrating normal operation.

[issue7866.zip](https://github.com/Scirra/Construct-bugs/files/14435462/issue7866.zip)

Steps:

1. Press `1` to play the first sound, you will see the duration `218.04`.
2. Press `2` to stop all sounds.
3. Press `3` to play the second sound, you will see the duration `186.768`.

https://github.com/Scirra/Construct-bugs/assets/91274932/38c52aaf-f4be-47e2-ac05-6b6aaa554c7d

**Comment by j0schi** [comment]
Hmm idk why this still happens but as written in my last update it only happened for me when adding it under the same tag from an external source so its a specific case :) If i find the time i will update here with a demo project.  But jea it could be the same as #7266 

Thanks for investigating, as i found the workarround its low priority for me now, i was just bashing my head as the timng witht he music is important for the project :D

**Comment by AshleyScirra** [comment]
Please always follow the bug report guidelines otherwise it's impossible for us to help.
