### ISSUE TITLE
Loading a project with bundled addons can cause a crash

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#7867]
## Problem description

When loading a project with bundled addons, if you also have that addon installed in C3, if you load the project before C3 has finished loading all of its addons, it can cause a crash

## Steps to reproduce

1. Have many addons installed (it increases the likelyhood that this issue happens)
2. Have a project with one of these addons bundled
3. Load project as soon as C3 launches

## Observed result

If the project's bundled addons are loaded before C3 has finished loading its addons, it can cause a crash with an error message like this:
`<addonName> already exists in lang file`

I assume this comes from C3 loading the installed addon after the bundled version of the addon has been loaded, and crashing because the addon is already there.

## Expected result

No crash should happen

## More details
I can't provide a repro c3p because this is not project specific, and even with a repro, this is random as it highly depends on the order of operations when things are loaded

**Affected browsers/platforms:** Tested Chrome only

**First affected release:** Has been rarely happening for as long as I've been using bundled addons

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I reviewed the editor code, and it is coded to wait for C3 to finish loading all its own addons and installed addons before it attempts to open a project, precisely to avoid this problem, as it should guarantee that bundled addons are always loaded after everything else and never before. Perhaps there is some oversight that causes a problem, but as per the usual bug report guidelines, without a repro it's generally impossible to fix, so closing.
