### ISSUE TITLE
Very Large HTML Games can't Update

### ISSUE THREAD

**Issue by Laserwolve** [Scirra/Construct-bugs#7868]
## Problem description

Very large HTML projects (export size larger than 500 MBs) can't update using the offline capability/service worker.

## Attach a .c3p

[Link to a .c3p of a very large Construct project](https://drive.google.com/file/d/1ztTh7fOrjNUOWpyFXMNtex8ukQigNdR6/view?usp=sharing) (no add-ons, no JavaScript, latest stable)
[Link to an HTML export of that project](https://drive.google.com/file/d/1R9JC6Ld2GTk7twY2jvEATGKiIoQfMHM6/view?usp=sharing) (images deduplicated, recompressed, advanced minification, using `webp` images, offline support enabled)
[Link to another HTML export of that project,](https://drive.google.com/file/d/1mlmOew35amMZ9P9Oi8_64AETpuye4HiL/view?usp=sharing) just with the version number updated so that it's different (same export settings as the previous)

## Steps to reproduce

1. Host the first HTML export on Netlify, GitHub Pages, etc.
2. Browse to whatever default domain they give you
3. Wait for the game to load
4. Wait for the offline files to cache
5. Replace the game with the 2nd HTML export
6. Refresh the tab with the game in it

## Observed result

The previous version comes up, and shows this error message:
![image](https://github.com/Scirra/Construct-bugs/assets/87336074/eaa30894-9597-47a8-acb8-a05289c26ed4)

## Expected result

The previous version should come up, but an update should be detected and start downloading the new version, and there should be no error message.

## More details

**Affected browsers/platforms:** Edge v122, Windows 11

**First affected release:** Unknown

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Edge 122.0.2365.52
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 9.7 gb (3.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002503) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by WilsonPercival** [comment]
Can not reproduce. I've uploaded your first HTML export. Then I loaded the second HTML export. Everything opens, there are no yellow messages in the console.

**Comment by Laserwolve** [comment]
@WilsonPercival, did the second HTML export properly update?

**Comment by WilsonPercival** [comment]
> @WilsonPercival, did the second HTML export properly update?

I think yes. I can't say for sure that the second version was downloaded. Notifying the version in the console would be nice.

**Comment by AshleyScirra** [comment]
Please check again with r382 - I think it should handle this better now.

**Comment by Laserwolve** [comment]
> Please check again with r382 - I think it should handle this better now.

It's working now. Thanks!
![image](https://github.com/Scirra/Construct-bugs/assets/87336074/bff8d6b9-2fa8-44a3-8d49-96ffe0c94953)

**Comment by AshleyScirra** [comment]
Thanks for confirming!
