### ISSUE TITLE
Problem with network information on cordova

### ISSUE THREAD

**Issue by creakosta** [Scirra/Construct-bugs#7870]
## Problem description
I have problem with network information plugin on cordova in my project. I build it in Monaca CLI 12.0.0 and android 12.0.1. If I add network information plugin then I recived this error in Android Studio and my app is frized on black screen:

[INFO:CONSOLE(5892)] "Uncaught (in promise) TypeError: navigator.connection.addEventListener is not a function", source: https://localhost/scripts/c3runtime.js

## Attach a .c3p

not project specific

## Steps to reproduce

1. Add network information plugin to cordova poject
2. Build and run app

## Observed result

App not loaded and freeze

## Expected result

App loaded succesfull and get network info

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
No repro has been provided, and Construct does not have any built-in "network information plugin". If you are using a third-party plugin, please report any issues to the addon developer.
