### ISSUE TITLE
import dialogs not consistently styled in dark theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7877]
## Problem description
import dialogs are not consistently styled in the dark theme

## Attach a .c3p
not project specific

## Steps to reproduce

1. open import dialogs

## Observed result
music and sound are styled correctly
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/008ff7be-96f5-4f18-97ba-1c7e06555bd8)

Videos, Fonts, Icons & Screenshots and Files are styled differently
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/7ff4640f-4b58-4487-8228-6db4b514d976)

## Expected result
all are styled like the sound and music dialog

## More details

if you are already looking at the import dialog you might also want to consider https://github.com/Scirra/Construct-feature-requests/issues/163 ;)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This appears to be a regression from way back in 2018 from fixing #1804. It should be fixed in the next beta.
