### ISSUE TITLE
PWA install from Browser plugin has no effect on iOS

### ISSUE THREAD

**Issue by Kernonen** [Scirra/Construct-bugs#7884]
PWA install has no effect on iOS

 I set up a basic app with a button to allow intallation. It works perfectly well in Android but button has no effect on ios. 
Test "+ Browser: On install available" return installation is not available when I test on iOS.

[PWA.c3p](https://www.dropbox.com/scl/fi/quyo2o0399b2zhgrrfq3q/PWA.c3p?rlkey=cvgsozeh8xuib796q7c4jpvz5&dl=0)

1. create a new document
2. add Browser plugin
3. add a button on screen to call installation

## Observed result

test preview and export/host online return same result : has effect on Android. No effect on ios
## Expected result

I expect to have the same result on iOS than on Android

Affected platform : iOS/safari

**First affected release: r382 beta
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I'm afraid Safari does not support prompting PWA install. Apple would need to add support for that. Web apps can however be installed manually by choosing the "Add to home screen" option. You should also use the 'Is install available' condition to verify that an install can be requested, as it may not always be available on Android, and it will be unavailable on Safari so the option will not appear where it is not supported. (For reference this appears to have also been posted to the forum: https://www.construct.net/en/forum/construct-3/how-do-i-8/new-pwa-plugin-ios-181195)

**Comment by Kernonen** [comment]
Thank you Ashley. So to summarise, when using this function :
- Check if installation is available, even on android
- If yes, (Android), let the PWA install do its job
- if not, check the platform the user is on (Android / iOS) and display custom install instruction for these users who are not all aware of PWA installation possibility.
