### ISSUE TITLE
Mouse overlaping detection fail bug

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-bugs#7888]
## Problem description
when using mouse overlaping on objects with touch on the same condition, the mouse is triggering if it is the second condition, but not if it is the first condition.

## Attach a .c3p
https://drive.google.com/file/d/1H8IVn98cG7WHAdL76PxlqD8Sr3yRWS14/view?usp=sharing

## Steps to reproduce

1. Run the project as is and hover the boxes
2. Return to edition, on the event sheet change the order in the or condition so touch is first and mouse is second (touch or mouse)
3. Run the project again and hover the boxes

## Observed result

When mouse is second in the or action, the event is triggering even if the mouse is not touching objects, when the mouse is first condition, it works properly normal.

## Expected result

First or second shouldn't change the result. The boxes should be big only when the mouse is over.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
It seems to me that the more fundamental mistake is that with this composition of events, actions begin to be executed even when we do not hover the mouse over the sprite. Actions stop executing when I move the cursor out of the visible area of the game space.

[issue7888.zip](https://github.com/Scirra/Construct-bugs/files/14545354/issue7888.zip)

https://github.com/Scirra/Construct-bugs/assets/91274932/a0282c96-b471-4c41-b66e-f30d58512e36

**Comment by kingpirux** [comment]
true, it will detect collision on all objects, like if the mouse is everywhere. could be a silly thing like "false or false=true"

**Comment by AshleyScirra** [comment]
The 'Is touching object' condition was coded differently to 'Cursor is over object'. I've updated the next beta to use the same code for both, which looks like it fixes the problem, so it should be working from there.

**Comment by kingpirux** [comment]
![image](https://github.com/Scirra/Construct-bugs/assets/6506303/473b6d70-cd83-4f31-ae13-b8c7d150a841)
the bug is not completly fixed if you have the window resized and have the mouse out of the layout, still detects the full contact on all the objects

> The 'Is touching object' condition was coded differently to 'Cursor is over object'. I've updated the next beta to use the same code for both, which looks like it fixes the problem, so it should be working from there.

**Comment by AshleyScirra** [comment]
@kingpirux - it is best to file a new issue if there are still problems, as comments on closed bug reports are easily missed, or may lack essential details we need for a bug report. However in this case I did identify one more problem which has been fixed for the next beta.
