### ISSUE TITLE
Align Space not working properly with Hierarchy Wrap mode

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#7892]
## Problem description

Using Align->Space feature doesn't align objects properly while using Wrap mode.

## Attach a .c3p
[New project.zip](https://github.com/Scirra/Construct-bugs/files/14569457/New.project.zip)

## Steps to reproduce

1. Shift+Click the to select the red sprites
2. Right click on any of them
3. Align -> Space -> Vertical

## Observed result

Items get messed up (i.e. wrap has no effect)

## Expected result

Items get arranged taking into account the Wrap mode (i.e. treating an object+its hierarchy as one object)

## More details

**Affected browsers/platforms:** 

**First affected release:** stable

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta for both aligning by edges and spacing.
