### ISSUE TITLE
depth writing in wgsl (reopen with another comment/question)

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-bugs#7893]
This is a reopen of #7875 with a new question / comment:

My question on whether this is a bug or feature request is if the webgpu effect render supports the direct-3d render option, do we not need to replicate the default webgpu fragment shader and do the the transparency based write depth function? If we do not do that, will our render have issues with transparency and depth?

This is the last operation of the default shader, don't we need to include that in webgpu direct-3d render options?

`			output.color = c * input.fragColor;
			${useFragDepth ? "output.fragDepth = select(input.fragPos.z, 1.0, output.color.a == 0.0);" : ""}
			return output;`

**Comment by AshleyScirra** [comment]
It's not an appropriate use of bug reports to file an issue merely to ask a question, so closing this. I will take a look at responding in the other thread.
