### ISSUE TITLE
Custom action for a family crashes the browser (Opera GX).

### ISSUE THREAD

**Issue by dupuqub** [Scirra/Construct-bugs#7894]
## Problem description

Opera crashes when adding a custom action for a family.

## Attach a .c3p

Any file should present it.

## Steps to reproduce

1. Create a sprite.
2. Create a new family with the sprite.
3. Add a custom action and name it "Change_Going_X" (something about this specific name makes it crash).

## Observed result

Opera crashes the page.

![Capture](https://github.com/Scirra/Construct-bugs/assets/34659544/38395a4a-2f92-4278-be37-a4fe6bccce48)

## Expected result

Not crashing.

## More details

**Affected browsers/platforms:**  Opera GX LVL5 (core: 107.0.5045.60)

**First affected release:**  r382

## System details

<details><summary>View details</summary>

There were no crash reports.

</details>

**Comment by AshleyScirra** [comment]
I would guess this is #7796, which is a bug in the Chromium browser engine which Opera GX uses, and they haven't updated to the fixed version (M122) yet.

Please do include your platform information in the bug report as it always helps - I don't know what version of Chromium Opera GX uses, it's hard to find online, and the platform information usually includes that information.

**Comment by dupuqub** [comment]
I thought this "Opera GX LVL5 (core: 107.0.5045.60)" was the platform information.

**Comment by WilsonPercival** [comment]
@dupuqub 
<img width="464" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/91274932/4cc5343e-6d6c-4508-affc-ab14391cd173">

**Comment by dupuqub** [comment]
damn, I forgot about it. Just edited it in the System details.
