### ISSUE TITLE
Follow behaviour: Distance warping 

### ISSUE THREAD

**Issue by brushfe** [Scirra/Construct-bugs#7898]
## Problem description

Sprites with the Follow behaviour are warping unnaturally to the follow distance once the behaviour starts following its target.

In this example, this snapping happens using "Distance" following, and a 16 pixel Delay. The target uses 8-Direction to move (I've restricted this to Left/Right movement to simplify the test). 

There are three examples of this problem:

**1. Moving to the left:**  once the target exceeds a certain number of pixels, the follower warps to its follow distance. However, with a Delay value of 16, it should've started following long before it warps. Instead, it waits until the target has moved a certain distance.

**2. Moving to the right:** once the target passes over the follower, the follower warps to the 16 pixel distance. However, it should only start following once the distance to the target is greater than/equal to 16 (or whatever the Delay value is). 

**3. Moving left & right very quickly:** After moving a certain number of pixels, the follower warps to a position underneath the target.

## Attach a .c3p

https://drive.google.com/file/d/13FAkeVTWoplJ4hnoAeyQO3E6ZXS7m0P7/view?usp=drive_link

## Steps to reproduce

1. Run the attached project.
2. Problem 1 (moving left): Hold the left arrow key until the follower warps.
3. Problem 2 (moving right): Hold the right arrow key until the target crosses over the follower (it will warp).
4. Problem 3 (moving left & right): Rapidly press the left and right arrow keys until the follower warps.

## Observed result

In all three cases, the follower warps in an unnatural way to its follow distance, regardless of the distance between itself and its target. 

## Expected result

I believe what's happening is that the follow behaviour is only tracking its own history list **after** the target has moved (Delay value) pixels. **It's not taking into account the actual distances between the objects.** 

Since the purpose of "Distance" following is to keep the follower at a certain distance, I imagine the actual distance between the objects needs to be considered. The follower shouldn't move if the target is within it's Delay range. It also shouldn't wait to follow if the target exceeds that distance.

## More details

**Affected browsers/platforms:** Chrome 122.0.6261.112, MacOS 14.3.1

**First affected release:** r382

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is just the distance equivalent of #7879. The problem is until the followed object has moved 16px, there is no data for it to follow 16px behind. Only when there is enough history recorded that it can tell where is 16px behind the object's movement is, does it then move the following object. I'm not sure what to do about this as there is no data to be followed which is why it can't move the object immediately. However as this seems to be a problem for both modes of the Follow behavior perhaps there is some other mode that can be added to solve this.

**Comment by AshleyScirra** [comment]
I've added a 'from current position' setting for the Follow action for the next beta, which I think solves this. We might need a couple more beta releases to review if this is the best way to solve the problem.

**Comment by brushfe** [comment]
Fantastic, thanks for looking into this! I'll try out the new feature as soon as I can. 

It certainly feels like 'distance' following is quite different than 'time'. You'd expect the object to follow at that distance regardless and the moment the behaviour is enabled— waiting for the target to have moved its Delay value doesn't seem relevant here (it seems more relevant to 'time').

You'd also expect it to only follow once the target is (Delay value) away, since that's the 'following' distance you've set. But maybe that's an option—some people may like the Braid/Ninja Gaiden/Time Trial Ghost style tracking, where the follower mimics your every move. Others may want the follower to only follow once the target has exceeded the Delay value. 

I'm very excited to see the next iteration! Have a great weekend!
