### ISSUE TITLE
Pasting an object onto a global layer and then trying to move it out of that global layer crashes

### ISSUE THREAD

**Issue by MethuselahConstruct** [Scirra/Construct-bugs#7901]
## Problem description

I have a global layer across multiple layouts. If you copy and paste an object into the global layer (usually on accident, not looking which layer is selected), and then select that object and change its layer to a non-global layer, construct crashes. Once it has crashed 

## Steps to reproduce

1. Copy the sprite object on layer 0 (local layer)
2. Paste the sprite object with layer 1 selected (global layer)
3. Enter the pasted sprite's properties and change its layer to layer 0, layout 1 or 2

## Observed result
https://youtu.be/KOHauUD2pqU

https://github.com/Scirra/Construct-bugs/assets/103547162/db74f996-9d30-4f10-b18a-cb9f1d1471b3

Construct crashes. Error report:
Error report information
Type: unhandled exception
File: https://editor.construct.net/r379/projectResources.js, line 1425, col 242
Message: Uncaught Error: instance not on this layer
Stack: Error: instance not on this layer at d.UCc (https://editor.construct.net/r379/projectResources.js:1425:248) at d.fub (https://editor.construct.net/r379/projectResources.js:852:48) at https://editor.construct.net/r379/components/bars/propertiesBar/propertiesBar.js:19:24 at hh (https://editor.construct.net/r379/main.js:375:99) at Kq.g.J.$ob.YW (https://editor.construct.net/r379/main.js:1560:418) at Kq.g.J.$ob.wI (https://editor.construct.net/r379/main.js:1561:71) at HTMLSelectElement.cu (https://editor.construct.net/r379/main.js:1559:343)
Construct version: r379
URL: https://editor.construct.net/
Date: Thu Mar 14 2024 15:21:45 GMT-0500 (Central Daylight Time)
Uptime: 11531.8 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Opera 107.0.5045.21
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 OPR/107.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 630 (0x0000591B) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex
## Expected result
The object moves layers without crashing.

## More details

**Affected browsers/platforms:** Happens in Chrome and Opera on Windows

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7850

Please always check the latest releases before reporting. Most likely this has already been fixed.

**Comment by MethuselahConstruct** [comment]
I searched and saw that one, but the steps to repeat were different, so I made this one.

**Comment by MethuselahConstruct** [comment]
Also I'm on 379? It's the latest stable build. I'm not messing with betas.

**Comment by DiegoScirra** [comment]
This was fixed already, but it's still only available in the beta versions.
