### ISSUE TITLE
No permission to save then crash

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7903]
![image](https://github.com/Scirra/Construct-bugs/assets/5744908/d98509ce-58f6-4100-8c0d-35a70aea2347)

Occasionally I get the "unable to save" error randomly when "save as single file", but then just saving again generally fixes the issue.

However this time I also got a crash to occur!

Obviously cannot replicate this, as it's strange combo and has never happened to me before.
But just incase the crash report is helpful:

_______________________________

Error report information
Type: unhandled rejection
Reason: Error: Failed to fetch @ TypeError: Failed to fetch
Stack: TypeError: Failed to fetch
Construct version: r383
URL: https://editor.construct.net/r383/
Date: Sat Mar 16 2024 22:48:01 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 28096.7 s

Platform information
Product: Construct 3 r383 (beta)
Browser: Chrome 122.0.6261.129
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.3499999046325684
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F03) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_shader_pixel_local_storage, WEBGL_stencil_texturing

**Comment by WilsonPercival** [comment]
I always only use `Download a copy` and I've never had any problems.

<img width="320" alt="aaa" src="https://github.com/Scirra/Construct-bugs/assets/91274932/25efc277-22bb-4a8c-9268-2ddd9f043eb6">

**Comment by AshleyScirra** [comment]
Unfortunately the crash report is not helpful in this case, and without a repro it is often impossible to act on the issue.

When you next observe this, try pressing F12 and check the browser console for any more detailed error message - if there's anything there that's all we'd have to go on.

**Comment by alastajj** [comment]
> I always only use `Download a copy` and I've never had any problems.
> 
> <img alt="aaa" width="320" src="https://private-user-images.githubusercontent.com/91274932/313403371-25efc277-22bb-4a8c-9268-2ddd9f043eb6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzAyMTAsIm5iZiI6MTcxMDkyOTkxMCwicGF0aCI6Ii85MTI3NDkzMi8zMTM0MDMzNzEtMjVlZmMyNzctMjJiYi00YThjLTkyNjgtMmRkZDlmMDQzZWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDEwMTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjOWExNjZiOTU1YWVjYTJkNTkxNGIwNDhmZmQ1M2JjNTA5OTE1MGMxNDBhY2ViNTJiODA0NDZhMjY1N2FkNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MEODby-ULAABt4fhLhE0-LG0eT4uLv0cHqxOdxTUzJ4">

that's interesting! Perhaps I could try "download a copy" instead of "save single file". Even though the bug only occurs about 0.5% of the time.

I just changed Chrome's default download directory to go to my sync'd Mega folder. I only use Chrome for C3 anyway.

Thanks!

**Comment by AshleyScirra** [comment]
As this issue is not currently actionable, closing. However if you can reproduce the issue again and find anything potentially relevant logged in the browser console when it happens, please comment again here.
