### ISSUE TITLE
Set from JSON and Tween state issue

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7905]
## Problem description

Another variation of https://github.com/Scirra/Construct-bugs/issues/7779

Just change The condition is to 'On Start of layout'. 

When the object destroyed and re-created, it does not return to the playing state.

## Attach a .c3p

[#issue7779.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14624339/issue7779.c3p.zip)

## Steps to reproduce
1. press 1 
1. press 2 

## Observed result

Animation is stop 

## Expected result

Animation continues to rotate

## More details

**Affected browsers/platforms:** 

**First affected release:** r380

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
