### ISSUE TITLE
down-scaling quality high pads out images to the next power of two size even if the texture is already power of two

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7909]
## Problem description
Down-scaling quality high pads out images to the next power of two size even if it's already power of two. Maybe this is by design but that doesn't make much sense to me as from my understand the mip-maps pixels will be aligned in both cases.
In my project I already imported most texture in power of two sizes, but due to this bug: https://github.com/Scirra/Construct-bugs/issues/7900 I enabled full screen quality high. There I noticed that textures of the size 256x256 are padded out to 512x512.
If I resize the texture to 254x254 or below it is padded to 256x256.
As I was already importing assets in power of two size my memory usage quadrupled due to this additional padding.
**This workflow seems a bit counter intuitive, if this is by design I think it should be clearly communicated in the documentation that images need to be 2 pixels smaller on each axis to be padded efficiently.**

## Attach a .c3p
[spritesheeting.zip](https://github.com/Scirra/Construct-bugs/files/14655158/spritesheeting.zip)

## Steps to reproduce

1. open the sprite-sheet view

## Observed result
2048x2048 texture is used for 16 256x256 images

## Expected result
a 1024x1024 texture would be enough

## More details
Now that I am aware of this it isn't a big problem I'll just make sure to resize all assets two pixels smaller, but it's still weird workflow wise as it's so common to create textures/sprites in power of two sizes.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
https://www.construct.net/en/tutorials/construct-3s-export-4

<img width="514" alt="image" src="https://github.com/Scirra/Construct-bugs/assets/91274932/1fbf2094-f7fd-4542-9dd7-3d5070ca1297">

**Comment by F3der1co** [comment]
I see, not the most obvious place to find that information. But that explains it!

**Comment by AshleyScirra** [comment]
This is by design: spritesheet images cannot be placed exactly adjacent, otherwise there is often obvious color bleed from adjacent images. Therefore a 1px space is mandatory, and that is added on to the image size, before it is then padded. So power-of-two sizes are actually the worst size for a spritesheet (causing the most wasted space), and two pixels less is ideal (as there is space for a 1px border either side).
