### ISSUE TITLE
ios export

### ISSUE THREAD

**Issue by mrbotts** [Scirra/Construct-bugs#7916]
Error report information
Type: unhandled exception
File: https://editor.construct.net/r379/main.js, line 1935, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at xr.g.Ei.MPa (https://editor.construct.net/r379/main.js:1935:242) at dj.g.ZBc.Dd (https://editor.construct.net/r379/main.js:1937:415) at https://editor.construct.net/r379/main.js:1937:139
Construct version: r379
URL: https://editor.construct.net/
Date: Thu Mar 21 2024 12:02:46 GMT-0700 (Pacific Daylight Time)
Uptime: 70 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 122.0.6261.129
Browser engine: Chromium
Context: browser
Operating system: macOS 14.4.0
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, ANGLE Metal Renderer: Apple M2, Unspecified Version)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_pvrtc, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise it is impossible for us to help.
