### ISSUE TITLE
template creates incorrect hierarchy if it's also in a container

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7917]
## Problem description
template creates incorrect hierarchy if it's also in a container with its children

## Attach a .c3p
[templateContainerHierarchy.zip](https://github.com/Scirra/Construct-bugs/files/14706150/templateContainerHierarchy.zip)

## Steps to reproduce

1. run preview

## Observed result
created objects child's arrow points down

## Expected result
the arrow points to the right, as it's created with the template where the child points to the right

## More details

to me it seems like creating with template incorrectly takes container object state of first instance instead of the template instance.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.
