### ISSUE TITLE
Timers not working individually

### ISSUE THREAD

**Issue by kingpirux** [Scirra/Construct-bugs#7920]
## Problem description
The timer behaviour is not working independently, only one timer is triggering at a time in the same object type.

## Attach a .c3p
https://drive.google.com/file/d/1OmwHD7r2Z4xKQENrwpHijFh2Jg_4_SfQ/view?usp=sharing

## Steps to reproduce

1. Start the project
2. Watch the numbers on the text object
3.

## Observed result
Only one timer is triggering

## Expected result
Both timers should be triggering and printing the result on the text object

## More details

This problem is not solved with On Created or using For Each object, also not working with different Tags, only one timmer is triggering.

**Affected browsers/platforms:**  Chrome

**First affected release:**  Tested with Stable and 384

**Comment by WilsonPercival** [comment]
The link you provided is not working.

**Comment by kingpirux** [comment]
sorry new link now, this should be open for everybody

**Comment by AshleyScirra** [comment]
This is indeed currently by design. See the note for 'On timer' in the [Timer behavior manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/timer).

**Comment by F3der1co** [comment]
> > This is indeed currently by design. See the note for 'On timer' in the [Timer behavior manual entry](https://www.construct.net/en/make-games/manuals/construct-3/behavior-reference/timer).
> 
> > "This is like using the system Every X seconds condition, or the system Wait action, except that times are kept for each instance individually.
> 
> this is from the entry it literally says individually, but they are triggered once for all, not individually at all and the For Each workaround DOESNT work.

you need to add the for each here:
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/7b3e0c10-8c7f-4635-b629-c075a0f29e25)
