### ISSUE TITLE
gamepad plugin has a noticible input delay

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7921]
## Problem description
The gamepad plugin introduces a rather large input delay. In main.js I implemented the gamepadAPI to compare.

## Attach a .c3p
[gamepadTest.zip](https://github.com/Scirra/Construct-bugs/files/14732889/gamepadTest.zip)

## Steps to reproduce

1. run preview
2. open console
3. press A on the gamepad

## Observed result
there is an input delay caused by the gamepad plugin, in the console you can visually see the logging of the gamepad plugin lagging behind, additionally you can see a different time is logged

## Expected result
The gamepad plugin is as fast as the gamepadAPI

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
On my system it only measures a 2ms difference in timing - much less than a single frame at 60 FPS (~16ms). However I think the design of the input handling may have added an extra frame of latency. I've adjusted the design and increased the polling rate for the next beta which should mean that gamepad input is processed as soon as possible.
