### ISSUE TITLE
Update 'World to HUD Position Template' 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7922]
## Problem description

When the ['World to HUD Position Template'](https://editor.construct.net/#open=world-to-hud-position) was published, the `LayerToLayer` expression did not exist, so it still uses the previous approach, which looks very complicated.

I recommend updating it to avoid causing confusion to others

## Attach a .c3p

https://editor.construct.net/#open=world-to-hud-position

## Steps to reproduce
1.
2.
3.

## Observed result

```
CanvasToLayerX("HUD", LayerToCanvasX("World", CoinItem.x, CoinItem.y), LayerToCanvasY("World", CoinItem.x, CoinItem.y))
```

## Expected result

```
LayerToLayerX("World", "HUD", CoinItem.X, CoinItem.Y)
```

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The example has been updated for the next beta.
