### ISSUE TITLE
flowchart: Crash when Press 'C' key

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7923]
## Problem description

Currently if the clipboard has some other pasted data it crashes when I press `C`.  Yes, only `C` instead of `Ctrl + C`.

## Attach a .c3p

any projects

## Steps to reproduce
1. Copy any content, For example, this sentence even if it has nothing to do with C3 data. 
2. Create New Project, Add Flowchart, Open the Flowchart.
3. Press 'C'

## Observed result

Crash 
```
Error report information
Type: unhandled exception
File: https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js, line 28, col 328
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'Lh')
Stack: TypeError: Cannot read properties of undefined (reading 'Lh') at qlb (https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js:28:328) at Fmb.nX (https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js:139:185) at Elb (https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js:35:217) at Array. (https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js:132:374) at window.$i.dispatchEvent (https://editor.construct.net/r385/main.js:1270:399) at Tlb (https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js:44:370) at Array. (https://editor.construct.net/r385/components/editors/flowchartView/flowchartView.js:161:276) at Tf.g.wb.Dza.dispatchEvent (https://editor.construct.net/r385/main.js:1270:399) at Tf.g.wb.Dza.Ed (https://editor.construct.net/r385/main.js:1373:16) at Esa.Ed (https://editor.construct.net/r385/main.js:1376:292)
Construct version: r385
URL: https://editor.construct.net/r385/
Date: Wed Mar 27 2024 02:37:09 GMT+0800 (中国标准时间)
Uptime: 10.8 s

Platform information
Product: Construct 3 r385 (beta)
Browser: Edge 122.0.2365.92
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex
```

## Expected result

NO Crash 

## More details

**Affected browsers/platforms:** Edge

**First affected release:** r385

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r385 (beta)
Browser: Edge 122.0.2365.92
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 192 gb
Storage usage (approx): 432 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment]
Both issues will be fixed in the next beta. Cut, copy and paste shortcuts where not taking into account the modifier keys.
