### ISSUE TITLE
Loading a Parent's State from JSON after Destroying its Children makes the Children Behave Unexpectedly 

### ISSUE THREAD

**Issue by CodyRockwell** [Scirra/Construct-bugs#7925]
## Problem description

When you save a hierarchy parent's state as a JSON after destroying one or more of its children, and then load the parent's state from that JSON after restarting the layout, any children that are part of the hierarchy can behave strangely. 

## Attach a .c3p

https://drive.google.com/file/d/15gQ-93AD6K5rdUOFmKzjVQEdrrctd9WF/view?usp=drive_link

## Steps to reproduce

1. Click one of the children to destroy them. 
2. Save the parent's state as JSON by clicking the "AsJSON" button.
3. Restart the layout by clicking the "Restart Layout" button. This will load the parent's state from the JSON on restarting of the layout.
4. If you destroyed the white child, nothing strange will have happened
5. If you destroyed the red child or both children, the hierarchy will be messed up

## Observed result

When the red child is destroyed and then the layout is restarted and the parent's state is set from JSON, the red sprite is repositioned to the position relative to the parent where the white child is supposed be. The white sprite is also removed as a child of the parent, while the red sprite becomes a child of the parent instead.

When both children are destroyed and then the layout is restarted and the parent's state is set to the JSON, both of the children are destroyed.

## Expected result

Restarting the layout and then loading the parent's state from the JSON should restore the hierarchy to the state it was when the parent's state was first set to a JSON. That is, if any of the children were destroyed prior to setting the JSON, they should not be included in the hierarchy (though my understanding is that they should still be present in the restarted layout). 

Previously destroyed children should not take the position in the hierarchy of those that were unchanged at the time of setting the JSON data.

## More details

**Affected browsers/platforms:** 

Chrome

Stable r379 and beta r385

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 123.0.6312.58
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 2.1 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002487) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by WilsonPercival** [comment]
The link you provided is not working.

**Comment by CodyRockwell** [comment]
> The link you provided is not working.

My apologies. It should work now

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta. All three cases mentioned should produce the expected result.
