### ISSUE TITLE
Typos in descriptions (pt.3)

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#7929]
**1.** ![1](https://github.com/Scirra/Construct-bugs/assets/59319082/00f0e51b-4db1-4303-9451-158fd12dc846)
**2.** ![2](https://github.com/Scirra/Construct-bugs/assets/59319082/01960015-071f-4bb2-8eb8-aa9c5df32e09)
**3.** ![3](https://github.com/Scirra/Construct-bugs/assets/59319082/c530a736-9b59-4810-9364-b1825ac79d48)
**4.** ![4](https://github.com/Scirra/Construct-bugs/assets/59319082/066a3ea5-6608-4db7-b90f-bbc1ef2702c1)
**5.** ![5](https://github.com/Scirra/Construct-bugs/assets/59319082/49414798-ea9f-47da-b7df-3ff39c8f047e)
**6.** ![6](https://github.com/Scirra/Construct-bugs/assets/59319082/f4600a28-d6e2-4d78-b779-eac0ed6f3125)
**7.** ![7](https://github.com/Scirra/Construct-bugs/assets/59319082/37fc8237-2a05-4728-8f11-865addb2da6a)
**8.** ![8](https://github.com/Scirra/Construct-bugs/assets/59319082/e3b75d4c-ee3c-40a5-b7af-69f9058c2ec9)
**9.** ![9](https://github.com/Scirra/Construct-bugs/assets/59319082/177d95fe-36aa-4e8e-b639-3308e81d4e5a)
**10.** ![10](https://github.com/Scirra/Construct-bugs/assets/59319082/f8379e4d-b114-4944-8e04-d0a6ba605dd3)
**11.** ![11](https://github.com/Scirra/Construct-bugs/assets/59319082/db100dc1-ba88-409b-82a7-ec9a1d59de60)
**12.** ![12](https://github.com/Scirra/Construct-bugs/assets/59319082/d0ad5223-e2b5-4f86-bf0f-50d6195bac1c)
**13.** ![13](https://github.com/Scirra/Construct-bugs/assets/59319082/5a5fa049-16a2-4106-bf73-bea4833bb2cf)
**14.** ![14](https://github.com/Scirra/Construct-bugs/assets/59319082/313a031d-bef0-4a34-8b44-ac38a18cb7af)
**15.** ![15](https://github.com/Scirra/Construct-bugs/assets/59319082/f9fce336-643b-42e3-8593-65bceccdb6ac)
**16.** ![16](https://github.com/Scirra/Construct-bugs/assets/59319082/331e9db0-d812-4dde-b8c4-d96aa371e349)
**17.** ![17](https://github.com/Scirra/Construct-bugs/assets/59319082/5875b907-21a1-48e8-b137-2406dba13fe8)
**18.** ![18](https://github.com/Scirra/Construct-bugs/assets/59319082/2bbbbcbe-4e62-4609-842e-cb67d01284c5)
**19.** ![19](https://github.com/Scirra/Construct-bugs/assets/59319082/603b5590-67dd-4bbb-a363-f65c52de6b40)
**20.** ![20](https://github.com/Scirra/Construct-bugs/assets/59319082/8c6a35cb-286d-4eb5-a9eb-c9526d3ef367)
**21.** ![21](https://github.com/Scirra/Construct-bugs/assets/59319082/27fa3edf-23e5-4d02-bb32-570daf413562)

## Additional typos (in several strings)

_dimentions_ → `dimensions`
_anti clockwise_ → `anti-clockwise`
_Ommit_ → `Omit`
_This is an editor only property._ → `This is an editor-only property.`
_a HTML (element/string/layer)_ → `an HTML (element/string/layer)`

**Comment by F3der1co** [comment]
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/c2f36671-1f3f-4e8f-8615-371bcabfdbba)

**Comment by AshleyScirra** [comment]
Thanks, most of these should be fixed in the next beta (except for a couple of cases where I used different language or deemed the existing language acceptable).
