### ISSUE TITLE
Broken save/load in r386 - sceneGraph children

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-bugs#7933]
## Problem description

Save/load broke in r386, loading the project and save file with r385 works well.

## Attach a .c3p

[saveBug.zip](https://github.com/Scirra/Construct-bugs/files/14845902/saveBug.zip)

## Steps to reproduce

1. Preview.
2. Press "save".
3. Press "Load" twice! (in my big project it happens on the first load of a second preview, but here it only happens on the 2nd load)

## Observed result

Crash with console error

## Expected result

No crash.

## More details

**Affected browsers/platforms:** Tested only on Chrome

**First affected release:** worked in r385 but broke in r386

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
If you don't provide the project file and reproduction steps, it won't be possible to help.

**Comment by avishaymizrav** [comment]
> If you don't provide the project file and reproduction steps, it won't be possible to help.

I know that, I tried for hours to figure it out with no luck.
Eventually I managed to create a minimal project, so I updated the report.

**Comment by DiegoScirra** [comment]
Was introduced in **r386** from fixing #7925. Both problems will be fixed in the next beta.
