### ISSUE TITLE
3DShape is invisible for Nearest sampling

### ISSUE THREAD

**Issue by MrAlexSmr** [Scirra/Construct-bugs#7937]
## Problem description

3DShape is not shown or invisible on run of the project if "nearest" sampling is enabled.

## Attach a .c3p

[3dShapeNearest.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14894679/3dShapeNearest.c3p.zip)

## Steps to reproduce

1. Add a bunch of default 3DShapes
2. Check "nearest" sampling
3. Run

## Observed result

Empty screen is shown

## Expected result

A bunch of 3DShapes should be visible

## More details

Choosing any other sampling mode will solve the issue.

**Affected browsers/platforms:**

Safari 17.4.1 (19618.1.15.11.14)

**First affected release:**

r379 stable

## System details

MacOS Sonoma 14.4.1 (23E224)

**Comment by WilsonPercival** [comment]
Can not reproduce.

**Comment by MrAlexSmr** [comment]
[recording.mp4.zip](https://github.com/Scirra/Construct-bugs/files/14895882/recording.mp4.zip)

Just in case, here is the recording of my screen where I can reproduce it.
I can only assume this issue may be very narrow platform-specific or smth like that.
