### ISSUE TITLE
Unable to make sprite/edit current sprite

### ISSUE THREAD

**Issue by momerathsx** [Scirra/Construct-bugs#7939]
## Problem description

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Da') @ TypeError: Cannot read properties of undefined (reading 'Da') at Tz.b_.Da (https://editor.construct.net/r379/projectResources.js:2258:155) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2123:207) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2128:410) at sy.g.J.fc.UP (https://editor.construct.net/r379/projectResources.js:2118:106) at https://editor.construct.net/r379/projectResources.js:2114:473 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: TypeError: Cannot read properties of undefined (reading 'Da') at Tz.b_.Da (https://editor.construct.net/r379/projectResources.js:2258:155) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2123:207) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2128:410) at sy.g.J.fc.UP (https://editor.construct.net/r379/projectResources.js:2118:106) at https://editor.construct.net/r379/projectResources.js:2114:473 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/?startTour
Date: Mon Apr 08 2024 06:59:41 GMT+0100 (British Summer Time)
Uptime: 23.1 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 123.0.6312.106
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER (0x000021C4) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex

## Steps to reproduce

1. Click on pre-made sprite to edit/ or create new sprite
2.system crashes
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'Da') @ TypeError: Cannot read properties of undefined (reading 'Da') at Tz.b_.Da (https://editor.construct.net/r379/projectResources.js:2258:155) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2123:207) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2128:410) at sy.g.J.fc.UP (https://editor.construct.net/r379/projectResources.js:2118:106) at https://editor.construct.net/r379/projectResources.js:2114:473 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Stack: TypeError: Cannot read properties of undefined (reading 'Da') at Tz.b_.Da (https://editor.construct.net/r379/projectResources.js:2258:155) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2123:207) at Q5a.Q2b.Da (https://editor.construct.net/r379/projectResources.js:2128:410) at sy.g.J.fc.UP (https://editor.construct.net/r379/projectResources.js:2118:106) at https://editor.construct.net/r379/projectResources.js:2114:473 at async window.bpb.ld (https://editor.construct.net/r379/main.js:2984:436)
Construct version: r379
URL: https://editor.construct.net/?startTour
Date: Mon Apr 08 2024 06:59:41 GMT+0100 (British Summer Time)
Uptime: 23.1 s

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 123.0.6312.106
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1660 SUPER (0x000021C4) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex

</details>

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7865

**Comment by DiegoScirra** [comment]
Closing. Take a look at #7865 for an explanation of what is happening and how to get around it.
