### ISSUE TITLE
iOS + Safari (iPad) ignores the specified device orientation

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7942]
## Problem description

I'm using remote preview to test a project. I've set it to go to fullscreen on a tap. On android the screen will then automatically rotate into the specified orientation (e.g. I'm holding the phone in portrait, the game will rotate into landscape when going fullscreen).

iOS however ignores this completely. The screen rotates whenever I rotate the device, behaving as if I'd chosen device orientation "any"

## Attach a .c3p

[iosdeviceorient.c3p.zip](https://github.com/Scirra/Construct-bugs/files/14937394/iosdeviceorient.c3p.zip)

## Steps to reproduce

1. Remote preview game on iOS + Safari
2. Hold device in portrait mode (the game is set to landscape)
3. Tap screen to go fullscreen

## Observed result

The game does not go into landscape. You can turn the device to make it go into landscape but it will rotate back when the device rotated. Basically it behaves like "device orientation any"

## Expected result

To work like it does on android, with the game automatically rotated into landscape (and "stuck" there)

## More details
I tried using browser lock orientation, doesn't help.
iPad 7th generation, iPadOS 17.4.1

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r386 (beta)
Browser: Chrome 123.0.6312.106
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 14 gb (2.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4080 (0x00002704) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
I'm afraid at the moment Safari does not support locking screen orientation, so there is no way for web content to lock orientation, even when in fullscreen mode. Chrome for Android does support screen orientation lock which is why it works there. As Construct is already coded to use screen orientation lock, then it should start working as soon as a version of Safari that supports it is released.

**Comment by Wackytoaster** [comment]
Apple doing apple things again I see. Thanks for the info!
