### ISSUE TITLE
Highlighting / scrolling issues on mobile

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#7943]
## Problem description

https://github.com/Scirra/Construct-bugs/assets/59319082/15b733b3-3e38-4b92-b914-618efbfe42bb

https://github.com/Scirra/Construct-bugs/assets/59319082/8d1b62af-1590-4094-8e30-3ec24f401061

https://github.com/Scirra/Construct-bugs/assets/59319082/30c43ec7-aeed-48b6-b89e-755e60e2e316

https://github.com/Scirra/Construct-bugs/assets/59319082/d544b2f3-b503-4f47-9ee2-1d903f9a6e39

https://github.com/Scirra/Construct-bugs/assets/59319082/711bb4ad-a832-46b5-a26f-48828f929dd7

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r386 (beta)
Browser: Firefox 123.0
Browser engine: Gecko
Context: browser
Operating system: Android 10
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Android 10; Mobile; rv:123.0) Gecko/123.0 Firefox/123.0
Language setting: en-US

Local storage
Storage quota (approx): 5.2 gb
Storage usage (approx): 22 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Rendering multiple on-screen Layout Views is slow in Firefox due to bug 1163426
The Clipboard API is not supported. Some clipboard features may be unavailable.
Determining input device capabilities is not supported.

WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: ARM
Renderer: Mali-G51, or similar
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_float_blend
OES_draw_buffers_indexed
OVR_multiview2
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context

Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers

Supported decode formats:
WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)

Supported encode formats:
WebM Opus (audio/webm;codecs=opus)

Video information
Supported decode formats:
WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:
WebM VP8 (video/webm;codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines with every report. We do not normally accept reports that consist only of videos.
