### ISSUE TITLE
Mouse addon stopped working

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#7946]
## Problem description

Why doesn't the mouse work?

![image](https://github.com/Scirra/Construct-bugs/assets/5744908/8636a62e-1a50-403a-98ed-5ad2135f8949)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
🤨
