### ISSUE TITLE
Tilemap drawing + spacebar scrolling

### ISSUE THREAD

**Issue by avishaymizrav** [Scirra/Construct-bugs#7948]
If you try scrolling the editor viewport by holding spacebar while drawing with any of the tilemap tools, the tool will continue drawing after the mouse button is released.

This is not a cp3 specific case, just add a tilemap to any project and try it.

## Steps to reproduce

1. Add tilemap object.
2. Select any drawing tool.
3. Start drawing.
4. Hold spacebar to move the viewport.
5. Release the mouse button.
6. Move the mouse around.

## Observed result

The tool keeps drawing even though the button is not down.

## Expected result

The tool should stop drawing.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
