### ISSUE TITLE
Object properties are clipped with ...

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7951]
## Problem description

The Template Name and instance variables are clipped with ... and do not show the full text when scrolled through with a mouse that can do horizontal scrolling or a trackpad. 

This is a hinderance because they now need to be clicked to show the full text, the click must happen before anything (if you click when you reach the end of the scrolling any click will reset the horizontal scrolling back to the left side), and the selected text is white on a dark theme which is still unacceptable for 2024 and was reported a long time ago (first in construct3.ideas and then it was ported by xhxiaiein to the git suggestions https://github.com/Scirra/Construct-feature-requests/issues/61)

![Gif 1](https://github.com/Scirra/Construct-bugs/assets/7268697/b88877d4-5dbe-4a4d-96e6-9dcda5e0dcd1)

![image](https://github.com/Scirra/Construct-bugs/assets/7268697/af4f068d-06c6-437a-8081-8bd6aa661339)

An example showing the issue which appears when I need to find some specific template from my UI bank layout.
<img width="1680" alt="Screenshot 2024-04-19 at 10 08 49" src="https://github.com/Scirra/Construct-bugs/assets/7268697/f0c379c9-b365-43c6-aed5-4c78bc54a62d">

I could resize it but look how much space it would take from my laptop's screen:
<img width="1680" alt="Screenshot 2024-04-19 at 10 14 12" src="https://github.com/Scirra/Construct-bugs/assets/7268697/6cc43cd0-6f9f-405b-a141-418c9445dcca">

This mouse that I bought for this reason, is now mostly an expensive basic mouse.

![image](https://github.com/Scirra/Construct-bugs/assets/7268697/630df78f-1415-4978-8ab5-b12a22652ae2)

I understand the need to put "..." where the text in the input box is bigger than the box but this is a very poor solution. 

A solution would be to have this new feature under settings so users can decide for themselves.
Another one would be for the full string to trigger on a scrolling event (similar how it expands when you expand the panel). and to resume to the trimmed ... one when not scrolling and scrolling is 0 (to avoid it resuming if the user scrolled to see the last bit and clicked away)

## Steps to reproduce

1.
2.
3.

## Observed result
The string in the instance var and Template name (maybe others too) are trimmed to fit the input field and end with "..." if they are too long.

## Expected result
I expect to scroll through any field and see the full string, not a trimmed down version.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r369, in r358 it wasn't like this

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 123.0.6312.123
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 2.1 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
This appears to actually be a bug in Chrome. It should show more text in the input field when you horizontally scroll it, but the bug in the handling of text-overflow: ellipsis means it incorrectly truncates text past the ellipsis in that case.

There appears to be an existing Chrome issue filed several years ago, but it's had some activity more recently. I added a comment here to try to draw some further attention to it: https://issues.chromium.org/issues/41245282

**Comment by JeFawk** [comment]
Thank you. I tested now with Firefox and that behavior is really good as it shows the text when scrolled and resumes to ... when not. Ill comment on the chromium issue as well.
