### ISSUE TITLE
"On 0 touch end" is triggered when touching the HTML object

### ISSUE THREAD

**Issue by janfredslund** [Scirra/Construct-bugs#7952]
## Problem description
When you touch the HTML-element, it triggers "On 0 touch start". But then strange things happen:
- On Android: The "On 0 touch end" is immediately triggered.
- On iOS: The "On 0 touch end" is triggered if the HTML element has scrolling, otherwise not.

## Attach a .c3p
[touchbug.zip](https://github.com/Scirra/Construct-bugs/files/15043199/touchbug.zip)

## Steps to reproduce
On an iOS device
Run the project and drag the HTML-element. The "On 0 touch start" triggers when you start touching the element, but if you drag up- or downwards the "On 0 touch end" triggers. If you disable the CSS style in line 1 you will see that "On 0 touch end" doesn't trigger while dragging.

On an Android device
Run the project and drag the HTML-element. The "On 0 touch start" triggers when you start touching the element, but immediately thereafter the "On 0 touch end" is triggered. The CSS style in line 1 doesn't matter here.

## Observed result
On Android the "On 0 touch end" is triggered when touching the HTML object.
On iOS the "On 0 touch end" is triggered when touching the HTML object AND the HTML object has scrolling enabled.

## Expected result
I would expect that "On 0 touch end" only triggered when you actually ended the touch.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 123.0.6312.123
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 142 gb
Storage usage (approx): 246 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 620 (0x00005917) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
I believe this is the normal handling of touch input for browsers. What is happening is when you first touch, it fires a touch start event. However if you move the touch vertically enough and it determines that your intent is to scroll the HTML element, then it cancels the touch (causing a touch end event in Construct) and switches over to a scrolling gesture for the HTML element. However if you move the touch horizontally, so long as it does not deem it to be an attempt to scroll the HTML element it allows the touch to continue to be handled by Construct, resulting in movement with the Drag & Drop behavior.

In this case I'd recommend adding the style `touch-action: pan-y` to the HTML element, which seems to help make it a bit more consistent, as it tells the browser the only intended touch gesture allowed for the HTML element is vertical scrolling. See: https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action
