### ISSUE TITLE
Spawn object is missing the template name option

### ISSUE THREAD

**Issue by TackerTacker** [Scirra/Construct-bugs#7956]
## Problem description

The Create Object action has a template name option

![image](https://github.com/Scirra/Construct-bugs/assets/18266300/af5e8b7d-6c3f-46d6-85da-87824d4d719f)

while the Spawn Object action doesn't have that option

![image](https://github.com/Scirra/Construct-bugs/assets/18266300/0cdcb30f-4970-49e4-a9ed-f20c04344207)

## Attach a .c3p

[spawn_object_missing_template_option_01.zip](https://github.com/Scirra/Construct-bugs/files/15051198/spawn_object_missing_template_option_01.zip)

## Steps to reproduce

1. Open the project and run it. All the stick figures are the same because I can't specify a template name.
2. Disable the Spawn Object action and enable the loop and Create Object action. 
3. Run the project again. The stick figures are mixed now because I can specify a template name.

## Observed result

I can only use templates with the Create Object action.

## Expected result

I would like to use templates with the Spawn Object action.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I guess it's an oversight - assigning to @DiegoScirra to add.

**Comment by DiegoScirra** [comment]
Will be added to the next beta.

Since **Spawn** applies the angle of the original to the new instance, that one property will not be taken from the template.
