### ISSUE TITLE
Update 'Text formatting' example

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7959]
## Problem description

add new bbcode usage into 'Text formatting' example
- `[stock]` 
- `[outlineback]`
- `[lineThickness]` 

```
[size=20][stroke]stroke text[/stroke][/size]

[size=20][outlineback=#FF0000]Outlined text[/outlineback][/size]
[size=20][color=yellow][lineThickness=2][outlineback=#FF0000]Outlined text and filled text[/outlineback][/lineThickness][/color][/size]
```

Of course, it would be better if we could continue to add more in this case.
- [icon=tag]
- [iconoffsety=50%]
- [tag=mytag]
- [insert]

when RTL languages are supported, [but some people may not have discovered this feature](https://www.construct.net/en/forum/construct-3/how-do-i-8/support-rtl-language-display-181619#forumPost1106426). So the use of [insert] also helps remind people

## Attach a .c3p

https://editor.construct.net/#open=text-formatting

## Steps to reproduce

1.
2.
3.

## Expected result

<img width="602" alt="Snipaste_2024-04-22_20-26-49" src="https://github.com/Scirra/Construct-bugs/assets/45864744/4f1a63b3-be28-4998-909f-adfccce16dcd">

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is not a bug, just a request to change an example project. I don't think such things should generally be filed as bugs, the feature request tracker is probably a better place for them.

In this case the 'Text formatting' example isn't meant to be a comprehensive reference of BBcode - that's what the manual is for. It's just an example of some of the stuff you can do with BBcode. There is a [separate example](https://editor.construct.net/#open=icons-in-text) covering icons in text.

**Comment by XHXIAIEIN** [comment]
There are several main reasons:
1. BBCODE is missing hyperlink to the document in the editor. https://github.com/Scirra/Construct-feature-requests/issues/35

2. Sometimes it is more helpful to provide an example than to read the documentation, because it can directly see the preview. 

Also, you can add a link to the documentation in this example, so people can open it to see the more.
