### ISSUE TITLE
Unknown Bug (Android/Mobile)

### ISSUE THREAD

**Issue by epic20** [Scirra/Construct-bugs#7960]
## Problem description

There's bugs on some devices that shows black screen on gameplay or opacity being flashy or 100%
which were not supposed to be like that. It works normally on my phone but I got reports that they have the bug.

## Attach a .c3p
https://drive.google.com/file/d/1xWMUx0Hi8XmEPXLQ7B0rn9X4VZ4ML8rd/view?usp=sharing
(Couldn't attach it because it was over 100mb so I use drive instead)

## More details

https://github.com/Scirra/Construct-bugs/assets/156667387/33c011cd-35f9-4fd0-9d1b-d3d442b42b65

https://github.com/Scirra/Construct-bugs/assets/156667387/5d91eab9-d295-415d-85dd-174ae3462439

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7315

**Comment by AshleyScirra** [comment]
@epic20 - does the problem go away if you change the project compositing mode to 'Standard'?

**Comment by epic20** [comment]
The same person that reported the issue still found the same problem after turning the compositing mode to Standard.

**Comment by epic20** [comment]
The footage
https://github.com/Scirra/Construct-bugs/assets/156667387/8e32e586-949b-4691-be61-f8faea1265a1

**Comment by epic20** [comment]
> @epic20 - does the problem go away if you change the project compositing mode to 'Standard'?

Today I turned everything back to default in the project properties and someone said they work fine now,. but I still don't know what actually made it happen,

**Comment by epic20** [comment]
In the new construct r388 version, I changed the compositing mode to standard again and everything is normal now.
