### ISSUE TITLE
Deactivating the Steam Overlay creates a ghosting effect when running a game with full-screen, letterbox scaling at a non-native resolution

### ISSUE THREAD

**Issue by Kabloop** [Scirra/Construct-bugs#7964]
## Problem description

Running a Construct 3 game with letterbox scaling, in full-screen mode, at a non-native resolution (ie, game is 16:9, and your monitor is at 14:9) and then activating and deactivating the Steam Overlay will create a "ghosting" effect, with the Steam overlay not disappearing.

## Attach a .c3p

[SteamOverlayGhosting.zip](https://github.com/Scirra/Construct-bugs/files/15092510/SteamOverlayGhosting.zip)

## Steps to reproduce

1. Export project for Steam
2. Add nw.exe as a "non-steam game"
3. Run the game through steam at a non-16:9 resolution (for example, 1400x900)
4. The game will automatically go full screen on load up.
5. Enable and disable the Steam overlay to create a ghosting effect.

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/167975040/46d2cf1b-e77c-469d-be1d-1a151897f14b)

## Expected result

The Steam Overlay should disappear completely.

## More details

If the user alt-tabs from the game after deactivating the Steam Overlay and then returns to it, the Steam Overlay will have disappeared completely (as it should be), resolving the issue.

Refresh letterbox does nothing, this file was obtained from https://github.com/Scirra/Construct-bugs/issues/6348 as the two issues could be related.

**Affected browsers/platforms:** Chromium/Steam

**First affected release:** First affected release: Never worked

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r379 (stable)
Browser: Chrome 124.0.6367.60
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 558 gb
Storage usage (approx): 8.2 gb (1.5%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 (0x00001C81) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
Really Valve needs to fix the underlying problem here - we already had a workaround for this but it stopped working for some reason. I've updated the workaround for the next beta, and that'll probably break in future again when something else changes, until Valve fix the underlying issue. So I'd recommend filing such issues with Valve as well.
