### ISSUE TITLE
IOS - Top ad banner displayed behind the notch (and status bar).

### ISSUE THREAD

**Issue by LapinChat** [Scirra/Construct-bugs#7966]
## Problem description

When displaying top ad banner with the official Admob plugin, the ad is shown behind the notch (and status bar).

## Attach a .c3p

No need.

## Steps to reproduce

1. Create yourself an empty project.
2. Request and show a banner ad a the top
3. Export an xcode project.
4. Try it on an iPhone with a notch

## Observed result

Screeshot:
![ad_screenshot](https://github.com/Scirra/Construct-bugs/assets/780392/686237d3-d8dd-4b40-b439-337b1c1219a5)

Modified screenshot to show what it looks like with a notch:
![ad_screenshot_with_ADDED_NOTCH](https://github.com/Scirra/Construct-bugs/assets/780392/4d8a6997-1166-4d21-a432-58f73ceee232)

## Expected result

Top ad banner displayed below the notch and the status bar.

## More details

**Affected browsers/platforms:** 
iOS (Tested on an iPhone 14)

**First affected release:** 

Don't know if it worked before.
Currently using  r388

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388 (stable)
Browser: Chrome 124.0.6367.62
Browser engine: Chromium
Context: webapp
Operating system: macOS 14.4.1
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 2
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 140 gb
Storage usage (approx): 1.5 gb (1.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel Inc.)
Renderer: ANGLE (Intel Inc., Intel(R) UHD Graphics 617, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 255.875
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by fredriksthlm** [comment]
There is a setting for offset in the plugin which you can expose in the C3 plugin @DiegoScirra , then people can modify their position manually based on different setups

**Comment by DiegoScirra** [comment]
We won't update until there is a new stable version. The newest versions are still labelled as alpha.

**Comment by LapinChat** [comment]
While waiting for a fix, is there a temporary solution I can apply on my side? Something that will help me publish my game with ads as soon as possible.

**Comment by DiegoScirra** [comment]
You could try putting the banner in the bottom instead of the top.

**Comment by LapinChat** [comment]
No, it is not possible. Doing this requires to change the layout of the game. It's currently too late for this. Everything is fine the way my game is working. I only need this banner ad to display at the right position, on top of the screen.

I was hoping for something more "hacky' like modifying the xcode project directly. Maybe you can point me in the right direction? I guess I'll have to dig in the project files myself in hope of finding somethings...

**Comment by fredriksthlm** [comment]
@DiegoScirra can't you just expose the offset setting, it is already there in the plugin

**Comment by DiegoScirra** [comment]
@fredriksthlm

Yes, I could do that. I was just commenting with something that would not require waiting for me to finish doing anything.

Unfortunately this feature is not particularly easy to work with, in fact it is quite awkward, painful even.

First off, all our test accounts have been shut down for inactivity. I also need to bootup Android Studio and/or XCode to at least test changes in the simulator. I basically need to re-learn everything each time I have to use either of those because there is always some weird error about something missing somewhere. Since our accounts where shutdown, if I actually wanted to test this in a real device I would need to wait for a new application to be verified which I have no idea how long it takes anymore.

@LapinChat

Since you mentioned hacking, I am looking at an exported project in Android Studio now, to see what could be added manually.

**Comment by DiegoScirra** [comment]
Ok, so I took at look at an exported xCode project, (not minified of course).

In the folder **www/scripts** look for the file **main.js** which is all the Javascript concatenated into a single file.

In **main.js** search for **class C3BannerAd**. Once you find that, scroll a little bit below to find the class method **Load**, in there there is an object which has all the options that are sent to a banner to create it. In all the things sent there is an **"offset"** property which is always set to 0, a bigger number will offset the banner down. After making the change, build the project.

**Comment by LapinChat** [comment]
@DiegoScirra 
It's working for now. Thanks for this temporary solution.

I took a look around the project files. I believe this problem as something to do with the safe area of the storyboard layout. Maybe look at AMBHelper class in /Plugins/AMBCore.swift . I'm not a swift programmer (maybe in the future... who knows).

Since we can only export for ios 13+, I think Scirra should update the ios project template accordingly.

I cannot put any more of my free time in this investigation.

Thanks for your help and I'll look forward a real fix. In the meantime I'll use the temporary working solution you provided.

**Comment by DiegoScirra** [comment]
The correct way of fixing this would be to come up with a small Cordova plugin that returns the size of the notch in both Android and iOS and then use that value to offset the banner. I am a little bit surprised that such a plugin doesn't already exist.

**Comment by DiegoScirra** [comment]
The next beta will add an 'offset' parameter to the 'Create banner advert' action.
