### ISSUE TITLE
Dragging objects in the editor with Shift key down loses object selection

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7972]
## Problem description

Using the Shift key to drag on the X/Y axis or at 45 degrees causes the object to lose selection once the dragging stops.

![Drag bug](https://github.com/Scirra/Construct-bugs/assets/7268697/53607ee2-63dd-463e-b9ba-011dc2bc7ca8)

Real Case
![image](https://github.com/Scirra/Construct-bugs/assets/7268697/9a758f78-414b-4299-8a00-7b006329b827)

## Attach a .c3p

[Drag bug.zip](https://github.com/Scirra/Construct-bugs/files/15141237/Drag.bug.zip)

## Steps to reproduce

1. Select an object or a group
2. Hold the Shift key
3. Hold the mouse button down on them to start dragging
4. Drag them
5. When they are in the desired position, stop holding down the mouse button

## Observed result

Notice the selected object, or one object out of the group where you started dragging from is deselected. This makes small adjustments harder than needed with having to select the object again, which is a big problem when there are tens of objects such as in the image above under Real Case.

If the Shift button is released before the mouse button, this issue is avoided but then the objects move a bit due to the axis not being locked.

## Expected result

I expect the objects to remain selected still even after I stop dragging and I'm not holding down the mouse button.

## More details

**Affected browsers/platforms:** Latest Chrome on Windows 10

**First affected release:** This issue is for as long as I can remember it, at least 2 years old.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.62
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 2 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
