### ISSUE TITLE
HTML5 iOS 17.4.1 UserMedia (camera) not working (PWA or browser)

### ISSUE THREAD

**Issue by andygilbert29** [Scirra/Construct-bugs#7974]
## Problem description

I have the latest iOS17 (17.4.1) on my phone and a previous PWA I had installed that opened the camera up using the UserMedia no longer works, just shows a black area. I have tried re-exporting using the latest C3 stable but to no avail.

I have also tried a new project (attached) to no avail.

## Attach a .c3p

[cam_test.zip](https://github.com/Scirra/Construct-bugs/files/15161517/cam_test.zip)

## Steps to reproduce

1. Export as HTML5.
2. Load using iOS 17 ( 17.4.1) in browser.
3. Save to homepage and open.

## Observed result

Black area where camera should be.

## Expected result

The camera to show up.

## More details

**Affected browsers/platforms:** 

iOS 17 as HTML5

![IMG_0575](https://github.com/Scirra/Construct-bugs/assets/56633336/2de6ba3d-2067-4752-8879-759d1767a199)

**Comment by andygilbert29** [comment]
Yes, although I have had it crash (or freeze) in Safari browser too, but generally appears to be working OK in Safari but fails when installed to home screen (vital to my app).

**Comment by AshleyScirra** [comment]
I'm afraid that is likely to be an issue with Safari rather than Construct, as it is running the same code in both cases. In this case I would advise reporting it directly to Apple at: https://bugs.webkit.org/
