### ISSUE TITLE
r389 undo crash with hierarchies

### ISSUE THREAD

**Issue by Wackytoaster** [Scirra/Construct-bugs#7976]
## Problem description

Crash when undo

## Attach a .c3p

[undocrash.c3p.zip](https://github.com/Scirra/Construct-bugs/files/15165781/undocrash.c3p.zip)

## Steps to reproduce

1. Add red sprite as child to blue sprite (replica)
2. Delete blue sprite from template
3. Ctrl+Z twice

## Observed result

Crash

## Expected result

🧊 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: cannot set deleted instance's UID @ Error: cannot set deleted instance's UID at d.ncc (https://editor.construct.net/r389/projectResources.js:834:231) at d.acc (https://editor.construct.net/r389/projectResources.js:844:293) at d.za (https://editor.construct.net/r389/projectResources.js:904:9) at X2a.Oj.Ve (https://editor.construct.net/r389/projectResources.js:2033:314) at PL.KS.Ve (https://editor.construct.net/r389/projectResources.js:2019:408) at window.vc.gi (https://editor.construct.net/r389/projectResources.js:2023:319) at d.gi (https://editor.construct.net/r389/projectResources.js:1884:111) at https://editor.construct.net/r389/main.js:2992:95 at window.xqb.gi (https://editor.construct.net/r389/main.js:2992:146)
Stack: Error: cannot set deleted instance's UID at d.ncc (https://editor.construct.net/r389/projectResources.js:834:231) at d.acc (https://editor.construct.net/r389/projectResources.js:844:293) at d.za (https://editor.construct.net/r389/projectResources.js:904:9) at X2a.Oj.Ve (https://editor.construct.net/r389/projectResources.js:2033:314) at PL.KS.Ve (https://editor.construct.net/r389/projectResources.js:2019:408) at window.vc.gi (https://editor.construct.net/r389/projectResources.js:2023:319) at d.gi (https://editor.construct.net/r389/projectResources.js:1884:111) at https://editor.construct.net/r389/main.js:2992:95 at window.xqb.gi (https://editor.construct.net/r389/main.js:2992:146)
Construct version: r389
URL: https://editor.construct.net/r389/
Date: Tue Apr 30 2024 16:19:35 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 59.7 s

Platform information
Product: Construct 3 r389 (beta)
Browser: Chrome 124.0.6367.63
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4080 (0x00002704) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
