### ISSUE TITLE
Ease Editor: handles scale with zoom level

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7980]
## Problem description
Ease Editor: handles scale with scroll level. The Timeline Bezier Curve handles this better, where the handles have a fixed size no matter the zoom

## Attach a .c3p
[easeCrash.zip](https://github.com/Scirra/Construct-bugs/files/15175575/easeCrash.zip)

## Steps to reproduce

1. open the ease editor
2. zoom in and out

## Observed result
the curve handles scale with the zoom level

## Expected result
they have a fixed size

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
