### ISSUE TITLE
Find Results auto-refresh makes Remove Results useless, scrolls to top even when panel gets no new results

### ISSUE THREAD

**Issue by JeFawk** [Scirra/Construct-bugs#7982]
## Problem description

The Find Results panel is a greatly used feature by us after the improvements it got a while back. 

We use it to find things, and remove results that aren't relevant usually when debugging an issue. We remove results as we get closer and closer to fixing the problem, it's a great technique!

However the auto-refresh implemented occurs even when there is no new result to be added to the list, making the Remove Results option useless as shown in the video: https://streamable.com/e1oqui 

Apart from removing the Removed Results it also refreshes the list of found references to the top of the list regardless of what scroll distance the user was at, which is a second issue when scrolling through 300+ found references.

So even if we don't use the Remove Results, the auto scroll to the top makes this very hard to use.

(unsure how long streamable keeps the video so I attach it here too)
https://github.com/Scirra/Construct-bugs/assets/7268697/3ef76a0f-84ee-4c56-adf5-648aa73b77d1

## Attach a .c3p

[New project.c3p.zip](https://github.com/Scirra/Construct-bugs/files/15179650/New.project.c3p.zip)

## Steps to reproduce

1. Open the project
2. Use the Find for "Function1"
![image](https://github.com/Scirra/Construct-bugs/assets/7268697/f9a70f13-5c7a-4163-9ddc-7671a4ac86de)

3. Remove some results
4. Scroll to a random place in the Find panel
5. Scroll to the bottom of the event sheet
6. Notice the Browser object with Warn action that writes to console
7. Change the text in the Browser object to "funny" or "fun"

## Observed result

The Find panel refreshes scrolling all the way to the top, and the removed results appear again.
This behaviour makes working with it much harder than needed and other features (Remove Result) less useful next to not useful at all. 

## Expected result

I'd expect the Find Results to not auto refresh for 2 reasons:
1. there is a button for that on the panel
2. there is no new result to be displayed

Would be great to have a checkbox for this auto refresh which can by default be on, and then we can turn it off when we don't need it.

## More details

**Affected browsers/platforms:** Latest Chrome on Windows

**First affected release:** for a very long time

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.62
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 1006 gb
Storage usage (approx): 2 gb (0.2%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002488) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
This sounds more like a feature request - it's currently working as designed but if the result is unfortunate usability, it's not a defect, but a request for an improvement (particularly if the request is to add an 'auto refresh' checkbox). So I think this is best submitted to the feature request tracker.
