### ISSUE TITLE
Quest Flowchart Example

### ISSUE THREAD

**Issue by PulpFLOZ** [Scirra/Construct-bugs#7983]
## Problem description

the quest flowchart  does not work at all in the new update 

## Attach a .c3p
it in the example browser

## Steps to reproduce

1.just play the example you'll see right away
2.
3.

## Observed result
none of the quest move forward 

## Expected result

for the example to work
## More details

I think it the involvement of node reference that broke it 

**Affected browsers/platforms:** 

**First affected release:** 
r388.2
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
The project was relying on a very subtle behaviour which has changed since the initial release of flowcharts. Until we update the projects in the example browser, here is the fixed project.

[quest-flowcharts.zip](https://github.com/Scirra/Construct-bugs/files/15191596/quest-flowcharts.zip)
