### ISSUE TITLE
Dictionary.CurrentValue returns 0 instead of ""

### ISSUE THREAD

**Issue by michel63** [Scirra/Construct-bugs#7984]
## Problem description

Dictionary empty values turn into 0 when retrieving to use in Text or to copy to another Dictionary object.

## Attach a .c3p

[DictionaryEmptyValue.c3p](https://www.dropbox.com/scl/fi/vy4qoa0sohl57pkw468fn/DictionaryEmptyValue.c3p?rlkey=i0xdinglmq8mh7dzw2rhmut9h&st=70bf71al&dl=0)

## Steps to reproduce

1. Create new project.
2. Insert a Dictionary object and a Text object
3. Add data to the Dictionary on start of Layout (empty values)
4. Loop the Dictionary to output values to the Text object

## Observed result

Dictionary.CurrentValue returns 0 instead of ""
Whereas Dictionary.Get(Dictionary.CurrentKey) returns "" as expected
(this workaround was suggested by Dop2000 on the forum: [https://www.construct.net/en/forum/construct-3/how-do-i-8/dictionary-empty-values-turn-182037](https://www.construct.net/en/forum/construct-3/how-do-i-8/dictionary-empty-values-turn-182037))

## Expected result

Dictionary.CurrentValue should return ""

## More details

This issue may be related to another issue reported and fixed in 2018 : [https://github.com/Scirra/Construct-bugs/issues/2466](https://github.com/Scirra/Construct-bugs/issues/2466)

**Affected browsers/platforms:** 
Issue observed on Chrome

**First affected release:** 
No idea which release was first affected
## System details

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Edge 124.0.2478.80
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36 Edg/124.0.0.0
Language setting: en-US

<details><summary>View details</summary>
WebM H.264 (video/webm;codecs=avc1.420034)

Local storage
Storage quota (approx): 274 gb
Storage usage (approx): 897 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00009A68) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
