### ISSUE TITLE
The "On kicked" trigger never fires, either on the host or on the client (peer).

### ISSUE THREAD

**Issue by EweRDay** [Scirra/Construct-bugs#7989]
## Problem description

The "On kicked" trigger never fires, either on the host or on the client (peer).

The "Kick peer" event does not work completely, in fact, the client is still in the room, because when the client tries to join this room again, the error "already in a room" appears. And in order for the client to reconnect, he needs to reconnect to the signal server.

I assume that the kick does not happen completely because: after the client is kicked, the client simply displays a message that the host has disconnected and the peer (host) has left the room, and after the host closes the game (window), the client suddenly sees a message that he has left the signal server, only after that, he will be able to connect to the rooms.

## Attach a .c3p

[mpKickBug.zip](https://github.com/Scirra/Construct-bugs/files/15224719/mpKickBug.zip)

## Steps to reproduce

1. Open two instances of the example
2. Wait for them to join each other.
3. After attaching the peer to the host, the host will kick it in 3 seconds.

## Observed result

The "On kicked" trigger did not work and it is no longer possible to connect to the room unless you reconnect to the signal server

## Expected result

The "On kicked" trigger should have been triggered. And after that, I could reconnect to the room.

## More details

**Affected browsers/platforms:** Chrome, Windows/Android

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.119
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: ru-RU

Local storage
Storage quota (approx): 73 гб
Storage usage (approx): 66 мб (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D9Ex vs_3_0 ps_3_0, nvldumdx.dll)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
It's surprisingly difficult to get a message out to network just before disconnecting the connection, and although it was trying to send a "kicked" message it was not getting transmitted. I'm pretty sure this used to work and browsers have adjusted how messages are sent when a disconnection happens. Anyway I've adjusted this for the next beta so it should work again.
