### ISSUE TITLE
Help manuals options in other editor language will broken

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#7990]
## Problem description

In other editor languages (such as Chinese), click the `help` option in any way cannot jump to the manual correctly. Because the referenced parameters were not handled correctly.

`.../construct-3/[plugin-reference/sprite]?`

```
https://www.construct.net/en/make-games/manuals/construct-3/[plugin-reference/sprite]?utm_campaign=C3Editor&utm_source=browser&utm_medium=r389&utm_term=OpenManualLink&utm_content=PluginHelp
```

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/3f80ada5-912e-4e35-b467-d036d5014f83)

```
https://www.construct.net/make-games/manuals/construct-3/plugin-reference/sprite?utm_campaign=C3Editor&utm_source=browser&utm_medium=r388.2&utm_term=OpenManualLink&utm_content=PluginHelp
```

![image](https://github.com/Scirra/Construct-bugs/assets/45864744/6c224917-4a43-4084-ad6a-e531b1559de8)

## Steps to reproduce

1. change language to Chinese "简体中文"
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/1bc0ebbf-a9f4-4023-b802-789e6d8bef95)

2. Create any plugin and click the object type help option
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/12ad10a7-5ce2-4d1c-a56a-c0271cd09f2d)

## Observed result

extra [...] symbols
`.../construct-3/[plugin-reference/sprite]?`

ERR_TOO_MANY_REDIRECTS
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/d3d44476-cfc6-48d5-bb5f-9b34f814e905)

## Expected result

not [] symbols
`.../construct-3/plugin-reference/sprite?`

works as expected

## More details

This goes back to a suggestion once posted on the suggestion platform.  Even if the editor switches to another language, the original english object name can still be searched.

For example, in the Chinese language the "Mouse" is translated as "鼠标" and "Keyboard" is translated as "键盘". current, you can no use search for them by "Mouse" or "Keyborad". for CJK languages, we also need to use the input method to find them. This is very inconvenient. 

For this solution, you can view: https://github.com/Scirra/Construct-feature-requests/issues/95

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed the help links to ensure they work in non-English languages for the next beta.
