### ISSUE TITLE
Bug when removing a layer (Particles and sprite)

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-bugs#7991]
## Problem description

If you add an image to the particles through a sprite and then fix these particles on another sprite through the hierarchy and remove the layer on which they will be, then the game breaks down

## Attach a .c3p

[layer-hier-part-bug.zip](https://github.com/Scirra/Construct-bugs/files/15232509/layer-hier-part-bug.zip)

## Steps to reproduce

Look at the attached file. Add a sprite image to the particles. Connect the particles in a hierarchy with another sprite. Create a sprite. And then delete the layer on which the sprite with particles was created:

Press A, then press D and see the errors in the console

## Observed result

Errors in the console and the game stops working correctly

## Expected result

No errors

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
