### ISSUE TITLE
Template Replica, circular reference editor crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#7992]
## Problem description
When adding a replica as a child of its template you create an infinite loop that crashes the editor. As this can sometimes happen by accident it would be good if c3 would not allow doing this hierarchy connection

## Attach a .c3p
[templateCircularReference.zip](https://github.com/Scirra/Construct-bugs/files/15237627/templateCircularReference.zip)

## Steps to reproduce

1. add one of the replicas as a child of the template

## Observed result
editor freezes

## Expected result
editor doesn't allow making this hierarchy connection and shows a message to tell the user what the issue is. 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
The next beta will avoid the crash.

With that kind of setups it's very hard to tell what is the expected behaviour though or even what a useful behaviour would be, so we are still taking feedback on this feature.
