### ISSUE TITLE
Cryptography plugin does'nt work on http protocol

### ISSUE THREAD

**Issue by EweRDay** [Scirra/Construct-bugs#8002]
## Problem description

When using the Cryptography plugin on unsecured sites (http), an error occurs, due to which the plugin does not work.

## Attach a .c3p

[CryptographyOnHTTP.zip](https://github.com/Scirra/Construct-bugs/files/15262029/CryptographyOnHTTP.zip)

## Steps to reproduce

1. Open the example and export it to HTML (or open [link](http://u92529no.beget.tech/), at the moment there is already an example uploaded to an unsecured server)
2. Upload the exported HTML to an http server
3. Open and observe the error in the console

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/99734313/698d5428-303a-4c25-a1eb-264a20876881)
![image](https://github.com/Scirra/Construct-bugs/assets/99734313/c166294a-99ee-412c-a6dc-279811563475)

## Expected result

![image](https://github.com/Scirra/Construct-bugs/assets/99734313/3078caf9-1542-4cc3-a5b4-cfe8a59da496)

## More details
**Affected browsers/platforms:** Chrome, Windows

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.119
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: ru-RU

Local storage
Storage quota (approx): 73 гб
Storage usage (approx): 66 мб (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

WebGL 2+ is not supported. Rendering quality and features may be affected.
WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1050 Ti Direct3D9Ex vs_3_0 ps_3_0, nvldumdx.dll)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

ANGLE_instanced_arrays
EXT_blend_minmax
EXT_color_buffer_half_float
EXT_float_blend
EXT_frag_depth
EXT_shader_texture_lod
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_sRGB
KHR_parallel_shader_compile
OES_element_index_uint
OES_fbo_render_mipmap
OES_standard_derivatives
OES_texture_float
OES_texture_float_linear
OES_texture_half_float
OES_texture_half_float_linear
OES_vertex_array_object
WEBGL_color_buffer_float
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_depth_texture
WEBGL_lose_context
WEBGL_multi_draw
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment]
This is the expected behaviour. 

All modern browsers require HTTPS for this feature to work.

**Comment by EweRDay** [comment]
> This is the expected behaviour.
> 
> All modern browsers require HTTPS for this feature to work.

This is quite strange, because because of this I have to resort to including javascript scripts in my project, for example the forge library. And strangely enough, you can write a banal sha256 hashing script that will work even on the http protocol and does not require an https connection.

Moreover, I have not found information anywhere in the documentation for this plugin that it will not work over an unsecured protocol.

However, I believe that the plugin does not work 100%.

**Comment by DiegoScirra** [comment]
The restriction is imposed by modern browsers for security reasons. All C3 does is expose that API.

https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API

You can implement your own hashing algorithms, they will probably be a lot less efficient. More importantly is if data is transmitted over HTTP, it is simply not secure, defeating the purpose of cryptography.

**Comment by EweRDay** [comment]
> The restriction is imposed by modern browsers for security reasons. All C3 does is expose that API.
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
> 
> You can implement your own hashing algorithms, they will probably be a lot less efficient. More importantly is if data is transmitted over HTTP, it is simply not secure, defeating the purpose of cryptography.

I am aware of the consequences of sending data over http.
Now I understand that this api that you are using simply prohibits the use of http itself, thank you.

**Comment by AshleyScirra** [comment]
Lots of modern web platform features now require HTTPS. You will find a number of things not working, not just cryptography, if you publish on HTTP. All modern web content should be published on HTTPS.

**Comment by EweRDay** [comment]
> Lots of modern web platform features now require HTTPS. You will find a number of things not working, not just cryptography, if you publish on HTTP. All modern web content should be published on HTTPS.

Yes, I know, thank you. Of course, I use HTTPS and I know about its advantages, but still I sometimes test some functions on an unsecured protocol and thanks to this I found out that this plugin does not work. I thought it might be a mistake, since I didn't see any information anywhere that it doesn't work on HTTP. Perhaps I would like it to just be stated. With the help of hashing and encryption, you can make a decent protection for your project so that it works only on the right original domain, this protection will greatly complicate the lives of ignorant users, I know that it can be circumvented, but it will be difficult, but as it turned out, using this plugin it will not work, the project can be simply upload to HTTP hosting and that's it, the plugin will stop working. This can probably just be fixed by additional checks on which protocol the page is running on, but I just started learning Javascript and implemented a good library with hashing and various types of encryption, flesh to RSA. Thanks for the response guys! Have a good day!

**Comment by AshleyScirra** [comment]
The guide [Publishing to the web](https://www.construct.net/en/tutorials/publishing-web-10) has a section that says "Use secure hosting". If you just want to test things quickly, use Construct's preview mode, which is HTTPS. If you want to test things quickly after export, use a local web server running on `localhost`, which still counts as secure. If you are publishing to a public web server, these days you should always use HTTPS.

**Comment by EweRDay** [comment]
> The guide [Publishing to the web](https://www.construct.net/en/tutorials/publishing-web-10) has a section that says "Use secure hosting". If you just want to test things quickly, use Construct's preview mode, which is HTTPS. If you want to test things quickly after export, use a local web server running on `localhost`, which still counts as secure. If you are publishing to a public web server, these days you should always use HTTPS.

Thank you. By testing, I did not mean a cursory test, but testing of an exported project. I was wondering how the project would behave on HTTP. When debugging, I usually use local testing.
