### ISSUE TITLE
3d rendering transparency glitch

### ISSUE THREAD

**Issue by rationality6** [Scirra/Construct-bugs#8004]
## Problem description

There is an issue drawing the transparency in 3D rendering. Please see attached.

rendering glitch

![Screenshot 2024-05-10 at 12 30 20 AM](https://github.com/Scirra/Construct-bugs/assets/3889468/9ff940d5-c547-4ff9-b6c0-116765eb95ce)

## Attach a .c3p

it's also happen in official game

## Steps to reproduce

1. open official game Ancient watcher

## Observed result

rendering glitch

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by NickR-Git** [comment]
You may be able to solve this issue for now by putting the sprite on a different layer than the background.

**Comment by AshleyScirra** [comment]
This appears to be a regression from r380 - an optimization for rendering effects in 3D accidentally caused incorrect rendering with fog in some cases. I've reverted the optimization for the next release which fixes it.
