### ISSUE TITLE
Use localeCompare to sort in non-English languages

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8010]
## Problem description

Currently, the editor use encoding order when sorting. But in non-English, usually not used this order, but is according to the dictionary order of the local language.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare

## Attach a .c3p

[issue-dictionary-sort.c3p.zip](https://github.com/Scirra/Construct-bugs/files/15288751/issue-dictionary-sort.c3p.zip)

## Steps to reproduce

1. Variable list
2. Layout name

## Observed result

for example in Chinese

```
const names = ['上海', '北京', '深圳', '杭州', '西安', '成都', '云南']
names.sort()

// ['上海', '云南', '北京', '成都', '杭州', '深圳', '西安']
```

## Expected result

```
const names = ['上海', '北京', '深圳', '杭州', '西安', '成都', '云南']
names.sort((a, b) => a.localeCompare(b));

// ['北京', '成都', '杭州', '上海', '深圳', '西安', '云南']
```

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Sorting is used in a great deal of places all across the editor, and each case probably needs evaluating to determine whether locale sorting is appropriate or not. Therefore this is probably quite a significant amount of upgrade/refactoring work, and I think this is better categorised as a feature request.
