### ISSUE TITLE
miss 'type mismatch errors' translate

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8011]
## Problem description

In the 'Set JSON' action, if enter a number in a 'JSON string', this prompt has not been translated.

![Snipaste_2024-05-13_10-50-58](https://github.com/Scirra/Construct-bugs/assets/45864744/a3a30bb7-1a46-4cbe-ae8b-49961da77272)

## Attach a .c3p

[issue-errors.type-mismatch.c3p.zip](https://github.com/Scirra/Construct-bugs/files/15288887/issue-errors.type-mismatch.c3p.zip)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Both the 'Type mismatch' error and build server status are translatable from the next beta. The strings will appear on POEditor the same day the beta release goes out (and then any new translations will then only appear in the next beta release after that).
