### ISSUE TITLE
Xbox UWP in export dialog 'Learn more' link is broken

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8018]
## Problem description

![Snipaste_2024-05-16_17-05-57](https://github.com/Scirra/Construct-bugs/assets/45864744/baf31f2a-8370-4370-b69c-78b3543cc3f5)

## Observed result

https://www.construct.net/en?utm_campaign=C3Editor&utm_source=browser&utm_medium=r391

## Expected result

https://www.construct.net/en/blogs/ashleys-blog-2/construct-xbox-support-1873

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I've removed the link for the next beta. Currently there isn't any appropriate documentation for it to link to (we don't generally link to blog posts in the editor).
