### ISSUE TITLE
r391 Template: Crash when Click Replica objects in Other Layout

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8020]
## Problem description

Crash when click on Replica obejct.

Update: 
Even if I select this object type( 'ChipmunkCollision' ) from the project folder it crashes

## Attach a .c3p

This is not a minimal reproduction project. I can't reproduce it in a new project because it can work when I paste it into a new project.

This is the object I deleted other object from the crash project, it will crash when clicked the Red box.
[r391-Template-Crash-issue-2.c3p.zip](https://github.com/Scirra/Construct-bugs/files/15360415/r391-Template-Crash-issue-2.c3p.zip)

This is the original crashed project. When you using 'Tab' to Click the Replica Red box in Layout 1
[r391-Template-Crash-issue-1.c3p.zip](https://github.com/Scirra/Construct-bugs/files/15360406/r391-Template-Crash-issue-1.c3p.zip)

## Steps to reproduce
1. Click the Red Box in Layout 1

## Observed result

Crash
```
Error report information
Type: unhandled exception
File: https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js, line 115, col 9
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'Sb')
Stack: TypeError: Cannot read properties of undefined (reading 'Sb') at zV (https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js:115:9) at Spb (https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js:42:442) at CCG.aa.oX (https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js:167:369) at d.Sac (https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js:138:492) at d.zTc (https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js:138:458) at Array. (https://editor.construct.net/r391/components/bars/propertiesBar/propertiesBar.js:123:370) at window.uqb.dispatchEvent (https://editor.construct.net/r391/main.js:1271:42) at TQ (https://editor.construct.net/r391/components/editors/layoutView/layoutView.js:75:365) at Sib.Yp (https://editor.construct.net/r391/components/editors/layoutView/layoutView.js:227:479) at Sib.Mc (https://editor.construct.net/r391/components/editors/layoutView/layoutView.js:220:57)
Construct version: r391
URL: https://editor.construct.net/r391/
Date: Sat May 18 2024 14:05:38 GMT+0800 (中国标准时间)
Uptime: 4.3 s

Platform information
Product: Construct 3 r391 (beta)
Browser: Chrome 124.0.6367.208
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing
```

## Expected result

no Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PPlatform information
Product: Construct 3 r391 (beta)
Browser: Chrome 124.0.6367.208
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 2.200000047683716
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 192 gb
Storage usage (approx): 246 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon(TM) Graphics (0x00001681) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment]
The next beta will fix the crash.
