### ISSUE TITLE
Image Bug

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-bugs#8021]
## Problem description

Crach when editing the sprite image (double-click on the object).

I think it's because my image is too big: 10750 x 8860 PX.

When I loaded the image, everything went fine, but the image didn't want to appear on the scene, so I tried to edit the image of my object and it spit.

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

Error report information
Type: unhandled rejection
Reason: Error: unexpected type @ TypeError: unexpected type at Q.i (https://editor.construct.net/r391/main.js:1055:147) at d.via (https://editor.construct.net/r391/projectResources.js:820:504) at https://editor.construct.net/r391/projectResources.js:381:297
Stack: TypeError: unexpected type at Q.i (https://editor.construct.net/r391/main.js:1055:147) at d.via (https://editor.construct.net/r391/projectResources.js:820:504) at https://editor.construct.net/r391/projectResources.js:381:297
Construct version: r391
URL: https://editor.construct.net/r391/
Date: Sun May 19 2024 01:45:59 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 338840.6 s

Platform information
Product: Construct 3 r391 (beta)
Browser: Chrome 124.0.6367.158
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Google)
Renderer: ANGLE (Google, Vulkan 1.3.0 (SwiftShader Device (Subzero) (0x0000C0DE)), SwiftShader driver)
Major performance caveat: yes
Maximum texture size: 8192
Point size range: 1 to 1023
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_clip_cull_distance, WEBGL_compressed_texture_astc, WEBGL_compressed_texture_etc, WEBGL_compressed_texture_etc1, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_stencil_texturing

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Could you please attach the project file and write the steps to reproduce?

**Comment by DieppedalleDavid** [comment]
Sorry, no.

**Comment by DiegoScirra** [comment]
I can't reproduce this. In my case C3 struggles to work with an image of that size, but it doesn't crash. Will have to close as there is little to investigate here.
