### ISSUE TITLE
duplicate flowchart crash

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8025]
## Problem description
duplicating a flowchart causes a crash

## Attach a .c3p
Flowcharts and containers example project
https://editor.construct.net/#open=flowcharts-and-containers

## Steps to reproduce

1. right-click the flowchart in the project bar
2.click duplicate

## Observed result
crash

## Expected result
no crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: expected finite number @ TypeError: expected finite number at Q.B (https://editor.construct.net/r392/main.js:1053:407) at d.oq (https://editor.construct.net/r392/projectResources.js:614:327) at d.za (https://editor.construct.net/r392/projectResources.js:1810:110) at d.mg (https://editor.construct.net/r392/projectResources.js:1804:395) at https://editor.construct.net/r392/components/bars/projectBar/projectBar.js:88:229 at https://editor.construct.net/r392/main.js:1937:388
Stack: TypeError: expected finite number at Q.B (https://editor.construct.net/r392/main.js:1053:407) at d.oq (https://editor.construct.net/r392/projectResources.js:614:327) at d.za (https://editor.construct.net/r392/projectResources.js:1810:110) at d.mg (https://editor.construct.net/r392/projectResources.js:1804:395) at https://editor.construct.net/r392/components/bars/projectBar/projectBar.js:88:229 at https://editor.construct.net/r392/main.js:1937:388
Construct version: r392
URL: https://editor.construct.net/r392/
Date: Wed May 22 2024 10:27:47 GMT+0200 (Mitteleuropäische Sommerzeit)
Uptime: 14.9 s

Platform information
Product: Construct 3 r392 (beta)
Browser: Chrome 124.0.6367.209
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 1.0 (OpenGL ES 2.0 Chromium)
Numeric version: 1
Supports NPOT textures: partial
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4070 (0x00002786) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: ANGLE_instanced_arrays, EXT_blend_minmax, EXT_clip_control, EXT_color_buffer_half_float, EXT_depth_clamp, EXT_disjoint_timer_query, EXT_float_blend, EXT_frag_depth, EXT_polygon_offset_clamp, EXT_shader_texture_lod, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_sRGB, KHR_parallel_shader_compile, OES_element_index_uint, OES_fbo_render_mipmap, OES_standard_derivatives, OES_texture_float, OES_texture_float_linear, OES_texture_half_float, OES_texture_half_float_linear, OES_vertex_array_object, WEBGL_blend_func_extended, WEBGL_color_buffer_float, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_depth_texture, WEBGL_draw_buffers, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
