### ISSUE TITLE
"Timeline" breaks the Android app.

### ISSUE THREAD

**Issue by igortyhon** [Scirra/Construct-bugs#8026]
## Problem description

As soon as I add "Timeline" to a project and do an export for Android, on some devices the app hangs on the loading screen.

## Attach a .c3p

https://kibaga.org/bugs/BugTimeLineAndroid.zip
The archive contains the minimal project that causes the bug and without the bug.

Test video
https://youtu.be/rJsEz4nbT1M?si=3HTtyPxXhZLal1qh

## Steps to reproduce

1. I'm building a minimal project for android (it's in the archive). No problems when running on the device!
2. I add a simple "Timeline" to the project and build a build for android. When running on some devices, the application hangs on the loading screen. (mostly Huawei and Honor devices).
3. I save the error log from the device and take a screenshot and record a video. (all this is in the archive)

## Observed result

I see the app hangs on the loading screen.

## Expected result

I expect the first screen of the application to launch after the boot screen.

## More details

The timeline app hangs on some devices, so I've attached a text log from the device.
Test video
https://youtu.be/rJsEz4nbT1M?si=3HTtyPxXhZLal1qh

**Affected browsers/platforms:** 

For these test devices. Used the stable version 388-2.

**First affected release:** 

For these test devices. Worked for 379, broke in 388-2.

## System details

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 124.0.6367.208
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 258 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GT 1030 (0x00001D01) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

**Comment by WilsonPercival** [comment]
I opened your project in `r392b`, exported it to `Debug APK` and everything works fine for me.

**Comment by igortyhon** [comment]
> I opened your project in `r392b`, exported it to `Debug APK` and everything works fine for me.
Hi, I just built the package on version 392, the problem remains.
I want to clarify, the problem is on some devices (huawei and honore). On all other devices and emulators everything is fine.
I have 10 test devices and on eight the package works fine, on two it breaks.

**Comment by DiegoScirra** [comment]
Have you tried disabling minification when doing the export?

**Comment by DiegoScirra** [comment]
What models are the devices that are not working? What version of Chrome do they have installed? The Android System WebView version number would also be useful.

**Comment by DiegoScirra** [comment]
The next release will include additional feature support checks to make sure everything that is required is supported in the device. If any of the checks fail a message will be shown prompting to update the browser rather than hanging with no more feedback.

**Comment by igortyhon** [comment]
> Які моделі пристроїв не працюють? Яку версію Chrome вони встановили? Номер версії Android System WebView також буде корисним.

Hi.
You've pointed me in the right direction.
I have my Huawei WebView version 10.0.0.307 on my phone and for some reason it didn't update. I manually updated it to 11.0.6.310 and the problem was solved.
Now the project starts and works correctly.
Problem found, the cause was the old WebView.
Thank you for your help!
