### ISSUE TITLE
Bookmark is being deleted - Cut&Paste [enhancement]

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8031]
## Problem description

When you Cut&Paste Bookmarked comment, group or anything; Bookmark is being deleted. But when you move them bookmark not deleted. It is expected to exhibit the same behavior when you copy and paste.

## Attach a .c3p

[bookmark.zip](https://github.com/Scirra/Construct-bugs/files/15433892/bookmark.zip)

## Steps to reproduce

Cut & Paste bookmarked comment.

## Observed result

Bookmark is being deleted.

## Expected result

Bookmark not deleted.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
