### ISSUE TITLE
Open from Local Browser - Listing Bug

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8032]
## Problem description

Projects disappearing.

## Attach a .c3p

[First.zip](https://github.com/Scirra/Construct-bugs/files/15439081/First.zip)
[Test.zip](https://github.com/Scirra/Construct-bugs/files/15439082/Test.zip)

## Steps to reproduce

![A](https://github.com/Scirra/Construct-bugs/assets/54614906/f1a7d9fb-76b5-4dd8-b4c5-e6a4b0b3c832)

1. Change backup settings as in picture A
2. Open Construct App and load First.zip
3. Open New Construct App and load Test.zip
4. Go to First project and edit something (Add, delete anything).
5. Go to Test project and save it in local browser (use TestAAA or something different). **(Menu > Project > Save As > Save to local browser)**
6. Wait 1 minute for autosave First project.
7. When autosave shown close all Construct Apps and open new Construct App
8. You can't see your TestAAA project in Local Browser **(Menu > Project > Open from local browser)**

## Observed result

Projects disappearing.

## Expected result

Don't let projects get lost.

## More details

I can see it in Recent Projects but not in Local Browser (Open Project)
![Test](https://github.com/Scirra/Construct-bugs/assets/54614906/966efec0-5269-4a3e-8284-68e8476a4f08)

**Affected browsers/platforms:** Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r392 (beta)
Browser: Chrome 125.0.6422.78
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 135 gb
Storage usage (approx): 191 mb (0.1%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB (0x00001C02) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
For me, the 'Local browser' option does not appear in Chrome, neither under the default save location nor the backup location. This is because Chrome supports saving to local files and folders, so the local browser option is hidden in that case.

Presumably you've changed your browser configuration somehow? If you are using something like a browser extension that makes changes to the features Construct can use, I'm afraid we can't support that. Perhaps removing all browser extensions will restore the normal working of Construct.

**Comment by CrackHub** [comment]
I'm using Construct with new Chrome user profile. It doesn't have any browser extensions.
Also I'm using Local Browser when Construct supported and I still have that. It is really important to use Local Browser for me.
Organizing examples and using backups with it.
![image](https://github.com/Scirra/Construct-bugs/assets/54614906/2aa7039e-dd27-4768-9212-5fc7893d28e4)
