### ISSUE TITLE
Physics error with polygon collision

### ISSUE THREAD

**Issue by kimarutaGM** [Scirra/Construct-bugs#8035]
## Problem description
Can not preview the Project

## Attach a .c3p
[Bug Physic.zip](https://github.com/Scirra/Construct-bugs/files/15454072/Bug.Physic.zip)

## Steps to reproduce

I don't remember exactly each step. But something like
1. Add Sprite 
2. Add sprite to family
3. Physic behavior to that family
4. Change Collision Mask to : Use collision Polygon

## Observed result

Can not preview the Project, only Black Scene.

## Expected result

Object with Physic Behavior fall down.
## More details
 Test on Chrome

**Comment by WilsonPercival** [comment]
Duplicate https://github.com/Scirra/Construct-bugs/issues/7226

**Comment by kimarutaGM** [comment]
Thank @WilsonPercival . I see it.
