### ISSUE TITLE
this._IsFollowingCustomPropertyEnabled is not a function

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#8039]
## Problem description

Is Following Custom property condition throws an error

## Attach a .c3p

[follow custom property bug.zip](https://github.com/Scirra/Construct-bugs/files/15494513/follow.custom.property.bug.zip)

## Steps to reproduce

1. Hit play

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/11213825/21a500df-4d94-4525-aa6f-068802f53ddc)
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/8aeee67e-7962-436c-a1e7-14cbcc9f4fce)

## Expected result

I suppose should be using this?
![image](https://github.com/Scirra/Construct-bugs/assets/11213825/0585dc9a-034c-40de-9284-022a48d0fe54)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
