### ISSUE TITLE
Template is ignored when creating object via family

### ISSUE THREAD

**Issue by fodi** [Scirra/Construct-bugs#8040]
## Problem description

If I create two or more templates for an object which is also a member of a family and try to create instances during runtime by specifying a template and referencing the family instead of the object type, the template parameter is ignored.

## Attach a .c3p

[FamilyTemplateTest.zip](https://github.com/user-attachments/files/15511302/FamilyTemplateTest.zip)

## Steps to reproduce

1. Create eg. a sprite, add it to a family
2. Create two instances of the sprite, turn it into templates, optionally change some properties (eg. colour) so they can be distinguished
3. Make two Create object / Create object (by name) or Spawn another object actions by specifying the family in "Object to create" with each template names.

## Observed result

The object is always spawned using the "older" template, not the specified one.

## Expected result

It think a random member (object type) of the family should spawn and if it has a template named like the one specified in the create object / spawn another object action, it should respect it. 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be added in the next beta release.

You will need to watch out for object types that don't have the template you are trying to use.
