### ISSUE TITLE
SDK V2 / Behaviors Throw exception Cannot read properties of null (reading 'GetObjectClass')

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8042]
## Problem description

Basic-Bullet example behavior for SDK V2. Test the Basic-Bullet behavior provided in the SDK v2. The object with the behavior will move, but if you restart the layout the next time the behavior initializes, it loses the "instance" reference to the object containing it throwing an exception.

## Steps to reproduce

1. Install the example plugin Basic-Bullet provided in the SDK v2
2. Create a new project, add the behavior to an sprite. Add the keyboard plugin and add an event to restart the layout when pressing "R" in the keyboard.
3. Run the project, the sprite will start moving. Then press "R" to restart the layout, the exception will be thrown and shown in the developer console.

## Observed result

![image](https://github.com/Scirra/Construct-bugs/assets/10860045/9bf9c5e9-42ee-4aae-a4d9-a0050810ea13)

## Expected result

The "instance" attribute of the behavior must always be available.

## More details
Beta release r393.
Sample project attached.
[basic-bullet-test.zip](https://github.com/user-attachments/files/15521273/basic-bullet-test.zip)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetObjectClass')
    at BehaviorInstance.SortByTickSequence (behaviorInstance.js:6:376)
    at js_cols.RedBlackSet.behInstSortFunc [as compare] (runtime.js:11:317)
    at js_cols.RedBlackSet.get_ (redblackset.js:15:95)
    at js_cols.RedBlackSet.contains (redblackset.js:15:245)
    at js_cols.RedBlackSet.insert (redblackset.js:5:61)
    at RedBlackSet.Add (redblackset.js:27:352)
    at C3Runtime._AddBehInstToTick (runtime.js:80:160)
    at BasicBulletBehaviorInstance._setTicking (ISDKBehaviorInstanceBase.js:3:143)
    at new BasicBulletBehaviorInstance (b231cb77-01f8-4231-80ab-5837ffa8a5e4:25:9)
    at BehaviorInstance._InitScriptInterface (behaviorInstance.js:8:24)
</details>

**Comment by sotano42** [comment]
The IBehaviorInstance.instance property is also unavailable at the constructor of the Behavior, throwing the exact same exception.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/7e308c5b-c9f3-4c27-8c5d-e07cdbc320df)

@AshleyScirra

**Comment by AshleyScirra** [comment]
Thanks for the report, fixed for next beta.

**Comment by sotano42** [comment]
> Thanks for the report, fixed for next beta.

@AshleyScirra the IBehaviorInstance.instance is still not available when the constructor of the behavior is called. Is it supposed to work like that? Sometimes we need the instance to be passed to our wrapper classes to develop functionalities.

**Comment by AshleyScirra** [comment]
When the constructor of the behavior is called, the instance is still half-way through being created, so the instance reference cannot yet be used.

**Comment by sotano42** [comment]
> When the constructor of the behavior is called, the instance is still half-way through being created, so the instance reference cannot yet be used.

thanks, I realized I could use postCreate().
