### ISSUE TITLE
TileMovement conditions behave strangely with Timelines

### ISSUE THREAD

**Issue by ymanton** [Scirra/Construct-bugs#8043]
## Problem description

When a sprite with the TileMovement behaviour is animated with a Timeline, TileMovement conditions still pick the instance, even if its TM behaviour is disabled before playing the Timeline.

I think I might be OK with this, except that the instance is picked by the wrong conditions, and some TM expressions aren't updated as the Timeline plays. In the attached project you can find the following:

1. When the Timeline plays the player sprite's TileMovement.is-moving-Up condition always picks the instance, regardless of which direction the sprite is moving in.

2. The TargetGridX and TargetGridY expressions don't update while the Timeline is playing. It would be nice if they did (e.g. by being calculated from the next keyframe's x/y), but I can understand why they wouldn't; the problem is that conditions like is-moving and is-moving-Up still activate, so my actions and sub-events that use TargetGridX/Y are reached but don't have valid data to work with.

Disabling my TileMovement event code via groups or checking if a Timeline is playing, etc, allow me to work around the issue.

## Attach a .c3p

[TileMovementTimelineBug.zip](https://github.com/user-attachments/files/15523042/TileMovementTimelineBug.zip)

## Steps to reproduce

1. Run the attached project; the timeline will be played immediately; watch the console for messages.
2. Disable the entire sub-event block that contains the Timeline play action and re-run; you'll be able to control one of the sprites and its TileMovement conditions and expressions will work as expected.

## Observed result

Sprite 2 is picked by TileMovemement.is-moving-Up regardless of which direction 2 is moving in. 2's TargetGridXY stay at 0,0 for the duration of the animation, although GridXY still change.

## Expected result

I'd expect the player sprite to not be picked by TileMovement conditions while the Timeline plays because the sprite's TileMovement behaviour is disabled. Alternatively, I'd expect the right conditions to pick the sprite and TM expressions to be correct.

## More details

**Affected browsers/platforms:** 

Tested using Chrome 125.0.6422.78 on Windows.

**First affected release:** 

Tested in r388.2 stable.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r388.2 (stable)
Browser: Chrome 125.0.6422.78
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 571 gb
Storage usage (approx): 91 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00004626) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
The provided project is pretty complicated for a minimal repro and it also generates so much console log data it's hard to make sense of it. Can you provide a minimal project with the fewest objects and events possible as per the bug report guidelines?

**Comment by ymanton** [comment]
Sorry, here's a much smaller project.

[TileMovementTimelineBug.zip](https://github.com/user-attachments/files/15598067/TileMovementTimelineBug.zip)

The basic question is, should a behaviour condition pick instances that have the behaviour currently disabled?

I think I understand what's going on based on your comments in other issues related to Tile Movement; the timeline doesn't affect the target coords, which look like they're initialized to the current location, so if the timeline moves the instance down, is-moving picks the instance because the behaviour is always trying to move the instance to the target and is-moving-up picks the instance because the target is in the opposite direction. If I change the timeline to move the instance to the right, is-moving-left picks the instance, and so on. As soon as the timeline ends and Tile Movement is enabled, it moves back to the target.

I wondered if other behaviours did also so I tried Move To, but that is-moving condition doesn't pick instances that are moved via timeline, regardless of whether the behaviour is enabled or disabled on the instance, and the instance doesn't move back to the target once the timeline ends.

My current workaround is to just add an extra Tile Movement is-not-enabled condition to filter out the instances that I want to manipulate via timelines, but it took some time to figure out what was going on after reading the manual and other issues up and down and being thoroughly confused.

**Comment by AshleyScirra** [comment]
I think this minimal repro demonstrates what you are talking about: [issue8043.zip](https://github.com/user-attachments/files/15774123/issue8043.zip)
Drag the blue square and the disabled Tile Movement behavior's 'Is moving' condition is true.

I don't think the 'Is moving' or 'Is moving in direction' conditions should be true while the behavior is disabled. That is fixed for the next beta.
