### ISSUE TITLE
Jumpthru bug with scale layout

### ISSUE THREAD

**Issue by q3olegka** [Scirra/Construct-bugs#8046]
## Problem description

It seems that an object with Platform behavior when jumping gets stuck in objects with Jumthru behavior when the layout scale is changed. Because of this, Platform freezes on the jump animation.

## Attach a .c3p

[jumpthru-bug.zip](https://github.com/user-attachments/files/15581139/jumpthru-bug.zip)

## Steps to reproduce

Open the source code and jump onto the platform. Try to release the jump when the sprite is actually on the platform

It seems that it is necessary to change the scale of the layout in order for the bug to work and possibly need Jump sustain

https://github.com/Scirra/Construct-bugs/assets/50992459/b5475088-c1c1-4df2-a84f-6b867ee69cb7

https://github.com/Scirra/Construct-bugs/assets/50992459/a9d2c8dc-24ca-4052-b496-2cd5802cdbce

## Observed result

The object gets stuck with the jump animation

## Expected result

The object should have the landed animation triggered and it should not get stuck

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
Could you write the steps to reproduce the problem?

**Comment by q3olegka** [comment]
https://github.com/Scirra/Construct-bugs/assets/50992459/60922329-a7cd-4f9c-accd-15f8cd328952

[jumpthru-bug.zip](https://github.com/user-attachments/files/15614263/jumpthru-bug.zip)

Corrected it. 

In the video, I only press the "R" button to restart the layout.

I tried it on my phone, but with the values that are currently set in the source code, the sprite does not jump to the platform a little and therefore it is impossible to catch the bug there. 

You may also need to slightly correct the values for the variable "a" on your device. And apparently yes, the scale does not affect the problem in any way

**Comment by WilsonPercival** [comment]
Can not reproduce.

**Comment by q3olegka** [comment]
I can reproduce it in different browsers. And I want to point out that the main problem is not that the sprite is leaking through the platform. And the fact is that while already on the platform after the jump, the jump animation continues to be active

**Comment by q3olegka** [comment]
@AshleyScirra I can't reproduce the problem on my phone, but on my laptop, the problem exists in all browsers. And if you can't repeat the problem either, does that mean it's my laptop's problem, do you have any thoughts? And what percentage of people will face the same problem?

**Comment by AshleyScirra** [comment]
I tried this again and after 10 attempts it did not reproduce the problem. I'm afraid we just can't properly investigate issues unless there is a reliable way to reproduce it - even if it only happens something like 1 in 20 times, that alone makes it extremely difficult to ever fix, as we may have to try 20+ things before we can fix a bug, and if after each change we can't tell whether the change has helped then it's extremely difficult to make any progress.
