### ISSUE TITLE
tag autocomplete UX issue

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8047]
## Problem description
There is an ux issue with the autocomplete. If you click into the `""`, that most tags have as a default, no suggestions show up until you erase the trailing `"`

## Attach a .c3p
[trailingAuto.zip](https://github.com/user-attachments/files/15594555/trailingAuto.zip)

## Steps to reproduce

1. create a new on signal condition in the empty event
2. click between the two `"` in the condition dialog as if you wanted to type a string.

## Observed result
no auto complete suggestions show up
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/3a342a50-f98f-4a31-8032-1ad7b1d058dd)

## Expected result
auto complete suggestions are shown
![image](https://github.com/Scirra/Construct-bugs/assets/89512047/4a661361-ee08-4399-a6c6-8e3b3ad8c404)

## More details
This leads to the auto completion not showing up most of the time for me, I need to remember to first delete the last " and add it back later. Idk how this works internally, but maybe check if last character in the string is a `"` and if yes remove it from the autocomplete query.  `\"$`

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is the way autocomplete has always worked. If you want to suggest a change to how it currently works, it's best to file a feature request.

FWIW, the default empty string starts selected, so you can see autocomplete immediately by typing `"` which replaces the selection and lists suggestions.

**Comment by F3der1co** [comment]
filled as a feature request:
https://github.com/Scirra/Construct-feature-requests/issues/291
