### ISSUE TITLE
Beta r394: Missing TypeScript Definitions (before/afteranylayoutstart/end)

### ISSUE THREAD

**Issue by thepeachu** [Scirra/Construct-bugs#8048]
## Problem description

The release notes for [r394](https://www.construct.net/en/make-games/releases/beta/r394) say:

> Add IRuntime events before/afteranylayoutstart/end 

However, the corresponding TypeScript definitions are missing from the `RuntimeEventMap` interface in `IRuntime.d.ts`.

**Comment by AshleyScirra** [comment]
Updated TS definitions for the next beta.
