### ISSUE TITLE
Unhandled rejection when setting a variable

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#8049]
## Problem description

Construct crashed and shows an error message when setting/editing a variable in a **custom action** with at least **one parameter**

## Steps to reproduce

Just create a custom action with a parameter, then try setting a variable in it - see error log below

## Observed result

C3 crashed and shows error message when setting/editing a variable in a custom action with at least one parameter

## Expected result

Variable can be set and C3 doesnt crash

## More details

**Affected browsers/platforms:** 

Edge/Chrome
C3 version: 394

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: f.Bp is not a function @ TypeError: f.Bp is not a function at new window.g_b (https://editor.construct.net/r394/projectResources.js:3157:244) at pa.j (https://editor.construct.net/r394/main.js:1138:44) at new d (https://editor.construct.net/r394/projectResources.js:3188:269) at pa.j (https://editor.construct.net/r394/main.js:1138:44) at lF.g.J.jwb.R (https://editor.construct.net/r394/projectResources.js:3194:90) at hTa (https://editor.construct.net/r394/projectResources.js:572:57) at dTa (https://editor.construct.net/r394/projectResources.js:570:117) at eTa (https://editor.construct.net/r394/projectResources.js:569:391) at https://editor.construct.net/r394/projectResources.js:569:454
Stack: TypeError: f.Bp is not a function at new window.g_b (https://editor.construct.net/r394/projectResources.js:3157:244) at pa.j (https://editor.construct.net/r394/main.js:1138:44) at new d (https://editor.construct.net/r394/projectResources.js:3188:269) at pa.j (https://editor.construct.net/r394/main.js:1138:44) at lF.g.J.jwb.R (https://editor.construct.net/r394/projectResources.js:3194:90) at hTa (https://editor.construct.net/r394/projectResources.js:572:57) at dTa (https://editor.construct.net/r394/projectResources.js:570:117) at eTa (https://editor.construct.net/r394/projectResources.js:569:391) at https://editor.construct.net/r394/projectResources.js:569:454
Construct version: r394
URL: https://editor.construct.net/r394/
Date: Thu Jun 06 2024 01:06:12 GMT+0200 (Central European Summer Time)
Uptime: 68 s

Platform information
Product: Construct 3 r394 (beta)
Browser: Edge 125.0.2535.85
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36 Edg/125.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 Laptop GPU (0x00002520) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.

**Comment by XHXIAIEIN** [comment]
I found that it would add some items to the dialog, it would normal after restar the C3.
![image](https://github.com/Scirra/Construct-bugs/assets/45864744/ef492bc2-5a77-499c-a3a7-3c27bfa7c539)
