### ISSUE TITLE
 In macosx, the microphone stops working when exporting

### ISSUE THREAD

**Issue by ExeArt** [Scirra/Construct-bugs#8050]
## Attach a .c3p

>

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** <!macosx 12 6 2     Yandex browser.->

**First affected release:** 

## System details

<!Platform information
Product: Construct 3 r388.2 (stable)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: browser
Operating system: macOS 12.6.2
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 YaBrowser/24.4.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 4 gb (0.7%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (ATI Technologies Inc.)
Renderer: ANGLE (ATI Technologies Inc., AMD Radeon HD Verde PRO Prototype OpenGL Engine, OpenGL 4.1)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 2048
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
Audio information
System sample rate: 44100 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034) -->

<details><summary>View details</summary>

PASTE HERE

</details>
[Voice Recorder.c3p.zip](https://github.com/user-attachments/files/15636773/Voice.Recorder.c3p.zip)

**Comment by ExeArt** [comment]
After compilation, the microphone is no longer recognized
Macosx export to nvjs
this is an unmodified construct from the site
It recognizes the microphone only when viewing-and if you export to MACOSX nvjs, the microphone is not selected

**Comment by ExeArt** [comment]
111-
![222](https://github.com/Scirra/Construct-bugs/assets/171926788/521f8a48-aa2a-4bb5-be52-7da20c5a947d)
screenshot 1111 is in the project viewport-the microphone feels and the program works


screenshot 222 is after exporting the mac os x nvs project -the microphone does NOT feel and the program does NOT work
![222](https://github.com/Scirra/Construct-bugs/assets/171926788/125e6307-e7f2-49cf-8aee-7e8dc5d37c47)

**Comment by ExeArt** [comment]
everything works in the viewing mode

![111](https://github.com/Scirra/Construct-bugs/assets/171926788/80817876-499f-425b-92ae-53cdff0c839e)

**Comment by ExeArt** [comment]
https://disk.yandex.ru/d/uBBKtZqMiL400A
VIDEO OF ERROR

**Comment by ExeArt** [comment]
I looked
at the speech generation happening through the macosx VOICE OVER service
it selects the OUTPUT of audio devices
But the INPUT settings are NOT!

**Comment by ExeArt** [comment]
![Снимок экрана 2024-06-06 в 18 09 25](https://github.com/Scirra/Construct-bugs/assets/171926788/bb5bef01-894e-4eca-8b31-3cb7f333214e)

Onli OUT AUDIO DEVICE SETTINGS

There are no input settings

**Comment by ExeArt** [comment]
please help me set up the input source microphone, you need to select it somehow

The choice in the system settings does not help

**Comment by AshleyScirra** [comment]
I tried exporting the 'Voice recorder' example with NW.js v0.88.0 for Mac64 (ARM) and ran it on an M1 MacBook Pro running macOS 14.5. It worked fine, and detected the built-in microphone seemingly exactly the same way it did in the Chrome browser. So as far as I can see everything is working OK. Perhaps you need to update the system settings to allow microphone permission to the app.

**Comment by ExeArt** [comment]
Good afternoon
I've done it all 1000 times already
It does not help-the problem has not been solved!
