### ISSUE TITLE
com.google.android.play:core is outdated

### ISSUE THREAD

**Issue by C3GameDev** [Scirra/Construct-bugs#8058]
## Problem description

Hey,
there is an issue with Android exports / upload to Google Play:
Message from Google:
> com.google.android.play:core has added this note for core:1.8.0:
> 
> If your app is targeting SDK 34+ (targetSdkVersion), then the PlayCore SDK is outdated and will likely cause crashes in your app! Please update: https://developer.android.com/guide/playcore#playcore-migration

## Steps to reproduce

1. Just build a minimal android app and try to upload to Google Play, you will get a warning.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Are you sure you're not using any third-party addons that are in fact causing this? I'm not sure if or where any official Construct features use com.google.android.play:core - a quick search in our codebase yields nothing.

It's not clear what you mean by a "minimal android app" (does that include certain specific features?). This is why we require a project file.

**Comment by fredriksthlm** [comment]
@AshleyScirra  It is your share plugin, since have "Review" in it. The cordova plugin you use is very outdated.
It exists updated cordova plugins that use the review library instead of the core library.

**Comment by AshleyScirra** [comment]
I've updated the Share plugin and its corresponding Cordova plugin for the next beta to be compatible with Android 14 as per the migration guide.
