### ISSUE TITLE
cannot request Pointer Lock from js since r264

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8059]
## Problem description
I want to request the pointer lock from js, this is particularly important as I want to request it with `unadjustMovment: true` to work around https://github.com/Scirra/Construct-bugs/issues/7648
This was possible before but stopped working in r264 (the release that added the request pointer lock action to the mouse object)

## Attach a .c3p
[requestPointerLockFromJS.zip](https://github.com/user-attachments/files/15805437/requestPointerLockFromJS.zip)

## Steps to reproduce

1. start preview
2. click

## Observed result
pointer lock works in pre r264
pointer lock doesn't work in r264+

## Expected result
we can request pointer lock from js in all versions of c3

## More details
maybe the way to get the canvas needs to be changed and it's just a mistake in my implementation, but I didn't find much info about it. :/

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It seems to work fine for me. Construct adding its own support for this should not have affected the ability to also access the API from JavaScript.
