### ISSUE TITLE
Calling Pause Timeline after Play Timeline doesn't work

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8060]
Calling Pause Timeline after Play Timeline doesn't work

## Attach a .c3p
[New project (1).zip](https://github.com/user-attachments/files/15806361/New.project.1.zip)

## Steps to reproduce

1. Click the left-most button

## Observed result

Timeline runs.

## Expected result

Timeline should play and pause immediately.

Even waiting for 0.01 seconds won't help, I have to wait 0.1 seconds to make the Pause action trigger.
Also using Timeline.OnStart event to pause the timeline doesn't work.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
