### ISSUE TITLE
On loader layout complete not triggering (maybe race condition)

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8061]
## Problem description
On loader layout completed does not trigger in some circumstances, maybe it's some race condition.

## Attach a .c3p
[onLoaderLayoutNotTriggered.zip](https://github.com/user-attachments/files/15807018/onLoaderLayoutNotTriggered.zip)

## Steps to reproduce

1. preview layout 1 (or preview project)

## Observed result
stays on layout 1

## Expected result
goes to layout 2

## More details
My guess is it is some sort of race condition or similar, because for example if I add the text object to layout 1 too it works correctly for some reason.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
There was indeed a race condition here: if the loader layout completed very quickly (and having no objects on it means it completes instantly), then 'On loader layout complete' could trigger before 'On start of layout', which is an unexpected situation and so doesn't work correctly (in this case the 'Go to layout' action ends up being ignored, despite the trigger running). This is fixed for the next beta as it now guarantees 'On loader layout complete' triggers after 'On start of layout', even if it completes instantly.
