### ISSUE TITLE
Update 'The Rain Demo'

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8064]
## Problem description

The Rain Demo uses a deprecated 'Set web font' action.
https://fonts.google.com/specimen/Revalia

![Snipaste_2024-06-15_22-36-12](https://github.com/Scirra/Construct-bugs/assets/45864744/325bc4ab-24ff-4998-b4b0-79b9ba290332)

![Snipaste_2024-06-15_22-36-35](https://github.com/Scirra/Construct-bugs/assets/45864744/815e0145-2d0e-4fa1-9ce1-c7676d60f671)

## Attach a .c3p

https://editor.construct.net/#open=ghost-shooter-rain-demo

## Steps to reproduce

1.
2.
3.

## Expected result
Download the 'Revalia' font and replace
https://fonts.google.com/specimen/Revalia

## More details

Why does it have to be replaced?

Because this translation is not available in other languages, it will become [...]

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Updated the example for the next beta to avoid using deprecated features.
