### ISSUE TITLE
Performance Degradation on Deep Hierarchies - Wrap selection mode

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8067]
## Problem description

When creating complex and deep hierarchies within the editor, the performance of construct degrades greatly to the point it becomes unusable. Construct editor's performance should not degrade.

There are multiple use cases where hierarchies are very deep: windows with nested frames, complex character animations, etc.

## Attach
[construct-hier-performance.zip](https://github.com/user-attachments/files/15875567/construct-hier-performance.zip)

## Steps to reproduce

1. Create a deep hierarchy with several objects

![image](https://github.com/Scirra/Construct-bugs/assets/10860045/4795e84d-89c3-4cf9-8dae-08c0652aec25)

2. Set the selection mode to "Wrap" for the parent object.

![image](https://github.com/Scirra/Construct-bugs/assets/10860045/36478e15-ca67-424c-a99f-2e7cf1e5f2b2)

3. Try to transform the group of objects within the editor, simply move them around, performance will degrade greatly and the window becomes unresponsive.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/1dbedc00-4a55-4c81-a0e5-553cfc78de0b)

## Observed result

Performance degrades greatly.

## Expected result

Performance should not be affected.

## More details

Construct r395 and r388.2
Chrome

## System details
No crashes, just poor performance.

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by TackerTacker** [comment]
I can confirm this, the select mode doesn't even have to be wrap, once a hierarchy gets to a certain node depth I can just move a single node in the hierarchy tree and it will still lag or freeze my editor.

https://github.com/Scirra/Construct-bugs/assets/18266300/3b83770c-3fc1-4d82-95c0-b8abe564f28d

Here is the project file from the video, though it doesn't do anything different than the one already posted, I just added objects that aren't in a hierarchy as a comparison, showing that they don't have any issues.
[Hierarchy_performance_test_01.zip](https://github.com/user-attachments/files/16085487/Hierarchy_performance_test_01.zip)

**Comment by DiegoScirra** [comment]
These issues should be fixed on the next beta.
