### ISSUE TITLE
SDK v2 - ISDKInstanceBase._tick2() is never called despite having called ISDKInstanceBase._setTicking2 to true

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8068]
## Problem description

When creating a global plugin that ticks, the method ISDKInstanceBase._tick2() is never called despite having called ISDKInstanceBase._setTicking2(true).

## Attach a .c3p

Use the sample addon "singleGlobalPlugin", the problem presents there.

## Steps to reproduce

1. Call the ISDKInstanceBase._setTicking2(true) from the constructor of the addon.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/3b628f30-dcc8-4681-99fd-96d74b263c0e)

2. Override the _tick2 method and log anything to the console to test it.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/43310867-dc61-4487-99eb-1285dded47ab)

3. Create a sample project using the MyCustomPlugin from the singleGlobalPlugin example, and run the project.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/165550a3-c477-4e3b-ab75-24b871ceb4d4)

4.The message "TICK 2 running" should appear in the console, but the _tick2 method is never called.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/1ae88a72-64c8-45dd-885f-20ba7c8504b9)

## Observed result

ISDKInstanceBase._tick2() is never called 

## Expected result

ISDKInstanceBase._tick2() should be called

## More details
Construct beta r395

## System details
No exceptions nor errors appear in the console.

<details><summary>View details</summary>
PASTE HERE
</details>

**Comment by AshleyScirra** [comment]
Please provide a sample addon when filing SDK issues - it's much easier and less error prone than trying to copy code out of screenshots.

**Comment by AshleyScirra** [comment]
Fixed for next release.
