### ISSUE TITLE
SDK v2 - System plugin Save action throws an exception, thus the game is not saved.

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8069]
## Problem description

When using the singleGlobalPlugin example and testing the save and load actions from the System plugin, if you try to save the game it will throw an exception. Construct seems to be losing the _sdkInst which should have a reference to the plugin instance.

## Attach a .c3p

Create a sample project and install the singleGlobalPlugin from the examples for the SDK v2.
[save-test.zip](https://github.com/user-attachments/files/15880493/save-test.zip)

## Steps to reproduce

1. Install the singleGlobalPlugin addon from the SDK examples.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/d08ceaee-2537-4495-ab47-cfde5a3cdcf7)

2. Add the keyboard plugin to trigger the save and load actions from the system plugin as follows
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/9bf512b1-2cf9-4908-8a28-a183ede8dc72)

3. Run the project and press "S" to save the game, it will immediatelly throw an exception:
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/fdef41d0-3a0f-4f27-9c4b-23f6bd13f71b)

4. The reference on this._sdkInst attribute is null, it tries to backfall to trigger the _iScriptInterface.saveToJson() method which is invalid also.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/8a485bc6-b4e4-44ec-a78d-b8441b818d4a)

## Observed result
Game fails to save the state

## Expected result

Game must be saved correctly with no exceptions thrown.

## More details
Construct beta r395

## System details

<details><summary>View details</summary>
instance.js:33 Uncaught (in promise) TypeError: this._iScriptInterface.saveToJson is not a function
    at Instance.SaveToJson (instance.js:33:360)
    at objectClass.js:34:45
    at Array.map (<anonymous>)
    at ObjectClass._SaveToJson (objectClass.js:34:30)
    at C3Runtime._SaveToJsonString (runtime.js:122:199)
    at C3Runtime._DoSaveToSlot (runtime.js:119:149)
    at C3Runtime._HandleSaveOrLoad (runtime.js:116:476)
    at C3Runtime.Tick (runtime.js:85:501)
    at normal (runtime.js:8:38)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next release.
