### ISSUE TITLE
SDK v2 -  SingleGlobalInstance._setTicking(false) throws an exception when reading the Dispatcher 

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8070]
## Problem description

When using the singleGlobalPlugin and adding _setTicking(true) in the constructor, it starts ticking, but when you stop ticking by calling _setTicking(false), it immediatelly throws an exception about an undefined reference.

## Attach a .c3p

Install the singleGlobalPlugin and add an action to start ticking at the constructor, then stop ticking in the first tick at _tick() method.

## Steps to reproduce

1. Start ticking in the constructor of the singleGlobalPlugin example.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/961904bc-1611-414e-9018-aed378abb4f9)

2. Immediatelly stop ticking at the very first execution of _tick() method
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/93ba29b9-ca24-4dcf-9ae2-de0500a861eb)

3. Install the plugin in construct, run and the exception will be thrown.

![image](https://github.com/Scirra/Construct-bugs/assets/10860045/bd1eda3c-8a4f-479e-a2eb-3dd103606dc5)

![image](https://github.com/Scirra/Construct-bugs/assets/10860045/2b87943a-9348-4eaf-bf68-e6e95554031d)

## Observed result
Calling _setTicking(false) causes an exception.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/0f2d40fa-befa-44a2-92e4-70a5b277bba9)

The this._runtime reference is undefined, it may be a typo.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/1eb08efd-4a82-4381-91ed-74da2f456d04)

## Expected result

No exception should be thrown when ticking is stopped.

## More details
Construct beta r395

## System details

<details><summary>View details</summary>

ISDKInstanceBase.js:5 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Dispatcher')
    at SingleGlobalInstance._setTicking (ISDKInstanceBase.js:5:391)
    at SingleGlobalInstance._tick (2d37dfd5-4dc0-41cc-8dc3-758b88d07a52:23:8)
    at Array._p_tickFunc (ISDKInstanceBase.js:5:301)
    at EventHandler._FireNonCancellable (handler.js:7:27)
    at EventDispatcher.dispatchEvent (dispatcher.js:4:235)
    at C3Runtime.Step_AfterPreTick (runtime.js:90:214)
    at C3Runtime.Tick (runtime.js:85:393)
    at C3Runtime.Start (runtime.js:45:313)
    at async C3Runtime.Init (runtime.js:28:161)
    at async InitRuntime (workermain.js:8:1)

</details>

**Comment by AshleyScirra** [comment]
Please provide a sample addon when filing SDK issues - it's much easier and less error prone than trying to copy code out of screenshots.

**Comment by AshleyScirra** [comment]
Fixed for next release.
