### ISSUE TITLE
Keyboard object throws error, when auto complete from data-list on HTML element input

### ISSUE THREAD

**Issue by armandoalonso** [Scirra/Construct-bugs#8071]
## Problem description

Context, I am subclassing an HTML Element in typescript. I am attaching to the "keypress" on the input element. the subclassed object generates the datalist dynamically to show a set of commands when the user types.

If the keyboard plugin is in the project, when the user auto-completes from the data-list, an exception is thrown from the keyboard object when trying to identity which key code was pressed.  this only happens when the user invokes the auto complete suggestion using the mouse or the arrow keys

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at KeyboardInstance._OnKeyDown (runtime.js:5:208)

```
## Attach a .c3p

[input_error_debug.zip](https://github.com/user-attachments/files/15885092/input_error_debug.zip)

I have attached a zip file containing the folder project, this project has the keyboard plugin included, if you remove the keyboard plugin, there are no longer any errors in the dev console. 

## Steps to reproduce

1. open the project contained in the zip file 
2. run the project
3. click in the section that says "type your command here"
4. start typing draw-card 
5. when the auto-complete section becomes visible, click on the selection
6. this will trigger and exception in the keyboard
7. if you remove keyboard object and follow same steps there is no error

## Observed result

the keyboard plugin is listening for key-pressed events, and selecting an option from the data-list triggers that event on the keyboard object, but there is no keycode associated with that action which causes the exception to bubble up. see attached video

https://github.com/Scirra/Construct-bugs/assets/7579560/e6c77f03-2840-45dd-aa2f-745f2e8f1755

## Expected result

The keyboard option handles or ignores the case when picking from a datalist and no exceptions are thrown in the console.

## More details

**Affected browsers/platforms:** Edge was the only browser I tested

**First affected release:** Latest beta :  r395

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r395 (beta)
Browser: Edge 126.0.2592.56
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
Language setting: en-US

Local storage
Storage quota (approx): 1.1 tb
Storage usage (approx): 248 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4080 Laptop GPU (0x000027E0) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
It seems browsers fire keyboard events with no properties when autocompleting a datalist element, which is kind of odd. I've updated the next beta to ignore such events so no error is logged in this case.
