### ISSUE TITLE
SDK v2 - ISDKBehaviorInstanceBase constructor and _postCreate() are not being called after _loadFromJson()

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8074]
## Problem description

After loading the state of the game with the system action load which calls _loadFromJson() from the behavior, the constructor and tue _postCreate() method are never called, thus the object instance remains in an incomplete state because the initializations made in the constructor and further operations in the _postCreate() are never invoked.

Additionally, if you call the system action Save, then destroy the object instance, and then call the system action Load to restore the game state, only the constructor is called and _postCreate() is omitted somehow. 

Both scenarios were tested on the basic bullet behavior.

## Attach a .c3p

Behavior: [basic-bullet.zip](https://github.com/user-attachments/files/15890093/basic-bullet.zip)
Sample Project: [test-loadState.zip](https://github.com/user-attachments/files/15901265/test-loadState.zip)

## Steps to reproduce

Scenario 1:
1. Install the plugin and open the project attached
2. Run the project, allow the sprite to move a bit, then press "S" in the keyboard to save the state.
3. Open the developer console an look for the messages "initializing" and "Post create called" to confirm the constructor and the _postCreate() executions.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/6d959cbd-ad99-4728-bec3-c2fb71da7cfc)

4. Now press "L" in the keyboard to load the state and restore the game.
6. Review messages again and you will notice that neither the constructor nor _postCreate() methods where called, since there's no messages in the console.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/a6483348-ec66-4540-82e8-c0e94bf6fe21)

Scenario 2:
1. Install the plugin and open the project attached
2. Run the project, allow the sprite to move a bit, then press "S" in the keyboard to save the state.
3. Open the developer console an look for the messages "initializing" and "Post create called" to confirm the constructor and the _postCreate() executions.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/807648b7-89e7-4c01-b60c-db427fcdd3ee)

4. Press "D" in the keyboard to destroy the instance.
5. Now press "L" in the keyboard to load the state and restore the game.
6. Review messages again and you will notice that only the constructor was called, but the _postCreate() method wasn't.
![image](https://github.com/Scirra/Construct-bugs/assets/10860045/36acf7ff-d9e9-4d83-bae9-f18faf804adc)

## Observed result

Constructor and _postCreate() methods are not called correctly after loading the game state.

## Expected result

Constructor and _postCreate() methods should be called to complete the behavior initialization correctly.

## More details
Construct beta r396
Chrome

## System details

No crashes nor erros are thrown.

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
The provided project file requires the addon *Plugin Smart UI (ppstudio_smartui_plugin) by Pixel Perfect Studio*. Please provide a project file that does not use any other addons than the one you provided.

**Comment by sotano42** [comment]
> The provided project file requires the addon _Plugin Smart UI (ppstudio_smartui_plugin) by Pixel Perfect Studio_. Please provide a project file that does not use any other addons than the one you provided.

I removed the unnecessary addon.

**Comment by AshleyScirra** [comment]
Scenario 1 is not actually a bug. Construct will load state for existing instances where possible. So rather than destroy and then recreate an instance, it just loads state for the existing instance. If you put a log message in `_loadFromJson()` you can see this happening - it calls that when loading the savegame.

Scenario 2 looks more like a bug - `_postCreate()` should indeed be called in this case. I've updated the next release to ensure that is called when a new instance is created while loading a savegame. Note that as `_postCreate()` is called after creation when its full state is meant to be ready, the call order in this case will go `constructor`, `_loadFromJson()` to load its state, `_postCreate()` now the full state is ready, and then the `afterload` event fires. In comparison an ordinary created instance will only call `constructor` then `_postCreate()`.

**Comment by sotano42** [comment]
> Scenario 1 is not actually a bug. Construct will load state for existing instances where possible. So rather than destroy and then recreate an instance, it just loads state for the existing instance. If you put a log message in `_loadFromJson()` you can see this happening - it calls that when loading the savegame.
> 
> Scenario 2 looks more like a bug - `_postCreate()` should indeed be called in this case. I've updated the next release to ensure that is called when a new instance is created while loading a savegame. Note that as `_postCreate()` is called after creation when its full state is meant to be ready, the call order in this case will go `constructor`, `_loadFromJson()` to load its state, `_postCreate()` now the full state is ready, and then the `afterload` event fires. In comparison an ordinary created instance will only call `constructor` then `_postCreate()`.

**For scenario 1:** If you try to recreate the object without calling the constructor, we have no access to the initial properties this._getInitProperties(); The method throws an exception if we try to call it from within the _postCreate. What's the method to get to the properties then? I ask it because the scenario 1 behaves the same as when restarting the layout, I can't access the initial properties of the object to complete the instance state.

**Comment by AshleyScirra** [comment]
Why would you need initial properties when loading an object? In that case you want to load properties from the saved data, not the properties specified in the editor.
