### ISSUE TITLE
Open local file bug

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8075]
## Problem description

Drag&Drop func.zip you can open but "Menu>Project>Open local file" not work.

![image](https://github.com/Scirra/Construct-bugs/assets/54614906/489cab20-a9c6-4c97-83b3-6632c6ebd72f)

## Attach a .c3p
[func.zip](https://github.com/user-attachments/files/15890438/func.zip)

## Steps to reproduce

1. Menu>Project>Open local file
2. Select func.zip

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is by design. Dragging and dropping a .zip file to open it exists only to make it easier for us to deal with bug reports, as GitHub does not allow the .c3p extension.
