### ISSUE TITLE
Sort Z Order [Enhancement]

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8077]
## Problem description

Sort Z Order not working with hierarchy. Working with so many objects and zOrdering really nightmare. "Sort Z Order" action should be work with hierarchy too.
If you think this is a feature request, Referring this topic: https://github.com/Scirra/Construct-feature-requests/issues/9
You can also add this as a complementary feature.

## Attach a .c3p

[zOrder.c3p.zip](https://github.com/user-attachments/files/15891858/zOrder.c3p.zip)

## Steps to reproduce

1. Run project.

## Observed result

![a](https://github.com/Scirra/Construct-bugs/assets/54614906/e6f0279b-53d5-4e93-909a-96568479e6d1)

## Expected result

Must be properly z-ordered with skeleton parts

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by WilsonPercival** [comment]
[SceneGraphTest.zip](https://github.com/user-attachments/files/15893807/SceneGraphTest.zip)

**Comment by WilsonPercival** [comment]
[SceneGraphTest.zip](https://github.com/user-attachments/files/15893933/SceneGraphTest.zip)

**Comment by AshleyScirra** [comment]
This appears to be a feature request, so please submit it to the feature request tracker.
