### ISSUE TITLE
Audio : Keeps playing for few ticks after stopping it

### ISSUE THREAD

**Issue by Kashin-Ginn** [Scirra/Construct-bugs#8080]
## Problem description

Audio keeps playing after few ticks after using stop audio tag in action

## Attach a .c3p

[bug_audio_onLayoutRestart.zip](https://github.com/user-attachments/files/15935821/bug_audio_onLayoutRestart.zip)

## Steps to reproduce

Just spam SPACE in the project, the following steps will be done automatically

1. Stop audio "soundTag"
2. Restart
3. Check if audio "soundTag" is playing or not
4. If audio tag not playing, then play

## Observed result

After spamming SPACE to stop sound tag and restart the layout, the audio sound keeps playing for few ticks, so the next condition "is audio tag playing" sometimes returns true

## Expected result

Audio should stop playing instantly after stopping it, so that the next condition to check if it is still playing should returns false

## More details

**Affected browsers/platforms:**  Chrome (not sure about others)

**First affected release:**  This project is from latest r396, not sure about older versions

## System details

No crash, just a simple C3 bug, easy to reproduce
<details><summary>View details</summary>

PASTE HERE

</details>
@AshleyScirra

**Comment by AshleyScirra** [comment]
Minimal repro: [issue8080.zip](https://github.com/user-attachments/files/16729694/issue8080.zip)
Immediately after the 'Stop' action 'Is tag playing' should return false, but it still indicates playing instead.

**Comment by AshleyScirra** [comment]
This looks like the 'Stop' equivalent of some older issues involving the 'Is playing' state not immediately updating after a 'Play' action (#2426, #2528). It should be fixed in the next beta.
