### ISSUE TITLE
Boss fireballs won't continue past spawning and are destroyed incorrectly. 

### ISSUE THREAD

**Issue by ironhide1975** [Scirra/Construct-bugs#8083]
It's hard to explain, but I had a level with a Mega Man Style boss on it. When the boss rolled into the screen, and attempted to spawn a bullet, the bullet would only travel so far before being destroyed. I spent a few hours trying to diagnois this issue and found that another character in the same part of the level was causing the issue, although I don't know why. When I deleted and recreated a copy of the character, the issue went away and spawned fireballs worked correctly

## Attach a .c3p

I clicked to add a file and my browser won't let me attach it. The cp3 is greyed out. How do I get this to you?

## Steps to reproduce

1. Play Wily Level 4
2. Click 3 to jump to Boss
3. Enter Boss room

## Observed result

Currently the issue is fixed, but I don't know why before there was a problem rendering the bullets. Previously the spawned fireballs would dissappear after a few seconds. 

## Expected result

Bullets should render and fire correctly towards player.

## More details

This was done in Safari on MacOs

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by ironhide1975** [comment]
[Mega Max.c3p.zip](https://github.com/user-attachments/files/15942140/Mega.Max.c3p.zip)

**Comment by WilsonPercival** [comment]
If the problem cannot be reproduced, what do you want in that case?

**Comment by AshleyScirra** [comment]
I'm afraid we cannot accept bug reports with such large projects, as these are impossible to debug and are commonly just mistakes in event sheets. Please see the bug report guidelines. If you need help building your project, try posting to the forum instead.

**Comment by ironhide1975** [comment]
I’m telling you this is not a problem with event sheets. This is a bug that occurred in the app based upon some character on the scene which makes no sense. I have tried posting stuff to the forums before and no one responds to them. I’m trying to help you make your product better. Give me some time to at least respond before you close the bug out.
