### ISSUE TITLE
App Icon Maskable is not showing

### ISSUE THREAD

**Issue by Alaadel** [Scirra/Construct-bugs#8086]
## Problem description

The project is using icons set to "App Icon Maskable", but they are not showing. It shows Cordova icon as the app icon.

## Attach a .c3p
[Downloads.zip](https://github.com/user-attachments/files/15991342/Downloads.zip)

## Steps to reproduce

1. Build as Android debug apk

**Comment by fredriksthlm** [comment]
"App icon maskable" is not related to Android/Cordova builds. So the correct behavior is to show the Cordova icon.

**Comment by Alaadel** [comment]
I thought "App icon maskable" is a version of "App icon" but offer more flexibility.
- If I set both, would one override the other, or each has a separate use by the system?

**Comment by fredriksthlm** [comment]
You can read the [manual](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/icons-splash)

_Maskable_ is for webapps, _adaptives_ are for android, _icon_ is the general one.

**Comment by AshleyScirra** [comment]
As noted in the documentation, "App icon maskable" is currently for PWAs only.
