### ISSUE TITLE
Error creating WebGL renderer

### ISSUE THREAD

**Issue by JetGames777** [Scirra/Construct-bugs#8087]
## Problem description

2% of players who play our games have an error "Error creating WebGL renderer:" this error occurs when starting the game and does not allow it to fully load. As a result, we lose about 2% of players, which is an awful lot. This problem we observe in all games, except those that were created on r317

## System details

Basically, the error occurs in Chrome 109.0.0 browser.
But it also occurs in 
- Opera 95.0.0
- Edge 109.0.1518
- Safari 17.5.0 
- Chrome 86.0.4240
- Chrome 107.0.0

**Comment by AshleyScirra** [comment]
I'm afraid this is beyond our control, and usually comes down to problems with the device's graphics driver. The best thing to do is install any available system software updates. I'd also point out the most recent version of Chrome and Edge is v126, so v86, v107 and v109 are quite far out of date now. For example Chrome 86 is 4 years out of date. It should be auto-updating, so it's not clear why it's out of date, but updating it to the latest version may well fix the problem.
