### ISSUE TITLE
Playable Ads exports files that "need a software update"

### ISSUE THREAD

**Issue by dhiavoodoo** [Scirra/Construct-bugs#8090]
## Problem description

Whenever exporting any Construct Project in "Playable Ad" format, the exported file shows the following error message : "Software update needed
This content is not supported because your device's software appears to be out-of-date. Try installing any available software updates. Alternatively try on a different device.

Missing features: Modern JavaScript support
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36".

I tested all the different export parameters for Playable Ad, but this didn't change anything.

## Attach a .c3p
[Example file](https://drive.google.com/file/d/1HDlpw-ysnNjRqvaPaQIbnwrW6rn0YOE-/view?usp=sharing)

## Steps to reproduce

1. Open the Construct Project
2. Export to Playable Ad format (choose any parameters)
3. Unzip and open the exported HTML file in any browser, desktop or mobile.

## Observed result
An error message keeps the playable from being running correctly 
"Software update needed
This content is not supported because your device's software appears to be out-of-date. Try installing any available software updates. Alternatively try on a different device.

Missing features: Modern JavaScript support
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36".

## Expected result
The playable ad is able to open / be played correctly.

## More details
This has been happening since the last Construct stable update.
This occurs on Android phones running Edge, as well as PCs running Chrome, Edge, and other browsers (latest version).

**Affected browsers/platforms:** 
Chrome/Firefox/Safari, Windows/macOS/Android

**First affected release:** 
Worked in r388
Not sure if the issue started with r388.2 or r397

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r397 (stable)
Browser: Chrome 126.0.6478.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 121 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x0000A7A0) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by cemalacikgoz** [comment]
We have the same problem and waiting for a fix.

**Comment by AshleyScirra** [comment]
I would advise to use the web (HTML5) export instead of the Playable Ad export. The web export gives you a zip of assets which most platforms already accept. The Playable Ad export tries to produce a single-file export, which is extremely complicated and difficult to maintain, ending up with problems like this, and is usually unnecessary anyway these days. In future we will likely switch the Playable Ad export to produce a zip of assets like the HTML5 export does and you can already use that option today.

**Comment by dhiavoodoo** [comment]
Hi @AshleyScirra ,
I second @cemalacikgoz's reply, we use this export format because these platforms only accept single .html file exports unfortunately :/

**Comment by AshleyScirra** [comment]
A single HTML file is a total nightmare to support. I do not know how much longer it will be feasible to keep supporting the single-file option. Please ask them to support zips of web assets like other platforms do - both Facebook and Google playable ads now support zips of web assets, and we can easily support that long-term.

**Comment by AshleyScirra** [comment]
This should be fixed in the next beta, but as I noted, please use the zip option wherever possible or ask the ad providers to support it if they don't accept it - we will probably have to retire the single-file mode sooner or later as it's so difficult to support.
