### ISSUE TITLE
Semi-Transparent Boxes Around Sprite?

### ISSUE THREAD

**Issue by shlomi93** [Scirra/Construct-bugs#8093]
## Problem description

I'm developing a simple game, and each sprite have smei-transparent box around it.
It's not part of the image, it's being generated in the software (latest Construct 3 paid version).
I've attached an image to show what I'm talking about.
How can I remove these boxes??

## Attach a .c3p
[bug_show_case.zip](https://github.com/user-attachments/files/16041337/bug_show_case.zip)

## Steps to reproduce

1. download the c3p file
2. preview the game_layout
3. observe the semi-transparent box around the shoe sprite

## Observed result

semi-transparent box around the shoe sprite

## Expected result

That there will be no semi-transparent box around the shoe sprite

## More details
In Construct's help forume the user dop2000 suggested trying to use version r388.2, and indeed there's no boxes in that version.
I cannot use that version since after exporting the game as html5, I cannot run it in the browser due to bad version of chrome/js/firefox, and I have the latest of all!
Tried NoSave behaviour on affected sprites (suggested in Construct forum), no change...

_**Another note:**_
if I open a new project, and copy all the layouts and the events and all, the boxes darkness is being changed to a random strenght.
Sometimes it's darker, sometimes it's almost invisible, and sometimes it's not visible at all!
It's hard to catch that invisible case, and even if I've caught it, every small change in the project can reproduce these boxes.

**Affected browsers/platforms:** Chrome/Firefox/Safari, Windows/IOS/Android

**First affected release:** worked in r388.2 but broke in r397

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r397 (stable)
Browser: Chrome 126.0.6478.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 286 gb
Storage usage (approx): 26 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics 630 (0x00003E9B) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by Kashin-Ginn** [comment]
There's no bug, your shoe sprite clearly has some color, you need to clean it.

**Comment by shlomi93** [comment]
Correct, there is some color, but it's generated by the software.
My files are clean! (photoshoped) 
The fill tool not working, also selecting blank area then deleting it doesn't work.
BTW: the fill tool also changing the colors of the image and make it a bit transparent! (see short vid)

https://github.com/Scirra/Construct-bugs/assets/33894162/86bf1532-062d-42f5-adba-6a5fb28a2112

**Comment by Kashin-Ginn** [comment]
[shoe_v2.zip](https://github.com/user-attachments/files/16045166/shoe_v2.zip)

Hello, 
I think it will be harder to test your project even by the experts, since your images already have some alpha.

Can you reproduce the issue with this new PNG file which I cleaned rapidly using photoshop?
Just replace the image and do the same test (import/save/export etc) using the required C3 version and check if the issue is happening again.

If it doesn't, means all your images were exported with some alpha.

Else if you reproduce it again... means there's indeed a bug.

**Comment by shlomi93** [comment]
Thanks for quick replay,
I reproduce the issue with shoe_v2.
All I did is taking the original [bug_show_case.zip](https://github.com/user-attachments/files/16041337/bug_show_case.zip) that I've uploaded, and just replaced it with your [shoe_v2.zip](https://github.com/user-attachments/files/16045166/shoe_v2.zip).
The boxes are still there :(

**Comment by shlomi93** [comment]
### New Info:
I did try again several more times and noticed that even in version 388 the issue is stil there.
But it's random! same process causing different results.

Process:
1. open a new project
2. copy the background from another construct 3 project (copy-paste from one windows to the other)
3. copy-paste another 2 sprites.
4. run game.

I did that twice, one has boxes, the other doesn't. I screenshot the results so you could see.

TRY 1:
![try1](https://github.com/Scirra/Construct-bugs/assets/33894162/83df0a98-b449-4355-956d-12e64f6ad66e)

TRY 2:
![try2](https://github.com/Scirra/Construct-bugs/assets/33894162/d8477280-f370-4a7a-ab8f-a8337a9eeb7e)

**Comment by AshleyScirra** [comment]
The problem in the originally provided project is the object sprite_shoe3 has a background alpha of 2, not 0, so there is in fact a slightly semitransparent white rectangular background on it, which is what you're seeing.

If in some situation Construct is incorrectly setting a background alpha then please file a separate issue for that with reliable steps to reproduce the problem.

**Comment by shlomi93** [comment]
> The problem in the originally provided project is the object sprite_shoe3 has a background alpha of 2, not 0, so there is in fact a slightly semitransparent rectangular background on it, which is what you're seeing.
> 
> If in some situation Construct is incorrectly setting a background alpha then please file a separate issue for that with reliable steps to reproduce the problem.

What? Have you read the whole post?
The original image doesn't have any alpha! it's Construct 3 that adds this alpha.

Look at the video, look on my last msg here, Construct 3 is generating alpha and changes colors of the image!
Same process with same image gets different results - this is 100% a bug!

This is not a problem in Construct 2 Free version - over there, the same image doesn't generate these boxes!

Note that [Kashin-Ginn](https://github.com/Kashin-Ginn) thought this was an image issue as well and he has provided a clean image, and yet, the results are the same, so the issue is not the image.

BTW: this happens with other images in other projects in Construct 3.

**Comment by AshleyScirra** [comment]
Please file a new issue if you still believe there is a problem. The original issue states that the project should be opened and inspected, but it sounds like you're talking about a different problem, in which case a new issue should be filed. We need every issue to follow the bug report guidelines - it very quickly becomes very confusing and difficult to deal with issues which can only be pieced together from comments, and that often means the full bug report guidelines have not been followed, which often then means the issue is impossible to investigate.

**Comment by shlomi93** [comment]
Why fileing a new issue?
All the info, and more,  is here in this thread.
I've overcome this bug by opening a new project and copy all the layouts, events, and objects.
Sometimes Construct puts the boxed around sprites, and sometimes not. after several tries I get a clean project.
This is 100% a bug, random results for the exact same process.
I will say that the fact that I'm showing you the issue is on your side, yet getting this kind of answers, shade some light on the quality of the support and service Construct provides.
I will be happy if you will solved this BUG.

**Comment by AshleyScirra** [comment]
We require all issues are filed following the bug report guidelines. The issue you are talking about has not yet been filed following the guidelines. If you do file it following the guidelines we will investigate it.
