### ISSUE TITLE
Text doesn't render properly in 3D

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#8097]
## Problem description

This is a weird one. The text object, when placed in 3D doesn't render when Z elevation is too high, but changing the FOV changes the max Z elevation that can be used. However, when a text has been rendered at least once, it keeps rendering well until the end of the layout even if the FOV changes back

## Attach a .c3p

[Render Text Bug.zip](https://github.com/user-attachments/files/16063859/Render.Text.Bug.zip)

## Steps to reproduce

1. Open project
2. Shift or Space to move camera back and forth
3. Mouse wheel to change FOV

## Observed result

Without changing the FOV, the text eventually stops rendering, changing the FOV makes other text objects get displayed

## Expected result

Text should render properly

## More details

https://github.com/Scirra/Construct-bugs/assets/11213825/462791d4-df39-4c7c-b78e-b9cc9cff796f

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Text isn't really designed to work in 3D - it is essentially vector content and relies on a 2D scale value to determine the rendering resolution. In 3D with an oblique camera angle that means there isn't a 2D scale that can be calculated, so the engine just does whatever calculation it would use in 2D and goes with that.

That being said it didn't work out very well in this case. I've fixed the calculation to give a better result when using 3D camera like this example - but that doesn't solve the fundamental problem that text won't always look correct in 3D.
