### ISSUE TITLE
R398 Beta - Instance View Drag/Drop to create hierarchy crashes construct

### ISSUE THREAD

**Issue by justifun** [Scirra/Construct-bugs#8099]
## Problem description
Instance View Dragging and dropping a sprite to create hierarchy crashes construct

If you have 2 sprites in the instance view window and you drag one on top another to create a hierarchy it crashes construct

## Attach a .c3p
Attached [instanceViewBug.zip](https://github.com/user-attachments/files/16070866/instanceViewBug.zip)

## Steps to reproduce

1. Create 2 sprites
2. Open the new instance view window and drag one sprite on top another in the list to create a hierarchy

## Observed result

Red Screen "Ooops something went wrong" crash. (See crash log below)

## Expected result

Sprite 1 should have become the child of sprite 2

## More details

**Affected browsers/platforms:** 
Chrome (only one tested)

Broken in initial release of beta 398 with release of new instance view window

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r398/components/bars/instanceBar/instanceBar.js, line 61, col 496
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'oL')
Stack: TypeError: Cannot read properties of undefined (reading 'oL') at CCG.ba.w7 (https://editor.construct.net/r398/components/bars/instanceBar/instanceBar.js:61:496) at Array. (https://editor.construct.net/r398/components/bars/instanceBar/instanceBar.js:33:357) at CCG.vh.g.J.YFa.dispatchEvent (https://editor.construct.net/r398/main.js:1280:399) at Ah (https://editor.construct.net/r398/main.js:384:228) at d.Fd (https://editor.construct.net/r398/main.js:1663:13) at Rb.te (https://editor.construct.net/r398/main.js:1654:89)
Construct version: r398
URL: https://editor.construct.net/r398/
Date: Tue Jul 02 2024 08:30:44 GMT-0700 (Pacific Daylight Time)
Uptime: 18.3 s

Platform information
Product: Construct 3 r398 (beta)
Browser: Chrome 126.0.6478.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.100000023841858
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4090 (0x00002684) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by DiegoScirra** [comment]
We will likely make a hot fix for this, it slipped by at the last moment.

**Comment by XHXIAIEIN** [comment]
It could still crash when using the right click context menu action "Removing from parent" or "Remove all children" in the Layout View 

[issue.c3p.zip](https://github.com/user-attachments/files/16114739/issue.c3p.zip)

![Snipaste_2024-07-06_11-00-31](https://github.com/Scirra/Construct-bugs/assets/45864744/42e4f08f-f041-45f3-b915-6e70fe208879)
