### ISSUE TITLE
Crach when cancelling tilleset edition

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-bugs#8103]
## Problem description

I remember editing the tile size on the tilleset, then I don't remember, I undid "Ctrl + Z" then it spit, I don't know why.

PASTE HERE

Error report information
Type: unhandled exception
File: https://editor.construct.net/r398-2/main.js, line 1079, col 505
Message: Uncaught RangeError: Invalid array length
Stack: RangeError: Invalid array length at Array.push () at np.EVb (https://editor.construct.net/r398-2/main.js:1079:505) at np.Cqb (https://editor.construct.net/r398-2/main.js:1080:86) at VUb (https://editor.construct.net/r398-2/plugins/allEditorPlugins.js:48:65) at https://editor.construct.net/r398-2/plugins/allEditorPlugins.js:357:443 at mw.op.I7c (https://editor.construct.net/r398-2/projectResources.js:950:76) at e1b.Instance.Cg (https://editor.construct.net/r398-2/plugins/allEditorPlugins.js:357:236) at d.Cg (https://editor.construct.net/r398-2/projectResources.js:894:373) at d.Cg (https://editor.construct.net/r398-2/projectResources.js:1461:315) at d.Cg (https://editor.construct.net/r398-2/projectResources.js:1416:3)
Construct version: r398.2
URL: https://editor.construct.net/r398-2/
Date: Sun Jul 07 2024 14:36:36 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 4163.4 s

Platform information
Product: Construct 3 r398.2 (beta)
Browser: Chrome 126.0.6478.62
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

**Comment by AshleyScirra** [comment]
Please follow the bug report guidelines otherwise unfortunately it is impossible for us to help.
