### ISSUE TITLE
Tilemap mirror tile when drawing bug 

### ISSUE THREAD

**Issue by AndreYin** [Scirra/Construct-bugs#8105]
## Problem description
Pressing X (or the mirror button on the tilemap bar) while having a copied tile, and selecting a new tile from the tilemap bar changes the brush back to the previous copied tile instead of the newly selected one.

## Attach a .c3p
https://1drv.ms/u/s!AuQM7MihYyx4tMN7B3NjkaBXYa0mQA?e=nN4p43

## Steps to reproduce

1. Open the capx
2. Select the tilemap object and click the pencil to start editing it
3. Hold shift and left click the tile with the rock on water
4.  In the tilemap bar, click any other tile
5. Press X (or click the mirror button) 

## Observed result
The brush reverts to the previous tile .

## Expected result
The brush should mirror the currently selected tile.

## More details

Another weird thing that's happening in this project is that if you edit the tilemap image the drawn tiles seem to change.
To do this:

1. Double-click the tilemap object to edit the art
2. Try changing the green color to any other color
3. Close the window, all grass tiles will become rock tiles

**Affected browsers/platforms:** 
Tested on Edge, running C3 as an app

**First affected release:** 
r398.2

**Comment by AndreYin** [comment]
One thing I also noticed is that even if you close the project and open a completely new project, if you click any tile in the tilemap bar and press X it will try to use the previously copied tiles.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta, was introduced when trying to fix the previous issue.
