### ISSUE TITLE
unadjust mouse movement breaks fov

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8110]
## Problem description
Using unadjusted mouse movement in pointer lock breaks dynamic FOV during mouse movement.

## Attach a .c3p
[unadjustMouseIssue.zip](https://github.com/user-attachments/files/16181186/unadjustMouseIssue.zip)

## Steps to reproduce

1. start preview
2. click to pointer lock
3. hold the right mouse button to change FOV (don't move the mouse)
4. move the mouse while the right mouse button is still held

## Observed result
The FOV changes correctly on right mouse button hold, but resets once you start moving the mouse.

## Expected result
The FOV stays at 24 while the right mouse button is held, even with mouse movement.

## More details
**If you disable the unadjust mouse movement it works as expected**

**Comment by AshleyScirra** [comment]
This issue is nothing to do with FOV - it's the browser incorrectly tracking button input in this mode. It looks like a Chrome bug, so I filed it here: https://issues.chromium.org/issues/353249342
Closing this issue as it will be followed up there.
