### ISSUE TITLE
Platform & Solid collision bug

### ISSUE THREAD

**Issue by vendaraa** [Scirra/Construct-bugs#8113]
## Problem description

The platform behavior has a bug where, upon colliding with a wall, there is often a gap between the platformer and the wall. Additionally, the size of this gap varies each time.

## Attach a .c3p
[.c3p file](https://mega.nz/file/kQZggSKL#t6KtBkSbuIxCrwTyyjPxDUCnbHbOn-QVB5p4mv_JsCA)

## Steps to reproduce

1. Create a sprite with a platform behavior
2. Create walls with the solid behavior
3. Move the platformer at the wall multiple times

## Observed result

Each time the platformer hits the wall, there is a different sized gap between.

## Expected result

The platformer should be perfectly aligned to the solid object

## More details

https://github.com/user-attachments/assets/baf4b30c-ea17-413e-8cf4-fb0624bc3c27

**Affected browsers/platforms:** This bug seems to appear anywhere. Preview, nwjs, webview...

**First affected release:** I sadly can not provide a clear version, the only thing i know is, that in February 2023 this problem didn't exist for sure.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r397 (stable)
Browser: Chrome 126.0.6478.127
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 24
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 279 gb
Storage usage (approx): 1.1 gb (0.4%)
Persistant storage: Yes

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3080 Ti (0x00002208) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
The Platform behavior doesn't work that well with really tiny objects, and the object here is only 4x4 and uses fullscreen mode to scale it up much bigger. There are some places in the platform logic it uses a few pixels of tolerance which means it can become noticable with such tiny objects. I would advise to just use a larger object.

**Comment by vendaraa** [comment]
What throws me off is, that i used the exact same setup for [my game](https://www.construct.net/en/free-online-games/pixel-speedrun-2363/play?) few years ago. It worked perfectly fine. I even copy pasted the player to the new project.
