### ISSUE TITLE
Physics behavior causing black screen

### ISSUE THREAD

**Issue by epic20** [Scirra/Construct-bugs#8115]
## Problem description

I was trying to make a ragdoll and then some of the body parts with physics enabled makes the screen go black.

## Attach a .c3p

[Action.zip](https://github.com/user-attachments/files/16232711/Action.zip)

## Steps to reproduce

There is a family called "Ragdoll" with the sprites that have the word "Physic" at the end of the name. (I don't think the family object is the issue)

For some reason when enabling the physics behavior on "HeadPhysic", "TopLeftArmPhysic" and "LeftBottomArmPhysic" It works fine
but the rest of the other sprites with physics behavior causes the screen to go black.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please provide a minimal project using the fewest objects and events as possible, as per the bug report guidelines. I'm afraid more complex projects like this are practically impossible to debug, and so we need the minimal project in order to be able to help you.

**Comment by AshleyScirra** [comment]
I cannot observe any problem with that project. It seems to work fine.
