### ISSUE TITLE
Set master volume not working on music files, on mobile browsers

### ISSUE THREAD

**Issue by JMartenJ** [Scirra/Construct-bugs#8116]
## Problem description

The action "Set master volume" doesn't affect audio files imported as Music. Specifically, it doesn't work on mobile browsers when the project is exported as a html5 project.

## Steps to reproduce

1. Create an On start of layout event.
2. Import an audio file as Music.
3. Add the Audio action Play, select the imported file.
4. Add the Event Set master volume to -200db.
5. Export as a web project, upload to your preferred site.

## Observed result

When played on a mobile device, the sound is not lowered.

## Expected result

The music track should not be audible.

## More details

**Affected browsers/platforms:** Tested on an iPhone device. Tested on both Safari and Firefox.

**First affected release:**

## System details

<details><summary>View details</summary>

</details>

**Comment by AshleyScirra** [comment]
This seems to work correctly for me in Chrome for Android. Is this something that only happens for you on iOS?

**Comment by AshleyScirra** [comment]
This is a bug in Safari. I've filed it with Apple here: https://bugs.webkit.org/show_bug.cgi?id=276813

In the mean time I've put in place a workaround for the next release.
