### ISSUE TITLE
Platform Is On Floor bug

### ISSUE THREAD

**Issue by Pigpud** [Scirra/Construct-bugs#8119]
##

When jumping onto a platform with the jump through behavior added to it, the condition "Is On Floor" occasionally reads false even when moving around on the platform.

## 
[Platform_Bug.zip](https://github.com/user-attachments/files/16249188/Platform_Bug.zip)

## Steps to reproduce

1. Open the project.
2. Move around with arrow keys.
3. Jump onto the blue platform.

## Observed result

When the platform is jumped on, the condition Is On Floor will read false, even though the player sprite is on it. It might take several tries to replicate. 

## Expected result

Condition should read true.

## More details

https://github.com/user-attachments/assets/a5c9da3a-c14e-4dde-b6e2-2ff8ec131e31

**Affected browsers/platforms:** 

**First affected release:** Discovered while using stable r397. I was able to replicate in the last beta as well.

## System details

PASTE HERE

**Comment by AshleyScirra** [comment]
I can't reproduce any problem with this project. It's also essential to provide a reliable reproduction project wherever possible - if it only happens say 1 out of 10 times, that alone makes it extremely difficult to fix, as we may have to try something 20+ times before we fix it, and if each time we don't know if our change has worked or not, it's incredibly hard to make any progress. So if you still think there is a problem that needs to be investigated here I would suggest to file a new issue with an automatic reproduction project that doesn't require any user input and reliably demonstrates the problem.
