### ISSUE TITLE
cannot start debug preview from event sheet if a second project has been opened

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8121]
## Problem description
I cannot start the debug preview from an event sheet if a second project has been opened.

## Attach a .c3p
empty project

## Steps to reproduce

1. create an empty project
2. create another empty project (keep both open)
3. click on the event sheet of the first project
4. try starting a debug preview

## Observed result
nothing happens

## Expected result
the debug preview starts,

## More details
the normal "preview layout" works with the same repro steps, hence I think it's a bug.
This doesn't seem to be caused by the preview code changes as it also doesn't work in R398.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
