### ISSUE TITLE
Image glitch during r400 

### ISSUE THREAD

**Issue by LucasJanela** [Scirra/Construct-bugs#8122]
Image glitches during r400

project link ->[Power Gem Fetcher.zip](https://github.com/user-attachments/files/16272879/Power.Gem.Fetcher.zip)

When the game progress, some glitched pixels appear on transparent areas of the images
 
When I started to test the new update from construct 3, that's r400, during preview mode, my game started to show glitched pixels on sprites, green tiledBackgrounds 

I wanted to don't show glitched pixels

It worked on r397

**Comment by AshleyScirra** [comment]
I ran the project and couldn't see anything wrong in the first 30 seconds, so it looks fine to me. We don't normally accept full projects anyway - please see the bug report guidelines and ensure any issues you file comply with them, as otherwise usually it's impossible for us to help.
