### ISSUE TITLE
Instance Bar doesn't update when copy pasting via keyboard shortcut

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8125]
## Problem description
The Instance Bar doesn't update when copy pasting via keyboard shortcut.

## Attach a .c3p
not project specific

## Steps to reproduce

1. make sure the instance bar is visible
2. copy and paste an instance via ctrl+c, ctrl+v

## Observed result
the instance bar doesn't show the newly created instances

## Expected result
the instance bar updates on the paste

## More details
It works with copy pasting through the context menu, as well as Ctrl+X, Ctrl+V.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
