### ISSUE TITLE
Export statistics: NaN tb script size

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8126]
## Problem description
export statisitcs incorrectly shows total script size: 
![image](https://github.com/user-attachments/assets/67a031c3-e5ed-4f89-aca4-d8297c0921b3)

## Attach a .c3p
[scriptSize.zip](https://github.com/user-attachments/files/16321850/scriptSize.zip)

## Steps to reproduce

1. export to Web (HMTL5), I didn't test others
2. show export statistics

## Observed result
total script size incorrect:
![image](https://github.com/user-attachments/assets/a056a34f-7517-401b-a3a0-29e14372e31e)

## Expected result
A usable total script size is shown

## More details
This doesn't seem to reproduce on some circumstances, for example with minification

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
