### ISSUE TITLE
Incomplete container on loader layout

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8127]
## Problem description
if there is an incomplete container instance on the loader layout the project doesn't run.

## Attach a .c3p
[incompleteContainerLoader.zip](https://github.com/user-attachments/files/16331216/incompleteContainerLoader.zip)

## Steps to reproduce

1. note that layout 1 is set as the loader layout and has an instance that is in a container but that container object isn't on the layout
2. start preview of Layout 1 (or start project preview)

## Observed result
black screen and error:
TypeError: Cannot read properties of null (reading 'IsInContainer')

## Expected result
Maybe no error, maybe better error.
I understand that this is a difficult case and I am not entirely sure what should happen here as loading of new instances is disallowed on loader layouts.

## More details
This has been reported before but with a less reliable repros:
https://github.com/Scirra/Construct-bugs/issues/5894
https://github.com/Scirra/Construct-bugs/issues/6689

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
