### ISSUE TITLE
Overlapping condition fails in certain conditions

### ISSUE THREAD

**Issue by Everade** [Scirra/Construct-bugs#8128]
## Problem description
The "Is overlapping another object" condition does not return true, if the overlap happens outside the viewport, and the layer scale of both layers vary.

## Attach a .c3p
[issue8128.zip](https://github.com/user-attachments/files/16340594/issue8128.zip)

## Steps to reproduce
1. Move the cursor over the red box
2. Click any mouse button to destroy the box
3. The red box can not be destroyed even though it should

## Observed result
The green boxes, which are still inside the viewport, or partially, can be destroyed as expected. However the red box, which is entirely outside the viewport, can not be destroyed because the overlap condition fails.

## Expected result
The "is overlapping another object" should work outside the viewport area, even when the layer scales are set differently.

## More details
When the layer scale of layer 0 is set to 1, the red box can be destroyed.

**Affected browsers/platforms:**
Chrome

**First affected release:**
Unknown

## System details
<details><summary>View details</summary>
Platform information
Product: Construct 3 r400 (beta)
Browser: Chrome 126.0.6478.128
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 32
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 503 gb
Storage usage (approx): 2.2 gb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3090 (0x00002204) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
</details>

**Comment by F3der1co** [comment]
This seems to be tied to collision cells in some way, as if I set collision cell size at start of layout it fixes the problem.

**Comment by AshleyScirra** [comment]
Checking collisions between instances on different layers with different transforms (i.e. different parallax, scroll, scale etc.) is a pretty complicated case in the engine. (I also think it's a rare case - it doesn't seem to me to make much sense to test collisions between objects which are essentially operating in entirely different co-ordinate systems based on their visual appearance, but some people ended up using it, so the engine supports it.)

This case should have disabled the collision cells optimization as the layer transforms are different, but it wasn't doing that correctly. Tracking the necessary state to handle this correctly is a bit tricky, but it's done for the next beta which should fix this.
