### ISSUE TITLE
Construct Docs Broken Links

### ISSUE THREAD

**Issue by andressantiago** [Scirra/Construct-bugs#8131]
## Problem description
Listing broken links found in docs:
- [Overview -> Project Structure](https://www.construct.net/en/make-games/manuals/construct-3/overview/project-structure) links  ["Project Primitives"](https://www.construct.net/make-games/manuals/construct-3/project-primitives). Goes to Home of docs.
- [Overview -> Project Structure](https://www.construct.net/en/make-games/manuals/construct-3/overview/project-structure) links ["Scripting"](https://www.construct.net/en/make-games/manuals/construct-3/scripting). Goes to Home of docs.

**Comment by AshleyScirra** [comment]
Thanks for spotting these. The "Project primitives" section doesn't have its own introductory page so I just took off the link. The scripting link has been updated.
