### ISSUE TITLE
Construct Docs Project Structure: some paragraphs are out of order

### ISSUE THREAD

**Issue by andressantiago** [Scirra/Construct-bugs#8132]
## Problem description

On the Overview -> Project Structure page there is a "Timeline & Eases" section where timeline is explained but the eases paragraph is after the "Sound and Music" section.

Also the syntax looks odd for the section headings as they are not consistent. "Timeline & Eases" uses an ampersand but "Sound and Music" is fully written out.

**Comment by AshleyScirra** [comment]
Thanks, updated the manual entry.
