### ISSUE TITLE
Images Inconsistently Fill Their Transparent Areas with Random Colors in Chrome on Microsoft Surface

### ISSUE THREAD

**Issue by ChromeWisp** [Scirra/Construct-bugs#8134]
## Problem description

On Microsoft Surface laptops, images containing transparent areas may have those areas filled in with blocks of solid or partly translucent colors. The graphics that become affected this way are not always the same in a given project after refreshing and testing again. In some projects you might not even see the issue affect any images at all. This appears to only affect Chrome, as I haven't been able to reproduce the issue on Firefox.

## Attach a .c3p

[History of Space Travel.zip](https://github.com/user-attachments/files/16368641/History.of.Space.Travel.zip)

## Steps to reproduce

1. Open the attached project or another containing images containing transparent sections.
2. Run the project, looking out for images whose transparent sections are replaced with blocks of solid or translucent color.
3. Refresh the project at least once, noting how different images in the project are now affected.

## Observed result

Images containing transparent sections fill in seemingly at random with translucent or solid colors.

## Expected result

Transparency in images remains transparent.

## More details
 Attached is a picture of the phenomenon in my own attached project around the year number speech bubbles, as well as screenshots of this happening in example projects found in the example browser. I couldn't reproduce the issue in every example project there, but in some it was easier to see affected sprites. Again, this only seems to happen on Microsoft Surface tablets/laptops (I've tried on a couple different Surfaces to make sure it's not just mine being broken) and only on Chrome so far as I can tell.

![r381 Transparency Bug 5](https://github.com/user-attachments/assets/9b3ba791-4f60-4c69-86f5-354ca2977321)
![r381 Transparency Bug](https://github.com/user-attachments/assets/8976500e-b781-48b8-830f-5b915cd37e58)
![r381 Transparency Bug 2](https://github.com/user-attachments/assets/05df7247-f1df-48d4-90c7-93c3757a6491)
![r381 Transparency Bug 3](https://github.com/user-attachments/assets/6047181c-d2ee-4065-9bbe-9454a290100b)
![r381 Transparency Bug 4](https://github.com/user-attachments/assets/7976dab7-04a7-4886-9314-d8f4538b9767)

**Affected browsers/platforms:**  Chrome.

**First affected release:**  r381 beta.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r382 (beta)
Browser: Chrome 126.0.6478.183
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 301 mb (0.4%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
</details>

**Comment by AshleyScirra** [comment]
Device-specific graphics glitches are highly likely to be graphics driver bugs rather than a problem with Construct. I'm afraid you'll need to contact Microsoft support about this - it's part of the device's system software that is faulty.
