### ISSUE TITLE
[r391] Timeline doesn't clean old instance from lookup map after swapping

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-bugs#8140]
## Problem description

If you swap an instance in the timeline, previous instance will be still linked with this timeline.

## Attach a .c3p

Use blank project

## Steps to reproduce

1. Drag an instance to the timeline
2. Swap it with another instance of this or another object

## Observed result

Now when you select previous instance this will also highlight a swapped instance in the timeline window. You can also crash an engine removing the track from timeline and dragging old instance to the timeline window.

## Expected result

After swapping old instance should not be linked with timeline anymore.

## More details

**Affected browsers/platforms:** All

**First affected release:** r391

**Comment by DiegoScirra** [comment]
Both issues will be fixed in the next beta.
