### ISSUE TITLE
Timeline "Set instance" doesn't work properly with multiple instances

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-bugs#8141]
## Problem description

In order to swap an instance of timeline during runtime "Set instance" is used as described here: https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/timeline-controller. Though an example with different object types was provided, but this bug refers to setting an instance to one object type twice.

Using "Set instance" multiple times **with the same object type or family** will lead to only first action being completed and others ignored. Is this intended behaviour?

## Attach a .c3p

https://drive.google.com/file/d/1DwBftPj5PDlObJgPlShtGOJpKfGl2RVS/view?usp=sharing

## Steps to reproduce

**With c3p example**
1. You can activate/deactivate groups to see different logic behaviour

**Blank project**
1. Create 2 sprites
2. Drop them to timeline window and give them trackId or leave it blank
3. Create 2 more sprites. **These should be the same object type**
4. Pick them and use "Set isntance" to swap first 2 sprites during runtime

## Observed result

Only first "Set instance" works

## Expected result

Both "Set instance" works

## More details

**Affected browsers/platforms:** All

**First affected release:** Never worked. Behaviour changed in r366 though

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r397 (stable)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 143 gb
Storage usage (approx): 327 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
Supported encode formats:

WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)

</details>

**Comment by DiegoScirra** [comment]
This wasn't working as you were expecting because the use case of picking specific instances of the same object type in successive calls to **Set Instance** was not handled properly. The next beta release will support the case.
