### ISSUE TITLE
Failed to load web font at Playable export

### ISSUE THREAD

**Issue by akarmehmet** [Scirra/Construct-bugs#8143]
It gives an error while loading the web font you are using in the Playable export. It shows the default browser font. It shows web font without any problems in Preview mode. There is no problem in exports taken from r399 version and before. The problem started to occur with r400 and later versions. The message "Failed to load resource: net::ERR_FILE_NOT_FOUND" is displayed in the console as an error.

## File
[Example.zip](https://github.com/user-attachments/files/16412992/Example.zip)

![Screenshot 2024-07-29 at 15 19 48](https://github.com/user-attachments/assets/0f20f4d9-5468-4c9a-873c-96835fcb25e9)

## Steps to reproduce

1. Open the above project with r401 version
2. Export project as Playable Ad (single file) option
3. Select the options below and click next : 
-  Deduplicate images -> Checked
- Lossless format -> WebP
- Lossy format -> WebP
- Optimize images -> Unchecked
- Minify mode -> Single
5. Download export zip file and extract single html file 
6. Open Html file in any browser

## Observed result
 
The web font "Kaboulege" fails to load, resulting in the text being displayed with a fallback font. An error message indicating the font loading issue is shown in the browser console. The visual appearance of the text does not match the design specifications due to the missing font.
## Expected result
The web font "Kaboulege" should load correctly, and the text should be displayed properly using the specified font. There should be no errors related to font loading, and the visual appearance of the text should match the design specifications.

## More details

**Affected browsers/platforms:** 

- MacBook Pro 13-inch M1 2020 macOS Sonoma 14.5

- Google Chrome Version 126.0.6478.185 (Official Build) (arm64)
- Safari Version 17.5 (19618.2.12.11.6)

**First affected release:** 

- r400

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r401 (beta)
Browser: Chrome 126.0.6478.185
Browser engine: Chromium
Context: browser
Operating system: macOS 14.5.0
Device type: desktop
Device pixel ratio: 2.5
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 340 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_render_shared_exponent
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
Fixed for next beta.
