### ISSUE TITLE
Hierarchies spanning multiple global layers can cause a crash

### ISSUE THREAD

**Issue by CodyRockwell** [Scirra/Construct-bugs#8144]
## Problem description

Hierarchies that contain instances on different global layers can cause the editor to crash. It happens when trying to open a layout that has the global layers of children, but not the parent.

## Attach a .c3p

https://drive.google.com/file/d/14xLOBD8vNjIPFyVwqq7yNPdlM0luBz2W/view?usp=sharing

## Steps to reproduce

1. Try to open the layout named "Crash"
2. Construct 3 crashes

## Observed result

Construct 3 crashes when trying to open the layout named "Crash".

## Expected result

Probably children should be released from the hierarchy in this layout. This is how it works for parents as, far I'm aware aware, with layouts that have the parent's global layer but not the children's resulting in the parent being part of no hierarchy for that layout.

## More details

**Affected browsers/platforms:** Chrome

**First affected release:** r401

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r401/components/editors/layoutView/layoutView.js, line 56, col 71
Message: Uncaught TypeError: Cannot read properties of null (reading 'Io')
Stack: TypeError: Cannot read properties of null (reading 'Io') at https://editor.construct.net/r401/components/editors/layoutView/layoutView.js:56:71 at Array.filter () at Ohb (https://editor.construct.net/r401/components/editors/layoutView/layoutView.js:55:460) at window.yLc.qU (https://editor.construct.net/r401/components/editors/layoutView/layoutView.js:209:114) at Array. (https://editor.construct.net/r401/components/editors/layoutView/layoutView.js:208:6) at window.Wm.dispatchEvent (https://editor.construct.net/r401/main.js:1284:42) at hnc (https://editor.construct.net/r401/components/editors/layoutView/layoutView.js:91:443)
Construct version: r401
URL: https://editor.construct.net/r401/
Date: Tue Jul 30 2024 12:13:54 GMT+0800 (Australian Western Standard Time)
Uptime: 1515.7 s

Platform information
Product: Construct 3 r401 (beta)
Browser: Chrome 127.0.6533.73
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002487) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta.

Currently what happens in this kind of setups is that the instances which are not shown are simply not drawn along with the arrows connecting them. Logically the hierarchy remains.
