### ISSUE TITLE
Regression: zElevation Text doesn't render if camera is below it

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8146]
## Problem description
regression from #8097
Text doesn't render if the 3d camera is below it (has lower z)

## Attach a .c3p
[zEleveationTextRender.zip](https://github.com/user-attachments/files/16424011/zEleveationTextRender.zip)

## Steps to reproduce

1. start preview
2. look up
3. fly up (mouse view basic fly controls using W and S)
4. look down

## Observed result
when looking up there are no texts visible
when looking down there is text visible (and it keeps being rendered if you go below it again)

## Expected result
text renders in both cases

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment]
Oh well, I just opened an issue as well, will close mine, thanks

https://github.com/Scirra/Construct-bugs/issues/8148

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
