### ISSUE TITLE
text in 3d performance regression

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8147]
## Problem description
regression from #8097
Text drawing cost now spikes to extremes when the camera is changing its z-elevation

## Attach a .c3p
[changingCameraZTextDraw.zip](https://github.com/user-attachments/files/16424116/changingCameraZTextDraw.zip)

## Steps to reproduce

1. look down
2. move camera with W and S
3. observe performance

## Observed result
GPU usage and drawcalls spike to extremes while the cameras Z is changing, looking around doesn't cause these spike

## Expected result
stable performance

## More details
If it's not fixable I'd rather have #8097 reverted tbh.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment]
Oh well, I just opened an issue as well, will close mine, thanks

https://github.com/Scirra/Construct-bugs/issues/8148

**Comment by F3der1co** [comment]
another thing I notice: in r401 the memory usage spikes much higher when looking at the texts and also stays higher when not looking at the texts compared to r400.

**Comment by AshleyScirra** [comment]
This is by design: the bug before involved text not re-rendering to match the display scale (just drawing like a sprite), and so losing quality. Text is meant to redraw to adapt the quality to the display scale, and after fixing the bug, it now does that. Constantly redrawing text is slower than not redrawing text, so it will be slower.

I suspect the main problem though is beta releases currently default to using the WebGPU renderer, which has a [known performance regression](https://issues.chromium.org/issues/40273077) with redrawing Text objects. If you switch back to the WebGL renderer it's a lot smoother.

**Comment by F3der1co** [comment]
It may be but the case is that in r400 we can use text in our games 3d world without any noticeable performance issue. 
In r401 we would have to remove all text in the 3d world because the performance is degraded to an extreme extend, not slightly but dropping frames and lag spikes on a powerful gaming PC (the game is supposed to release on mobile an web). This is the case with webGL2 (the real project doesn't use webGPU). So #8148 is basically the equivalent of shooting your foot to kill a fly to me, i.e. the bug is fixed but now I can't even use it.

Here's a little video where there are some 3d texts in the world, see how the game drops frames when looking at the text (144fps is vsync), performance measurements top left corner. Again this is a device much much more powerful than target hardware.
https://github.com/user-attachments/assets/fdecb55c-a931-4b4b-8763-278263295ee4

**Comment by skymen** [comment]
>the bug before involved text not re-rendering to match the display scale

To be honest, I would genuinely prefer if there was a way to opt into this. The lack of control over the text render quality has been a topic for a while and has come up a few times in the past, and I feel like in this case, it's no different.

To me there should be a way for us to decide on the text's render texture size, and I'm not sure there can ever be a one size fits all system. Web text rendering is done within vastly different constraints compared to games, and especially in 3D so I don't think the statement that "Text is meant to redraw to adapt the quality to the display scale" is completely true.

**Comment by skymen** [comment]
Did some tests, and yep, giving us control over the render quality completely fixes the issue
![image](https://github.com/user-attachments/assets/c1d5147e-1a95-46f0-b24b-e89426b18f15)

after playing around with this, I don't see any good reason this wouldn't be an option.

Real world showcase of the difference:
https://youtu.be/ajtDdAeEY4A

Also, I gave it a try, and this also completely fixes the issue for both 400 and 401
