### ISSUE TITLE
Text 3D issues

### ISSUE THREAD

**Issue by skymen** [Scirra/Construct-bugs#8148]
## Problem description

Hi, I reported a bug with 3D text rendering a few weeks ago that was pushed in last beta
https://github.com/Scirra/Construct-bugs/issues/8097

In my testing, it has made the text performance worse and it didn't fix the issue.

I think it's best to remove the fix made in the last patch, and I'll see if I can find weird ways to fix it on my own. If the thing I find involves messing with some rendering code I'll come back and make a better formulated bug report with a more concise repro. In the meantime I don't think the fix done last week should be kept.

## Attach a .c3p

N/A

## Steps to reproduce

N/A

## Observed result

N/A

## Expected result

N/A

## More details

N/A

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by skymen** [comment]
Better issues opened by Federico above, closing this one

**Comment by F3der1co** [comment]
xD the timing
