### ISSUE TITLE
Video doesn't play on mobile safari (iOS devices) R391+

### ISSUE THREAD

**Issue by paala** [Scirra/Construct-bugs#8153]
## Problem description
Video doesn't play on mobile safari (iOS devices) R391+

## Attach a .c3p
[VideoNotPlayingiOSSample.zip](https://github.com/user-attachments/files/16494865/VideoNotPlayingiOSSample.zip)

## Steps to reproduce

 

1.Load the project into R390 or under remote preview on iOS device. Notice video is playing.
2.Load the project into R391+ or under remote preview on iOS device. Notice video is NOT playing.
3. Can't make any other video format to play on mobile safari

## Observed result

Video is not playing when using R391+
## Expected result
Video should play

## More details

**Affected browsers/platforms:** 
safari mobile

**First affected release:** 
R391 first affected version
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Using r401 and the project file `VideoPlaybackR391.c3p`, remote previewing the project in Safari correctly plays the video just fine for me. I tested on both macOS 14.5 with Safari 17.5 and an iPhone with iOS 17.5.1 - in both cases the video plays after a click or tap (necessary to bypass autoplay restrictions).

**Comment by paala** [comment]
@AshleyScirra, Can you also try safari 17.6 and iOS 17.6(the latest version)? Maybe this bug happens only on the latest version

**Comment by AshleyScirra** [comment]
Tried with r402, macOS 14.6 with Safari 17.6, and iOS 17.6, and all works there too.

**Comment by paala** [comment]
@AshleyScirra I was trying to make an exported from my browser to see if it works on your ios.
But every export with version R402 make the site not able to load on netlify.
Exports with R401 work fine.
Tried on 2 computers just a basic game with a text put there

See sample:https://serene-muffin-88ef5e.netlify.app/

**Comment by paala** [comment]
@AshleyScirra 
Can you confirm this link works(shows video on iOS)
https://testsafari401.netlify.app/
On my device, on my client device it doesn't load

**Comment by AshleyScirra** [comment]
If there is a problem with just one host, it's probably that the host is misconfigured. From a quick look it doesn't look like they always sent a `Content-Type` header for the video request, which could break it. So it looks like it might be a problem with netlify and not Construct.

**Comment by paala** [comment]
@AshleyScirra  versions exported under R390 work on netlify; 
Versions exported with R391+ do not work.
In r391 the changes where related to the video plugin.
On my device the video doesn't work on remote preview also.
i doubt the problem is a netlify.
I can't find another host like netlify to try it
