### ISSUE TITLE
Crash editing the node name

### ISSUE THREAD

**Issue by DieppedalleDavid** [Scirra/Construct-bugs#8156]
## Problem description

In the flowchart editor, editing the node name crashes the program (Edit Caption).

## System details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'H') @ TypeError: Cannot read properties of null (reading 'H') at amb (https://editor.construct.net/r402/components/editors/flowchartView/flowchartView.js:6:379)
Stack: TypeError: Cannot read properties of null (reading 'H') at amb (https://editor.construct.net/r402/components/editors/flowchartView/flowchartView.js:6:379)
Construct version: r402
URL: https://editor.construct.net/r402/
Date: Tue Aug 06 2024 14:34:38 GMT+0200 (heure d’été d’Europe centrale)
Uptime: 186.5 s

Platform information
Product: Construct 3 r402 (beta)
Browser: Chrome 126.0.6478.182
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36
Language setting: fr-FR

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3070 (0x00002484) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

![image](https://github.com/user-attachments/assets/4903f9df-abad-4725-a43e-df55de82f5f6)

**Comment by DiegoScirra** [comment]
I see where the crash might be happening, but I can't reproduce this myself. Just bringing up the menu by right clicking seems to work as expected.

Are you doing anything in particular before or after the context menu is shown?

**Comment by DieppedalleDavid** [comment]
[tmp.zip](https://github.com/user-attachments/files/16514475/tmp.zip)

**Comment by DiegoScirra** [comment]
Check the next beta release to see if the problem was resolved. Unfortunately I am not able to reproduce the problem so I can't check it myself.

**Comment by DieppedalleDavid** [comment]
No change on my side.

**Comment by AshleyScirra** [comment]
r403 is now out - please check again there.

**Comment by DieppedalleDavid** [comment]
Solved, no more problems!
