### ISSUE TITLE
The app (APK or AAB) is stuck on the splash screen after the last update r402 

### ISSUE THREAD

**Issue by Vladyslavtur** [Scirra/Construct-bugs#8160]
## Problem description

New r402 version has errors in main.js. (TypeError: Cannot convert undefined or null to object) The result is a blank screen. Please fix ASAP, blocked and unable to revert to old version till this is fixed!

[ A minimal Construct project (.c3p) just example](https://drive.google.com/file/d/18Sd3VMHg_ZccklZ1GbW98YVFUKfT5EZ7/view?usp=sharing
) , but it is reproduced with en empty one. 

## Steps to reproduce

1. Create new project
2. Export it as Mobile/Android
3. Choose Debug Apk or Signed AppBundle (nevermind)
4. Open on Android device (most likely with 12+ Android version)

## Observed result

Black, White or custom splash screen is displayed &  and everything is stuck.

## Expected result

Next layout should be opened after splash screen.

## More details
For a test, I created a small progect-game. I exported with r401 and r402. The result is the same as on big project.
In r401 - everything works and starts.
In r402 - splash screen and stuck.

## System details

[Here I can add some logs from logcat.
](https://drive.google.com/file/d/1gbvdyrVi6iV4o-wUdzpsydD-CArvHWH6/view?usp=sharing)

**Comment by epic20** [comment]
Tbh I'm worried that I have to wait until August 19-23 to fix this issue because the blank screen is gonna be there for a while in my game on Google Play.

**Comment by Vladyslavtur** [comment]
I reverted the last change and the older version is now available to users. It works. 
But I'm still in the stage of closed testing. I don't know how it works for releases.

**Comment by AshleyScirra** [comment]
This should be fixed in r402.2.
