### ISSUE TITLE
Some elements of the dark theme are not displayed in Firefox

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#8161]
## Problem description

I've found that some start page menu elements (arrows, recommended examples stars, close buttons, checkboxes, search icon) are not displayed in Firefox, while they do in Chromium. This only affects dark theme - the light theme and the default theme are displayed consistently in both browsers.

## Observed result

**Firefox (above) / Chromium (below):**

![1_firefox](https://github.com/user-attachments/assets/05163202-cf96-4ef3-af9c-8f30f0e7659a)
![1_chromium](https://github.com/user-attachments/assets/5c643b95-8968-4764-8099-c0c3cd1e6c7e)

![2_firefox](https://github.com/user-attachments/assets/30c30ee3-a197-4f11-ada7-f76488853323)
![2_chromium](https://github.com/user-attachments/assets/8151514e-4fc8-4df6-b590-ae150cc29df2)

![3_firefox](https://github.com/user-attachments/assets/1c040adb-19ea-474b-858f-a12360d84f5a)
![3_chromium](https://github.com/user-attachments/assets/a852c8fc-5420-41d8-bc91-30eb066fd9b4)

![4_firefox](https://github.com/user-attachments/assets/2755aaa4-8e2c-4c15-9db8-ab1686371a7c)
![4_chromium](https://github.com/user-attachments/assets/2d434a4f-cbd0-445c-93b0-64f342a4220e)

## Expected result

Elements should display the same in Chromium and Firefox.

## More details

**Affected browsers/platforms:** Firefox

**Affected releases:** r397 (current stable) & r402.2 (current beta)

## System details

<details><summary>View details</summary>

Platform information

Product: Construct 3 r402.2 (beta)
Browser: Firefox 129.0
Browser engine: Gecko
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
Language setting: en-US
Local storage

Storage quota (approx): 10 gb
Storage usage (approx): 48 mb (0.5%)
Persistant storage: No
Browser support notes

This list contains missing features that are not required, but could improve performance or user experience if supported.

    Rendering multiple on-screen Layout Views is slow in Firefox due to [bug 1163426](https://bugzilla.mozilla.org/show_bug.cgi?id=1163426)
    Determining input device capabilities is not supported.

WebGL information

Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics Direct3D11 vs_5_0 ps_5_0), or similar
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

    EXT_color_buffer_float
    EXT_float_blend
    EXT_texture_compression_bptc
    EXT_texture_compression_rgtc
    EXT_texture_filter_anisotropic
    OES_draw_buffers_indexed
    OES_texture_float_linear
    OVR_multiview2
    WEBGL_compressed_texture_s3tc
    WEBGL_compressed_texture_s3tc_srgb
    WEBGL_debug_renderer_info
    WEBGL_debug_shaders
    WEBGL_lose_context
    WEBGL_provoking_vertex

Audio information

System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

    WebM Opus (audio/webm;codecs=opus)
    WebM Vorbis (audio/webm;codecs=vorbis)
    MPEG-4 Opus (audio/mp4;codecs=opus)
    MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
    MP3 (audio/mpeg)
    FLAC (audio/flac)
    PCM WAV (audio/wav;codecs=1)

Supported encode formats:

    WebM Opus (audio/webm;codecs=opus)

Video information

Supported decode formats:

    WebM AV1 (video/webm;codecs=av01.0.00M.08)
    WebM VP9 (video/webm;codecs=vp9)
    WebM VP8 (video/webm;codecs=vp8)
    MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
    MPEG-4 VP9 (video/mp4;codecs=vp9)
    MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

Supported encode formats:

    WebM VP8 (video/webm;codecs=vp8)

</details>

**Comment by AshleyScirra** [comment]
These look like bugs in Firefox itself, as it's the same content displayed correctly in other browsers.

Reducing these to a minimal repro could prove to be hard work, and meanwhile the effect is only cosmetic. I'd suggest reporting this to Mozilla directly as a web compatibility issue.
