### ISSUE TITLE
不斷跳出的系統錯誤

### ISSUE THREAD

**Issue by 0000-my** [Scirra/Construct-bugs#8165]
## Problem description

As long as the project is exported twice in a row, an error will appear. After restarting, as long as the project is exported, an error will appear.

## Steps to reproduce

1.Export the project and wait for completion
2.Export the project again and wait for completion
3.Close the project, reopen it and export the project

## Observed result

An error message occurred

## Expected result

nothing will happen
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE
Error report information
Type: unhandled exception
File: https://editor.construct.net/r397/main.js, line 1952, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at Dr.g.Oi.eRa (https://editor.construct.net/r397/main.js:1952:242) at ej.g.NEc.Dd (https://editor.construct.net/r397/main.js:1954:415) at https://editor.construct.net/r397/main.js:1954:139
Construct version: r397
URL: https://editor.construct.net/
Date: Sun Aug 11 2024 19:10:18 GMT+0800 (台北標準時間)
Uptime: 52 s

Platform information
Product: Construct 3 r397 (stable)
Browser: Edge 127.0.2651.86
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36 Edg/127.0.0.0
Language setting: zh-TW

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 5500 (0x00001616) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by XHXIAIEIN** [comment]
You may need to add more detailed information:

1. What export method did you choose to see the error? H5? Android? NW.js? Webview2? Have you tested other export methods and the same error occurred?

2. What error did you see? You need to provide detailed information about the error so they can help you track the issue. Or provide a screenshot and press F12 to see the console log error.

<details><summary>中文说明</summary>

你可能需要补充更详细的信息：
1. 你选择什么样的导出方式看到了错误。H5? Android? NW.js? Webview2?  是否有测试其他的导出方式也出现了同样的错误。

2. 你看到了什么错误，你需要提供错误详细的信息，他们才能帮你跟踪这个问题。或者提供截图，以及按下 F12 看看控制台的日志错误。

</details>

**Comment by 0000-my** [comment]
I'm sure Android does, but others seem to be too

**Comment by DiegoScirra** [comment]
Are there any extensions installed?

**Comment by DiegoScirra** [comment]
Browser extensions can have unexpected behaviours when working alongside C3.

**Comment by AshleyScirra** [comment]
There is not enough information provided to be able to investigate this, so closing.
