### ISSUE TITLE
Audio Play(by Name) does not work with string variable for sounds in folder

### ISSUE THREAD

**Issue by UpToSix** [Scirra/Construct-bugs#8166]
## Steps to reproduce

1.Playing audio directly from folder through the file name String variable. This does not work. If the audio are brought under "sounds" folder directly, then works. Or else, we need to pass the folder path now. This is not expected. we have games with 1000+ sound files organized under folder. game was working file and running filke in store where we are not passing the path.
Thsi shoudl be corrected ASAP please.

## Observed result

Please support audio Play(by name) with string variable where sound is organized in folder.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details
[Math_Local_Test_xx2.c3p.zip](https://github.com/user-attachments/files/16574892/Math_Local_Test_xx2.c3p.zip)

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Jase0000** [comment]
Not a bug.

On the 3rd button, the local var "localStr2", change this to: 

Number Formation Instruction/Number_02

Then it works.

If you don't want folder paths, you can change your project properties: Compatibility Settings > Export File Structure, change this from "Folders" to "Flat" and all the buttons will work.
