### ISSUE TITLE
SDK V2 - Advanced Minification incorrect class Mapping for SingleGlobal plugins

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8168]
## Problem description

When exporting a project using advanced minification, plugin class class name is incorrectly minified, thus the references are lost and the project fails to run. I tested it with the SingleGlobal plugin example provided by the SDK v2.

## Attach a .c3p
Plugin: [mycompany_singleglobal.zip](https://github.com/user-attachments/files/16594598/mycompany_singleglobal.zip)
Test Project: [testAdvMin.zip](https://github.com/user-attachments/files/16594600/testAdvMin.zip)

## Steps to reproduce

1. Install the sample plugin taken from the SDK v2
2. Open the attached project. You'll notice that the event sheet only has one condition, calling the "IsLargeNumer" method of the plugin
3. Export the project using advanced minification.
4. Install the exported project in your local webserver
5. Open the URL to your localserver/project

## Observed result

Project will fail to run because minification incorrectly mapped the plugin ID and the plugin classname.
![image](https://github.com/user-attachments/assets/b27bd678-dc94-462b-9ffc-e35e11f954d9)
![image](https://github.com/user-attachments/assets/6128ac75-a9ac-4969-bb50-45e6cbe1daf6)
In above screenshots the class **globalThis.A.ga.Tt** corresponds to the plugin class **C3.Plugins.MyCompany_SingleGlobal**, which is incorrectly minified. The **Tt** reference doesn't exist in the minified code.

## Expected result

Project must run and should had been correctly minified.

## More details

r402-2 Beta

## System details

<details><summary>View details</summary>

workermain.js:5 [C3 runtime] Failed to load all engine scripts in worker:  TypeError: Cannot set properties of undefined (setting 'U')
    at c3main.js:1802:187

</details>

**Comment by AshleyScirra** [comment]
This is a bug in Closure Compiler. If you have code of the form:

```js
const C3 = globalThis.C3;

C3.Plugins.MyCompany_SingleGlobal.Instance = class { /* ... */ }
```

then Closure Compiler just deletes the entire class in advanced mode. I reported this to Google, but they have shown no interest in fixing it. This is part of the reason we are moving to UglifyJS, which should not be affected by this issue.

You can work around the issue with Closure Compiler by consistently using `globalThis`, i.e.:

```js
const C3 = globalThis.C3;

// note: use globalThis again here
globalThis.C3.Plugins.MyCompany_SingleGlobal.Instance = class { /* ... */ }
```

You only need to do that where it uses a class expression - i.e. the plugin, type and instance classes.
