### ISSUE TITLE
Preview window is not displaying game preview (Windows 10)

### ISSUE THREAD

**Issue by FreshDopeGames** [Scirra/Construct-bugs#8172]
## Problem description

When trying to preview a project or game on Windows 10, the preview window does not load for some games. I've tried this with my own game (linked below), but also with games on the Start Page. Some on the Start Page work every time, but some like Segmented Boss Fight, First Person Shooter do not load at all when previewing them using http://preview.construct.net.

## Attach a .c3p

https://drive.google.com/file/d/1IDbmGOSeLxjfu97-mdQDYEk1QClJJBbF/view?usp=drive_link

## Steps to reproduce

1. Load the game into the editor (editor.construct.net)
2. Attempt to preview the layout or the project
3. Observe the https://preview.construct.net window

## Observed result

Blank screen (white or black)

## Expected result

Game preview works as expected (play the layout or project)

## More details
This seems to not be an issue on MacOS Sonoma using the same browsers.

**Affected browsers/platforms:**  Chrome/Firefox, Windows 10

**First affected release:**  Seems to have happened with r397 or one earlier stable build

## System details

<details><summary>View details</summary>

PASTE HERE
![construct_preview](https://github.com/user-attachments/assets/8e3a50ca-9ad7-4156-8151-5c418b20daae)

</details>

**Comment by AshleyScirra** [comment]
I do not appear to have permission to access the link. If I preview the 'First person shooter' sample it works fine for me in r403.

The console messages you included a picture of include mysterious errors for requests that Construct isn't making. I would guess you have a browser extension that is interfering with Construct. Try disabling any browser extensions you have installed and try again.

**Comment by FreshDopeGames** [comment]
Apologies for the access issue, the file has been made available now.

**Comment by AshleyScirra** [comment]
The file opens and runs just fine for me. I would guess as I thought that you have a browser extension that is interfering with Construct. Try disabling any browser extensions you have installed and try again.
