### ISSUE TITLE
[Manuals] Advanced Random ProbabilityTableJSON use wrong symbol example.

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8174]
## Problem description

link: [Create probability table from JSON](https://www.construct.net/en/make-games/manuals/construct-3/plugin-reference/advanced-random#:~:text=values%20are%20taken.-,Create%20probability%20table%20from%20JSON,-Create%20a%20new)

![image](https://github.com/user-attachments/assets/673239bb-dfd9-4a8a-8a60-d1e10cc87d64)

## Observed result

This may be because the document incorrectly parses `[`, resulting in the temporary use of the `(` symbol instead

> Create probability table from JSON
> Create a new probability table from a JSON string. The input should be an array of (weight: number, value: number|string) tuples.

## Expected result

```
[weight: number, value: number|string]
```

And provide a concrete example, which helps the user understand. Because he can just copy and paste to see it in action
```
[[1, "Apple"], [2, "Banana"], [3, Carrot]]
[["Apple", 1], ["Banana", 2], [Carrot, 3]]  // I noticed that this works, so it helps with the neatness.
```

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Updated the manual entry and added an example.
