### ISSUE TITLE
Memory leak or garbage collection problem in Pathfinding

### ISSUE THREAD

**Issue by lord-nobuo** [Scirra/Construct-bugs#8178]
## Problem description

There seems to be a memory leak or garbage collection problem with **Pathfinding**.  There is an observable residual increase in idle memory usage as pathfinding operations are completed over time.  I discovered this in my game project first, and for this bug report, built an entirely new project intended to make it easy to reproduce & investigate this issue.

## Attach a .c3p

https://drive.google.com/file/d/1kjWh0U_y2I2spOgNzaJmZ4TqjTdBG8gQ/view?usp=sharing

## Steps to reproduce

1.  Run the project.
2.  In Chrome, hit F12, open DevTools -> Memory tab.  You'll be observing the memory usage in the bottom left, and here idle at the start it will be very low (sub-100mb in my testing).
3.  Click the "1x iteration" button.  This will run through the simulation function once and to show you what's happening here:  "WorkerSprite" is created from "SpawnPoint" and will proceed to pathfind to each "DestinationSprite".  Once each iteration is complete, the involved WorkerSprite is destroyed.  _This simulates the full life cycle of continually spawning NPCs in my game, and this process happens repeatedly for long periods._
4.  Click the button (1x or 2x) to simulate more iterations.  The memory problem will quickly become evident in DevTools.

## Observed result

After around 20+ iterations (24,000+ total paths found in my sample project), the baseline memory usage of my game is noticeably increased, even after allowing the game to idle for sufficient time for all WorkerSprites to be destroyed in between iterations (returning the game to its basic starting state).  Unexpected memory usage exceeds 1GB on my PC after around 30 iterations.  If iterations continue, the browser will eventually kill the game with an "Out of Memory" error.

## Expected result

After pathfinding is complete and the pathfinding sprite is destroyed, I would expect any system memory involved in the pathfinding operation to be unallocated.

## More details
Don't spam the "add iteration" buttons too quickly or you'll see an Out of Memory error for a different reason (an understandable reason) which is unrelated to this bug report.  On my end, it works best if I don't have more than 4-5 queued iterations at a time.  Allow each iteration to process before queuing up more than that.

**Affected browsers/platforms:**   Chrome

**First affected release:** Discovered in the current Stable version & reproduced/reported with the latest beta release, per your bug report guidelines.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r402.2 (beta)
Browser: Chrome 127.0.6533.120
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 22
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 556 gb
Storage usage (approx): 81 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 4080 Laptop GPU (0x000027E0) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
I suspect this is some kind of GC bug in Chrome/V8 - possibly a regression as I suspect this would have been reported by now if it had always been there. I can't see any reason it should leak memory as all our existing code is careful to clear up state after pathfinding calculations and ensure nothing is left behind. However I did find a straightforward workaround which seems to fix the memory leak, so I've added that for the next beta.
