### ISSUE TITLE
SDK v2 - Exporting projects with inline-script dependency doesn't include the dependencies indicated

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8179]
## Problem description

When creating singleGlobal plugins, if you add a dependency js file in the addon.json, and then include it with the AddFileDependency method, construct never loads it and when exporting it the file is never consider as part of the project, therefore the whole project fails to load.

addon.json includes a dependency called "test.js"
![image](https://github.com/user-attachments/assets/d4a6ae13-48de-475a-bb51-371875e9c7f6)

The type of dependency is inline-script
![image](https://github.com/user-attachments/assets/96783649-dd4e-4a5c-9d79-4d2d42d927f6)

Source code of test.js
![image](https://github.com/user-attachments/assets/a3b377c7-5901-47fd-8d8b-aebd87b6285a)

## Attach a .c3p
[singleglobal-test-export.zip](https://github.com/user-attachments/files/16643955/singleglobal-test-export.zip)
[mycompany_singleglobal_w-dependency.zip](https://github.com/user-attachments/files/16643966/mycompany_singleglobal_w-dependency.zip)

## Steps to reproduce

1. Include the addon attached in construct
2. Open the c3p file attached
3. Export the project with no minification at all

## Observed result
Scenario 1. When running the project in preview, if you debug, you'll notice the test.js script was never loaded in the list of scripts
Scenario 2. When exporting the project with no minification at all, none of the exported scripts contains the source code of the test.js script, indicating it was never loaded nor considered as part of the project.

## Expected result

inline-scripts must be correctly exported

## More details

Beta r402-2

## System details
No exceptions thrown, but the script is not being exported.

**Comment by AshleyScirra** [comment]
"inline-script" dependencies aren't supported in the Addon SDK v2. They were removed in [r398](https://www.construct.net/en/make-games/releases/beta/r398):

> SDK v2: remove support for "inline-script" dependencies (use another runtime script instead)

If you use one anyway, Construct will log an error to the console and ignore the dependency.

The reason for this is the "inline-script" dependency type is pointless - just add another runtime script, which does the same thing. IIRC it's a legacy of the C2 runtime which only used one runtime script and didn't support adding additional runtime scripts.

**Comment by sotano42** [comment]
> The reason for this is the "inline-script" dependency type is pointless -

I disagree with this. In my case, I have really big scripts and frameworks of my own that I need to break down into several scripts for readability because I can't use modules. Inline scripts make total sense to me. Embeding external libraries that do not involve the DOM should be supported as inline scripts.

**Comment by sotano42** [comment]
I think I figured it out, it will be great if you could release the documentation of the new features as you release the beta verions. Method AddC3RuntimeScript() is nowhere in the doc.

**Comment by AshleyScirra** [comment]
Perhaps I should have said "redundant" instead of "pointless" - you can still use inline script dependencies, but using additional runtime scripts instead of the "inline-script" dependency.
