### ISSUE TITLE
r334 Text and SpriteFont 'Origin' property issue

### ISSUE THREAD

**Issue by elfwy-uwu** [Scirra/Construct-bugs#8182]
## Problem description

Text and SpriteFont replicas with different 'origin' property from source will reset 'origin' to default when any property of replica is changed. This will reset actual origin point and will not change property value in the properties bar. Sometimes after changing replica property you will need to undo (ctrl+z), i did not see the pattern though.

This bug is easy to catch in big hierarchy structures that include Text/SpriteFont

## Attach a .c3p

https://drive.google.com/file/d/1E70hjK8lr-jLIIhIJ4_eG-HGKsOmme2n/view?usp=sharing

## Steps to reproduce

c3p:
1. Choose SpriteFont or Text replica
2. You can see that origin point is already modified compared to template source, just change any property (for example check Bold)
3. Sometimes you need to press Ctrl+Z

blank:
1. Create SpriteFont or Text object, make a template
2. Copy this instance to make a replica
3. Change Origin point of replica
4. Now change any other property of the replica
5. Sometimes you need to press Ctrl+Z

## Observed result

You can see that SpriteFont/text replica origin changed to default, though it's still stated as correct in the properties bar

## Expected result

Origin is not changed unintendedly

## More details

**Affected browsers/platforms:** all

**First affected release:** r334

**Comment by elfwy-uwu** [comment]
upd: This is also the case for TiledBackground. Looks like all objects with 'origin' property are affected.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
