### ISSUE TITLE
Mignify error with UglifyJS

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#8184]
As of r403, when i use mignify with the new mignify method (UglifyJS - Advanced) i get this error:

Error: Build failed with 2 errors:
node_modules/esbuild-wasm/lib/main.js:1216:27: ERROR: [plugin: file-map-resolver] path 'fs' not resolvable
node_modules/esbuild-wasm/lib/main.js:1216:27: ERROR: [plugin: file-map-resolver] path 'path' not resolvable

**Comment by F3der1co** [comment]
I get the same error

**Comment by AshleyScirra** [comment]
No project was provided so I opened Spell Caster, exported with UglifyJS advanced minification, and it worked fine. Please always follow the bug report guidelines, every time, no matter how obvious you think the problem is, since otherwise it's impossible to help.
