### ISSUE TITLE
AJAX and NW.js plugins throw errors when using UglifyJS

### ISSUE THREAD

**Issue by GameSoul7Eugene** [Scirra/Construct-bugs#8185]
## Problem description

If you try to export a project that has an AJAX or NW.js plugin using the new UglifyJS minifier, it will fail and show an error. This affects the UglifyJS minifier as a whole, regardless of which minify mode you choose, and only these two specific plugins. Other Construct plugins and behaviors are not affected.

## Steps to reproduce

1. Create a new project
2. Add an AJAX or NW.js plugin to it
3. Export it with UglifyJS (with any minify mode option)

## Observed result

Export shows the following errors, depending on the plugin used:

![ajax-error](https://github.com/user-attachments/assets/88fcea6d-06e0-4e3d-acf2-82e609d8a8fa)
_AJAX_

![nwjs-error](https://github.com/user-attachments/assets/0baceb57-0135-4106-a015-a14e6fb8c0d9)
_NW.js_

## Expected result

Export goes off without any errors!

## More details

**Affected browsers/platforms:** any

**First affected release:** `r403` as it was the first release to add the UglifyJS minifier.

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r403 (beta)
Browser: (unknown) (unknown)
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 84 gb
Storage usage (approx): 32 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) HD Graphics 4000 (0x00000166) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_norm16
KHR_parallel_shader_compile
OES_draw_buffers_indexed
OES_texture_float_linear
OVR_multiview2
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_provoking_vertex
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)

</details>

**Comment by DinoSystem** [comment]
I got this issue too, and i confirm removing AJAX fixed it!

**Comment by AshleyScirra** [comment]
I could reproduce this, and the fix is done on the server-side, so it should work now in the current beta release as well.
