### ISSUE TITLE
Opening a .c3p project in Google Chrome or MS Edge (Windows) browsers fails: 

### ISSUE THREAD

**Issue by jenzj** [Scirra/Construct-bugs#8187]
## Problem description

Opening a Construct3 project in Chrome or Edge browsers (Window 11 OS) fails with message **Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.**

## Attach a .c3p

[https://www.dropbox.com/scl/fi/civ63d6k2amdsr5ye99pt/Test.c3p?rlkey=1ohznpg3sx9lmpzy67jevct19&dl=0](https://www.construct.net/out?u=https%3a%2f%2fwww.dropbox.com%2fscl%2ffi%2fciv63d6k2amdsr5ye99pt%2fTest.c3p%3frlkey%3d1ohznpg3sx9lmpzy67jevct19%26dl%3d0)

## Steps to reproduce

1.  Open Construct3 Editor in Google Chrome on Windows 11 platform.
2.  Create a simple project and save as a single-file.
3.  Close project.
4.   Open project using the Construct3 Editor in Chrome.  

## Observed result

The message appears:  **Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.**

## Expected result

The editor should have opened the Construct3 project which has a simple layout and no event sheets.

## More details

- Using the Brave browser, the c3p project opens without a problem (Windows).

- Opening the project in MacOS using Chrome also works.

**Affected browsers/platforms:**  Chrome/Firefox/Edge on Windows 11

**First affected release:** 3.97 

## System details

F12 console showed the following:

![image](https://github.com/user-attachments/assets/012de7d3-def0-4b90-a47b-5209a730c9a7)

<details><summary>View details</summary>

Opening a Construct3 project in Chrome or Edge browsers (Window 11 OS) fails with message **Failed to open project. Check it is a valid Construct 3 single-file (.c3p) project.**

</details>

**Comment by AshleyScirra** [comment]
If I download the provided .c3p file and drag-and-drop it in to the window in Chrome on Windows 11, it opens fine. So it seems the project file is OK.

To further investigate we'd need steps to follow that reliably reproduce the problem. I suspect this may be something like a browser extension interfering with Construct - try disabling any browser extensions you have installed. As this issue can't be actioned further, closing.

**Comment by XHXIAIEIN** [comment]
I also occasionally receive such an error. When I open it for the first time, it will prompt that it is invalid, but when I open it for the second time, it opens normally. But I encountered this situation in PWA of Windows 11.
