### ISSUE TITLE
internationalization throws an error when minifying using advanced.

### ISSUE THREAD

**Issue by CGOGamefi** [Scirra/Construct-bugs#8188]
## Problem description

See attached image for console log. When minifying an HTML5 project using advanced it will throw this error after deployed. Minifying with simple it does not. Checking in preview in Construct 3 also does not throw this error.

## Attach a .c3p

I am under NDA and cannot share the file.

## Steps to reproduce

1. using AJAX request a localization json file.
2. use internationalization set locale to your localization file.
3. launch game and see the console.
4. the json file fails to be found.

## Observed result

see screenshot of console

## Expected result

the json files all load.

## More details
This happens after the game has been deployed (using vercel.com)
![Screenshot 2024-08-21 185407](https://github.com/user-attachments/assets/a4434efc-241e-4714-95d7-957fe4a16812)
![Screenshot 2024-08-21 194658](https://github.com/user-attachments/assets/e91ca254-e67f-4551-95eb-f8c258e51a4b)

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Please provide a minimal project as per the bug report guidelines.

See the bug report FAQ regarding sharing your full project - we don't want the full project anyway.
