### ISSUE TITLE
Crash as soon as android export starts.

### ISSUE THREAD

**Issue by Ocsid** [Scirra/Construct-bugs#8190]
## Problem description

red screen error on start of android export.
The export continues without problems and the produced apk works fine, but construct has to be reloaded.
I have tried to export both in latest stable and latest beta, with the same error.

## Attach a .c3p
[debug.zip](https://github.com/user-attachments/files/16738105/debug.zip)

I have not used any external plugins, behaviours or browser extensions.
A clean project does not reproduce the error.

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r403/main.js, line 1962, col 242
Message: Uncaught TypeError: d.getModifierState is not a function
Stack: TypeError: d.getModifierState is not a function at vr.g.Vi.XSa (https://editor.construct.net/r403/main.js:1962:242) at $i.g.nIc.yd (https://editor.construct.net/r403/main.js:1964:415) at https://editor.construct.net/r403/main.js:1964:139
Construct version: r403
URL: https://editor.construct.net/r403/
Date: Sat Aug 24 2024 23:20:26 GMT+0200 (centraleuropeisk sommartid)
Uptime: 33.8 s

Platform information
Product: Construct 3 r403 (beta)
Browser: Chrome 127.0.6533.120
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 3060 (0x00002504) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by Ocsid** [comment]
[debug.zip](https://github.com/user-attachments/files/16738089/debug.zip)
Managed to strip quite alot while keeping the bug, try to export as android debug.apk

**Comment by AshleyScirra** [comment]
It works fine for me in r404. It looks like another case of #7529 - a mysterious error we can't reproduce. Our best guess is it is being caused by a browser extension that is interfering with Construct. Try disabling any browser extensions you have installed. It would be interesting to know which one causes it if you can figure that out.
