### ISSUE TITLE
Black Screen on Playable Export When Physics Behavior is Added to Any Object

### ISSUE THREAD

**Issue by akarmehmet** [Scirra/Construct-bugs#8191]
When adding the Physics behavior to any object in my Construct 3 project, the exported playable version consistently opens to a black screen. This issue occurs regardless of the object's properties or the complexity of the project. The problem only manifests when the Physics behavior is applied; removing it restores normal functionality.

## Attach a .c3p
[Test.c3p.zip](https://github.com/user-attachments/files/16750624/Test.c3p.zip)

## Steps to reproduce
1. Create a new project in Construct 3.
2. Add any object to the layout (e.g., a sprite).
3. Add the Physics behavior to the object.
4. Export the project as a playable (HTML5 or any other format).
5. Open the exported project in a browser 

## Observed result

The project loads to a black screen, with no visible content.

## Expected result

 The exported project should run normally, with the object responding to the Physics behavior.

## More details
When attempting to run the exported project, the following errors appear in the console:
![Screenshot 2024-08-26 at 18 35 10](https://github.com/user-attachments/assets/ef543fc2-296a-4240-94e6-60c0826ed64d)

**Affected browsers/platforms:** 
Chrome - Version 127.0.6533.120 (Official Build) (arm64)
Safari - Version 17.6 (19618.3.11.11.5)

**First affected release:** 
worked in r399 but broke in r402

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r402 (beta)
Browser: Chrome 127.0.6533.120
Browser engine: Chromium
Context: browser
Operating system: macOS 14.6.1
Device type: desktop
Device pixel ratio: 1.25
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 276 gb
Storage usage (approx): 565 mb (0.2%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Apple)
Renderer: ANGLE (Apple, ANGLE Metal Renderer: Apple M1, Unspecified Version)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_render_shared_exponent
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by dhiavoodoo** [comment]
Also having the same issue here. It started with r400 :/

**Comment by AshleyScirra** [comment]
Should be fixed in the next beta.
