### ISSUE TITLE
Cordova WebView not resized on Android

### ISSUE THREAD

**Issue by creakosta2** [Scirra/Construct-bugs#8192]
## Problem description

I use a third-party monetization cordova plugin that creates an banner AdView at the top or bottom of the screen, while the game content is reduced to fit the free space on the screen. This was the case when I created my projects in Construct 2, but after switching to Construct 3, this behavior stopped working on cordova Android, but it works on cordova iOS and other platforms in web. If the banner is placed at the bottom of the screen, it seems to simply overlap the content. If the banner is placed at the top, the content is shifted down and not reduced, but cut off from the bottom. At the same time, if I delete the banner, the viewport size change event is triggered.

## Attach a .c3p

[test_resize.zip](https://github.com/user-attachments/files/16784843/test_resize.zip)
[cordova proj.zip](https://github.com/user-attachments/files/16784824/cordova.proj.zip)

## Steps to reproduce

1. Build and run cordova project on android device
2. Touch BANNER button to show banner

## Observed result
Banner not shrink the viewport and red squares on bottom are overlapped

![Observed](https://github.com/user-attachments/assets/d332ccba-2eec-405f-aacf-380900d75165)

## Expected result
Banner shrink the viewport and red squares on bottom full visible

![Expected](https://github.com/user-attachments/assets/d628e91d-805a-4605-b556-d69673e8da34)

## More details

**Affected browsers/platforms:** 

Cordova android 13.0.0, Pixel 4a

**First affected release:** 

The bug is observed in all releases of Construct 3

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r404 (beta)
Browser: Chrome 128.0.6613.84
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 572 gb
Storage usage (approx): 464 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2080 with Max-Q Design (0x00001ED0) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by creakosta2** [comment]
Is it possible that something in CSS does not allow the viewport to be resized?

**Comment by creakosta2** [comment]
maybe it has something to do with this:

https://github.com/Scirra/Construct-bugs/issues/5581#issue-1186155058

**Comment by DiegoScirra** [comment]
The next beta will be adding a new "Overlap" parameter to banner adverts.

It will be "true" by default so the banners behave as they do now. Setting it to "false" will make the banner show up on top or bellow the main WebView making it resize, so no content is cut off.

**Comment by creakosta2** [comment]
> The next beta will be adding a new "Overlap" parameter to banner adverts.
> 
> It will be "true" by default so the banners behave as they do now. Setting it to "false" will make the banner show up on top or bellow the main WebView making it resize, so no content is cut off.

Hi! Will this fix work with third party advertising plugins?

**Comment by DiegoScirra** [comment]
This just works with banners shown using the Mobile Adverts plugin. Other plugins need to handle positioning themselves.

**Comment by creakosta2** [comment]
> This just works with banners shown using the Mobile Adverts plugin. Other plugins need to handle positioning themselves.

the plugin i use has banner positioning but webview doesnt change size in C3 games on Android, here this plugin:

https://github.com/creakosta2/cordova-plugin-yandex-ads
