### ISSUE TITLE
scrolling instance bar during search resets selection

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8193]
## Problem description
scrolling the instance bar during search resets selection

## Attach a .c3p
[instanceBarScrollBug.zip](https://github.com/user-attachments/files/16803875/instanceBarScrollBug.zip)

## Steps to reproduce

1. make sure the instance bar is visible
2. search "s"
3. select a sprite in the bar (not the top most)
4. scroll the instance bar

https://github.com/user-attachments/assets/dd6a2fdd-ff33-44a7-8fde-3d2f1567c0f8
## Observed result
selection switches to the top most searched instance

## Expected result
selection doesn't change

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
