### ISSUE TITLE
instance bar sometimes not clickable

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8194]
## Problem description
the instance bar is sometimes not interactable.

## Attach a .c3p
[instanceBarNotInteractable.zip](https://github.com/user-attachments/files/16803922/instanceBarNotInteractable.zip)

## Steps to reproduce

I am not entirely sure what causes it so might require some tinkering
1. make sure the instance bar is enabled
2. try selecting an instance on it or search
3. try dock, un-dock, change size or move to the right/other place
4. repeat from 2.

https://github.com/user-attachments/assets/128ae855-3a61-4e0c-b28a-a6ae96b5c464

## Observed result
instance bar isn't interactable (hover still shows up)

## Expected result
instance bar is interactable

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
