### ISSUE TITLE
instance bar, expand all doesn't work sometimes

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8195]
## Problem description
instance bar, expand all doesn't work sometimes

## Attach a .c3p
[collapseHierachy.zip](https://github.com/user-attachments/files/16804091/collapseHierachy.zip)

## Steps to reproduce

1. collaps a hierarchy by clicking the arrow
2. right-click and select expand all

https://github.com/user-attachments/assets/ea242236-51d2-46c4-8ed2-76567c183964

## Observed result
the arrow changes state but the collapsed instances aren't updated (maybe tree update call missing)
I am not 100% sure, but I think the mix of clicking to collapse and context menu causes the issue, using one way exclusively seems to work.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
