### ISSUE TITLE
instance bar, context menu remove from parent doesn't update tree

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8196]
## Problem description
instance bar, context menu remove from parent doesn't update tree

## Attach a .c3p
[removeFromParent.zip](https://github.com/user-attachments/files/16804420/removeFromParent.zip)

## Steps to reproduce

1. right click sprite 23 in the instance bar
2. select hierarchy>remove from parent

https://github.com/user-attachments/assets/09a59aee-3538-4519-afb7-b70e813d940f

## Observed result
instance bar view doesn't update

## Expected result
tree updates

## More details
removing from parent inside the layout view does work

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta, was introduced with provious changes to improve the performance on layouts with a large amount of instances.
