### ISSUE TITLE
Manual:  Using Expression Calculation in the Properties Bar

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8197]
## Problem description

In the documentation of the Properties Bar, the description of the [Typing calculations](https://www.construct.net/en/make-games/manuals/construct-3/interface/bars/properties-bar#internalH1Link2) is incorrect.

> In number values, you can type calculations like 1920 / 2 and press enter to set the value to the result of the calculation (960). The syntax used is the same as [expressions](https://www.construct.net/make-games/manuals/construct-3/project-primitives/events/expressions) used in events. You can also use some basic [system expressions](https://www.construct.net/make-games/manuals/construct-3/system-reference/system-expressions) like sqrt(64).

## Observed result

I tried and couldn't use like `sqrt(64)`

![image](https://github.com/user-attachments/assets/7c422247-8623-413e-9b4a-34e11a4a9ea9)

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Actually the documentation is meant to be correct, but the ability to use system expressions was accidentally broken a while back. It should be fixed for the next beta.
