### ISSUE TITLE
New version r397.2 doesn't open my project

### ISSUE THREAD

**Issue by KoolGamesRicardo** [Scirra/Construct-bugs#8199]
## Problem description

My folder project does not open on version r397.2 but works fine on r397.

## Attach a .c3p

Earliest commit, default C3 files
https://drive.google.com/file/d/1dglJiu_Oenh1LRS_sa9MGZanL7sIooe5/view?usp=sharing

Basic code for movement
https://drive.google.com/file/d/11oeQGMGWfhROvdwhVrqjxp68QBn4SMpq/view?usp=sharing
## Steps to reproduce

1. Open second file with r397
2. Verify that everything is fine
3. Open same file with r397.2
4. Verify that project won't open

## Observed result

Project doesn't open

## Expected result

Project opens normally

## More details

I'm not using any community addons for this test to avoid potential issues regarding external code.

I've tried it in Chrome Web browser and in the Chrome application (not sure what the correct name is for this one)
Firefox seems to open fine

**Affected browsers/platforms:** 
Chrome, windows

**First affected release:** 
r397.2

## System details

<details><summary>View details</summary>

OS Name	Microsoft Windows 10 Pro
Version	10.0.19045 Build 19045
System Type	x64-based PC
Processor	AMD Ryzen 7 5800X 8-Core Processor
RAM        16.0GB
Browser Google Chrome 128.0.6613.120 (64-bit)

</details>

**Comment by AshleyScirra** [comment]
Both projects open just fine for me in r397.2.

When it fails to open, press F12 and check the browser console - there may be a more detailed error message there. Also try disabling any browser extensions you have installed in case they are interfering.

**Comment by AshleyScirra** [comment]
Well, it's working fine for me here, and it's very hard to understand how this could have been caused by Construct, as there have been no changes that should affect project file compatibility from r397 to r397.2. The fact it's working for me suggests it's a problem specific to your system, such as perhaps some kind of specific configuration in your browser. Can you provide the system details as the bug report guidelines normally require? Those were omitted from your original report and it's the last thing that might point to some kind of clue as to what happened.

**Comment by KoolGamesRicardo** [comment]
Updated original Report with system details

**Comment by KoolGamesRicardo** [comment]
The console error points to this piece of code
More specifically the last 'else'
Might be an issue with an addon that is installed?
```
Mn = function(d, e) {
    if ("missing-addons" === e.type)
        CCG.N.g.P.O("MissingAddons").R({
            e4: e.e4,
            s4a: e.s4a
        });
    else if ("saved-with-future-release" === e.type) {
        d = CCG.N.sd.vB;
        const f = CCG.N.mQ(e.lrc);
        e = CCG.N.Hwb(e.lrc);
        CCG.N.g.P.O("OK").R(CCG.N.j(CCG.N.ae, co("ui.errors.project-saved-in-newer-release", f, d), {
            links: [location.origin + "/" + e]
        }))
    } else
        console.error("[Project] Exception opening: ", e),
        CCG.N.g.P.O("OK").R({
            message: (0,
            CCG.Dn)(d),
            aqc: !0
        })
}
```

**Comment by AshleyScirra** [comment]
Please get the system information from Construct's Platform Info dialog as per the bug report guidelines.

I'm afraid posting code snippets doesn't help us understand why the problem happened in the first place.

**Comment by KoolGamesRicardo** [comment]
I've figured out the issue, it seems like an addon that was installed but not required or used in the project that was trying to open, was causing the issue.
