### ISSUE TITLE
Hierarchy: The child object has the 'No Save' behavior,  when using the system 'save / load' action will load failed

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8200]
## Problem description

Hierarchy: The child object has the 'No Save' behavior, when using the system 'load' action will load failed.

![image](https://github.com/user-attachments/assets/f86e6f1e-ed15-4a64-a15a-0325603ebfab)

## Attach a .c3p

[childobj-nosave.c3p.zip](https://github.com/user-attachments/files/16852075/childobj-nosave.c3p.zip)

## Steps to reproduce
1. pressed '1'
2. pressed '2'
3.

## Observed result

load failed

## Expected result

load complete

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by akarmehmet** [comment]
@DiegoScirra When you open the attached project with version 388.2 and earlier, the load operation can be performed without any problems. The problem started after version 388.2.

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta, was introduced in r391 as a result of fixing #7971. Both issues should be working now.
