### ISSUE TITLE
Translate: 'System objects not display translations in event dialog title

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8201]
## Problem description

In the title of the event dialog(Contains condition and action), 'System' object type was not correctly displayed as translated. It seems that it no used the translation terms

<img width="1280" alt="Snipaste_2024-09-04_12-32-24" src="https://github.com/user-attachments/assets/a4adb859-5e8c-413d-9a7b-919d4aabf9b9">

 
There is also Contains description
<img width="460" alt="85694a91a5c3fefab5b519f18f518683" src="https://github.com/user-attachments/assets/e8336bdd-34ea-40b9-81c7-54ea66310cf6">

## Steps to reproduce
1. Switch to any language 
2. Add event
3. 

## Observed result

Display as 'System'

## Expected result

Display as translated

## More details

**Affected browsers/platforms:** 

**First affected release:** r206

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I noticed this also happens with 'Functions'. Should be fixed in the next beta.
