### ISSUE TITLE
Using the host browser in multiplayer

### ISSUE THREAD

**Issue by unluckysoon** [Scirra/Construct-bugs#8203]
## Problem description

Hello! I'm having an issue while creating a game using the multiplayer object and I'm reaching out for help.
I'm testing with the MULTIPLYAER:PONG example provided.
After the host and peer are connected, if the host minimizes their browser, the game stops and doesn't proceed. The game resumes when the host reactivates their browser.
Could you provide some guidance on this issue?

## Attach a .c3p
example) MULTIPLYAER:PONG

## Steps to reproduce
1. The host user joins.
2. The peer joins.
3. While playing the game, the host minimizes their browser.
4. The game is frozen on the peer's screen.

## Observed result
The game is frozen on the peer screen.

## Expected result
The game should play on the peer screen even if the host's browser is minimised

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

Chrome Browser 128.0.6613.119

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
I think this used to work but got broken at somepoint. I've updated the next beta which should fix it so the host stays active even when they minimize the window - but note this is at the discretion of the browser, and sometimes they force background pages to shut down to save memory, so if that starts happening I'm not sure there's much more we can do.

**Comment by unluckysoon** [comment]
> I think this used to work but got broken at somepoint. I've updated the next beta which should fix it so the host stays active even when they minimize the window - but note this is at the discretion of the browser, and sometimes they force background pages to shut down to save memory, so if that starts happening I'm not sure there's much more we can do.

It works well. Thank you so much,
