### ISSUE TITLE
Missing type in PluginInfoCategory

### ISSUE THREAD

**Issue by yannloosli** [Scirra/Construct-bugs#8207]
## Problem description

Here is the current def:
![image](https://github.com/user-attachments/assets/bd42060f-e3d4-4dff-9377-248730a1db6c)

It seems that "html-elements" is missing.

## Attach a .c3p

Not needed I think...

## Steps to reproduce

Not needed I think...

## Observed result

TS warning

## Expected result

No TS warning...

## More details
I'm using r405beta.

**Comment by AshleyScirra** [comment]
Updated for the next beta.
