### ISSUE TITLE
Ease Editor Bug

### ISSUE THREAD

**Issue by CrackHub** [Scirra/Construct-bugs#8208]
## Problem description

Editing segment crashing editor.

## Attach a .c3p

[easebug.zip](https://github.com/user-attachments/files/16919735/easebug.zip)

## Steps to reproduce

1. Double click on "Ease 1"
2. In Ease Editor, click yellow dot.
3. Change segment to Cubic.
4. Change segment to Linear.

## Observed result

Crash

## Expected result

No crash

## More details

**Affected browsers/platforms:** Chrome 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled exception
File: https://editor.construct.net/r405/projectResources.js, line 2956, col 31
Message: Uncaught TypeError: Cannot read properties of null (reading 'fGa')
Stack: TypeError: Cannot read properties of null (reading 'fGa') at Jbb.Nac.fGa (https://editor.construct.net/r405/projectResources.js:2956:31) at CCG.Jl.g.J.hl.o1b.j3c [as mIb] (https://editor.construct.net/r405/projectResources.js:2920:144) at Uh (https://editor.construct.net/r405/main.js:317:90) at CCG.Jl.g.J.hl.o1b.Qca (https://editor.construct.net/r405/main.js:1787:29) at HTMLSelectElement. (https://editor.construct.net/r405/main.js:1785:134)
Construct version: r405
URL: https://editor.construct.net/r405/
Date: Sat Sep 07 2024 22:45:32 GMT+0300 (GMT+03:00)
Uptime: 161.6 s

Platform information
Product: Construct 3 r405 (beta)
Browser: Chrome 128.0.6613.120
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 0.8999999761581421
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1060 3GB (0x00001C02) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by CrackHub** [comment]
Also I post some enhancements. I hope we have this features. 
https://github.com/Scirra/Construct-feature-requests/issues/345#issuecomment-2336430271

**Comment by DiegoScirra** [comment]
The issue will be fixed in the next beta.
