### ISSUE TITLE
SDK v2 - ISDKBehaviorInstanceBase._loadFromJson is called twice for the same UID

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8209]
## Problem description

When an object is loaded, sometimes the _loadFromJson  is called twice. That's because the loadState methods of the engine assumes the UID loading order is the same for the objects that do not exist and need to be recreated after a loadState call. You can verify this behavior with the bullet-behavior example, also attached in the issue.

## Attach a .c3p
[bullet-load-error.zip](https://github.com/user-attachments/files/16919759/bullet-load-error.zip)
[behavior-basic-bullet.zip](https://github.com/user-attachments/files/16919761/behavior-basic-bullet.zip)

## Steps to reproduce

1. Attached project has 3 objects in the layout.
2. Press "S" to save the state of the scene
3. Press "D" to delete the instance UID 2.
4. Press "L" to load the state
5. Check the dev-console and you will notice a log with the UIDs being loaded
![image](https://github.com/user-attachments/assets/2121ef2d-df5e-4788-9931-490005c6c379)
6. Verify that the UID 4 appears twice, because its _loadFromJson method was called twice too. 
7. The missing instance UID 2 was never called to be loaded. This behavior is incorrect.

## Observed result

The _loadFromJson is called twice for the same UID

## Expected result

The _loadFromJson must be called for the missing instance, not twice for one of the existing instances.

## More details

r405 beta

## System details

No exceptions thrown, just an incorrect behavior is present.

**Comment by AshleyScirra** [comment]
It's actually correctly loading all three instances, but for one of the instances, `instance.uid` returns an incorrect value as it captured the wrong value after loading. It should be fixed in the next beta, which ensures `instance.uid` is correct after loading a savegame.
