### ISSUE TITLE
A Newly created Object That Has Physics starts Jittering & Moving When Created 

### ISSUE THREAD

**Issue by Tarek200** [Scirra/Construct-bugs#8210]
When I spawn a ball that has Physics, the ball starts jittering and moving when created despite that I dont apply any force to it.
The problem seems to be linked to when I destroy the ball that is already in the layout and right after, on the same tick, I spawn a new ball so the old ball seems to have an effect on the new ball not sure why. This is just guessing because if I add a small (wait for 0.1) before spawning the new ball the bug doesn't occur.

[Physics Bug1.zip](https://github.com/user-attachments/files/16919998/Physics.Bug1.zip)

## Steps to reproduce

1. Run the project
2. Mouse Right-Click
3. Wait till spawns a new ball

## Observed result

99% of the time when the ball is spawned starts Jittering & Moving

## Expected result

The new ball spawns without not  Jittering or Moving. It should be 100% immovable (Velocity X&Y = 0)

## More details

**Affected browsers/platforms:** 
Chrome

**First affected release:** 
r397-2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r405 (beta)
Browser: Chrome 128.0.6613.120
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 71 gb
Storage usage (approx): 187 mb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1070 (0x00001BE1) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
I think this is just because 'Destroy' does not take effect instantly. (If you have events like 'Destroy enemy, create explosion at enemy', then it still works because the destroy is not actually done until later.) Therefore your project creates a new physics body directly on top of the existing one, which is not realistic, so the engine tries to resolve the situation by giving both bodies some velocities to move them apart. Adding a wait means the old object is truly destroyed before creating the new one. Another workaround is to disable the physics behavior just before the 'Destroy' action so it immediately stops the physics simulation.

**Comment by Tarek200** [comment]
> herefore your project creates a new physics body directly on top of the existing one, which is not realistic, so the engine tries to resolve the situation by giving both bodies some velocities to move them apart

Hi Ashley
Thanks for the explanation
That's exactly what I thought was happening, though to prevent that situation from happening that's why I added before destroying the ball an action move to a position:
X = - 100000
Y = - 100000

So how can they interact? as the new ball gets created at:
X = - 309
Y = - 576


![0ccf01](https://github.com/user-attachments/assets/c7e49cb3-67f5-43c7-aacd-cf5e81632e73)

**Comment by AshleyScirra** [comment]
The Physics engine updates on a per-tick basis, not instantly. So that position change would only affect the physics engine at the next tick, at which point another physics object is created over it.
