### ISSUE TITLE
When duplicating a Layout, the editor properties for each Layer are not included

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8212]
## Problem description

In the Layer Properties, check Preview parallax in editor
![image](https://github.com/user-attachments/assets/1583f6a8-e8ee-4e08-a727-7e0bb0dd8d9f)

And then Copy the Layout
![image](https://github.com/user-attachments/assets/9ce5f96c-3666-48c6-9f37-2f721ba9a187)

The new Layout will not retain the parallax properties

## Attach a .c3p

[previewlayerparallax-copyLayout.c3p.zip](https://github.com/user-attachments/files/16941286/previewlayerparallax-copyLayout.c3p.zip)

## Steps to reproduce
1. Check the "parallax in editor" property for each layer in **Layout 1**
2. Copy **Layout 1**
3. 

## Observed result

Layout 2 does not included the editor properties of each layer of Layout 1

## Expected result

When copying Layout, the Layer editor properties are also included

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the first beta after the next stable release.
