### ISSUE TITLE
Missing GetObjectClassBySID function

### ISSUE THREAD

**Issue by yannloosli** [Scirra/Construct-bugs#8215]
## Problem description

Creating a DOM plugin, I need to link an instance to another type of object. 
I have a plugin creating Map, and another creating marker on it. I need to tell on which map each marker will be instantiated.
I can get the SID of the map. But once in instance.js, I can't figure where to find **GetObjectClassBySID**. I see it in TS def, but I can't find where to call it. Maybe I've missed something, but I am almost sure it is missing.

## Attach a .c3p
Not needed I think

## More details
In sdkV1, I was doing it like this : 
```
this.mapUid = this._sdkType._runtime._objectClassesBySid.get(this.mapSid)
```

## System details

<details><summary>View details</summary>

Using C3 r406 beta
</details>

**Comment by AshleyScirra** [comment]
There is [no such documented method](https://www.construct.net/en/make-games/manuals/addon-sdk/runtime-reference/runtime) in the Addon SDK v1. Therefore this has never been supported and your addon has already been at risk of breaking at any time.

If you need this to port your addon to SDK v2, you can [submit a feature request](https://github.com/Scirra/Construct-feature-requests), which should describe your use case and why you need this.

**Comment by yannloosli** [comment]
That's a good news. I was a little lost with your first answer 😌

**Comment by AshleyScirra** [comment]
Added `runtime.sdk.getObjectClassBySid()` for the next beta.
