### ISSUE TITLE
SDK v2 - IsPreview() method from IRuntime is missing in SDK v2

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8225]
## Problem description

IsPreview() method is missing in SDK v2. It should be available for backwards compatibility with ported addons.
Many 3rd party integrations need thorough testing even when the addons are already developed and used. Therefore, I have several plugins that evaluate when the developer is running in preview mode to notify them of erros or important messages that should not be visible in the exported game. To automate this considerations, IsPreview() was an official feature from SDK v1 that I used widely.

Use Cases:
1. GA4 avoids tracking in preview mode to prevent the analytics from getting garbage traffic from testing.
2. For integrating with a 3rd party portal that uses is own API, the plugin sends important messages to the developers while developing the game. Those messages are omitted in the exported game automatically.

![image](https://github.com/user-attachments/assets/1bd84038-8696-4be6-a229-fd659cecfc4b)

## Attach a .c3p

Not applicable

## Steps to reproduce

Method is missing in the SDK v2 API

## Observed result

Method should be available

## More details

r406-2 Beta

## System details

No exception, method is just missing.

**Comment by AshleyScirra** [comment]
This is already supported via [IPlatformInfoObjectType](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/plugin-interfaces/platform-info) with the `exportType` property. However it does require that the Platform Info object is added to the project. Possible workarounds are to use alert() if `runtime.platformInfo` is not set, or fall back to checking `location.origin === "https://preview.construct.net"`.

**Comment by sotano42** [comment]
> This is already supported via [IPlatformInfoObjectType](https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/plugin-interfaces/platform-info) with the `exportType` property which is `"preview"` in preview mode. However it does require that the Platform Info object is added to the project. Possible workarounds are to use alert() if `runtime.platformInfo` is not set, or fall back to checking `location.origin === "https://preview.construct.net"`.

@AshleyScirra  I can workaround that, but the fact is that the feature was removed from the runtime and moved to a plugin, which is a breaking change of an official feature. Now, we have an unnecessary dependency to add another plugin. Please, keep the sdk v1 features backward compatibility as they were. I'm migrating all of my addons which used only official features, yet they are breaking because of little changes like this.
