### ISSUE TITLE
AJAX Progress Trigger and Expression does not work with upload Binary PUT

### ISSUE THREAD

**Issue by vicbarbosa** [Scirra/Construct-bugs#8229]
## Problem description
I made a minimal project where users can record videos and upload the videos to a server API
When an AJAX Binary PUT is sent. AJAX On Progress never triggers and AJAX.Progress never updates.
I want to be able to show the upload progress to my users, since this can take very long, but it simply does not work as described in the documentation.

However, Progress Trigger and AJAX.Progress does work fine with download requests such as AJAX Request URL ("GET")

## Attach a .c3p

> For security reasons, this example project will **only work by entering the Auth Token I will provide in private** through Ashley's email. I'll be linking this issue in the email.
[ajax-upload-progress-bug.zip](https://github.com/user-attachments/files/17034033/ajax-upload-progress-bug.zip)

## Steps to reproduce

1. Request camera permission
2. Start recording (Record a long video)
3. Stop recording
4. Start upload

## Observed result

The progress text does not update, the progress bar does not update, the browser console never logs the Progress Trigger log.
**In short, event 11 never triggers, and it should**
![image](https://github.com/user-attachments/assets/beb0f3b3-25eb-4eab-882f-998d758c52c7)

## Expected result

Progress Trigger should trigger and AJAX.Progress should return the current progress inside the trigger as described in the documentation

## More details

This issue seems to be 10 years old since Construct 2
https://www.construct.net/en/forum/construct-2/how-do-i-18/ajax-progress-post-url-88572

**Affected browsers/platforms:** 

All platforms and systems

**First affected release:** 

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r407 (stable)
Browser: Chrome 128.0.6613.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 586 gb
Storage usage (approx): 151 mb (0%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2070 SUPER (0x00001E84) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
It's the browser that makes the request and reports progress. Construct merely triggers 'On progress' whenever the `onprogress` callback of XMLHttpRequest fires. However it also requires that the `lengthComputable` property of the progress event is set, otherwise it cannot calculate the progress. The fact that some kinds of request show progress demonstrates Construct's code is working correctly to report the progress whenever the browser reports the progress. If some kinds of request don't report progress, that must be either because the browser is not firing `onprogress`, or because `lengthComputable` is false. In either case these are issues with the browser or server, not Construct. There are some known cases where progress events are not reported depending on the server configuration, such as depending on the server's use of compression IIRC - I'm afraid such things are beyond the scope of Construct.

**Comment by vicbarbosa** [comment]
@AshleyScirra thanks for your reply but I think you could take a second look on this

StackOverflow https://stackoverflow.com/questions/20095002/how-to-show-progress-bar-while-loading-using-ajax
![image](https://github.com/user-attachments/assets/2f1e7496-dd6a-4cc2-bdbf-b51bee1de710)

Construct 3
![image](https://github.com/user-attachments/assets/cf5c058c-fe7d-445b-8fc1-a31f0121ffad)

Construct does not seem to access request.upload["progress"]
So I suppose this Trigger is listening only to download events and not upload events.
Also, it seems that request.lengthComputable is different than request.upload.lengthComputable

On a side note, I tried on my end to send the Request Header "Content-Length" str(BynaryData.byteLength) but it seems that Chrome does not allow this header.

**Comment by AshleyScirra** [comment]
Ah, you're right - apologies, I forgot about the separate upload progress handler. However the existing 'On progress' trigger is implicitly an 'On download progress' trigger - I don't think it makes sense to re-use the same trigger for uploads, as if you upload a large request and then download a large response, it doesn't seem right that the same trigger would fire in two sequences, both times going from 0-100, without a good way to distinguish each case. So for the next beta I've added a separate 'On upload progress' trigger which should cover this.

**Comment by vicbarbosa** [comment]
Awesome news! Thank you for the quick replies. Glad we were able to sort this out.

For security reasons, I'll be removing my minimal example from this issue since it is no longer necessary.

**Comment by vicbarbosa** [comment]
Hi, sorry for necroing this issue. Is this planned to get pushed to Stable release anytime soon?

**Comment by vicbarbosa** [comment]
Nvm I just saw it is already live
