### ISSUE TITLE
Example 'Astral Swine' not in R407

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8231]
## Problem description

[r406](https://www.construct.net/en/make-games/releases/beta/r406) has a new examples '[Astral swine](https://editor.construct.net/r407#open=astral-swine)'. but it not in [r407](https://editor.construct.net/#open-example-browser)

The strange thing is the 'Color Sorting Example' that was in same time is in r407, while 'Astral Swine' is not.  

![image](https://github.com/user-attachments/assets/b6d06ef3-83d7-4eb5-b0b1-2ab904f9295f)

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This example was intentionally withdrawn for the time being.
