### ISSUE TITLE
Instance bar: when search no results,  switch layout and clear the search does not restore the list

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8232]
## Problem description

when search no results in Instance bar, switch layout and clear the search does not restore the list

## Attach a .c3p

[issue-Instancebar-search.c3p.zip](https://github.com/user-attachments/files/17043788/issue-Instancebar-search.c3p.zip)

## Steps to reproduce
1. Have 2 Layout, Open the Instance bar
![image](https://github.com/user-attachments/assets/90e8724e-bb14-4a84-bb63-65151537e85e)

2. search anything at Instance bar in Layout 1 
![image](https://github.com/user-attachments/assets/61bef105-9f57-4973-a3f6-2143b80dd091)

3. open Layout 2, and clear the search
![image](https://github.com/user-attachments/assets/5dd1b7c1-2f58-4bfc-a808-253ba7cdea43)

## Observed result

Nothing will be shown until restart the Instance bar 

addition: it will crash if check the "Instances bar" again from "Menu - View - Bars" at this time

![image](https://github.com/user-attachments/assets/d036cb9e-d459-40f4-9b29-6a6b9c467455)

## Expected result

when clear the search, refresh the list. display all instance

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
