### ISSUE TITLE
How do can you unit test Construct when writing Javascript / Typescript?

### ISSUE THREAD

**Issue by npmccauslin** [Scirra/Construct-bugs#8235]
## Problem description

Construct has typescript support, that's been great! However, it uses some pretty specific settings that seem to conflict with jest. Is there some documentation on this or is it possible?

## Attach a .c3p

There really isn't a specific project, in general I haven't been able to get jest to work with construct typescript configuration.

## Steps to reproduce

1. Try to unit test typescript logic in a project.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by XHXIAIEIN** [comment]
You can ask questions here:
https://www.construct.net/en/forum/construct-3/scripting-51

**Comment by AshleyScirra** [comment]
This doesn't appear to be a bug report, so closing. For general discussion it's best to post to the forum.

**Comment by npmccauslin** [comment]
Thanks y'all! @Laserwolve interesting, I tried using Playwright but struggled to get Construct to recognize mouse events, do you run it against a prod build or the remote preview?
