### ISSUE TITLE
Export statistics: minified data shows NaN

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8238]
## Problem description

Export statistics: minified data shows NaN
This applies to any export method.

<img width="320" alt="Snipaste_2024-09-20_13-56-18" src="https://github.com/user-attachments/assets/f7166407-a2f2-4f8e-9eff-39a066c0ee02">

<br>

<img width="480" alt="Snipaste_2024-09-20_13-56-18" src="https://github.com/user-attachments/assets/273f09ca-bc9b-4bd2-9032-11c52c4a016e">

## Attach a .c3p

any project.
e.g: https://editor.construct.net/#open=visual-novel-sniff-and-fetch

## Steps to reproduce

Export HTML5
![image](https://github.com/user-attachments/assets/2545db9a-b9dd-4f8e-94f3-12887a312cca)
![image](https://github.com/user-attachments/assets/4ed3e260-78e9-4a7a-a57e-b8781f66c4ba)

Export Webview2
![image](https://github.com/user-attachments/assets/1b6bc6d8-5437-407c-8b1f-7e308e6daf0f)
![image](https://github.com/user-attachments/assets/2a966a7c-c237-4d5b-99d8-abd2286f7c0d)
![image](https://github.com/user-attachments/assets/52c77bb8-c3c6-4eba-969b-0c908ac8a9a1)

## Observed result

the minified data or compressed is NaN

## Expected result

If not, then display 0

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Fixed for the next release.
