### ISSUE TITLE
Remote Preview no support iOS Wechat In-app browser

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8239]
## Problem description

The iOS WeChat In-app browser cannot use remote preview. 

Remote preview is works on Android WeChat, because WeChat uses other browser kernels in Android. iOS is using WKWebview.

## Steps to reproduce
1. Using iOS [Wechat](https://www.wechat.com/) and Scan the Remote Preview qrcode.  

<img width="260" alt="Snipaste_2024-09-20_15-21-46" src="https://github.com/user-attachments/assets/92e8224d-53f0-45e8-b011-6aae44991ddd">

2. After waiting, a pop-up dialog will appear at the Loading scripts... stage.  

<img width="260" alt="Snipaste_2024-09-20_15-21-46" src="https://github.com/user-attachments/assets/ccf031b6-bebe-40e8-beba-4c2ceb059964">

3. if Click 'OK', The page will go to a black screen. Then nothing happens.   

<img width="260" alt="Snipaste_2024-09-20_15-21-46" src="https://github.com/user-attachments/assets/41479545-7c0a-4f55-9d95-7cbe52d17d5a">

## Observed result

iOS Wechat In-app browser
<img width="360" alt="Snipaste_2024-09-20_15-21-46" src="https://github.com/user-attachments/assets/23fa5a81-9b11-4344-9914-8549ec2b2faf">

## Expected result

This works fine in Safari.
<img width="360" alt="Snipaste_2024-09-20_15-28-53" src="https://github.com/user-attachments/assets/5fb8f4be-8e66-4b69-a6b7-0d11f824a7ed">

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

iOS 18.1
Weixin 8.0.52

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
If it works in Safari my first guess would be this is some kind of problem with WeChat, not Construct, so your first port of call should be to report it to WeChat.
