### ISSUE TITLE
Changing the Tilemap image size shifts all the tiles on the Tilemap on the Layout

### ISSUE THREAD

**Issue by FuzzyPixelGameStudio** [Scirra/Construct-bugs#8240]
## Problem description

Found this bug when I tried to add additional buildings to my tilemap. Previously if you would increase Tilemap image height without changing the width or tile properties of a Tilemap image, you would simply add more tiles to Tilemap image, without changing the numbers of existing tiles (still works in r397.2 stable). But in the recent 407 update changing height or width of a Tilemap image (even by 1 pixel) shifts all the tiles currently used in the Tileset placed on the layout exacly by 1 to the left. 

## Attach a .c3p

[Tilemap_bug.zip](https://github.com/user-attachments/files/17084678/Tilemap_bug.zip)

## Steps to reproduce

1. Double-click on the Tilemap object on the layout to enter Tilemap source image editor.
2. Add any number of pixels to height (or even width) of the Tilemap source image.
3. Close the editor.

## Observed result

The Tilemap that existed on the layout changes, shifting all the tiles. They now use -1 of their previous position (except for the first row), despite Tiles not changing their numbers in the Tilemap editor.

## Expected result

Tiles on the Tilemap that was placed on the layout does not change, since the numbers of the Tiles they used did not change.

## More details

As far as I understand, the tiles are being counted horizontally starting from the top left corner. So changing the width of the Tilemap can affect how the tiles are being numbered (and therefore can affect which tiles will appear on the Tilemap placed on the layout). But adding the height should not change the displayed tiles since their number did not change. That worked in 397.2 - I've tested that: adding height did not change the tiles used on the Tilemap on the layout.

**Affected browsers/platforms:** Chrome

**First affected release:** 407

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r407 (stable)
Browser: Chrome 128.0.6613.138
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 20
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 139 gb
Storage usage (approx): 129 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1080 (0x00001B80) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
OVR_multiview2
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.265 (video/mp4;codecs=hev1.1.2.L93.B0)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment]
Was introduced in r398 when trying to fix #8065. Looks like we will be doing a patch to the latest stable since this was a regression introduced from the previous stable.
