### ISSUE TITLE
Cannot preview game in r407, working in r397-2

### ISSUE THREAD

**Issue by affinixy** [Scirra/Construct-bugs#8242]
## Problem description

After r407, Chome is unable to preview any project. Even the demo projects or examples will have this error when press preview.

To be sure, I tried running previous version of construct.
When I use https://editor.construct.net/r397-2/ to open projects, preview will work again.

## Attach a .c3p

Any demo or sample project in construct.net will have this error when we try to preview the game

## Steps to reproduce

1. open chrome
2. load any sample project or example
3. press Preview.

## Observed result

After "Please wait loading..."
I see pop up.
"Unable to load all project files in preview. The project may fail to load, or some features may be unavailable. If you are using a private browsing mode, try using the standard browsing mode instead. Check the browser console for more error details."

Console message. There is 1 red error.
[C3 runtime] Failed to load all engine scripts in worker:  TypeError: Failed to fetch dynamically imported module: https://preview.construct.net/scripts/c3main.js

## Expected result

Project to play preview

## More details
**This is the chrome version that r407 is not working. tested on PC 1**
Google Chrome | 129.0.6668.59 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)
-- | --
Revision | 8591405f2525be5aa06c825e3051a243c42a80f1-refs/branch-heads/6668@{#1319}
OS | Windows 10 Version 22H2 (Build 19045.4894)
JavaScript | V8 12.9.202.18

**This is the Chrome version on PC 2 that Construct editor r407 is working**
Google Chrome | 129.0.6668.59 (Official Build) (64-bit) (cohort: Stable Installs & Version Pins)
-- | --
Revision | 8591405f2525be5aa06c825e3051a243c42a80f1-refs/branch-heads/6668@{#1319}
OS | Windows 11 Version 23H2 (Build 22631.4169)
JavaScript | V8 12.9.202.18

Firefox is working on PC 1 and PC 2.

worked in r397-2 but broke in r407

## System details

previewWindow.js:14 [Preview] Error waiting for service worker readiness:  SW ready timeout
SendBlobsToServeFromSW @ previewWindow.js:14
await in SendBlobsToServeFromSW
InitScriptData @ previewWindow.js:10
OnMessage @ previewWindow.js:2
OnMessageFromPort @ bootPreview.js:180Understand this warning

previewWindow.js:17 [Preview] Error serving blobs from Service Worker:  Error: no service worker controller available
    at SendBlobsToServeFromSW (previewWindow.js:15:84)
    at async Object.InitScriptData (previewWindow.js:10:456)

**Comment by AshleyScirra** [comment]
It works fine for me.

Try clearing your browser cache - the latest version has some updated server-side code for preview. It's been out for a month or two already, but if your browser somehow has outdated files it might stop preview working.

**Comment by affinixy** [comment]
Thanks for explaining, I tried clearing my cache and it is still not working.
Your explanation leads me to check out these beta.

406.2 - not working
405  - not working
404  - not working
402  - not working
400  - not working
399 - working
398 - working

Can i ask which is the server side code that was suppose to download dynamically, that is causing the issue.
Is there a way for me to manually add the file into my browser?

**Comment by AshleyScirra** [comment]
r400 is when we introduced our new preview/export code, which requires some server-side changes. This suggests you still have the old files cached which is why the new preview system is not working. As far as I'm aware it's working for everyone else, and if not the solution is you clear your browser cache.

**Comment by affinixy** [comment]
I reinstalled chrome, clear chrome cache and windows temp files, it is working now. Thank you!
