### ISSUE TITLE
"Browser" plugin "does not open URL" in ios 18.0 Before the last apple update everything worked fine

### ISSUE THREAD

**Issue by yaro888** [Scirra/Construct-bugs#8247]
## Problem description

In the latest iOS 18.0 update and the new Xcode 16.0 update, after compiling the project in Construct 3 Stable version r407.2 , the "Browser" plugin stopped working correctly

## Steps to reproduce

In the latest iOS 18.0 update and the new Xcode 16.0 update, after compiling the project in Construct 3 Stable version r407.2 , the "Browser" plugin stopped working correctly - namely, such actions as "open URL in new window" and "go to URL"

## Observed result

any URL does not open

## Expected result

correct work of the "Browser" plugin for iOS devices version 18.0

## More details

everything worked fine before the iOS 18 update on any versions of Construct 3

I'm attaching a screenshot from xcode when I click on the button and then follow the link - but it still doesn't happen(

![photo_2024-09-24_20-16-36](https://github.com/user-attachments/assets/b1caf8d1-3947-4aeb-80c8-0f61ee0bce29)

**Comment by AshleyScirra** [comment]
I think the version of cordova-plugin-inappbrowser used on the build service was out of date. I just updated it - try exporting to Xcode from Construct again, does that fix it?

**Comment by yaro888** [comment]
Yes, everything works great now, thank you!
