### ISSUE TITLE
Black screen in my game with r408

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#8248]
In r408, after few seconds playing my (rather complex) game, it freezes for few secs, and then the screen goes black (showing only HTML elements, like sliders and buttons), and the console shows this:

![{1B03D940-38CE-4F5D-8201-667BABB4A429}](https://github.com/user-attachments/assets/3d4213fc-513d-4c7c-890e-7b5056bf111f)

This does not happen in previous versions, i suspect it has something to do with hierarchies since it happened before after some hierarchy update.

I know this report will probably be closed without investigation since I couldn't reliably reproduce it in a new project, but I'm desperate as beta r408 broke my large project and i don't know how to isolate the issue :(

**Comment by DinoSystem** [comment]
UPDATE: seems like if i remove all "Pick child" events in the project, the bug doesn't occur anymore, this should isolate the issue, but i still can't reproduce it in a simplier project.

**Comment by AshleyScirra** [comment]
I'm afraid it is genuinely impossible for us to investigate a report like this, hence the reason we have bug report guidelines, so closing. Please do file an issue if you can identify a minimal repro.
