### ISSUE TITLE
Whitelist plugins (new & urgent)

### ISSUE THREAD

**Issue by Chadori** [Scirra/Construct-bugs#8249]
Hi,

Would you please whitelist the following new plugins:

```JS
community-cordova-plugin-consent@2.6.2
```

Urgent need due to conflict with `cordova-plugin-device`.

I have followed the required guidelines to the best of my knowledge; please let me know if there are issues with my request.

Thank you.

**Comment by AshleyScirra** [comment]
Is this forked from an existing plugin that was previously allowed? If so please state which.

**Comment by Chadori** [comment]
Hi, yeah, the plugin is `cordova-plugin-consent`.

**Comment by AshleyScirra** [comment]
Added `community-cordova-plugin-consent@2.6.2` to build service.
