### ISSUE TITLE
Instance bar: Crash if check the "Instances bar" again from "Menu - View - Bars" 

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8251]
## Problem description

When the instance bar is already open, click again from the menu will crash

![0](https://github.com/user-attachments/assets/42af3b11-1873-4337-8f6a-aea425a27d9a)

![1](https://github.com/user-attachments/assets/3cbf8b15-1270-4ceb-b9c2-7aa547f5f201)

## Steps to reproduce
1. "Menu - View - Bars" open instance bar 
2. "Menu - View - Bars - instance bar" again 
3.

## Observed result

crash

## Expected result

no crash and close instance bar 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
