### ISSUE TITLE
Game Freeze when destroying object with child entity

### ISSUE THREAD

**Issue by zakkaplay** [Scirra/Construct-bugs#8252]
## Problem description

The game freezes when destroying an object with a child.

## Attach a .c3p
Google Drive : 
https://drive.google.com/file/d/1O8vQfbmpDydZRdkzuMSpsd313f3VWv1i/view?usp=sharing

## Steps to reproduce

1. Run the game
2. Tap to continue.
3. The character will move towards the object to collect the item & trigger the bug

## Observed result

The game will freeze.

## Expected result

The game should not freeze. 

## More details
I have created added a work around which does not freeze the game, which requires the child to be destroyed first. 

## System details
From Console : 
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'IsOriginalSizeKnown')

at SceneGraphInfo.GetParentScaleX (sceneGraphInfo.js:6:238)

at WorldInfo.GetX (worldInfo.js:15:86)

at WorldInfo.RemoveChild (worldInfo.js:39:411)

at WorldInfo.Release (worldInfo.js:9:441)

at Instance.Release (instance.js:6:225)

at C3Runtime._ReleasePendingInstances (runtime.js:97:426)

at C3Runtime._DoChangeLayout (runtime.js:101:472)

at async C3Runtime._MaybeChangeLayout (runtime.js:98:89)

at async C3Runtime.Tick (runtime.js:90:46)

</details>

**Comment by AshleyScirra** [comment]
The project uses a third-party addon *Behavior Trail Renderer (skymenTrail) by skymen*. Please provide a project file not using any third-party addons as per the bug report guidelines.

**Comment by zakkaplay** [comment]
The Trail Renderer is removed. 
[Uploading Game Freeze when destroying object with child entity.zip…]()

**Comment by DinoSystem** [comment]
I think I also got this issue on my project

**Comment by zakkaplay** [comment]
Not sure if the new file is uploaded correctly, but I've added a link to my google drive: 
[https://drive.google.com/file/d/1O8vQfbmpDydZRdkzuMSpsd313f3VWv1i/view?usp=sharing](url)

**Comment by zakkaplay** [comment]
Trying again:
https://drive.google.com/file/d/1O8vQfbmpDydZRdkzuMSpsd313f3VWv1i/view?usp=sharing

**Comment by AshleyScirra** [comment]
This project has hundreds of events. I'm afraid such projects are often pretty much impossible to debug. Can you provide a minimal project as per the bug report guidelines?

**Comment by DinoSystem** [comment]
I'll try to simplify the project if @zakkaplay doesnt show up

**Comment by DiegoScirra** [comment]
Should be fixed by the next beta.
