### ISSUE TITLE
Request pointer lock won't work on Steam Deck when unadjusted movement is set to true.

### ISSUE THREAD

**Issue by bilgekaan** [Scirra/Construct-bugs#8257]
## Problem description

Request pointer lock won't work on Steam Deck when unadjusted movement is set to true.

I tested it with NW.js on Steam Deck and the web version on Steam Deck’s Desktop mode using Chrome. The pointer lock doesn’t work in either of these situations. Console shows: 'Uncaught (in promise) DOMException: The options asked for in this request are not supported on this platform.'

I’m not sure if it’s fixable, so it would be useful to check if unadjusted movement is supported before making the request.

## Steps to reproduce

1. Open Steam Deck's desktop mode.
2. Try this game: https://bilgetbd.itch.io/pager

**Comment by AshleyScirra** [comment]
Chrome doesn't support the 'unadjusted movement' option on Linux. [This page](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock) indicates it's only supported on Windows, macOS and ChromeOS. So it won't work until Google add support for it in Chrome.

**Comment by F3der1co** [comment]
> Chrome doesn't support the 'unadjusted movement' option on Linux. [This page](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestPointerLock) indicates it's only supported on Windows, macOS and ChromeOS. So it won't work until Google add support for it in Chrome.

The problem is that there isn't a proper way for us to handle this with the mouse plugin. On pointer lock error runs a lot for other reasons (trying to request shortly after releasing it)
