### ISSUE TITLE
AJAX plugin bug from version r400 onwards

### ISSUE THREAD

**Issue by maickbicho2** [Scirra/Construct-bugs#8258]
## Problem description

the ajax plugin URL request when made for internal project files if it contains letters in capslock (capital letters) no longer works since version r400.

my project has more than 10,000 well-optimized events and with 3 years of development, how did this work before this update, my entire project has words in capslock, please solve this.

## Steps to reproduce

just make an AJAX request for a file within the project in the "files" folder but write the URL in capslock (capital letters)

1.
2.
3.

## Observed result

dont work

## Expected result

work

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
![fffffffffffffffffffffffffff](https://github.com/user-attachments/assets/252edbe8-d895-4dd9-a70a-9555bdb7b776)
![hhhhhhhhhh](https://github.com/user-attachments/assets/7fd7da22-ff9c-40fc-ab18-1dfd8f4cb8a5)

**Comment by maickbicho2** [comment]
![fffffffffffffffffffffffffff](https://github.com/user-attachments/assets/7b533bd3-0bcb-4936-8fab-8a1c44161ed6)
![hhhhhhhhhh](https://github.com/user-attachments/assets/edd715d0-07be-446f-8a0d-1f20a298c34a)

**Comment by AshleyScirra** [comment]
No sample project was provided as the bug report guidelines require. I made a test project that requests a file named "TEST.txt" in r407.2 and it works fine: [issue8258.zip](https://github.com/user-attachments/files/17188129/issue8258.zip)
Therefore the issue as stated appears to be wrong, as this feature does appear to still be working correctly beyond r400.

If you recently changed your project's 'Export file structure' mode to 'Folders', you may need to update some paths. See [this guide](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/deprecated-features) for more details.
