### ISSUE TITLE
Export game - Virus?

### ISSUE THREAD

**Issue by starkiJi** [Scirra/Construct-bugs#8260]
- Online virus scanner finds viruses ( 2 screenshots ).
- The project is empty, has only 1 sprite.
- r407-2 or r388-2
- **Export MacOS(WKWebView) - clear**,  **Export Windows(WebView2) and NW.js - virus**
- It might be because of the plugins for construct 3, but I did NOT add them to the project.

![99](https://github.com/user-attachments/assets/2db553f0-4a00-404b-a975-8d49b708f8f7)
![888](https://github.com/user-attachments/assets/6fdaea5c-8dd8-460c-81d9-3b0698f61b3d)

**Comment by AshleyScirra** [comment]
These look like false positives. You'll need to report them to the antivirus vendor as such.
