### ISSUE TITLE
Instance bar: Crash after delete instance then undo, and Change the Hierarchy

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8262]
## Problem description

Crash When delete the instance, undo, and Change the Hierarchy in the Instance bar.

## Attach a .c3p

[issue-instancebar-undo.c3p.zip](https://github.com/user-attachments/files/17210109/issue-instancebar-undo.c3p.zip)

## Steps to reproduce

1. Select all Sprite
![image](https://github.com/user-attachments/assets/5d0608df-68a9-4910-ac4b-b47a13c3e434)

2. delete
![image](https://github.com/user-attachments/assets/9f9c560b-1e0c-4bdd-a6ea-a3cff6e9bbad)

3. undo
![image](https://github.com/user-attachments/assets/55a5af74-c33b-4549-98b8-a0940b2e2b57)

4. Adjust the hierarchy of instance in the Instance bar
![image](https://github.com/user-attachments/assets/a9b3ab9e-79ab-429a-8793-c64884a39cc0)

## Observed result

![image](https://github.com/user-attachments/assets/078a4809-bd53-49d1-8688-6d75cc45d1a8)

## Expected result

no Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
