### ISSUE TITLE
Instance bar: Crash when rename global layer

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8264]
## Attach a .c3p

[issue-instancebar-globallayer.c3p.zip](https://github.com/user-attachments/files/17210725/issue-instancebar-globallayer.c3p.zip)

## Steps to reproduce
1. open Instance bar
2. rename 'Global 2' to other name 

## Observed result

![image](https://github.com/user-attachments/assets/10a79b8a-7876-4b44-b222-3d49cad2ed7a)

## Expected result

no Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
