### ISSUE TITLE
Instance bar: Crash when add Hierarchy in global layer but other layer not exist in the other layout

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8266]
## Attach a .c3p

[issue-instancebar-globallayer-2.c3p.zip](https://github.com/user-attachments/files/17211352/issue-instancebar-globallayer-2.c3p.zip)

## Steps to reproduce

In Layout 2, have 2 global layer
![image](https://github.com/user-attachments/assets/a5b69d86-1b44-402e-ad0c-3b5bc1d3abfc)

![image](https://github.com/user-attachments/assets/cdfa2ee2-d762-4178-b7f4-b741d28ce84b)

In Layout 1, use the gloal layer 
![image](https://github.com/user-attachments/assets/f126b67d-4267-47a6-93a5-6c18424d605d)

then open instance bar, open Layout 1

## Observed result

![image](https://github.com/user-attachments/assets/e4e00562-2f50-4f47-b478-b10ea8eb524c)

## Expected result

No Crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
