### ISSUE TITLE
int() vs floor()

### ISSUE THREAD

**Issue by oosyrag** [Scirra/Construct-bugs#8268]
## Problem description

int() seems to have the exact same function as floor(). This can be observed with a negative number, where the result is rounded down instead of truncated (rounded towards 0). Is this intended?

## Attach a .c3p

https://www.dropbox.com/scl/fi/l4uwa2ff1u8ypg67yx6es/int.c3p?rlkey=ua1c6vfzk7qtir617xjotbyei&st=ccu75alw&dl=0

## Steps to reproduce

Preview project

## Observed result

int(-123.4) and floor(-123.4) both return -124

## Expected result

int(-123.4) would return -123

## More details

I'm assuming this isn't intended, as floor() and ceil() round towards negative and positive infinity, while int() should truncate or round towards 0.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
The purpose of `int` is to convert a string to an integer - the integer counterpart to the `float` expression. As it happens you can pass it a number and it does do the same as floor() in that case, but that's not the main purpose it exists.
