### ISSUE TITLE
Software crashes while copying flowchart from one project to another

### ISSUE THREAD

**Issue by xinlanjun** [Scirra/Construct-bugs#8271]
## Problem description

Software crashes while copying flowchart from one project to another

## Attach a .c3p

no need

## Steps to reproduce

1.Create a new project, make a flowchart
2.Create a new project and copy the previous flowchart
3.

## Observed result

![bug2093](https://github.com/user-attachments/assets/b5d6ada8-00f9-43f2-b993-909f9bdef359)

## Expected result

Don't crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
