### ISSUE TITLE
The save and load system not include the state of the DrawingCanvas

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8275]
## Problem description

The save and load system not include the state of the DrawingCanvas

## Attach a .c3p

[issue-saveload-drawingCanvas.c3p.zip](https://github.com/user-attachments/files/17277083/issue-saveload-drawingCanvas.c3p.zip)

## Steps to reproduce

1. Use Mouse to draw any thing.
2. Press 1 to save.
3. Press space to clear canvas.
4. Press 2 to load.

## Observed result

DrawingCanvas has not changed

## Expected result

DrawingCanvas will load the state when saving

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
It's currently by design that Drawing Canvas does not save its image with savegames. Doing so could cause accidentally very large savegame data.
