### ISSUE TITLE
Bookmark Bar - Crash when clicking bookmark

### ISSUE THREAD

**Issue by Jase0000** [Scirra/Construct-bugs#8277]
Occasionally I am double-clicking a bookmark and getting a red C3 crash screen. Crash report below.

Once this occurs, if I had saved beforehand, I am able to crash the project by starting C3, opening project, double click the offending bookmark, and same crash appears.

## Steps to reproduce

Unfortunately I cannot find a way to repro this, but I have tried flicking between event sheets, adding, cutting and pasting, etc.

I can nuke my entire project until it is just the offending bookmark, let me know if this would help and I will do this.

I remember this occurred in the past and was fixed, I was so sure this never happened again ever since and I often use bookmarks, but yeah, here we are.

## Observed result

Crash

## Expected result

No crash

## More details

Latest Chrome, no extensions.

**First affected release:** 
r410

## System details

<details><summary>View details</summary>

Error report information
Type: assertion failure
Message: bookmark does not belong to this event sheet
Stack: Error at za.y9a (https://editor.construct.net/r410/main.js:1093:314) at window.assert (https://editor.construct.net/r410/main.js:1008:353) at d.Gcb (https://editor.construct.net/r410/components/editors/eventSheetView/eventSheetView.js:176:233) at https://editor.construct.net/r410/components/bars/bookmarksBar/bookmarksBar.js:10:409
Construct version: r410
URL: https://editor.construct.net/r410/
Date: Wed Oct 09 2024 21:55:53 GMT+0100 (British Summer Time)
Uptime: 15.7 s

Platform information
Product: Construct 3 r410 (beta)
Browser: Chrome 129.0.6668.90
Browser engine: Chromium
Context: browser
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce RTX 2060 (0x00001F15) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing
</details>

**Comment by DiegoScirra** [comment]
I think the previous issue was #7672. I have a feeling it must be something similar.

**Comment by Jase0000** [comment]
Yeah it's baffling, it seems very common all of a sudden so I'm clearly doing some sort of behaviour that's triggering it!  I encountered it about 5 times in a day. (I clear bookmarks, continue on, then suddenly encounter again). 

I'm mostly in a few event sheets, maybe 3 or so, placing bookmarks, jumping between them, changing events, hitting undo/redo at times, occasionally visit a layout and then back to event sheet. 

If you do think an minimal project of the corrupt bookmark would maybe give clues, do let me know, I took a backup of the corrupt bookmark project, might take a bit of time for me to trim down huge project, happy to do it of course but maybe you have an inkling already from the posted bug log. 

It might be quick for me to get this for you, but might be time consuming if I end up having to "test" along the way, making sure the bug still triggers rather than quickly deleting everything and the bug doesn't occur anymore, and maybe you already have an idea and not need this in the end.

**Comment by DiegoScirra** [comment]
Check the next release for a possible fix to this issue. I have a feeling the change I made will fix the problem, but I can't tell for sure because I can't reproduce the crash to begin with. So from the next beta just try it out to see if it happens or not.

**Comment by DiegoScirra** [comment]
If you can come up with steps to reproduce the problem, it would still be useful.

**Comment by DiegoScirra** [comment]
r412 is out now with the potential fix.

**Comment by Jase0000** [comment]
Thank you @DiegoScirra , I used event sheets a lot yesterday, bookmarks a lot, no crash as of yet. Will continue each day. 

I'm convinced it's fixed:  I opened the backup project I kept with the "broken bookmark", still crashes in r410, doesn't crash in r412 and takes me to the bookmark! 

Thank you so so much, you can imagine the fright I would get when midway in deep coding session and suddenly hit with red crash screen. Very grateful for your help, even with my vagueness in bug report!

**Comment by DiegoScirra** [comment]
I will close this as I am pretty certain the issue is fixed now. It had to do with a cache used to lookup bookmarks becoming stale. Now the cache is no longer used so that problem should not happen again.
