### ISSUE TITLE
Video plugin, lags

### ISSUE THREAD

**Issue by starkiJi** [Scirra/Construct-bugs#8280]
Performance issue. 
Due to a large number of video instances with different video recordings, all video instances slow down when playing (on a good PC). Perhaps you can make adjustments to the "Video" plugin.

I have prepared an example with 2 scenes, you will immediately notice the problem with the frame rate in the video plugin.

**Source file -** https://drive.google.com/file/d/1SgQMClFU-z8FDzWkg7SINVZiLFciKiJe/view?usp=sharing

**r407.2**

**Comment by AshleyScirra** [comment]
The video plugin is not designed to be used like this, so closing as wontfix. It looks like you ought to be using ordinary sprites instead.

Video playback is a heavyweight feature - it has a high performance overhead. Devices can usually use hardware to decode a few video streams efficiently, but if you use lots then it will likely do most of them with software decoding, which is extremely CPU intensive. This isn't a problem with Construct - it's just how video playback works on computers.
