### ISSUE TITLE
setting a new flowchart with the same tag as a previous one doesn't replace it

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8283]
## Problem description
Setting a new flowchart with the same tag as a previous one doesn't replace it. This is especially confusing if you don't set the tag.

## Attach a .c3p
[flowchartTest.zip](https://github.com/user-attachments/files/17366839/flowchartTest.zip)

## Steps to reproduce

1. preview
2. press A
3. press B

## Observed result
when pressing B the text of the first flowchart is typed

## Expected result
when pressing B the text of the second flowchart is typed

## More details
this is caused by both flowcharts having the same tag, I guess the intended flow is to end a flowchart before starting the next one.
But imo it should be changed so the new flowchart replaces the old one with the same tag. This would make it a lot cleaner especially in situation where you don't care about having multiple flowcharts on the same controller and are just setting them without even defining a tag.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by F3der1co** [comment]
little addition: other construct systems using tags tend to replace instead of failing silently. For example: Timer or advancedRandom probability tables.

**Comment by DiegoScirra** [comment]
This will be changed for the next beta.
