### ISSUE TITLE
empty flowchart tips, the help links should use lists format

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8288]
## Problem description

This manual link part may have a different layout after being translated into other languages, making it difficult to read. 

![image](https://github.com/user-attachments/assets/9ac33b48-1a7c-41a3-884f-ee99d73ee2d3)

## Attach a .c3p

https://editor.construct.net/r411/

## Observed result

For more information see the following manual entries: link1, link2, link3

## Expected result

For more information see the following manual entries: 
- link1
- link2
- link3

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
That particular list of links is generated using the browser's built in translation object, so the list should be generated using the correct punctuation for the chosen language.

I can only verify it for English, Spanish and other lanuages similar to Spanish.

**Comment by XHXIAIEIN** [comment]
I think can use a list like in Timeline
![image](https://github.com/user-attachments/assets/4bde066a-37e9-44e7-94c0-4501018ec104)

**Comment by XHXIAIEIN** [comment]
My description might be misleading, I made a quick demo:

![image](https://github.com/user-attachments/assets/4007eef4-7e55-4a47-8d8a-ac33a82cae5a)

**Comment by AshleyScirra** [comment]
> This manual link part may have a different layout after being translated into other languages, making it difficult to read.

It should wrap like any other text. Can you explain what it is about normally wrapping text with links in it that makes it difficult to read?

**Comment by XHXIAIEIN** [comment]
Although the text can be wrapped, it does not look beautiful. The text of these 3 links looks very similar, and together they are not that attractive. Identify them on the same line as would in a captcha.

Especially in Chinese, the text is wrapped by character in Chinese. At first glance, users only see "Flowchart", and it is difficult to distinguish between the three of them at the first time.

![image](https://github.com/user-attachments/assets/49f8217f-467b-4b9a-b682-f9fdc8169226)

Especially in the case that the window is not fully opened and the window width is insufficient.

![image](https://github.com/user-attachments/assets/e6c63565-4764-40eb-afdc-308c2aaa26ce)


If use a list to display this information, it will look much clearer

![image](https://github.com/user-attachments/assets/3b91b456-e672-4c58-9470-2faf8ac11c5c)

**Comment by AshleyScirra** [comment]
I think that qualifies as a feature request instead of a bug since nothing is actually broken and it's just a request to change how some text is laid out, so closing - please file it as a suggestion instead.
