### ISSUE TITLE
[BUG] Drawing canvas - Image saved and loaded in another sprite does not visually match on PC vs Mobile

### ISSUE THREAD

**Issue by Kashin-Ginn** [Scirra/Construct-bugs#8292]
## Problem description

I was using the drawing canvas object to paste object A and saved the image to another sprite object B. The save works except the saved image is visually different on a PC vs on a mobile. 

## Attach a
[drawingCanvas_pasteAndSave_singleFile.zip](https://github.com/user-attachments/files/17531449/drawingCanvas_pasteAndSave_singleFile.zip)
 .c3p

## Steps to reproduce

1. Launch the project on PC and watch the result
2. Launch the project again but on a mobile (via preview) or directly on chrome itself (via device simulation)

## Observed result
The result is not the same on both. (Visually, the saved image is slightly misplaced)

## Expected result
The saved image in the sprite should be similar be it on a PC or on a mobile device

## More details

**Affected browsers/platforms:** 
Tested on Chrome and Android, not sure about others

**First affected release:** 
r412... 
I replicate the issue on r350 just for test... same bug. Looks like it was there since long
## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by Kashin-Ginn** [comment]
![pasteAndSave_comparison](https://github.com/user-attachments/assets/843bc198-6a81-446a-a2aa-4521345d05e9)

**Comment by Kashin-Ginn** [comment]
I'm kindly requesting for a fix soon since this is blocking me from moving forward in my game. I have to re-arrange 3-5 sprites and save it as a single sprite in my game. I cannot think of another solution since this method helps to paste and save an image at a desired position

**Comment by avishaymizrav** [comment]
You can try - System -> Snapshot Canvas
You can set the bounding box of the snapshot around your sprites.

**Comment by Kashin-Ginn** [comment]
@avishaymizrav Thanks for the suggestion but there's no way to load the image on another sprite after snapshot

**Comment by Kashin-Ginn** [comment]
@avishaymizrav 
Hey, thanks for the suggestion, but at the same time, on the forum, I saw the user dop2000 used a formula  "PlatformInfo.CanvasDeviceWidth / ViewportWidth(0)" while saving the image. I tried it and it works!


I'm closing this. The plugin needs an option to do that manually though!
