### ISSUE TITLE
[theme] checkbox in instance bar not styled

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8293]
## Problem description
checkbox of instance bar is not styled like other dark theme checkboxes

## Observed result
![image](https://github.com/user-attachments/assets/bade550c-c0f7-47ad-ad66-70f6a84a2831)

## Expected result
![image](https://github.com/user-attachments/assets/55427d6d-d9d4-4090-9165-f27b37f6f6ca)

**Comment by XHXIAIEIN** [comment]
This also affects the Timeline
![image](https://github.com/user-attachments/assets/96527b29-a862-445f-81c8-3694e83d405f)

**Comment by XHXIAIEIN** [comment]
and Log in
![image](https://github.com/user-attachments/assets/01e3aaae-aa77-4635-9214-6002f659c11d)

**Comment by DiegoScirra** [comment]
Will be fixed on the next beta.

The login dialog will be left as it is now because it's not as easy to change as the rest of the project. It's a very minor issue anyway.
