### ISSUE TITLE
[theme] flowchart reference node not styled correctly in dark theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8294]
## Problem description
flowchart reference node not styled correctly in dark theme

## Observed result
![image](https://github.com/user-attachments/assets/9671a0a2-3a4e-4d8e-9b9a-b56c14152718)

## Expected result
![image](https://github.com/user-attachments/assets/2f9a8473-6c9f-4abe-b798-ee120966234f)

**Comment by DiegoScirra** [comment]
Fixed on the next beta.
