### ISSUE TITLE
[theme] View spritesheets zoom slider not styled correctly in dark theme

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8295]
## Problem description
View spritesheets zoom slider not styled correctly in dark theme

## Observed result
![image](https://github.com/user-attachments/assets/1761c0e3-eb76-4bad-884b-3c2c86f2114a)

## Expected result
![image](https://github.com/user-attachments/assets/68de282b-dfe8-4b53-95a4-dbc1746e1c88)

**Comment by DiegoScirra** [comment]
Fixed on the next beta.
