### ISSUE TITLE
[theme] Addon manager odd formatting of search and checkboxes

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8296]
## Problem description
Addon manager formatting issue of search and checkboxes in dark theme. (I didn't check unthemed, so not sure if isolated to dark theme)

## Observed result
![image](https://github.com/user-attachments/assets/88b6c31d-404f-4cf4-b4ac-ef72e576b7fb)

## Expected result
More space between text and the search box and checkboxes. Text of checkboxes correctly alligned

**Comment by F3der1co** [comment]
un-themed looks better but also not perfect imo (y touching search box and also baseline of checkbox and text offset).
![image](https://github.com/user-attachments/assets/56dc2a0e-47b9-49be-ad95-1e1c8c0643ae)

**Comment by DiegoScirra** [comment]
Fixed on the next beta.
