### ISSUE TITLE
[theme] layer selection in instance bar, color counter to expectations

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8297]
## Problem description
The highlighting of the selected layer in the instance bar using the dark theme is not ideal

## Observed result
![image](https://github.com/user-attachments/assets/18d46b54-ec51-4d32-842d-adb0aa0073e2)
the selected layers text becomes black

## Expected result
They become lighter as that is the dark theme convention for something that is selected.
Or maybe a different way of formatting, just bold and no color change for example. The black looks odd to me

**Comment by XHXIAIEIN** [comment]
if this is the same issue
![image](https://github.com/user-attachments/assets/b48a7cd5-02fb-4a1e-b0d8-b1191feef97a)

Expected result
![image](https://github.com/user-attachments/assets/9e642fc1-8048-45a1-85ac-a322edb4ff85)

**Comment by DiegoScirra** [comment]
@XHXIAIEIN 

That button is part of the default controls the browser provides for audio elements, and there are no CSS selectors to target that element.

The only alternative is to hide all the default controls and implement your own using CSS and JavaScript. In my opinion, it's not worth the trouble.

**Comment by DiegoScirra** [comment]
The first issue will be fixed in the next beta.
