### ISSUE TITLE
[theme] Ease editor>Miscellaneous settings slider not styled

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8298]
## Problem description
In the Ease editor under Miscellaneous settings the Graph slider not styled in the dark theme

## Observed result
![image](https://github.com/user-attachments/assets/dc277818-46e4-4295-9e3e-624a4c75a402)

## Expected result
![image](https://github.com/user-attachments/assets/a69c01e9-d09d-4e02-9b75-a4bcfc03ac35)

**Comment by DiegoScirra** [comment]
Fixed in the next beta.
