### ISSUE TITLE
HTML Elements on invisible layers render regardless of layer visibility

### ISSUE THREAD

**Issue by NickR-Git** [Scirra/Construct-bugs#8299]
## Problem description

HTML Elements on invisible layers render regardless of layer visibility

## Attach a .c3p

Using global layers as an example:
[HTMLBUG.zip](https://github.com/user-attachments/files/17561447/HTMLBUG.zip)

## Steps to reproduce

1. Create a global layer on a layout, uncheck "initially visible"
2. And an HTML element to the layer
3. Add the global layer to another layout

## Observed result

HTML elements render even when they shouldn't.

## Expected result

HTML elements to be invisible

## More details

All platforms effected starting with r413

r413

**Comment by DinoSystem** [comment]
I can confirm this, happens also to non global layers to me

**Comment by AshleyScirra** [comment]
Minimal repro: [issue8299.zip](https://github.com/user-attachments/files/17571265/issue8299.zip)

This is a regression from fixing #7781 in r413: the layer visibility, interactivity and opacity properties now all consistently apply to HTML layers. Visiblity changes still work if they are applied to the [HTML layer](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/html-layers) the object belongs to - but in this case you'd need to add a HTML layer to make it work. So while this would arguably make sense as an initial design, it's an accidental breaking change, as projects previously depended on the visibility of the Construct layer that HTML objects belong to.

This is fixed for visibility only in the next beta, but unfortunately that leaves the way HTML layer properties are handled as being inconsistent - the opacity or interactivity setting of the layer the HTML object is on is ignored, but the visibility setting is used, unless the layer is a HTML layer. I think that's just a quirk we have to live with for backwards compatibility, as probably lots of projects already depend on layer visibility working like it did.
