### ISSUE TITLE
Crash When Right Click Menu - View - Bars

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8303]
## Problem description

Right-click any item multiple times in Menu - View - Bars will Crash 

<img width="486" alt="Snipaste_2024-10-30_20-25-43" src="https://github.com/user-attachments/assets/5a668d75-745f-461f-9da1-29a162ad8a01">

<img width="509" alt="Snipaste_2024-10-30_20-26-00" src="https://github.com/user-attachments/assets/3a1d35f9-4473-4cd8-86cc-7a8bac1a41fd">

## Steps to reproduce
1. Add or Open a Project
2. Click Menu - View - Bars
3. Right-click any item multiple times

## Observed result

Crash 

## Expected result

no Crash 

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
