### ISSUE TITLE
Editor in Mobile: iOS 18 Safari can not close dialog

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8305]
## Problem description

On iOS 18.1 Safari, Some **close buttons** do not respond after clicking.

(The result is the same open in the browser or added C3 to the home page)

But it works fine in chrome iOS.

## Attach a .c3p

N/A

## Steps to reproduce

1. Example Browser: **Filter** close button
![image](https://github.com/user-attachments/assets/dad8161c-5946-48ad-a952-58be5131df25)

2.Example Browser: Example **Card Image** close button
![image](https://github.com/user-attachments/assets/594707f0-e909-4719-99a0-2f7fb7778b5c)

3.OPEN - FILE: No response （But menu - OPEN can works）
![image](https://github.com/user-attachments/assets/bc09966c-7416-4617-aba6-3e0b44e9fc13)

## Observed result

Click the close button, no response.

If long press, another menu will pop up with 2 close options. Click on any of the options to close. (Although it seems that there is no difference between these two option)

## Expected result

The close button works fine

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>
Platform information
Product: Construct 3 r407.2 (stable)
Browser: Safari 18.1
Browser engine: WebKit
Context: webapp
Operating system: iOS 18.1
Device type: mobile
Device pixel ratio: 3
Logical CPU cores: 4
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (iPhone; CPU iPhone OS 18_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Mobile/15E148 Safari/604.1
Language setting: en-US

Local storage
Storage quota (approx): 38 gb
Storage usage (approx): 28 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

UI effects are disabled in settings.
Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_render_shared_exponent
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
</details>

**Comment by AshleyScirra** [comment]
This should be fixed in the next beta.
