### ISSUE TITLE
Array/Dictionary files should be hidden the "Import map Purpose" properties

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8307]
## Problem description

C3 array and dictionary files also use the .json format, and the properties of Purpose are displayed in the property. But it doesn't actually work here.

![image](https://github.com/user-attachments/assets/112ea768-05d2-4e2e-ba74-9833e4191feb)

## Attach a .c3p

https://editor.construct.net/beta/#open=import-maps

## Steps to reproduce

1. New Array or Dictionary files in Files folder.
2. check properties.

## Observed result

it doesn't actually work here.

## Expected result

like check .json whether the data editor can be displayed, do not display Purpose properties in C3 array and dictionary files.

```
{ "c2dictionary": true, "data": {} }
{ "c2array":true,"size":[],"data":[] }
```

## By the way

Hopefully Array, Dictionary, JSON objects can also be add a Purpose properties to quick imports `c2dictionary` and `c2array` files on object created. https://github.com/Scirra/Construct-feature-requests/issues/116

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
