### ISSUE TITLE
r413 - Error when exporting with mignifier

### ISSUE THREAD

**Issue by DinoSystem** [Scirra/Construct-bugs#8308]
When exporting using the mignifier, it interrupts and this message appears:

Error: Build failed with 2 errors:
file-map:scripts/c3runtime.js:2206:9: ERROR: The symbol "n5" has already been declared
file-map:scripts/c3runtime.js:2207:9: ERROR: The symbol "n5" has already been declared

C3 version: r413, worked fine with previous releases

**Comment by AshleyScirra** [comment]
No project was provided and I can't reproduce with either a new empty project or 'Spell caster' using either simple or advanced debug mode. Please always follow the bug report guidelines every time - we really need that information to be able to help.
