### ISSUE TITLE
SDK v2 - Exception Cannot read properties of null (reading 'GetLayer') after layout restarts using drawingPlugin

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8311]
## Problem description

SDK v2 Drawing plugin crashes when trying to read the layer property after the layout restarts. When using the sample plugin "drawingPlugin" I started ticking and access the layer property, but the sdk throws an exception.

## Attach a .c3p
Addon: [drawingPlugin addon - Layer error.zip](https://github.com/user-attachments/files/17612064/drawingPlugin.addon.-.Layer.error.zip)
Project: [drawing-layer error.zip](https://github.com/user-attachments/files/17612074/drawing-layer.error.zip)

## Steps to reproduce

1. Install the attached addon
2. Open the attached project and run it. The dev console will display "Running on layer:" per tick.
3. While running it, press R to restart the layout
4. Find the exception in the devconsole.

## Observed result

An exception is thrown, crashing the addon.

## Expected result

Should not throw an exception.

## More details

r407.2 stable
r413 beta

## System details

<details><summary>View details</summary>

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'GetILayer')
    at get layer (IWorldInstance.js:1:1043)
    at DrawingInstance._tick (instance.js:24:41)
    at e.#tickFunc.#tickFunc (ISDKInstanceBase.js:1:1845)
    at C3.Event.Handler._FireNonCancellable (handler.js:1:2186)
    at C3.Event.Dispatcher.dispatchEvent (dispatcher.js:1:978)
    at C3.Runtime.Step_AfterPreTick (runtime.js:1:39931)
    at C3.Runtime.Tick (runtime.js:1:37989)
    at normal (runtime.js:1:3114)

</details>

**Comment by AshleyScirra** [comment]
The problem is the runtime is still trying to tick a destroyed instance. This is fixed for the next beta, but you can also work around it in the current release by calling `this._setTicking(true);` in the `_release()` method.
