### ISSUE TITLE
SDK v2 - Child _postCreate method is not called before parent's On Created event triggers

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8312]
## Problem description

When creating a hierarchy of objects, the children object's state is incomplete, thus the final property values and overall state of hierarchy is inconsistent. 

I have very complex addons that rely on the _postCreate method to complete its initialization, however the method for children objects is not called before the parent's On Created event triggers, leading to an incomplete/inconsistent state of the children at the moment the On Created event is called.

The attached project has a hierarchy of two objects: parent and child. Both objects use the sampleBullet behavior. 
![image](https://github.com/user-attachments/assets/10196301-b341-4545-a857-37ae3604e30d)

At the moment the On Created method is trigger for the parent "green" object, I assume the child should be already fully initialized. To test this, the _postCreate method changes arbitrarly the speed of the bullet to 50. The object's final state should have the speed set to 50.

However, when I access the children to retrieve its speed at the On Created event of the parent's, the speed is still 100. I logged the speed in the devconsole.

![image](https://github.com/user-attachments/assets/018ba992-176a-49fa-867f-6e0aece576d3)

## Attach a .c3p

Addon:  [basicBullet - OnCreated incomplete state.zip](https://github.com/user-attachments/files/17612143/basicBullet.-.OnCreated.incomplete.state.zip)
Project: [OnCreated event - postCreate not called.zip](https://github.com/user-attachments/files/17612146/OnCreated.event.-.postCreate.not.called.zip)

## Steps to reproduce

1. Install the attached behavior and open the project provided.
2. Run the project and open the dev console
3. At the moment the event On Created is triggered for the parent object, their children have not completed their initialization yet. The method _postCreate for all their children haven't been called at this point.
4. The state of the hierarchy is inconsistent because the children are not in their final state.

## Observed result

_postCreate method for the children in a hierarchy hasn't been called at the moment the parent triggers the On Created event.

## Expected result

Child objects should have a complete state, their _postCreate method should have already been called before the On Created of the parent's is triggered.

## More details

r413 beta
r407.2 stable

## System details

No exception is thrown, but the child objects are not fully initialized. See attached projects.

**Comment by AshleyScirra** [comment]
This is currently by design, and it's part of how Construct has always worked rather than being anything specific to SDK v2. When creating a hierarchy it calls `_postCreate()` and triggers 'On created' for each instance in turn from the top of the hierarchy to the bottom - so in this case the sequence will be:

1. Green behavior _postCreate()
2. Green trigger 'On created'
3. Red behavior _postCreate()
4. Red behavior 'On created'

This is currently by design (and applies to both SDK v1 and v2), and it does mean that if you set up an event to pick a child in green's 'On created' and run some action, it can be overwritten by changes in a child's _postCreate(). This is just a consequence of the current design and not necessarily a bug, though. This is a difficult problem in general - 'On created' is difficult to use correctly in cases like this because it is in fact called part-way through initialization. Even if the order above was rearranged, there are still difficult cases depending on sequencing: 'On created' must be called in some order and there will be other edge cases where something done in 'On created' can be reverted by 'On created' triggered for something else in the hierarchy, and likewise for _postCreate().

The best solution is probably to have some kind of additional trigger only fired after all the above steps are complete, e.g. 'On hierarchy created' and a corresponding SDK call. However this would be a feature request and would need to be thought through carefully, as there could still be difficult dependency issues between the order in which 'On hierarchy created' is run (if it applies to children too), as well as addons depending on each other being initialized if multiple addons use the corresponding SDK method. Initialization is surprisingly complicated! I don't think there is any obvious "just do X and it always works" approach.

What might be more pragmatic is just to work around it. In 'On start of layout', all hierarchies are fully created and all initialization triggers and methods will have already run - so if you run an action there, everything is ready. Similarly if you use a 'Create object' action, all the initialization triggers and methods are run inside that action, and so in the following action everything is ready. So some kind of initialization action would probably be a straightforward workaround. Alternatively it may be possible to do lazy initialization or end-of-tick initialization automatically. It depends on your specific use case.

**Comment by sotano42** [comment]
@AshleyScirra One of the main problems that I believe causes this is the fact that the Instance is not destroyed but reused. That pushed me to rely on the _postCreate rather than in the constructor. You could re-assess this.

The problem is that at On Created the hierarchy is inconsistent, thus I could never rely on full initialization for hierarchies, and I will have to always work around it, which seems odd for an engine. 

A solution suggestion: You could probably initialize the objects by creating them first all completely, and then calling the OnCreated event from the bottom most to the top-most objects in the scenegraph, to make sure when you reach the top-most parent, all its children are ready. I would imagine this is complicated, but I believe it's necessary. Otherwise, hierarchies will always be unreliable.

For instance, I'm creating a dialog window and a button, which is child of the dialog. I want to access the button to set its text at the OnCreated event, but it's not fully ready. This will be a very common use case when creating UIs, it should work.

**Comment by AshleyScirra** [comment]
> One of the main problems that I believe causes this is the fact that the Instance is not destroyed but reused

IIRC that relates to savegames, which wasn't used in this report?

> You could probably initialize the objects by creating them first all completely, and then calling the OnCreated event from the bottom most to the top-most objects in the scenegraph

That's likely a breaking change to existing projects, so is not something we can easily do.

As I mentioned 'On created' is fundamentally going to be mid-way through initialization so is probably never going to be suitable for initializing hierarchies. For example even with your suggestion, someone could file an issue very much like this one, but using 'Red: On created - pick parent', which could be broken for the same reason but in the opposite direction. A different solution is needed, and I covered some potential approaches in my previous comment.

**Comment by sotano42** [comment]
>> One of the main problems that I believe causes this is the fact that the Instance is not destroyed but reused
>IIRC that relates to savegames, which wasn't used in this report?

Yes, it's related to the bug I reported some weeks ago #8261 which you said it's also the way construct works. I still believe the instance should be disposed completely, instead of reused. The use of _postCreate is a consequence of construct reusing instances, that's why I couldn't rely on the constructor which I think should had been the correct option.

> As I mentioned 'On created' is fundamentally going to be mid-way through initialization so is probably never going to be suitable for initializing hierarchies. For example even with your suggestion, someone could file an issue very much like this one, but using 'Red: On created - pick parent', which could be broken for the same reason but in the opposite direction. A different solution is needed, and I covered some potential approaches in my previous comment.

In this scenario considering you implement my suggestions, if you go on any direction on the hierarchy to trigger the OnCreated events it should work, because you've ran the full object initialization for the whole hierarchy at this point. Even if it's mid-way it will still work, because the initialization order is the scenegraph tree, going from the bottom-most to the top-most. The key here is to respect the order set by the scenegraph. So my idea is to hold the OnCreated triggers until you fully initialize the hierarchy. Once it's fully initialized, you go over each object respecting the scenegraph order. 

![image](https://github.com/user-attachments/assets/2314cf33-7ff4-42e6-88d2-0886793d2592)

Like in the image above, you should go over the scenegraph tree and when you reach a node that has no children, you save a reference pointing to that instance for later triggering the OnCreate. Then, you move to the upper node to continue processing the tree. In the image above, your initialization order should be: **D,E,B,F,G,C,A.** 

This will keep all the projects of older versions with no impacts, and will improve the initialization for the hierarchies, because the OnCreated method will still be called but at the right moment. Because OnCreated is usually the starting point of everything for that object, I don't think there's going to be an impact for existing projects.

**Comment by F3der1co** [comment]
little side note, Godot has the scene graph at the core of the engine and so also has to tackle issues like this.
They have `_enter_tree()` that runs when a node is created and `_ready()` which runs when all child nodes have been created.
And `_ready()` is used almost always used over "_enter_tree()` when writing your games code.

**Comment by sotano42** [comment]
> little side note, Godot has the scene graph at the core of the engine and so also has to tackle issues like this. They have `_enter_tree()` that runs when a node is created and `_ready()` which runs after all child nodes have been created. And `_ready()` is almost always used instead of `_enter_tree()` when writing your games code, as that state is a lot more useful as often initialization logic requires accessing children.

Agreem, it's defintelly tackled by all the engines out-there, it should be solved here too from my point of view. I'm really hopping that Ashley can fix this, otherwise hierarchies will never be reliable for picking instances. It's already a problem because sometimes you have to add a small wait to be able to pick the instance in its final state.

**Comment by AshleyScirra** [comment]
I don't think this qualifies as a bug, because everything is working as designed - if you want new features to make it easier, there may well be a good case for that, but bug reports aren't the place for that discussion, so I'd suggest posting it as a feature request.

**Comment by sotano42** [comment]
> I don't think this qualifies as a bug, because everything is working as designed - if you want new features to make it easier, there may well be a good case for that, but bug reports aren't the place for that discussion, so I'd suggest posting it as a feature request.

I don't agree this is a construct "feature", because it's clearly an inconsistent behavior when creating hierarchies that needs to be solved. It is not to make it easier, but to make it work. Better integrations with tools like spriter and spine that will rely heavily in hierarchies may not work either. 

I've found several problems in the current architecture of construct that may held back other devs from creating more complex addons and I'm taking the time to report them because I use a lot construct and want it to be stable for my own interests of course. I don't understand why this flaws should not be attended. Solving these problems will make the sdk v2 more stable in the long run which I believe is what you wanted to pursue.

I can create a feature request, but it's basically a trash can. Requests can sit there for months and nobody review that. I rose one for the SDK v2 that no one looked at, what's the point?. It's just a polite way to dismiss it.

**Comment by AshleyScirra** [comment]
I agree there should be something added to Construct to improve this, but that does not make it a bug. If we accept such cases as bugs, then the bug report platform will fill up with feature requests that people are reporting as bugs, and then there is no more separation of these things, and it will become much harder to do our jobs. Please go ahead and file a feature request and post the link to it here, and I will see if it can be prioritised for the next release cycle.

**Comment by sotano42** [comment]
@AshleyScirra I appreciate your willingness to review it. I've just logged a feature request here:
https://github.com/Scirra/Construct-feature-requests/issues/393
