### ISSUE TITLE
Physics behavior doesn't behaves correctly when timescale for object is changed

### ISSUE THREAD

**Issue by sotano42** [Scirra/Construct-bugs#8313]
## Problem description

If you change the time-scale for a specific object that uses the physics behavior, the object still runs at runtime time-scale.

## Attach a .c3p

Project: [set-object-time-scale Error.zip](https://github.com/user-attachments/files/17622729/set-object-time-scale.Error.zip)

## Steps to reproduce

1. Open and run the attached project
2. Press space to set impulse in the ball
3. Press "A" key to change the object time-scale to zero
4. Object still runs at normal time-scale

## Observed result

Set Object Time-Scale doesn't work for Physics behavior

## Expected result

Time-scale should affect object 

## More details

r407.2 stable
r413 beta

## System details

No exception thrown, it just fails to change the time-scale.

**Comment by F3der1co** [comment]
all physics simulation needs to step at once to properly resolve afaik, as one object needs to be able to affect other objects in a predictable way. Still it's odd how there isn't a separate physics timescale.
(could be added as an additional factor, so would be backwards compatible `timescale * physicsTimescale`)

**Comment by AshleyScirra** [comment]
I'm afraid the Physics engine steps the entire world with a single delta-time value, so it is not possible to implement per-object timescales with Physics. I suspect all physics engines probably work the same way too - after all they are designed to model the real world, and in the real world things cannot normally move with different time scales, and so there are no realistic physical results that can be simulated for that. So it's just not something that is supported.
