### ISSUE TITLE
Crash when Importing Frames from Strip

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-bugs#8315]
## Problem description

After importing frames from strip in the Image Editor Construct crashes.
When I tested it does that only if the "Replace entire animation" box is checked.

## Steps to reproduce

1. Double-CLick on a sprite.
2. Import frames from Strip, select the image and Click Open.
3. Check "Replace entire animation" --> Click Import

## Observed result

Crash

## Expected result

Images are imported

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
