### ISSUE TITLE
Dark theme bug: Event sheet suddenly turns blinding white

### ISSUE THREAD

**Issue by alastajj** [Scirra/Construct-bugs#8316]
## Problem description

Dark theme tends to be a lot easier on the eyes, but when selecting things in the Event sheet, it suddenly flashes white, which goes against the purpose of the theme.

This is especially problematic when you click on a group which contains many events or comments inside of it, because they'll all be selected, which causes a lot of white to suddenly flash in your face.

![flashbang](https://github.com/user-attachments/assets/ea284b45-8a74-4b79-ac74-c40583be2db4)

## Attach a .c3p

[darkthemeBug.zip](https://github.com/user-attachments/files/17673402/darkthemeBug.zip)

## Steps to reproduce

1. Click event sheet
2. Select anything (e.g. Cntrl + A, will select everything)

## Observed result

Flashbang.

Before selecting:

![image](https://github.com/user-attachments/assets/3fb55edf-824a-49ce-a679-acaa413d5645)

After selecting:

![image](https://github.com/user-attachments/assets/7ebec736-f6a4-4d8f-9dd1-f8311ea9b998)

## Expected result

A darker selecting color.

**Comment by AshleyScirra** [comment]
Closing as this is already [filed as a feature request](https://github.com/Scirra/Construct-feature-requests/issues/61).

**Comment by alastajj** [comment]
@AshleyScirra  Mr @DiegoScirra requested it be open

**Comment by DiegoScirra** [comment]
I didn't remember this was already in a feature request. As long as it's already in one of our main trackers it should be ok.
