### ISSUE TITLE
Html element is shown before layout starts & disappears before layout ends

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#8321]
Html element (for example a text input in a non html layer) is shown before the start of the next layout and disappears faster than the other elements when layout ends.

[HtmlElement.zip](https://github.com/user-attachments/files/17723948/HtmlElement.zip)

## Steps to reproduce

1. Run Project in fullscreen
2. Change layout

## Observed result

https://github.com/user-attachments/assets/9e4e90c7-4167-4133-bc84-a671e7ec79e9

## Expected result

Text input to start & end at the same time with all other elements in layout.

## More details

Look how text input blends with the previous layout because it is shown before next layout starts.
![1](https://github.com/user-attachments/assets/8bc9a12f-d9ee-4cf3-9206-f737fbf886a7)

And here you can see text input missing at the end of layout
![2](https://github.com/user-attachments/assets/ea36c1a9-22fe-410c-bfee-55753b48f555)

Chrome, Windows

**First affected release:** I don't know, i think it is along time ago

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r415 (beta)
Browser: Chrome 130.0.6723.117
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.7 gb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M (0x00000A68) Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by AshleyScirra** [comment]
I find it hard to spot the delay here - I think it's one frame (~16ms) which you have to be watching very carefully to spot. The provided project does enable worker mode, and I think in that case as the rendering is running independently of DOM rendering, it is not currently possible to guarantee they update exactly simultaneously. This is noted in the [HTML layers](https://www.construct.net/en/make-games/manuals/construct-3/tips-and-guides/html-layers) section of the manual, which notes "Browsers do not always update canvas elements and other HTML elements at the same time."

I think it's better with worker mode turned off, in which case rendering and DOM updates are synchronized, so that may be a possible workaround. Other than that though this looks to me like a minor issue which is likely infeasible to fix, so closing as wontfix.
