### ISSUE TITLE
Condition "Is on-screen" inverted, is not working

### ISSUE THREAD

**Issue by Dramamini** [Scirra/Construct-bugs#8322]
I use "Is on-screen" to identify if an object is on layout. But if I invert "is on screen" condition,  to see if an object is missing, it is not working. Am I using it in a wrong way?

[IsOnScreenBug.zip](https://github.com/user-attachments/files/17724060/IsOnScreenBug.zip)

## Steps to reproduce

1. Create an object
2. "is on screen" is working
3. Destroy the object

## Observed result

https://github.com/user-attachments/assets/4f5369d8-1064-4be4-a4e5-5b2c81e1b3fd

## Expected result

Inverted is on screen to work. To identify that the object is missing.

## More details

Chrome, Windows

**First affected release:** Don't know

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r415 (beta)
Browser: Chrome 130.0.6723.117
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 4
Approx. device memory: 4 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
Language setting: en-US

Local storage
Storage quota (approx): 559 gb
Storage usage (approx): 1.7 gb (0.3%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Nothing is missing. Everything is OK!
WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce G105M (0x00000A68) Direct3D11 vs_4_1 ps_4_1, D3D11)
Major performance caveat: no
Maximum texture size: 8192
Point size range: 1 to 1024
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_depth_clamp
EXT_disjoint_timer_query_webgl2
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 2
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

WebM Opus (audio/webm;codecs=opus)
MPEG-4 Opus (audio/mp4;codecs=opus)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

WebM AV1 (video/webm;codecs=av01.0.00M.08)
WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
WebM H.264 (video/webm;codecs=avc1.420034)
MPEG-4 AV1 (video/mp4;codecs=av01.0.00M.08)
MPEG-4 VP9 (video/mp4;codecs=vp9)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by avishaymizrav** [comment]
Is on-screen needs to pick instances to validate, even for inverted conditions.
Once you destroy the only remaining instance both events will not run anymore.
You can simply use ELSE on the Is on-screen event, since no instances are picked in the first event, the else will be triggered instead.

**Comment by AshleyScirra** [comment]
This is not a bug. All conditions implicitly test if objects that exist meet the condition. In other words 'Is on screen' means 'Does any instance that exists have a position inside the viewport'. When you invert that it changes the meaning to 'Does any instance that exists *not* have a position inside the viewport'.

In other words if no instance exists the question about whether it is inside or outside the viewport is not valid to ask, so the condition is always false no matter whether it is inverted.
