### ISSUE TITLE
bug on moving events

### ISSUE THREAD

**Issue by luckyrawatfreax** [Scirra/Construct-bugs#8326]
## Problem description
I'm trying to move a group of event under another group which

## Attach a .c3p
[drag events issue.zip](https://github.com/user-attachments/files/17815120/drag.events.issue.zip)

## Steps to reproduce

1. open attached file
2. move "old group" inside "new group"

## Observed result

![image](https://github.com/user-attachments/assets/219b0c3e-4af7-45e4-b892-4a6b21ee0de7)

## Expected result
that group should move inside another group

## More details

variable "temp" is inside "old group"

![image](https://github.com/user-attachments/assets/7a83f11e-6e9f-4d28-a715-052d8754b998)

**Affected browsers/platforms:** 
Windows / Chrome

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This looks like the same issue as #6760.
