### ISSUE TITLE
Sprite scale is changed when reordering frames

### ISSUE THREAD

**Issue by anty21ro** [Scirra/Construct-bugs#8331]
## Problem description

When you reorder the frames from a sprite that has the scale different of 100%, and the other instances also have the scale different of 100%, too, all of them will get back to 100% scale.

Here's a video:

https://github.com/user-attachments/assets/817c252a-77f9-4d57-bd52-5933d3733a3e

## Steps to reproduce

1. Create a sprite with at least 2 frames.
2. Duplicate the sprite so that you have more instanced of it in a layout.
3. Change the X/Y scale of each sprite so that is different than 100%.
4. Open the image editor and reorder the frames than close it.

## Observed result

X/Y scale changes to 100%.

## Expected result

X/Y scale should not change.

## More details

This is not the only time the scale of the sprites is changed.
I noticed sometimes if the instances of the sprite have different "Initial frame", the same thing can happen like I described above if you reorder a frame of a sprite that has the scale of 100%. 

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>
[SpriteFrameChangedBug.zip](https://github.com/user-attachments/files/17853532/SpriteFrameChangedBug.zip)

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
