### ISSUE TITLE
Attempting to clone certain object types causes crash

### ISSUE THREAD

**Issue by jakemay74** [Scirra/Construct-bugs#8338]
## Problem description

Attempting to clone a sprite object from Project Bar > Object Types by right clicking on the object and selecting clone causes a crash.
Attempting to clone a sprite object from the Layout view fails without crashing but displays the following warning:
"Some items were not pasted. Not all the copied items could be pasted to this project. Check all the names and requirements (e.g. instance variables) match."

## Attach a .c3p
[C3CloneBug02.zip](https://github.com/user-attachments/files/17934964/C3CloneBug02.zip)

## Steps to reproduce

1. Create a new project using the default settings.
2. Add a sprite object to the layout with fill colour, keeping all other settings to default.
3. Add a tiled background to the layout with fill colour, keeping all other settings to default.
4. Add a text object to the layout, keeping all settings to default
5. Right-click on the sprite in the layout view and select "Clone object type". Observe the fail message.
6. Right-click on the sprite in the project window and select "Clone". project crashes
7. Repeat the above but exclude step 3, to confirm that trying to clone from the layout view isn't the cause of the problem.
8. Restart the project.
9. Right-click on the tiled background in the layout view and select "Clone object type". Project crashes.
10. Restart the project.
11. Right-click on the tiled background in the project window and select "Clone". Project crashes.
12. Restart the project.
13. Right-click the text object in the layout view and select "Clone object". Object is cloned successfully.
13. Right-click the text object in the project window and select "Clone object". Object is cloned successfully.

## Observed result

Attempting to clone a sprite from the layout view fails without a crash.
Attempting to clone a sprite from the project window results in a crash.
Attempting to clone a tiled background in either view causes a crash.
Text objects clone successfully in both views.

## Expected result

Sprite and Tiled background objects should clone successfully without crashing the project.

## More details
Haven't tested any other objects, might happen with those too.

Tested in Chrome, only noticed it happening with the latest beta release (r417) but it might have been happening earlier.

## System details

Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of undefined (reading 'json') @ TypeError: Cannot read properties of undefined (reading 'json') at d.adc (https://editor.construct.net/r417/projectResources.js:1995:107) at d.Aa (https://editor.construct.net/r417/projectResources.js:792:506) at ktb.bwb (https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:134:169) at https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:23:138 at https://editor.construct.net/r417/main.js:1925:414
Stack: TypeError: Cannot read properties of undefined (reading 'json') at d.adc (https://editor.construct.net/r417/projectResources.js:1995:107) at d.Aa (https://editor.construct.net/r417/projectResources.js:792:506) at ktb.bwb (https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:134:169) at https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:23:138 at https://editor.construct.net/r417/main.js:1925:414
Construct version: r417
URL: https://editor.construct.net/r417/
Date: Wed Nov 27 2024 13:19:46 GMT+0000 (Greenwich Mean Time)
Uptime: 19.4 s

Platform information
Product: Construct 3 r417 (beta)
Browser: Chrome 131.0.6778.86
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x000046A3) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

**Comment by AshleyScirra** [comment]
@DiegoScirra - I think this is related to your recent changes.

Please note: don't include how you made the project in steps to reproduce. In this case the steps to reproduce are:

1. Open project
2. Right-click the large yellow square in the Layout View (Sprite)
3. Choose 'Clone object type'
4. Click to place the clone

**Comment by Rhindon** [comment]
This may have already been confirmed earlier, but I didn't see it identified here in this post.
Not only is it sprites, but also 3D objects. SpriteFonts, Tilemaps, Shadowlight, and TiledBackground. Pretty much any object in the Project window that can be cloned.

The following is the crash report that I received, just in case it provides unique information that might be helpful:

> Error report information
> Type: unhandled rejection
> Reason: Error: Cannot read properties of undefined (reading 'json') @ TypeError: Cannot read properties of undefined (reading 'json') at d.adc (https://editor.construct.net/r417/projectResources.js:1995:107) at d.Aa (https://editor.construct.net/r417/projectResources.js:792:506) at ktb.bwb (https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:134:169) at https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:23:138 at https://editor.construct.net/r417/main.js:1925:414
> Stack: TypeError: Cannot read properties of undefined (reading 'json') at d.adc (https://editor.construct.net/r417/projectResources.js:1995:107) at d.Aa (https://editor.construct.net/r417/projectResources.js:792:506) at ktb.bwb (https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:134:169) at https://editor.construct.net/r417/components/bars/projectBar/projectBar.js:23:138 at https://editor.construct.net/r417/main.js:1925:414
> Construct version: r417
> URL: https://editor.construct.net/r417/
> Date: Wed Nov 27 2024 21:48:19 GMT-0600 (Central Standard Time)
> Uptime: 39871.3 s
> 
> Platform information
> Product: Construct 3 r417 (beta)
> Browser: Chrome 131.0.6778.86
> Browser engine: Chromium
> Context: webapp
> Operating system: Windows 11
> Device type: desktop
> Device pixel ratio: 1.5
> Logical CPU cores: 16
> Approx. device memory: 8 GB
> User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
> Language setting: en-US
> 
> WebGL information
> Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
> Numeric version: 2
> Supports NPOT textures: yes
> Supports GPU profiling: no
> Supports highp precision: yes
> Vendor: Google Inc. (Intel)
> Renderer: ANGLE (Intel, Intel(R) UHD Graphics (0x00009BC4) Direct3D11 vs_5_0 ps_5_0, D3D11)
> Major performance caveat: no
> Maximum texture size: 16384
> Point size range: 1 to 1024
> Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_draw_instanced_base_vertex_base_instance, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_multi_draw_instanced_base_vertex_base_instance, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_shader_pixel_local_storage, WEBGL_stencil_texturing

**Comment by RevRico** [comment]
Error report information
Type: unhandled rejection
Reason: Error: Cannot read properties of null (reading 'eka') @ TypeError: Cannot read properties of null (reading 'eka') at d.Ph (https://editor.construct.net/r417/projectResources.js:852:9) at d.Ri (https://editor.construct.net/r417/projectResources.js:652:6) at d.Ri (https://editor.construct.net/r417/projectResources.js:850:319) at d.Ri (https://editor.construct.net/r417/projectResources.js:768:203) at d.Ca (https://editor.construct.net/r417/projectResources.js:651:396) at d.Ca (https://editor.construct.net/r417/projectResources.js:748:219) at https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:65 at fkb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:172) at window.qn.ywb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:149:510) at Hmb.Uc (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:285:502)
Stack: TypeError: Cannot read properties of null (reading 'eka') at d.Ph (https://editor.construct.net/r417/projectResources.js:852:9) at d.Ri (https://editor.construct.net/r417/projectResources.js:652:6) at d.Ri (https://editor.construct.net/r417/projectResources.js:850:319) at d.Ri (https://editor.construct.net/r417/projectResources.js:768:203) at d.Ca (https://editor.construct.net/r417/projectResources.js:651:396) at d.Ca (https://editor.construct.net/r417/projectResources.js:748:219) at https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:65 at fkb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:44:172) at window.qn.ywb (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:149:510) at Hmb.Uc (https://editor.construct.net/r417/components/editors/layoutView/layoutView.js:285:502)
Construct version: r417
URL: https://editor.construct.net/r417/
Date: Thu Nov 28 2024 10:52:14 GMT-0400 (GMT-04:00)
Uptime: 16.9 s

Platform information
Product: Construct 3 r417 (beta)
Browser: Edge 131.0.2903.70
Browser engine: Chromium
Context: webapp
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 12
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (NVIDIA)
Renderer: ANGLE (NVIDIA, NVIDIA GeForce GTX 1650 (0x00002188) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
