### ISSUE TITLE
Image/Animation editor - Cannot save the current image to a directory

### ISSUE THREAD

**Issue by Kashin-Ginn** [Scirra/Construct-bugs#8344]
## Problem description

 Cannot save a sprite using the save button in the editor

## Steps to reproduce

1. Create a sprite
2. Open its editor
3. Save image

## Observed result

A menu is shown saying d.Pd is not a function

## Expected result

 It should show me the directory where I want to save the image

## More details

**Affected browsers/platforms:** 

**First affected release:** 
Issue on r417 & r418
Works on r416

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta, was introduced in r417.
