### ISSUE TITLE
"Set cursor to none" and "Request pointer lock" not work on webview2 r418

### ISSUE THREAD

**Issue by xinlanjun** [Scirra/Construct-bugs#8345]
"Set cursor to none" and "Request pointer lock" not work on webview2 ，The gamepad doesn't work too(It works fine in preview mode)
r418

**Comment by AshleyScirra** [comment]
This looks like a bug in WebView2 in the new mode. I've reported it here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/4968
