### ISSUE TITLE
SDK V2 c3 typedef for  getObjectClassBySid

### ISSUE THREAD

**Issue by MikalDev** [Scirra/Construct-bugs#8346]
## Attach a .c3p
Not project related

## Steps to reproduce
Set up typescript for a default C3 V2 addon (C3 create ts-defs dir in addon dir) and run tsc: watch in Code

## Observed result
src/ts-defs/runtime/ISDKUtils.d.ts:15:22 - error TS7006: Parameter 'sid' implicitly has an 'any' type.

15  getObjectClassBySid(sid): IObjectClass<IInstance>;

I expect no type errors
## More details
Fix is probably:
	getObjectClassBySid(sid:number): IObjectClass<IInstance>;

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, fixed for next beta.
