### ISSUE TITLE
WindowsIconUpdater.exe broken again

### ISSUE THREAD

**Issue by BluePinStudio** [Scirra/Construct-bugs#8349]
## Problem description

WindowsIconUpdater.exe issues an error when attempting to use it. This is happening latest Stable and Beta branches.

## Attach a .c3p

Don't need a c3p

## Steps to reproduce

1. Make a webview build and attempt to use WindowsIconUpdater.exe

## Observed result

Error appears

## Expected result

No error and icon is changed

**Comment by AshleyScirra** [comment]
No project was provided so I exported 'Spell caster' in r418 with the Windows WebView2 export, extracted all the files, and ran WindowsIconUpdater.exe, and it worked fine.

Please always follow the full bug report guidelines and provide detailed information such as the exact text of any error messages you saw. It is impossible to further investigate when these details are missing from your report.

**Comment by BluePinStudio** [comment]
> No project was provided so I exported 'Spell caster' in r418 with the Windows WebView2 export, extracted all the files, and ran WindowsIconUpdater.exe, and it worked fine.
> 
> Please always follow the full bug report guidelines and provide detailed information such as the exact text of any error messages you saw. It is impossible to further investigate when these details are missing from your report.

The error code i get is "Failed to find or update any executible file icons. Check the folder structure is correct. (Try running this tool immediately after extracting an export, since Construct exports with the expected folder structure.) Also check that you write access to the executable files."

You're right it doesn't happen in the example projects but its happening in my project for some reason. I have all the default icons in the icon folder, i just changed the artwork while retaining the same file structure. 

I tried to find more repro steps, such as disabling asset packaging or switching to stable and it still happens. Sorry I can't provide any further details. Perhaps its just an edge case and we can all forget about it.

**Comment by AshleyScirra** [comment]
Are you sure you extracted all files before running it? If so it must be something different about your project. I could further investigate if you can share a project reproducing the problem, but otherwise there isn't anything further we can do, so closing this issue - feel free to file another issue if you can reproduce.
