### ISSUE TITLE
[Documentation] iRenderer: drawMesh() and setBlendMode() aren't documented in manual

### ISSUE THREAD

**Issue by OverboyDev** [Scirra/Construct-bugs#8350]
## Problem description

iRenderer: drawMesh() and setBlendMode() aren't documented in manual
while it was introduced in r393 https://www.construct.net/fr/make-games/releases/beta/r393

IRenderer script interface manual : https://www.construct.net/en/make-games/manuals/construct-3/scripting/scripting-reference/graphics-interfaces/irenderer-interface

## Steps to reproduce

1.
2.
3.

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Thanks, not sure how I missed those. Updated the documentation to cover them.
