### ISSUE TITLE
add/edit family dialog does not focus field

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8351]
## Problem description
the add/edit family dialog does not focus a field by default

## Attach a .c3p
irrelevant

## Steps to reproduce

1. open the add or edit family dialog
2. try typing, pressing enter, directions etc.

## Observed result
nothing happens. We first need to select a field 

## Expected result
I would expect a similar situation like most other dialogs, like the add action dialog for example, where the search field is selected and/or the first element in the list is selected

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
You can tab focus through different fields, but I think it does make sense to start focus on the search field, so changed that for the next beta.

**Comment by F3der1co** [comment]
thanks for the change! 
I can change focus with tab, but it didn't select an element in the grid view meaning I need to click an element to then change selecting with the arrow keys for example
