### ISSUE TITLE
Game sound and music disappear after minimising the browser on iPhone 16 Pro with iOS 18.1

### ISSUE THREAD

**Issue by GameDev00-00** [Scirra/Construct-bugs#8353]
The sound and music in my game disappear after minimising the browser and then resuming the game.

## Steps to reproduce

1. Launch the game.
2. Enter the main menu or action phase.
3. Make sure the sound and music are playing.
4. Minimise the browser.
5. Reopen the browser and resume the game.
6. Observe that the sound and music are gone.

## Expected result

**Affected browsers/platforms:** 

**First affected release:** 

* This problem occurs on iPhone 16 pro with firmware 18.1
* This issue does not occur on iPhone 8 with firmware 15.4.1 and iPhone 8 plus with firmware 16.7.2

<details><summary>View details</summary>

https://github.com/user-attachments/assets/72b2a365-a8de-4288-bf56-e9f21209a768

</details>

**Comment by AshleyScirra** [comment]
Please provide a project that demonstrates the issue, as per the bug report guidelines.

**Comment by AshleyScirra** [comment]
Issue has been open for a week with no response so closing.
