### ISSUE TITLE
don't use hypotenuse in distanceTo3D() function

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8355]
## Problem description
A lot of time is spend here and Math.hypot() is slow. Please calculate the distance using square root instead.

## Attach a .c3p
[distanceTo3d.zip](https://github.com/user-attachments/files/18110978/distanceTo3d.zip)

## Steps to reproduce
profile

## Observed result
![image](https://github.com/user-attachments/assets/89287a40-ca7f-4b2b-9cd0-8760273bd8ee)
time is spend in distanceTo3d()

## Expected result
better perf with Math.sqrt()
https://jsbm.dev/f1kc9y6XWL7Mg

## More details
sorry for reports like these, but I really want 3d shape perf to be better as their drawcalls are the main performance bottleneck in a live game (majority of cpu usage is spend on drawCalls). So I am trying everything I can and this seems like an easy win unless there is a reason hypotenuse is needed here.

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
Performance is a minefield: unfortunately the benchmark you linked to is worthless, as it is basically all dead code, and so the optimizer could just delete the calculation for either of the tests as it doesn't affect the way the code runs, and you wouldn't know it did that, and then you get an extraordinary good score and get misled in to thinking it is much more efficient.

The benchmark you linked to appeared to show Math.sqrt() being 8-9x faster, but with my own carefully written benchmark to avoid optimizers deleting or hoisting calculations, it's more like ~2x in Chrome: [sqrt-hypot-perftest.zip](https://github.com/user-attachments/files/18128311/sqrt-hypot-perftest.zip) So I would assume something like dead code elimination significantly distorted the other benchmark.
Then this calculation is a pretty small part of the 3D shape code being run, so it doesn't represent a major overhead. Just to throw in another complication, profilers can be hit-and-miss and inaccurately attribute time spent, so you have to treat them with some skepticism.

I was still surprised the performance difference is that big between Math.sqrt() and Math.hypot() - I'd have assumed Math.hypot() would have actually been faster, as it handles more of the calculation with a built-in method. I've changed Construct for the next release to use Math.sqrt() where I think it's performance-sensitive, including with 3D shape. In your benchmark it seems to gain about 10% performance, so it's hardly a huge transformation, but worth doing I suppose.

Ideally all browsers would have Math.hypot() as fast as Math.sqrt() - there's [this existing V8 issue](https://issues.chromium.org/issues/42203737) for Chrome, and I also filed a [Firefox issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1937103) and [Safari issue](https://bugs.webkit.org/show_bug.cgi?id=284631) as both of those appear to be affected to. Hopefully that gets fixed and then we'll delete our workaround (and who knows, it might even be faster that way in the end).

**Comment by F3der1co** [comment]
Thank a lot for doing the change, 10% perf improvement does sound really good to me!
I'll try to be more thorough with my benchmark if I make similar reports in the future. 
I also initially did the benchmark by having the random in each iteration, but then I assumed the smaller difference was caused by now a good chunk of the time spend on random() making the relative difference of sqrt() vs hypot() seem smaller than it is in reality. But yea it's difficult with benchmarks like this, it's easier if the change can be made in engine so the actual real case can be tested.

**Comment by AshleyScirra** [comment]
The calls to Math.random() do add overhead, but they are necessary to avoid the optimizer hoisting expressions. For example if the test does this:

```js
function SqrtTest()
{
	const dx = Math.random();
	const dy = Math.random();
	const dz = Math.random();

	let sum = 0;
	for (let i = 0; i < ITERATIONS; ++i)
	{
		sum += Math.sqrt(dx * dx + dy * dy + dz * dz);
	}
	return sum;
}
```

Then an optimizer can quite reasonably identify that `dx * dx + dy * dy + dz * dz` does not change in the loop and effectively rewrite the code to do this:

```js
function SqrtTest()
{
	const dx = Math.random();
	const dy = Math.random();
	const dz = Math.random();
	const param = dx * dx + dy * dy + dz * dz;

	let sum = 0;
	for (let i = 0; i < ITERATIONS; ++i)
	{
		sum += Math.sqrt(param);
	}
	return sum;
}
```

This is guaranteed to work the same - but now the test has silently been changed from measuring the overhead of calculating the parameter repeatedly to calculating it just once. If that happens for one test but not another, then it produces misleading results. This is also why my tests accumulate a sum and return it, and then log it to the console - otherwise the optimizer could quite reasonably determine the code does nothing, and delete it all, and then you're measuring running nothing.

You have to be really, really careful with benchmarks to avoid this - people fall in to these traps all the time and produce nonsense benchmark figures (and then sometimes try to promote the results on social media, and then get embarrassed by how wrong they were!)
