### ISSUE TITLE
r420: Crash when import file into Animations Picker

### ISSUE THREAD

**Issue by XHXIAIEIN** [Scirra/Construct-bugs#8360]
## Problem description

![Snipaste_2024-12-17_22-20-35](https://github.com/user-attachments/assets/fe91839b-efeb-4fa9-b2c3-f6c9f92297df)

## Attach a .c3p

https://editor.construct.net/r420/

## Steps to reproduce

1. Add a Sprite Object

2. drop a image file into Animations editor - Animations bar

3. impot from sprite sheet
> @AshleyScirra , this option width is so small. Please increase the width appropriately. Make it so that it does not wrap.

![image](https://github.com/user-attachments/assets/3025caa5-6187-4ebb-9f8b-d4c01ab2c708)

## Observed result

crash

## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

Error report information
Type: unhandled rejection
Reason: Error: element does not correspond to any part of the editor @ Error: element does not correspond to any part of the editor at NL.g.K.LU.BCb (https://editor.construct.net/r420/projectResources.js:2808:210) at feb.JBb.Ba (https://editor.construct.net/r420/projectResources.js:2944:20) at NL.g.K.LU.TC (https://editor.construct.net/r420/projectResources.js:2807:166) at NL.g.K.LU.R (https://editor.construct.net/r420/projectResources.js:2804:243) at Bz.dxb.KZa (https://editor.construct.net/r420/projectResources.js:2760:458) at async hfb.ud (https://editor.construct.net/r420/projectResources.js:3118:127)
Stack: Error: element does not correspond to any part of the editor at NL.g.K.LU.BCb (https://editor.construct.net/r420/projectResources.js:2808:210) at feb.JBb.Ba (https://editor.construct.net/r420/projectResources.js:2944:20) at NL.g.K.LU.TC (https://editor.construct.net/r420/projectResources.js:2807:166) at NL.g.K.LU.R (https://editor.construct.net/r420/projectResources.js:2804:243) at Bz.dxb.KZa (https://editor.construct.net/r420/projectResources.js:2760:458) at async hfb.ud (https://editor.construct.net/r420/projectResources.js:3118:127)
Construct version: r420
URL: https://editor.construct.net/r420/
Date: Tue Dec 17 2024 22:23:19 GMT+0800 (中国标准时间)
Uptime: 36.3 s

Platform information
Product: Construct 3 r420 (beta)
Browser: Chrome 131.0.6778.140
Browser engine: Chromium
Context: browser
Operating system: Windows 11
Device type: desktop
Device pixel ratio: 1
Logical CPU cores: 8
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (Intel)
Renderer: ANGLE (Intel, Intel(R) Iris(R) Xe Graphics (0x00009A49) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

</details>

**Comment by DiegoScirra** [comment]
Will be fixed in the next release, we might make a patch release for this since it prevents the feature from being tried out.
