### ISSUE TITLE
Array, sorting along y sorts each collumns elements

### ISSUE THREAD

**Issue by F3der1co** [Scirra/Construct-bugs#8362]
## Problem description
Sorting an array along the x axis sorts it in a way where the collumns stay intact. Sorting along the y axis sorts each collumns elements, scrambling the rows.
Is this a bug or a feature? At least the documentation makes it sound like a bug.
![image](https://github.com/user-attachments/assets/602b9e70-7736-4439-925d-addc16c848d3)

## Attach a .c3p
[sortYAxis.zip](https://github.com/user-attachments/files/18187912/sortYAxis.zip)

## Steps to reproduce

1. preview 
2. check console

## Observed result
each collumns elements are sorted, rows are scrambled because of it

1, five
5, one
second collumn is sorted too (alphabetically)

## Expected result
rows stay intact (like sorting along x but flipped)

only (0, i) is sorted, and rows are moved with the sorted first element of the row

1, one
5, five
## More details

**Affected browsers/platforms:** 

**First affected release:** 

## System details

<details><summary>View details</summary>

PASTE HERE

</details>

**Comment by AshleyScirra** [comment]
This is a bit of a complicated issue: the way the existing sort was coded looked reasonable, but mixed up the sort modes. Really there are two ways to sort a 2D array on each axis: X separately, X by column, Y separately, and Y by row. The existing X sort was by column, and the existing Y sort was separately, as a side effect of the way it was coded. There was no way to sort Y by row, but also no way to sort X separately (so each row sorts its items individually). This appears to be an old design mistake. Fixing it is complicated by the fact existing projects may depend on the current behavior.

So to fix this I've replaced the sort action for the next beta with five sort modes: X by column, X separately, Y by row, Y separately, and Z (separately only). The old action is deprecated so existing projects keep working the same, but newly added actions can choose these new modes. With the new action the Y by row mode does what you want. While I was at it, I also made it handle tie breakers when sorting by column/row by looking at the rest of the array - so now you can properly sort 2D arrays on either axis either preserving columns and rows or separately.

**Comment by F3der1co** [comment]
amazing, ty!
