### ISSUE TITLE
Tilemap bug - invalid tiles being created when editing tilemap image

### ISSUE THREAD

**Issue by AndreYin** [Scirra/Construct-bugs#8364]
## Problem description
Editing a tilemap image makes it so where you had erased tiles before become invalid tiles. 
If you run the game, or save the project and reload it, then the invalid tiles show as one of the newly added tiles? But trying to select them by using shift+right click doesn't work.

## Attach a .c3p

https://1drv.ms/u/s!AuQM7MihYyx4tcMFegf7E_5E-xXRag?e=CA5Ai6

## Steps to reproduce

1. Create a new project and add a tilemap to it
2. Draw around using any tile, select some tiles to create a stamp by using shift + left mouse click, use right mouse click to erase around an area
3. Double click the tilemap to edit the image and change its height (using the Align Top-Left option so the previous tiles keep their ID intact)

## Observed result

The previously erased tiles become invalid tiles

## Expected result

Editing the tilemap image should not do this

## More details

Video showing it happening: https://streamable.com/5o9f6n

(The invalid tiles might show as red tiles - try editing the tilemap image again and they'll become invisible)

**Affected browsers/platforms: all**

**Comment by DiegoScirra** [comment]
This will be fixed in the next beta. After resizing the source image, all tiles with indexes that fall outside the maximum allowed for the new image size will be set as empty tiles.
