### ISSUE TITLE
flowchart crash after duplication

### ISSUE THREAD

**Issue by Ldwebster111** [Scirra/Construct-bugs#8368]
## Problem description

Flowcharts crash after duplicating them and changing the start node. This can be recreated on any of the example projects

![flowchart crash](https://github.com/user-attachments/assets/2ab593d4-c7cf-4471-b3ca-489b2b6f6a3e)

## Steps to reproduce

1. Duplicate a flowchart (copy paste also works)
2. go to the copied flowchart and try changing the start node

## Observed result

Program crashes

## More details

Error report information
Type: unhandled exception
File: https://editor.construct.net/r416-2/main.js, line 1105, col 65
Message: Uncaught TypeError: Cannot read properties of undefined (reading 'lO')
Stack: TypeError: Cannot read properties of undefined (reading 'lO') at new f8a.Iub (https://editor.construct.net/r416-2/projectResources.js:2170:313) at ya.j (https://editor.construct.net/r416-2/main.js:1105:44) at Oq.g.J.Oub.Oo (https://editor.construct.net/r416-2/components/bars/propertiesBar/propertiesBar.js:62:270) at Oq.g.J.Oub.Jq (https://editor.construct.net/r416-2/main.js:1556:496) at Oq.g.J.Oub.nK (https://editor.construct.net/r416-2/main.js:1557:50) at HTMLInputElement.mv (https://editor.construct.net/r416-2/main.js:1554:429)
Construct version: r416.2
URL: https://editor.construct.net/
Date: Sun Dec 22 2024 20:58:47 GMT+1100 (Australian Eastern Daylight Time)
Uptime: 36.8 s

Platform information
Product: Construct 3 r416.2 (stable)
Browser: Chrome 131.0.6778.205
Browser engine: Chromium
Context: webapp
Operating system: Windows 10
Device type: desktop
Device pixel ratio: 1.5
Logical CPU cores: 16
Approx. device memory: 8 GB
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
Language setting: en-US

WebGL information
Version string: WebGL 2.0 (OpenGL ES 3.0 Chromium)
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Google Inc. (AMD)
Renderer: ANGLE (AMD, AMD Radeon RX 6700 XT (0x000073DF) Direct3D11 vs_5_0 ps_5_0, D3D11)
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 1024
Extensions: EXT_clip_control, EXT_color_buffer_float, EXT_color_buffer_half_float, EXT_conservative_depth, EXT_depth_clamp, EXT_disjoint_timer_query_webgl2, EXT_float_blend, EXT_polygon_offset_clamp, EXT_render_snorm, EXT_texture_compression_bptc, EXT_texture_compression_rgtc, EXT_texture_filter_anisotropic, EXT_texture_mirror_clamp_to_edge, EXT_texture_norm16, KHR_parallel_shader_compile, NV_shader_noperspective_interpolation, OES_draw_buffers_indexed, OES_sample_variables, OES_shader_multisample_interpolation, OES_texture_float_linear, OVR_multiview2, WEBGL_blend_func_extended, WEBGL_clip_cull_distance, WEBGL_compressed_texture_s3tc, WEBGL_compressed_texture_s3tc_srgb, WEBGL_debug_renderer_info, WEBGL_debug_shaders, WEBGL_lose_context, WEBGL_multi_draw, WEBGL_polygon_mode, WEBGL_provoking_vertex, WEBGL_stencil_texturing

**Comment by DiegoScirra** [comment]
Will be fixed in the next beta.
