### ISSUE TITLE
Game is Freezing

### ISSUE THREAD

**Issue by ironhide1975** [Scirra/Construct-bugs#8369]
## Problem description

Start the game, and proceed right walking with your character. After a few seconds, the game will freeze.

## Attach a .c3p

https://www.dropbox.com/scl/fi/2u9e9gm4tfj4awijaimf6/Transformers.c3p.zip?rlkey=24ltxo2mylfj6f9dqft0wus9e&st=y2kobliy&dl=0

## Steps to reproduce

1. Load Game
2. Load Level 1 
3. Run Scene
4. Move right by pressing 'D', use mouse click to fire or punch.
5. After you reach Ravage the game will freeze,

## Observed result

Game freezes

## Expected result

Game should not freeze.

## More details

Safari...

**Affected browsers/platforms:** 

416.2

## System details

<details><summary>View details</summary>

Platform information
Product: Construct 3 r416.2 (stable)
Browser: Safari 18.2
Browser engine: WebKit
Context: browser
Operating system: macOS 10.15.7
Device type: desktop
Device pixel ratio: 2
Logical CPU cores: 8
Approx. device memory: (unavailable)
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.2 Safari/605.1.15
Language setting: en-US

Local storage
Storage quota (approx): 77 gb
Storage usage (approx): 65 mb (0.1%)
Persistant storage: No

Browser support notes
This list contains missing features that are not required, but could improve performance or user experience if supported.

Idle callbacks are not supported. Background loading performance may be degraded.
Determining input device capabilities is not supported.
WebGL information
Version string: WebGL 2.0
Numeric version: 2
Supports NPOT textures: yes
Supports GPU profiling: no
Supports highp precision: yes
Vendor: Apple Inc.
Renderer: Apple GPU
Major performance caveat: no
Maximum texture size: 16384
Point size range: 1 to 511
Extensions:

EXT_clip_control
EXT_color_buffer_float
EXT_color_buffer_half_float
EXT_conservative_depth
EXT_depth_clamp
EXT_float_blend
EXT_polygon_offset_clamp
EXT_render_snorm
EXT_texture_compression_bptc
EXT_texture_compression_rgtc
EXT_texture_filter_anisotropic
EXT_texture_mirror_clamp_to_edge
EXT_texture_norm16
KHR_parallel_shader_compile
NV_shader_noperspective_interpolation
OES_draw_buffers_indexed
OES_sample_variables
OES_shader_multisample_interpolation
OES_texture_float_linear
WEBGL_blend_func_extended
WEBGL_clip_cull_distance
WEBGL_compressed_texture_astc
WEBGL_compressed_texture_etc
WEBGL_compressed_texture_etc1
WEBGL_compressed_texture_pvrtc
WEBKIT_WEBGL_compressed_texture_pvrtc
WEBGL_compressed_texture_s3tc
WEBGL_compressed_texture_s3tc_srgb
WEBGL_debug_renderer_info
WEBGL_debug_shaders
WEBGL_lose_context
WEBGL_multi_draw
WEBGL_polygon_mode
WEBGL_provoking_vertex
WEBGL_render_shared_exponent
WEBGL_stencil_texturing
Audio information
System sample rate: 48000 Hz
Output channels: 6
Output interpretation: speakers
Supported decode formats:

WebM Opus (audio/webm;codecs=opus)
WebM Vorbis (audio/webm;codecs=vorbis)
MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
MP3 (audio/mpeg)
FLAC (audio/flac)
PCM WAV (audio/wav;codecs=1)
Supported encode formats:

MPEG-4 AAC (audio/mp4;codecs=mp4a.40.2)
Video information
Supported decode formats:

WebM VP9 (video/webm;codecs=vp9)
WebM VP8 (video/webm;codecs=vp8)
MPEG-4 H.264 (video/mp4;codecs=avc1.420034)
Supported encode formats:

MPEG-4 H.264 (video/mp4;codecs=avc1.420034)

</details>

**Comment by DiegoScirra** [comment]
I tried opening the project and it seems to work properly, was able to go all the way to the end of the first level.

**Comment by ironhide1975** [comment]
It had something to do with the indentation of the Laserbeak code. Once I moved that out it resolved.

**Comment by DiegoScirra** [comment]
Closing.
